(function (global) {
  'use strict';

  // N3 questions (format: listening-data.js). As in the real N3 test, 問題1
  // and 問題2 have printed choices (phrase) instead of pictures, 概要理解
  // asks for the point of a whole talk, and the speakers talk faster.
  const add = global.LISTENING_ADD;
  const p = (ja, en) => ({ type: 'phrase', ja, en });
  const r = (ja, en, say) => (say ? { ja, en, say } : { ja, en });
  const M = 'M', F = 'F';
  const l = (who, ja, en, say) => (say ? { who, ja, en, say } : { who, ja, en });

  add('kadai', [
    { id: 'n3-report-graph', level: 'N3',
      intro: '大学[だいがく]で 先生[せんせい]と 男[おとこ]の 学生[がくせい]が 話[はな]しています。男[おとこ]の 学生[がくせい]は この 後[あと] まず 何[なに]を しますか。',
      voices: { M: 'young' },
      lines: [
        l(M, '先生[せんせい]、レポートを 見[み]て いただけましたか。', 'Professor, did you get a chance to look at my report?'),
        l(F, 'ええ。内容[ないよう]は よく 書[か]けて いますよ。参考[さんこう]にした 本[ほん]も ちゃんと 書[か]いて ありますね。', 'Yes. The content is well written, and you listed the books you referred to properly.'),
        l(F, 'ただ、この グラフが 見[み]にくいですね。数字[すうじ]が 小[ちい]さすぎて 読[よ]めません。', 'But this graph is hard to read. The numbers are too small.'),
        l(M, 'わかりました。字数[じすう]は 足[た]りて いますか。', 'I see. Is it long enough?'),
        l(F, '字数[じすう]は 大丈夫[だいじょうぶ]です。まず そこを 直[なお]して、もう 一度[いちど] 出[だ]して ください。', 'The length is fine. Fix that first and hand it in again.'),
      ],
      choices: [p('参考[さんこう]にした 本[ほん]を 書[か]き足[た]す', 'Add the books he referred to'), p('グラフを 作[つく]り直[なお]す', 'Redo the graph'), p('レポートを 長[なが]く する', 'Make the report longer'), p('内容[ないよう]を 書[か]き直[なお]す', 'Rewrite the content')],
      answer: 1, why: 'Content, sources and length are fine; the graph is hard to read, so he redoes it first.' },
    { id: 'n3-meeting-room', level: 'N3',
      intro: '会社[かいしゃ]で 女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は この 後[あと] まず 何[なに]を しますか。',
      lines: [
        l(F, '明日[あした]の 会議[かいぎ]の 準備[じゅんび]、どう なってる？', 'How are the preparations for tomorrow’s meeting going?'),
        l(M, '資料[しりょう]の コピーは もう 終[お]わりました。', 'I’ve already finished copying the documents.'),
        l(F, 'ありがとう。会議室[かいぎしつ]の 予約[よやく]は？', 'Thanks. What about booking the meeting room?'),
        l(M, 'あ、まだです。プロジェクターも 借[か]りないと いけませんね。', 'Oh, not yet. We need to borrow a projector too.'),
        l(F, 'プロジェクターは 会議室[かいぎしつ]に ある はずよ。部屋[へや]が 取[と]れないと 困[こま]るから、すぐ 予約[よやく]して。', 'There should be a projector in the meeting room. We’re stuck if we can’t get a room, so book it right away.'),
      ],
      choices: [p('資料[しりょう]を コピーする', 'Copy the documents'), p('プロジェクターを 借[か]りる', 'Borrow a projector'), p('部長[ぶちょう]に 連絡[れんらく]する', 'Contact the manager'), p('会議室[かいぎしつ]を 予約[よやく]する', 'Book the meeting room')],
      answer: 3, why: 'The copies are done and the room should have a projector; booking the room comes first (すぐ予約して).' },
    { id: 'n3-library-card', level: 'N3',
      intro: '図書館[としょかん]で 男[おとこ]の人[ひと]と 図書館[としょかん]の 人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は この 後[あと] まず 何[なに]を しますか。',
      lines: [
        l(M, 'すみません、本[ほん]を 借[か]りたいんですが、カードを 持[も]って いないんです。', 'Excuse me, I’d like to borrow a book, but I don’t have a card.'),
        l(F, 'では、カードを お作[つく]りしますね。住所[じゅうしょ]の わかる もの、例[たと]えば 免許証[めんきょしょう]は お持[も]ちですか。', 'Then let’s make you one. Do you have something with your address on it, a driving licence for example?'),
        l(M, 'はい、あります。', 'Yes, I do.'),
        l(F, 'では、まず こちらの 申込書[もうしこみしょ]に お名前[なまえ]と ご住所[じゅうしょ]を 書[か]いて ください。書[か]き終[お]わったら、免許証[めんきょしょう]と 一緒[いっしょ]に 出[だ]して くださいね。', 'Then first write your name and address on this form. When you’ve finished, hand it in with your licence.'),
      ],
      choices: [p('免許証[めんきょしょう]を 取[と]りに 帰[かえ]る', 'Go home for his licence'), p('申込書[もうしこみしょ]に 書[か]く', 'Fill in the form'), p('写真[しゃしん]を 撮[と]る', 'Have a photo taken'), p('借[か]りる 本[ほん]を 選[えら]ぶ', 'Choose the books to borrow')],
      answer: 1, why: 'He has his licence with him; まず申込書に書いてください — the form comes first.' },
    { id: 'n3-party-plates', level: 'N3',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が パーティーの 準備[じゅんび]に ついて 話[はな]しています。女[おんな]の人[ひと]は 何[なに]を 買[か]いに 行[い]きますか。',
      lines: [
        l(M, '飲[の]み物[もの]は 田中[たなか]さんが 持[も]って 来[き]て くれる ことに なったよ。', 'It’s been settled that Tanaka-san will bring the drinks.'),
        l(F, 'よかった。料理[りょうり]は もう 店[みせ]に 頼[たの]んで あるし…。', 'Good. And the food is already ordered from the restaurant…'),
        l(M, 'ケーキは どう する？', 'What shall we do about a cake?'),
        l(F, 'ケーキは 鈴木[すずき]さんが 作[つく]るって。あ、でも 紙[かみ]の お皿[さら]と コップが 足[た]りないかも。私[わたし]、買[か]って くるね。', 'Suzuki-san says she’ll make one. Oh, but we might not have enough paper plates and cups. I’ll go and buy some.'),
      ],
      choices: [p('飲[の]み物[もの]', 'Drinks'), p('料理[りょうり]', 'Food'), p('ケーキ', 'A cake'), p('紙[かみ]の 皿[さら]と コップ', 'Paper plates and cups')],
      answer: 3, why: 'Drinks, food and cake are all covered; she goes for paper plates and cups.' },
    { id: 'n3-clinic-first', level: 'N3',
      intro: '病院[びょういん]の 受付[うけつけ]で 女[おんな]の人[ひと]と 受付[うけつけ]の 人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は まず 何[なに]を しますか。',
      lines: [
        l(F, 'すみません、こちらは 初[はじ]めてなんですが。', 'Excuse me, this is my first time here.'),
        l(M, 'では、こちらの 紙[かみ]に 今日[きょう]の 具合[ぐあい]を 書[か]いて いただきます。', 'Then I’ll ask you to describe how you feel today on this sheet.'),
        l(M, 'でも、その 前[まえ]に 保険証[ほけんしょう]を 見[み]せて いただけますか。体温[たいおん]は 書[か]き終[お]わってから 測[はか]りますので。', 'But before that, may I see your health insurance card? We’ll take your temperature after you’ve filled it in.'),
      ],
      choices: [p('保険証[ほけんしょう]を 見[み]せる', 'Show her insurance card'), p('紙[かみ]に 具合[ぐあい]を 書[か]く', 'Describe her symptoms on the sheet'), p('体温[たいおん]を 測[はか]る', 'Take her temperature'), p('名前[なまえ]が 呼[よ]ばれるまで 待[ま]つ', 'Wait until her name is called')],
      answer: 0, why: 'その前に保険証を — the insurance card comes before the sheet and the temperature.' },
    { id: 'n3-hotel-today', level: 'N3',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 旅行[りょこう]の 準備[じゅんび]に ついて 話[はな]しています。女[おんな]の人[ひと]は 今日[きょう] 何[なに]を しますか。',
      lines: [
        l(M, '新幹線[しんかんせん]の 切符[きっぷ]は もう 買[か]った？', 'Have you bought the shinkansen tickets yet?'),
        l(F, 'ううん、切符[きっぷ]は 来週[らいしゅう] 会社[かいしゃ]の 近[ちか]くで 買[か]う つもり。', 'No, I’m planning to buy them near work next week.'),
        l(M, 'ホテルは？ 連休[れんきゅう]だから、早[はや]く しないと いっぱいに なるよ。', 'And the hotel? It’s a long weekend, so if you don’t hurry it’ll be full.'),
        l(F, 'そうね。じゃあ、今日[きょう]中[じゅう]に 予約[よやく]しとく。お土産[みやげ]は 向[む]こうで 探[さが]せば いいし。', 'True. Then I’ll book it today. Souvenirs I can look for when I’m there.'),
      ],
      choices: [p('新幹線[しんかんせん]の 切符[きっぷ]を 買[か]う', 'Buy the shinkansen tickets'), p('ホテルを 予約[よやく]する', 'Book the hotel'), p('お土産[みやげ]を 買[か]う', 'Buy souvenirs'), p('会社[かいしゃ]を 休[やす]む 連絡[れんらく]を する', 'Tell work she’ll be off')],
      answer: 1, why: 'Tickets next week, souvenirs when she’s there; the hotel today (今日中に予約) before it fills up.' },
    { id: 'n3-club-join', level: 'N3',
      intro: '大学[だいがく]で 男[おとこ]の 学生[がくせい]と 女[おんな]の 学生[がくせい]が 話[はな]しています。女[おんな]の 学生[がくせい]は この 後[あと] 何[なに]を しますか。',
      voices: { M: 'young', F: 'young' },
      lines: [
        l(F, '写真部[しゃしんぶ]に 入[はい]りたいんだけど、どう すれば いいの？', 'I want to join the photography club. What do I have to do?'),
        l(M, '申込書[もうしこみしょ]を 部長[ぶちょう]に 出[だ]せば いいよ。会費[かいひ]は 来月[らいげつ]で いいから。', 'Just hand the form to the club leader. You can pay the fee next month.'),
        l(F, '部長[ぶちょう]って、どこに いるの？', 'Where’s the leader?'),
        l(M, '今日[きょう]は 授業[じゅぎょう]で 来[こ]られないんだ。でも、四時[よじ]から 部室[ぶしつ]で 説明会[せつめいかい]が あるから、まず それに 出[で]て みたら？ 申込書[もうしこみしょ]は その 後[あと]で いいよ。', 'He can’t come today because of class. But there’s an information session in the club room from four, so why not go to that first? The form can wait until after.'),
        l(F, 'うん、そう する。', 'OK, I’ll do that.'),
      ],
      choices: [p('申込書[もうしこみしょ]を 出[だ]す', 'Hand in the form'), p('会費[かいひ]を 払[はら]う', 'Pay the fee'), p('説明会[せつめいかい]に 出[で]る', 'Go to the information session'), p('部長[ぶちょう]に 電話[でんわ]する', 'Phone the club leader')],
      answer: 2, why: 'The leader isn’t in today, so first the information session; the form after, the fee next month.' },
    { id: 'n3-moving-oversize', level: 'N3',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 引[ひ]っ越[こ]しに ついて 話[はな]しています。男[おとこ]の人[ひと]は 今週中[こんしゅうちゅう]に 何[なに]を しますか。',
      lines: [
        l(F, '電気[でんき]と ガスの 連絡[れんらく]は した？', 'Have you contacted the electricity and gas companies?'),
        l(M, 'うん、それは 昨日[きのう] 済[す]ませた。', 'Yes, I did that yesterday.'),
        l(F, '住所[じゅうしょ]の 変更[へんこう]は？', 'And the change of address?'),
        l(M, 'それは 引[ひ]っ越[こ]した 後[あと]じゃないと できないんだ。', 'I can’t do that until after the move.'),
        l(F, 'じゃあ、古[ふる]い ソファーは？ 大[おお]きい ごみは 一週間[いっしゅうかん] 前[まえ]までに 申[もう]し込[こ]まないと いけないのよ。', 'What about the old sofa? For big rubbish you have to apply at least a week ahead.'),
        l(M, 'あ、そうか。じゃあ、今週中[こんしゅうちゅう]に 申[もう]し込[こ]んで おくよ。', 'Oh, right. Then I’ll apply this week.'),
      ],
      choices: [p('電気[でんき]と ガスの 会社[かいしゃ]に 連絡[れんらく]する', 'Contact the electricity and gas companies'), p('住所[じゅうしょ]の 変更[へんこう]を する', 'Change his address'), p('大[おお]きい ごみの 申[もう]し込[こ]みを する', 'Apply for big-rubbish collection'), p('新[あたら]しい ソファーを 買[か]う', 'Buy a new sofa')],
      answer: 2, why: 'Utilities are done, the address change waits until after; the sofa needs a big-rubbish application a week ahead.' },
    { id: 'n3-bike-shop', level: 'N3',
      intro: '自転車屋[じてんしゃや]で 女[おんな]の人[ひと]と 店[みせ]の 人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は この 後[あと] どう しますか。',
      lines: [
        l(F, 'すみません、後[うし]ろの タイヤが すぐ 柔[やわ]らかく なって しまうんです。', 'Excuse me, my back tyre keeps going soft.'),
        l(M, 'ちょっと 見[み]せて ください。…ああ、穴[あな]は 開[あ]いて いませんね。空気[くうき]を 入[い]れる ところが 緩[ゆる]んで いるだけです。', 'Let me see… Ah, there’s no hole. The valve is just loose.'),
        l(F, 'タイヤを 換[か]えなくても いいんですか。', 'So I don’t need a new tyre?'),
        l(M, 'ええ、締[し]めて 空気[くうき]を 入[い]れれば 大丈夫[だいじょうぶ]です。五分[ごふん]で できますよ。', 'No, if I tighten it and pump it up, it’ll be fine. It takes five minutes.'),
        l(F, 'じゃあ、お願[ねが]いします。', 'Then please do that.'),
      ],
      choices: [p('タイヤを 新[あたら]しく する', 'Get a new tyre'), p('自転車[じてんしゃ]を 預[あず]けて 帰[かえ]る', 'Leave the bike and go home'), p('空気[くうき]を 入[い]れて もらう', 'Have the valve tightened and the tyre pumped up'), p('新[あたら]しい 自転車[じてんしゃ]を 買[か]う', 'Buy a new bike')],
      answer: 2, why: 'No hole, just a loose valve: he tightens it and pumps it up in five minutes.' },
    { id: 'n3-cooking-class', level: 'N3',
      intro: '料理[りょうり]教室[きょうしつ]で 先生[せんせい]が 話[はな]しています。生徒[せいと]は 最初[さいしょ]に 何[なに]を しますか。',
      lines: [
        l(F, '皆[みな]さん、今日[きょう]は 野菜[やさい]の スープを 作[つく]ります。材料[ざいりょう]は テーブルの 上[うえ]に 用意[ようい]して あります。', 'Everyone, today we’re making vegetable soup. The ingredients are ready on the tables.'),
        l(F, 'エプロンを まだ して いない 人[ひと]も いますが、それは 後[あと]で かまいません。', 'Some of you haven’t put on aprons yet, but that can wait.'),
        l(F, '野菜[やさい]を 洗[あら]ったり 切[き]ったり する 前[まえ]に、まず 石[せっ]けんで よく 手[て]を 洗[あら]って ください。', 'Before washing or cutting the vegetables, first wash your hands well with soap.'),
      ],
      choices: [p('エプロンを する', 'Put on an apron'), p('野菜[やさい]を 洗[あら]う', 'Wash the vegetables'), p('手[て]を 洗[あら]う', 'Wash their hands'), p('材料[ざいりょう]を 用意[ようい]する', 'Get the ingredients ready')],
      answer: 2, why: 'まずよく手を洗ってください — hands first; aprons later, the ingredients are already out.' },
    { id: 'n3-email-subject', level: 'N3',
      intro: '会社[かいしゃ]で 男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は この 後[あと] まず 何[なに]を しますか。',
      lines: [
        l(F, '課長[かちょう]、お客様[きゃくさま]への メール、これで 送[おく]っても いいでしょうか。', 'Section chief, is this email to the client OK to send?'),
        l(M, 'どれどれ。…宛先[あてさき]は 合[あ]って いるね。内容[ないよう]も いいと 思[おも]う。', 'Let’s see… The address is right. The content is fine too.'),
        l(M, 'でも、件名[けんめい]が 入[はい]って いないよ。それを 書[か]いてから 送[おく]って。添付[てんぷ]の 資料[しりょう]は 明日[あした]でも いいから。', 'But there’s no subject. Add that and then send it. The attachment can go tomorrow.'),
      ],
      choices: [p('宛先[あてさき]を 確[たし]かめる', 'Check the address'), p('件名[けんめい]を 書[か]く', 'Write a subject line'), p('内容[ないよう]を 書[か]き直[なお]す', 'Rewrite the content'), p('資料[しりょう]を 添付[てんぷ]する', 'Attach the documents')],
      answer: 1, why: 'Address and content are fine; the subject (件名) is missing. The attachment can wait.' },
    { id: 'n3-presentation', level: 'N3',
      intro: '大学[だいがく]で 女[おんな]の 学生[がくせい]と 男[おとこ]の 学生[がくせい]が 話[はな]しています。男[おとこ]の 学生[がくせい]は 今日[きょう] 何[なに]を しますか。',
      voices: { M: 'young', F: 'young' },
      lines: [
        l(F, '発表[はっぴょう]の 準備[じゅんび]、進[すす]んでる？', 'How’s the presentation coming along?'),
        l(M, 'スライドは もう できたよ。練習[れんしゅう]は 明日[あした] みんなで する ことに なってる。', 'The slides are done. We’re all rehearsing tomorrow.'),
        l(F, '配[くば]る 資料[しりょう]は？', 'What about the handouts?'),
        l(M, 'あ、それ、まだ 印刷[いんさつ]して ない。明日[あした]は 朝[あさ]から 練習[れんしゅう]だから、今日[きょう] やって おかないと。', 'Oh, I haven’t printed those yet. We rehearse from the morning tomorrow, so I’d better do it today.'),
      ],
      choices: [p('スライドを 作[つく]る', 'Make the slides'), p('発表[はっぴょう]の 練習[れんしゅう]を する', 'Rehearse the presentation'), p('配[くば]る 資料[しりょう]を 印刷[いんさつ]する', 'Print the handouts'), p('先生[せんせい]に 相談[そうだん]する', 'Talk to the professor')],
      answer: 2, why: 'The slides are done and the rehearsal is tomorrow; today he prints the handouts.' },
  ]);

  add('point', [
    { id: 'n3-late-report', level: 'N3',
      intro: '先生[せんせい]と 女[おんな]の 学生[がくせい]が 話[はな]しています。女[おんな]の 学生[がくせい]は どうして レポートを 出[だ]すのが 遅[おく]れましたか。',
      voices: { F: 'young' },
      lines: [
        l(M, 'レポート、締[し]め切[き]りは 昨日[きのう]でしたよ。', 'The deadline for the report was yesterday.'),
        l(F, 'すみません。風邪[かぜ]を ひいた わけではないんです。パソコンが 急[きゅう]に 動[うご]かなく なって、書[か]いた データが 全部[ぜんぶ] 消[き]えて しまったんです。', 'I’m sorry. It’s not that I caught a cold. My computer suddenly stopped working and all the data I’d written disappeared.'),
        l(M, 'それは 大変[たいへん]でしたね。じゃあ、今回[こんかい]だけは 受[う]け取[と]りましょう。', 'That must have been hard. All right, I’ll accept it, just this once.'),
      ],
      choices: [p('風邪[かぜ]を ひいたから', 'She caught a cold'), p('データが 消[き]えて しまったから', 'Her data was lost'), p('締[し]め切[き]りを 間違[まちが]えたから', 'She got the deadline wrong'), p('アルバイトが 忙[いそが]しかったから', 'Her part-time job was busy')],
      answer: 1, why: '風邪をひいたわけではない — not a cold; the computer broke and the data was lost.' },
    { id: 'n3-quit-tennis', level: 'N3',
      intro: '男[おとこ]の 学生[がくせい]と 女[おんな]の 学生[がくせい]が 話[はな]しています。男[おとこ]の 学生[がくせい]は どうして テニス部[ぶ]を やめましたか。',
      voices: { M: 'young', F: 'young' },
      lines: [
        l(F, 'テニス部[ぶ]、やめたんだって？ 練習[れんしゅう]が 厳[きび]しいから？', 'I heard you quit the tennis club. Because practice was too tough?'),
        l(M, 'いや、練習[れんしゅう]は 大変[たいへん]だったけど、楽[たの]しかったよ。', 'No, practice was hard, but fun.'),
        l(M, '実[じつ]は 来月[らいげつ]から 留学[りゅうがく]する ことに なったんだ。それで 準備[じゅんび]で 忙[いそが]しくて。', 'Actually, it’s been decided I’m going abroad to study next month. So I’m busy getting ready.'),
        l(F, 'へえ、すごいね。', 'Wow, that’s great.'),
      ],
      choices: [p('練習[れんしゅう]が 厳[きび]しかったから', 'Practice was too tough'), p('けがを したから', 'He got injured'), p('留学[りゅうがく]の 準備[じゅんび]が あるから', 'He has to prepare to study abroad'), p('アルバイトを 始[はじ]めたから', 'He started a part-time job')],
      answer: 2, why: 'Practice was hard but fun; he’s going abroad next month (留学することになった).' },
    { id: 'n3-trip-hard', level: 'N3',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 旅行[りょこう]に ついて 話[はな]しています。男[おとこ]の人[ひと]は 旅行[りょこう]で 何[なに]が 一番[いちばん] 大変[たいへん]だったと 言[い]って いますか。',
      lines: [
        l(F, '週末[しゅうまつ]の 旅行[りょこう]、雨[あめ]で 大変[たいへん]だったでしょう。', 'Your weekend trip must have been awful with the rain.'),
        l(M, '雨[あめ]は 一日目[いちにちめ]だけだったから、それほどでも なかったよ。', 'It only rained on the first day, so it wasn’t that bad.'),
        l(M, 'ホテルも 思[おも]ったより よかったし。ただ、帰[かえ]りの 高速道路[こうそくどうろ]が ひどく 混[こ]んで いて、家[いえ]に 着[つ]くのに 八時間[はちじかん]も かかったんだ。それが 一番[いちばん] 疲[つか]れたね。', 'The hotel was better than I expected too. But the motorway home was terribly jammed, and it took eight hours to get home. That was the most tiring part.'),
      ],
      choices: [p('雨[あめ]が 降[ふ]った こと', 'The rain'), p('ホテルが よくなかった こと', 'The hotel wasn’t good'), p('道[みち]が 混[こ]んで いた こと', 'The traffic jam'), p('お金[かね]が かかった こと', 'It was expensive')],
      answer: 2, why: 'Rain only on day one, the hotel was good; the jammed motorway home was the worst (一番疲れた).' },
    { id: 'n3-like-town', level: 'N3',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は 今[いま]の 町[まち]の どんな ところが 気[き]に 入[い]って いますか。',
      lines: [
        l(M, '引[ひ]っ越[こ]して 半年[はんとし]ですね。新[あたら]しい 町[まち]は どうですか。', 'It’s been six months since you moved. How’s the new town?'),
        l(F, '駅[えき]から 少[すこ]し 遠[とお]いし、大[おお]きな お店[みせ]も ないんですけど…。', 'It’s a bit far from the station, and there are no big shops, but…'),
        l(F, '夜[よる]は とても 静[しず]かで、よく 眠[ねむ]れるんです。前[まえ]の 町[まち]は 車[くるま]の 音[おと]が うるさかったので、それが 一番[いちばん] うれしいですね。', 'it’s very quiet at night and I sleep well. My old town was noisy with traffic, so that’s what I’m happiest about.'),
      ],
      choices: [p('駅[えき]から 近[ちか]い ところ', 'Being close to the station'), p('買[か]い物[もの]が 便利[べんり]な ところ', 'Convenient shopping'), p('静[しず]かな ところ', 'It’s quiet'), p('家賃[やちん]が 安[やす]い ところ', 'Cheap rent')],
      answer: 2, why: 'Far from the station, no big shops — but quiet at night, which she likes most.' },
    { id: 'n3-why-this-shop', level: 'N3',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は どうして この 店[みせ]を 選[えら]びましたか。',
      lines: [
        l(F, 'この 店[みせ]、よく 来[く]るの？ 安[やす]いから？', 'Do you come here often? Because it’s cheap?'),
        l(M, 'いや、値段[ねだん]は 普通[ふつう]だよ。味[あじ]も まあまあかな。', 'No, the prices are average. And the taste is so-so.'),
        l(M, 'でも、夜[よる] 遅[おそ]くまで 開[あ]いて いるから、残業[ざんぎょう]の 後[あと]でも 入[はい]れるんだ。それで よく 来[く]るんだよ。', 'But it’s open late, so I can come even after working overtime. That’s why I come a lot.', 'でも、夜遅くまであいているから、残業のあとでもはいれるんだ。それでよく来るんだよ。'),
      ],
      choices: [p('値段[ねだん]が 安[やす]いから', 'It’s cheap'), p('料理[りょうり]が おいしいから', 'The food is good'), p('遅[おそ]くまで 開[あ]いて いるから', 'It’s open late'), p('会社[かいしゃ]から 近[ちか]いから', 'It’s near work')],
      answer: 2, why: 'Average prices and so-so taste — he comes because it’s open late (遅くまで開いている).' },
    { id: 'n3-new-job', level: 'N3',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は 新[あたら]しい 仕事[しごと]の 何[なに]が 大変[たいへん]だと 言[い]って いますか。',
      lines: [
        l(F, '新[あたら]しい 仕事[しごと]は どう？ 慣[な]れた？', 'How’s the new job? Getting used to it?'),
        l(M, '仕事[しごと]の 内容[ないよう]は 前[まえ]と 似[に]て いるから、問題[もんだい]ないよ。周[まわ]りの 人[ひと]も 親切[しんせつ]だし。', 'The work itself is similar to before, so no problem. And the people around me are kind.'),
        l(M, 'ただ、毎朝[まいあさ] 七時[しちじ]には 会社[かいしゃ]に 着[つ]いて いないと いけないんだ。朝[あさ]が 弱[よわ]いから、それが つらくて。', 'But I have to be at work by seven every morning. I’m not a morning person, so that’s hard.'),
      ],
      choices: [p('仕事[しごと]の 内容[ないよう]が 難[むずか]しい こと', 'The work is difficult'), p('周[まわ]りの 人[ひと]が 厳[きび]しい こと', 'The people are strict'), p('朝[あさ] 早[はや]く 行[い]かなければ ならない こと', 'He has to go in early'), p('帰[かえ]りが 遅[おそ]い こと', 'He gets home late')],
      answer: 2, why: 'The work and people are fine; being at work by seven is hard because he’s not a morning person.' },
    { id: 'n3-phone-problem', level: 'N3',
      intro: '店[みせ]で 女[おんな]の人[ひと]と 店[みせ]の 人[ひと]が 話[はな]しています。女[おんな]の人[ひと]の 携帯電話[けいたいでんわ]は 何[なに]が 問題[もんだい]ですか。',
      lines: [
        l(M, '画面[がめん]が 割[わ]れて しまったんですか。', 'Has the screen cracked?'),
        l(F, 'いいえ、画面[がめん]は 大丈夫[だいじょうぶ]です。電話[でんわ]も ちゃんと かけられます。', 'No, the screen is fine. I can make calls properly too.'),
        l(F, 'ただ、朝[あさ] 充電[じゅうでん]しても、昼[ひる]には もう 電池[でんち]が なくなって しまうんです。', 'But even if I charge it in the morning, the battery is already flat by noon.'),
      ],
      choices: [p('画面[がめん]が 割[わ]れた こと', 'The screen cracked'), p('電話[でんわ]が かけられない こと', 'She can’t make calls'), p('電池[でんち]が すぐ なくなる こと', 'The battery runs out quickly'), p('写真[しゃしん]が 撮[と]れない こと', 'She can’t take photos')],
      answer: 2, why: 'Screen and calls are fine; the battery is flat by noon (電池がなくなってしまう).' },
    { id: 'n3-study-drama', level: 'N3',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は 今[いま] どうやって 日本語[にほんご]を 勉強[べんきょう]して いますか。',
      lines: [
        l(M, '日本語[にほんご]、上手[じょうず]に なりましたね。学校[がっこう]に 通[かよ]って いるんですか。', 'Your Japanese has really improved. Do you go to a school?'),
        l(F, '前[まえ]は 通[かよ]って いましたが、仕事[しごと]が 忙[いそが]しく なって やめました。教科書[きょうかしょ]も なかなか 開[ひら]く 時間[じかん]が なくて。', 'I used to, but I stopped when work got busy. I hardly have time to open a textbook either.'),
        l(F, 'その かわりに、毎晩[まいばん] 日本[にほん]の ドラマを 見[み]る ように して いるんです。', 'Instead, I make a point of watching Japanese dramas every night.'),
      ],
      choices: [p('学校[がっこう]に 通[かよ]って いる', 'She goes to a school'), p('教科書[きょうかしょ]で 勉強[べんきょう]して いる', 'She studies with a textbook'), p('ドラマを 見[み]て いる', 'She watches dramas'), p('友[とも]だちと 話[はな]して いる', 'She talks with friends')],
      answer: 2, why: 'She stopped school and has no time for textbooks; そのかわりに she watches dramas every night.' },
    { id: 'n3-trip-cancel', level: 'N3',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は どうして 旅行[りょこう]を やめましたか。',
      lines: [
        l(F, '来週[らいしゅう]の 北海道[ほっかいどう]旅行[りょこう]、やめたんですか。仕事[しごと]ですか。', 'You’ve cancelled next week’s trip to Hokkaido? Because of work?'),
        l(M, '休[やす]みは 取[と]れて いたんですけど、母[はは]が 急[きゅう]に 入院[にゅういん]する ことに なって…。', 'I’d got the time off, but my mother suddenly has to go into hospital…'),
        l(F, 'そうでしたか。お大事[だいじ]に。', 'I’m sorry to hear that. I hope she gets well.'),
      ],
      choices: [p('仕事[しごと]が 休[やす]めなかったから', 'He couldn’t get time off'), p('お母[かあ]さんが 入院[にゅういん]するから', 'His mother is going into hospital'), p('天気[てんき]が 悪[わる]いから', 'The weather is bad'), p('お金[かね]が 足[た]りないから', 'He’s short of money')],
      answer: 1, why: 'He had the time off; his mother has to go into hospital (母が入院することになって).' },
    { id: 'n3-event-place', level: 'N3',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が お祭[まつ]りに ついて 話[はな]しています。今年[ことし]の お祭[まつ]りは 去年[きょねん]と 何[なに]が 違[ちが]いますか。',
      lines: [
        l(M, '今年[ことし]の 夏祭[なつまつ]りも 八月[はちがつ]の 第一[だいいち] 土曜日[どようび]？', 'Is this year’s summer festival on the first Saturday of August again?'),
        l(F, 'うん、日[ひ]にちも 時間[じかん]も 去年[きょねん]と 同[おな]じ。花火[はなび]も あるよ。', 'Yes, same date and time as last year. And there are fireworks.'),
        l(F, 'ただ、公園[こうえん]が 工事[こうじ]中[ちゅう]だから、場所[ばしょ]が 駅前[えきまえ]の 広場[ひろば]に 変[か]わったの。', 'But the park is under construction, so it’s moved to the square in front of the station.'),
      ],
      choices: [p('日[ひ]にち', 'The date'), p('時間[じかん]', 'The time'), p('場所[ばしょ]', 'The place'), p('花火[はなび]が ない こと', 'No fireworks')],
      answer: 2, why: 'Same date, time and fireworks; the place moved to the station square (場所が変わった).' },
    { id: 'n3-why-bus', level: 'N3',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は 今日[きょう] どうして バスで 来[き]ましたか。',
      lines: [
        l(F, 'あれ、今日[きょう]は 車[くるま]じゃないんですか。故障[こしょう]ですか。', 'Oh, not by car today? Has it broken down?'),
        l(M, 'いいえ、車[くるま]は 大丈夫[だいじょうぶ]です。', 'No, the car’s fine.'),
        l(M, '今夜[こんや] 部長[ぶちょう]たちと 飲[の]みに 行[い]く ことに なって いるので、車[くるま]は 置[お]いて きたんです。', 'I’m going out drinking with the managers tonight, so I left the car at home.'),
      ],
      choices: [p('車[くるま]が 壊[こわ]れたから', 'The car broke down'), p('夜[よる] お酒[さけ]を 飲[の]むから', 'He’ll be drinking tonight'), p('道[みち]が 混[こ]んで いるから', 'The roads are busy'), p('ガソリンが 高[たか]いから', 'Petrol is expensive')],
      answer: 1, why: 'The car is fine; he’s drinking with the managers tonight, so he left it at home.' },
    { id: 'n3-gift-choice', level: 'N3',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。二人[ふたり]は 退職[たいしょく]する 山本[やまもと]さんに 何[なに]を 贈[おく]る ことに しましたか。',
      lines: [
        l(M, '山本[やまもと]さんへの プレゼント、花束[はなたば]で いいかな。', 'Will a bouquet do for Yamamoto-san’s present?'),
        l(F, '花[はな]は 送別会[そうべつかい]で みんなから 渡[わた]す ことに なって いるよ。', 'Everyone is giving flowers at the farewell party.'),
        l(M, 'じゃあ、ワインは？', 'Then wine?'),
        l(F, 'お酒[さけ]は 飲[の]まない 人[ひと]だから…。退職[たいしょく]したら 旅行[りょこう]を したいって 言[い]って いたから、旅行[りょこう]かばんは どう？', 'He doesn’t drink… He said he wants to travel after retiring, so how about a suitcase?'),
        l(M, 'いいね。そう しよう。', 'Good idea. Let’s do that.'),
      ],
      choices: [p('花束[はなたば]', 'A bouquet'), p('ワイン', 'Wine'), p('旅行[りょこう]かばん', 'A suitcase'), p('旅行[りょこう]の 本[ほん]', 'A travel book')],
      answer: 2, why: 'Flowers come from everyone at the party and he doesn’t drink: a suitcase for his travels.' },
  ]);

  add('gaiyou', [
    { id: 'n3-g-sleep', level: 'N3',
      intro: 'ラジオで 医者[いしゃ]が 話[はな]しています。',
      lines: [
        l(F, '最近[さいきん]、夜[よる] なかなか 眠[ねむ]れないと いう 人[ひと]が 増[ふ]えて います。', 'More and more people say they can’t get to sleep at night.'),
        l(F, '寝[ね]る 前[まえ]に スマートフォンの 画面[がめん]を 長[なが]く 見[み]て いると、目[め]や 頭[あたま]が 休[やす]まらず、眠[ねむ]りにくく なります。', 'If you look at a smartphone screen for a long time before bed, your eyes and mind don’t rest and it’s harder to fall asleep.'),
        l(F, '寝[ね]る 一時間[いちじかん] 前[まえ]には 画面[がめん]を 見[み]るのを やめて、ぬるい お風呂[ふろ]に 入[はい]ったり、静[しず]かな 音楽[おんがく]を 聞[き]いたり して みて ください。', 'Stop looking at screens an hour before bed, and try taking a lukewarm bath or listening to quiet music.'),
      ],
      question: '医者[いしゃ]は 何[なに]に ついて 話[はな]して いますか。',
      choices: [r('スマートフォンの 選[えら]び方[かた]', 'How to choose a smartphone'), r('よく 眠[ねむ]る ための 方法[ほうほう]', 'Ways to sleep well'), r('お風呂[ふろ]の 入[はい]り方[かた]', 'How to take a bath', 'お風呂のはいり方'), r('目[め]の 病気[びょうき]', 'Eye diseases')],
      answer: 1, why: 'The whole talk is about sleeping well: stop screens an hour before bed, take a bath, listen to music.' },
    { id: 'n3-g-canteen', level: 'N3',
      intro: '会社[かいしゃ]で 男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。',
      lines: [
        l(M, '新[あたら]しい 社員[しゃいん]食堂[しょくどう]、もう 行[い]った？', 'Have you been to the new staff canteen yet?'),
        l(F, 'うん、昨日[きのう]。きれいだし、メニューも 多[おお]くて よかった。', 'Yes, yesterday. It’s clean and there are lots of dishes, which is nice.'),
        l(F, 'でも、値段[ねだん]が 前[まえ]より ずいぶん 高[たか]く なったでしょう。毎日[まいにち] 使[つか]うには ちょっと…。お弁当[べんとう]を 持[も]って 来[く]る ほうが いいかなって 思[おも]って。', 'But it’s become a lot more expensive than before, hasn’t it? For every day it’s a bit… I’m thinking I’d rather bring a packed lunch.'),
      ],
      question: '女[おんな]の人[ひと]は 新[あたら]しい 社員[しゃいん]食堂[しょくどう]に ついて どう 思[おも]って いますか。',
      choices: [r('きれいで 安[やす]いので、毎日[まいにち] 使[つか]いたい', 'Clean and cheap, so she wants to use it every day'), r('メニューが 少[すく]ないので、行[い]きたくない', 'Too few dishes, so she doesn’t want to go'), r('いい ところも あるが、高[たか]いので 毎日[まいにち]は 使[つか]わない', 'It has good points, but it’s expensive so she won’t use it every day'), r('前[まえ]の 食堂[しょくどう]と 変[か]わらない', 'It’s no different from the old one')],
      answer: 2, why: 'Clean, lots of choice — but much pricier, so she’ll bring a packed lunch instead.' },
    { id: 'n3-g-museum', level: 'N3',
      intro: '美術館[びじゅつかん]で 係[かかり]の 人[ひと]が 話[はな]しています。',
      lines: [
        l(M, '本日[ほんじつ]は ご来館[らいかん] ありがとうございます。', 'Thank you for visiting us today.'),
        l(M, '館内[かんない]では 写真[しゃしん]を 撮[と]る ことが できますが、フラッシュは 使[つか]わないで ください。また、作品[さくひん]には 触[さわ]らないよう お願[ねが]いします。', 'You may take photos inside, but please don’t use flash. And please don’t touch the works.'),
        l(M, '大[おお]きな 荷物[にもつ]は 入[い]り口[ぐち]の ロッカーに お預[あず]けください。', 'Please leave large bags in the lockers at the entrance.'),
      ],
      question: '係[かかり]の 人[ひと]は 何[なに]に ついて 話[はな]して いますか。',
      choices: [r('美術館[びじゅつかん]の 歴史[れきし]', 'The museum’s history'), r('作品[さくひん]の 説明[せつめい]', 'An explanation of the works'), r('館内[かんない]で 守[まも]る こと', 'Rules to follow inside'), r('ロッカーの 使[つか]い方[かた]', 'How to use the lockers')],
      answer: 2, why: 'Photos without flash, no touching, bags in lockers: the rules for visitors.' },
    { id: 'n3-g-teacher', level: 'N3',
      intro: '日本語[にほんご]学校[がっこう]で 先生[せんせい]が 話[はな]しています。',
      lines: [
        l(F, '皆[みな]さん、来週[らいしゅう]から 授業[じゅぎょう]の 始[はじ]め方[かた]が 少[すこ]し 変[か]わります。', 'Everyone, from next week the way we start class will change a little.'),
        l(F, '毎回[まいかい] 最初[さいしょ]の 十分[じゅっぷん]で、前[まえ]の 日[ひ]に 習[なら]った 言葉[ことば]の 小[ちい]さい テストを します。', 'For the first ten minutes of every lesson, there’ll be a short test on the words from the day before.'),
        l(F, '成績[せいせき]には 入[はい]りませんから、心配[しんぱい]しなくても 大丈夫[だいじょうぶ]ですよ。復習[ふくしゅう]の ためだと 思[おも]って ください。', 'It won’t count towards your grades, so don’t worry. Think of it as revision.'),
      ],
      question: '先生[せんせい]は 何[なに]に ついて 話[はな]して いますか。',
      choices: [r('成績[せいせき]の つけ方[かた]', 'How grades are given'), r('新[あたら]しい 教科書[きょうかしょ]', 'A new textbook'), r('授業[じゅぎょう]の 時間[じかん]が 変[か]わる こと', 'Class times changing'), r('授業[じゅぎょう]の 初[はじ]めに 小[ちい]さい テストを する こと', 'A short test at the start of each lesson')],
      answer: 3, why: 'From next week: a ten-minute vocabulary test at the start of each lesson (not graded).' },
    { id: 'n3-g-film', level: 'N3',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 映画[えいが]に ついて 話[はな]しています。',
      lines: [
        l(F, '昨日[きのう] 見[み]た 映画[えいが]、どうだった？ 評判[ひょうばん]が いいよね。', 'How was the film you saw yesterday? It’s got good reviews.'),
        l(M, 'うーん、俳優[はいゆう]の 演技[えんぎ]は すばらしかったし、音楽[おんがく]も よかったんだけど…。', 'Hmm, the acting was wonderful and the music was good too, but…'),
        l(M, '話[はなし]が 長[なが]すぎて、途中[とちゅう]で 眠[ねむ]く なっちゃった。もう 少[すこ]し 短[みじか]ければ もっと 楽[たの]しめたと 思[おも]う。', 'the story was far too long and I got sleepy halfway through. If it had been a bit shorter I’d have enjoyed it more.'),
      ],
      question: '男[おとこ]の人[ひと]は 映画[えいが]に ついて どう 思[おも]って いますか。',
      choices: [r('全部[ぜんぶ] すばらしかった', 'Everything was wonderful'), r('演技[えんぎ]も 音楽[おんがく]も よくなかった', 'Both the acting and the music were bad'), r('いい ところも あったが、長[なが]すぎた', 'It had good points, but was too long'), r('話[はなし]が 短[みじか]すぎた', 'The story was too short')],
      answer: 2, why: 'Great acting and music, but too long (長すぎて) — he got sleepy.' },
    { id: 'n3-g-announce', level: 'N3',
      intro: 'スーパーで 店内[てんない]放送[ほうそう]が 流[なが]れて います。',
      lines: [
        l(F, 'ご来店[らいてん]の お客様[きゃくさま]に お知[し]らせ いたします。', 'An announcement for our customers.'),
        l(F, '本日[ほんじつ]、駐車場[ちゅうしゃじょう]の 工事[こうじ]の ため、北側[きたがわ]の 入[い]り口[ぐち]は ご利用[りよう] いただけません。', 'Today, because of work on the car park, the north entrance cannot be used.'),
        l(F, 'お車[くるま]で お帰[かえ]りの お客様[きゃくさま]は、南側[みなみがわ]の 出口[でぐち]を ご利用[りよう]ください。ご迷惑[めいわく]を おかけして 申[もう]し訳[わけ]ございません。', 'Customers leaving by car, please use the south exit. We apologise for the inconvenience.'),
      ],
      question: '何[なに]に ついての お知[し]らせですか。',
      choices: [r('今日[きょう]の 安[やす]い 品物[しなもの]', 'Today’s bargains'), r('使[つか]えない 入[い]り口[ぐち]', 'An entrance that can’t be used'), r('店[みせ]の 営業[えいぎょう]時間[じかん]', 'The opening hours'), r('落[お]とし物[もの]', 'Lost property')],
      answer: 1, why: 'The north entrance is closed for car-park work; use the south exit.' },
  ]);

  add('hatsuwa', [
    { id: 'n3-h-late-meeting', level: 'N3', scene: { setting: 'office', left: 'office', right: 'officeWoman', arrow: 'left' },
      intro: '会議[かいぎ]に 遅[おく]れて しまいました。部屋[へや]に 入[はい]る 時[とき]、何[なん]と 言[い]いますか。',
      choices: [r('遅[おく]れて 申[もう]し訳[わけ]ありません。', 'I’m very sorry I’m late.'), r('遅[おく]れないで ください。', 'Please don’t be late.'), r('お待[ま]ちして いました。', 'I was waiting for you.')], answer: 0, why: 'Apologise humbly: 遅れて申し訳ありません.' },
    { id: 'n3-h-recommend-friend', level: 'N3', scene: { setting: 'restaurant', left: 'friend', right: 'friendMan', arrow: 'right' },
      intro: '友[とも]だちが この 店[みせ]の 料理[りょうり]を 知[し]りません。おすすめを 教[おし]えて あげたいです。何[なん]と 言[い]いますか。',
      choices: [r('ここは 何[なに]が おいしいの？', 'What’s good here?'), r('ここの ラーメン、食[た]べて みたら？', 'Why don’t you try the ramen here?'), r('ラーメン、食[た]べた ことが ある？', 'Have you ever had ramen?')], answer: 1, why: '〜てみたら？ suggests trying something.' },
    { id: 'n3-h-take-photo-ok', level: 'N3', scene: { setting: 'shop', left: 'tourist', right: 'clerkMan', prop: 'camera', holder: 'left', arrow: 'left' },
      intro: 'お店[みせ]の 中[なか]で 写真[しゃしん]を 撮[と]りたいです。店[みせ]の 人[ひと]に 何[なん]と 言[い]いますか。',
      choices: [r('写真[しゃしん]を 撮[と]って いただけませんか。', 'Could you take my photo?'), r('ここで 写真[しゃしん]を 撮[と]っても かまいませんか。', 'Do you mind if I take photos here?'), r('写真[しゃしん]を 撮[と]りましょうか。', 'Shall I take a photo?')], answer: 1, why: '〜てもかまいませんか asks permission.' },
    { id: 'n3-h-lend-umbrella', level: 'N3', scene: { setting: 'rain', left: 'officeWoman', right: 'office', prop: 'umbrella', holder: 'left', propSize: 40, arrow: 'left' }, replyBy: 'F',
      intro: '同僚[どうりょう]が 傘[かさ]を 持[も]って いないので、自分[じぶん]の 傘[かさ]を 貸[か]して あげます。何[なん]と 言[い]いますか。',
      choices: [r('よかったら、これ、使[つか]って ください。', 'If you like, please use this.'), r('傘[かさ]を 貸[か]して もらえますか。', 'Could you lend me an umbrella?'), r('傘[かさ]を 忘[わす]れないで くださいね。', 'Don’t forget your umbrella.')], answer: 0, why: 'Offering: よかったら、使ってください.' },
    { id: 'n3-h-call-back', level: 'N3', scene: { setting: 'office', left: 'officeWoman', right: 'office', prop: 'phone', holder: 'left', propSize: 30, arrow: 'left' }, replyBy: 'F',
      intro: '電話[でんわ]を かけた 相手[あいて]は 会議[かいぎ]中[ちゅう]でした。後[あと]で 電話[でんわ]が ほしいです。何[なん]と 言[い]いますか。',
      choices: [r('後[あと]で お電話[でんわ]しましょうか。', 'Shall I call later?'), r('会議[かいぎ]は 何時[なんじ]に 終[お]わりましたか。', 'What time did the meeting end?'), r('お手数[てすう]ですが、後[あと]で お電話[でんわ] いただけますか。', 'Sorry to trouble you, but could he call me back later?')], answer: 2, why: 'Asking for a call back: 後でお電話いただけますか.' },
    { id: 'n3-h-praise', level: 'N3', scene: { setting: 'office', left: 'teacher', right: 'officeWoman', arrow: 'left' },
      intro: '部下[ぶか]の 資料[しりょう]が とても よく できて いました。何[なん]と 言[い]いますか。',
      choices: [r('よく できて いるね。助[たす]かったよ。', 'Well done. That was a big help.'), r('資料[しりょう]を 作[つく]って くれる？', 'Could you make the documents?'), r('もう 少[すこ]し 頑張[がんば]って。', 'Try a bit harder.')], answer: 0, why: 'Praise and thanks: よくできているね、助かったよ.' },
    { id: 'n3-h-seat-taken', level: 'N3', scene: { setting: 'train', left: 'grandpa', right: 'woman2', arrow: 'left' }, voices: { M: 'old' },
      intro: '電車[でんしゃ]で 空[あ]いて いる 席[せき]に 座[すわ]りたいです。隣[となり]の 人[ひと]に 何[なん]と 言[い]いますか。',
      choices: [r('ここ、空[あ]いて いますか。', 'Is this seat free?'), r('ここに 座[すわ]って ください。', 'Please sit here.'), r('席[せき]を 譲[ゆず]りましょうか。', 'Shall I give you my seat?')], answer: 0, why: 'Ask if the seat is free: 空いていますか.' },
    { id: 'n3-h-congrats-baby', level: 'N3', scene: { setting: 'office', left: 'officeWoman', right: 'father', arrow: 'left' }, replyBy: 'F',
      intro: '同僚[どうりょう]に 子[こ]どもが 生[う]まれました。何[なん]と 言[い]いますか。',
      choices: [r('お疲[つか]れさまでした。', 'Thanks for your hard work.'), r('ご出産[しゅっさん]、おめでとうございます。', 'Congratulations on the birth.'), r('お大事[だいじ]に。', 'Take care of yourself.')], answer: 1, why: 'Congratulate: おめでとうございます.' },
  ]);

  const q = (id, who, ja, en, replyBy, choices, answer, why, extra = {}) => Object.assign({ id, level: 'N3', lines: [l(who, ja, en)], replyBy, choices, answer, why }, extra);
  add('sokuji', [
    q('n3-s-help-carry', M, 'この 荷物[にもつ]、運[はこ]ぶの 手伝[てつだ]って くれない？', 'Could you help me carry this?', F,
      [r('うん、どこに 持[も]って いけば いい？', 'Sure, where shall I take it?'), r('うん、手伝[てつだ]って くれて ありがとう。', 'Yes, thanks for helping me.'), r('うん、運[はこ]んで もらった。', 'Yes, I had it carried.')], 0, 'Agree and ask where — the natural reply to a request.'),
    q('n3-s-should-have', F, 'もっと 早[はや]く 家[いえ]を 出[で]れば よかった。', 'I should have left home earlier.', M,
      [r('うん、早[はや]く 出[で]よう。', 'Yeah, let’s leave early.'), r('電車[でんしゃ]が 遅[おく]れて いたから、しかたないよ。', 'The trains were late, so it couldn’t be helped.'), r('早[はや]く 出[で]て よかったね。', 'Good thing you left early.')], 1, '〜ばよかった is a regret; comfort her.'),
    q('n3-s-supposed', M, '田中[たなか]さん、もう 着[つ]いて いる はずなんだけど。', 'Tanaka-san should have arrived by now.', F,
      [r('電話[でんわ]して みましょうか。', 'Shall I try calling him?'), r('はい、着[つ]く はずでした。', 'Yes, he was supposed to.'), r('もう 出発[しゅっぱつ]しましょうか。', 'Shall we set off?')], 0, '〜はず: he should be here but isn’t — so check.'),
    q('n3-s-not-sure', F, '明日[あした]の 試合[しあい]、雨[あめ]で 中止[ちゅうし]に なるかもしれないね。', 'Tomorrow’s match might be cancelled because of rain.', M,
      [r('うん、中止[ちゅうし]だったね。', 'Yes, it was cancelled.'), r('じゃあ、朝[あさ] 確認[かくにん]して から 行[い]こう。', 'Then let’s check in the morning before we go.'), r('雨[あめ]が 降[ふ]って よかったね。', 'Good that it rained.')], 1, 'It might be cancelled → check in the morning.'),
    q('n3-s-thanks-yesterday', M, '昨日[きのう]は ごちそうさまでした。', 'Thank you for the meal yesterday.', F,
      [r('いいえ、こちらこそ 来[き]て くれて ありがとう。', 'Not at all — thank you for coming.'), r('いいえ、いただきます。', 'No, I’ll have some.'), r('じゃあ、また ごちそうして ください。', 'Then treat me again.')], 0, 'Reply to thanks for a meal you hosted: こちらこそ.'),
    q('n3-s-so-tired', F, '今日[きょう]は 一日中[いちにちじゅう] 歩[ある]いたから、足[あし]が 棒[ぼう]に なっちゃった。', 'I walked all day, so my legs are like sticks.', M,
      [r('じゃあ、少[すこ]し 休[やす]もうか。', 'Then shall we rest a bit?'), r('棒[ぼう]は どこに ある？', 'Where’s the stick?'), r('もっと 歩[ある]けば よかったね。', 'You should have walked more.')], 0, '足が棒になる means her legs are exhausted.'),
    q('n3-s-borrow-car', M, '週末[しゅうまつ]、車[くるま]を 借[か]りても いいかな。', 'Is it OK if I borrow the car at the weekend?', F,
      [r('うん、借[か]りて あげる。', 'Yes, I’ll borrow it for you.'), r('いいよ。ガソリンだけ 入[い]れて おいてね。', 'Sure. Just fill it with petrol.'), r('週末[しゅうまつ]は 借[か]りたよ。', 'I borrowed it at the weekend.')], 1, 'Permission plus a condition.'),
    q('n3-s-sold-out', F, '申[もう]し訳[わけ]ございません。その 商品[しょうひん]は 売[う]り切[き]れて しまいました。', 'I’m very sorry, that item is sold out.', M,
      [r('じゃあ、次[つぎ]は いつ 入[はい]りますか。', 'Then when will you get more in?'), r('じゃあ、それを ください。', 'Then I’ll take it.'), r('よく 売[う]れて いますか。', 'Is it selling well?')], 0, 'Sold out → ask when it will be restocked.'),
    q('n3-s-cheer', M, '来週[らいしゅう]、大事[だいじ]な 面接[めんせつ]が あるんだ。', 'I’ve got an important interview next week.', F,
      [r('面接[めんせつ]、どうだった？', 'How did the interview go?'), r('そうなんだ。頑張[がんば]ってね。', 'Really? Good luck.'), r('面接[めんせつ]を 受[う]けて あげる。', 'I’ll do the interview for you.')], 1, 'Next week → wish him luck.'),
    q('n3-s-what-mean', F, 'この 漢字[かんじ]、どういう 意味[いみ]か わかる？', 'Do you know what this kanji means?', M,
      [r('ごめん、僕[ぼく]も わからない。辞書[じしょ]で 調[しら]べて みよう。', 'Sorry, I don’t know either. Let’s look it up.'), r('うん、わかって よかった。', 'Yes, I’m glad I understood.'), r('漢字[かんじ]で 書[か]いて。', 'Write it in kanji.')], 0, 'Admit you don’t know and suggest looking it up.'),
    q('n3-s-instead', M, '今日[きょう]は 僕[ぼく]が 部長[ぶちょう]の 代[か]わりに 会議[かいぎ]に 出[で]ます。', 'Today I’ll attend the meeting in place of the manager.', F,
      [r('部長[ぶちょう]は 会議[かいぎ]に 出[で]ましたか。', 'Did the manager attend?'), r('わかりました。よろしく お願[ねが]いします。', 'I see. We look forward to working with you.'), r('代[か]わりを 探[さが]しましょう。', 'Let’s look for a substitute.')], 1, 'Accept: よろしくお願いします.'),
    q('n3-s-almost-forgot', F, 'あ、危[あぶ]ない。財布[さいふ]を 忘[わす]れる ところだった。', 'Oh, close one. I nearly forgot my wallet.', M,
      [r('忘[わす]れて よかったね。', 'Good thing you forgot it.'), r('気[き]が ついて よかったね。', 'Good thing you noticed.'), r('財布[さいふ]を 探[さが]して いるの？', 'Are you looking for your wallet?')], 1, '〜ところだった: she almost forgot but didn’t.'),
    q('n3-s-ask-way', M, '駅[えき]までの 道[みち]、わかりますか。', 'Do you know the way to the station?', F,
      [r('ええ、わかりにくいですね。', 'Yes, it’s confusing.'), r('ええ、一緒[いっしょ]に 行[い]きましょうか。', 'Yes — shall we go together?'), r('駅[えき]は 混[こ]んで いますね。', 'The station is crowded.')], 1, 'Yes, and offer to go together.'),
    q('n3-s-no-way', F, '一日[いちにち]で この 本[ほん]を 全部[ぜんぶ] 読[よ]むなんて、無理[むり]だよ。', 'There’s no way I can read this whole book in a day.', M,
      [r('じゃあ、半分[はんぶん]ずつ 読[よ]もうか。', 'Then shall we read half each?'), r('全部[ぜんぶ] 読[よ]めて よかったね。', 'Good that you read it all.'), r('うん、一日[いちにち]で 読[よ]んだよ。', 'Yes, I read it in a day.')], 0, 'She says it’s impossible → suggest splitting it.'),
    q('n3-s-reschedule', M, 'すみません、明日[あした]の 約束[やくそく]、あさってに して もらえませんか。', 'Sorry, could we move tomorrow’s appointment to the day after?', F,
      [r('あさっては 昨日[きのう]でしたね。', 'The day after was yesterday.'), r('ええ、あさってでも 大丈夫[だいじょうぶ]ですよ。', 'Sure, the day after is fine.'), r('約束[やくそく]を 守[まも]って ください。', 'Please keep your promise.')], 1, 'Agree to the new day.'),
    q('n3-s-taste', F, 'この スープ、ちょっと 味[あじ]が 薄[うす]くない？', 'Isn’t this soup a bit bland?', M,
      [r('そう？ じゃあ、塩[しお]を 少[すこ]し 入[い]れよう。', 'Is it? Then let’s add a little salt.'), r('うん、薄[うす]く 切[き]って。', 'Yes, slice it thinly.'), r('スープは 熱[あつ]いね。', 'The soup is hot.')], 0, '味が薄い means bland → add salt.'),
    q('n3-s-no-need', M, '駅[えき]まで 送[おく]ろうか。', 'Shall I take you to the station?', F,
      [r('ありがとう。でも、近[ちか]いから 歩[ある]いて 行[い]くよ。', 'Thanks, but it’s close so I’ll walk.'), r('うん、送[おく]って あげる。', 'Yes, I’ll take you.'), r('駅[えき]まで 送[おく]りました。', 'I took you to the station.')], 0, 'Politely decline an offer.'),
    q('n3-s-good-at', F, '料理[りょうり]、上手[じょうず]なんですね。', 'You’re a good cook, aren’t you?', M,
      [r('いえいえ、まだまだです。', 'Oh no, I’ve still a long way to go.'), r('はい、上手[じょうず]に 作[つく]って ください。', 'Yes, please make it well.'), r('料理[りょうり]が 好[す]きですか。', 'Do you like cooking?')], 0, 'Modestly deflect a compliment: まだまだです.'),
  ]);
})(typeof window !== 'undefined' ? window : globalThis);
