(function (global) {
  'use strict';

  // More N3 and N2 questions (format: listening-data.js; printed phrase
  // choices for 問題1 and 問題2, spoken choices for 概要理解).
  const add = global.LISTENING_ADD;
  const p = (ja, en) => ({ type: 'phrase', ja, en });
  const r = (ja, en, say) => (say ? { ja, en, say } : { ja, en });
  const M = 'M', F = 'F';
  const l = (who, ja, en, say) => (say ? { who, ja, en, say } : { who, ja, en });
  const q = (level, id, who, ja, en, replyBy, choices, answer, why) => ({ id, level, lines: [l(who, ja, en)], replyBy, choices, answer, why });

  add('kadai', [
    { id: 'n3-k-gym-join', level: 'N3',
      intro: 'スポーツクラブで 男[おとこ]の人[ひと]と 受付[うけつけ]の 人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は この 後[あと] まず 何[なに]を しますか。',
      lines: [
        l(M, '入会[にゅうかい]したいんですが。', 'I’d like to join.'),
        l(F, 'ありがとうございます。では、こちらの 用紙[ようし]に お名前[なまえ]と ご住所[じゅうしょ]を 書[か]いて ください。写真[しゃしん]は あとで こちらで 撮[と]ります。', 'Thank you. Then please write your name and address on this form. We’ll take your photo here afterwards.'),
        l(M, 'お金[かね]は 今日[きょう] 払[はら]うんですか。', 'Do I pay today?'),
        l(F, 'いいえ、来月[らいげつ]から 口座[こうざ]から 引[ひ]き落[お]とされます。', 'No, it’s taken from your bank account from next month.'),
      ],
      choices: [p('用紙[ようし]に 名前[なまえ]と 住所[じゅうしょ]を 書[か]く', 'Write his name and address on the form'), p('写真[しゃしん]を 撮[と]って もらう', 'Have his photo taken'), p('お金[かね]を 払[はら]う', 'Pay the fee'), p('銀行[ぎんこう]に 行[い]く', 'Go to the bank')],
      answer: 0, why: 'The form comes first; the photo is afterwards, and payment is by direct debit next month.' },
    { id: 'n3-k-trip-plan', level: 'N3',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 旅行[りょこう]の 準備[じゅんび]に ついて 話[はな]しています。女[おんな]の人[ひと]は この 後[あと] 何[なに]を しますか。',
      lines: [
        l(M, 'ホテルの 予約[よやく]は もう したよ。', 'I’ve already booked the hotel.'),
        l(F, 'ありがとう。じゃあ、わたしは 新幹線[しんかんせん]の 切符[きっぷ]を 買[か]って おくね。', 'Thanks. Then I’ll buy the bullet train tickets.'),
        l(M, '切符[きっぷ]は 会社[かいしゃ]の 帰[かえ]りに ぼくが 買[か]えるよ。それより、向[む]こうで 行[い]く レストランを 調[しら]べて くれない？ 君[きみ]の ほうが 詳[くわ]しいから。', 'I can buy the tickets on my way home from work. Instead, could you look up restaurants to go to there? You know more about that.'),
        l(F, 'わかった。じゃあ、そうする。', 'OK, I’ll do that.'),
      ],
      choices: [p('ホテルを 予約[よやく]する', 'Book the hotel'), p('新幹線[しんかんせん]の 切符[きっぷ]を 買[か]う', 'Buy the train tickets'), p('レストランを 調[しら]べる', 'Look up restaurants'), p('会社[かいしゃ]に 休[やす]みを 頼[たの]む', 'Ask work for time off')],
      answer: 2, why: 'He has the hotel and will buy the tickets; she looks up restaurants.' },
    { id: 'n3-k-parcel-redeliver', level: 'N3',
      intro: '女[おんな]の人[ひと]が 宅配便[たくはいびん]の 会社[かいしゃ]に 電話[でんわ]を しています。女[おんな]の人[ひと]は 何時[なんじ]ごろ うちに いなければ なりませんか。',
      lines: [
        l(F, '不在票[ふざいひょう]が 入[はい]って いたので、もう 一度[いちど] 届[とど]けて いただきたいんですが。', 'There was a missed-delivery notice, so I’d like it delivered again.'),
        l(M, 'かしこまりました。本日[ほんじつ]ですと、夕方[ゆうがた] 六時[ろくじ]から 八時[はちじ]の 間[あいだ]に なりますが。', 'Certainly. For today, that would be between six and eight in the evening.'),
        l(F, '六時[ろくじ]は まだ 会社[かいしゃ]なので、明日[あした]の 午前中[ごぜんちゅう]で お願[ねが]いします。', 'I’m still at work at six, so tomorrow morning, please.'),
      ],
      choices: [p('今日[きょう]の 六時[ろくじ]から 八時[はちじ]', 'Today from six to eight'), p('今日[きょう]の 午前中[ごぜんちゅう]', 'This morning'), p('明日[あした]の 午前中[ごぜんちゅう]', 'Tomorrow morning'), p('明日[あした]の 六時[ろくじ]から 八時[はちじ]', 'Tomorrow from six to eight')],
      answer: 2, why: 'She can’t be home at six today, so she chooses tomorrow morning.' },
    { id: 'n3-k-club-prepare', level: 'N3',
      intro: '大学[だいがく]で 先輩[せんぱい]と 新[あたら]しい 部員[ぶいん]が 話[はな]しています。新[あたら]しい 部員[ぶいん]は 来週[らいしゅう]までに 何[なに]を 用意[ようい]しますか。',
      voices: { M: 'young', F: 'young' },
      lines: [
        l(F, '来週[らいしゅう]から 練習[れんしゅう]に 参加[さんか]して ね。ラケットは 部[ぶ]のを 貸[か]して あげるから。', 'Join practice from next week. We’ll lend you one of the club’s rackets.'),
        l(M, 'ありがとうございます。靴[くつ]は 普通[ふつう]の 運動靴[うんどうぐつ]で いいですか。', 'Thank you. Are ordinary trainers OK for shoes?'),
        l(F, 'コートが 傷[きず]つくから、テニス用[よう]の 靴[くつ]を 買[か]って きて。ユニフォームは 試合[しあい]の 前[まえ]で いいよ。', 'They damage the court, so buy tennis shoes. The uniform can wait until before a match.'),
      ],
      choices: [p('ラケット', 'A racket'), p('テニス用[よう]の 靴[くつ]', 'Tennis shoes'), p('ユニフォーム', 'A uniform'), p('普通[ふつう]の 運動靴[うんどうぐつ]', 'Ordinary trainers')],
      answer: 1, why: 'The racket is lent and the uniform can wait; he needs tennis shoes.' },
    { id: 'n3-k-doctor-visit', level: 'N3',
      intro: '病院[びょういん]で 看護師[かんごし]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は この 後[あと] どこへ 行[い]きますか。',
      lines: [
        l(F, '診察[しんさつ]の 前[まえ]に 熱[ねつ]を 測[はか]りますので、こちらで 体温計[たいおんけい]を 使[つか]って ください。', 'We’ll take your temperature before the examination, so please use the thermometer here.'),
        l(M, 'はい。…三十七度[さんじゅうななど] 五分[ごぶ]でした。', 'OK… it’s 37.5.'),
        l(F, 'では、熱[ねつ]の ある 方[かた]は 二階[にかい]の 待合室[まちあいしつ]で お待[ま]ちください。一階[いっかい]は 熱[ねつ]の ない 方[かた]用[よう]です。', 'Then people with a fever, please wait in the waiting room on the second floor. The first floor is for people without a fever.'),
      ],
      choices: [p('一階[いっかい]の 待合室[まちあいしつ]', 'The ground-floor waiting room'), p('二階[にかい]の 待合室[まちあいしつ]', 'The second-floor waiting room'), p('診察室[しんさつしつ]', 'The consulting room'), p('受付[うけつけ]', 'Reception')],
      answer: 1, why: 'He has a fever (37.5), so he waits on the second floor.' },
    { id: 'n3-k-recycle-day', level: 'N3',
      intro: 'アパートで 男[おとこ]の人[ひと]と 大家[おおや]さんが 話[はな]しています。男[おとこ]の人[ひと]は 古[ふる]い 雑誌[ざっし]を いつ 出[だ]しますか。',
      lines: [
        l(M, 'すみません、古[ふる]い 雑誌[ざっし]は 何曜日[なんようび]に 出[だ]せば いいですか。', 'Excuse me, which day do I put out old magazines?'),
        l(F, '紙[かみ]の ごみは 水曜日[すいようび]ですよ。ただ、今週[こんしゅう]は 祝日[しゅくじつ]なので、木曜日[もくようび]に なります。', 'Paper rubbish is Wednesday. But this week Wednesday’s a holiday, so it’s Thursday.'),
        l(M, 'わかりました。じゃあ 今週[こんしゅう]は 木曜日[もくようび]ですね。', 'I see. So this week it’s Thursday.'),
      ],
      choices: [{ type: 'week', days: [3] }, { type: 'week', days: [4] }, { type: 'week', days: [2] }, { type: 'week', days: [5] }],
      answer: 1, why: 'Usually Wednesday, but this week’s holiday moves it to Thursday.' },
    { id: 'n2-k-client-visit', level: 'N2',
      intro: '会社[かいしゃ]で 課長[かちょう]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は この 後[あと] まず 何[なに]を しなければ なりませんか。',
      lines: [
        l(F, '明日[あした]の A社[えーしゃ]への 訪問[ほうもん]だけど、資料[しりょう]は できてる？', 'About tomorrow’s visit to Company A — are the materials ready?', '明日の、えーしゃへの訪問だけど、資料はできてる？'),
        l(M, 'はい、昨日[きのう] 完成[かんせい]しました。人数分[にんずうぶん] 印刷[いんさつ]も 済[す]んで います。', 'Yes, I finished them yesterday. I’ve printed one for everyone too.'),
        l(F, 'そう。先方[せんぽう]の 担当者[たんとうしゃ]が 替[か]わったって 聞[き]いたけど、時間[じかん]の 確認[かくにん]は した？', 'Good. I heard their contact person changed — did you confirm the time?'),
        l(M, 'あ、まだです。前[まえ]の 方[かた]と 決[き]めた ままでした。', 'Ah, not yet. It’s still what I arranged with the previous person.'),
        l(F, 'じゃあ、すぐ 新[あたら]しい 担当者[たんとうしゃ]に 連絡[れんらく]して。資料[しりょう]の 宛名[あてな]も 直[なお]さなきゃ いけないけど、それは その 後[あと]で いいから。', 'Then contact the new person right away. You’ll also need to fix the name on the materials, but that can come after.'),
      ],
      choices: [p('資料[しりょう]を 完成[かんせい]させる', 'Finish the materials'), p('資料[しりょう]を 印刷[いんさつ]する', 'Print the materials'), p('新[あたら]しい 担当者[たんとうしゃ]に 時間[じかん]を 確認[かくにん]する', 'Confirm the time with the new contact'), p('資料[しりょう]の 宛名[あてな]を 直[なお]す', 'Correct the name on the materials')],
      answer: 2, why: 'Materials are done and printed; contacting the new person comes first, the name fix after.' },
    { id: 'n2-k-apartment-move-out', level: 'N2',
      intro: '不動産屋[ふどうさんや]で 女[おんな]の人[ひと]と 店[みせ]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は 今月中[こんげつちゅう]に 何[なに]を しなければ なりませんか。',
      lines: [
        l(F, '来月末[らいげつまつ]で 部屋[へや]を 出[で]たいんですが。', 'I’d like to move out at the end of next month.'),
        l(M, 'かしこまりました。解約[かいやく]の 場合[ばあい]は 一[いっ]か月前[げつまえ]までに 書類[しょるい]を 出[だ]して いただく ことに なって います。', 'Certainly. When ending a contract, you need to submit the paperwork at least one month ahead.', 'かしこまりました。解約の場合は、いっかげつまえまでに、書類を出していただくことになっています。'),
        l(F, 'じゃあ、今月中[こんげつちゅう]ですね。鍵[かぎ]は いつ 返[かえ]せば いいですか。', 'So within this month. When should I return the keys?'),
        l(M, '鍵[かぎ]は 出[で]る 日[ひ]に、部屋[へや]の 確認[かくにん]の 時[とき]で 結構[けっこう]です。', 'The keys can be returned on the day you leave, when we check the room.'),
      ],
      choices: [p('解約[かいやく]の 書類[しょるい]を 出[だ]す', 'Submit the cancellation papers'), p('鍵[かぎ]を 返[かえ]す', 'Return the keys'), p('部屋[へや]の 確認[かくにん]を して もらう', 'Have the room checked'), p('引[ひ]っ越[こ]し先[さき]を 決[き]める', 'Decide where to move')],
      answer: 0, why: 'The papers must go in a month ahead — this month; keys and the check are on the day.' },
    { id: 'n2-k-conference-roles', level: 'N2',
      intro: '大学[だいがく]で 先生[せんせい]と 女[おんな]の 学生[がくせい]が 学会[がっかい]の 準備[じゅんび]に ついて 話[はな]しています。女[おんな]の 学生[がくせい]は 何[なに]を 担当[たんとう]しますか。',
      voices: { F: 'young' },
      lines: [
        l(M, '受付[うけつけ]は 一年生[いちねんせい]に 頼[たの]んで あるから、君[きみ]には 会場[かいじょう]の 案内[あんない]を お願[ねが]いしたいんだけど。', 'The first-years are doing reception, so I’d like you to guide people around the venue.'),
        l(F, 'すみません、当日[とうじつ]は 午後[ごご]に 自分[じぶん]の 発表[はっぴょう]が あって、ずっとは いられないんです。', 'Sorry, I have my own presentation in the afternoon that day, so I can’t be there the whole time.'),
        l(M, 'そうか。じゃあ、案内[あんない]は ほかの 人[ひと]に 頼[たの]むよ。代[か]わりに、前[まえ]の 日[ひ]に 配[くば]る 資料[しりょう]を まとめて くれる？', 'I see. Then I’ll ask someone else to guide. Instead, could you put together the handouts the day before?'),
        l(F, 'はい、それなら できます。', 'Yes, I can do that.'),
      ],
      choices: [p('受付[うけつけ]', 'Reception'), p('会場[かいじょう]の 案内[あんない]', 'Guiding at the venue'), p('配[くば]る 資料[しりょう]の 準備[じゅんび]', 'Preparing the handouts'), p('午後[ごご]の 発表[はっぴょう]の 司会[しかい]', 'Chairing the afternoon talks')],
      answer: 2, why: 'She can’t guide all day because of her talk, so she prepares the handouts.' },
    { id: 'n2-k-refund', level: 'N2',
      intro: '電話[でんわ]で 男[おとこ]の人[ひと]と 店[みせ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は この 後[あと] 何[なに]を しますか。',
      lines: [
        l(M, 'ネットで 注文[ちゅうもん]した セーターが 届[とど]いたんですが、サイズが 合[あ]わなくて。', 'The sweater I ordered online arrived, but it doesn’t fit.'),
        l(F, '申[もう]し訳[わけ]ございません。交換[こうかん]と 返金[へんきん]、どちらに なさいますか。', 'We apologise. Would you like an exchange or a refund?'),
        l(M, '大[おお]きい サイズは もう 売[う]り切[き]れて いたので、返金[へんきん]で お願[ねが]いします。', 'The larger size was already sold out, so a refund, please.'),
        l(F, 'かしこまりました。では、商品[しょうひん]を お送[おく]りいただく 前[まえ]に、ホームページから 返品[へんぴん]の 申[もう]し込[こ]みを お願[ねが]いいたします。番号[ばんごう]が 出[で]ますので、それを 箱[はこ]に 書[か]いて お送[おく]りください。', 'Certainly. Before sending the item back, please apply for a return on our website. You’ll get a number; write it on the box and send it.'),
      ],
      choices: [p('大[おお]きい サイズを 注文[ちゅうもん]する', 'Order a larger size'), p('ホームページで 返品[へんぴん]を 申[もう]し込[こ]む', 'Apply for a return on the website'), p('箱[はこ]に 番号[ばんごう]を 書[か]いて 送[おく]る', 'Write the number on the box and send it'), p('店[みせ]に セーターを 持[も]って いく', 'Take the sweater to the shop')],
      answer: 1, why: 'Before sending it, he applies on the website to get the number.' },
    { id: 'n2-k-seminar-room', level: 'N2',
      intro: '会社[かいしゃ]で 女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 研修[けんしゅう]の 準備[じゅんび]に ついて 話[はな]しています。男[おとこ]の人[ひと]は 何[なに]を 用意[ようい]しますか。',
      lines: [
        l(F, '明日[あした]の 研修[けんしゅう]、プロジェクターは 会議室[かいぎしつ]に ついてるから、持[も]って いかなくて いいよ。', 'For tomorrow’s training, the meeting room has a projector, so you don’t need to bring one.'),
        l(M, 'わかりました。マイクは どうしましょう。', 'OK. What about a microphone?'),
        l(F, '二十人[にじゅうにん]ぐらいだから、なくても 大丈夫[だいじょうぶ]でしょう。それより、名札[なふだ]を 人数分[にんずうぶん] 作[つく]って おいて。初[はじ]めて 会[あ]う 人[ひと]が 多[おお]いから。', 'It’s about twenty people, so we can do without. More importantly, make name tags for everyone. Many of them haven’t met before.'),
      ],
      choices: [p('プロジェクター', 'A projector'), p('マイク', 'A microphone'), p('名札[なふだ]', 'Name tags'), p('会議室[かいぎしつ]の 予約[よやく]', 'A meeting-room booking')],
      answer: 2, why: 'The room has a projector and no mic is needed; he makes name tags.' },
  ]);

  add('point', [
    { id: 'n3-p-why-cook', level: 'N3',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は どうして 料理[りょうり]を 始[はじ]めましたか。',
      lines: [
        l(F, '最近[さいきん]、お弁当[べんとう]を 持[も]って きてるね。節約[せつやく]？', 'You’ve been bringing a packed lunch lately. Saving money?'),
        l(M, 'それも あるけど、健康診断[けんこうしんだん]で 野菜[やさい]が 足[た]りないって 言[い]われて。自分[じぶん]で 作[つく]れば 野菜[やさい]を たくさん 入[い]れられるでしょう。', 'That too, but at my health check they said I don’t eat enough vegetables. If I make it myself I can put lots in.'),
      ],
      choices: [p('お金[かね]を 節約[せつやく]したいから', 'He wants to save money'), p('野菜[やさい]を たくさん 食[た]べたいから', 'He wants to eat more vegetables'), p('料理[りょうり]が 好[す]きだから', 'He likes cooking'), p('会社[かいしゃ]の 食堂[しょくどう]が 閉[し]まったから', 'The canteen closed')],
      answer: 1, why: 'Saving is a side reason; the health check said he needs more vegetables.' },
    { id: 'n3-p-concert-problem', level: 'N3',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が コンサートに ついて 話[はな]しています。女[おんな]の人[ひと]は 何[なに]が 残念[ざんねん]だったと 言[い]って いますか。',
      lines: [
        l(M, '昨日[きのう]の コンサート、どうだった？', 'How was yesterday’s concert?'),
        l(F, '歌[うた]は すごく よかったよ。席[せき]も 前[まえ]の ほうだったし。', 'The singing was great. And our seats were near the front.'),
        l(F, 'ただ、いちばん 聞[き]きたかった 曲[きょく]を 歌[うた]って くれなかったの。それだけが ね。', 'Only, they didn’t sing the song I most wanted to hear. That was the one thing.'),
      ],
      choices: [p('歌[うた]が 下手[へた]だった こと', 'The singing was bad'), p('席[せき]が 後[うし]ろだった こと', 'The seats were at the back'), p('聞[き]きたい 曲[きょく]が なかった こと', 'The song she wanted wasn’t played'), p('コンサートが 短[みじか]かった こと', 'The concert was short')],
      answer: 2, why: 'Singing and seats were good; her favourite song wasn’t sung.' },
    { id: 'n3-p-new-apartment', level: 'N3',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は 新[あたら]しい 部屋[へや]の どこが いちばん 気[き]に 入[い]って いますか。',
      lines: [
        l(M, '引[ひ]っ越[こ]し、終[お]わった？ 新[あたら]しい 部屋[へや]は どう？', 'Have you finished moving? How’s the new place?'),
        l(F, '駅[えき]からは ちょっと 遠[とお]く なったけど、前[まえ]より 広[ひろ]いし、家賃[やちん]も 同[おな]じぐらい。', 'It’s a bit further from the station, but it’s bigger than before and the rent is about the same.'),
        l(F, 'でも 何[なに]より、窓[まど]から 海[うみ]が 見[み]えるのが いいの。毎朝[まいあさ] 気持[きも]ちが いいよ。', 'But above all, I love that I can see the sea from the window. Every morning feels great.'),
      ],
      choices: [p('駅[えき]から 近[ちか]い ところ', 'Being close to the station'), p('部屋[へや]が 広[ひろ]い ところ', 'Being spacious'), p('家賃[やちん]が 安[やす]い ところ', 'Being cheap'), p('窓[まど]から 海[うみ]が 見[み]える ところ', 'The sea view from the window')],
      answer: 3, why: '何より — above all — the sea view.' },
    { id: 'n3-p-late-reason', level: 'N3',
      intro: '会社[かいしゃ]で 男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は どうして 会議[かいぎ]に 遅[おく]れましたか。',
      lines: [
        l(M, '会議[かいぎ]、遅[おく]れたね。電車[でんしゃ]？', 'You were late to the meeting. The train?'),
        l(F, 'ううん、電車[でんしゃ]は 時間[じかん]どおりだったの。会社[かいしゃ]の 前[まえ]で お客様[きゃくさま]に 会[あ]って、道[みち]を 聞[き]かれたから 案内[あんない]して いたら 遅[おそ]く なっちゃって。', 'No, the train was on time. I met a customer outside the office who asked the way, and while I was showing them, I got late.'),
      ],
      choices: [p('電車[でんしゃ]が 遅[おく]れたから', 'The train was late'), p('寝坊[ねぼう]したから', 'She overslept'), p('お客様[きゃくさま]を 案内[あんない]して いたから', 'She was showing a customer the way'), p('会議[かいぎ]の 時間[じかん]を 間違[まちが]えたから', 'She got the time wrong')],
      answer: 2, why: 'The train was on time; she was guiding a customer.' },
    { id: 'n3-p-language-study', level: 'N3',
      intro: '女[おんな]の 留学生[りゅうがくせい]と 男[おとこ]の人[ひと]が 話[はな]しています。女[おんな]の 留学生[りゅうがくせい]は 日本語[にほんご]の 何[なに]が いちばん 難[むずか]しいと 言[い]って いますか。',
      voices: { F: 'young' },
      lines: [
        l(M, '日本語[にほんご]、上手[じょうず]に なったね。漢字[かんじ]は 大変[たいへん]じゃない？', 'Your Japanese has got good. Isn’t kanji hard?'),
        l(F, '漢字[かんじ]は 毎日[まいにち] 書[か]いて いるから、だいぶ 慣[な]れました。文法[ぶんぽう]も 大丈夫[だいじょうぶ]です。', 'I write kanji every day, so I’m quite used to it. Grammar is fine too.'),
        l(F, '困[こま]るのは 敬語[けいご]ですね。アルバイトで 使[つか]うんですが、いつも 間違[まちが]えて しまって。', 'What troubles me is keigo. I use it at my part-time job, but I always get it wrong.'),
      ],
      choices: [p('漢字[かんじ]', 'Kanji'), p('文法[ぶんぽう]', 'Grammar'), p('敬語[けいご]', 'Honorific language'), p('発音[はつおん]', 'Pronunciation')],
      answer: 2, why: 'Kanji and grammar are OK; keigo is what she struggles with.' },
    { id: 'n3-p-shop-closing', level: 'N3',
      intro: 'ラジオで 男[おとこ]の人[ひと]が 話[はな]しています。この 店[みせ]は どうして 閉[し]まりますか。',
      lines: [
        l(M, '駅前[えきまえ]の 本屋[ほんや]「みどり書店[しょてん]」が 今月末[こんげつまつ]で 閉店[へいてん]します。', 'Midori Books in front of the station will close at the end of this month.'),
        l(M, 'お客[きゃく]さんは 減[へ]って いなかったそうですが、建物[たてもの]が 古[ふる]く なり、取[と]り壊[こわ]される ことに なったため だそうです。店[みせ]の 人[ひと]は 新[あたら]しい 場所[ばしょ]を 探[さが]して いると 話[はな]して います。', 'Apparently customers hadn’t fallen off; the building has grown old and is to be demolished. The staff say they are looking for a new location.'),
      ],
      choices: [p('お客[きゃく]さんが 減[へ]ったから', 'Customers fell off'), p('建物[たてもの]が 壊[こわ]されるから', 'The building will be demolished'), p('店[みせ]の 人[ひと]が 年[とし]を とったから', 'The owner got old'), p('ネットの 本屋[ほんや]に 負[ま]けたから', 'Online shops beat it')],
      answer: 1, why: 'Customers hadn’t dropped; the old building is being torn down.' },
    { id: 'n2-p-why-quit-job', level: 'N2',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]が 会社[かいしゃ]を 辞[や]める いちばんの 理由[りゆう]は 何[なん]ですか。',
      lines: [
        l(M, '会社[かいしゃ]、辞[や]めるんだって？ 給料[きゅうりょう]に 不満[ふまん]でも あったの？', 'I hear you’re leaving the company? Unhappy with the pay?'),
        l(F, '給料[きゅうりょう]は 悪[わる]くないし、職場[しょくば]の 人[ひと]も いい 人[ひと]ばかりなんだけどね。', 'The pay isn’t bad, and everyone at work is nice.', '給料は悪くないし、職場のひとも、いいひとばかりなんだけどね。'),
        l(F, '前[まえ]から 環境[かんきょう]の 仕事[しごと]が したくて。ちょうど 募集[ぼしゅう]が あったから、今[いま] 挑戦[ちょうせん]しないと 後悔[こうかい]すると 思[おも]ったの。', 'I’ve wanted to work in the environment field for a long time. There happened to be an opening, and I felt I’d regret it if I didn’t try now.'),
      ],
      choices: [p('給料[きゅうりょう]が 安[やす]いから', 'The pay is low'), p('職場[しょくば]の 人間関係[にんげんかんけい]が 悪[わる]いから', 'Relationships at work are bad'), p('やりたかった 分野[ぶんや]の 仕事[しごと]に 挑戦[ちょうせん]したいから', 'She wants to try work in the field she always wanted'), p('家族[かぞく]の 事情[じじょう]で 引[ひ]っ越[こ]すから', 'She’s moving for family reasons')],
      answer: 2, why: 'Pay and people are fine; she wants to try environmental work.' },
    { id: 'n2-p-product-change', level: 'N2',
      intro: '会社[かいしゃ]で 男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 新[あたら]しい 商品[しょうひん]に ついて 話[はな]しています。女[おんな]の人[ひと]は 商品[しょうひん]の 何[なに]を 変[か]えるべきだと 言[い]って いますか。',
      lines: [
        l(M, '新[あたら]しい 飲[の]み物[もの]、お客様[きゃくさま]の アンケートでは 味[あじ]の 評価[ひょうか]が 高[たか]かったよ。', 'For the new drink, the customer survey rated the taste highly.'),
        l(F, 'ええ。値段[ねだん]も 問題[もんだい]ないと 思[おも]います。', 'Yes. And I don’t think the price is a problem.'),
        l(F, '気[き]に なるのは、棚[たな]に 並[なら]んだ 時[とき]に 目立[めだ]たない ことなんです。今[いま]の 地味[じみ]な 色[いろ]では、手[て]に 取[と]って もらえないんじゃ ないでしょうか。', 'What worries me is that it doesn’t stand out on the shelf. With the current dull colours, I doubt people will pick it up.'),
      ],
      choices: [p('味[あじ]', 'The taste'), p('値段[ねだん]', 'The price'), p('パッケージの 色[いろ]', 'The packaging colour'), p('量[りょう]', 'The amount')],
      answer: 2, why: 'Taste and price are fine; the dull packaging needs to change.' },
    { id: 'n2-p-library-hours', level: 'N2',
      intro: '市役所[しやくしょ]の 人[ひと]が 話[はな]しています。図書館[としょかん]の 開館[かいかん]時間[じかん]を 延[の]ばす 主[おも]な 目的[もくてき]は 何[なん]ですか。',
      lines: [
        l(F, '来月[らいげつ]から、市立[しりつ]図書館[としょかん]は 平日[へいじつ]の 閉館[へいかん]時間[じかん]を 午後[ごご] 六時[ろくじ]から 九時[くじ]に 延[の]ばします。', 'From next month, the city library will extend its weekday closing time from 6 p.m. to 9 p.m.'),
        l(F, 'これまで 利用者[りようしゃ]の 多[おお]くは 高齢者[こうれいしゃ]と 子[こ]どもでしたが、仕事[しごと]帰[がえ]りの 人[ひと]にも 気軽[きがる]に 利用[りよう]して もらう ことが ねらいです。', 'Until now most users were elderly people and children; the aim is to let people on their way home from work use it easily too.'),
      ],
      choices: [p('子[こ]どもの 勉強[べんきょう]の 場所[ばしょ]を 増[ふ]やすため', 'More study space for children'), p('働[はたら]いて いる 人[ひと]が 使[つか]いやすく するため', 'Make it easier for working people'), p('高齢者[こうれいしゃ]の 利用[りよう]を 増[ふ]やすため', 'More use by the elderly'), p('本[ほん]の 数[かず]を 増[ふ]やすため', 'More books')],
      answer: 1, why: 'The aim (ねらい) is people coming home from work.' },
    { id: 'n2-p-team-success', level: 'N2',
      intro: 'テレビで サッカーチームの 監督[かんとく]が 話[はな]しています。監督[かんとく]は チームが 強[つよ]く なった 理由[りゆう]は 何[なん]だと 言[い]って いますか。',
      lines: [
        l(F, '今年[ことし]は 優勝[ゆうしょう]でしたね。新[あたら]しい 選手[せんしゅ]の 活躍[かつやく]が 大[おお]きかったのでしょうか。', 'You won the title this year. Was it largely thanks to the new players?'),
        l(M, 'もちろん 彼[かれ]らも よく やって くれました。練習[れんしゅう]の 量[りょう]も 増[ふ]やしました。', 'Of course they did well, and we increased the amount of training.'),
        l(M, 'ですが、一番[いちばん]は 選手[せんしゅ]どうしが 試合中[しあいちゅう]に 声[こえ]を かけ合[あ]う ように なった ことです。それで 守[まも]りが 安定[あんてい]しました。', 'But the biggest thing is that the players started talking to each other during matches. That steadied our defence.'),
      ],
      choices: [p('新[あたら]しい 選手[せんしゅ]が 入[はい]った こと', 'New players joining'), p('練習[れんしゅう]を 増[ふ]やした こと', 'More training'), p('選手[せんしゅ]が 声[こえ]を かけ合[あ]う ように なった こと', 'Players calling to each other'), p('監督[かんとく]が 代[か]わった こと', 'A new manager')],
      answer: 2, why: '一番は — the players communicating during matches.' },
    { id: 'n2-p-hotel-complaint', level: 'N2',
      intro: 'ホテルで 女[おんな]の人[ひと]と フロントの 人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は 何[なに]に 困[こま]って いますか。',
      lines: [
        l(F, 'すみません、305号室[ごうしつ]の 者[もの]ですが。', 'Excuse me, I’m in room 305.', 'すみません、さんまるごごうしつの者ですが。'),
        l(M, 'はい、どう なさいましたか。エアコンの 調子[ちょうし]でしょうか。', 'Yes, what seems to be the matter? Is it the air conditioner?'),
        l(F, 'いえ、部屋[へや]は 快適[かいてき]なんですが、隣[となり]の 部屋[へや]の テレビの 音[おと]が 夜中[よなか]まで 聞[き]こえて きて、眠[ねむ]れなかったんです。', 'No, the room itself is comfortable, but I could hear the TV in the next room until the middle of the night and couldn’t sleep.'),
      ],
      choices: [p('エアコンが 壊[こわ]れて いる こと', 'The air conditioner is broken'), p('隣[となり]の 部屋[へや]が うるさい こと', 'The next room is noisy'), p('部屋[へや]が 狭[せま]い こと', 'The room is small'), p('テレビが つかない こと', 'The TV won’t turn on')],
      answer: 1, why: 'Not the air conditioner — the TV noise from next door.' },
    { id: 'n2-p-bike-commute', level: 'N2',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]が 自転車[じてんしゃ]で 通勤[つうきん]する ように なった いちばんの 理由[りゆう]は 何[なん]ですか。',
      lines: [
        l(F, '最近[さいきん]、自転車[じてんしゃ]で 来[き]てるんですね。運動[うんどう]の ためですか。', 'You’ve been coming by bike lately. Is it for the exercise?'),
        l(M, '体[からだ]にも いいし、交通費[こうつうひ]も かからないんですけどね。', 'It’s good for me, and it costs nothing in fares.'),
        l(M, '実[じつ]は、引[ひ]っ越[こ]して 電車[でんしゃ]だと 乗[の]り換[か]えが 二回[にかい]も ある ように なって しまって。自転車[じてんしゃ]なら 二十分[にじゅっぷん]で 着[つ]くので、その ほうが ずっと 早[はや]いんです。', 'Actually, since I moved, the train means changing twice. By bike it’s twenty minutes, which is much faster.'),
      ],
      choices: [p('健康[けんこう]の ため', 'For his health'), p('交通費[こうつうひ]を 節約[せつやく]する ため', 'To save on fares'), p('電車[でんしゃ]より 早[はや]く 着[つ]く から', 'It’s faster than the train'), p('電車[でんしゃ]が 混[こ]んで いる から', 'The trains are crowded')],
      answer: 2, why: 'Health and money are bonuses; after moving the bike is much faster.' },
  ]);

  add('gaiyou', [
    { id: 'n3-g-walking', level: 'N3',
      intro: 'テレビで 医者[いしゃ]が 話[はな]しています。',
      lines: [
        l(M, '運動[うんどう]を しなければ と 思[おも]って いても、なかなか 続[つづ]かない 人[ひと]が 多[おお]いようです。', 'Many people think they should exercise but can’t keep it up.'),
        l(M, '特別[とくべつ]な ことを する 必要[ひつよう]は ありません。一駅[ひとえき] 手前[てまえ]で 降[お]りて 歩[ある]く、エレベーターではなく 階段[かいだん]を 使[つか]う。それだけでも 体[からだ]は 変[か]わります。', 'You don’t need to do anything special. Get off one stop early and walk, take the stairs instead of the lift. That alone changes your body.'),
        l(M, '毎日[まいにち]の 生活[せいかつ]の 中[なか]で 少[すこ]しずつ 体[からだ]を 動[うご]かす ことが 大切[たいせつ]なのです。', 'What matters is moving a little at a time in your everyday life.'),
      ],
      question: '医者[いしゃ]が いちばん 言[い]いたい ことは 何[なん]ですか。',
      choices: [r('スポーツクラブに 通[かよ]うと いい', 'You should go to a gym'), r('生活[せいかつ]の 中[なか]で 少[すこ]しずつ 体[からだ]を 動[うご]かすと いい', 'Move a little within daily life'), r('エレベーターは 使[つか]わない ほうが いい', 'Never use lifts'), r('電車[でんしゃ]に 乗[の]らない ほうが いい', 'Don’t take trains')],
      answer: 1, why: 'The examples all support moving a little in everyday life.' },
    { id: 'n3-g-school-lunch', level: 'N3',
      intro: '小学校[しょうがっこう]で 校長先生[こうちょうせんせい]が 保護者[ほごしゃ]に 話[はな]しています。',
      lines: [
        l(F, '来月[らいげつ]から、給食[きゅうしょく]に 地元[じもと]の 農家[のうか]で とれた 野菜[やさい]を 使[つか]う ことに なりました。', 'From next month, school lunches will use vegetables grown by local farmers.'),
        l(F, '新鮮[しんせん]で おいしいだけでなく、子[こ]どもたちが 自分[じぶん]の 町[まち]の 農業[のうぎょう]に 関心[かんしん]を 持[も]つ きっかけに なれば と 考[かんが]えて います。', 'Besides being fresh and tasty, we hope it will get the children interested in their own town’s farming.'),
        l(F, '秋[あき]には 畑[はたけ]の 見学[けんがく]も 予定[よてい]して います。', 'We’re also planning a visit to the fields in autumn.'),
      ],
      question: '校長先生[こうちょうせんせい]は 何[なに]に ついて 話[はな]して いますか。',
      choices: [r('給食[きゅうしょく]の 値段[ねだん]が 変[か]わる こと', 'Lunch prices changing'), r('給食[きゅうしょく]に 地元[じもと]の 野菜[やさい]を 使[つか]う こと', 'Using local vegetables in school lunches'), r('秋[あき]の 遠足[えんそく]の 場所[ばしょ]', 'Where the autumn trip goes'), r('野菜[やさい]が 嫌[きら]いな 子[こ]どもの こと', 'Children who dislike vegetables')],
      answer: 1, why: 'The talk is about local vegetables in school lunches and why.' },
    { id: 'n3-g-phone-manners', level: 'N3',
      intro: '会社[かいしゃ]で 先輩[せんぱい]が 新入社員[しんにゅうしゃいん]に 話[はな]しています。',
      lines: [
        l(F, '電話[でんわ]に 出[で]たら、まず 会社[かいしゃ]の 名前[なまえ]と 自分[じぶん]の 名前[なまえ]を 言[い]って ください。', 'When you answer the phone, first say the company name and your own name.'),
        l(F, '相手[あいて]の 名前[なまえ]や 用件[ようけん]は、必[かなら]ず メモを 取[と]りましょう。わからない ことは その 場[ば]で 答[こた]えず、確認[かくにん]して から 折[お]り返[かえ]し 電話[でんわ]を すると 伝[つた]えて ください。', 'Always write down the caller’s name and business. Don’t answer what you don’t know on the spot — say you’ll check and call back.'),
      ],
      question: '先輩[せんぱい]は 何[なに]に ついて 話[はな]して いますか。',
      choices: [r('電話[でんわ]の 受[う]け方[かた]', 'How to answer the phone'), r('メモの 書[か]き方[かた]', 'How to write notes'), r('会社[かいしゃ]の 歴史[れきし]', 'The company’s history'), r('お客様[きゃくさま]への 謝[あやま]り方[かた]', 'How to apologise to customers')],
      answer: 0, why: 'Name first, take notes, call back: how to handle phone calls.' },
    { id: 'n3-g-festival', level: 'N3',
      intro: 'ラジオで 女[おんな]の人[ひと]が 話[はな]しています。',
      lines: [
        l(F, '毎年[まいとし] 人気[にんき]の 夏祭[なつまつ]りですが、今年[ことし]は 会場[かいじょう]の 近[ちか]くに 車[くるま]を 止[と]める 場所[ばしょ]が ありません。', 'The summer festival is popular every year, but this year there’s nowhere to park near the venue.'),
        l(F, 'お越[こ]しの 際[さい]は、駅[えき]から 出[で]る 無料[むりょう]の バスを ご利用[りよう]ください。バスは 夕方[ゆうがた] 四時[よじ]から 十五分[じゅうごふん]おきに 出[で]て います。', 'When you come, please use the free bus from the station. Buses run every fifteen minutes from four in the evening.'),
      ],
      question: '女[おんな]の人[ひと]が いちばん 伝[つた]えたい ことは 何[なん]ですか。',
      choices: [r('祭[まつ]りの 日[ひ]が 変[か]わった', 'The festival date changed'), r('祭[まつ]りには 車[くるま]で 来[こ]ないで バスを 使[つか]って ほしい', 'Come by the bus, not by car'), r('駐車場[ちゅうしゃじょう]が 新[あたら]しく できた', 'A new car park opened'), r('バスの 料金[りょうきん]が 上[あ]がった', 'The bus fare went up')],
      answer: 1, why: 'No parking, so use the free bus from the station.' },
    { id: 'n3-g-review-tips', level: 'N3',
      intro: '日本語[にほんご]学校[がっこう]で 先生[せんせい]が 話[はな]しています。',
      lines: [
        l(M, '新[あたら]しい 言葉[ことば]を 覚[おぼ]えても、すぐ 忘[わす]れて しまうと いう 人[ひと]が いますね。', 'Some of you say you forget new words right after learning them.'),
        l(M, '人[ひと]は 一度[いちど] 覚[おぼ]えた ことも、使[つか]わなければ 忘[わす]れます。習[なら]った 日[ひ]の 夜[よる]、次[つぎ]の 日[ひ]、一週間後[いっしゅうかんご]と、何回[なんかい]か 見直[みなお]して ください。', 'People forget what they learned if they don’t use it. Look over it several times: that night, the next day, a week later.'),
      ],
      question: '先生[せんせい]は 何[なに]に ついて 話[はな]して いますか。',
      choices: [r('言葉[ことば]を 忘[わす]れない ための 復習[ふくしゅう]の 仕方[しかた]', 'How to review so you don’t forget words'), r('新[あたら]しい 教科書[きょうかしょ]', 'A new textbook'), r('夜[よる] 勉強[べんきょう]する ことの 悪[わる]い 点[てん]', 'Why studying at night is bad'), r('来週[らいしゅう]の テストの 範囲[はんい]', 'Next week’s test')],
      answer: 0, why: 'Review several times so words stick.' },
    { id: 'n3-g-bike-rules', level: 'N3',
      intro: '警察官[けいさつかん]が 高校[こうこう]で 話[はな]しています。',
      lines: [
        l(M, '自転車[じてんしゃ]は 便利[べんり]ですが、事故[じこ]も 増[ふ]えて います。', 'Bikes are convenient, but accidents are increasing too.'),
        l(M, 'スマートフォンを 見[み]ながら 乗[の]ったり、夜[よる] ライトを つけないで 走[はし]ったり するのは とても 危険[きけん]です。それから、ヘルメットも かぶる ように して ください。', 'Riding while looking at your phone or riding at night without a light is very dangerous. And please wear a helmet.'),
      ],
      question: '警察官[けいさつかん]は 何[なに]に ついて 話[はな]して いますか。',
      choices: [r('自転車[じてんしゃ]の 安全[あんぜん]な 乗[の]り方[かた]', 'Riding bikes safely'), r('自転車[じてんしゃ]の 選[えら]び方[かた]', 'Choosing a bike'), r('スマートフォンの 使[つか]い方[かた]', 'Using smartphones'), r('ヘルメットの 値段[ねだん]', 'Helmet prices')],
      answer: 0, why: 'Phones, lights, helmets: all about riding safely.' },
    { id: 'n2-g-four-day-week', level: 'N2',
      intro: 'テレビで 経営者[けいえいしゃ]が 話[はな]しています。',
      lines: [
        l(M, '当社[とうしゃ]では 一年前[いちねんまえ]から 週[しゅう] 四日[よっか] 勤務[きんむ]を 取[と]り入[い]れました。', 'A year ago our company introduced a four-day working week.'),
        l(M, '働[はたら]く 時間[じかん]が 減[へ]れば 売[う]り上[あ]げも 減[へ]るのではないかと 心配[しんぱい]して いましたが、実際[じっさい]には 会議[かいぎ]を 短[みじか]く するなど 工夫[くふう]が 生[う]まれ、売[う]り上[あ]げは 前年[ぜんねん]と 変[か]わりませんでした。', 'We worried that fewer hours would mean lower sales, but in fact ideas like shorter meetings emerged and sales were the same as the year before.'),
        l(M, 'それに、休[やす]みが 増[ふ]えた ことで 社員[しゃいん]の 満足度[まんぞくど]が 上[あ]がり、辞[や]める 人[ひと]も 減[へ]りました。', 'On top of that, with more time off, staff satisfaction rose and fewer people quit.'),
      ],
      question: '経営者[けいえいしゃ]は 週[しゅう] 四日[よっか] 勤務[きんむ]に ついて どう 考[かんが]えて いますか。',
      choices: [r('売[う]り上[あ]げが 減[へ]ったので やめたい', 'Sales fell, so he wants to stop'), r('売[う]り上[あ]げを 保[たも]ちながら 社員[しゃいん]の 満足度[まんぞくど]も 上[あ]がり、成功[せいこう]だった', 'Sales held and staff are happier: a success'), r('社員[しゃいん]は 喜[よろこ]んだが、会議[かいぎ]が 増[ふ]えて 困[こま]った', 'Staff liked it but meetings increased'), r('まだ 始[はじ]めた ばかりで わからない', 'It’s too early to tell')],
      answer: 1, why: 'Sales unchanged, happier staff, fewer leaving — he sees it as a success.' },
    { id: 'n2-g-food-waste', level: 'N2',
      intro: 'ラジオで 女[おんな]の人[ひと]が 話[はな]しています。',
      lines: [
        l(F, 'スーパーでは、賞味期限[しょうみきげん]が 近[ちか]い 商品[しょうひん]を 値下[ねさ]げして 売[う]る ことが 増[ふ]えて います。', 'Supermarkets are increasingly selling items close to their best-before date at a discount.'),
        l(F, '「古[ふる]い ものは 買[か]いたくない」と 思[おも]う 方[かた]も いるでしょう。しかし、賞味期限[しょうみきげん]は おいしく 食[た]べられる 期間[きかん]の 目安[めやす]で、過[す]ぎても すぐに 食[た]べられなく なる わけでは ありません。', 'Some may think, “I don’t want to buy old things.” But the best-before date is a guide to when food tastes best; it doesn’t mean it becomes inedible right after.'),
        l(F, 'すぐに 食[た]べる ものなら、こうした 商品[しょうひん]を 選[えら]ぶ ことが、捨[す]てられる 食品[しょくひん]を 減[へ]らす ことに つながります。', 'If you’ll eat it soon, choosing these items helps reduce the food that gets thrown away.'),
      ],
      question: '女[おんな]の人[ひと]が いちばん 言[い]いたい ことは 何[なん]ですか。',
      choices: [r('賞味期限[しょうみきげん]が 過[す]ぎた ものは すぐ 捨[す]てるべきだ', 'Throw food out once it passes the date'), r('期限[きげん]の 近[ちか]い 値下[ねさ]げ品[ひん]を 選[えら]ぶ ことで 食品[しょくひん]の 無駄[むだ]を 減[へ]らせる', 'Buying discounted near-date food reduces waste'), r('スーパーは 値下[ねさ]げを やめるべきだ', 'Supermarkets should stop discounts'), r('古[ふる]い 食品[しょくひん]は 体[からだ]に 悪[わる]い', 'Old food is bad for you')],
      answer: 1, why: 'Her point is that buying near-date items cuts food waste.' },
    { id: 'n2-g-handwriting', level: 'N2',
      intro: '講演会[こうえんかい]で 男[おとこ]の人[ひと]が 話[はな]しています。',
      lines: [
        l(M, '最近[さいきん]は 何[なん]でも パソコンや スマートフォンで 書[か]く ように なり、手[て]で 字[じ]を 書[か]く 機会[きかい]が ずいぶん 減[へ]りました。', 'These days we write everything on computers and phones, and chances to write by hand have fallen a lot.'),
        l(M, 'もちろん 便利[べんり]ですが、手書[てが]きには 手書[てが]きの よさが あります。手[て]で 書[か]いた ほうが 内容[ないよう]を 覚[おぼ]えやすいと いう 研究[けんきゅう]も ありますし、手書[てが]きの 手紙[てがみ]には 書[か]いた 人[ひと]の 気持[きも]ちが 伝[つた]わります。', 'Of course it’s convenient, but handwriting has its own merits. Research suggests you remember content better when you write it by hand, and a handwritten letter conveys the writer’s feelings.'),
        l(M, '時[とき]には ペンを 持[も]って みては いかがでしょうか。', 'Why not pick up a pen now and then?'),
      ],
      question: '男[おとこ]の人[ひと]は 何[なに]に ついて 話[はな]して いますか。',
      choices: [r('パソコンの 便利[べんり]な 使[つか]い方[かた]', 'Handy computer tips'), r('手[て]で 字[じ]を 書[か]く ことの よさ', 'The merits of writing by hand'), r('きれいな 字[じ]を 書[か]く 練習[れんしゅう]', 'Practising neat handwriting'), r('手紙[てがみ]の 書[か]き方[かた]の 決[き]まり', 'Rules for writing letters')],
      answer: 1, why: 'Memory and feelings: the merits of handwriting.' },
    { id: 'n2-g-tourism-town', level: 'N2',
      intro: 'テレビで 町長[ちょうちょう]が 話[はな]しています。',
      lines: [
        l(F, 'わが 町[まち]には 有名[ゆうめい]な 観光地[かんこうち]は ありません。しかし、ここ 数年[すうねん]、海外[かいがい]からの 旅行者[りょこうしゃ]が 増[ふ]えて います。', 'Our town has no famous sights. But in the last few years, more travellers have come from abroad.'),
        l(F, '旅行者[りょこうしゃ]が 求[もと]めて いるのは、農家[のうか]に 泊[と]まって 田植[たう]えを 手伝[てつだ]ったり、地元[じもと]の 人[ひと]と 料理[りょうり]を 作[つく]ったり する、普段[ふだん]の 暮[く]らしの 体験[たいけん]なのです。', 'What they want is experience of ordinary life: staying at farms, helping plant rice, cooking with local people.'),
        l(F, '今後[こんご]も、特別[とくべつ]な 施設[しせつ]を 作[つく]るより、こうした 体験[たいけん]を 増[ふ]やして いきたいと 考[かんが]えて います。', 'From now on, rather than building special facilities, we want to offer more of these experiences.'),
      ],
      question: '町長[ちょうちょう]は 何[なに]に ついて 話[はな]して いますか。',
      choices: [r('新[あたら]しい 観光施設[かんこうしせつ]の 計画[けいかく]', 'Plans for a new tourist facility'), r('普段[ふだん]の 暮[く]らしを 体験[たいけん]する 観光[かんこう]の 魅力[みりょく]', 'The appeal of experiencing everyday life'), r('農家[のうか]の 人手[ひとで]不足[ぶそく]', 'The farm labour shortage'), r('海外[かいがい]旅行[りょこう]の 人気[にんき]の 国[くに]', 'Popular countries for travel abroad')],
      answer: 1, why: 'Visitors want everyday-life experiences, and the town will offer more.' },
    { id: 'n2-g-reading-children', level: 'N2',
      intro: '講演会[こうえんかい]で 女[おんな]の人[ひと]が 話[はな]しています。',
      lines: [
        l(F, '子[こ]どもに 本[ほん]を 好[す]きに なって ほしいと 願[ねが]う 親[おや]は 多[おお]いでしょう。', 'Many parents hope their children will come to love books.'),
        l(F, 'ですが、「本[ほん]を 読[よ]みなさい」と 言[い]うだけでは 逆効果[ぎゃくこうか]です。子[こ]どもは 大人[おとな]の する ことを まねします。親[おや]自身[じしん]が 楽[たの]しそうに 本[ほん]を 読[よ]む 姿[すがた]を 見[み]せる ことが、何[なに]よりの 近道[ちかみち]なのです。', 'But just saying “Read a book!” backfires. Children copy what adults do. Letting them see you enjoying a book yourself is the best shortcut.'),
      ],
      question: '女[おんな]の人[ひと]が いちばん 言[い]いたい ことは 何[なん]ですか。',
      choices: [r('子[こ]どもに 毎日[まいにち] 本[ほん]を 読[よ]ませるべきだ', 'Make children read every day', '子どもに、毎日、ほんを読ませるべきだ'), r('親[おや]が 楽[たの]しんで 本[ほん]を 読[よ]む 姿[すがた]を 見[み]せると いい', 'Parents should be seen enjoying books'), r('子[こ]どもに 本[ほん]を たくさん 買[か]って あげると いい', 'Buy children lots of books'), r('子[こ]どもは 大人[おとな]の 言[い]う ことを 聞[き]かない', 'Children don’t listen to adults')],
      answer: 1, why: 'Children copy adults, so show them you enjoy reading.' },
  ]);

  add('hatsuwa', [
    { id: 'n3-h-borrow-charger', level: 'N3', scene: { setting: 'office', left: 'office', right: 'officeWoman', prop: 'smartphone', holder: 'left', arrow: 'left' },
      intro: 'スマートフォンの 電池[でんち]が なくなりそうです。同僚[どうりょう]に 充電器[じゅうでんき]を 借[か]りたいです。何[なん]と 言[い]いますか。',
      choices: [r('充電器[じゅうでんき]、貸[か]して あげようか。', 'Shall I lend you a charger?'), r('充電器[じゅうでんき]、ちょっと 貸[か]して もらえない？', 'Could you lend me your charger for a bit?'), r('充電器[じゅうでんき]、借[か]りた ことが ある？', 'Have you ever borrowed a charger?')], answer: 1, why: '〜てもらえない？ asks a favour.' },
    { id: 'n3-h-leave-message', level: 'N3', scene: { setting: 'office', left: 'officeWoman', right: 'man', prop: 'phone', holder: 'left', arrow: 'left' }, replyBy: 'F',
      intro: '電話[でんわ]で 山田[やまだ]さんを 呼[よ]びましたが、いませんでした。伝言[でんごん]を 頼[たの]みたいです。何[なん]と 言[い]いますか。',
      choices: [r('では、伝言[でんごん]を お願[ねが]いできますか。', 'Then could I leave a message?'), r('では、伝言[でんごん]を 伝[つた]えましょうか。', 'Then shall I pass on a message?'), r('では、山田[やまだ]さんに 代[か]わります。', 'Then I’ll put Yamada on.')], answer: 0, why: '伝言をお願いできますか asks to leave a message.' },
    { id: 'n3-h-compliment-dish', level: 'N3', scene: { setting: 'home', left: 'friendMan', right: 'friend', arrow: 'left' },
      intro: '友[とも]だちの 家[いえ]で 料理[りょうり]を ごちそうに なりました。とても おいしかったです。何[なん]と 言[い]いますか。',
      choices: [r('これ、本当[ほんとう]に おいしいね。どう やって 作[つく]るの？', 'This is really good. How do you make it?'), r('これ、作[つく]って あげようか。', 'Shall I make this for you?'), r('おいしく 作[つく]れなくて ごめんね。', 'Sorry I couldn’t make it tasty.')], answer: 0, why: 'Praise it and ask how it’s made.' },
    { id: 'n3-h-refuse-politely', level: 'N3', scene: { setting: 'office', left: 'office', right: 'officeWoman', arrow: 'left' },
      intro: '先輩[せんぱい]に 飲[の]みに 誘[さそ]われましたが、今日[きょう]は 用事[ようじ]が あります。何[なん]と 言[い]いますか。',
      choices: [r('すみません、今日[きょう]は ちょっと 用事[ようじ]が あって…。また 誘[さそ]って ください。', 'Sorry, I have something on today… please ask me again.'), r('いいですね。何時[なんじ]に しますか。', 'Sounds good. What time?'), r('今日[きょう]は 飲[の]みに 行[い]きましょう。', 'Let’s go for a drink today.')], answer: 0, why: 'Decline softly with 〜て… and ask to be invited again.' },
  ]);

  add('sokuji', [
    q('N3', 'n3-s-forgot-umbrella', F, 'あ、かさ 持[も]って くるの 忘[わす]れちゃった。', 'Oh, I forgot to bring an umbrella.', M,
      [r('じゃあ、ぼくのに 入[はい]って いく？', 'Then want to share mine?'), r('かさを 持[も]って きて よかったね。', 'Good thing you brought one.'), r('忘[わす]れないで ください。', 'Please don’t forget.')], 0, 'Offer to share your umbrella.'),
    q('N3', 'n3-s-cant-decide', M, 'どっちの 色[いろ]に するか、なかなか 決[き]められないんだ。', 'I just can’t decide which colour to get.', F,
      [r('もう 決[き]めて おいたよ。', 'I already decided.'), r('わたしなら 青[あお]に するけど。', 'I’d go with blue, myself.'), r('決[き]めて くれて ありがとう。', 'Thanks for deciding.')], 1, 'Give your opinion to help him decide.'),
    q('N3', 'n3-s-sounds-hard', F, '今週[こんしゅう]は 毎日[まいにち] 残業[ざんぎょう]なんです。', 'I’m working overtime every day this week.', M,
      [r('それは 大変[たいへん]ですね。無理[むり]しないで くださいね。', 'That’s tough. Don’t overdo it.'), r('残業[ざんぎょう]して よかったですね。', 'Good that you did overtime.'), r('来週[らいしゅう]は 残業[ざんぎょう]しましょう。', 'Let’s do overtime next week.')], 0, 'Sympathise: 大変ですね.'),
    q('N3', 'n3-s-just-arrived', M, 'あれ、もう 来[き]てたの？', 'Oh, you’re here already?', F,
      [r('うん、さっき 着[つ]いた ところ。', 'Yes, I just got here.'), r('うん、これから 行[い]く ところ。', 'Yes, I’m about to go.'), r('うん、来[こ]なかったよ。', 'Yes, I didn’t come.')], 0, '〜たところ: just arrived.'),
    q('N3', 'n3-s-lend-notes', F, '昨日[きのう]の 授業[じゅぎょう]の ノート、見[み]せて もらえない？', 'Could you show me your notes from yesterday’s class?', M,
      [r('いいよ。はい、どうぞ。', 'Sure, here you go.'), r('うん、見[み]せて もらったよ。', 'Yes, they showed me.'), r('ノートを 買[か]いに 行[い]こう。', 'Let’s go buy notebooks.')], 0, 'Grant the favour.'),
    q('N3', 'n3-s-what-happened', M, 'どうしたの？ 元気[げんき]ないね。', 'What’s up? You seem down.', F,
      [r('うん、元気[げんき]だよ。ありがとう。', 'Yes, I’m fine, thanks.'), r('実[じつ]は 財布[さいふ]を なくしちゃって。', 'Actually, I lost my wallet.'), r('元気[げんき]を 出[だ]して ね。', 'Cheer up.')], 1, 'Explain what is wrong.'),
    q('N3', 'n3-s-hurry-up', F, '急[いそ]がないと、電車[でんしゃ]に 間[ま]に合[あ]わないよ。', 'If we don’t hurry we’ll miss the train.', M,
      [r('うん、間[ま]に合[あ]って よかった。', 'Yes, glad we made it.'), r('わかった、走[はし]ろう。', 'OK, let’s run.'), r('電車[でんしゃ]が 来[き]たね。', 'The train came.')], 1, 'Respond to the warning: let’s run.'),
    q('N3', 'n3-s-taste-test', M, 'この スープ、ちょっと 味[あじ]が 薄[うす]くない？', 'Isn’t this soup a bit bland?', F,
      [r('そう？ じゃあ、塩[しお]を 少[すこ]し 入[い]れようか。', 'Really? Then shall I add a little salt?'), r('うん、濃[こ]くて おいしいね。', 'Yes, it’s rich and good.'), r('スープは 飲[の]まなかったよ。', 'I didn’t have the soup.')], 0, 'Offer to fix the taste.'),
    q('N3', 'n3-s-seat-free', F, 'すみません、この 席[せき]、空[あ]いて いますか。', 'Excuse me, is this seat free?', M,
      [r('はい、どうぞ。', 'Yes, go ahead.'), r('はい、空[あ]けました。', 'Yes, I opened it.'), r('いいえ、座[すわ]りません。', 'No, I won’t sit.')], 0, 'Offer the free seat.'),
    q('N3', 'n3-s-keep-secret', M, 'これ、まだ みんなには 言[い]わないで おいて ね。', 'Don’t tell everyone about this yet, OK?', F,
      [r('うん、みんなに 言[い]って おくね。', 'OK, I’ll tell everyone.'), r('わかった、だれにも 言[い]わないよ。', 'Got it, I won’t tell anyone.'), r('もう 言[い]わなかったよ。', 'I already didn’t say.')], 1, 'Promise to keep it quiet.'),
    q('N2', 'n2-s-by-all-means', M, 'もし よろしければ、今度[こんど] 工場[こうじょう]を ご案内[あんない]しましょうか。', 'If you like, shall I show you around the factory next time?', F,
      [r('ぜひ お願[ねが]いします。', 'Yes, I’d love that.'), r('ご案内[あんない]いただきました。', 'You showed me around.'), r('工場[こうじょう]に ご案内[あんない]ください。', 'Please guide me to a factory.')], 0, 'Accept the offer: ぜひお願いします.'),
    q('N2', 'n2-s-no-wonder-tired', F, '昨日[きのう]、結局[けっきょく] 朝[あさ]の 四時[よじ]まで 資料[しりょう]を 作[つく]って いたんです。', 'In the end I was making the materials until four in the morning yesterday.', M,
      [r('道理[どうり]で 眠[ねむ]そうな わけだ。', 'No wonder you look sleepy.'), r('早[はや]く 寝[ね]られて よかったね。', 'Glad you got to bed early.'), r('四時[よじ]に 起[お]きたんですね。', 'So you got up at four.')], 0, '道理で〜わけだ: no wonder.'),
    q('N2', 'n2-s-only-if', M, '雨[あめ]さえ 降[ふ]らなければ、明日[あした]の 試合[しあい]は 勝[か]てると 思[おも]うんだけど。', 'As long as it doesn’t rain, I think we can win tomorrow’s match.', F,
      [r('晴[は]れると いいね。', 'Hope it’s sunny.'), r('雨[あめ]で 勝[か]てて よかったね。', 'Good you won thanks to the rain.'), r('試合[しあい]は 中止[ちゅうし]だったね。', 'The match was cancelled.')], 0, '〜さえ〜なければ: hope for good weather.'),
    q('N2', 'n2-s-cant-believe', F, 'えっ、田中[たなか]さんが 会社[かいしゃ]を 辞[や]める なんて、信[しん]じられない。', 'What? Tanaka-san quitting? I can’t believe it.', M,
      [r('ぼくも 昨日[きのう] 聞[き]いて 驚[おどろ]いたよ。', 'I was surprised too when I heard yesterday.'), r('信[しん]じて くれて ありがとう。', 'Thanks for believing me.'), r('田中[たなか]さんは 辞[や]めないそうだよ。', 'Apparently Tanaka won’t quit.')], 0, 'Share the surprise.'),
    q('N2', 'n2-s-could-you-check', M, 'お忙[いそが]しい ところ 申[もう]し訳[わけ]ないんですが、この 書類[しょるい]に 目[め]を 通[とお]して いただけませんか。', 'Sorry to bother you when you’re busy, but could you look over this document?', F,
      [r('ええ、お昼[ひる]までには 見[み]て おきます。', 'Sure, I’ll look at it by lunchtime.'), r('ええ、目[め]が 疲[つか]れました。', 'Yes, my eyes are tired.'), r('書類[しょるい]を 通[とお]りました。', 'I passed the document.')], 0, '目を通す means look over; agree.'),
    q('N2', 'n2-s-almost-missed', F, 'あと 一分[いっぷん] 遅[おそ]かったら、飛行機[ひこうき]に 乗[の]り遅[おく]れる ところだったよ。', 'One more minute and I would have missed the plane.', M,
      [r('間[ま]に合[あ]って よかったね。', 'Glad you made it.'), r('乗[の]り遅[おく]れて 残念[ざんねん]だったね。', 'Too bad you missed it.'), r('次[つぎ]の 飛行機[ひこうき]は 何時[なんじ]？', 'What time is the next plane?')], 0, '〜ところだった: she nearly missed it but made it.'),
    q('N2', 'n2-s-as-expected', M, '新[あたら]しい 部長[ぶちょう]、さすがに 話[はなし]が わかりやすいですね。', 'The new manager explains things clearly, as you’d expect.', F,
      [r('ええ、長年[ながねん] 営業[えいぎょう]を して こられた 方[かた]ですからね。', 'Yes, he spent many years in sales, after all.'), r('ええ、わかりにくかったですね。', 'Yes, it was hard to follow.'), r('部長[ぶちょう]に 話[はな]して おきます。', 'I’ll tell the manager.')], 0, 'さすが: agree and give the reason.'),
    q('N2', 'n2-s-not-worth', F, 'あの 映画[えいが]、二時間[にじかん] 並[なら]んで 見[み]る ほどでは なかったよ。', 'That film wasn’t worth queueing two hours for.', M,
      [r('そんなに 期待[きたい]外[はず]れだったの？', 'Was it that disappointing?'), r('二時間[にじかん] 並[なら]んで よかったね。', 'Glad you queued for two hours.'), r('じゃあ、ぼくも 早[はや]く 並[なら]ばなきゃ。', 'Then I’d better queue early too.')], 0, '〜ほどではない: it wasn’t that good.'),
    q('N2', 'n2-s-take-over', M, '来週[らいしゅう]から 出張[しゅっちょう]なので、その 間[あいだ]、この 仕事[しごと]を お願[ねが]いしても いいですか。', 'I’m away on business from next week — may I leave this work to you while I’m gone?', F,
      [r('わかりました。わからない ことが あったら 連絡[れんらく]しますね。', 'All right. I’ll contact you if anything’s unclear.'), r('出張[しゅっちょう]、お願[ねが]いします。', 'Please go on the business trip.'), r('来週[らいしゅう]は お休[やす]みですね。', 'So you’re off next week.')], 0, 'Accept the handover.'),
    q('N2', 'n2-s-hardly-matters', F, 'ごめん、約束[やくそく]の 時間[じかん]に 五分[ごふん] 遅[おく]れそう。', 'Sorry, I’m going to be five minutes late.', M,
      [r('五分[ごふん]ぐらい、気[き]に しなくて いいよ。', 'Five minutes is nothing, don’t worry.'), r('五分[ごふん] 早[はや]く 着[つ]いたね。', 'You arrived five minutes early.'), r('遅[おく]れないで よかった。', 'Glad you weren’t late.')], 0, 'Reassure her.'),
    q('N2', 'n2-s-wish-known', M, 'セールが 昨日[きのう]までだったなんて、知[し]ってたら 行[い]ったのに。', 'If I’d known the sale ended yesterday, I would have gone.', F,
      [r('え、教[おし]えて あげれば よかったね。', 'Oh, I should have told you.'), r('セールに 行[い]けて よかったね。', 'Glad you made the sale.'), r('明日[あした]まで セールだよ。', 'The sale runs till tomorrow.')], 0, '〜のに: regret; she wishes she had told him.'),
    q('N2', 'n2-s-not-necessarily', F, '高[たか]い ものなら 品質[ひんしつ]も いいはずですよね。', 'If it’s expensive, the quality must be good, right?', M,
      [r('高[たか]いから いいとは 限[かぎ]らないよ。', 'Expensive doesn’t necessarily mean good.'), r('品質[ひんしつ]が いいから 安[やす]いね。', 'It’s cheap because the quality is good.'), r('高[たか]く なる はずだったね。', 'It was supposed to get pricier.')], 0, '〜とは限らない: not necessarily.'),
  ]);
})(typeof window !== 'undefined' ? window : globalThis);
