(function (global) {
  'use strict';

  // N2 questions (format: listening-data.js): business and everyday talk at
  // natural speed, printed choices in 問題1 and 2, longer talks in 概要理解,
  // and a lot of 即時応答 with keigo and indirect replies.
  const add = global.LISTENING_ADD;
  const p = (ja, en) => ({ type: 'phrase', ja, en });
  const r = (ja, en, say) => (say ? { ja, en, say } : { ja, en });
  const M = 'M', F = 'F';
  const l = (who, ja, en, say) => (say ? { who, ja, en, say } : { who, ja, en });

  add('kadai', [
    { id: 'n2-estimate', level: 'N2',
      intro: '会社[かいしゃ]で 部長[ぶちょう]と 女[おんな]の 社員[しゃいん]が 話[はな]しています。女[おんな]の 社員[しゃいん]は この 後[あと] まず 何[なに]を しなければ なりませんか。',
      lines: [
        l(M, '例[れい]の 見積書[みつもりしょ]、取引先[とりひきさき]に もう 送[おく]った？', 'Have you sent that quotation to the client yet?'),
        l(F, 'いえ、金額[きんがく]の 確認[かくにん]が まだでして。経理[けいり]の 山田[やまだ]さんが 今日[きょう]は お休[やす]みなんです。', 'No, the amounts haven’t been checked yet. Yamada-san in accounting is off today.'),
        l(M, 'そうか。でも、先方[せんぽう]は 今日[きょう]中[じゅう]に 欲[ほ]しいと 言[い]って いたからなあ。', 'I see. But they said they wanted it today.'),
        l(M, '金額[きんがく]は 僕[ぼく]が 見[み]て おくから、送[おく]る 前[まえ]に、遅[おく]れる ことを 先方[せんぽう]に 電話[でんわ]で 一言[ひとこと] 伝[つた]えて おいて くれる？ 送[おく]るのは 夕方[ゆうがた]で いいから。', 'I’ll check the amounts myself. Before sending it, could you give them a quick call to say it’ll be a little late? Sending it this evening is fine.'),
      ],
      choices: [p('見積書[みつもりしょ]を 取引先[とりひきさき]に 送[おく]る', 'Send the quotation'), p('経理[けいり]の 山田[やまだ]さんに 連絡[れんらく]する', 'Contact Yamada-san in accounting'), p('取引先[とりひきさき]に 電話[でんわ]を する', 'Phone the client'), p('金額[きんがく]を 確認[かくにん]する', 'Check the amounts')],
      answer: 2, why: 'The manager checks the amounts; before sending it she must phone the client to warn of the delay.' },
    { id: 'n2-seminar-signup', level: 'N2',
      intro: '大学[だいがく]で 職員[しょくいん]と 男[おとこ]の 学生[がくせい]が 話[はな]しています。男[おとこ]の 学生[がくせい]は この 後[あと] 何[なに]を しますか。',
      voices: { M: 'young' },
      lines: [
        l(M, 'すみません、来月[らいげつ]の 就職[しゅうしょく]セミナーに 申[もう]し込[こ]みたいんですが。', 'Excuse me, I’d like to sign up for next month’s job-hunting seminar.'),
        l(F, '申[もう]し込[こ]みは 大学[だいがく]の ホームページから お願[ねが]いして います。ただ、その 前[まえ]に 学生[がくせい]番号[ばんごう]で ログインできるように して おかないと いけないんです。', 'Sign-up is through the university website. But before that, you need to be able to log in with your student number.'),
        l(M, 'あ、パスワードを 忘[わす]れて しまって…。', 'Oh, I’ve forgotten my password…'),
        l(F, 'それでしたら、まず 隣[となり]の 窓口[まどぐち]で パスワードを 新[あたら]しく 発行[はっこう]して もらって ください。学生証[がくせいしょう]が 必要[ひつよう]です。', 'In that case, first get a new password issued at the next counter. You’ll need your student ID.'),
        l(M, '学生証[がくせいしょう]なら 持[も]って います。', 'I have my student ID with me.'),
      ],
      choices: [p('ホームページから 申[もう]し込[こ]む', 'Sign up on the website'), p('隣[となり]の 窓口[まどぐち]へ 行[い]く', 'Go to the next counter'), p('学生証[がくせいしょう]を 取[と]りに 行[い]く', 'Fetch his student ID'), p('学生[がくせい]番号[ばんごう]を 調[しら]べる', 'Look up his student number')],
      answer: 1, why: 'He can’t log in without a new password, issued at the next counter; he already has his student ID.' },
    { id: 'n2-repair-ac', level: 'N2',
      intro: '電話[でんわ]で 女[おんな]の人[ひと]と 修理[しゅうり]会社[がいしゃ]の 人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は この 後[あと] まず 何[なに]を しますか。',
      lines: [
        l(F, 'エアコンから 急[きゅう]に 水[みず]が 垂[た]れて きたんです。修理[しゅうり]に 来[き]て いただけますか。', 'Water has suddenly started dripping from my air conditioner. Could you come and repair it?'),
        l(M, 'かしこまりました。ただ、最短[さいたん]でも あさってに なって しまいます。', 'Certainly. But the earliest we can come is the day after tomorrow.'),
        l(M, 'それまでは 運転[うんてん]を 止[と]めて いただいて、念[ねん]の ため コンセントも 抜[ぬ]いて おいて ください。床[ゆか]が 濡[ぬ]れる ようでしたら、タオルを 敷[し]いて おいて いただければ。', 'Until then, please switch it off, and to be safe unplug it as well. If the floor gets wet, you could put a towel down.'),
        l(F, 'わかりました。床[ゆか]は もう 拭[ふ]いて あります。', 'I see. I’ve already wiped the floor.'),
      ],
      choices: [p('エアコンを 止[と]めて コンセントを 抜[ぬ]く', 'Switch off and unplug the air conditioner'), p('床[ゆか]を 拭[ふ]く', 'Wipe the floor'), p('修理[しゅうり]の 日[ひ]を 決[き]める', 'Fix a repair date'), p('新[あたら]しい エアコンを 買[か]う', 'Buy a new air conditioner')],
      answer: 0, why: 'The floor is already wiped; she must switch it off and unplug it until the repair.' },
    { id: 'n2-event-venue', level: 'N2',
      intro: 'イベント会社[がいしゃ]で 男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は この 後[あと] 何[なに]を しますか。',
      lines: [
        l(M, '来月[らいげつ]の 展示会[てんじかい]、参加者[さんかしゃ]が 予想[よそう]より かなり 増[ふ]えそうなんだ。', 'It looks like a lot more people than expected will come to next month’s exhibition.'),
        l(F, 'では、会場[かいじょう]を 広[ひろ]い ところに 変[か]えた ほうが いいでしょうか。', 'Then should we change to a bigger venue?'),
        l(M, '今[いま]から 会場[かいじょう]を 変[か]えるのは 難[むずか]しいよ。それより、時間[じかん]を 午前[ごぜん]と 午後[ごご]に 分[わ]けて、人[ひと]が 集中[しゅうちゅう]しない ように したい。', 'It’s hard to change the venue now. Rather, I want to split it into morning and afternoon sessions so people don’t all come at once.'),
        l(M, '参加者[さんかしゃ]への 案内[あんない]は 決[き]まってから で いいから、まず 会場[かいじょう]に 時間[じかん]を 延長[えんちょう]できるか 問[と]い合[あ]わせて くれる？', 'The notice to participants can wait until it’s decided. First, could you ask the venue whether we can extend the hours?'),
      ],
      choices: [p('広[ひろ]い 会場[かいじょう]を 探[さが]す', 'Look for a bigger venue'), p('参加者[さんかしゃ]に 案内[あんない]を 送[おく]る', 'Send participants a notice'), p('会場[かいじょう]に 問[と]い合[あ]わせる', 'Contact the venue'), p('参加者[さんかしゃ]の 数[かず]を 数[かぞ]え直[なお]す', 'Recount the participants')],
      answer: 2, why: 'No venue change; first ask the venue about extending the hours. The notice comes later.' },
    { id: 'n2-doctor-advice', level: 'N2',
      intro: '病院[びょういん]で 医者[いしゃ]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は これから まず 何[なに]を しますか。',
      lines: [
        l(F, '検査[けんさ]の 結果[けっか]ですが、血圧[けつあつ]が 少[すこ]し 高[たか]めですね。', 'About your test results — your blood pressure is a little high.'),
        l(M, '薬[くすり]を 飲[の]まなければ なりませんか。', 'Do I have to take medicine?'),
        l(F, '今[いま]の 段階[だんかい]では、薬[くすり]は まだ 必要[ひつよう]ありません。運動[うんどう]も 大切[たいせつ]ですが、急[きゅう]に 激[はげ]しい 運動[うんどう]を 始[はじ]めるのは かえって よくないんです。', 'At this stage you don’t need medicine yet. Exercise matters too, but suddenly starting hard exercise can actually be bad.'),
        l(F, 'まずは 食事[しょくじ]の 塩分[えんぶん]を 減[へ]らす ことから 始[はじ]めて ください。一[いっ]か月後[げつご]に もう 一度[いちど] 測[はか]りましょう。', 'Start by cutting down the salt in your meals. Let’s measure again in a month.'),
      ],
      choices: [p('薬[くすり]を 飲[の]み始[はじ]める', 'Start taking medicine'), p('激[はげ]しい 運動[うんどう]を 始[はじ]める', 'Start hard exercise'), p('塩分[えんぶん]を 控[ひか]える', 'Cut down on salt'), p('毎日[まいにち] 血圧[けつあつ]を 測[はか]る', 'Measure his blood pressure daily')],
      answer: 2, why: 'No medicine yet and no sudden hard exercise; まずは塩分を減らすことから.' },
    { id: 'n2-hotel-change', level: 'N2',
      intro: '旅行[りょこう]会社[がいしゃ]で 女[おんな]の人[ひと]と 係[かかり]の 人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は この 後[あと] 何[なに]を しますか。',
      lines: [
        l(F, '来週[らいしゅう]の ツアーですが、一人[ひとり] 参加[さんか]できなく なって しまって。キャンセル料[りょう]は かかりますか。', 'About next week’s tour — one person can no longer come. Is there a cancellation fee?'),
        l(M, '出発[しゅっぱつ]の 一週間[いっしゅうかん] 前[まえ]を 過[す]ぎて いますので、料金[りょうきん]の 半分[はんぶん]が かかって しまいます。', 'It’s less than a week before departure, so half the price will be charged.'),
        l(M, 'ただ、ほかの 方[かた]に 代[か]わって いただく ことは 無料[むりょう]で できますよ。その 場合[ばあい]は 明日[あした]までに お名前[なまえ]を お知[し]らせください。', 'However, you can have someone else go in their place for free. In that case, please let us know their name by tomorrow.'),
        l(F, 'それなら、妹[いもうと]に 行[い]けるか 聞[き]いて みます。', 'Then I’ll ask my younger sister if she can go.'),
      ],
      choices: [p('キャンセル料[りょう]を 払[はら]う', 'Pay the cancellation fee'), p('ツアーを 全部[ぜんぶ] キャンセルする', 'Cancel the whole tour'), p('妹[いもうと]に 都合[つごう]を 聞[き]く', 'Ask her sister if she’s free'), p('出発[しゅっぱつ]の 日[ひ]を 変[か]える', 'Change the departure date')],
      answer: 2, why: 'Instead of paying half, a replacement is free — so she asks her sister if she can go.' },
    { id: 'n2-printer-trouble', level: 'N2',
      intro: '会社[かいしゃ]で 男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は この 後[あと] まず 何[なに]を しますか。',
      lines: [
        l(M, '会議[かいぎ]の 資料[しりょう]を 印刷[いんさつ]しようと したら、プリンターが 動[うご]かないんですよ。', 'I tried to print the meeting documents but the printer won’t work.'),
        l(F, 'ああ、あれ、今朝[けさ]から 調子[ちょうし]が 悪[わる]いのよ。業者[ぎょうしゃ]には もう 連絡[れんらく]して あるけど、来[く]るのは 午後[ごご]なの。', 'Oh, that’s been playing up since this morning. I’ve already called the repair company, but they’re not coming until the afternoon.'),
        l(M, '会議[かいぎ]は 十一時[じゅういちじ]からなんですけど…。', 'The meeting is at eleven…'),
        l(F, '三階[さんがい]の プリンターなら 使[つか]えるわよ。データを 送[おく]って、取[と]りに 行[い]けば いいわ。', 'You can use the printer on the third floor. Send the data and go and pick it up.'),
      ],
      choices: [p('業者[ぎょうしゃ]に 連絡[れんらく]する', 'Call the repair company'), p('三階[さんがい]の プリンターで 印刷[いんさつ]する', 'Print on the third-floor printer'), p('会議[かいぎ]の 時間[じかん]を 変[か]える', 'Change the meeting time'), p('午後[ごご]まで 待[ま]つ', 'Wait until the afternoon')],
      answer: 1, why: 'The repair company is already called but comes too late; he prints on the third floor.' },
    { id: 'n2-volunteer', level: 'N2',
      intro: '市役所[しやくしょ]で 男[おとこ]の人[ひと]と 職員[しょくいん]が 話[はな]しています。男[おとこ]の人[ひと]は この 後[あと] 何[なに]を しますか。',
      lines: [
        l(M, '川[かわ]の 清掃[せいそう]ボランティアに 参加[さんか]したいんですが。', 'I’d like to join the river clean-up volunteers.'),
        l(F, 'ありがとうございます。参加[さんか]には 事前[じぜん]の 登録[とうろく]が 必要[ひつよう]で、登録[とうろく]用紙[ようし]は こちらに ございます。', 'Thank you. You need to register in advance; here is the registration form.'),
        l(F, '保険[ほけん]に 入[はい]って いただく 必要[ひつよう]が ありますが、それは 市[し]の ほうで 手続[てつづ]きしますので、ご心配[しんぱい]なく。', 'You need to be insured, but the city handles that, so don’t worry.'),
        l(M, 'わかりました。じゃあ、ここで 書[か]いて いきます。', 'I see. Then I’ll fill it in here.'),
      ],
      choices: [p('保険[ほけん]に 申[もう]し込[こ]む', 'Apply for insurance'), p('登録[とうろく]用紙[ようし]に 記入[きにゅう]する', 'Fill in the registration form'), p('清掃[せいそう]の 道具[どうぐ]を 買[か]う', 'Buy cleaning tools'), p('家[いえ]で 用紙[ようし]を 書[か]いて 送[おく]る', 'Fill in the form at home and post it')],
      answer: 1, why: 'The city handles insurance; he fills in the registration form there and then.' },
    { id: 'n2-thesis', level: 'N2',
      intro: '大学[だいがく]で 先生[せんせい]と 女[おんな]の 学生[がくせい]が 卒業[そつぎょう]論文[ろんぶん]に ついて 話[はな]しています。女[おんな]の 学生[がくせい]は まず 何[なに]を しますか。',
      voices: { F: 'young' },
      lines: [
        l(F, 'テーマは 決[き]まったんですが、アンケートを いつ 始[はじ]めれば いいか 迷[まよ]って いて。', 'I’ve decided my topic, but I’m not sure when to start the survey.'),
        l(M, 'アンケートの 前[まえ]に、まず 先行[せんこう]研究[けんきゅう]を きちんと 読[よ]んで おく ことですね。似[に]た 調査[ちょうさ]が もう あるかもしれないし。', 'Before the survey, you should first read the previous research properly. A similar study may already exist.'),
        l(F, '質問[しつもん]の 内容[ないよう]は 先[さき]に 考[かんが]えて おいた ほうが いいですか。', 'Should I think about the questions first?'),
        l(M, 'それは 読[よ]んでからの ほうが いい 質問[しつもん]が 作[つく]れますよ。', 'You’ll write better questions after you’ve read.'),
      ],
      choices: [p('アンケートを 始[はじ]める', 'Start the survey'), p('質問[しつもん]を 考[かんが]える', 'Write the questions'), p('先行[せんこう]研究[けんきゅう]を 読[よ]む', 'Read the previous research'), p('テーマを 決[き]め直[なお]す', 'Rethink her topic')],
      answer: 2, why: 'まず先行研究を読んでおくこと — reading comes before the questions and the survey.' },
    { id: 'n2-new-staff', level: 'N2',
      intro: '店[みせ]で 店長[てんちょう]と 新[あたら]しい アルバイトの 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は 今日[きょう] まず 何[なに]を しますか。',
      lines: [
        l(M, '今日[きょう]から よろしく。レジの 仕事[しごと]は 来週[らいしゅう]から 覚[おぼ]えて もらうから。', 'Welcome aboard. You’ll start learning the till next week.'),
        l(F, 'はい。今日[きょう]は 何[なに]を すれば いいでしょうか。', 'OK. What should I do today?'),
        l(M, '品出[しなだ]しを お願[ねが]いしたいんだけど、その 前[まえ]に 制服[せいふく]に 着替[きが]えて きて。ロッカーの 鍵[かぎ]は これね。', 'I’d like you to stock the shelves, but before that, go and change into your uniform. Here’s your locker key.'),
        l(F, 'わかりました。', 'Understood.'),
      ],
      choices: [p('レジの 仕事[しごと]を 覚[おぼ]える', 'Learn the till'), p('商品[しょうひん]を 棚[たな]に 並[なら]べる', 'Stock the shelves'), p('制服[せいふく]に 着替[きが]える', 'Change into her uniform'), p('ロッカーの 鍵[かぎ]を 借[か]りに 行[い]く', 'Go and borrow a locker key')],
      answer: 2, why: 'The till is next week; その前に制服に着替えて — change first, then stock the shelves.' },
  ]);

  add('point', [
    { id: 'n2-why-transfer', level: 'N2',
      intro: '会社[かいしゃ]で 女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は どうして 転勤[てんきん]を 希望[きぼう]しましたか。',
      lines: [
        l(F, '大阪[おおさか]支社[ししゃ]への 転勤[てんきん]、自分[じぶん]から 希望[きぼう]したんですって？ 給料[きゅうりょう]が 上[あ]がるから？', 'I heard you asked for the transfer to the Osaka branch yourself. Because of a pay rise?'),
        l(M, 'いや、給料[きゅうりょう]は ほとんど 変[か]わらないんだ。仕事[しごと]の 内容[ないよう]も 今[いま]と 同[おな]じだし。', 'No, the pay hardly changes. And the work is the same as now.'),
        l(M, '実[じつ]は、大阪[おおさか]に いる 父[ちち]の 体[からだ]の 調子[ちょうし]が よくなくて ね。近[ちか]くに いて あげたいと 思[おも]って。', 'Actually, my father in Osaka isn’t in good health. I want to be near him.'),
      ],
      choices: [p('給料[きゅうりょう]が 上[あ]がるから', 'His pay goes up'), p('新[あたら]しい 仕事[しごと]が したいから', 'He wants new work'), p('父親[ちちおや]の 近[ちか]くに いたいから', 'He wants to be near his father'), p('大阪[おおさか]が 好[す]きだから', 'He likes Osaka')],
      answer: 2, why: 'Same pay and work; his father in Osaka is unwell and he wants to be close by.' },
    { id: 'n2-product-problem', level: 'N2',
      intro: '会議[かいぎ]で 男[おとこ]の人[ひと]が 新[あたら]しい 商品[しょうひん]に ついて 話[はな]しています。この 商品[しょうひん]の 一番[いちばん]の 問題[もんだい]は 何[なん]ですか。',
      lines: [
        l(M, '先月[せんげつ] 発売[はつばい]した 掃除機[そうじき]ですが、デザインに ついては 好評[こうひょう]で、値段[ねだん]に ついての 不満[ふまん]も ほとんど ありません。', 'About the vacuum cleaner we launched last month: the design is well received, and there are almost no complaints about the price.'),
        l(M, '吸[す]う 力[ちから]も 十分[じゅうぶん]だと いう 声[こえ]が 多[おお]い ものの、本体[ほんたい]が 重[おも]くて、階段[かいだん]で 使[つか]いにくいと いう 意見[いけん]が かなり 寄[よ]せられて います。', 'Many say the suction is good enough, but we’ve had a lot of feedback that the unit is heavy and hard to use on stairs.'),
        l(M, '次[つぎ]の 製品[せいひん]では この 点[てん]を 最優先[さいゆうせん]で 改善[かいぜん]したいと 考[かんが]えて います。', 'In the next model we want to make improving this the top priority.'),
      ],
      choices: [p('デザインが よくない こと', 'The design is poor'), p('値段[ねだん]が 高[たか]い こと', 'It’s expensive'), p('吸[す]う 力[ちから]が 弱[よわ]い こと', 'Weak suction'), p('重[おも]くて 使[つか]いにくい こと', 'It’s heavy and awkward')],
      answer: 3, why: 'Design, price and suction are fine; it’s too heavy to use on stairs.' },
    { id: 'n2-chose-uni', level: 'N2',
      intro: '男[おとこ]の 学生[がくせい]と 女[おんな]の 学生[がくせい]が 話[はな]しています。女[おんな]の 学生[がくせい]は どうして この 大学[だいがく]を 選[えら]びましたか。',
      voices: { M: 'young', F: 'young' },
      lines: [
        l(M, 'この 大学[だいがく]を 選[えら]んだのは、やっぱり 有名[ゆうめい]だから？', 'Did you choose this university because it’s famous?'),
        l(F, 'ううん、名前[なまえ]で 選[えら]んだ わけじゃないの。家[いえ]からは かえって 遠[とお]いくらいだし。', 'No, I didn’t choose it for its name. It’s actually rather far from home.'),
        l(F, '高校[こうこう]の 時[とき]に 読[よ]んだ 本[ほん]を 書[か]いた 先生[せんせい]が ここで 教[おし]えて いて、どうしても その 先生[せんせい]の ゼミに 入[はい]りたかったんだ。', 'A professor who wrote a book I read in high school teaches here, and I really wanted to join his seminar.'),
      ],
      choices: [p('有名[ゆうめい]な 大学[だいがく]だから', 'It’s a famous university'), p('家[いえ]から 近[ちか]いから', 'It’s close to home'), p('習[なら]いたい 先生[せんせい]が いるから', 'A professor she wants to study with is there'), p('学費[がくひ]が 安[やす]いから', 'Fees are low')],
      answer: 2, why: 'Not its name or location; the author of a book she loved teaches there.' },
    { id: 'n2-restaurant-change', level: 'N2',
      intro: 'テレビで 女[おんな]の 人[ひと]が レストランの 店長[てんちょう]に インタビューを しています。店長[てんちょう]は 店[みせ]を 変[か]えた ことで、何[なに]が 一番[いちばん] よかったと 言[い]って いますか。',
      lines: [
        l(F, '昨年[さくねん]、メニューを 半分[はんぶん]に 減[へ]らされたそうですね。', 'I hear you cut your menu in half last year.'),
        l(M, 'ええ。売[う]り上[あ]げは 正直[しょうじき] あまり 変[か]わって いないんですが、材料[ざいりょう]の 無駄[むだ]が 減[へ]りました。', 'Yes. Honestly, sales haven’t changed much, but there’s less wasted food.'),
        l(M, 'それより 何[なに]より、一[ひと]つ 一[ひと]つの 料理[りょうり]に 時間[じかん]を かけられる ように なって、常連[じょうれん]の お客様[きゃくさま]から 「前[まえ]より おいしく なった」と 言[い]われる ことが 増[ふ]えたんです。これが 一番[いちばん] うれしいですね。', 'Above all, we can spend more time on each dish, and regulars tell us more often that it’s tastier than before. That’s what makes me happiest.'),
      ],
      choices: [p('売[う]り上[あ]げが 増[ふ]えた こと', 'Sales went up'), p('材料[ざいりょう]の 無駄[むだ]が 減[へ]った こと', 'Less wasted food'), p('料理[りょうり]が おいしく なったと 言[い]われる こと', 'Customers say the food is better'), p('新[あたら]しい 客[きゃく]が 増[ふ]えた こと', 'More new customers')],
      answer: 2, why: 'Sales are flat and waste is down, but 何より regulars say the food is better.' },
    { id: 'n2-commute-change', level: 'N2',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]が 自転車[じてんしゃ]通勤[つうきん]を 始[はじ]めた 一番[いちばん]の 理由[りゆう]は 何[なん]ですか。',
      lines: [
        l(M, '最近[さいきん] 自転車[じてんしゃ]で 通勤[つうきん]して いるんですね。健康[けんこう]の ためですか。', 'You’ve been cycling to work lately. For your health?'),
        l(F, '結果的[けっかてき]に 体[からだ]には いいんですけど、それが きっかけじゃ ないんです。交通費[こうつうひ]も 会社[かいしゃ]から 出[で]て いますし。', 'It does turn out to be good for me, but that’s not what started it. And the company pays my travel costs anyway.'),
        l(F, '朝[あさ]の 満員[まんいん]電車[でんしゃ]が どうしても 我慢[がまん]できなく なったんです。毎朝[まいあさ] 疲[つか]れて 会社[かいしゃ]に 着[つ]くのが 嫌[いや]で。', 'I just couldn’t stand the packed morning trains any more. I hated arriving at work exhausted every morning.'),
      ],
      choices: [p('健康[けんこう]の ため', 'For her health'), p('交通費[こうつうひ]を 節約[せつやく]する ため', 'To save on fares'), p('満員[まんいん]電車[でんしゃ]が 嫌[いや]だったから', 'She hated the packed trains'), p('会社[かいしゃ]が 近[ちか]く なったから', 'Her office moved closer')],
      answer: 2, why: 'Health is a side effect and fares are paid; she couldn’t stand the packed trains.' },
    { id: 'n2-book-sales', level: 'N2',
      intro: 'ラジオで 本屋[ほんや]の 店長[てんちょう]が 話[はな]しています。店長[てんちょう]は 最近[さいきん] 売[う]れて いる 本[ほん]の 特徴[とくちょう]は 何[なん]だと 言[い]って いますか。',
      lines: [
        l(M, '最近[さいきん] よく 売[う]れて いるのは、意外[いがい]にも 分厚[ぶあつ]い 小説[しょうせつ]ではなく、写真[しゃしん]や 絵[え]が 多[おお]い 本[ほん]でも ないんです。', 'What sells well lately, surprisingly, isn’t thick novels, nor books full of photos and pictures.'),
        l(M, '一[ひと]つの 話[はなし]が 五分[ごふん]ほどで 読[よ]み終[お]わる 短[みじか]い 話[はなし]を 集[あつ]めた 本[ほん]が、通勤[つうきん]の 途中[とちゅう]に 読[よ]めると いうので、若[わか]い 会社員[かいしゃいん]を 中心[ちゅうしん]に 人気[にんき]なんですよ。', 'Collections of short stories you can finish in about five minutes each are popular, mainly with young office workers, because they can read them on the way to work.'),
      ],
      choices: [p('長[なが]い 小説[しょうせつ]である こと', 'They are long novels'), p('写真[しゃしん]が 多[おお]い こと', 'They have many photos'), p('短[みじか]い 時間[じかん]で 読[よ]める こと', 'They can be read in a short time'), p('値段[ねだん]が 安[やす]い こと', 'They are cheap')],
      answer: 2, why: 'Neither thick novels nor picture books: short stories you can read in five minutes.' },
    { id: 'n2-meeting-postponed', level: 'N2',
      intro: '会社[かいしゃ]で 男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。会議[かいぎ]は どうして 延期[えんき]に なりましたか。',
      lines: [
        l(M, '明日[あした]の 会議[かいぎ]、延期[えんき]に なったって 本当[ほんとう]？ 部長[ぶちょう]の 出張[しゅっちょう]？', 'Is it true tomorrow’s meeting was postponed? The manager’s business trip?'),
        l(F, '部長[ぶちょう]は 予定[よてい]どおり 戻[もど]られるわよ。会議室[かいぎしつ]も 押[お]さえて あるし。', 'The manager is back as planned. And the room is booked.'),
        l(F, '取引先[とりひきさき]から 届[とど]く はずの データが 遅[おく]れて いて、それが ないと 話[はな]し合[あ]えないのよ。', 'The data we were supposed to get from the client is late, and we can’t discuss anything without it.'),
      ],
      choices: [p('部長[ぶちょう]が 出張[しゅっちょう]中[ちゅう]だから', 'The manager is away'), p('会議室[かいぎしつ]が 使[つか]えないから', 'The meeting room is unavailable'), p('必要[ひつよう]な データが 届[とど]いて いないから', 'The data they need hasn’t arrived'), p('参加者[さんかしゃ]が 集[あつ]まらないから', 'Not enough people can attend')],
      answer: 2, why: 'The manager and the room are fine; the client’s data hasn’t arrived.' },
    { id: 'n2-gym-quit', level: 'N2',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は どうして スポーツクラブを やめましたか。',
      lines: [
        l(F, 'スポーツクラブ、やめちゃったの？ 会費[かいひ]が 高[たか]かった？', 'You quit the gym? Was the membership too expensive?'),
        l(M, '会費[かいひ]は まあ 仕方[しかた]ないと 思[おも]ってたんだ。設備[せつび]も 新[あたら]しかったし。', 'I’d accepted the fee. And the equipment was new.'),
        l(M, 'ただ、仕事[しごと]の 時間[じかん]が 変[か]わって、営業[えいぎょう]時間[じかん]内[ない]に 行[い]けなく なっちゃったんだよ。それで 行[い]かないのに 払[はら]い続[つづ]けるのも ばからしいと 思[おも]って。', 'But my working hours changed and I can’t get there while it’s open. Paying without going seemed silly.'),
      ],
      choices: [p('会費[かいひ]が 高[たか]かったから', 'The fee was too high'), p('設備[せつび]が 古[ふる]かったから', 'The equipment was old'), p('開[あ]いて いる 時間[じかん]に 行[い]けなく なったから', 'He can no longer go while it’s open'), p('けがを したから', 'He got injured')],
      answer: 2, why: 'His working hours changed, so he can’t go during opening hours.' },
    { id: 'n2-seminar-feedback', level: 'N2',
      intro: 'セミナーの 後[あと]で 男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は セミナーの 何[なに]が 不満[ふまん]でしたか。',
      lines: [
        l(M, '今日[きょう]の セミナー、どうだった？ 講師[こうし]の 話[はなし]、わかりやすかったよね。', 'How was today’s seminar? The speaker was easy to follow, wasn’t he?'),
        l(F, 'うん、話[はなし]は よかった。資料[しりょう]も 丁寧[ていねい]だったし。', 'Yes, the talk was good. And the materials were thorough.'),
        l(F, 'でも、質問[しつもん]の 時間[じかん]が ほとんど なかったのが 残念[ざんねん]。聞[き]きたい ことが たくさん あったのに。', 'But it was a pity there was hardly any time for questions. I had lots I wanted to ask.'),
      ],
      choices: [p('話[はなし]が わかりにくかった こと', 'The talk was hard to follow'), p('資料[しりょう]が 足[た]りなかった こと', 'There weren’t enough materials'), p('質問[しつもん]の 時間[じかん]が 短[みじか]かった こと', 'Too little time for questions'), p('会場[かいじょう]が 狭[せま]かった こと', 'The room was cramped')],
      answer: 2, why: 'The talk and materials were good; there was barely time for questions.' },
    { id: 'n2-app-popular', level: 'N2',
      intro: 'テレビで 男[おとこ]の人[ひと]が 新[あたら]しい アプリに ついて 話[はな]しています。この アプリが 人気[にんき]の 理由[りゆう]は 何[なん]ですか。',
      lines: [
        l(M, 'この 家計簿[かけいぼ]アプリ、機能[きのう]の 多[おお]さでは ほかの アプリに かないません。デザインも ごく 普通[ふつう]です。', 'This household-budget app can’t compete with others on features, and the design is very ordinary.'),
        l(M, 'それでも 利用者[りようしゃ]が 増[ふ]え続[つづ]けて いるのは、レシートを カメラで 撮[と]るだけで、金額[きんがく]が 自動的[じどうてき]に 入力[にゅうりょく]される からなんです。面倒[めんどう]な ことが 苦手[にがて]な 人[ひと]でも 続[つづ]けられると 評判[ひょうばん]です。', 'Its users keep increasing because you just photograph a receipt and the amounts are entered automatically. People say even those who hate fiddly tasks can keep it up.'),
      ],
      choices: [p('機能[きのう]が 多[おお]い こと', 'It has lots of features'), p('デザインが いい こと', 'Good design'), p('入力[にゅうりょく]が 簡単[かんたん]な こと', 'Entering data is easy'), p('無料[むりょう]で 使[つか]える こと', 'It’s free')],
      answer: 2, why: 'Not features or design; photographing a receipt enters the amounts automatically.' },
    { id: 'n2-moving-reason', level: 'N2',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は どうして 郊外[こうがい]に 引[ひ]っ越[こ]す ことに しましたか。',
      lines: [
        l(M, '郊外[こうがい]に 引[ひ]っ越[こ]すんだって？ 通勤[つうきん]、大変[たいへん]に ならない？', 'You’re moving out to the suburbs? Won’t your commute get harder?'),
        l(F, '週[しゅう]に 三日[みっか]は 在宅[ざいたく]勤務[きんむ]だから、そんなに 気[き]に ならないの。', 'I work from home three days a week, so I don’t mind much.'),
        l(F, '家賃[やちん]が 安[やす]く なるのも うれしいけど、何[なに]より 子[こ]どもが 思[おも]い切[き]り 遊[あそ]べる 広[ひろ]い 庭[にわ]が ある 家[いえ]に 住[す]みたかったの。', 'Lower rent is nice too, but more than anything I wanted a house with a big garden where the kids can play freely.'),
      ],
      choices: [p('在宅[ざいたく]勤務[きんむ]が 増[ふ]えたから', 'She works from home more'), p('家賃[やちん]が 安[やす]いから', 'The rent is lower'), p('庭[にわ]の ある 家[いえ]に 住[す]みたいから', 'She wants a house with a garden'), p('会社[かいしゃ]が 引[ひ]っ越[こ]したから', 'Her company moved')],
      answer: 2, why: 'Working from home makes it possible and the rent helps, but 何より a garden for the kids.' },
    { id: 'n2-late-delivery', level: 'N2',
      intro: '電話[でんわ]で 男[おとこ]の人[ひと]と 店[みせ]の 人[ひと]が 話[はな]しています。商品[しょうひん]が 届[とど]くのが 遅[おく]れて いる 理由[りゆう]は 何[なん]ですか。',
      lines: [
        l(M, '先週[せんしゅう] 注文[ちゅうもん]した 椅子[いす]が まだ 届[とど]かないんですが。', 'The chair I ordered last week still hasn’t arrived.'),
        l(F, '大変[たいへん] 申[もう]し訳[わけ]ございません。お客様[きゃくさま]の ご注文[ちゅうもん]は 確[たし]かに 承[うけたまわ]って おります。', 'We are very sorry. We have certainly received your order.'),
        l(F, '実[じつ]は、工場[こうじょう]で 部品[ぶひん]が 不足[ふそく]して おりまして、生産[せいさん]が 止[と]まって いるんです。来週[らいしゅう]には 再開[さいかい]する 予定[よてい]でございます。', 'The truth is, the factory is short of parts and production has stopped. It is due to restart next week.'),
      ],
      choices: [p('注文[ちゅうもん]が 届[とど]いて いなかったから', 'The order never reached them'), p('配達[はいたつ]の 人[ひと]が 足[た]りないから', 'There aren’t enough delivery staff'), p('部品[ぶひん]が 足[た]りなくて 作[つく]れないから', 'There aren’t enough parts to make it'), p('住所[じゅうしょ]が 間違[まちが]って いたから', 'The address was wrong')],
      answer: 2, why: 'The order was received; the factory is short of parts (部品が不足).' },
  ]);

  const g = (id, intro, lines, question, choices, answer, why, extra = {}) => Object.assign({ id, level: 'N2', intro, lines, question, choices, answer, why }, extra);
  add('gaiyou', [
    g('n2-g-remote', '会社[かいしゃ]の 説明会[せつめいかい]で 人事[じんじ]の 人[ひと]が 話[はな]しています。', [
      l(M, '当社[とうしゃ]では 三年前[さんねんまえ]から、週[しゅう]に 二日[ふつか]まで 自宅[じたく]で 働[はたら]ける 制度[せいど]を 取[と]り入[い]れて います。', 'Three years ago we introduced a system that lets staff work from home up to two days a week.'),
      l(M, '初[はじ]めは 仕事[しごと]の 効率[こうりつ]が 下[さ]がるのではと いう 心配[しんぱい]も ありましたが、実際[じっさい]には 通勤[つうきん]の 疲[つか]れが 減[へ]った ことで、集中力[しゅうちゅうりょく]が 上[あ]がったと いう 声[こえ]が 多[おお]く 聞[き]かれます。', 'At first some worried efficiency would drop, but in fact we hear a lot that concentration has improved, because people are less tired from commuting.'),
      l(M, '一方[いっぽう]で、同僚[どうりょう]と 話[はな]す 機会[きかい]が 減[へ]ったと 感[かん]じる 社員[しゃいん]も いるため、月[つき]に 一度[いちど]は 全員[ぜんいん]が 出社[しゅっしゃ]する 日[ひ]を 設[もう]けて います。', 'On the other hand, some feel they talk to colleagues less, so we have a day each month when everyone comes in.'),
    ], '人事[じんじ]の 人[ひと]は 主[おも]に 何[なに]に ついて 話[はな]して いますか。', [
      r('在宅[ざいたく]勤務[きんむ]を 取[と]り入[い]れた 結果[けっか]', 'The results of introducing remote work'), r('通勤[つうきん]時間[じかん]を 短[みじか]く する 方法[ほうほう]', 'Ways to shorten commuting'), r('同僚[どうりょう]との 付[つ]き合[あ]い方[かた]', 'How to get on with colleagues'), r('新[あたら]しい 会社[かいしゃ]の 建物[たてもの]', 'The company’s new building'),
    ], 0, 'The whole talk is about how working from home has turned out: better focus, less contact, a monthly office day.'),
    g('n2-g-plastic-bags', 'ラジオで 専門家[せんもんか]が 話[はな]しています。', [
      l(F, 'レジ袋[ぶくろ]が 有料[ゆうりょう]に なって、袋[ふくろ]を 持[も]ち歩[ある]く 人[ひと]は 確[たし]かに 増[ふ]えました。', 'Since plastic bags started costing money, more people certainly carry their own.'),
      l(F, 'しかし、レジ袋[ぶくろ]は プラスチックごみ 全体[ぜんたい]の ほんの 一部[いちぶ]に すぎません。食品[しょくひん]の 包装[ほうそう]や ペットボトルの ほうが はるかに 多[おお]いのです。', 'But plastic bags are only a tiny part of all plastic waste. Food packaging and plastic bottles are far more.'),
      l(F, '袋[ふくろ]だけで 満足[まんぞく]せず、普段[ふだん]の 買[か]い物[もの]全体[ぜんたい]を 見直[みなお]す ことが 大切[たいせつ]だと 思[おも]います。', 'I think it’s important not to stop at bags, but to rethink our everyday shopping as a whole.'),
    ], '専門家[せんもんか]が 一番[いちばん] 言[い]いたい ことは 何[なん]ですか。', [
      r('レジ袋[ぶくろ]を もっと 高[たか]く するべきだ', 'Plastic bags should cost more'), r('レジ袋[ぶくろ]以外[いがい]の ごみにも 目[め]を 向[む]けるべきだ', 'We should look at waste beyond plastic bags'), r('ペットボトルは 使[つか]わない ほうが いい', 'It’s better not to use plastic bottles'), r('買[か]い物[もの]の 回数[かいすう]を 減[へ]らすべきだ', 'We should shop less often'),
    ], 1, 'Bags are a small part; her point is to rethink all the plastic in our shopping (袋だけで満足せず).'),
    g('n2-g-hobby-book', '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。', [
      l(F, '最近[さいきん] 料理[りょうり]教室[きょうしつ]に 通[かよ]い始[はじ]めたんだって？', 'I hear you’ve started going to cooking classes.'),
      l(M, 'うん。料理[りょうり]が うまく なりたいと いうより、仕事[しごと]以外[いがい]の 知[し]り合[あ]いが 欲[ほ]しくて ね。', 'Yes. Not so much to get better at cooking, more because I wanted to know people outside work.'),
      l(M, '会社[かいしゃ]と 家[いえ]の 往復[おうふく]だけだと、話[はな]す 相手[あいて]が いつも 同[おな]じでしょう。教室[きょうしつ]には 学生[がくせい]から お年寄[としよ]りまで いて、話[はなし]を するのが 楽[たの]しいんだ。', 'If it’s just work and home, you always talk to the same people. The class has everyone from students to old people, and talking with them is fun.'),
    ], '男[おとこ]の人[ひと]が 料理[りょうり]教室[きょうしつ]に 通[かよ]う 理由[りゆう]は 何[なん]ですか。', [
      r('料理[りょうり]が 上手[じょうず]に なりたいから', 'To become a better cook'), r('いろいろな 人[ひと]と 知[し]り合[あ]いたいから', 'To get to know all kinds of people'), r('会社[かいしゃ]の 人[ひと]に 勧[すす]められたから', 'A colleague recommended it'), r('家[いえ]で 料理[りょうり]を する ため', 'To cook at home'),
    ], 1, 'というより — not really for cooking; he wants acquaintances outside work.'),
    g('n2-g-station', '駅[えき]で アナウンスが 流[なが]れて います。', [
      l(F, 'お客様[きゃくさま]に お知[し]らせ いたします。ただいま、強風[きょうふう]の 影響[えいきょう]で、川[かわ]の 上[うえ]を 通[とお]る 区間[くかん]の 運転[うんてん]を 見合[みあ]わせて おります。', 'An announcement for passengers. Because of strong winds, services on the section over the river are currently suspended.'),
      l(F, '再開[さいかい]の 見込[みこ]みは 立[た]って おりません。お急[いそ]ぎの お客様[きゃくさま]は、駅前[えきまえ]から 出[で]て いる 臨時[りんじ]バスを ご利用[りよう]ください。', 'There is no estimate yet for when they will resume. Passengers in a hurry, please use the special buses from in front of the station.'),
    ], 'アナウンスで 一番[いちばん] 伝[つた]えたい ことは 何[なん]ですか。', [
      r('電車[でんしゃ]が もうすぐ 動[うご]き出[だ]す こと', 'Trains will start running soon'), r('電車[でんしゃ]が 止[と]まって いて、バスが 使[つか]える こと', 'Trains are stopped and buses are available'), r('バスが 遅[おく]れて いる こと', 'The buses are late'), r('駅[えき]の 出口[でぐち]が 変[か]わった こと', 'The station exits have changed'),
    ], 1, 'Services are suspended with no restart time, and there are special buses.'),
    g('n2-g-reading', '大学[だいがく]の 授業[じゅぎょう]で 先生[せんせい]が 話[はな]しています。', [
      l(M, '皆[みな]さんは レポートを 書[か]く とき、インターネットで 調[しら]べた ことを そのまま 使[つか]って いませんか。', 'When you write reports, don’t you use what you found online just as it is?'),
      l(M, 'ネットの 情報[じょうほう]は 便利[べんり]ですが、誰[だれ]が 書[か]いたのか わからない ものも 多[おお]く、間違[まちが]って いる ことも あります。', 'Online information is handy, but often you can’t tell who wrote it, and sometimes it’s wrong.'),
      l(M, '必[かなら]ず 本[ほん]や 論文[ろんぶん]など、ほかの 資料[しりょう]でも 確[たし]かめる ように して ください。', 'Always check it against other sources as well, such as books and papers.'),
    ], '先生[せんせい]が 学生[がくせい]に 言[い]いたい ことは 何[なん]ですか。', [
      r('インターネットを 使[つか]っては いけない', 'Don’t use the internet'), r('情報[じょうほう]は ほかの 資料[しりょう]でも 確[たし]かめる べきだ', 'Check information against other sources'), r('レポートは 短[みじか]く 書[か]く べきだ', 'Write shorter reports'), r('論文[ろんぶん]を たくさん 書[か]く べきだ', 'Write lots of papers'),
    ], 1, 'Not a ban on the internet — always confirm with other sources.'),
    g('n2-g-shop-reopen', 'テレビで 女[おんな]の 人[ひと]が 話[はな]しています。', [
      l(F, '駅前[えきまえ]の 商店街[しょうてんがい]で 長年[ながねん] 親[した]しまれて きた パン屋[や]が、来月[らいげつ] 閉店[へいてん]する ことに なりました。', 'A bakery that has been loved for many years on the shopping street by the station is to close next month.'),
      l(F, '店主[てんしゅ]の 高齢[こうれい]が 理由[りゆう]ですが、この 店[みせ]の パンの 味[あじ]を 残[のこ]したいと、近所[きんじょ]の 若[わか]い 夫婦[ふうふ]が 作[つく]り方[かた]を 受[う]け継[つ]ぎ、来春[らいしゅん] 新[あたら]しい 店[みせ]を 開[ひら]く そうです。', 'The reason is the owner’s age, but a young couple from the neighbourhood, wanting to keep the bread’s flavour alive, are learning the recipes and will open a new shop next spring.'),
    ], '女[おんな]の人[ひと]は 何[なに]に ついて 話[はな]して いますか。', [
      r('パン屋[や]の 新[あたら]しい 商品[しょうひん]', 'A bakery’s new products'), r('商店街[しょうてんがい]の お祭[まつ]り', 'The shopping street’s festival'), r('閉店[へいてん]する パン屋[や]の 味[あじ]が 受[う]け継[つ]がれる こと', 'A closing bakery’s recipes being carried on'), r('パンの 作[つく]り方[かた]', 'How to bake bread'),
    ], 2, 'The bakery closes, but a young couple will carry on its bread in a new shop.'),
    g('n2-g-sleep-company', 'ラジオで 男[おとこ]の 人[ひと]が 話[はな]しています。', [
      l(M, 'ある 会社[かいしゃ]では、昼休[ひるやす]みに 十五分[じゅうごふん]だけ 昼寝[ひるね]を する ことを 社員[しゃいん]に 勧[すす]めて います。', 'One company encourages its staff to take a fifteen-minute nap at lunchtime.'),
      l(M, '最初[さいしょ]は 「会社[かいしゃ]で 寝[ね]るなんて」と 反対[はんたい]する 声[こえ]も ありましたが、午後[ごご]の 会議[かいぎ]で 眠[ねむ]そうに して いる 人[ひと]が 減[へ]り、ミスも 少[すく]なく なったそうです。', 'At first some objected to sleeping at work, but apparently fewer people look sleepy in afternoon meetings, and there are fewer mistakes.'),
      l(M, '短[みじか]い 昼寝[ひるね]は、仕事[しごと]の 質[しつ]を 高[たか]める 一[ひと]つの 方法[ほうほう]と 言[い]えそうです。', 'A short nap could be called one way of raising the quality of work.'),
    ], '男[おとこ]の人[ひと]は 何[なに]が 言[い]いたいのですか。', [
      r('昼休[ひるやす]みを 長[なが]く するべきだ', 'Lunch breaks should be longer'), r('会社[かいしゃ]で 寝[ね]るのは よくない', 'Sleeping at work is bad'), r('短[みじか]い 昼寝[ひるね]は 仕事[しごと]に いい 影響[えいきょう]が ある', 'A short nap is good for work'), r('会議[かいぎ]は 午前[ごぜん]に するべきだ', 'Meetings should be in the morning'),
    ], 2, 'Fewer sleepy people and fewer mistakes: a short nap improves work.'),
    g('n2-g-volunteer-talk', '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。', [
      l(M, '週末[しゅうまつ]の ボランティア、続[つづ]けて いるんだね。大変[たいへん]じゃない？', 'You’re still doing the weekend volunteering. Isn’t it hard?'),
      l(F, '体[からだ]は 疲[つか]れるけど、教[おし]えて いる 子[こ]どもたちが 少[すこ]しずつ 字[じ]を 読[よ]めるように なるのを 見[み]ると、こっちが 元気[げんき]を もらえるの。', 'I get tired, but seeing the children I teach gradually learn to read gives me energy.'),
      l(F, '自分[じぶん]の ために やって いる ような ものかもしれないね。', 'Maybe I’m really doing it for myself.'),
    ], '女[おんな]の人[ひと]は ボランティアに ついて どう 思[おも]って いますか。', [
      r('疲[つか]れるので、もう やめたい', 'It’s tiring, so she wants to stop'), r('自分[じぶん]も 力[ちから]を もらえる ので 続[つづ]けたい', 'It gives her energy too, so she wants to continue'), r('子[こ]どもたちの 成長[せいちょう]が 遅[おそ]くて 心配[しんぱい]だ', 'She’s worried the children are slow'), r('もっと 多[おお]くの 人[ひと]に 参加[さんか]して ほしい', 'She wants more people to join'),
    ], 1, 'Tiring, but the children’s progress energises her — she’s doing it for herself too.'),
    g('n2-g-museum-free', '市[し]の 職員[しょくいん]が 話[はな]しています。', [
      l(M, '来月[らいげつ]から 市立[しりつ]美術館[びじゅつかん]は、毎月[まいつき] 第三[だいさん] 日曜日[にちようび]を 無料[むりょう]の 日[ひ]と します。', 'From next month, the city art museum will be free on the third Sunday of every month.'),
      l(M, 'これまで 美術館[びじゅつかん]に 来[き]た ことの ない 方[かた]、特[とく]に 子[こ]ども連[づ]れの ご家族[かぞく]に、気軽[きがる]に 足[あし]を 運[はこ]んで いただきたいと 考[かんが]えて います。', 'We would like people who have never been to the museum, especially families with children, to drop in without a second thought.'),
    ], '職員[しょくいん]は 何[なに]に ついて 話[はな]して いますか。', [
      r('美術館[びじゅつかん]の 新[あたら]しい 作品[さくひん]', 'The museum’s new works'), r('美術館[びじゅつかん]が 無料[むりょう]に なる 日[ひ]と その 目的[もくてき]', 'The museum’s free days and why'), r('子[こ]ども向[む]けの 教室[きょうしつ]', 'Classes for children'), r('美術館[びじゅつかん]の 工事[こうじ]', 'Work on the museum'),
    ], 1, 'A monthly free day, to bring in new visitors and families.'),
    g('n2-g-smartphone-kids', '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 子[こ]どもの スマートフォンに ついて 話[はな]しています。', [
      l(M, 'うちの 子[こ]、まだ 小学生[しょうがくせい]なのに、スマホが 欲[ほ]しいって 言[い]うんだよ。', 'Our kid is still in primary school but keeps asking for a smartphone.'),
      l(F, 'うちも そう。でも、連絡[れんらく]が 取[と]れると 安心[あんしん]だから、持[も]たせる ことに したの。', 'Ours too. But being able to reach them is reassuring, so we decided to let them have one.'),
      l(F, 'ただし、使[つか]う 時間[じかん]や 場所[ばしょ]は 家族[かぞく]で ルールを 決[き]めて ね。持[も]たせる なら、それが 一番[いちばん] 大事[だいじ]だと 思[おも]う。', 'But we set family rules on when and where it’s used. If you give them one, I think that matters most.'),
    ], '女[おんな]の人[ひと]の 考[かんが]えに 一番[いちばん] 近[ちか]いのは どれですか。', [
      r('子[こ]どもに スマホを 持[も]たせるべきではない', 'Children shouldn’t have smartphones'), r('子[こ]どもには 早[はや]く スマホを 持[も]たせた ほうが いい', 'Children should get smartphones early'), r('持[も]たせるなら、使[つか]い方[かた]の ルールが 大切[たいせつ]だ', 'If you give one, rules for using it matter'), r('スマホより パソコンの ほうが いい', 'A computer is better than a smartphone'),
    ], 2, 'She allows it for safety, but the family rules are what matter most.'),
  ]);

  const q = (id, who, ja, en, replyBy, choices, answer, why) => ({ id, level: 'N2', lines: [l(who, ja, en)], replyBy, choices, answer, why });
  add('sokuji', [
    q('n2-s-too-much', M, 'こんなに たくさん いただいて しまって、かえって 申[もう]し訳[わけ]ないです。', 'Receiving so much makes me feel bad, if anything.', F,
      [r('いいえ、ほんの 気持[きも]ちですから。', 'Not at all, it’s just a small token.'), r('では、もっと 差[さ]し上[あ]げます。', 'Then I’ll give you more.'), r('申[もう]し訳[わけ]ないですね。', 'That’s inexcusable, isn’t it.')], 0, 'Reply modestly to thanks for a gift: ほんの気持ちですから.'),
    q('n2-s-cant-help', F, 'この 雨[あめ]じゃ、試合[しあい]は 中止[ちゅうし]せざるを 得[え]ないね。', 'With this rain, they’ll have no choice but to cancel the match.', M,
      [r('うん、中止[ちゅうし]しなくて よかった。', 'Yes, good thing they didn’t cancel.'), r('残念[ざんねん]だけど、仕方[しかた]ないね。', 'It’s a shame, but it can’t be helped.'), r('雨[あめ]なら 得[とく]だね。', 'Rain is a bargain then.')], 1, '〜ざるを得ない: no choice — agree it can’t be helped.'),
    q('n2-s-for-a-beginner', M, '初[はじ]めて 作[つく]った にしては、よく できて いるね。', 'For a first attempt, it’s really well made.', F,
      [r('ありがとう。思[おも]ったより うまく いったよ。', 'Thanks. It went better than I expected.'), r('初[はじ]めてじゃ ないよ。', 'It’s not my first time.'), r('じゃあ、作[つく]って みようかな。', 'Then maybe I’ll try making one.')], 0, '〜にしては praises it; accept with thanks.'),
    q('n2-s-meeting-room', F, '会議室[かいぎしつ]、三時[さんじ]から 使[つか]わせて いただいても よろしいでしょうか。', 'May we use the meeting room from three?', M,
      [r('ええ、どうぞ お使[つか]いください。', 'Yes, please go ahead.'), r('はい、使[つか]わせて あげます。', 'Yes, I’ll let you use it.'), r('三時[さんじ]に 使[つか]いましたよ。', 'We used it at three.')], 0, 'Polite permission: どうぞお使いください.'),
    q('n2-s-busy-now', M, '今[いま]、ちょっと よろしいですか。', 'Do you have a moment?', F,
      [r('すみません、五分[ごふん]ほど 待[ま]って いただけますか。', 'Sorry, could you wait about five minutes?'), r('はい、よろしかったです。', 'Yes, it was fine.'), r('ちょっとだけ よろしく。', 'Just a little, please.')], 0, 'A natural reply when busy: ask them to wait.'),
    q('n2-s-hard-to-say', F, '言[い]いにくいんですが、この 資料[しりょう]、もう 一度[いちど] 作[つく]り直[なお]して もらえませんか。', 'This is hard to say, but could you redo these documents?', M,
      [r('わかりました。どこを 直[なお]せば いいですか。', 'Understood. What should I fix?'), r('言[い]いにくいなら 言[い]わないで ください。', 'If it’s hard, don’t say it.'), r('作[つく]り直[なお]して あげます。', 'I’ll redo it for you.')], 0, 'Accept and ask what to change.'),
    q('n2-s-not-again', M, 'また 遅刻[ちこく]？ これで 三回目[さんかいめ]だよ。', 'Late again? That’s the third time.', F,
      [r('申[もう]し訳[わけ]ありません。以後[いご] 気[き]を つけます。', 'I’m very sorry. I’ll be careful from now on.'), r('三回目[さんかいめ]なら 大丈夫[だいじょうぶ]です。', 'The third time is fine.'), r('遅刻[ちこく]しないで ください。', 'Please don’t be late.')], 0, 'Apologise and promise to be careful.'),
    q('n2-s-taking-leave', F, 'では、本日[ほんじつ]は これで 失礼[しつれい]いたします。', 'Well then, I’ll take my leave for today.', M,
      [r('お忙[いそが]しい ところ、ありがとうございました。', 'Thank you for your time when you’re so busy.'), r('失礼[しつれい]な 方[かた]ですね。', 'How rude.'), r('いいえ、どういたしまして。', 'You’re welcome.')], 0, 'Thank a visitor who is leaving.'),
    q('n2-s-cant-hear', M, 'すみません、お電話[でんわ]が 少[すこ]し 遠[とお]いようなんですが。', 'Sorry, I can’t hear you very well.', F,
      [r('失礼[しつれい]しました。これで いかがでしょうか。', 'Sorry — is that better?'), r('電話[でんわ]は 遠[とお]くに あります。', 'The phone is far away.'), r('もう 少[すこ]し 近[ちか]くに 来[き]て ください。', 'Please come a bit closer.')], 0, '電話が遠い means the line is faint — speak up.'),
    q('n2-s-what-if', F, 'もし 明日[あした] 電車[でんしゃ]が 止[と]まったら、どう する？', 'What will you do if the trains stop tomorrow?', M,
      [r('止[と]まって よかったね。', 'Good thing they stopped.'), r('そうなったら、バスで 行[い]くしか ないね。', 'Then I’ll have no choice but to take the bus.'), r('電車[でんしゃ]は 止[と]まりましたよ。', 'The trains stopped.')], 1, 'A hypothetical: say what you’d do.'),
    q('n2-s-surprised', M, 'えっ、あの 二人[ふたり]、結婚[けっこん]するの？ 全然[ぜんぜん] 知[し]らなかった。', 'What, those two are getting married? I had no idea.', F,
      [r('私[わたし]も 昨日[きのう] 聞[き]いて びっくりしたよ。', 'I was surprised too when I heard yesterday.'), r('結婚[けっこん]して いないよ。', 'They aren’t married.'), r('知[し]らないで ください。', 'Please don’t know.')], 0, 'Share the surprise.'),
    q('n2-s-overdo', F, '最近[さいきん]、毎晩[まいばん] 遅[おそ]くまで 残業[ざんぎょう]して いるらしいね。無理[むり]しないでよ。', 'I hear you’re working late every night. Don’t overdo it.', M,
      [r('ありがとう。来週[らいしゅう]には 落[お]ち着[つ]く はずだから。', 'Thanks. It should calm down next week.'), r('うん、無理[むり]だったよ。', 'Yeah, it was impossible.'), r('残業[ざんぎょう]して ください。', 'Please work overtime.')], 0, 'Thank her for her concern.'),
    q('n2-s-anyway', M, 'どうせ 言[い]っても 聞[き]いて くれないんだから。', 'He won’t listen anyway, whatever I say.', F,
      [r('そう 言[い]わずに、もう 一度[いちど] 話[はな]して みたら？', 'Don’t say that — why not try talking to him once more?'), r('じゃあ、聞[き]いて あげるよ。', 'Then I’ll listen.'), r('言[い]わなくて よかったね。', 'Good thing you didn’t say it.')], 0, 'Encourage him not to give up.'),
    q('n2-s-accept-offer', F, 'よろしければ、駅[えき]まで お送[おく]りしましょうか。', 'If you like, shall I take you to the station?', M,
      [r('では、お言葉[ことば]に 甘[あま]えて。', 'Then I’ll gratefully accept.'), r('はい、お送[おく]りします。', 'Yes, I’ll take you.'), r('よろしくなかったです。', 'It wasn’t good.')], 0, 'お言葉に甘えて accepts a kind offer.'),
    q('n2-s-deadline', M, 'この 報告書[ほうこくしょ]、金曜日[きんようび]までに 仕上[しあ]げて もらえるかな。', 'Can you get this report finished by Friday?', F,
      [r('金曜日[きんようび]は ちょっと 厳[きび]しいので、月曜日[げつようび]の 朝[あさ]でも よろしいですか。', 'Friday is a bit tight — would Monday morning be OK?'), r('金曜日[きんようび]に 仕上[しあ]げました。', 'I finished it on Friday.'), r('はい、仕上[しあ]げて ください。', 'Yes, please finish it.')], 0, 'Negotiate the deadline politely.'),
    q('n2-s-no-wonder', F, '彼[かれ]、毎日[まいにち] 三時間[さんじかん] 練習[れんしゅう]して いるんだって。', 'Apparently he practises three hours every day.', M,
      [r('道理[どうり]で 上手[じょうず]な わけだ。', 'No wonder he’s so good.'), r('じゃあ、練習[れんしゅう]して ください。', 'Then please practise.'), r('三時間[さんじかん]も 遅[おく]れたの？', 'He was three hours late?')], 0, '道理で〜わけだ: that explains it.'),
    q('n2-s-careful', M, 'この 道[みち]、夜[よる]は 暗[くら]いから 気[き]を つけてね。', 'This road is dark at night, so be careful.', F,
      [r('うん、ありがとう。明[あか]るい 道[みち]を 通[とお]って 帰[かえ]る ことに する。', 'Thanks. I’ll go home a brighter way.'), r('うん、暗[くら]く して おく。', 'OK, I’ll keep it dark.'), r('気[き]を つけなくて いいよ。', 'You needn’t be careful.')], 0, 'Thank him and say what you’ll do.'),
    q('n2-s-hope-rain', F, '明日[あした]の 遠足[えんそく]、雨[あめ]に ならなければ いいんだけど。', 'I hope it doesn’t rain for tomorrow’s outing.', M,
      [r('天気[てんき]予報[よほう]では 晴[は]れるって 言[い]ってたよ。', 'The forecast says it’ll be fine.'), r('雨[あめ]に なって よかったね。', 'Good that it rained.'), r('遠足[えんそく]に 行[い]かなければ いいね。', 'Hopefully we won’t go.')], 0, 'Reassure her about the weather.'),
    q('n2-s-mistake-mine', M, '数字[すうじ]が 合[あ]わないと 思[おも]ったら、僕[ぼく]の 計算[けいさん]ミスだったよ。', 'I wondered why the numbers didn’t add up — it was my own miscalculation.', F,
      [r('原因[げんいん]が わかって よかったね。', 'Good that you found the cause.'), r('じゃあ、計算[けいさん]して あげる。', 'Then I’ll calculate it for you.'), r('数字[すうじ]が 合[あ]って いるね。', 'The numbers add up.')], 0, 'Relief that the cause is found.'),
    q('n2-s-look-forward', F, '新[あたら]しい プロジェクト、いよいよ 来週[らいしゅう]から 始[はじ]まりますね。', 'The new project finally starts next week.', M,
      [r('ええ、どんな ものに なるか 楽[たの]しみです。', 'Yes, I’m looking forward to seeing how it turns out.'), r('ええ、もう 終[お]わりましたね。', 'Yes, it’s already over.'), r('始[はじ]まらないで ほしいです。', 'I hope it doesn’t start.')], 0, 'Share the anticipation.'),
    q('n2-s-thanks-help', M, '先日[せんじつ]は 本当[ほんとう]に お世話[せわ]に なりました。', 'Thank you so much for your help the other day.', F,
      [r('いえいえ、お役[やく]に 立[た]てて よかったです。', 'Not at all, I’m glad I could help.'), r('お世話[せわ]して ください。', 'Please look after me.'), r('先日[せんじつ]は 休[やす]みでした。', 'The other day was a holiday.')], 0, 'Reply humbly to thanks.'),
    q('n2-s-should-ask', F, '分[わ]からない ことが あったら、遠慮[えんりょ]しないで 聞[き]いてね。', 'If there’s anything you don’t understand, don’t hesitate to ask.', M,
      [r('ありがとうございます。助[たす]かります。', 'Thank you, that helps a lot.'), r('遠慮[えんりょ]して 聞[き]きません。', 'I’ll hold back and not ask.'), r('聞[き]いて あげます。', 'I’ll ask for you.')], 0, 'Thank her for the offer.'),
    q('n2-s-compare', M, 'A社[しゃ]と B社[しゃ]、どちらの 案[あん]が いいと 思[おも]う？', 'Which do you think is better, Company A’s proposal or B’s?', F,
      [r('値段[ねだん]なら A社[しゃ]だけど、品質[ひんしつ]を 考[かんが]えると B社[しゃ]かな。', 'On price, A, but considering quality, maybe B.'), r('どちらも 会社[かいしゃ]です。', 'They’re both companies.'), r('案内[あんない]して ください。', 'Please show me around.')], 0, 'Give a reasoned comparison.', ),
    q('n2-s-cannot-make-it', F, '申[もう]し訳[わけ]ないんですが、明日[あした]の 打[う]ち合[あ]わせ、急用[きゅうよう]で 伺[うかが]えなく なりました。', 'I’m very sorry, but something urgent has come up and I can’t come to tomorrow’s meeting.', M,
      [r('そうですか。では、また 日程[にってい]を 調整[ちょうせい]しましょう。', 'I see. Then let’s rearrange the schedule.'), r('では、伺[うかが]って ください。', 'Then please visit.'), r('急[いそ]いで 来[き]て ください。', 'Please hurry over.')], 0, 'Accept and offer to reschedule.'),
  ]);
})(typeof window !== 'undefined' ? window : globalThis);
