(function (global) {
  'use strict';

  // More 問題1 (task) and 問題2 (point) questions, written by hand. Format:
  // listening-data.js.
  const add = global.LISTENING_ADD;
  const items = (...list) => ({ type: 'items', items: list.map(x => (Array.isArray(x) ? x : [x, 1])) });
  const kid = extra => Object.assign({ type: 'person', child: true, hair: 'spiky', bottom: 'shorts', bottomColor: 'navy' }, extra);

  add('kadai', [
    {
      id: 'pool-bring', level: 'N5',
      intro: '先生[せんせい]が 話[はな]しています。学生[がくせい]は 明日[あした] 何[なに]を 持[も]って 来[き]ますか。',
      lines: [
        { who: 'F', ja: '明日[あした]は プールで 授業[じゅぎょう]を します。', en: 'Tomorrow’s lesson is at the pool.' },
        { who: 'F', ja: '水着[みずぎ]と タオルを 持[も]って 来[き]て ください。', en: 'Please bring a swimsuit and a towel.' },
        { who: 'F', ja: 'ゴーグルは 学校[がっこう]のを 貸[か]しますから、要[い]りません。', en: 'You don’t need goggles — the school will lend you some.' },
      ],
      choices: [items('swimsuit', 'goggles'), items('towel', 'goggles'), items('swimsuit', 'towel', 'goggles'), items('swimsuit', 'towel')],
      answer: 3,
      why: 'A swimsuit (水着) and a towel; the school lends goggles.',
    },
    {
      id: 'order-lunch', level: 'N5',
      intro: 'レストランで 女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は 何[なに]を 食[た]べますか。',
      lines: [
        { who: 'M', ja: '何[なに]に しますか。', en: 'What will you have?' },
        { who: 'F', ja: 'カレーに します。', en: 'I’ll have the curry.' },
        { who: 'M', ja: 'ここの カレーは とても 辛[から]いですよ。', en: 'The curry here is very spicy.' },
        { who: 'F', ja: 'えっ、辛[から]いのは ちょっと…。じゃあ、ラーメンに します。', en: 'Oh, I’m not good with spicy food. Then I’ll have ramen.' },
      ],
      choices: [items('curry'), items('sushi'), items('ramen'), items('sandwich')],
      answer: 2,
      why: 'She wanted curry, but it’s very spicy (辛い), so she has ramen.',
    },
    {
      id: 'cafe-order', level: 'N5',
      intro: '喫茶店[きっさてん]で 男[おとこ]の人[ひと]が 注文[ちゅうもん]しています。男[おとこ]の人[ひと]は 何[なに]を 注文[ちゅうもん]しますか。',
      lines: [
        { who: 'M', ja: 'すみません、コーヒーを 三[みっ]つ ください。', en: 'Excuse me, three coffees, please.' },
        { who: 'F', ja: 'あ、私[わたし]は コーヒーじゃなくて、ジュースが いいです。', en: 'Oh, I’d like juice, not coffee.' },
        { who: 'M', ja: 'じゃあ、コーヒーを 二[ふた]つと ジュースを 一[ひと]つ お願[ねが]いします。', en: 'Then two coffees and one juice, please.' },
      ],
      choices: [items(['coffee', 3]), items(['coffee', 2], 'juice'), items('coffee', ['juice', 2]), items(['juice', 3])],
      answer: 1,
      why: 'Three coffees at first, but one of them changes to juice: two coffees and one juice.',
    },
    {
      id: 'lost-umbrella', level: 'N5',
      intro: '駅[えき]で 女[おんな]の人[ひと]と 駅員[えきいん]が 話[はな]しています。女[おんな]の人[ひと]の 傘[かさ]は どれですか。',
      lines: [
        { who: 'F', ja: 'すみません、電車[でんしゃ]に 傘[かさ]を 忘[わす]れました。', en: 'Excuse me, I left my umbrella on the train.' },
        { who: 'M', ja: 'どんな 傘[かさ]ですか。青[あお]い 傘[かさ]ですか。', en: 'What kind of umbrella? A blue one?' },
        { who: 'F', ja: 'いいえ、赤[あか]い 傘[かさ]です。白[しろ]い 丸[まる]が たくさん あります。', en: 'No, a red one. It has lots of white dots.' },
      ],
      choices: [items({ name: 'umbrella', color: 'blue', pattern: 'dots' }), items({ name: 'umbrella', color: 'red' }), items({ name: 'umbrella', color: 'blue' }), items({ name: 'umbrella', color: 'red', pattern: 'dots' })],
      answer: 3,
      why: 'Red (赤い) with white dots (白い丸).',
    },
    {
      id: 'which-cat', level: 'N5',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]の 猫[ねこ]は どれですか。',
      lines: [
        { who: 'M', ja: '木村[きむら]さんの 猫[ねこ]は どれですか。あの 黒[くろ]い 猫[ねこ]ですか。', en: 'Which one is your cat, Kimura-san? That black one?' },
        { who: 'F', ja: 'いいえ、うちの 猫[ねこ]は 白[しろ]いです。', en: 'No, ours is white.' },
        { who: 'M', ja: 'あの 大[おお]きい 白[しろ]い 猫[ねこ]ですね。', en: 'That big white one, then.' },
        { who: 'F', ja: 'いいえ、その 隣[となり]の 小[ちい]さい 猫[ねこ]です。', en: 'No, the small one next to it.' },
      ],
      choices: [items({ name: 'cat', color: 'white', big: true }), items({ name: 'cat', color: 'white', small: true }), items({ name: 'cat', color: 'black', small: true }), items({ name: 'cat', color: 'black', big: true })],
      answer: 1,
      why: 'White (白い), and the small one (小さい猫), not the big one.',
    },
    {
      id: 'meet-place', level: 'N5',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。二人[ふたり]は どこで 会[あ]いますか。',
      lines: [
        { who: 'F', ja: '明日[あした]、駅[えき]で 会[あ]いましょうか。', en: 'Shall we meet at the station tomorrow?' },
        { who: 'M', ja: '駅[えき]は 人[ひと]が 多[おお]いですから、駅[えき]の 前[まえ]の 本屋[ほんや]は どうですか。', en: 'The station is crowded, so how about the bookshop in front of it?' },
        { who: 'F', ja: 'いいですね。じゃ、本屋[ほんや]で 会[あ]いましょう。', en: 'Good idea. Let’s meet at the bookshop.' },
      ],
      choices: [items('station'), items('cafe'), items('park'), items('bookstore')],
      answer: 3,
      why: 'Not the crowded station — the bookshop (本屋) in front of it.',
    },
    {
      id: 'souvenir', level: 'N5',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は お母[かあ]さんに 何[なに]を 買[か]いますか。',
      lines: [
        { who: 'M', ja: 'お母[かあ]さんに お土産[みやげ]を 買[か]いますか。', en: 'Are you buying your mother a souvenir?' },
        { who: 'F', ja: 'ええ。お菓子[かし]は どうでしょうか。', en: 'Yes. What about sweets?' },
        { who: 'M', ja: 'お母[かあ]さんは 甘[あま]い 物[もの]が 好[す]きですか。', en: 'Does your mother like sweet things?' },
        { who: 'F', ja: 'いいえ、あまり…。Tシャツも サイズが わかりませんから、この 人形[にんぎょう]に します。', en: 'Not really… And I don’t know her T-shirt size, so I’ll get this doll.', say: 'いいえ、あまり。ティーシャツもサイズがわかりませんから、この人形にします。' },
      ],
      choices: [items('sweets'), items('tshirt'), items('doll'), items('postcard')],
      answer: 2,
      why: 'Not sweets (she doesn’t like sweet things) and not a T-shirt (size unknown): the doll (人形).',
    },
    {
      id: 'kid-clothes', level: 'N5',
      voices: { M: 'child' },
      intro: 'お母[かあ]さんと 男[おとこ]の子[こ]が 話[はな]しています。男[おとこ]の子[こ]は 何[なに]を 着[き]て 行[い]きますか。',
      lines: [
        { who: 'M', ja: 'いってきます。', en: 'I’m off!' },
        { who: 'F', ja: 'ちょっと 待[ま]って。今日[きょう]は 寒[さむ]いから、セーターを 着[き]て。帽子[ぼうし]も かぶって 行[い]きなさい。', en: 'Wait a moment. It’s cold today, so put on a sweater. And wear a hat, too.' },
        { who: 'M', ja: '帽子[ぼうし]は 嫌[いや]だよ。', en: 'I don’t want a hat.' },
        { who: 'F', ja: 'しかたが ないわね。じゃあ、セーターだけ 着[き]て 行[い]きなさい。', en: 'Oh, all right. Then just wear the sweater.' },
      ],
      choices: [kid({ top: 'tshirt', topColor: 'blue' }), kid({ top: 'sweater', topColor: 'red', cap: true }), kid({ top: 'tshirt', topColor: 'blue', cap: true }), kid({ top: 'sweater', topColor: 'red' })],
      answer: 3,
      why: 'He refuses the hat, so just the sweater (セーターだけ).',
    },
    {
      id: 'clean-first', level: 'N5',
      voices: { M: 'child' },
      intro: 'お母[かあ]さんと 男[おとこ]の子[こ]が 話[はな]しています。男[おとこ]の子[こ]は 最初[さいしょ]に 何[なに]を しますか。',
      lines: [
        { who: 'M', ja: 'お母[かあ]さん、公園[こうえん]で サッカーを して くるね。', en: 'Mum, I’m going to play football in the park.' },
        { who: 'F', ja: '宿題[しゅくだい]は？', en: 'What about your homework?' },
        { who: 'M', ja: '宿題[しゅくだい]は もう 終[お]わったよ。', en: 'I’ve already finished my homework.' },
        { who: 'F', ja: 'じゃあ、部屋[へや]を 掃除[そうじ]してから 行[い]きなさい。', en: 'Then clean your room before you go.' },
      ],
      choices: [items('soccer'), items('broom'), items('homework'), items('game')],
      answer: 1,
      why: '掃除してから行きなさい: clean the room first, then football. The homework is already done.',
    },
    {
      id: 'girl-present', level: 'N5',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。二人[ふたり]は 女[おんな]の子[こ]に 何[なに]を あげますか。',
      lines: [
        { who: 'M', ja: 'さくらちゃんの 誕生日[たんじょうび]に、本[ほん]は どうですか。', en: 'How about a book for Sakura-chan’s birthday?' },
        { who: 'F', ja: '本[ほん]は たくさん 持[も]って いますよ。', en: 'She already has lots of books.' },
        { who: 'M', ja: 'じゃあ、ゲームは？', en: 'A game, then?' },
        { who: 'F', ja: 'まだ 五歳[ごさい]ですから…。くまの ぬいぐるみが いいと 思[おも]います。', en: 'She’s only five… I think a teddy bear would be good.' },
      ],
      choices: [items('book'), items('game'), items('teddy'), items('flower')],
      answer: 2,
      why: 'She has lots of books and is too young for games: a teddy bear (くまのぬいぐるみ).',
    },
    {
      id: 'cinema-seat', level: 'N4',
      intro: '映画館[えいがかん]で 男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は どの 席[せき]に 座[すわ]りますか。',
      lines: [
        { who: 'M', ja: '一番[いちばん] 前[まえ]の 席[せき]が 空[あ]いて いますよ。', en: 'The seats right at the front are free.' },
        { who: 'F', ja: '前[まえ]は 首[くび]が 疲[つか]れますから、真[ま]ん中[なか]ぐらいが いいです。', en: 'My neck gets tired at the front, so somewhere in the middle is better.' },
        { who: 'M', ja: 'じゃあ、Cの 列[れつ]に しましょう。通路[つうろ]の 隣[となり]の 四番[よんばん]は どうですか。', en: 'Then let’s sit in row C. How about number 4, next to the aisle?', say: 'じゃあ、シーの列にしましょう。通路の隣の四番はどうですか。' },
        { who: 'F', ja: 'いいですね。私[わたし]は その 隣[となり]に 座[すわ]ります。', en: 'Good. I’ll sit next to you.' },
      ],
      choices: [{ type: 'seats', row: 'A', seat: 4 }, { type: 'seats', row: 'C', seat: 1 }, { type: 'seats', row: 'C', seat: 4 }, { type: 'seats', row: 'E', seat: 4 }],
      answer: 2,
      why: 'Not the front row (A): row C in the middle, seat 4 by the aisle.',
    },
    {
      id: 'medicine', level: 'N4',
      intro: '病院[びょういん]で 医者[いしゃ]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は いつ 薬[くすり]を 飲[の]みますか。',
      lines: [
        { who: 'F', ja: 'この 薬[くすり]は 朝[あさ]と 夜[よる]、ご飯[はん]を 食[た]べた 後[あと]に 飲[の]んで ください。', en: 'Take this medicine in the morning and at night, after meals.' },
        { who: 'M', ja: '昼[ひる]も 飲[の]みますか。', en: 'At lunchtime too?' },
        { who: 'F', ja: 'いいえ、昼[ひる]は 飲[の]まなくても いいですよ。', en: 'No, you don’t need to take it at lunchtime.' },
      ],
      choices: [{ type: 'times', when: ['morning', 'noon', 'night'] }, { type: 'times', when: ['morning', 'night'] }, { type: 'times', when: ['night'] }, { type: 'times', when: ['noon', 'bed'] }],
      answer: 1,
      why: 'Morning and night (朝と夜), not at lunchtime (昼は飲まなくてもいい).',
    },
    {
      id: 'office-first', level: 'N4',
      intro: '会社[かいしゃ]で 男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は まず 何[なに]を しますか。',
      lines: [
        { who: 'M', ja: '会議室[かいぎしつ]の 掃除[そうじ]と 資料[しりょう]の コピー、それから お茶[ちゃ]の 準備[じゅんび]を お願[ねが]いします。', en: 'Please clean the meeting room, copy the documents and get the tea ready.' },
        { who: 'F', ja: 'はい。どれから しましょうか。', en: 'Sure. Which shall I do first?' },
        { who: 'M', ja: 'コピーは もう 山田[やまだ]さんに 頼[たの]みました。お客[きゃく]さんが 来[く]る 前[まえ]に、まず 会議室[かいぎしつ]を 掃除[そうじ]して ください。お茶[ちゃ]は 最後[さいご]で いいです。', en: 'I’ve already asked Yamada-san to do the copies. Before the guests arrive, please clean the meeting room first. The tea can be last.' },
      ],
      choices: [items('copier'), items('tea'), items('broom'), items('phone')],
      answer: 2,
      why: 'まず会議室を掃除して: cleaning comes first; the copies are Yamada-san’s job and the tea is last.',
    },
    {
      id: 'route-hospital', level: 'N4',
      intro: '駅[えき]の 前[まえ]で 女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は どう 行[い]きますか。',
      lines: [
        { who: 'F', ja: 'すみません、さくら病院[びょういん]へは どう 行[い]けば いいですか。', en: 'Excuse me, how do I get to Sakura Hospital?' },
        { who: 'M', ja: 'この 道[みち]を まっすぐ 行[い]くと、角[かど]が 二[ふた]つ あります。', en: 'Go straight along this road and there are two corners.' },
        { who: 'M', ja: '一[ひと]つ目[め]の 角[かど]じゃなくて、二[ふた]つ目[め]の 角[かど]を 右[みぎ]に 曲[ま]がって ください。すぐ 病院[びょういん]が 見[み]えますよ。', en: 'Not the first corner — turn right at the second. You’ll see the hospital straight away.' },
      ],
      choices: [{ type: 'route', turns: ['up', 'right'] }, { type: 'route', turns: ['up', 'up', 'left'] }, { type: 'route', turns: ['up', 'up', 'right'] }, { type: 'route', turns: ['up', 'right', 'up'] }],
      answer: 2,
      why: 'Straight on past the first corner, then right at the second (二つ目の角を右).',
    },
    {
      id: 'boss-present', level: 'N4',
      intro: '会社[かいしゃ]で 女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。二人[ふたり]は 部長[ぶちょう]に 何[なに]を あげますか。',
      lines: [
        { who: 'F', ja: '部長[ぶちょう]の 誕生日[たんじょうび]、何[なに]が いいでしょうね。', en: 'What would be good for the manager’s birthday?' },
        { who: 'M', ja: 'ビールは どうですか。', en: 'How about beer?' },
        { who: 'F', ja: '部長[ぶちょう]は お酒[さけ]を 飲[の]まないんですよ。', en: 'The manager doesn’t drink.' },
        { who: 'M', ja: 'じゃあ、花[はな]は？', en: 'Flowers, then?' },
        { who: 'F', ja: '花[はな]は 去年[きょねん] あげましたから、今年[ことし]は 本[ほん]に しましょう。旅行[りょこう]の 本[ほん]が 好[す]きだそうですよ。', en: 'We gave flowers last year, so let’s give a book this year. I hear he likes travel books.' },
      ],
      choices: [items('beer'), items('flower'), items('sweets'), items('book')],
      answer: 3,
      why: 'He doesn’t drink and got flowers last year, so a (travel) book.',
    },
    {
      id: 'trip-pack', level: 'N4',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 旅行[りょこう]の 準備[じゅんび]を しています。女[おんな]の人[ひと]は 何[なに]を 持[も]って 行[い]きますか。',
      lines: [
        { who: 'M', ja: 'カメラは 持[も]って 行[い]く？', en: 'Are you taking the camera?' },
        { who: 'F', ja: '写真[しゃしん]は 携帯[けいたい]で 撮[と]るから、要[い]らないわ。', en: 'I’ll take photos with my phone, so I don’t need it.' },
        { who: 'M', ja: '向[む]こうは 雨[あめ]が 多[おお]いらしいよ。', en: 'Apparently it rains a lot there.' },
        { who: 'F', ja: 'じゃあ、傘[かさ]は 持[も]って 行[い]った ほうが いいわね。', en: 'Then I’d better take an umbrella.' },
      ],
      choices: [items('camera', 'umbrella'), items('smartphone', 'umbrella'), items('camera', 'smartphone'), items('smartphone')],
      answer: 1,
      why: 'Her phone (no camera — she takes photos with it) and an umbrella, because it rains a lot there.',
    },
    {
      id: 'box-where', level: 'N4',
      intro: '部屋[へや]で 女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は 箱[はこ]を どこに 置[お]きますか。',
      lines: [
        { who: 'M', ja: 'この 箱[はこ]、どこに 置[お]きましょうか。ドアの 横[よこ]で いいですか。', en: 'Where shall I put this box? Is next to the door OK?' },
        { who: 'F', ja: 'ドアの 横[よこ]だと、出[で]る 時[とき]に 邪魔[じゃま]ですね。', en: 'Next to the door, it’ll be in the way when we go out.' },
        { who: 'M', ja: 'じゃあ、窓[まど]の 前[まえ]は？', en: 'In front of the window, then?' },
        { who: 'F', ja: '窓[まど]が 開[あ]けられなく なりますから、本棚[ほんだな]の 右[みぎ]に 置[お]いて ください。', en: 'Then we couldn’t open the window. Please put it to the right of the bookshelf.' },
      ],
      choices: [{ type: 'room', at: 'door' }, { type: 'room', at: 'window' }, { type: 'room', at: 'shelf-left' }, { type: 'room', at: 'shelf-right' }],
      answer: 3,
      why: 'Not by the door (in the way) or the window (can’t open it): to the right of the bookshelf (本棚の右).',
    },
    {
      id: 'supermarket', level: 'N4',
      intro: 'スーパーで 男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は 何[なに]を 買[か]いますか。',
      lines: [
        { who: 'M', ja: '卵[たまご]と 牛乳[ぎゅうにゅう]を 買[か]えば いいんだよね。', en: 'I just need to buy eggs and milk, right?' },
        { who: 'F', ja: '牛乳[ぎゅうにゅう]は 昨日[きのう] 買[か]ったから、まだ あるよ。', en: 'I bought milk yesterday, so we still have some.' },
        { who: 'F', ja: 'それより、パンが もう ないから、パンを 買[か]って。', en: 'More importantly, we’re out of bread, so get bread.' },
        { who: 'M', ja: 'わかった。卵[たまご]と パンだね。', en: 'OK. Eggs and bread.' },
      ],
      choices: [items('egg', 'milk'), items('egg', 'bread'), items('milk', 'bread'), items('egg', 'milk', 'bread')],
      answer: 1,
      why: 'Eggs and bread — there’s still milk from yesterday.',
    },
    {
      id: 'bookshop-where', level: 'N4',
      intro: '駅[えき]を 出[で]た ところで、男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。本屋[ほんや]は どこですか。',
      lines: [
        { who: 'M', ja: 'この 近[ちか]くに 本屋[ほんや]は ありますか。', en: 'Is there a bookshop near here?' },
        { who: 'F', ja: 'ええ。道[みち]の 向[む]こう側[がわ]に あります。', en: 'Yes, on the other side of the road.' },
        { who: 'M', ja: '駅[えき]の ちょうど 前[まえ]ですか。', en: 'Right opposite the station?' },
        { who: 'F', ja: 'いいえ、駅[えき]の 前[まえ]から 少[すこ]し 左[ひだり]です。', en: 'No, a little to the left of the spot opposite the station.' },
      ],
      choices: [{ type: 'map', at: 'front', label: '駅' }, { type: 'map', at: 'left', label: '駅' }, { type: 'map', at: 'front-left', label: '駅' }, { type: 'map', at: 'corner', label: '駅' }],
      answer: 2,
      why: 'Across the road (向こう側), and a little left of directly opposite the station.',
    },
    {
      id: 'tonight', level: 'N4',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の 学生[がくせい]が 話[はな]しています。男[おとこ]の 学生[がくせい]は 今晩[こんばん] 何[なに]を しますか。',
      voices: { M: 'young' },
      lines: [
        { who: 'F', ja: '今晩[こんばん]、カラオケに 行[い]かない？', en: 'Want to go to karaoke tonight?' },
        { who: 'M', ja: 'ごめん。明日[あした] 漢字[かんじ]の テストが あるんだ。', en: 'Sorry. I’ve got a kanji test tomorrow.' },
        { who: 'F', ja: '作文[さくぶん]の 宿題[しゅくだい]も あったよね。', en: 'There was an essay for homework too, wasn’t there?' },
        { who: 'M', ja: '作文[さくぶん]は 来週[らいしゅう]までだから、今晩[こんばん]は テストの 勉強[べんきょう]を するよ。', en: 'The essay isn’t due until next week, so tonight I’ll study for the test.' },
      ],
      choices: [items('karaoke'), items('homework'), items('study'), items('work')],
      answer: 2,
      why: 'Studying for tomorrow’s kanji test; the essay is due next week.',
    },
  ]);

  add('point', [
    {
      id: 'season', level: 'N5',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は どの 季節[きせつ]が 一番[いちばん] 好[す]きですか。',
      lines: [
        { who: 'M', ja: '夏[なつ]は 好[す]きですか。', en: 'Do you like summer?' },
        { who: 'F', ja: '暑[あつ]いのは ちょっと…。冬[ふゆ]も 寒[さむ]いから 好[す]きじゃありません。', en: 'I’m not good with heat… And I don’t like winter either — it’s cold.' },
        { who: 'M', ja: 'じゃあ、秋[あき]ですか。', en: 'Autumn, then?' },
        { who: 'F', ja: '秋[あき]も いいですが、桜[さくら]が きれいですから、春[はる]が 一番[いちばん] 好[す]きです。', en: 'Autumn is nice too, but the cherry blossoms are beautiful, so I like spring best.' },
      ],
      choices: [items('beach'), items('sakura'), items('leaves'), items('snowman')],
      answer: 1,
      why: 'Spring (春), because of the cherry blossoms.',
    },
    {
      id: 'pets', level: 'N5',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]の 家[いえ]には 何[なに]が いますか。',
      lines: [
        { who: 'F', ja: '田中[たなか]さんは 犬[いぬ]を 飼[か]って いますか。', en: 'Do you have a dog, Tanaka-san?' },
        { who: 'M', ja: 'いいえ、犬[いぬ]は いません。猫[ねこ]が 二匹[にひき] います。', en: 'No, no dog. I have two cats.' },
        { who: 'F', ja: 'いいですね。私[わたし]は 鳥[とり]が 一羽[いちわ] います。', en: 'Nice. I have a bird.' },
      ],
      choices: [items('dog'), items(['cat', 2]), items('cat'), items('bird')],
      answer: 1,
      why: 'No dog — two cats (猫が二匹). The bird is hers.',
    },
    {
      id: 'hobby', level: 'N5',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]の 趣味[しゅみ]は 何[なん]ですか。',
      lines: [
        { who: 'F', ja: '山田[やまだ]さんの 趣味[しゅみ]は 何[なん]ですか。', en: 'What’s your hobby, Yamada-san?' },
        { who: 'M', ja: '写真[しゃしん]を 撮[と]る ことです。', en: 'Taking photographs.' },
        { who: 'F', ja: 'よく 山[やま]へ 行[い]きますね。山登[やまのぼ]りも 好[す]きですか。', en: 'You often go to the mountains. Do you like climbing too?' },
        { who: 'M', ja: '山[やま]へは 写真[しゃしん]を 撮[と]りに 行[い]くだけです。', en: 'I only go to the mountains to take photos.' },
      ],
      choices: [items('hiking'), items('cooking'), items('camera'), items('music')],
      answer: 2,
      why: 'Taking photos (写真を撮ること); the mountains are just where he takes them.',
    },
    {
      id: 'breakfast', level: 'N5',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は 今朝[けさ] 何[なに]を 食[た]べましたか。',
      lines: [
        { who: 'M', ja: '朝[あさ]ご飯[はん]は いつも パンですか。', en: 'Do you always have bread for breakfast?' },
        { who: 'F', ja: 'ええ、いつもは パンと コーヒーです。', en: 'Yes, usually bread and coffee.' },
        { who: 'F', ja: 'でも、今朝[けさ]は 時間[じかん]が なくて、バナナを 一本[いっぽん] 食[た]べただけです。', en: 'But this morning I had no time, so I just ate a banana.' },
      ],
      choices: [items('bread', 'coffee'), items('rice'), items('banana'), items('egg', 'bread')],
      answer: 2,
      why: 'Bread and coffee is her usual — this morning, just a banana.',
    },
    {
      id: 'car-which', level: 'N5',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]の 車[くるま]は どれですか。',
      lines: [
        { who: 'F', ja: '駐車場[ちゅうしゃじょう]の あの 赤[あか]い 車[くるま]が 鈴木[すずき]さんのですか。', en: 'Is that red car in the car park yours, Suzuki-san?' },
        { who: 'M', ja: 'いいえ、赤[あか]いのは 父[ちち]のです。', en: 'No, the red one is my father’s.' },
        { who: 'M', ja: '私[わたし]のは 白[しろ]くて 小[ちい]さい 車[くるま]です。', en: 'Mine is the small white one.' },
      ],
      choices: [items({ name: 'car', color: 'red', big: true }), items({ name: 'car', color: 'white', big: true }), items({ name: 'car', color: 'red', small: true }), items({ name: 'car', color: 'white', small: true })],
      answer: 3,
      why: 'The red one is his father’s; his is white and small (白くて小さい).',
    },
    {
      id: 'absent', level: 'N4',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は どうして パーティーに 行[い]きませんか。',
      lines: [
        { who: 'M', ja: '明日[あした]の パーティー、行[い]きますか。', en: 'Are you going to tomorrow’s party?' },
        { who: 'F', ja: '行[い]きたいんですが、昨日[きのう]から 熱[ねつ]が あるんです。', en: 'I’d like to, but I’ve had a fever since yesterday.' },
        { who: 'M', ja: 'それは 大変[たいへん]ですね。アルバイトは？', en: 'That’s rough. What about your part-time job?' },
        { who: 'F', ja: 'アルバイトも 休[やす]みました。早[はや]く 治[なお]したいです。', en: 'I took the day off work too. I want to get better quickly.' },
      ],
      choices: [items('work'), items('thermometer'), items('homework'), items('rain')],
      answer: 1,
      why: 'She has a fever (熱があるんです) — she even took time off work.',
    },
    {
      id: 'osaka-how', level: 'N4',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は 何[なに]で 大阪[おおさか]へ 行[い]きましたか。',
      lines: [
        { who: 'F', ja: '大阪[おおさか]へは 新幹線[しんかんせん]で 行[い]ったんですか。', en: 'Did you go to Osaka by shinkansen?' },
        { who: 'M', ja: '新幹線[しんかんせん]は 高[たか]いので、最初[さいしょ]は バスで 行[い]こうと 思[おも]いました。', en: 'The shinkansen is expensive, so at first I was going to take the bus.' },
        { who: 'M', ja: 'でも、バスは 時間[じかん]が かかるし、安[やす]い 飛行機[ひこうき]の チケットが あったので、飛行機[ひこうき]に しました。', en: 'But the bus takes ages, and there was a cheap plane ticket, so I flew.' },
      ],
      choices: [items('shinkansen'), items('bus'), items('car'), items('plane')],
      answer: 3,
      why: 'Not the shinkansen (expensive) or the bus (slow): a cheap flight (飛行機にしました).',
    },
    {
      id: 'broken', level: 'N4',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。何[なに]が 壊[こわ]れましたか。',
      lines: [
        { who: 'F', ja: '元気[げんき]が ないですね。テレビが 壊[こわ]れたんですか。', en: 'You look down. Did your TV break?' },
        { who: 'M', ja: 'いいえ、テレビじゃなくて、洗濯機[せんたくき]が 壊[こわ]れて しまったんです。', en: 'No, not the TV — my washing machine broke.' },
        { who: 'M', ja: '冷蔵庫[れいぞうこ]も 古[ふる]いですが、そちらは まだ 大丈夫[だいじょうぶ]です。', en: 'The fridge is old too, but it’s still OK.' },
      ],
      choices: [items('tv'), items('fridge'), items('washer'), items('computer')],
      answer: 2,
      why: 'The washing machine (洗濯機); the TV is fine and the fridge still works.',
    },
    {
      id: 'lost-phone', level: 'N4',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は 何[なに]を なくしましたか。',
      lines: [
        { who: 'M', ja: 'どう したんですか。財布[さいふ]を なくしたんですか。', en: 'What’s wrong? Did you lose your wallet?' },
        { who: 'F', ja: '財布[さいふ]は かばんの 中[なか]に ありました。鍵[かぎ]も あります。', en: 'My wallet was in my bag. And I have my keys.' },
        { who: 'F', ja: 'なくしたのは 携帯電話[けいたいでんわ]なんです。', en: 'It’s my mobile phone I’ve lost.' },
      ],
      choices: [items('wallet'), items('key'), items('umbrella'), items('smartphone')],
      answer: 3,
      why: 'Wallet and keys are fine — she lost her mobile phone (携帯電話).',
    },
    {
      id: 'weekend', level: 'N4',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は 週末[しゅうまつ] 何[なに]を しましたか。',
      lines: [
        { who: 'F', ja: '週末[しゅうまつ]は テニスを したんですか。', en: 'Did you play tennis at the weekend?' },
        { who: 'M', ja: 'する つもりでしたが、雨[あめ]だったので できませんでした。', en: 'I meant to, but it rained so I couldn’t.' },
        { who: 'M', ja: 'それで、家[いえ]で 料理[りょうり]を 作[つく]りました。', en: 'So I cooked at home instead.' },
      ],
      choices: [items('tennis'), items('swim'), items('cooking'), items('broom')],
      answer: 2,
      why: 'Tennis was the plan, but it rained, so he cooked (料理を作りました).',
    },
    {
      id: 'sister-job', level: 'N4',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]の お姉[ねえ]さんの 仕事[しごと]は どれですか。',
      lines: [
        { who: 'M', ja: 'お姉[ねえ]さんは 病院[びょういん]で 働[はたら]いて いるんですよね。お医者[いしゃ]さんですか。', en: 'Your sister works at a hospital, doesn’t she? Is she a doctor?' },
        { who: 'F', ja: 'いいえ、医者[いしゃ]じゃなくて、看護師[かんごし]です。', en: 'No, not a doctor — she’s a nurse.' },
        { who: 'M', ja: 'そうですか。大変[たいへん]な 仕事[しごと]ですね。', en: 'I see. That’s a tough job.' },
      ],
      choices: [
        { type: 'person', hair: 'bob', top: 'whitecoat', glasses: true },
        { type: 'person', hair: 'bun', top: 'jacket', topColor: 'purple', bottom: 'skirt', glasses: true },
        { type: 'person', hair: 'bun', top: 'whitecoat', topColor: 'mint' },
        { type: 'person', hair: 'bob', top: 'apron', topColor: 'sky', bottom: 'trousers' },
      ],
      answer: 2,
      why: 'Not a doctor (医者じゃなくて) — a nurse (看護師), in the nurse’s uniform.',
    },
    {
      id: 'sport', level: 'N4',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は どの スポーツを するのが 一番[いちばん] 好[す]きですか。',
      lines: [
        { who: 'F', ja: 'サッカーが 好[す]きなんですね。いつも テレビで 見[み]て いますね。', en: 'You like football, don’t you? You’re always watching it on TV.' },
        { who: 'M', ja: '見[み]るのは サッカーが 好[す]きですが、自分[じぶん]で するのは 野球[やきゅう]が 一番[いちばん] 好[す]きです。', en: 'I like watching football, but the one I like playing best is baseball.' },
      ],
      choices: [items('soccer'), items('tennis'), items('baseball'), items('swim')],
      answer: 2,
      why: 'Football is for watching; to play, baseball (するのは野球が一番).',
    },
    {
      id: 'birthday-gift', level: 'N4',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は 誕生日[たんじょうび]に 何[なに]を もらいましたか。',
      lines: [
        { who: 'M', ja: 'その 時計[とけい]、すてきですね。誕生日[たんじょうび]に もらったんですか。', en: 'That watch is lovely. Did you get it for your birthday?' },
        { who: 'F', ja: 'いいえ、時計[とけい]は 自分[じぶん]で 買[か]いました。', en: 'No, I bought the watch myself.' },
        { who: 'F', ja: '誕生日[たんじょうび]には 姉[あね]に ネックレスを もらいました。', en: 'For my birthday my sister gave me a necklace.' },
      ],
      choices: [items('watch'), items('flower'), items('necklace'), items('bag')],
      answer: 2,
      why: 'She bought the watch herself; the birthday present was a necklace (ネックレス).',
    },
    {
      id: 'her-house', level: 'N4',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]の 家[いえ]は どれですか。',
      lines: [
        { who: 'M', ja: '佐藤[さとう]さんの 家[いえ]は どんな 家[いえ]ですか。', en: 'What’s your house like, Sato-san?' },
        { who: 'F', ja: '二階建[にかいだ]てで、屋根[やね]が 青[あお]いです。', en: 'It has two floors and a blue roof.' },
        { who: 'M', ja: '家[いえ]の 前[まえ]に 車[くるま]が ありますか。', en: 'Is there a car in front of it?' },
        { who: 'F', ja: 'いいえ、車[くるま]は ありません。でも、大[おお]きい 木[き]が あります。', en: 'No, no car. But there’s a big tree.' },
      ],
      choices: [{ type: 'home', floors: 2, roof: 'blue', car: true }, { type: 'home', floors: 1, roof: 'blue', tree: true }, { type: 'home', floors: 2, roof: 'red', tree: true }, { type: 'home', floors: 2, roof: 'blue', tree: true }],
      answer: 3,
      why: 'Two floors (二階建て), a blue roof, no car, and a big tree.',
    },
    {
      id: 'trash-day', level: 'N4',
      intro: 'アパートで 男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。燃[も]える ごみは 何曜日[なんようび]に 出[だ]しますか。',
      lines: [
        { who: 'F', ja: 'すみません、燃[も]える ごみは 何曜日[なんようび]ですか。', en: 'Excuse me, which days is burnable rubbish collected?' },
        { who: 'M', ja: '月曜日[げつようび]と 木曜日[もくようび]です。', en: 'Monday and Thursday.' },
        { who: 'F', ja: '水曜日[すいようび]じゃ ないんですね。', en: 'Not Wednesday, then.' },
        { who: 'M', ja: 'ええ、水曜日[すいようび]は 瓶[びん]と 缶[かん]の 日[ひ]です。', en: 'Right — Wednesday is for bottles and cans.' },
      ],
      choices: [{ type: 'week', days: [1, 3] }, { type: 'week', days: [3] }, { type: 'week', days: [1, 4] }, { type: 'week', days: [2, 5] }],
      answer: 2,
      why: 'Monday and Thursday (月曜日と木曜日). Wednesday is bottles and cans.',
    },
    {
      id: 'brother-which', level: 'N4',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 写真[しゃしん]を 見[み]て います。男[おとこ]の人[ひと]の お兄[にい]さんは どの 人[ひと]ですか。',
      lines: [
        { who: 'F', ja: 'この 眼鏡[めがね]を かけて いる 人[ひと]が お兄[にい]さんですか。', en: 'Is this person with glasses your older brother?' },
        { who: 'M', ja: 'いいえ、それは 弟[おとうと]です。', en: 'No, that’s my younger brother.' },
        { who: 'M', ja: '兄[あに]は 帽子[ぼうし]を かぶって、かばんを 持[も]って いる 人[ひと]です。', en: 'My older brother is the one wearing a cap and carrying a bag.' },
      ],
      choices: [
        { type: 'person', hair: 'short', top: 'jacket', topColor: 'green', glasses: true, bag: true },
        { type: 'person', hair: 'short', top: 'jacket', topColor: 'green', cap: true },
        { type: 'person', hair: 'short', top: 'jacket', topColor: 'green', cap: true, bag: true },
        { type: 'person', hair: 'short', top: 'jacket', topColor: 'green', bag: true },
      ],
      answer: 2,
      why: 'The one with glasses is the younger brother; the older one wears a cap and carries a bag.',
    },
  ]);
})(typeof window !== 'undefined' ? window : globalThis);
