(function (global) {
  'use strict';

  // More 問題3 (utterance expressions) and 問題4 (quick response) questions.
  // Format: listening-data.js. The replies are only ever spoken, so each one
  // has to be a plausible-sounding thing to say — just not the right one.
  const add = global.LISTENING_ADD;
  const r = (ja, en, say) => (say ? { ja, en, say } : { ja, en });

  add('hatsuwa', [
    { id: 'call-clerk', level: 'N5', scene: { setting: 'shop', left: 'woman', right: 'clerkMan', arrow: 'left' }, replyBy: 'F',
      intro: '店[みせ]で 店[みせ]の 人[ひと]を 呼[よ]びます。何[なん]と 言[い]いますか。',
      choices: [r('すみません。', 'Excuse me.'), r('いらっしゃいませ。', 'Welcome (said by staff).'), r('ごちそうさま。', 'Thanks for the meal.')],
      answer: 0, why: 'すみません gets someone’s attention. いらっしゃいませ is what the staff say to you.' },
    { id: 'home-back', level: 'N5', voices: { M: 'child' }, scene: { setting: 'home', left: 'boy', right: 'mother', arrow: 'left' },
      intro: '学校[がっこう]から 家[いえ]に 帰[かえ]りました。何[なん]と 言[い]いますか。',
      choices: [r('いってきます。', 'I’m off.'), r('ただいま。', 'I’m home.'), r('おかえりなさい。', 'Welcome home (said by the family).')],
      answer: 1, why: 'Coming home you say ただいま; the family answers おかえりなさい.' },
    { id: 'off-to-school', level: 'N5', voices: { F: 'child' }, scene: { setting: 'home', left: 'father', right: 'girl', arrow: 'right' }, replyBy: 'F',
      intro: '朝[あさ]、学校[がっこう]へ 行[い]きます。家[いえ]の 人[ひと]に 何[なん]と 言[い]いますか。',
      choices: [r('いってらっしゃい。', 'See you (said to someone leaving).'), r('ただいま。', 'I’m home.'), r('いってきます。', 'I’m off.')],
      answer: 2, why: 'The one leaving says いってきます; いってらっしゃい is the reply.' },
    { id: 'after-meal', level: 'N5', scene: { setting: 'restaurant', left: 'man2', right: 'waiter', prop: 'rice', arrow: 'left' },
      intro: 'ご飯[はん]を 食[た]べ終[お]わりました。何[なん]と 言[い]いますか。',
      choices: [r('いただきます。', 'Said before eating.'), r('ごちそうさまでした。', 'Thank you for the meal (after eating).'), r('おやすみなさい。', 'Good night.')],
      answer: 1, why: 'After a meal: ごちそうさまでした. いただきます comes before.' },
    { id: 'bump', level: 'N5', scene: { setting: 'street', left: 'woman2', right: 'man', arrow: 'left' }, replyBy: 'F',
      intro: '道[みち]で 人[ひと]に ぶつかって しまいました。何[なん]と 言[い]いますか。',
      choices: [r('ありがとうございます。', 'Thank you.'), r('どういたしまして。', 'You’re welcome.'), r('すみません。', 'Sorry.')],
      answer: 2, why: 'An apology: すみません.' },
    { id: 'evening', level: 'N5', scene: { setting: 'night', left: 'man', right: 'grandma', arrow: 'left' },
      intro: '夜[よる]、近所[きんじょ]の 人[ひと]に 会[あ]いました。何[なん]と 言[い]いますか。',
      choices: [r('こんばんは。', 'Good evening.'), r('おはようございます。', 'Good morning.'), r('いってきます。', 'I’m off.')],
      answer: 0, why: 'In the evening you greet people with こんばんは.' },
    { id: 'happy-birthday', level: 'N5', scene: { setting: 'living', left: 'friend', right: 'woman2', prop: 'cake', holder: 'left', arrow: 'left' }, replyBy: 'F',
      intro: '今日[きょう]は 友[とも]だちの 誕生日[たんじょうび]です。何[なん]と 言[い]いますか。',
      choices: [r('ありがとう。', 'Thank you.'), r('お誕生日[たんじょうび]、おめでとう。', 'Happy birthday.'), r('どういたしまして。', 'You’re welcome.')],
      answer: 1, why: 'お誕生日おめでとう. ありがとう is what the birthday person says back.' },
    { id: 'enter-office', level: 'N5', voices: { M: 'young' }, scene: { setting: 'office', left: 'student', right: 'teacher', arrow: 'left' },
      intro: '先生[せんせい]の 部屋[へや]に 入[はい]ります。何[なん]と 言[い]いますか。',
      choices: [r('いってきます。', 'I’m off.'), r('失礼[しつれい]します。', 'Excuse me (for coming in).'), r('おかえりなさい。', 'Welcome home.')],
      answer: 1, why: 'Entering a teacher’s or boss’s room: 失礼します.' },
    { id: 'offer-seat', level: 'N5', voices: { M: 'young' }, scene: { setting: 'train', left: 'student', right: 'grandma', arrow: 'left' },
      intro: '電車[でんしゃ]で おばあさんに 席[せき]を あげます。何[なん]と 言[い]いますか。',
      choices: [r('どうぞ、座[すわ]って ください。', 'Please, have a seat.'), r('どうも ありがとう。', 'Thanks very much.'), r('いただきます。', 'Said before eating.')],
      answer: 0, why: 'Offering the seat: どうぞ、座ってください. どうもありがとう is her reply.' },
    { id: 'ask-price', level: 'N5', scene: { setting: 'shop', left: 'man', right: 'clerk', prop: 'bag', holder: 'left', arrow: 'left' },
      intro: '店[みせ]で かばんの 値段[ねだん]を 聞[き]きます。何[なん]と 言[い]いますか。',
      choices: [r('これは 何[なん]ですか。', 'What is this?'), r('これを ください。', 'I’ll take this.'), r('これは いくらですか。', 'How much is this?')],
      answer: 2, why: 'いくらですか asks the price.' },
    { id: 'ask-toilet', level: 'N5', scene: { setting: 'station', left: 'tourist', right: 'office', arrow: 'left' },
      intro: '駅[えき]で トイレの 場所[ばしょ]が わかりません。何[なん]と 言[い]いますか。',
      choices: [r('すみません、トイレは どこですか。', 'Excuse me, where is the toilet?'), r('トイレに 行[い]きました。', 'I went to the toilet.'), r('トイレは きれいですね。', 'The toilet is clean, isn’t it?')],
      answer: 0, why: '〜はどこですか asks where something is.' },
    { id: 'first-meet', level: 'N5', scene: { setting: 'office', left: 'officeWoman', right: 'office', arrow: 'left' }, replyBy: 'F',
      intro: '初[はじ]めて 会[あ]った 人[ひと]に 何[なん]と 言[い]いますか。',
      choices: [r('お久[ひさ]しぶりです。', 'Long time no see.'), r('はじめまして。', 'Nice to meet you.'), r('おやすみなさい。', 'Good night.')],
      answer: 1, why: 'Meeting someone for the first time: はじめまして.' },
    { id: 'good-night', level: 'N5', voices: { F: 'child' }, scene: { setting: 'living', left: 'girl', right: 'father', arrow: 'left' }, replyBy: 'F',
      intro: '寝[ね]る 前[まえ]に 家族[かぞく]に 何[なん]と 言[い]いますか。',
      choices: [r('おやすみなさい。', 'Good night.'), r('おはよう。', 'Good morning.'), r('いってきます。', 'I’m off.')],
      answer: 0, why: 'Before going to bed: おやすみなさい.' },
    { id: 'give-gift', level: 'N5', scene: { setting: 'park', left: 'friendMan', right: 'friend', prop: 'gift', holder: 'left', arrow: 'left' },
      intro: '友[とも]だちに プレゼントを あげます。何[なん]と 言[い]いますか。',
      choices: [r('ありがとう。', 'Thank you.'), r('これ、どうぞ。', 'This is for you.'), r('いただきます。', 'Said before eating.')],
      answer: 1, why: 'Handing something over: これ、どうぞ. ありがとう is for the one who receives it.' },
    { id: 'phone-answer', level: 'N5', scene: { setting: 'living', left: 'mother', right: 'man', prop: 'phone', holder: 'right', propSize: 34, arrow: 'right' },
      intro: '電話[でんわ]が かかって きました。電話[でんわ]に 出[で]て、まず 何[なん]と 言[い]いますか。',
      choices: [r('はい、どうぞ。', 'Here you are.'), r('さようなら。', 'Goodbye.'), r('もしもし。', 'Hello? (on the phone)')],
      answer: 2, why: 'Answering the phone: もしもし.' },
    { id: 'get-well', level: 'N4', scene: { setting: 'hospital', left: 'friend', right: 'friendMan', arrow: 'left' }, replyBy: 'F',
      intro: '病院[びょういん]に いる 友[とも]だちに 会[あ]いに 来[き]ました。帰[かえ]る 時[とき]、何[なん]と 言[い]いますか。',
      choices: [r('おめでとう。', 'Congratulations.'), r('お大事[だいじ]に。', 'Take care of yourself.'), r('いってらっしゃい。', 'See you (to someone going out).')],
      answer: 1, why: 'To someone who is ill or hurt: お大事に.' },
    { id: 'say-again', level: 'N4', voices: { M: 'young' }, scene: { setting: 'classroom', left: 'student', right: 'teacherWoman', arrow: 'left' },
      intro: '先生[せんせい]の 話[はなし]が よく 聞[き]こえませんでした。何[なん]と 言[い]いますか。',
      choices: [r('もう 一度[いちど] 言[い]いましょうか。', 'Shall I say it again?'), r('すみません、もう 一度[いちど] お願[ねが]いします。', 'Sorry, once more please.'), r('もう 一度[いちど] 聞[き]いて ください。', 'Please listen once more.')],
      answer: 1, why: 'Asking for a repeat: もう一度お願いします. 言いましょうか offers to repeat yourself.' },
    { id: 'open-window', level: 'N4', scene: { setting: 'office', left: 'office', right: 'officeWoman', arrow: 'left' },
      intro: '部屋[へや]が 暑[あつ]いので、窓[まど]を 開[あ]けたいです。何[なん]と 言[い]いますか。',
      choices: [r('窓[まど]を 開[あ]けても いいですか。', 'May I open the window?'), r('窓[まど]を 開[あ]けて あげましょうか。', 'Shall I open the window for you?'), r('窓[まど]が 開[あ]いて いますね。', 'The window is open, isn’t it?')],
      answer: 0, why: 'Asking permission: 〜てもいいですか.' },
    { id: 'recommend', level: 'N4', scene: { setting: 'restaurant', left: 'woman', right: 'waiter', arrow: 'left' }, replyBy: 'F',
      intro: 'レストランで、店[みせ]の 人[ひと]に おすすめの 料理[りょうり]を 聞[き]きます。何[なん]と 言[い]いますか。',
      choices: [r('何[なに]を 作[つく]りましょうか。', 'What shall I make?'), r('何[なに]を 食[た]べましたか。', 'What did you eat?'), r('おすすめは 何[なん]ですか。', 'What do you recommend?')],
      answer: 2, why: 'おすすめは何ですか asks for a recommendation.' },
    { id: 'running-late', level: 'N4', voices: { M: 'young' }, scene: { setting: 'street', left: 'friendMan', right: 'friend', prop: 'smartphone', holder: 'left', propSize: 30, arrow: 'left' },
      intro: '約束[やくそく]の 時間[じかん]に 遅[おく]れそうです。友[とも]だちに 電話[でんわ]で 何[なん]と 言[い]いますか。',
      choices: [r('ごめん、少[すこ]し 遅[おく]れる。', 'Sorry, I’ll be a little late.'), r('遅[おく]れないでね。', 'Don’t be late, OK?'), r('もう 遅[おそ]いよ。', 'It’s already late.')],
      answer: 0, why: 'Warning that you’ll be late: 少し遅れる. 遅れないでね is what the friend might say.' },
    { id: 'carry-for-teacher', level: 'N4', voices: { M: 'young' }, scene: { setting: 'classroom', left: 'student', right: 'teacher', prop: 'box', holder: 'right', propSize: 40, arrow: 'left' },
      intro: '先生[せんせい]が 重[おも]い 荷物[にもつ]を 持[も]って います。何[なん]と 言[い]いますか。',
      choices: [r('持[も]って ください。', 'Please hold it.'), r('お持[も]ちしましょうか。', 'Shall I carry that for you?'), r('持[も]って いただけませんか。', 'Could you carry it for me?')],
      answer: 1, why: 'お持ちしましょうか humbly offers to carry it.' },
    { id: 'borrow-umbrella', level: 'N4', scene: { setting: 'rain', left: 'office', right: 'officeWoman', prop: 'umbrella', holder: 'right', propSize: 40, arrow: 'left' },
      intro: '雨[あめ]が 降[ふ]って いますが、傘[かさ]が ありません。会社[かいしゃ]の 人[ひと]に 何[なん]と 言[い]いますか。',
      choices: [r('傘[かさ]を 貸[か]して いただけませんか。', 'Could you lend me an umbrella?'), r('傘[かさ]を 貸[か]しましょうか。', 'Shall I lend you an umbrella?'), r('傘[かさ]を 借[か]りて ください。', 'Please borrow an umbrella.')],
      answer: 0, why: 'Asking to borrow it: 貸していただけませんか. 貸しましょうか is an offer.' },
    { id: 'take-message', level: 'N4', scene: { setting: 'office', left: 'officeWoman', right: 'office', prop: 'phone', holder: 'left', propSize: 30, arrow: 'left' }, replyBy: 'F',
      intro: '電話[でんわ]を かけましたが、田中[たなか]さんは いません。電話[でんわ]に 出[で]た 人[ひと]に 何[なん]と 言[い]いますか。',
      choices: [r('田中[たなか]さんに 伝[つた]えましょうか。', 'Shall I tell Tanaka-san?'), r('田中[たなか]さんに 聞[き]いて ください。', 'Please ask Tanaka-san.'), r('では、田中[たなか]さんに 伝[つた]えて いただけますか。', 'Then could you pass on a message to Tanaka-san?')],
      answer: 2, why: 'Leaving a message: 伝えていただけますか. 伝えましょうか is what the other person offers.' },
    { id: 'decline', level: 'N4', scene: { setting: 'park', left: 'friend', right: 'friendMan', arrow: 'left' }, replyBy: 'F',
      intro: '友[とも]だちに 映画[えいが]に 誘[さそ]われましたが、その 日[ひ]は 用事[ようじ]が あります。何[なん]と 言[い]いますか。',
      choices: [r('いいね、行[い]こう。', 'Great, let’s go.'), r('ごめん、その 日[ひ]は ちょっと…。', 'Sorry, that day is a bit…'), r('どうして 行[い]かないの。', 'Why aren’t you going?')],
      answer: 1, why: 'A soft refusal: その日はちょっと….' },
    { id: 'congrats-pass', level: 'N4', scene: { setting: 'classroom', left: 'schoolgirl', right: 'student', arrow: 'left' }, replyBy: 'F', voices: { F: 'young' },
      intro: '友[とも]だちが 大学[だいがく]の 試験[しけん]に 合格[ごうかく]しました。何[なん]と 言[い]いますか。',
      choices: [r('合格[ごうかく]、おめでとう。', 'Congratulations on passing.'), r('頑張[がんば]ってね。', 'Good luck.'), r('残念[ざんねん]だったね。', 'That’s a shame.')],
      answer: 0, why: 'They passed: おめでとう. 頑張ってね is for before the exam.' },
  ]);

  add('sokuji', [
    { id: 'how-are-you', level: 'N5', lines: [{ who: 'F', ja: 'お元気[げんき]ですか。', en: 'How are you?' }], replyBy: 'M',
      choices: [r('はい、元気[げんき]です。', 'I’m fine.'), r('はい、ありがとうございました。', 'Yes, thank you (for what you did).'), r('いいえ、元気[げんき]でした。', 'No, I was fine.')],
      answer: 0, why: 'お元気ですか → はい、元気です.' },
    { id: 'whose-umbrella', level: 'N5', lines: [{ who: 'M', ja: 'これは だれの 傘[かさ]ですか。', en: 'Whose umbrella is this?' }], replyBy: 'F',
      choices: [r('青[あお]い 傘[かさ]です。', 'It’s a blue umbrella.'), r('わたしのです。', 'It’s mine.'), r('そこに あります。', 'It’s there.')],
      answer: 1, why: 'だれの asks whose: わたしのです.' },
    { id: 'where-live', level: 'N5', lines: [{ who: 'F', ja: 'どこに 住[す]んで いますか。', en: 'Where do you live?' }], replyBy: 'M',
      choices: [r('三年[さんねん]です。', 'Three years.'), r('一人[ひとり]で 住[す]んで います。', 'I live alone.'), r('横浜[よこはま]です。', 'In Yokohama.')],
      answer: 2, why: 'どこに asks where: 横浜です.' },
    { id: 'class-time', level: 'N5', lines: [{ who: 'M', ja: '明日[あした]の 授業[じゅぎょう]は 何時[なんじ]からですか。', en: 'What time does tomorrow’s class start?' }], replyBy: 'F',
      choices: [r('九時[くじ]からです。', 'From nine.'), r('九時間[くじかん]です。', 'Nine hours.'), r('毎日[まいにち]です。', 'Every day.')],
      answer: 0, why: '何時から asks the starting time.' },
    { id: 'hungry', level: 'N5', lines: [{ who: 'F', ja: 'おなかが すきましたね。', en: 'I’m hungry, aren’t you?' }], replyBy: 'M',
      choices: [r('じゃ、寝[ね]ましょう。', 'Then let’s sleep.'), r('じゃ、何[なに]か 食[た]べましょう。', 'Then let’s eat something.'), r('ごちそうさまでした。', 'Thanks for the meal.')],
      answer: 1, why: 'Hungry → let’s eat something.' },
    { id: 'favourite-colour', level: 'N5', lines: [{ who: 'M', ja: '何色[なにいろ]が 好[す]きですか。', en: 'What colour do you like?' }], replyBy: 'F',
      choices: [r('はい、好[す]きです。', 'Yes, I like it.'), r('赤[あか]い 本[ほん]です。', 'It’s a red book.'), r('青[あお]が 好[す]きです。', 'I like blue.')],
      answer: 2, why: '何色 asks which colour: 青が好きです.' },
    { id: 'cold-today', level: 'N5', lines: [{ who: 'F', ja: '今日[きょう]は 寒[さむ]いですね。', en: 'It’s cold today, isn’t it?' }], replyBy: 'M',
      choices: [r('ええ、本当[ほんとう]に 寒[さむ]いですね。', 'Yes, it really is cold.'), r('いいえ、寒[さむ]かったです。', 'No, it was cold.'), r('ありがとうございます。', 'Thank you.')],
      answer: 0, why: 'Agree with small talk: ええ、本当に寒いですね.' },
    { id: 'siblings', level: 'N5', lines: [{ who: 'M', ja: '兄弟[きょうだい]は いますか。', en: 'Do you have any brothers or sisters?' }], replyBy: 'F',
      choices: [r('二十歳[はたち]です。', 'I’m twenty.'), r('はい、姉[あね]と 弟[おとうと]が います。', 'Yes, an older sister and a younger brother.'), r('三階[さんがい]です。', 'The third floor.')],
      answer: 1, why: '兄弟はいますか → 姉と弟がいます.' },
    { id: 'thanks-help', level: 'N5', lines: [{ who: 'F', ja: '手伝[てつだ]って くれて、ありがとう。', en: 'Thanks for helping me.' }], replyBy: 'M',
      choices: [r('いいえ、どういたしまして。', 'You’re welcome.'), r('はい、ありがとう。', 'Yes, thanks.'), r('いただきます。', 'Said before eating.')],
      answer: 0, why: 'Answer thanks with どういたしまして.' },
    { id: 'what-bought', level: 'N5', lines: [{ who: 'M', ja: '昨日[きのう]、デパートで 何[なに]を 買[か]いましたか。', en: 'What did you buy at the department store yesterday?' }], replyBy: 'F',
      choices: [r('デパートで 買[か]いました。', 'I bought it at the department store.'), r('靴[くつ]を 買[か]いました。', 'I bought some shoes.'), r('昨日[きのう] 買[か]いました。', 'I bought it yesterday.')],
      answer: 1, why: '何を asks what: 靴を買いました.' },
    { id: 'when-came', level: 'N5', lines: [{ who: 'F', ja: 'いつ 日本[にほん]に 来[き]ましたか。', en: 'When did you come to Japan?' }], replyBy: 'M',
      choices: [r('飛行機[ひこうき]で 来[き]ました。', 'I came by plane.'), r('一人[ひとり]で 来[き]ました。', 'I came alone.'), r('去年[きょねん]の 四月[しがつ]です。', 'Last April.')],
      answer: 2, why: 'いつ asks when: 去年の四月.' },
    { id: 'how-was-trip', level: 'N5', lines: [{ who: 'M', ja: '旅行[りょこう]は どうでしたか。', en: 'How was your trip?' }], replyBy: 'F',
      choices: [r('とても 楽[たの]しかったです。', 'It was great fun.'), r('来週[らいしゅう] 行[い]きます。', 'I’m going next week.'), r('電車[でんしゃ]で 行[い]きます。', 'I’ll go by train.')],
      answer: 0, why: 'どうでしたか asks how it was: 楽しかったです.' },
    { id: 'may-sit', level: 'N5', lines: [{ who: 'F', ja: 'ここに 座[すわ]っても いいですか。', en: 'May I sit here?' }], replyBy: 'M',
      choices: [r('いいえ、座[すわ]りません。', 'No, I won’t sit.'), r('ええ、どうぞ。', 'Yes, please do.'), r('はい、座[すわ]りました。', 'Yes, I sat down.')],
      answer: 1, why: 'Giving permission: ええ、どうぞ.' },
    { id: 'whats-that', level: 'N5', lines: [{ who: 'M', ja: 'それは 何[なん]ですか。', en: 'What’s that?' }], replyBy: 'F',
      choices: [r('日本[にほん]の お菓子[かし]です。', 'Japanese sweets.'), r('あそこです。', 'Over there.'), r('田中[たなか]さんです。', 'It’s Tanaka-san.')],
      answer: 0, why: '何ですか asks what a thing is.' },
    { id: 'what-drink', level: 'N5', lines: [{ who: 'F', ja: '何[なに]を 飲[の]みますか。', en: 'What will you drink?' }], replyBy: 'M',
      choices: [r('はい、飲[の]みました。', 'Yes, I drank it.'), r('コップに 入[い]れます。', 'I’ll put it in a glass.'), r('じゃあ、お茶[ちゃ]を お願[ねが]いします。', 'Then tea, please.')],
      answer: 2, why: '何を飲みますか → お茶をお願いします.' },
    { id: 'birthday-when', level: 'N5', lines: [{ who: 'M', ja: '誕生日[たんじょうび]は いつですか。', en: 'When’s your birthday?' }], replyBy: 'F',
      choices: [r('二十歳[はたち]です。', 'I’m twenty.'), r('三月[さんがつ] 三日[みっか]です。', 'March the 3rd.'), r('毎年[まいとし]です。', 'Every year.')],
      answer: 1, why: 'いつ asks the date: 三月三日.' },
    { id: 'see-you', level: 'N5', lines: [{ who: 'F', ja: 'じゃ、また 明日[あした]。', en: 'See you tomorrow, then.' }], replyBy: 'M',
      choices: [r('はじめまして。', 'Nice to meet you.'), r('いってらっしゃい。', 'See you (to someone going out).'), r('ええ、また 明日[あした]。', 'Yes, see you tomorrow.')],
      answer: 2, why: 'Answer また明日 with また明日.' },
    { id: 'help-offer', level: 'N4', lines: [{ who: 'M', ja: '重[おも]そうですね。手伝[てつだ]いましょうか。', en: 'That looks heavy. Shall I help?' }], replyBy: 'F',
      choices: [r('ありがとうございます。お願[ねが]いします。', 'Thank you, yes please.'), r('はい、手伝[てつだ]います。', 'Yes, I’ll help.'), r('手伝[てつだ]って あげます。', 'I’ll help you.')],
      answer: 0, why: 'Accept an offer of help with お願いします.' },
    { id: 'eaten-yet', level: 'N4', lines: [{ who: 'F', ja: 'もう 昼[ひる]ご飯[はん]を 食[た]べましたか。', en: 'Have you had lunch yet?' }], replyBy: 'M',
      choices: [r('はい、まだです。', 'Yes, not yet.'), r('いいえ、まだです。', 'No, not yet.'), r('いいえ、食[た]べました。', 'No, I ate.')],
      answer: 1, why: 'もう〜ましたか → いいえ、まだです (or はい、食べました).' },
    { id: 'attend', level: 'N4', lines: [{ who: 'M', ja: '明日[あした]の 会議[かいぎ]に 出[で]られますか。', en: 'Can you attend tomorrow’s meeting?' }], replyBy: 'F',
      choices: [r('いいえ、出[で]ませんでした。', 'No, I didn’t attend.'), r('はい、出[で]ました。', 'Yes, I attended.'), r('すみません、明日[あした]は ちょっと…。', 'Sorry, tomorrow is a bit difficult.')],
      answer: 2, why: 'He asks about tomorrow; the past-tense replies don’t fit.' },
    { id: 'report-done', level: 'N4', lines: [{ who: 'F', ja: 'レポートは もう 書[か]き終[お]わりましたか。', en: 'Have you finished writing the report?' }], replyBy: 'M',
      choices: [r('いいえ、あと 少[すこ]しです。', 'No, almost.'), r('はい、これから 書[か]きます。', 'Yes, I’ll write it now.'), r('いいえ、書[か]き終[お]わりました。', 'No, I’ve finished.')],
      answer: 0, why: 'Not finished yet: いいえ、あと少しです.' },
    { id: 'look-pale', level: 'N4', lines: [{ who: 'M', ja: 'どう したんですか。顔色[かおいろ]が 悪[わる]いですよ。', en: 'What’s wrong? You look pale.' }], replyBy: 'F',
      choices: [r('はい、元気[げんき]です。', 'Yes, I’m fine.'), r('ちょっと 頭[あたま]が 痛[いた]いんです。', 'I have a bit of a headache.'), r('顔[かお]を 洗[あら]いました。', 'I washed my face.')],
      answer: 1, why: 'Explain what’s wrong with 〜んです.' },
    { id: 'been-kyoto', level: 'N4', lines: [{ who: 'F', ja: '京都[きょうと]へ 行[い]った ことが ありますか。', en: 'Have you ever been to Kyoto?' }], replyBy: 'M',
      choices: [r('はい、行[い]きます。', 'Yes, I go.'), r('京都[きょうと]は 遠[とお]いです。', 'Kyoto is far.'), r('いいえ、まだ 一度[いちど]も ありません。', 'No, never.')],
      answer: 2, why: '〜たことがありますか asks about experience.' },
    { id: 'take-break', level: 'N4', lines: [{ who: 'M', ja: '少[すこ]し 休[やす]みませんか。', en: 'Shall we take a short break?' }], replyBy: 'F',
      choices: [r('はい、休[やす]みませんでした。', 'Yes, I didn’t rest.'), r('そうですね、休[やす]みましょう。', 'Good idea, let’s take a break.'), r('いいえ、休[やす]んで ください。', 'No, please rest.')],
      answer: 1, why: 'Accept the suggestion with 〜ましょう.' },
    { id: 'borrow-dictionary', level: 'N4', lines: [{ who: 'F', ja: 'この 辞書[じしょ]、ちょっと 借[か]りても いいですか。', en: 'May I borrow this dictionary for a moment?' }], replyBy: 'M',
      choices: [r('ええ、どうぞ。', 'Sure, go ahead.'), r('ええ、借[か]ります。', 'Yes, I’ll borrow it.'), r('いいえ、貸[か]しました。', 'No, I lent it.')],
      answer: 0, why: 'Giving permission: ええ、どうぞ.' },
    { id: 'too-expensive', level: 'N4', lines: [{ who: 'M', ja: 'この かばん、ちょっと 高[たか]すぎますね。', en: 'This bag is a bit too expensive.' }], replyBy: 'F',
      choices: [r('ええ、安[やす]いですね。', 'Yes, it’s cheap.'), r('高[たか]い ところに あります。', 'It’s up high.'), r('じゃあ、もう 少[すこ]し 安[やす]いのを 見[み]ましょう。', 'Then let’s look at a cheaper one.')],
      answer: 2, why: 'Too expensive → look at a cheaper one.' },
    { id: 'wedding', level: 'N4', lines: [{ who: 'F', ja: 'ご結婚[けっこん]、おめでとうございます。', en: 'Congratulations on your wedding.' }], replyBy: 'M',
      choices: [r('どういたしまして。', 'You’re welcome.'), r('ありがとうございます。', 'Thank you.'), r('お大事[だいじ]に。', 'Take care.')],
      answer: 1, why: 'Accept congratulations with ありがとうございます.' },
    { id: 'bus-not-coming', level: 'N4', lines: [{ who: 'M', ja: 'バスが なかなか 来[き]ませんね。', en: 'The bus just isn’t coming, is it?' }], replyBy: 'F',
      choices: [r('そうですね。歩[ある]いて 行[い]きましょうか。', 'No. Shall we walk?'), r('ええ、もう 来[き]ましたね。', 'Yes, it’s already come.'), r('バスで 来[き]ました。', 'I came by bus.')],
      answer: 0, why: 'Agree and suggest something: 歩いて行きましょうか.' },
    { id: 'speak-english', level: 'N4', lines: [{ who: 'F', ja: '英語[えいご]が 話[はな]せますか。', en: 'Can you speak English?' }], replyBy: 'M',
      choices: [r('英語[えいご]で 話[はな]しました。', 'I spoke in English.'), r('はい、話[はな]して ください。', 'Yes, please speak.'), r('少[すこ]しだけ 話[はな]せます。', 'Just a little.')],
      answer: 2, why: '話せますか asks about ability: 少しだけ話せます.' },
    { id: 'if-time', level: 'N4', lines: [{ who: 'M', ja: 'もし 時間[じかん]が あったら、ちょっと 手伝[てつだ]って もらえますか。', en: 'If you have time, could you give me a hand?' }], replyBy: 'F',
      choices: [r('はい、手伝[てつだ]って もらいます。', 'Yes, I’ll have you help.'), r('ええ、いいですよ。', 'Sure.'), r('時間[じかん]が ありました。', 'I had time.')],
      answer: 1, why: 'A request (〜てもらえますか) → ええ、いいですよ.' },
    { id: 'ask-way', level: 'N4', lines: [{ who: 'F', ja: 'すみません、駅[えき]へ 行[い]く 道[みち]を 教[おし]えて いただけませんか。', en: 'Excuse me, could you tell me the way to the station?' }], replyBy: 'M',
      choices: [r('ええ、この 道[みち]を まっすぐ 行[い]って ください。', 'Sure, go straight along this road.'), r('駅[えき]で 会[あ]いましょう。', 'Let’s meet at the station.'), r('道[みち]が 広[ひろ]いですね。', 'The road is wide, isn’t it?')],
      answer: 0, why: 'She asks for directions; give them.' },
    { id: 'kept-waiting', level: 'N4', lines: [{ who: 'M', ja: 'お待[ま]たせしました。', en: 'Sorry to keep you waiting.' }], replyBy: 'F',
      choices: [r('はい、待[ま]ちます。', 'Yes, I’ll wait.'), r('ごちそうさまでした。', 'Thanks for the meal.'), r('いいえ、私[わたし]も 今[いま] 来[き]た ところです。', 'Not at all, I’ve only just arrived myself.')],
      answer: 2, why: 'A kind answer to お待たせしました: 今来たところです.' },
    { id: 'close-window', level: 'N4', lines: [{ who: 'F', ja: '寒[さむ]いので、窓[まど]を 閉[し]めて もらえませんか。', en: 'It’s cold — could you close the window?' }], replyBy: 'M',
      choices: [r('あ、すみません。すぐ 閉[し]めます。', 'Oh, sorry. I’ll close it right away.'), r('窓[まど]を 開[あ]けましょうか。', 'Shall I open the window?'), r('寒[さむ]く なりましたね。', 'It’s got cold, hasn’t it?')],
      answer: 0, why: 'Do what she asks: すぐ閉めます.' },
    { id: 'why-japanese', level: 'N4', lines: [{ who: 'M', ja: 'どうして 日本語[にほんご]を 勉強[べんきょう]して いるんですか。', en: 'Why are you studying Japanese?' }], replyBy: 'F',
      choices: [r('毎日[まいにち] 二時間[にじかん]です。', 'Two hours every day.'), r('日本[にほん]の 会社[かいしゃ]で 働[はたら]きたいからです。', 'Because I want to work for a Japanese company.'), r('先生[せんせい]に 習[なら]って います。', 'I learn from a teacher.')],
      answer: 1, why: 'どうして asks why: 〜からです.' },
    { id: 'when-arrived', level: 'N4', lines: [{ who: 'F', ja: 'いつ 着[つ]いたんですか。', en: 'When did you arrive?' }], replyBy: 'M',
      choices: [r('新幹線[しんかんせん]で 着[つ]きました。', 'I arrived by shinkansen.'), r('これから 着[つ]きます。', 'I’ll arrive now.'), r('さっき 着[つ]いた ところです。', 'I’ve just arrived.')],
      answer: 2, why: 'いつ asks when: さっき着いたところです.' },
    { id: 'smoking', level: 'N4', lines: [{ who: 'M', ja: 'ここで たばこを 吸[す]っても いいですか。', en: 'May I smoke here?' }], replyBy: 'F',
      choices: [r('すみません、ここは 禁煙[きんえん]なんです。', 'Sorry, this is non-smoking.'), r('はい、吸[す]いました。', 'Yes, I smoked.'), r('たばこは 高[たか]いですね。', 'Cigarettes are expensive, aren’t they?')],
      answer: 0, why: 'Politely refuse: ここは禁煙なんです.' },
  ]);
})(typeof window !== 'undefined' ? window : globalThis);
