(function (global) {
  'use strict';

  // Still more N5 and N4 conversations (format: listening-data.js).
  const add = global.LISTENING_ADD;
  const items = (...list) => ({ type: 'items', items: list.map(x => (Array.isArray(x) ? x : [x, 1])) });
  const r = (ja, en, say) => (say ? { ja, en, say } : { ja, en });
  const M = 'M', F = 'F';
  const l = (who, ja, en, say) => (say ? { who, ja, en, say } : { who, ja, en });

  add('kadai', [
    { id: 'picnic-drinks', level: 'N5',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は 何[なに]を 買[か]って いきますか。',
      lines: [
        l(F, '明日[あした]の ピクニック、お弁当[べんとう]は わたしが 作[つく]りますね。', 'I’ll make the packed lunches for tomorrow’s picnic.'),
        l(M, 'ありがとう。じゃあ、ぼくは 飲[の]み物[もの]を 買[か]って いきます。お茶[ちゃ]と ジュースで いいですか。', 'Thanks. Then I’ll buy the drinks. Is tea and juice OK?'),
        l(F, 'お茶[ちゃ]は うちに あるから、持[も]って いきます。ジュースだけ お願[ねが]いします。', 'We have tea at home, so I’ll bring it. Just the juice, please.'),
      ],
      choices: [items('tea'), items('juice'), items('tea', 'juice'), items('bento', 'juice')],
      answer: 1, why: 'She makes the lunches and brings the tea, so he only buys juice.' },
    { id: 'shop-eggs', level: 'N5',
      intro: 'お母[かあ]さんと 男[おとこ]の子[こ]が 話[はな]しています。男[おとこ]の子[こ]は 何[なに]を 買[か]いますか。',
      voices: { M: 'child' },
      lines: [
        l(F, 'スーパーで 卵[たまご]と 牛乳[ぎゅうにゅう]を 買[か]って きて。', 'Go and get eggs and milk from the supermarket.'),
        l(M, 'パンは？', 'What about bread?'),
        l(F, 'パンは まだ あるから いいわ。あ、りんごも 一[ひと]つ お願[ねが]い。', 'We still have bread, so that’s fine. Oh, and one apple, please.'),
      ],
      choices: [items('egg', 'milk'), items('egg', 'milk', 'bread'), items('egg', 'milk', 'apple'), items('milk', 'bread', 'apple')],
      answer: 2, why: 'Eggs and milk, no bread, and an apple too.' },
    { id: 'meet-clock-tower', level: 'N5',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 電話[でんわ]で 話[はな]しています。二人[ふたり]は 何時[なんじ]に 会[あ]いますか。',
      lines: [
        l(M, '土曜日[どようび]、映画[えいが]は 二時[にじ]からですね。', 'On Saturday the film starts at two, right?'),
        l(F, 'ええ。その 前[まえ]に 一緒[いっしょ]に 昼[ひる]ご飯[はん]を 食[た]べませんか。', 'Yes. Shall we have lunch together before that?'),
        l(M, 'いいですね。じゃあ、十二時[じゅうにじ]に 駅[えき]で 会[あ]いましょう。', 'Good idea. Then let’s meet at the station at twelve.'),
      ],
      choices: [{ type: 'clock', h: 12, m: 0 }, { type: 'clock', h: 2, m: 0 }, { type: 'clock', h: 1, m: 0 }, { type: 'clock', h: 11, m: 30 }],
      answer: 0, why: 'The film is at two, but they meet for lunch at twelve.' },
    { id: 'clean-room-first', level: 'N5',
      intro: '先生[せんせい]が 学生[がくせい]に 話[はな]しています。学生[がくせい]は 初[はじ]めに 何[なに]を しますか。',
      lines: [
        l(F, 'みなさん、今日[きょう]は 教室[きょうしつ]の 掃除[そうじ]を します。', 'Everyone, today we’ll clean the classroom.'),
        l(F, '初[はじ]めに 窓[まど]を 開[あ]けて ください。それから 机[つくえ]を 後[うし]ろに 運[はこ]んで、床[ゆか]を 掃[は]きます。ごみは 最後[さいご]に 捨[す]てて ください。', 'First open the windows. Then carry the desks to the back and sweep the floor. Throw out the rubbish last.'),
      ],
      choices: [{ type: 'room', at: 'window' }, { type: 'room', at: 'door' }, items('broom'), items('trash')],
      answer: 0, why: '初めに窓を開けてください — the windows come first.' },
    { id: 'birthday-gift-girl', level: 'N4',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は 妹[いもうと]に 何[なに]を あげますか。',
      lines: [
        l(M, '妹[いもうと]の 誕生日[たんじょうび]に 何[なに]を あげたら いいと 思[おも]う？ 本[ほん]が 好[す]きなんだけど。', 'What do you think I should give my sister for her birthday? She likes books.'),
        l(F, '本[ほん]は 好[す]きな 作家[さっか]が わからないと 難[むずか]しいよ。 かわいい かさは どう？ 毎日[まいにち] 使[つか]えるし。', 'Books are hard if you don’t know her favourite writer. How about a cute umbrella? She can use it every day.'),
        l(M, 'そうだね。先月[せんげつ] かさを なくしたって 言[い]って いたから、それに する。', 'True. She said she lost her umbrella last month, so I’ll go with that.'),
      ],
      choices: [items('book'), items({ name: 'umbrella', color: 'pink' }), items('bag'), items('necklace')],
      answer: 1, why: 'She lost her umbrella last month, so he gives her a cute one.' },
    { id: 'office-copy-count', level: 'N4',
      intro: '会社[かいしゃ]で 女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は コピーを 何枚[なんまい] しますか。',
      lines: [
        l(F, '会議[かいぎ]の 資料[しりょう]、コピーして もらえますか。出[で]る 人[ひと]は 十人[じゅうにん]です。', 'Could you copy the meeting papers? Ten people are attending.'),
        l(M, 'はい、十枚[じゅうまい]ですね。', 'Sure, ten copies then.'),
        l(F, 'あ、部長[ぶちょう]の 分[ぶん]も お願[ねが]いします。わたしは 自分[じぶん]のが あるので いりません。', 'Oh, one for the manager too, please. I have my own, so I don’t need one.'),
      ],
      choices: [{ type: 'text', text: '9枚' }, { type: 'text', text: '10枚' }, { type: 'text', text: '11枚' }, { type: 'text', text: '12枚' }],
      answer: 2, why: 'Ten attendees plus the manager makes eleven; she doesn’t need one.' },
    { id: 'train-transfer', level: 'N4',
      intro: '駅[えき]で 女[おんな]の人[ひと]と 駅員[えきいん]が 話[はな]しています。女[おんな]の人[ひと]は 何番線[なんばんせん]の 電車[でんしゃ]に 乗[の]りますか。',
      lines: [
        l(F, 'すみません、空港[くうこう]へ 行[い]きたいんですが。', 'Excuse me, I’d like to go to the airport.'),
        l(M, '空港[くうこう]へは 三番線[さんばんせん]の 電車[でんしゃ]ですが、今日[きょう]は 工事[こうじ]で 止[と]まって います。五番線[ごばんせん]の 電車[でんしゃ]に 乗[の]って、次[つぎ]の 駅[えき]で 乗[の]り換[か]えて ください。', 'For the airport it’s platform 3, but it’s stopped today for works. Take the train from platform 5 and change at the next station.'),
        l(F, '五番線[ごばんせん]ですね。ありがとうございます。', 'Platform 5. Thank you.'),
      ],
      choices: [{ type: 'platform', num: 3 }, { type: 'platform', num: 5 }, { type: 'platform', num: 2 }, { type: 'platform', num: 4 }],
      answer: 1, why: 'Platform 3 is closed for works, so she takes platform 5 and changes.' },
    { id: 'pack-for-rain', level: 'N4',
      intro: '男[おとこ]の子[こ]と お母[かあ]さんが 話[はな]しています。男[おとこ]の子[こ]は 何[なに]を 持[も]って いきますか。',
      voices: { M: 'child' },
      lines: [
        l(M, 'お母[かあ]さん、今日[きょう]は 遠足[えんそく]だから、帽子[ぼうし]を 持[も]って いくね。', 'Mum, it’s the school trip today, so I’ll take my hat.'),
        l(F, '天気予報[てんきよほう]では 午後[ごご]から 雨[あめ]だって。帽子[ぼうし]より かさの ほうが いいよ。', 'The forecast says rain from the afternoon. An umbrella is better than a hat.'),
        l(M, 'じゃあ、帽子[ぼうし]は やめて、かさと タオルを 持[も]って いく。', 'Then I’ll leave the hat and take an umbrella and a towel.'),
      ],
      choices: [items('hat', 'towel'), items('umbrella', 'towel'), items('hat', 'umbrella'), items('umbrella')],
      answer: 1, why: 'Rain is coming, so no hat: an umbrella and a towel.' },
  ]);

  add('point', [
    { id: 'when-holiday', level: 'N5',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は いつ 国[くに]へ 帰[かえ]りますか。',
      lines: [
        l(M, '夏休[なつやす]みに 国[くに]へ 帰[かえ]りますか。', 'Are you going back to your country in the summer holidays?'),
        l(F, 'はい。八月[はちがつ]の 十日[とおか]に 帰[かえ]ります。', 'Yes. I’m going back on the tenth of August.'),
        l(M, '何日[なんにち]に 戻[もど]りますか。', 'When are you coming back?'),
        l(F, '二十日[はつか]です。', 'On the twentieth.'),
      ],
      choices: [{ type: 'calendar', mark: 10 }, { type: 'calendar', mark: 20 }, { type: 'calendar', mark: 8 }, { type: 'calendar', mark: 4 }],
      answer: 0, why: 'She goes home on the 10th (十日) and comes back on the 20th.' },
    { id: 'how-many-cats', level: 'N5',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]の 家[いえ]に 猫[ねこ]は 何匹[なんびき] いますか。',
      lines: [
        l(M, '猫[ねこ]が 好[す]きですか。', 'Do you like cats?'),
        l(F, 'はい。家[いえ]に 二匹[にひき] いましたが、先月[せんげつ] もう 一匹[いっぴき] 来[き]ました。', 'Yes. I had two at home, and last month another one came.'),
        l(M, 'にぎやかですね。', 'Lively!'),
      ],
      choices: [items(['cat', 1]), items(['cat', 2]), items(['cat', 3]), items(['cat', 4])],
      answer: 2, why: 'Two, plus one more last month: three cats.' },
    { id: 'weather-sunday', level: 'N5',
      intro: 'テレビで 天気予報[てんきよほう]を 聞[き]いています。日曜日[にちようび]は どんな 天気[てんき]ですか。',
      lines: [
        l(F, '週末[しゅうまつ]の 天気[てんき]です。土曜日[どようび]は 一日[いちにち] 雨[あめ]でしょう。', 'Here’s the weekend weather. Saturday will be rainy all day.', '週末の天気です。土曜日は一日、あめでしょう。'),
        l(F, '日曜日[にちようび]は 朝[あさ]は くもりですが、午後[ごご]は 晴[は]れるでしょう。', 'Sunday will be cloudy in the morning but sunny in the afternoon.'),
      ],
      choices: [{ type: 'weather', am: 'rain', pm: 'rain' }, { type: 'weather', am: 'cloudy', pm: 'sun' }, { type: 'weather', am: 'sun', pm: 'cloudy' }, { type: 'weather', am: 'cloudy', pm: 'rain' }],
      answer: 1, why: 'Sunday: cloudy in the morning, sunny in the afternoon.' },
    { id: 'bus-number-school', level: 'N5',
      intro: '男[おとこ]の 学生[がくせい]と 女[おんな]の人[ひと]が 話[はな]しています。男[おとこ]の 学生[がくせい]は 何番[なんばん]の バスに 乗[の]りますか。',
      voices: { M: 'young' },
      lines: [
        l(M, 'すみません、さくら大学[だいがく]へ 行[い]く バスは 何番[なんばん]ですか。', 'Excuse me, which number bus goes to Sakura University?'),
        l(F, '七番[ななばん]と 九番[きゅうばん]ですよ。でも 九番[きゅうばん]は 今日[きょう]は 日曜日[にちようび]だから 来[き]ません。', 'Numbers 7 and 9. But the 9 doesn’t run today, since it’s Sunday.'),
        l(M, 'わかりました。ありがとうございます。', 'I see. Thank you.'),
      ],
      choices: [{ type: 'bus', num: 7 }, { type: 'bus', num: 9 }, { type: 'bus', num: 1 }, { type: 'bus', num: 4 }],
      answer: 0, why: 'The 9 doesn’t run on Sundays, so the 7.' },
    { id: 'phone-number-shop', level: 'N4',
      intro: '女[おんな]の人[ひと]が 店[みせ]に 電話[でんわ]を しています。店[みせ]の 新[あたら]しい 電話番号[でんわばんごう]は どれですか。',
      lines: [
        l(F, 'もしもし、そちらの 電話番号[でんわばんごう]は 〇三[ぜろさん]の 四五六七[よんごーろくなな]の 八九一二[はちきゅういちに]で いいですか。', 'Hello, is your number 03-4567-8912?', 'もしもし、そちらの電話番号は、ぜろさんの、よんごーろくななの、はちきゅういちにで、いいですか。'),
        l(M, '来月[らいげつ]から 変[か]わります。最後[さいご]が 八九二一[はちきゅうにいち]に なります。', 'It changes from next month. The last part becomes 8921.', '来月から変わります。最後が、はちきゅうにいちに、なります。'),
      ],
      choices: [{ type: 'text', text: '03-4567-8912' }, { type: 'text', text: '03-4567-8921' }, { type: 'text', text: '03-4576-8921' }, { type: 'text', text: '03-4567-9821' }],
      answer: 1, why: 'Only the last four digits change, to 8921.' },
    { id: 'why-late-train', level: 'N4',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は どうして 遅[おく]れましたか。',
      lines: [
        l(F, '遅[おそ]かったですね。電車[でんしゃ]が 止[と]まったんですか。', 'You’re late. Did the trains stop?'),
        l(M, 'いいえ、電車[でんしゃ]は 大丈夫[だいじょうぶ]でした。家[いえ]を 出[で]た あとで 財布[さいふ]を 忘[わす]れた ことに 気[き]が ついて、取[と]りに 帰[かえ]ったんです。', 'No, the trains were fine. After I left home I noticed I’d forgotten my wallet and went back for it.'),
      ],
      choices: [items('train-stopped'), items('wallet'), items('alarm'), items('rain')],
      answer: 1, why: 'Not the train: he went back home for his forgotten wallet.' },
    { id: 'which-shirt', level: 'N4',
      intro: '店[みせ]で 女[おんな]の人[ひと]と 店[みせ]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は どの シャツを 買[か]いますか。',
      lines: [
        l(F, 'この 白[しろ]い シャツの 大[おお]きいのは ありますか。', 'Do you have this white shirt in a larger size?'),
        l(M, '白[しろ]は 小[ちい]さいのしか ないんです。青[あお]か 黄色[きいろ]なら 大[おお]きいのが ありますが。', 'In white we only have small ones. In blue or yellow we have large ones.', '白は小さいのしかないんです。あおか黄色なら、大きいのがありますが。'),
        l(F, 'じゃあ、青[あお]いのに します。', 'Then I’ll take the blue one.'),
      ],
      choices: [items({ name: 'tshirt', color: 'white' }), items({ name: 'tshirt', color: 'blue' }), items({ name: 'tshirt', color: 'yellow' }), items({ name: 'tshirt', color: 'red' })],
      answer: 1, why: 'No large white ones, so she picks blue.' },
    { id: 'floor-restaurant-top', level: 'N4',
      intro: 'デパートで 男[おとこ]の人[ひと]と 店[みせ]の人[ひと]が 話[はな]しています。レストランは 何階[なんがい]に ありますか。',
      lines: [
        l(M, 'すみません、レストランは 七階[ななかい]ですか。', 'Excuse me, are the restaurants on the seventh floor?'),
        l(F, '七階[ななかい]は 本屋[ほんや]です。レストランは いちばん 上[うえ]の 八階[はっかい]で ございます。', 'The seventh floor is the bookshop. The restaurants are on the top floor, the eighth.'),
      ],
      choices: [{ type: 'floor', floor: 7, floors: 8 }, { type: 'floor', floor: 8, floors: 8 }, { type: 'floor', floor: 6, floors: 8 }, { type: 'floor', floor: 1, floors: 8 }],
      answer: 1, why: 'The 7th floor is books; restaurants are on the top floor, the 8th.' },
  ]);

  add('hatsuwa', [
    { id: 'pass-salt', level: 'N5', scene: { setting: 'restaurant', left: 'man', right: 'woman', arrow: 'left' },
      intro: '塩[しお]を 取[と]って ほしいです。何[なん]と 言[い]いますか。',
      choices: [r('塩[しお]を 取[と]って ください。', 'Please pass the salt.'), r('塩[しお]を 取[と]りましょう。', 'Let’s take the salt.'), r('塩[しお]は ありません。', 'There’s no salt.')],
      answer: 0, why: '〜てください asks someone to do something.' },
    { id: 'thanks-meal', level: 'N5', scene: { setting: 'home', left: 'boy', right: 'mother', arrow: 'left' }, voices: { M: 'child' },
      intro: 'ご飯[はん]を 食[た]べ終[お]わりました。何[なん]と 言[い]いますか。',
      choices: [r('いただきます。', 'Let’s eat.'), r('ごちそうさまでした。', 'Thank you for the meal.'), r('おやすみなさい。', 'Good night.')],
      answer: 1, why: 'After eating you say ごちそうさまでした.' },
    { id: 'shop-try-on', level: 'N5', scene: { setting: 'clothes', left: 'woman', right: 'clerkMan', arrow: 'left' },
      intro: 'この 服[ふく]を 着[き]て みたいです。店[みせ]の 人[ひと]に 何[なん]と 言[い]いますか。',
      choices: [r('着[き]て みても いいですか。', 'May I try it on?'), r('着[き]て ください。', 'Please wear it.'), r('もう 着[き]ました。', 'I already wore it.')],
      answer: 0, why: '〜てみてもいいですか asks to try it on.' },
    { id: 'go-first', level: 'N4', scene: { setting: 'station', left: 'man2', right: 'grandma', arrow: 'left' },
      intro: 'エレベーターの 前[まえ]に おばあさんが います。先[さき]に 乗[の]って ほしいです。何[なん]と 言[い]いますか。',
      choices: [r('お先[さき]に 失礼[しつれい]します。', 'Excuse me for leaving first.'), r('どうぞ、お先[さき]に。', 'Please, after you.'), r('先[さき]に 乗[の]っても いいですか。', 'May I get on first?')],
      answer: 1, why: 'どうぞ、お先に lets the other person go first.' },
    { id: 'wrong-number', level: 'N4', scene: { setting: 'office', left: 'officeWoman', right: 'office', prop: 'phone', holder: 'left', arrow: 'left' }, replyBy: 'F',
      intro: '電話[でんわ]を かけましたが、違[ちが]う 人[ひと]が 出[で]ました。何[なん]と 言[い]いますか。',
      choices: [r('すみません、間違[まちが]えました。', 'Sorry, I have the wrong number.'), r('どちら様[さま]ですか。', 'Who is calling, please?'), r('少々[しょうしょう] お待[ま]ちください。', 'One moment, please.')],
      answer: 0, why: 'You called the wrong number, so apologise: 間違えました.' },
    { id: 'visit-sick', level: 'N4', scene: { setting: 'hospital', left: 'woman2', right: 'friendMan', arrow: 'left' }, replyBy: 'F',
      intro: '入院[にゅういん]して いる 友[とも]だちに 会[あ]いに 来[き]ました。帰[かえ]る とき、何[なん]と 言[い]いますか。',
      choices: [r('お大事[だいじ]に。', 'Take care of yourself.'), r('お疲[つか]れさまでした。', 'Thanks for your hard work.'), r('お邪魔[じゃま]します。', 'Excuse me for coming in.')],
      answer: 0, why: 'To someone who is ill you say お大事に.' },
  ]);

  add('sokuji', [
    { id: 'what-time-now', level: 'N5', lines: [l(M, 'すみません、今[いま] 何時[なんじ]ですか。', 'Excuse me, what time is it now?')], replyBy: 'F',
      choices: [r('三時[さんじ]ごろでした。', 'It was about three.'), r('三時半[さんじはん]です。', 'It’s half past three.'), r('三時間[さんじかん]です。', 'Three hours.')], answer: 1, why: '今何時 asks the time now.' },
    { id: 'how-get-here', level: 'N5', lines: [l(F, '学校[がっこう]まで 何[なに]で 来[き]ますか。', 'How do you get to school?')], replyBy: 'M',
      choices: [r('自転車[じてんしゃ]で 来[き]ます。', 'I come by bike.'), r('八時[はちじ]に 来[き]ます。', 'I come at eight.'), r('友[とも]だちと 来[き]ます。', 'I come with a friend.')], answer: 0, why: '何で asks by what means.' },
    { id: 'can-borrow-dict', level: 'N5', lines: [l(M, 'この 辞書[じしょ]、ちょっと 借[か]りても いいですか。', 'May I borrow this dictionary for a moment?')], replyBy: 'F',
      choices: [r('はい、借[か]りました。', 'Yes, I borrowed it.'), r('ええ、どうぞ。', 'Sure, go ahead.'), r('いいえ、辞書[じしょ]です。', 'No, it’s a dictionary.')], answer: 1, why: 'Grant permission: ええ、どうぞ.' },
    { id: 'long-time', level: 'N5', lines: [l(F, 'お久[ひさ]しぶりですね。お元気[げんき]でしたか。', 'Long time no see. Have you been well?')], replyBy: 'M',
      choices: [r('はい、おかげさまで。', 'Yes, thank you.'), r('はい、はじめまして。', 'Yes, nice to meet you.'), r('いいえ、どういたしまして。', 'No, you’re welcome.')], answer: 0, why: 'おかげさまで answers how you have been.' },
    { id: 'whose-bag', level: 'N5', lines: [l(M, 'これは だれの かばんですか。', 'Whose bag is this?')], replyBy: 'F',
      choices: [r('わたしのです。', 'It’s mine.'), r('かばんの 中[なか]です。', 'It’s inside the bag.'), r('新[あたら]しいです。', 'It’s new.')], answer: 0, why: 'だれの asks whose.' },
    { id: 'eat-already', level: 'N5', lines: [l(F, 'もう 昼[ひる]ご飯[はん]を 食[た]べましたか。', 'Have you had lunch yet?')], replyBy: 'M',
      choices: [r('いいえ、まだです。', 'No, not yet.'), r('はい、食[た]べません。', 'Yes, I won’t eat.'), r('昼[ひる]ご飯[はん]です。', 'It’s lunch.')], answer: 0, why: 'もう〜ましたか → まだです when you haven’t.' },
    { id: 'could-you-repeat', level: 'N4', lines: [l(M, 'すみません、もう 一度[いちど] 言[い]って いただけませんか。', 'Sorry, could you say that once more?')], replyBy: 'F',
      choices: [r('はい、言[い]って いただきます。', 'Yes, I’ll have you say it.'), r('はい、ゆっくり 言[い]いますね。', 'Sure, I’ll say it slowly.'), r('いいえ、言[い]いませんでした。', 'No, I didn’t say it.')], answer: 1, why: 'Agree and repeat it slowly.' },
    { id: 'smoke-here', level: 'N4', lines: [l(M, 'ここで たばこを 吸[す]っても いいですか。', 'May I smoke here?')], replyBy: 'F',
      choices: [r('すみません、ここは 禁煙[きんえん]なんです。', 'Sorry, this is non-smoking.'), r('はい、吸[す]いましょう。', 'Yes, let’s smoke.'), r('たばこを 吸[す]った ことが あります。', 'I have smoked before.')], answer: 0, why: 'Politely refuse: 禁煙なんです.' },
    { id: 'already-decided', level: 'N4', lines: [l(F, '旅行[りょこう]の 場所[ばしょ]、もう 決[き]めた？', 'Have you decided where to go on the trip yet?')], replyBy: 'M',
      choices: [r('うん、北海道[ほっかいどう]に したよ。', 'Yes, I went with Hokkaido.'), r('うん、旅行[りょこう]したよ。', 'Yes, I travelled.'), r('うん、決[き]めて ほしい。', 'Yes, I want you to decide.')], answer: 0, why: '〜にする: I decided on Hokkaido.' },
    { id: 'shall-carry', level: 'N4', lines: [l(M, '重[おも]そうですね。持[も]ちましょうか。', 'That looks heavy. Shall I carry it?')], replyBy: 'F',
      choices: [r('ええ、持[も]ちましょう。', 'Yes, let’s carry it.'), r('ありがとうございます。助[たす]かります。', 'Thank you, that’s a big help.'), r('重[おも]く ありませんでした。', 'It wasn’t heavy.')], answer: 1, why: 'Accept the offer with thanks: 助かります.' },
    { id: 'how-long-stay', level: 'N4', lines: [l(F, '日本[にほん]には どのぐらい いる 予定[よてい]ですか。', 'How long are you planning to stay in Japan?')], replyBy: 'M',
      choices: [r('二年[にねん]ぐらいです。', 'About two years.'), r('去年[きょねん] 来[き]ました。', 'I came last year.'), r('東京[とうきょう]に います。', 'I’m in Tokyo.')], answer: 0, why: 'どのぐらい asks how long.' },
    { id: 'congrats-exam', level: 'N4', lines: [l(M, '試験[しけん]に 合格[ごうかく]しました。', 'I passed the exam.')], replyBy: 'F',
      choices: [r('それは 残念[ざんねん]でしたね。', 'That’s a shame.'), r('おめでとうございます。', 'Congratulations!'), r('がんばって ください。', 'Good luck.')], answer: 1, why: 'Good news → おめでとうございます.' },
  ]);
})(typeof window !== 'undefined' ? window : globalThis);
