(function (global) {
  'use strict';

  // More N5 and N4 conversations (format: listening-data.js) — enough for
  // a fifth N5 and a fourth N4 mock test.
  const add = global.LISTENING_ADD;
  const items = (...list) => ({ type: 'items', items: list.map(x => (Array.isArray(x) ? x : [x, 1])) });
  const phrase = (ja, en) => ({ type: 'phrase', ja, en });
  const r = (ja, en, say) => (say ? { ja, en, say } : { ja, en });

  add('kadai', [
    {
      id: 'tulips', level: 'N5',
      intro: '花屋[はなや]で 女[おんな]の人[ひと]と 店[みせ]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は どの 花[はな]を 買[か]いますか。',
      lines: [
        { who: 'F', ja: 'すみません、赤[あか]い チューリップを ください。', en: 'Excuse me, some red tulips, please.' },
        { who: 'M', ja: 'すみません、赤[あか]いのは 今日[きょう]は もう ありません。白[しろ]いのと 黄色[きいろ]いのが ありますよ。', en: 'Sorry, the red ones have sold out today. We have white ones and yellow ones.' },
        { who: 'F', ja: 'じゃあ、黄色[きいろ]いのを ください。', en: 'Then the yellow ones, please.' },
      ],
      choices: [items({ name: 'tulip', color: 'red' }), items({ name: 'tulip', color: 'white' }), items({ name: 'tulip', color: 'yellow' }), items({ name: 'tulip', color: 'pink' })],
      answer: 2,
      why: 'The red ones are gone, so she buys the yellow ones (黄色いの).',
    },
    {
      id: 'stationery', level: 'N5',
      intro: '男[おとこ]の 学生[がくせい]と 女[おんな]の 学生[がくせい]が 話[はな]しています。男[おとこ]の 学生[がくせい]は 何[なに]を 買[か]いますか。',
      voices: { M: 'young', F: 'young' },
      lines: [
        { who: 'M', ja: '明日[あした]から 学校[がっこう]ですね。ノートと 鉛筆[えんぴつ]を 買[か]わなければ なりません。', en: 'School starts tomorrow. I need to buy notebooks and pencils.' },
        { who: 'F', ja: 'ノートは 先週[せんしゅう] 買[か]いましたよね。', en: 'You bought notebooks last week, didn’t you?' },
        { who: 'M', ja: 'あ、そうでした。じゃ、鉛筆[えんぴつ]と ペンを 買[か]います。', en: 'Oh, right. Then I’ll buy pencils and a pen.' },
      ],
      choices: [items('notebook', 'pencil'), items('pencil', 'pen'), items('notebook', 'pen'), items('notebook', 'pencil', 'pen')],
      answer: 1,
      why: 'He already bought notebooks last week, so pencils and a pen.',
    },
    {
      id: 'chores-first', level: 'N4',
      voices: { M: 'young' },
      intro: 'お母[かあ]さんと 男[おとこ]の子[こ]が 話[はな]しています。男[おとこ]の子[こ]は まず 何[なに]を しますか。',
      lines: [
        { who: 'F', ja: 'ねえ、手伝[てつだ]って。洗濯物[せんたくもの]を 干[ほ]して、それから お皿[さら]も 洗[あら]って ほしいの。', en: 'Hey, give me a hand. I’d like you to hang up the washing, and then wash the dishes.' },
        { who: 'M', ja: 'いいよ。洗濯[せんたく]から する？', en: 'OK. Shall I start with the washing?' },
        { who: 'F', ja: 'あ、ごみの 車[くるま]が もうすぐ 来[く]るから、先[さき]に ごみを 出[だ]して きて。', en: 'Oh, the rubbish truck is coming soon, so take the rubbish out first.' },
        { who: 'M', ja: 'わかった。', en: 'Got it.' },
      ],
      choices: [items('washer'), items('dishes'), items('trash'), items('broom')],
      answer: 2,
      why: 'The rubbish truck is coming, so 先にごみを出して — the rubbish goes out first.',
    },
    {
      id: 'hike-pack', level: 'N4',
      intro: '先生[せんせい]が 学生[がくせい]に 話[はな]しています。学生[がくせい]は 明日[あした] 何[なに]を 持[も]って 行[い]きますか。',
      lines: [
        { who: 'M', ja: '明日[あした]は 山[やま]に 登[のぼ]ります。お弁当[べんとう]は 学校[がっこう]で 用意[ようい]しますから、持[も]って 来[こ]なくても いいです。', en: 'Tomorrow we climb a mountain. The school is providing lunch, so you don’t need to bring any.' },
        { who: 'M', ja: '日[ひ]が 強[つよ]いので、帽子[ぼうし]を 忘[わす]れないで ください。それから、飲[の]み物[もの]も 持[も]って 来[き]て ください。', en: 'The sun will be strong, so don’t forget a hat. And please bring something to drink.' },
      ],
      choices: [items('hat', 'drink'), items('hat', 'bento'), items('drink', 'umbrella'), items('hat', 'drink', 'bento')],
      answer: 0,
      why: 'A hat and a drink. Lunch is provided by the school.',
    },
    {
      id: 'flower-where', level: 'N4',
      intro: '部屋[へや]で 男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は 花[はな]を どこに 置[お]きますか。',
      lines: [
        { who: 'M', ja: 'この 花[はな]、どこに 置[お]こうか。本棚[ほんだな]の 横[よこ]は どう？', en: 'Where shall I put these flowers? How about next to the bookshelf?' },
        { who: 'F', ja: 'そこは 暗[くら]いでしょう。花[はな]は 明[あか]るい ところが いいのよ。', en: 'It’s dark there. Flowers like a bright spot.' },
        { who: 'M', ja: 'じゃあ、窓[まど]の 前[まえ]に 置[お]くね。', en: 'Then I’ll put them in front of the window.' },
      ],
      choices: [{ type: 'room', at: 'shelf-left' }, { type: 'room', at: 'door' }, { type: 'room', at: 'shelf-right' }, { type: 'room', at: 'window' }],
      answer: 3,
      why: 'By the bookshelf is too dark; flowers like light, so in front of the window (窓の前).',
    },
    {
      id: 'route-library', level: 'N4',
      intro: '駅[えき]の 前[まえ]で 男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は どう 行[い]きますか。',
      lines: [
        { who: 'M', ja: 'すみません、図書館[としょかん]は どう 行[い]けば いいですか。', en: 'Excuse me, how do I get to the library?' },
        { who: 'F', ja: 'この 道[みち]を まっすぐ 行[い]って、一[ひと]つ目[め]の 角[かど]を 左[ひだり]に 曲[ま]がって ください。', en: 'Go straight along this road and turn left at the first corner.' },
        { who: 'F', ja: 'それから、また まっすぐ 行[い]くと、図書館[としょかん]が あります。', en: 'Then keep going straight, and the library is there.' },
      ],
      choices: [{ type: 'route', turns: ['up', 'right', 'up'] }, { type: 'route', turns: ['up', 'left', 'up'] }, { type: 'route', turns: ['up', 'up', 'left'] }, { type: 'route', turns: ['left', 'up'] }],
      answer: 1,
      why: 'Straight, left at the first corner (一つ目の角を左), then straight again.',
    },
    {
      id: 'cinema-back', level: 'N4',
      intro: '映画館[えいがかん]で 女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は どの 席[せき]に 座[すわ]りますか。',
      lines: [
        { who: 'F', ja: '後[うし]ろの 方[ほう]の 席[せき]が いいです。', en: 'I’d like a seat near the back.' },
        { who: 'M', ja: 'じゃあ、一番[いちばん] 後[うし]ろの Eの 列[れつ]ですね。真[ま]ん中[なか]と 端[はし]、どちらが いいですか。', en: 'Then the very back row, E. The middle or the end?', say: 'じゃあ、一番後ろのイーの列ですね。真ん中と端、どちらがいいですか。' },
        { who: 'F', ja: '端[はし]が いいです。左[ひだり]の 端[はし]に します。', en: 'The end, please. I’ll take the left end.' },
      ],
      choices: [{ type: 'seats', row: 'E', seat: 6 }, { type: 'seats', row: 'E', seat: 1 }, { type: 'seats', row: 'A', seat: 1 }, { type: 'seats', row: 'C', seat: 1 }],
      answer: 1,
      why: 'The back row (E), at the left end: seat 1.',
    },
    {
      id: 'alarm', level: 'N4',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は 目覚[めざ]まし時計[どけい]を 何時[なんじ]に しますか。',
      lines: [
        { who: 'M', ja: '明日[あした]の 新幹線[しんかんせん]は 七時[しちじ]だよね。', en: 'Tomorrow’s shinkansen is at seven, right?' },
        { who: 'F', ja: 'うん。駅[えき]まで 三十分[さんじゅっぷん] かかるから、六時半[ろくじはん]には 家[いえ]を 出[で]ないと。', en: 'Yes. It takes thirty minutes to the station, so we have to leave home by half past six.' },
        { who: 'M', ja: '準備[じゅんび]に 四十分[よんじゅっぷん]は かかるから、目覚[めざ]ましは 五時[ごじ] 五十分[ごじゅっぷん]に しよう。', en: 'Getting ready takes forty minutes, so I’ll set the alarm for ten to six.' },
        { who: 'F', ja: 'そうね。', en: 'Good idea.' },
      ],
      choices: [{ type: 'clock', h: 6, m: 30 }, { type: 'clock', h: 7, m: 0 }, { type: 'clock', h: 6, m: 10 }, { type: 'clock', h: 5, m: 50 }],
      answer: 3,
      why: 'Leave at 6:30, minus forty minutes to get ready: 五時五十分, 5:50.',
    },
  ]);

  add('point', [
    {
      id: 'snow-cloud', level: 'N5',
      intro: 'テレビで 天気[てんき]の 話[はなし]を しています。明日[あした]の 天気[てんき]は どうですか。',
      lines: [
        { who: 'F', ja: '明日[あした]は 朝[あさ]から 雪[ゆき]が 降[ふ]るでしょう。', en: 'Tomorrow it will snow from the morning.' },
        { who: 'F', ja: '午後[ごご]は 雪[ゆき]は 止[や]みますが、晴[は]れないで、一日中[いちにちじゅう] 曇[くも]りでしょう。', en: 'The snow will stop in the afternoon, but it won’t clear — it will stay cloudy all day.' },
      ],
      choices: [{ type: 'weather', am: 'snow', pm: 'sun' }, { type: 'weather', am: 'cloudy', pm: 'snow' }, { type: 'weather', am: 'snow', pm: 'cloudy' }, { type: 'weather', am: 'rain', pm: 'cloudy' }],
      answer: 2,
      why: 'Snow in the morning, then cloudy (曇り) in the afternoon — it won’t clear up.',
    },
    {
      id: 'why-moving', level: 'N4',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。男[おとこ]の人[ひと]は どうして 引[ひ]っ越[こ]しますか。',
      lines: [
        { who: 'F', ja: '引[ひ]っ越[こ]すんですか。今[いま]の 部屋[へや]は 会社[かいしゃ]から 遠[とお]いんですか。', en: 'You’re moving? Is your flat far from work?' },
        { who: 'M', ja: 'いいえ、会社[かいしゃ]には 近[ちか]いんです。部屋[へや]も 広[ひろ]いし、家賃[やちん]も 高[たか]く ありません。', en: 'No, it’s close to work. The room is big, and the rent isn’t high.' },
        { who: 'M', ja: 'でも、隣[となり]の 人[ひと]が 毎晩[まいばん] うるさくて、よく 眠[ねむ]れないんです。', en: 'But the neighbour is noisy every night, and I can’t sleep well.' },
      ],
      choices: [phrase('会社[かいしゃ]から 遠[とお]いから', 'Because it’s far from work'), phrase('部屋[へや]が 狭[せま]いから', 'Because the room is small'), phrase('家賃[やちん]が 高[たか]いから', 'Because the rent is high'), phrase('隣[となり]の 人[ひと]が うるさいから', 'Because the neighbour is noisy')],
      answer: 3,
      why: 'Near work, big, cheap — but the neighbour is noisy (隣の人がうるさくて) and he can’t sleep.',
    },
    {
      id: 'which-bag', level: 'N4',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は どの かばんを 持[も]って 行[い]きますか。',
      lines: [
        { who: 'M', ja: '旅行[りょこう]には その 大[おお]きい 黒[くろ]い かばんを 持[も]って 行[い]くの？', en: 'Are you taking that big black bag on the trip?' },
        { who: 'F', ja: 'ううん、大[おお]きいのは 重[おも]いから、小[ちい]さいのに する。', en: 'No, the big one is heavy, so I’ll take a small one.' },
        { who: 'M', ja: '黒[くろ]い 小[ちい]さいの？', en: 'The small black one?' },
        { who: 'F', ja: 'ううん、茶色[ちゃいろ]の 小[ちい]さいのよ。', en: 'No, the small brown one.' },
      ],
      choices: [items({ name: 'bag', color: 'black', big: true }), items({ name: 'bag', color: 'black', small: true }), items({ name: 'bag', color: 'brown', big: true }), items({ name: 'bag', color: 'brown', small: true })],
      answer: 3,
      why: 'Not the big one (too heavy) and not the black one: the small brown one (茶色の小さいの).',
    },
    {
      id: 'wallet-where', level: 'N4',
      intro: '女[おんな]の人[ひと]と 男[おとこ]の人[ひと]が 話[はな]しています。財布[さいふ]は どこに ありましたか。',
      lines: [
        { who: 'F', ja: '財布[さいふ]が ない。かばんの 中[なか]にも ないし…。', en: 'My wallet’s gone. It’s not in my bag either…' },
        { who: 'M', ja: '机[つくえ]の 上[うえ]は？', en: 'On the desk?' },
        { who: 'F', ja: '見[み]たけど、なかった。', en: 'I looked; it wasn’t there.' },
        { who: 'M', ja: 'あ、あれじゃない？ 棚[たな]の 上[うえ]に あるよ。', en: 'Oh, isn’t that it? It’s on the shelf.' },
      ],
      choices: [{ type: 'key', at: 'bag', thing: 'wallet' }, { type: 'key', at: 'desk', thing: 'wallet' }, { type: 'key', at: 'chair', thing: 'wallet' }, { type: 'key', at: 'shelf', thing: 'wallet' }],
      answer: 3,
      why: 'Not in the bag or on the desk — on the shelf (棚の上).',
    },
    {
      id: 'tomorrow-how', level: 'N4',
      intro: '男[おとこ]の人[ひと]と 女[おんな]の人[ひと]が 話[はな]しています。女[おんな]の人[ひと]は 明日[あした] 何[なに]で 会社[かいしゃ]へ 行[い]きますか。',
      lines: [
        { who: 'M', ja: 'いつも 自転車[じてんしゃ]で 来[き]て いますよね。', en: 'You always come by bike, don’t you?' },
        { who: 'F', ja: 'ええ。でも、明日[あした]は 雨[あめ]らしいので、バスに しようと 思[おも]って いるんです。', en: 'Yes. But apparently it’ll rain tomorrow, so I’m thinking of taking the bus.' },
        { who: 'M', ja: '雨[あめ]の 日[ひ]の バスは 込[こ]んで、時間[じかん]も かかりますよ。', en: 'Buses are crowded on rainy days, and slow too.' },
        { who: 'F', ja: 'そうですね。じゃ、少[すこ]し 歩[ある]きますが、電車[でんしゃ]で 来[き]ます。', en: 'True. Then I’ll come by train, even though it means walking a bit.' },
      ],
      choices: [items('bike'), items('bus'), items('train'), items('walk')],
      answer: 2,
      why: 'Not the bike (rain) or the bus (crowded and slow): the train.',
    },
    {
      id: 'dentist-day', level: 'N4',
      intro: '男[おとこ]の人[ひと]が 歯医者[はいしゃ]に 電話[でんわ]を しています。男[おとこ]の人[ひと]は 何曜日[なんようび]に 歯医者[はいしゃ]へ 行[い]きますか。',
      lines: [
        { who: 'M', ja: 'すみません、火曜日[かようび]に 予約[よやく]して いる 田中[たなか]ですが、その 日[ひ]は 仕事[しごと]で 行[い]けなく なりました。', en: 'Hello, this is Tanaka. I have an appointment on Tuesday, but I can’t come because of work.' },
        { who: 'F', ja: 'そうですか。では、水曜日[すいようび]か 木曜日[もくようび]は いかがですか。', en: 'I see. How about Wednesday or Thursday?' },
        { who: 'M', ja: '水曜日[すいようび]も 忙[いそが]しいので、木曜日[もくようび]で お願[ねが]いします。', en: 'Wednesday is busy too, so Thursday, please.' },
      ],
      choices: [{ type: 'week', days: [2] }, { type: 'week', days: [3] }, { type: 'week', days: [4] }, { type: 'week', days: [2, 4] }],
      answer: 2,
      why: 'Not Tuesday (work) or Wednesday (busy): Thursday, 木曜日.',
    },
  ]);

  add('hatsuwa', [
    { id: 'borrow-book', level: 'N5', scene: { setting: 'shop', left: 'student', right: 'clerk', prop: 'book', holder: 'left', arrow: 'left' }, voices: { M: 'young' },
      intro: '図書館[としょかん]で 本[ほん]を 借[か]りたいです。何[なん]と 言[い]いますか。',
      choices: [r('この 本[ほん]を 借[か]りても いいですか。', 'May I borrow this book?'), r('この 本[ほん]を 読[よ]みましたか。', 'Did you read this book?'), r('この 本[ほん]、どうぞ。', 'Here, this book is for you.')],
      answer: 0, why: '〜てもいいですか asks permission to borrow it.' },
    { id: 'ask-name', level: 'N5', scene: { setting: 'classroom', left: 'teacher', right: 'student', arrow: 'left' },
      intro: '新[あたら]しい 学生[がくせい]の 名前[なまえ]を 聞[き]きたいです。何[なん]と 言[い]いますか。',
      choices: [r('お元気[げんき]ですか。', 'How are you?'), r('お名前[なまえ]は 何[なん]ですか。', 'What is your name?'), r('おいくつですか。', 'How old are you?')],
      answer: 1, why: 'お名前は何ですか asks a name.' },
    { id: 'see-off', level: 'N5', scene: { setting: 'home', left: 'mother', right: 'boy', arrow: 'left' }, replyBy: 'F', voices: { M: 'child' },
      intro: '子[こ]どもが 学校[がっこう]へ 行[い]きます。お母[かあ]さんは 何[なん]と 言[い]いますか。',
      choices: [r('おかえりなさい。', 'Welcome home.'), r('ただいま。', 'I’m home.'), r('いってらっしゃい。', 'See you later (to someone leaving).')],
      answer: 2, why: 'To someone going out: いってらっしゃい.' },
    { id: 'tasty', level: 'N5', scene: { setting: 'kitchen', left: 'friendMan', right: 'friend', prop: 'curry', holder: 'right', propSize: 34, arrow: 'left' },
      intro: '友[とも]だちが 作[つく]った カレーを 食[た]べました。何[なん]と 言[い]いますか。',
      choices: [r('とても おいしいです。', 'It’s really delicious.'), r('いただきます。', 'Said before eating.'), r('おいしく ないですか。', 'Isn’t it good?')],
      answer: 0, why: 'Praise the food: とてもおいしいです.' },
    { id: 'hand-in', level: 'N5', scene: { setting: 'classroom', left: 'schoolgirl', right: 'teacher', prop: 'homework', holder: 'left', arrow: 'left' }, replyBy: 'F', voices: { F: 'young' },
      intro: '先生[せんせい]に 宿題[しゅくだい]を 出[だ]します。何[なん]と 言[い]いますか。',
      choices: [r('宿題[しゅくだい]は ありますか。', 'Is there homework?'), r('宿題[しゅくだい]を しましょう。', 'Let’s do the homework.'), r('先生[せんせい]、宿題[しゅくだい]です。お願[ねが]いします。', 'Here’s my homework, sir.')],
      answer: 2, why: 'Handing it in: 宿題です。お願いします.' },
    { id: 'wrong-dish', level: 'N4', scene: { setting: 'restaurant', left: 'woman', right: 'waiter', prop: 'ramen', arrow: 'left' }, replyBy: 'F',
      intro: 'レストランで、注文[ちゅうもん]と 違[ちが]う 料理[りょうり]が 来[き]ました。何[なん]と 言[い]いますか。',
      choices: [r('すみません、これ、頼[たの]んで いないんですが。', 'Excuse me, I didn’t order this.'), r('これを 頼[たの]みましょうか。', 'Shall we order this?'), r('これは おいしそうですね。', 'This looks tasty.')],
      answer: 0, why: '頼んでいないんですが politely says it isn’t what you ordered.' },
    { id: 'quiet-please', level: 'N4', scene: { setting: 'train', left: 'officeWoman', right: 'man2', arrow: 'left' }, replyBy: 'F',
      intro: '電車[でんしゃ]で 隣[となり]の 人[ひと]の 電話[でんわ]が うるさいです。何[なん]と 言[い]いますか。',
      choices: [r('静[しず]かですね。', 'It’s quiet, isn’t it?'), r('すみません、少[すこ]し 静[しず]かに して いただけませんか。', 'Excuse me, could you be a little quieter?'), r('うるさく しても いいですか。', 'May I make noise?')],
      answer: 1, why: 'A polite request: 静かにしていただけませんか.' },
    { id: 'hold-on', level: 'N4', scene: { setting: 'office', left: 'officeWoman', right: 'office', prop: 'phone', holder: 'left', propSize: 30, arrow: 'left' }, replyBy: 'F',
      intro: '電話[でんわ]で、相手[あいて]に 少[すこ]し 待[ま]って もらいたいです。何[なん]と 言[い]いますか。',
      choices: [r('お待[ま]たせしました。', 'Sorry to keep you waiting.'), r('待[ま]って いますよ。', 'I’m waiting.'), r('少々[しょうしょう] お待[ま]ちください。', 'One moment, please.')],
      answer: 2, why: '少々お待ちください asks the caller to wait. お待たせしました is said after.' },
    { id: 'lost-way', level: 'N4', scene: { setting: 'street', left: 'tourist', right: 'woman2', arrow: 'left' },
      intro: '道[みち]が わからなく なりました。何[なん]と 言[い]いますか。',
      choices: [r('すみません、駅[えき]は どちらでしょうか。', 'Excuse me, which way is the station?'), r('駅[えき]まで 案内[あんない]しましょうか。', 'Shall I show you to the station?'), r('駅[えき]は 近[ちか]いですよ。', 'The station is close.')],
      answer: 0, why: 'Asking the way: 駅はどちらでしょうか. 案内しましょうか is an offer.' },
    { id: 'leave-early', level: 'N4', scene: { setting: 'office', left: 'office', right: 'officeWoman', arrow: 'left' },
      intro: '熱[ねつ]が あるので、会社[かいしゃ]を 早[はや]く 帰[かえ]りたいです。何[なん]と 言[い]いますか。',
      choices: [r('早[はや]く 帰[かえ]って ください。', 'Please go home early.'), r('熱[ねつ]が ありますか。', 'Do you have a fever?'), r('すみません、熱[ねつ]が あるので、早[はや]く 帰[かえ]っても いいでしょうか。', 'Sorry, I have a fever — may I go home early?')],
      answer: 2, why: 'Asking permission politely: 帰ってもいいでしょうか.' },
  ]);

  add('sokuji', [
    { id: 'where-toilet', level: 'N5', lines: [{ who: 'F', ja: 'すみません、トイレは どこですか。', en: 'Excuse me, where is the toilet?' }], replyBy: 'M',
      choices: [r('あちらです。', 'Over there.'), r('はい、トイレです。', 'Yes, it’s the toilet.'), r('トイレに 行[い]きました。', 'I went to the toilet.')], answer: 0, why: 'どこですか asks where.' },
    { id: 'how-much', level: 'N5', lines: [{ who: 'M', ja: 'この りんごは いくらですか。', en: 'How much are these apples?' }], replyBy: 'F',
      choices: [r('三[みっ]つです。', 'Three.'), r('一[ひと]つ 百円[ひゃくえん]です。', 'A hundred yen each.'), r('赤[あか]いです。', 'They’re red.')], answer: 1, why: 'いくら asks the price.' },
    { id: 'whos-that', level: 'N5', lines: [{ who: 'F', ja: 'あの 人[ひと]は だれですか。', en: 'Who is that person?' }], replyBy: 'M',
      choices: [r('先生[せんせい]です。', 'It’s our teacher.'), r('あそこです。', 'Over there.'), r('元気[げんき]です。', 'Fine.')], answer: 0, why: 'だれ asks who.' },
    { id: 'what-sport', level: 'N5', lines: [{ who: 'M', ja: 'どんな スポーツが 好[す]きですか。', en: 'What kind of sports do you like?' }], replyBy: 'F',
      choices: [r('はい、好[す]きです。', 'Yes, I like them.'), r('毎日[まいにち] します。', 'I do it every day.'), r('テニスが 好[す]きです。', 'I like tennis.')], answer: 2, why: 'どんな asks which kind.' },
    { id: 'go-together', level: 'N5', lines: [{ who: 'F', ja: '一緒[いっしょ]に 帰[かえ]りませんか。', en: 'Shall we go home together?' }], replyBy: 'M',
      choices: [r('ええ、帰[かえ]りましょう。', 'Sure, let’s go.'), r('はい、帰[かえ]りませんでした。', 'Yes, I didn’t go home.'), r('一緒[いっしょ]です。', 'It’s together.')], answer: 0, why: 'Accept the invitation with 〜ましょう.' },
    { id: 'which-one', level: 'N5', lines: [{ who: 'M', ja: 'どちらが 田中[たなか]さんの かさですか。', en: 'Which one is your umbrella, Tanaka-san?' }], replyBy: 'F',
      choices: [r('はい、そうです。', 'Yes, that’s right.'), r('その 青[あお]いのです。', 'The blue one.'), r('雨[あめ]です。', 'It’s raining.')], answer: 1, why: 'どちら asks which: その青いのです.' },
    { id: 'already-left', level: 'N4', lines: [{ who: 'M', ja: '山田[やまだ]さんは もう 帰[かえ]りましたか。', en: 'Has Yamada-san gone home already?' }], replyBy: 'F',
      choices: [r('ええ、さっき 帰[かえ]りましたよ。', 'Yes, he left a moment ago.'), r('ええ、これから 帰[かえ]りましたよ。', '(mixed-up tense)'), r('いいえ、もう 帰[かえ]りました。', 'No, he’s gone already.')], answer: 0, why: 'もう〜ましたか → ええ、さっき帰りました.' },
    { id: 'need-help', level: 'N4', lines: [{ who: 'F', ja: '何[なに]か 手伝[てつだ]う ことは ありますか。', en: 'Is there anything I can help with?' }], replyBy: 'M',
      choices: [r('はい、手伝[てつだ]いました。', 'Yes, I helped.'), r('じゃあ、この 箱[はこ]を 運[はこ]んで もらえますか。', 'Then could you carry this box?'), r('手伝[てつだ]って あげます。', 'I’ll help you.')], answer: 1, why: 'Accept an offer by asking for something specific.' },
    { id: 'shall-open', level: 'N4', lines: [{ who: 'M', ja: '暑[あつ]いですね。窓[まど]を 開[あ]けましょうか。', en: 'It’s hot, isn’t it? Shall I open the window?' }], replyBy: 'F',
      choices: [r('ええ、お願[ねが]いします。', 'Yes, please.'), r('ええ、開[あ]いて います。', 'Yes, it’s open.'), r('いいえ、暑[あつ]く ありませんでした。', 'No, it wasn’t hot.')], answer: 0, why: 'Accept the offer: お願いします.' },
    { id: 'what-hobby', level: 'N4', lines: [{ who: 'F', ja: '休[やす]みの 日[ひ]は 何[なに]を して いるんですか。', en: 'What do you do on your days off?' }], replyBy: 'M',
      choices: [r('日曜日[にちようび]です。', 'It’s Sunday.'), r('たいてい 釣[つ]りに 行[い]って います。', 'I usually go fishing.'), r('休[やす]んで ください。', 'Please rest.')], answer: 1, why: 'Tell what you usually do.' },
    { id: 'tired', level: 'N4', lines: [{ who: 'M', ja: '疲[つか]れた 顔[かお]を して いますね。', en: 'You look tired.' }], replyBy: 'F',
      choices: [r('昨日[きのう] あまり 寝[ね]られなかったんです。', 'I couldn’t sleep much last night.'), r('ええ、疲[つか]れて ください。', '(not a real reply)'), r('顔[かお]を 洗[あら]いましょう。', 'Let’s wash our faces.')], answer: 0, why: 'Explain why with 〜んです.' },
    { id: 'sounds-fun', level: 'N4', lines: [{ who: 'F', ja: '来週[らいしゅう]、友[とも]だちと 沖縄[おきなわ]へ 行[い]くんです。', en: 'I’m going to Okinawa with friends next week.' }], replyBy: 'M',
      choices: [r('沖縄[おきなわ]に 住[す]んで います。', 'I live in Okinawa.'), r('へえ、いいですね。楽[たの]しんで きて ください。', 'Oh, nice! Have fun.'), r('沖縄[おきなわ]へ 行[い]きましたか。', 'Did you go to Okinawa?')], answer: 1, why: 'React to news: いいですね、楽しんできてください.' },
    { id: 'lend-pen', level: 'N4', lines: [{ who: 'M', ja: 'ペンを 忘[わす]れて しまいました。', en: 'I’ve forgotten my pen.' }], replyBy: 'F',
      choices: [r('じゃあ、これを 使[つか]って ください。', 'Then use this one.'), r('ペンを 忘[わす]れましょう。', 'Let’s forget our pens.'), r('ペンは 高[たか]いですね。', 'Pens are expensive.')], answer: 0, why: 'Offer yours: これを使ってください.' },
    { id: 'how-was-test', level: 'N4', lines: [{ who: 'F', ja: '昨日[きのう]の テスト、どうだった？', en: 'How was yesterday’s test?' }], replyBy: 'M', voices: { M: 'young', F: 'young' },
      choices: [r('明日[あした]だよ。', 'It’s tomorrow.'), r('うん、テストだった。', 'Yeah, it was a test.'), r('思[おも]ったより 簡単[かんたん]だったよ。', 'Easier than I expected.')], answer: 2, why: 'どうだった asks how it went.' },
  ]);
})(typeof window !== 'undefined' ? window : globalThis);
