(function (global) {
  'use strict';

  // More memes for memes.html: a big batch of short ones (one to three
  // lines — a pun, a slang word, a "so true" observation) plus some longer
  // stories. Same format as memes-data.js, which must load first; `size`
  // ('short' | 'long') decides which tab an item is listed under.
  //
  // Words and grammar not already in the shared tables go in
  // MEME_GLOSSARY_2 / MEME_GRAMMAR_2 and are merged in the same way.
  // test_memes.js checks everything.

  global.MEME_GRAMMAR_2 = {
    'zo': { level: 'N4', title: 'ぞ — emphatic ending (rough)', pattern: 'Sentence + ぞ', note: 'A strong, rough "I\'m telling you!", mostly used by men: 行くぞ！ "let\'s go!", あるぞ "there it is!". Softer: よ.' },
    'daze': { level: 'N3', title: 'だぜ — cocky ending', pattern: 'Noun / sentence + だぜ', note: 'だ + ぜ: a swaggering, boyish "you bet!". Sounds like an anime hero; few adults use it seriously.' },
    'ryakugo': { level: 'N4', title: '略語 — chopped-down words', pattern: 'First kana of each part, glued together', note: 'Japanese shortens long words and phrases by keeping the start of each part: スマートフォン → スマホ, あけましておめでとう → あけおめ, 了解 → りょ.' },
    'dare-mo-neg': { level: 'N5', title: 'だれも + negative — nobody', pattern: 'だれも + negative verb', note: 'だれも知りません "nobody knows". Likewise なにも (nothing), どこにも (nowhere).' },
  };

  global.MEME_GLOSSARY_2 = {
    // Short ones, N5
    'アルミ缶': ['あるみかん', 'aluminium can', 'noun'],
    'ミカン': ['みかん', 'mikan, mandarin orange', 'noun'],
    'イルカ': ['いるか', 'dolphin', 'noun'],
    'ゾウ': ['ぞう', 'elephant', 'noun'],
    'ぞう': ['ぞう', '(pun) ぞ stretched out — "I tell ya!", sounding like ゾウ (elephant)', 'particle (pun)'],
    'じゃ(old)': ['じゃ', '(old-fashioned, old man\'s speech) = だ: is', 'copula'],
    'すもも': ['すもも', 'Japanese plum', 'noun'],
    'もも': ['もも', 'peach (桃)', 'noun'],
    'うち(among)': ['うち', 'among, (one) of', 'noun'],
    'も(kana)': ['も', 'the kana も', 'kana'],
    '生麦': ['なまむぎ', 'raw wheat', 'noun'],
    '生米': ['なまごめ', 'raw (uncooked) rice', 'noun'],
    '生卵': ['なまたまご', 'raw egg', 'noun'],
    '三回': ['さんかい', 'three times', 'noun'],
    '好きー': ['すきー', '好き ("like") with the き stretched — to match スキー', 'な-adjective (pun)'],
    'あけおめ': ['あけおめ', 'HNY! — short for あけましておめでとう', 'slang'],
    'ことよろ': ['ことよろ', '"be good to me this year!" — short for 今年もよろしく', 'slang'],
    'あけまして': ['あけまして', '(the year) having opened — in あけましておめでとう, Happy New Year', 'expression'],
    'スマートフォン': ['すまーとふぉん', 'smartphone', 'noun'],
    'パソコン': ['ぱそこん', 'PC, computer (short for パーソナルコンピューター)', 'noun'],
    'パーソナルコンピューター': ['ぱーそなるこんぴゅーたー', 'personal computer', 'noun'],
    'ゲット': ['げっと', 'getting, catching (from English "get")', 'noun'],
    'アニメ': ['あにめ', 'anime, animation', 'noun'],
    'サトシ': ['さとし', 'Satoshi — Ash Ketchum\'s Japanese name', 'name'],
    'トトロ': ['ととろ', 'Totoro, the big furry forest spirit', 'name'],
    'メイちゃん': ['めいちゃん', 'Mei, the little girl in となりのトトロ', 'name'],
    'トロール': ['とろーる', 'troll', 'noun'],
    'キティちゃん': ['きてぃちゃん', 'Hello Kitty', 'name'],
    'かなしい': ['かなしい', 'sad (悲しい)', 'い-adjective'],
    'ワンワン': ['わんわん', 'woof woof', 'onomatopoeia'],
    'ニャー': ['にゃー', 'meow', 'onomatopoeia'],
    'ブタ': ['ぶた', 'pig', 'noun'],
    'ブーブー': ['ぶーぶー', 'oink oink', 'onomatopoeia'],
    'おそい': ['おそい', 'slow; late (遅い)', 'い-adjective'],

    // Short ones, N4
    '内容': ['ないよう', 'content(s)', 'noun'],
    '客': ['きゃく', 'guest, customer', 'noun'],
    '柿': ['かき', 'persimmon', 'noun'],
    '食う': ['くう', 'to eat (rough, masculine)', 'う-verb'],
    'からまる': ['からまる', 'to get tangled', 'う-verb'],
    'バス': ['ばす', 'bus', 'noun'],
    'ガス': ['がす', 'gas', 'noun'],
    'バスバクバク': ['ばすばくばく', '(a tongue-twisted mess)', 'nonsense'],
    'マジ': ['まじ', '(slang) for real, seriously', 'な-adjective'],
    'ウケる': ['うける', '(slang) to be hilarious, to go down well', 'ichidan verb'],
    '了解': ['りょうかい', 'roger, understood, got it', 'noun'],
    'りょ': ['りょ', '"k" — 了解 chopped down', 'slang'],
    'り': ['り', '"k" — りょ chopped down even further', 'slang'],
    'ググる': ['ぐぐる', 'to google', 'う-verb'],
    'グーグル': ['ぐーぐる', 'Google', 'name'],
    '動詞': ['どうし', 'verb', 'noun'],
    'アンパンマン': ['あんぱんまん', 'Anpanman, the bean-bun superhero', 'name'],
    'お食べ': ['おたべ', '(gentle, old-fashioned) eat up — お + verb stem', 'verb (gentle command)'],
    'ジャムおじさん': ['じゃむおじさん', 'Uncle Jam, the baker who makes Anpanman\'s heads', 'name'],
    '閉まる': ['しまる', '(a door) to close', 'う-verb'],
    '三秒': ['さんびょう', 'three seconds', 'noun'],
    'くしゃみ': ['くしゃみ', 'sneeze', 'noun'],
    'うわさ': ['うわさ', 'rumour, gossip', 'noun'],
    '消しゴム': ['けしごむ', 'eraser, rubber', 'noun'],
    '校長': ['こうちょう', 'school principal, head teacher', 'noun'],
    '絶好調': ['ぜっこうちょう', 'in top form, on a roll', 'noun'],
    'うれしそう': ['うれしそう', 'looking happy', 'な-adjective'],
    '試験': ['しけん', 'exam', 'noun'],
    'カツ丼': ['かつどん', 'katsudon — a pork cutlet on rice', 'noun'],
    'カツ': ['かつ', 'cutlet (from "cutlet")', 'noun'],
    'おじぎ': ['おじぎ', 'bow (お辞儀)', 'noun'],

    // Short ones, N3
    'コーディネート': ['こーでぃねーと', 'coordinating an outfit', 'noun'],
    'こーでねーと': ['こーでねーと', 'rough, slurred こうでないと: "it\'s gotta be like this"', 'expression (casual)'],
    '乱暴': ['らんぼう', 'rough, violent', 'な-adjective'],
    'ワロタ': ['わろた', '(net slang) lol, I laughed — from 笑った', 'internet slang'],
    'スラング': ['すらんぐ', 'slang', 'noun'],
    'orz': ['おーあーるぜっと', 'a stick figure on its hands and knees: utter despair', 'emoticon'],
    'o': ['おー', 'the letter o', 'letter'],
    'r': ['あーる', 'the letter r', 'letter'],
    'z': ['ぜっと', 'the letter z', 'letter'],
    '腕': ['うで', 'arm', 'noun'],
    '天空の城ラピュタ': ['てんくうのしろらぴゅた', 'Castle in the Sky, a 1986 Ghibli film', 'name'],
    '放送する': ['ほうそうする', 'to broadcast', 'する-verb'],
    'バルス': ['ばるす', '"Balse!" — the spell that destroys the castle in ラピュタ', 'name'],
    '書き込む': ['かきこむ', 'to post (online), to write in', 'う-verb'],
    'サーバー': ['さーばー', 'server', 'noun'],
    '日曜': ['にちよう', 'Sunday', 'noun'],
    'サザエさん': ['さざえさん', 'Sazae-san, a family cartoon on every Sunday since 1969', 'name'],
    '憂鬱': ['ゆううつ', 'gloomy, depressed', 'な-adjective'],
    '症候群': ['しょうこうぐん', 'syndrome', 'noun'],
    '神': ['かみ', 'god; (net slang) amazing, god-tier', 'noun'],
    '店員': ['てんいん', 'shop clerk, staff', 'noun'],
    '対応': ['たいおう', 'service, way of dealing with people', 'noun'],
    '神ゲー': ['かみげー', '(slang) god-tier game', 'noun'],
    'クソゲー': ['くそげー', '(slang) crap game', 'noun'],
    'ガチ': ['がち', '(slang) for real, seriously, hardcore', 'adverb'],
    '勢': ['ぜい', 'crowd, group (〜勢)', 'suffix'],
    '趣味': ['しゅみ', 'hobby', 'noun'],
    '食べ放題': ['たべほうだい', 'all-you-can-eat', 'noun'],
    '元': ['もと', 'cost, original outlay (元を取る: get your money\'s worth)', 'noun'],
    '二度と': ['にどと', '(with negative) never again', 'adverb'],
    '京都': ['きょうと', 'Kyoto', 'name'],
    'ぶぶ漬け': ['ぶぶづけ', '(Kyoto) rice with tea poured over it', 'noun'],
    'どす': ['どす', '(Kyoto dialect) = です', 'copula'],
    'そろそろ': ['そろそろ', 'soon, it\'s about time', 'adverb'],
    'バーン': ['ばーん', 'bang!', 'onomatopoeia'],
    '撃つ': ['うつ', 'to shoot', 'う-verb'],
    '番組': ['ばんぐみ', 'TV programme, show', 'noun'],
    'マンホール': ['まんほーる', 'manhole', 'noun'],
    'キモかわいい': ['きもかわいい', 'creepy-cute', 'い-adjective'],
    'ブサかわいい': ['ぶさかわいい', 'ugly-cute', 'い-adjective'],
    'ぼっち': ['ぼっち', '(slang) loner, someone on their own', 'noun'],
    '一人ぼっち': ['ひとりぼっち', 'all alone', 'noun'],
    '飯': ['めし', 'meal, food (rough)', 'noun'],
    '楽しむ': ['たのしむ', 'to enjoy', 'う-verb'],
    'ソロ活': ['そろかつ', 'doing things solo, on purpose and happily', 'noun'],
    '少女': ['しょうじょ', 'girl; (少女マンガ) manga for girls', 'noun'],
    '追い詰める': ['おいつめる', 'to corner, to drive into a corner', 'ichidan verb'],
    '炭': ['すみ', 'charcoal', 'noun'],
    '芸能界': ['げいのうかい', 'show business, the entertainment world', 'noun'],
    'あいさつ': ['あいさつ', 'greeting (あいさつする: to greet)', 'noun'],

    // Long ones
    'しりとり': ['しりとり', 'shiritori — the word-chain game', 'noun'],
    'ん(kana)': ['ん', 'the kana ん', 'kana'],
    '負け': ['まけ', 'loss, defeat (〜の負け: … loses)', 'noun'],
    'りんご': ['りんご', 'apple', 'noun'],
    'ゴリラ': ['ごりら', 'gorilla', 'noun'],
    'ラッパ': ['らっぱ', 'trumpet, bugle', 'noun'],
    '三回目': ['さんかいめ', 'the third time', 'noun'],
    'みかん': ['みかん', 'mikan, mandarin orange', 'noun'],
    'だって': ['だって', 'but, because (childish excuse)', 'conjunction'],
    'もん': ['もん', '(childish, at the end) because…!', 'particle'],
    'アイス': ['あいす', 'ice cream', 'noun'],
    '早口': ['はやくち', 'fast talking', 'noun'],
    'あたためる': ['あたためる', 'to warm up, to heat up', 'ichidan verb'],
    'お箸': ['おはし', 'chopsticks', 'noun'],
    '袋': ['ふくろ', 'bag', 'noun'],
    '桃太郎': ['ももたろう', 'Momotarō, the Peach Boy of folk tales', 'name'],
    '鬼': ['おに', 'ogre, demon', 'noun'],
    'たいじ': ['たいじ', 'defeating, wiping out (退治)', 'noun'],
    'きびだんご': ['きびだんご', 'millet dumpling', 'noun'],
    'サル': ['さる', 'monkey', 'noun'],
    'キジ': ['きじ', 'pheasant', 'noun'],
    '鬼が島': ['おにがしま', 'Ogre Island', 'name'],
    '居間': ['いま', 'living room', 'noun'],
    'こたつ': ['こたつ', 'kotatsu — a low heated table with a quilt over it', 'noun'],
    'ヒーター': ['ひーたー', 'heater', 'noun'],
    'ついでに': ['ついでに', 'while you\'re at it', 'adverb'],
    'わな': ['わな', 'trap', 'noun'],
    '鶴': ['つる', 'crane (the bird)', 'noun'],
    '娘': ['むすめ', 'young woman; daughter', 'noun'],
    '機': ['はた', 'loom', 'noun'],
    '織る': ['おる', 'to weave', 'う-verb'],
    'のぞく': ['のぞく', 'to peek', 'う-verb'],
    'しかたない': ['しかたない', 'it can\'t be helped', 'expression'],
    'ボス': ['ぼす', 'boss', 'noun'],
    '戦': ['せん', 'battle, fight (〜戦)', 'suffix'],
    '東': ['ひがし', 'east', 'noun'],
    '西': ['にし', 'west', 'noun'],
    'いろいろ(na)': ['いろいろ', 'various, all kinds of', 'な-adjective'],
    'エスカレーター': ['えすかれーたー', 'escalator', 'noun'],
    'マクドナルド': ['まくどなるど', 'McDonald\'s', 'name'],
    'マック': ['まっく', 'McDonald\'s (in Tokyo)', 'name'],
    'マクド': ['まくど', 'McDonald\'s (in Osaka)', 'name'],
    'アホ': ['あほ', 'fool, idiot (light in Kansai)', 'noun'],
    'バカ': ['ばか', 'fool, idiot (light in Kantō)', 'noun'],
    'お餅': ['おもち', 'mochi, rice cake', 'noun'],
    '四角': ['しかく', 'square', 'noun'],
    '丸': ['まる', 'circle, round', 'noun'],
    'どっち': ['どっち', 'which (of two)', 'pronoun'],
    'けんか': ['けんか', 'quarrel, fight', 'noun'],
    'ライトノベル': ['らいとのべる', 'light novel', 'noun'],
    '異世界': ['いせかい', 'another world, a fantasy world', 'noun'],
    '転生': ['てんせい', 'reincarnation', 'noun'],
    '大人気': ['だいにんき', 'hugely popular', 'noun'],
    '普通': ['ふつう', 'ordinary, normal', 'noun'],
    '高校生': ['こうこうせい', 'high-school student', 'noun'],
    'はねる': ['はねる', 'to hit, to run over (with a vehicle)', 'ichidan verb'],
    '剣': ['けん', 'sword', 'noun'],
    '魔法': ['まほう', 'magic', 'noun'],
    'なぜか': ['なぜか', 'for some reason', 'adverb'],
    '最強': ['さいきょう', 'the strongest', 'noun'],
    'あまりに': ['あまりに', 'so (much), too', 'adverb'],
    'トラックさん': ['とらっくさん', '"Mr. Truck" — the truck that sends heroes to other worlds', 'name'],
    'タイトル': ['たいとる', 'title', 'noun'],
    'スライム': ['すらいむ', 'slime (the monster)', 'noun'],
    '件': ['けん', 'matter, case; (in titles) "the one where…"', 'noun'],
    '感じ': ['かんじ', 'feeling, sort of thing', 'noun'],
    '辞める': ['やめる', 'to quit (a job)', 'ichidan verb'],
    'そこで': ['そこで', 'so, at that point', 'conjunction'],
    '代行': ['だいこう', 'acting on someone\'s behalf, proxy', 'noun'],
    '本人': ['ほんにん', 'the person in question, oneself', 'noun'],
    '代わり': ['かわり', 'substitute (〜の代わりに: instead of, on behalf of)', 'noun'],
    '伝える': ['つたえる', 'to tell, to pass on', 'ichidan verb'],
    'サービス': ['さーびす', 'service', 'noun'],
    '代理': ['だいり', 'proxy, representative', 'noun'],
    '者': ['もの', 'person (humble)', 'noun'],
    '検索': ['けんさく', 'search (online)', 'noun'],
    '伝わる': ['つたわる', 'to be passed down', 'う-verb'],
    '知恵': ['ちえ', 'wisdom', 'noun'],
    '名人': ['めいじん', 'expert, master', 'noun'],
    '現代': ['げんだい', 'modern times, today', 'noun'],
    '版': ['ばん', 'version, edition', 'suffix'],
    'プログラマー': ['ぷろぐらまー', 'programmer', 'noun'],
    'バグ': ['ばぐ', 'bug', 'noun'],
    'だろう': ['だろう', 'probably, I suppose (plain でしょう)', 'auxiliary'],
    '小判': ['こばん', 'koban — an old oval gold coin', 'noun'],
    '価値': ['かち', 'value, worth', 'noun'],
    '無駄': ['むだ', 'waste, pointless', 'な-adjective'],
    '段ボール': ['だんぼーる', 'cardboard', 'noun'],
    '団子': ['だんご', 'dango, dumpling', 'noun'],
    '実際': ['じっさい', 'actually, in practice', 'noun'],
    '役': ['やく', 'use, role (役に立つ: to be useful)', 'noun'],
    'お花見': ['おはなみ', 'cherry-blossom viewing (party)', 'noun'],
    'まさに': ['まさに', 'exactly, precisely', 'adverb'],
    '筆者': ['ひっしゃ', 'the writer, the author', 'noun'],
    '鳴く': ['なく', '(an animal) to make its sound — bark, meow, sing', 'う-verb'],
    'ひどい': ['ひどい', 'terrible, awful', 'い-adjective'],
    '世界': ['せかい', 'world', 'noun'],
    '本日': ['ほんじつ', 'today (formal)', 'noun'],
    'ことわざ': ['ことわざ', 'proverb, saying', 'noun'],
  };

  const SHORT = [
    // ── N5 ──────────────────────────────────────────────────────────────────
    {
      id: 'meme-s5-arumikan', level: 'n5', size: 'short', kind: 'dajare', emoji: '🥫🍊',
      title: 'アルミ缶[かん]の上[うえ]にあるミカン', titleEn: 'A Mikan on a Can',
      punch: 'アルミ缶 (arumi-kan, aluminium can) + ある (there is) + ミカン (mikan, mandarin): arumikan no ue ni aru mikan. Probably Japan\'s second most famous おやじギャグ, right after 布団が吹っ飛んだ.',
      sentences: [
        { jp: '「 アルミ缶[かん] の 上[うえ] に ある ミカン 。 」', en: '"A mikan sitting on an aluminium can."',
          grammar: ['ni-aru:上にある', 'relative-clause:上にあるミカン'] },
        { jp: '「 アルミかん>アルミ缶 」 と 「 ある ミカン 」 、 同[おな]じ 音[おと] です 。', en: '"Arumi-kan" and "aru mikan" — the same sound.',
          grammar: ['to-and:アルミかん」と「あるミカン'] },
      ],
    },
    {
      id: 'meme-s5-iruka', level: 'n5', size: 'short', kind: 'dajare', emoji: '🐬',
      title: 'イルカはいるか？', titleEn: 'Is There a Dolphin?',
      punch: 'イルカ (iruka) is a dolphin, and いるか？ (iru ka) asks "is it there?". A favourite with small kids — and a neat reminder that か on the end turns a sentence into a question.',
      sentences: [
        { jp: '「 イルカ は いる か ？ 」', en: '"Is there a dolphin (iruka)?"',
          grammar: ['wa-topic:イルカは', 'ka-question:いるか'] },
        { jp: '「 はい 、 イルカ は いる よ 。 」', en: '"Yes, there\'s a dolphin."',
          grammar: ['yo:いるよ'] },
      ],
    },
    {
      id: 'meme-s5-zou', level: 'n5', size: 'short', kind: 'dajare', emoji: '🐘',
      title: 'ゾウがいるぞう', titleEn: 'There\'s an Elephant, I Tell Ya',
      punch: 'ゾウ (zou) is an elephant, and ぞ is a rough, emphatic sentence ending ("I\'m telling you!"). Stretch ぞ into ぞう and the elephant appears. Japanese dads stretch every ぞ like this.',
      sentences: [
        { jp: '「 あ 、 ゾウ が いる ぞう ！ 」', en: '"Oh, there\'s an elephant, I tell ya!"',
          grammar: ['ga-subject:ゾウが', 'zo:いるぞう'] },
      ],
    },
    {
      id: 'meme-s5-dareja', level: 'n5', size: 'short', kind: 'dajare', emoji: '🧓',
      title: 'ダジャレを言[い]うのはだれじゃ', titleEn: 'Who\'s Telling Puns?',
      punch: 'だれじゃ ("who is it?") is how an old man talks in Japanese stories — じゃ is old-fashioned for だ. Say it fast: dare ja → dajare. A pun about puns.',
      sentences: [
        { jp: '「 ダジャレ を 言[い]う の は だれ>誰 じゃ>じゃ(old) ？ 」', en: '"Who is it that\'s telling puns?"',
          grammar: ['no-wa:言うのは', 'question-words:だれじゃ'] },
      ],
    },
    {
      id: 'meme-s5-suki', level: 'n5', size: 'short', kind: 'dajare', emoji: '⛷️',
      title: 'スキーが好[す]きー', titleEn: 'I Lo-o-ove Skiing',
      punch: 'スキー (sukii, skiing) and 好き (suki, like) — stretch the き and they match. Low effort, high groan: a perfect おやじギャグ.',
      sentences: [
        { jp: '「 スキー が 好[す]きー ！ 」', en: '"I lo-o-ove skiing (sukii)!"',
          grammar: ['ga-suki:スキーが好きー'] },
        { jp: '冬[ふゆ] に なる と 、 お父[とう]さん は 毎年[まいとし] これ を 言[い]います>言う 。', en: 'Every winter, Dad says this.',
          grammar: ['to-conditional:なると', 'wo-object:これを言います'] },
      ],
    },
    {
      id: 'meme-s5-sumomo', level: 'n5', size: 'short', kind: 'twister', emoji: '🍑',
      title: 'すもももももももものうち', titleEn: 'Plums and Peaches',
      punch: 'A tongue twister (早口言葉) and a particle drill in one: すもも も もも も もも の うち — "plums (sumomo) too, peaches (momo) too, are kinds of peach". Eight も in a row, and only the spaces in your head tell the particle も from the word もも.',
      sentences: [
        { jp: '「 すもも も もも も もも の うち>うち(among) 」', en: '"Plums and peaches are both kinds of peach."',
          grammar: ['mo-also:すももも', 'no-possessive:もものうち'] },
        { jp: '「 も>も(kana) 」 が 八[やっ]つ ！ 何回[なんかい] 言[い]えます>言う か 。', en: 'Eight も in a row! How many times can you say it?',
          grammar: ['potential:言えます', 'ka-question:言えますか'] },
      ],
    },
    {
      id: 'meme-s5-namamugi', level: 'n5', size: 'short', kind: 'twister', emoji: '🌾🍚🥚',
      title: '生麦[なまむぎ]生米[なまごめ]生卵[なまたまご]', titleEn: 'Raw Wheat, Raw Rice, Raw Egg',
      punch: 'The classic Japanese tongue twister: namamugi namagome namatamago. 生 (nama) means raw — the same nama as in 生ビール (draft beer). Most native speakers trip by the third round.',
      sentences: [
        { jp: '「 生麦[なまむぎ] 、 生米[なまごめ] 、 生卵[なまたまご] 」', en: '"Raw wheat, raw rice, raw eggs."',
          grammar: ['plain-form:生卵'] },
        { jp: '三回[さんかい] 、 早[はや]く 言[い]って>言う ください 。', en: 'Say it three times, fast.',
          grammar: ['te-kudasai:言ってください', 'ku-adverb:早く'] },
      ],
    },
    {
      id: 'meme-s5-akeome', level: 'n5', size: 'short', kind: 'slang', emoji: '🎍📱',
      title: 'あけおめ！ことよろ！', titleEn: 'HNY! Be Nice to Me This Yr!',
      punch: 'Japanese loves chopping phrases down to their first syllables: あけましておめでとう (Happy New Year) → あけおめ, 今年もよろしく (be good to me again this year) → ことよろ. Every January, phones fill up with these two words.',
      sentences: [
        { jp: '「 あけおめ ！ ことよろ ！ 」', en: '"HNY! Pls b good 2 me this yr!"',
          grammar: ['ryakugo:あけおめ', 'ryakugo:ことよろ'] },
        { jp: '「 あけまして おめでとう 」 と 「 今年[ことし] も よろしく 」 を 短[みじか]く>短い しました>する 。', en: 'They\'re "akemashite omedetou" and "kotoshi mo yoroshiku", shortened.',
          grammar: ['ku-adverb:短くしました', 'to-and:」と「'] },
      ],
    },
    {
      id: 'meme-s5-sumaho', level: 'n5', size: 'short', kind: 'slang', emoji: '📱💻',
      title: 'スマホとパソコン', titleEn: 'Sumaho and Pasokon',
      punch: 'Long loanwords get chopped into two-plus-two syllables: スマ(ート)ホ(ン), パソ(ナル)コン(ピューター), コンビニ (convenience store), エアコン (air conditioner), リモコン (remote control). Say "smartphone" in full and you\'ll sound like a manual.',
      sentences: [
        { jp: 'スマホ は スマートフォン 、 パソコン は パーソナルコンピューター です 。', en: 'Sumaho is "smartphone", pasokon is "personal computer".',
          grammar: ['wa-contrast:パソコンは', 'ryakugo:スマホ'] },
        { jp: '日本語[にほんご] は 長[なが]い 言葉[ことば] を すぐ 短[みじか]く>短い します>する 。', en: 'Japanese shortens long words right away.',
          grammar: ['ku-adverb:短くします', 'i-adj-noun:長い言葉'] },
      ],
    },
    {
      id: 'meme-s5-getdaze', level: 'n5', size: 'short', kind: 'pop', emoji: '🔴⚪',
      title: 'ポケモン、ゲットだぜ！', titleEn: '"Pokémon — Gotcha!"',
      punch: 'In the Japanese anime, Ash is called サトシ, and he shouts ポケモンゲットだぜ！. ゲット is English "get", used for catching or scoring anything (新しい靴ゲット！ "new shoes — got \'em!"), and だぜ is a cocky, boyish way to end a sentence.',
      sentences: [
        { jp: '「 ポケモン 、 ゲット だ ぜ ！ 」', en: '"Pokémon — gotcha!"',
          grammar: ['daze:ゲットだぜ'] },
        { jp: 'これ は アニメ の サトシ の 言葉[ことば] です 。', en: 'It\'s Ash\'s (Satoshi\'s) catchphrase from the anime.',
          grammar: ['no-possessive:アニメのサトシ', 'no-possessive:サトシの言葉'] },
      ],
    },
    {
      id: 'meme-s5-totoro', level: 'n5', size: 'short', kind: 'pop', emoji: '🌳🐾',
      title: 'トトロの名前[なまえ]', titleEn: 'Where Totoro\'s Name Comes From',
      punch: 'In Studio Ghibli\'s となりのトトロ (1988), four-year-old Mei has a picture book about trolls — トロール in Japanese — and mispronounces the word as トトロ. The name stuck. となり means "next door", so the title is literally "Totoro next door".',
      sentences: [
        { jp: '「 となり の トトロ 」 の メイちゃん は 「 トロール 」 を 「 トトロ 」 と 言[い]いました>言う 。', en: 'In My Neighbour Totoro, little Mei says "Totoro" when she means "troll".',
          grammar: ['to-quote:「トトロ」と言いました', 'wo-object:「トロール」を'] },
        { jp: 'だから 、 あの 大[おお]きい 動物[どうぶつ] の 名前[なまえ] は トトロ です 。', en: 'That\'s why the big furry creature is called Totoro.',
          grammar: ['dakara:だから', 'i-adj-noun:大きい動物'] },
      ],
    },
    {
      id: 'meme-s5-kitty', level: 'n5', size: 'short', kind: 'trivia', emoji: '🎀🐱',
      title: 'キティちゃんの口[くち]', titleEn: 'Why Hello Kitty Has No Mouth',
      punch: 'Sanrio says Hello Kitty has no mouth on purpose: whoever looks at her can see their own feelings in her face. Her full name, by the way, is Kitty White, and she officially lives in London.',
      sentences: [
        { jp: 'キティちゃん に は 口[くち] が ありません>ある 。', en: 'Hello Kitty has no mouth.',
          grammar: ['ni-wa:キティちゃんには', 'masen:ありません'] },
        { jp: 'うれしい とき は 、 キティちゃん も うれしい 顔[かお] に 見[み]えます>見える 。', en: 'When you\'re happy, Kitty looks happy too.',
          grammar: ['toki:うれしいとき', 'ni-mieru:顔に見えます'] },
        { jp: 'かなしい とき は 、 かなしい 顔[かお] に 見[み]えます>見える 。', en: 'When you\'re sad, she looks sad.',
          grammar: ['toki:かなしいとき', 'ni-mieru:顔に見えます'] },
      ],
    },
    {
      id: 'meme-s5-wanwan', level: 'n5', size: 'short', kind: 'trivia', emoji: '🐕🐈🐖',
      title: 'ワンワンとニャー', titleEn: 'Woof in Japanese',
      punch: 'Every language hears animals differently. Japanese dogs go ワンワン, cats ニャー, pigs ブーブー, roosters コケコッコー, frogs ケロケロ. Kids call dogs ワンちゃん and cats にゃんこ after their sounds — and 2/22 (にゃん・にゃん・にゃん) is Cat Day in Japan.',
      sentences: [
        { jp: '日本[にほん] の 犬[いぬ] は 「 ワンワン 」 と 鳴[な]きます>鳴く 。', en: 'Japanese dogs go "wan wan".',
          grammar: ['to-quote:「ワンワン」と鳴きます'] },
        { jp: '猫[ねこ] は 「 ニャー 」 、 ブタ は 「 ブーブー 」 です 。', en: 'Cats go "nyaa", pigs go "buu buu".',
          grammar: ['wa-contrast:ブタは'] },
        { jp: 'あなた の 国[くに] の 犬[いぬ] は ？', en: 'What do dogs say in your country?',
          grammar: ['wa-topic:犬は', 'no-possessive:あなたの国'] },
      ],
    },
    {
      id: 'meme-s5-inemuri', level: 'n5', size: 'short', kind: 'aruaru', emoji: '🚃😴',
      title: '電車[でんしゃ]で寝[ね]る', titleEn: 'Sleeping on the Train',
      punch: 'Napping on the train (居眠り, inemuri) is completely normal in Japan — it\'s safe, and people are tired. The mystery every visitor notices: sleepers snap awake exactly at their stop. あるある means "so true!" — relatable everyday observations, a whole genre of Japanese humour.',
      sentences: [
        { jp: '日本[にほん] の 電車[でんしゃ] で は 、 たくさん の 人[ひと] が 寝[ね]て>寝る います>いる 。', en: 'On Japanese trains, lots of people are asleep.',
          grammar: ['te-iru:寝ています', 'de-place:電車では'] },
        { jp: 'でも 、 自分[じぶん] の 駅[えき] で は ちゃんと 起[お]きます>起きる 。', en: 'But they always wake up at their own station.',
          grammar: ['masu:起きます', 'no-possessive:自分の駅'] },
        { jp: 'どうして ？ だれ>誰 も 知[し]りません>知る 。', en: 'How? Nobody knows.',
          grammar: ['doushite:どうして', 'dare-mo-neg:だれも知りません'] },
      ],
    },
    {
      id: 'meme-s5-chottomatte', level: 'n5', size: 'short', kind: 'aruaru', emoji: '⏰',
      title: '「ちょっと待[ま]って」', titleEn: '"Wait a Sec"',
      punch: 'ちょっと means "a little", but ちょっと待って can mean anything from five seconds to an hour. A true あるある — and not only in Japan.',
      sentences: [
        { jp: '妹[いもうと] は 「 ちょっと 待[ま]って>待つ 」 と 言[い]いました>言う 。', en: 'My little sister said "wait a sec".',
          grammar: ['te-request:待って', 'to-quote:」と言いました'] },
        { jp: 'それ から 、 三十分[さんじゅっぷん] 待[ま]ちました>待つ 。', en: 'Then I waited thirty minutes.',
          grammar: ['masu-past:待ちました'] },
      ],
    },
    {
      id: 'meme-s5-weekend', level: 'n5', size: 'short', kind: 'aruaru', emoji: '📅🐢🐇',
      title: '金曜日[きんようび]と日曜日[にちようび]', titleEn: 'Friday Crawls, Sunday Flies',
      punch: 'Weekend time flies, office time crawls. The Sunday-evening dread is so universal in Japan that it\'s named after a cartoon — find サザエさん症候群 among the N3 short ones.',
      sentences: [
        { jp: '金曜日[きんようび] の 午後[ごご] は 、 時間[じかん] が とても おそい です 。', en: 'Friday afternoons go so slowly.',
          grammar: ['i-adj-desu:おそいです', 'wa-ga:午後は、時間がとてもおそい'] },
        { jp: '日曜日[にちようび] の 夜[よる] は 、 時間[じかん] が とても 早[はや]い です 。', en: 'Sunday evenings go so fast.',
          grammar: ['i-adj-desu:早いです'] },
        { jp: 'どうして でしょう 。', en: 'I wonder why.',
          grammar: ['deshou:どうしてでしょう'] },
      ],
    },

    // ── N4 ──────────────────────────────────────────────────────────────────
    {
      id: 'meme-s4-naiyou', level: 'n4', size: 'short', kind: 'dajare', emoji: '📄🫥',
      title: '内容[ないよう]がないよう', titleEn: 'Seems to Have No Content',
      punch: '内容 (naiyou, content) + ないよう (nai you, "seems there isn\'t any"). The perfect review of a boring essay, meeting or film: 内容がないよう！',
      sentences: [
        { jp: '「 この 本[ほん] 、 内容[ないよう] が ない よう だ 。 」', en: '"This book seems to have no content."',
          grammar: ['you-da:ないようだ', 'ga-subject:内容が'] },
      ],
    },
    {
      id: 'meme-s4-kyaku', level: 'n4', size: 'short', kind: 'twister', emoji: '🟠👅',
      title: '隣[となり]の客[きゃく]はよく柿[かき]食[く]う客[きゃく]だ', titleEn: 'The Persimmon-Eating Guest',
      punch: 'となりのきゃくはよくかきくうきゃくだ: all those k- sounds (kyaku, kaki, kuu, kyaku) knot your tongue. 食う is a rough, masculine word for "eat" — the polite one is 食べる.',
      sentences: [
        { jp: '「 隣[となり]>となり の 客[きゃく] は よく 柿[かき] 食[く]う 客[きゃく] だ 。 」', en: '"The guest next door is a guest who eats lots of persimmons."',
          grammar: ['relative-clause:よく柿食う客', 'no-possessive:隣の客'] },
        { jp: '早[はや]く 言[い]う と 、 舌[した] が からまります>からまる 。', en: 'Say it fast and your tongue gets tangled.',
          grammar: ['to-conditional:言うと', 'ku-adverb:早く'] },
      ],
    },
    {
      id: 'meme-s4-basugasu', level: 'n4', size: 'short', kind: 'twister', emoji: '🚌💥',
      title: 'バスガス爆発[ばくはつ]', titleEn: 'Bus Gas Explosion',
      punch: 'バスガス爆発 ("a bus\'s gas exploded") is short, but the s, g and b sounds keep swapping places. Tongue twisters (早口言葉, "fast-mouth words") are how announcers and actors warm up.',
      sentences: [
        { jp: '「 バス ガス 爆発[ばくはつ]>爆発する 」 を 三回[さんかい] 言[い]って>言う みて>みる 。', en: 'Try saying "basu gasu bakuhatsu" — bus gas explosion — three times.',
          grammar: ['te-miru:言ってみて'] },
        { jp: 'たぶん 、 「 バスバクバク … 」 に なる よ 。', en: 'You\'ll probably end up with "basu baku baku…".',
          grammar: ['ni-naru:」になる'] },
      ],
    },
    {
      id: 'meme-s4-ukeru', level: 'n4', size: 'short', kind: 'slang', emoji: '🤣',
      title: 'マジでウケる', titleEn: 'Seriously Hilarious',
      punch: 'マジ (from 真面目, "serious") means "for real", and ウケる (受ける, "to receive") means a joke landed — "that\'s so funny". マジでウケる is pure high-school speech; you\'ll hear it in every school drama.',
      sentences: [
        { jp: '「 それ 、 マジ で ウケる ！ 」', en: '"Seriously, that\'s hilarious!"',
          grammar: ['plain-form:ウケる'] },
        { jp: '「 マジ 」 は 「 本当[ほんとう] に 」 、 「 ウケる 」 は 「 おもしろい 」 と いう>言う 意味[いみ] だ よ 。', en: '"Maji" means "really", and "ukeru" means "funny".',
          grammar: ['to-iu:」という意味', 'wa-contrast:「ウケる」は'] },
      ],
    },
    {
      id: 'meme-s4-ryo', level: 'n4', size: 'short', kind: 'slang', emoji: '👌',
      title: '了解[りょうかい]→りょ→り', titleEn: 'Roger → Ro → R',
      punch: '了解 (ryoukai, "roger, understood") → りょ → り: the shortest reply in Japanese texting. Its cousin for thank-you is あざす, worn down from ありがとうございます.',
      sentences: [
        { jp: '「 了解[りょうかい] 」 は 「 わかりました>わかる 」 と いう>言う 意味[いみ] です 。', en: '"Ryoukai" means "got it".',
          grammar: ['to-iu:」という意味'] },
        { jp: '若[わか]い 人[ひと] は メッセージ で 「 りょ 」 と 書[か]きます>書く 。', en: 'Young people write "ryo" in messages.',
          grammar: ['de-means:メッセージで', 'ryakugo:りょ'] },
        { jp: 'もっと 急[いそ]いで>急ぐ いる とき は 、 「 り 」 だけ です 。', en: 'When they\'re in an even bigger hurry, it\'s just "ri".',
          grammar: ['te-iru:急いでいる', 'dake:「り」だけ'] },
      ],
    },
    {
      id: 'meme-s4-guguru', level: 'n4', size: 'short', kind: 'slang', emoji: '🔍',
      title: 'ググる', titleEn: 'To Google',
      punch: 'Japanese turns words into verbs by tacking on る: ググる (to google), メモる (to take a memo), サボる (to skip class — from French sabotage), ディスる (to diss). They conjugate like normal う-verbs: ググった, ググらない.',
      sentences: [
        { jp: 'わからない>わかる こと が ある と 、 すぐ ググる 。', en: 'Whenever there\'s something I don\'t know, I google it straight away.',
          grammar: ['to-conditional:あると', 'relative-clause:わからないこと'] },
        { jp: '「 ググる 」 は 「 グーグル 」 を 動詞[どうし] に した>する 言葉[ことば] だ 。', en: '"Guguru" is "Google" turned into a verb.',
          grammar: ['ni-suru:動詞にした', 'relative-clause:動詞にした言葉'] },
      ],
    },
    {
      id: 'meme-s4-anpanman', level: 'n4', size: 'short', kind: 'pop', emoji: '🍞🦸',
      title: 'ぼくの顔[かお]をお食[た]べ', titleEn: '"Here, Eat My Face"',
      punch: 'アンパンマン, Japan\'s most beloved toddler hero, has a head made of あんパン (bread filled with sweet bean paste) and feeds hungry people with it. お食べ is a gentle, old-fashioned "eat up". Adults find it a little unsettling; kids find it perfectly normal.',
      sentences: [
        { jp: 'アンパンマン は おなか>お腹 が すいた>すく 子[こ] に 言[い]います>言う 。', en: 'Anpanman says to a hungry child:',
          grammar: ['relative-clause:おなかがすいた子'] },
        { jp: '「 ぼく の 顔[かお] を お食[た]べ 。 」', en: '"Here — eat my face."',
          grammar: ['wo-object:顔をお食べ'] },
        { jp: '顔[かお] が なくなったら>なくなる 、 ジャムおじさん が 新[あたら]しい 顔[かお] を 作[つく]って>作る くれます>くれる 。', en: 'When his face is gone, Uncle Jam bakes him a new one.',
          grammar: ['tara:なくなったら', 'te-kureru:作ってくれます'] },
      ],
    },
    {
      id: 'meme-s4-elevator', level: 'n4', size: 'short', kind: 'aruaru', emoji: '🛗👆',
      title: '「閉[し]める」ボタン', titleEn: 'The "Close Door" Button',
      punch: 'A true あるある: the 閉 (close) button may be the most-pressed button in Japan. Polite people also hold 開 (open) for everyone else, then bow as the doors close.',
      sentences: [
        { jp: 'エレベーター に 乗[の]る と 、 すぐ 「 閉[し]める 」 ボタン を 押[お]して>押す しまう 。', en: 'Get in a lift and you end up jabbing the "close" button right away.',
          grammar: ['to-conditional:乗ると', 'te-shimau:押してしまう'] },
        { jp: 'ドア が 閉[し]まる まで の 三秒[さんびょう] が 待[ま]てない>待つ 。', en: 'You just can\'t wait the three seconds it takes the door to shut.',
          grammar: ['made:閉まるまで', 'potential:待てない'] },
      ],
    },
    {
      id: 'meme-s4-iketara', level: 'n4', size: 'short', kind: 'aruaru', emoji: '🙃',
      title: '行[い]けたら行[い]く', titleEn: '"I\'ll Come If I Can"',
      punch: '行けたら行く ("if I can go, I\'ll go") sounds positive but is the softest possible no — and Kansai people, so the joke goes, never show up after saying it. Like 「ちょっと…」 in the longer reads, the refusal hides inside a polite phrase.',
      sentences: [
        { jp: '「 行[い]けたら>行く 行[い]く 」 と 言[い]う 人[ひと] は 、 だいたい 来[こ]ない>来る 。', en: 'People who say "I\'ll come if I can" usually don\'t come.',
          grammar: ['tara:行けたら', 'potential:行けたら'] },
        { jp: '特[とく]に 関西[かんさい] で は 、 これ は 「 行[い]かない>行く 」 と いう>言う 意味[いみ] だ 。', en: 'Especially in Kansai, it just means "I\'m not coming".',
          grammar: ['to-iu:」という意味'] },
      ],
    },
    {
      id: 'meme-s4-ojigi', level: 'n4', size: 'short', kind: 'aruaru', emoji: '📞🙇',
      title: '電話[でんわ]でおじぎ', titleEn: 'Bowing on the Phone',
      punch: 'Bowing (おじぎ) is so automatic that people in Japan bow to the person on the other end of a phone call — sometimes several times, while saying すみません or よろしくお願いします. Watch any office at 9 a.m.',
      sentences: [
        { jp: '電話[でんわ] で 話[はな]し>話す ながら 、 だれ>誰 も 見[み]て>見る いない>いる のに 、 おじぎ を して>する しまう 。', en: 'Talking on the phone, you end up bowing — even though nobody can see you.',
          grammar: ['nagara:話しながら', 'noni:いないのに', 'te-shimau:してしまう'] },
      ],
    },
    {
      id: 'meme-s4-kushami', level: 'n4', size: 'short', kind: 'trivia', emoji: '🤧',
      title: 'くしゃみとうわさ', titleEn: 'Sneezing Means Gossip',
      punch: 'The old saying goes: 一ほめられ、二にくまれ、三ほれられ、四風邪ひく — one sneeze, someone is praising you; two, someone hates you; three, someone has fallen for you; four… you\'ve caught a cold. In manga, a sneeze (ハックション！) cuts away to whoever is talking about the sneezer.',
      sentences: [
        { jp: '日本[にほん] で は 、 くしゃみ を する と 、 だれ>誰 か が うわさ を して>する いる と 言[い]われて>言う いる 。', en: 'In Japan, they say that if you sneeze, someone is gossiping about you.',
          grammar: ['to-conditional:すると', 'passive:言われている'] },
        { jp: '一回[いっかい] は いい うわさ 、 二回[にかい] は 悪[わる]い うわさ だ そう だ 。', en: 'One sneeze is good gossip, two is bad gossip, apparently.',
          grammar: ['sou-hearsay:うわさだそうだ'] },
      ],
    },
    {
      id: 'meme-s4-keshigomu', level: 'n4', size: 'short', kind: 'riddle', emoji: '✏️❓',
      title: '使[つか]うほど小[ちい]さくなるもの', titleEn: 'The More You Use It…',
      punch: '〜ば〜ほど ("the more…, the more…") is a favourite riddle frame. Here\'s another: とればとるほど大きくなるものは？ — the more you take, the bigger it gets — 穴 (a hole).',
      sentences: [
        { jp: '「 使[つか]えば>使う 使[つか]う ほど 、 小[ちい]さく>小さい なる もの は 何[なん] だ ？ 」', en: '"The more you use it, the smaller it gets. What is it?"',
          grammar: ['ba-hodo:使えば使うほど', 'ku-naru:小さくなる'] },
        { jp: '答[こた]え は 消[け]しゴム 。 お金[かね] も そう だ けど … 。', en: 'The answer: an eraser. (Money too, but…)',
          grammar: ['wa-topic:答えは', 'mo-also:お金も'] },
      ],
    },
    {
      id: 'meme-s4-mizu', level: 'n4', size: 'short', kind: 'riddle', emoji: '🔪💧',
      title: '切[き]っても切[き]れないもの', titleEn: 'You Can\'t Cut It',
      punch: 'Slice water with a knife and it closes right up again. 切っても切れない is also a real idiom: 切っても切れない関係 is an unbreakable bond — like you and your phone.',
      sentences: [
        { jp: '「 切[き]って>切る も 切[き]って>切る も 、 切[き]れない>切る もの は 何[なん] だ ？ 」', en: '"You cut it and cut it, but it never gets cut. What is it?"',
          grammar: ['te-mo:切っても', 'potential:切れない'] },
        { jp: '答[こた]え は 「 水[みず] 」 。', en: 'The answer: water.',
          grammar: ['wa-topic:答えは'] },
      ],
    },
    {
      id: 'meme-s4-kouchou', level: 'n4', size: 'short', kind: 'dajare', emoji: '👴🏫',
      title: '校長[こうちょう]先生[せんせい]、絶好調[ぜっこうちょう]', titleEn: 'The Principal Is on a Roll',
      punch: '校長 (kouchou, school principal) rhymes with 絶好調 (zekkouchou, "in top form"). A safe pun to say to a teacher\'s face — they\'ve heard it a thousand times and still smile.',
      sentences: [
        { jp: '「 校長[こうちょう] 先生[せんせい] 、 今日[きょう] も 絶好調[ぜっこうちょう] です ね ！ 」', en: '"Principal (kouchou), you\'re in top form (zekkouchou) again today!"',
          grammar: ['mo-also:今日も', 'ne:ですね'] },
        { jp: '生徒[せいと] に そう 言[い]われる>言う と 、 校長[こうちょう] 先生[せんせい] は うれしそう だ 。', en: 'When the students say it, the principal looks pleased.',
          grammar: ['passive:言われる', 'sou-looks:うれしそう'] },
      ],
    },
    {
      id: 'meme-s4-katsu', level: 'n4', size: 'short', kind: 'trivia', emoji: '🍛🏆',
      title: 'カツを食[た]べて勝[か]つ', titleEn: 'Eat Katsu, Win',
      punch: 'Edible puns are real good-luck charms: カツ (cutlet) for 勝つ (to win), and キットカット for きっと勝つ ("you\'ll surely win") — which is why Kit Kats are a huge exam-season gift in Japan.',
      sentences: [
        { jp: '試験[しけん] や 試合[しあい] の 前[まえ] に 、 カツ丼[どん] を 食[た]べる 人[ひと] が 多[おお]い 。', en: 'Lots of people eat katsudon before an exam or a big game.',
          grammar: ['mae-ni:試合の前に', 'ya-and:試験や試合'] },
        { jp: '「 カツ 」 と 「 勝[か]つ 」 が 同[おな]じ 音[おと] だ から だ 。', en: 'Because "katsu" (cutlet) and "katsu" (to win) sound the same.',
          grammar: ['kara-reason:音だから'] },
      ],
    },

    // ── N3 ──────────────────────────────────────────────────────────────────
    {
      id: 'meme-s3-coordinate', level: 'n3', size: 'short', kind: 'dajare', emoji: '👗🕺',
      title: 'コーディネートはこーでねーと', titleEn: 'Coordination Goes Like This',
      punch: 'コーディネート (putting an outfit together) vs こーでねーと, a drawled こうでないと ("it\'s gotta be like this"). Delivered while striking a pose, ideally pointing at your own shoes.',
      sentences: [
        { jp: '「 コーディネート は 、 こーでねーと 。 」', en: '"Coordinating an outfit — it\'s gotta be like this."',
          grammar: ['ee-slur:こーでねーと'] },
        { jp: '「 こーでねーと 」 は 「 こう で なければ>ない 」 の 乱暴[らんぼう] な 言[い]い方[かた] だ 。', en: '"Kōdenēto" is a rough way of saying "kō de nakereba" — unless it\'s like this.',
          grammar: ['nakereba-naranai:なければ', 'na-adj-noun:乱暴な言い方'] },
      ],
    },
    {
      id: 'meme-s3-warota', level: 'n3', size: 'short', kind: 'slang', emoji: '😆⌨️',
      title: 'ワロタ', titleEn: 'Warota (lol)',
      punch: 'ワロタ comes from 2ちゃんねる, Japan\'s giant anonymous forum, where 笑った (waratta, "I laughed") got typed as a goofy, Kansai-flavoured ワロタ. Its family: ワロス, クソワロタ ("lmfao") and the now-classic 草.',
      sentences: [
        { jp: '「 ワロタ 」 は 「 笑[わら]った>笑う 」 の ネット スラング だ 。', en: '"Warota" is internet slang for "waratta" — "I laughed".',
          grammar: ['plain-form:笑った'] },
        { jp: 'もっと 笑[わら]った>笑う とき は 、 「 大草原[だいそうげん] 」 や 「 wwwww 」 を つける 。', en: 'When it\'s even funnier, you add 大草原 or wwwww.',
          grammar: ['toki:笑ったとき', 'ya-and:「大草原」や「wwwww」'] },
      ],
    },
    {
      id: 'meme-s3-orz', level: 'n3', size: 'short', kind: 'slang', emoji: '🙇‍♂️💧',
      title: 'orz', titleEn: 'orz — Total Despair',
      punch: 'orz (or OTL) is a 2000s Japanese text emoticon: a little stick figure collapsed on the floor, head down. Type it when you fail a test, miss the last train, or your 推し announces their marriage.',
      sentences: [
        { jp: '「 orz 」 は 、 人[ひと] が 手[て] と 膝[ひざ] を ついて>つく 落[お]ち込[こ]んで>落ち込む いる 姿[すがた] に 見[み]える 。', en: '"orz" looks like a person down on their hands and knees in despair.',
          grammar: ['ni-mieru:姿に見える', 'te-iru:落ち込んでいる'] },
        { jp: '「 o 」 が 頭[あたま] 、 「 r 」 が 腕[うで] 、 「 z 」 が 足[あし] だ 。', en: '"o" is the head, "r" the arms, and "z" the legs.',
          grammar: ['ga-subject:「o」が'] },
      ],
    },
    {
      id: 'meme-s3-barusu', level: 'n3', size: 'short', kind: 'pop', emoji: '🏰💥',
      title: 'バルス！', titleEn: 'Balse!',
      punch: 'バルス is the spell that destroys the floating castle at the climax of Ghibli\'s 天空の城ラピュタ (1986). Whenever the film airs on Japanese TV, viewers post バルス in sync — in 2013 it set a Twitter record of over 140,000 tweets in a single second.',
      sentences: [
        { jp: '「 天空[てんくう]の城[しろ]ラピュタ 」 が テレビ で 放送[ほうそう]される>放送する と 、 ファン は 同[おな]じ 瞬間[しゅんかん] に 「 バルス ！ 」 と 書[か]き込[こ]む>書き込む 。', en: 'Whenever Castle in the Sky airs on TV, fans all post "Balse!" at the very same moment.',
          grammar: ['passive:放送される', 'to-conditional:放送されると'] },
        { jp: 'その せい で 、 サーバー が 落[お]ち>落ちる そう に なった>なる こと も ある 。', en: 'It has even nearly crashed servers.',
          grammar: ['sei-de:そのせいで', 'sou-ni-naru:落ちそうになった', 'koto-ga-aru-sometimes:なったこともある'] },
      ],
    },
    {
      id: 'meme-s3-sazae', level: 'n3', size: 'short', kind: 'pop', emoji: '📺😩',
      title: 'サザエさん症候群[しょうこうぐん]', titleEn: 'Sazae-san Syndrome',
      punch: 'サザエさん, a gentle family cartoon, has aired every Sunday at 6:30 p.m. since 1969 — the longest-running animated TV series in the world. For generations its theme song has meant "the weekend is over", hence サザエさん症候群: the Sunday-night blues.',
      sentences: [
        { jp: '日曜[にちよう] の 夕方[ゆうがた] 、 アニメ 「 サザエさん 」 が 始[はじ]まる と 、 「 明日[あした] は 月曜日[げつようび] か … 」 と 憂鬱[ゆううつ] に なる 。', en: 'When Sazae-san comes on on Sunday evening, you sink into gloom: "Tomorrow\'s Monday…"',
          grammar: ['to-conditional:始まると', 'ni-naru:憂鬱になる'] },
        { jp: 'これ を 「 サザエさん 症候群[しょうこうぐん] 」 と 呼[よ]ぶ 。', en: 'This is called "Sazae-san syndrome".',
          grammar: ['to-quote:」と呼ぶ'] },
      ],
    },
    {
      id: 'meme-s3-kami', level: 'n3', size: 'short', kind: 'slang', emoji: '✨🙏',
      title: '神[かみ]対応[たいおう]', titleEn: 'God-Tier Service',
      punch: '神 (kami, god) is the internet\'s highest praise: 神対応 (amazing service), 神回 (a legendary episode), 神ゲー (a god-tier game). Its opposites are クソゲー ("crap game") and 塩対応 ("salty", cold treatment).',
      sentences: [
        { jp: 'すごく いい もの は 、 ネット で 「 神[かみ] 」 と 呼[よ]ばれる>呼ぶ 。', en: 'Online, anything amazing gets called "god".',
          grammar: ['passive:呼ばれる'] },
        { jp: '店員[てんいん] が 親切[しんせつ] だったら>だ 「 神[かみ] 対応[たいおう] 」 、 すごい ゲーム は 「 神[かみ]ゲー 」 だ 。', en: 'A super-kind clerk is "god-tier service"; an amazing game is a "god game".',
          grammar: ['tara:親切だったら'] },
        { jp: '逆[ぎゃく] に 、 ひどい ゲーム は 「 クソゲー 」 。', en: 'And a terrible game? A "kusoge" — a crap game.',
          grammar: ['wa-topic:ゲームは'] },
      ],
    },
    {
      id: 'meme-s3-gachi', level: 'n3', size: 'short', kind: 'slang', emoji: '💪🎮',
      title: 'ガチ勢[ぜい]', titleEn: 'The Hardcore Crowd',
      punch: 'ガチ comes from sumo slang ガチンコ, a real, unfixed bout. Now ガチで = "seriously", ガチ勢 = the hardcore crowd (vs エンジョイ勢, people just having fun), and ガチ恋 = being seriously in love with your idol.',
      sentences: [
        { jp: '「 ガチ で 疲[つか]れた>疲れる 」 は 「 本当[ほんとう] に 疲[つか]れた>疲れる 」 と いう>言う 意味[いみ] だ 。', en: '"Gachi de tsukareta" means "I\'m seriously tired".',
          grammar: ['to-iu:」という意味'] },
        { jp: '「 ガチ 勢[ぜい] 」 は 、 趣味[しゅみ] を 本気[ほんき] で やって>やる いる 人[ひと] たち の こと だ 。', en: '"Gachi-zei" are people who take a hobby dead seriously.',
          grammar: ['te-iru:やっている', 'no-koto:人たちのこと'] },
      ],
    },
    {
      id: 'meme-s3-motowotoru', level: 'n3', size: 'short', kind: 'aruaru', emoji: '🍖🍰😵',
      title: '食[た]べ放題[ほうだい]で元[もと]を取[と]る', titleEn: 'Getting Your Money\'s Worth',
      punch: '元を取る ("to recover the cost") is the sacred mission at 食べ放題 (all-you-can-eat) and 飲み放題 (all-you-can-drink) — usually against a strict 90-minute time limit.',
      sentences: [
        { jp: '食[た]べ放題[ほうだい] で 元[もと] を 取[と]ろう>取る と して>する 、 食[た]べ>食べる すぎて>すぎる 動[うご]けなく>動く なる 。', en: 'At all-you-can-eat, you try to get your money\'s worth, eat too much, and can\'t move.',
          grammar: ['you-to-suru:取ろうとして', 'sugiru:食べすぎて', 'ku-naru:動けなくなる'] },
        { jp: '次[つぎ] の 日[ひ] 、 「 もう 二度[にど]と 行[い]かない>行く 」 と 言[い]う 。 そして 、 また 行[い]く 。', en: 'The next day you say "never again". And then you go again.',
          grammar: ['to-quote:」と言う'] },
      ],
    },
    {
      id: 'meme-s3-bubuzuke', level: 'n3', size: 'short', kind: 'trivia', emoji: '🍵🚪',
      title: 'ぶぶ漬[づ]けでもどうどす？', titleEn: 'How About Some Tea-Rice?',
      punch: 'ぶぶ漬け is Kyoto dialect for お茶漬け (rice with tea poured over it). Legend says that when a Kyoto host offers it, they\'re politely hinting that your visit is over. Whether anyone still does it is debated, but it\'s the go-to joke about Kyoto\'s famously indirect manners (どす is Kyoto for です).',
      sentences: [
        { jp: '京都[きょうと] で 「 ぶぶ漬[づ]け でも>でも(suggest) どう どす か 」 と 言[い]われたら>言う 、 「 そろそろ 帰[かえ]って>帰る 」 と いう>言う 意味[いみ] らしい 。', en: 'In Kyoto, apparently, if someone asks "How about some tea-rice?", it means "time to go home".',
          grammar: ['tara:言われたら', 'passive:言われたら', 'rashii:意味らしい'] },
        { jp: '本当[ほんとう] に 食[た]べたら>食べる 、 もう 二度[にど]と 呼[よ]ばれない>呼ぶ かもしれない 。', en: 'Actually eat it, and you may never be invited again.',
          grammar: ['tara:食べたら', 'kamoshirenai:呼ばれないかもしれない'] },
      ],
    },
    {
      id: 'meme-s3-bang', level: 'n3', size: 'short', kind: 'trivia', emoji: '👉💥',
      title: '大阪[おおさか]で「バーン！」', titleEn: 'Bang! (Osaka Edition)',
      punch: 'Osaka people are famous for ノリ (going along with a joke) and ツッコミ (the comeback). The finger-gun test is a staple of variety TV: an astonishing number of passers-by clutch their chest and collapse. Not playing along is considered a bit of a letdown.',
      sentences: [
        { jp: '大阪[おおさか] の 人[ひと] に 指[ゆび] で ピストル の 形[かたち] を 作[つく]って>作る 「 バーン ！ 」 と 言[い]う と 、 撃[う]たれた>撃つ ふり を して>する くれる らしい 。', en: 'They say if you make a finger gun at someone from Osaka and go "Bang!", they\'ll pretend to be shot.',
          grammar: ['to-conditional:言うと', 'furi:撃たれたふり', 'te-kureru:してくれる', 'rashii:くれるらしい'] },
        { jp: 'テレビ 番組[ばんぐみ] で も 、 何度[なんど] も 試[ため]されて>試す いる 。', en: 'TV shows have tested it again and again.',
          grammar: ['passive:試されている'] },
      ],
    },
    {
      id: 'meme-s3-kawaii', level: 'n3', size: 'short', kind: 'aruaru', emoji: '🎀🕳️',
      title: '何[なん]でも「かわいい」', titleEn: 'Everything Is Kawaii',
      punch: 'かわいい covers far more than "cute": lovable, charming, pitiable, small, funny-looking. Japan even has キモかわいい (creepy-cute) and ブサかわいい (ugly-cute) — think of a squashed-faced pug — and hundreds of towns have their own かわいい mascot (ゆるキャラ). Look down: many manhole covers are works of art.',
      sentences: [
        { jp: '日本[にほん] で は 、 キャラクター も 、 おじさん も 、 マンホール の ふた も 「 かわいい 」 。', en: 'In Japan, characters, middle-aged men, even manhole covers are "kawaii".',
          grammar: ['mo-also:マンホールのふたも'] },
        { jp: '「 キモかわいい 」 「 ブサかわいい 」 と いう>言う 言葉[ことば] まで ある 。', en: 'There are even words like "kimo-kawaii" (creepy-cute) and "busa-kawaii" (ugly-cute).',
          grammar: ['made-even:言葉まで', 'to-iu:」という言葉'] },
      ],
    },
    {
      id: 'meme-s3-bocchi', level: 'n3', size: 'short', kind: 'slang', emoji: '🍱🧍',
      title: 'ぼっち飯[めし]', titleEn: 'Eating Alone',
      punch: 'ぼっち is self-deprecating student slang. But the mood has flipped: ソロ活 — solo karaoke, solo yakiniku, solo travel — is now trendy, and restaurants with one-person booths are booming.',
      sentences: [
        { jp: '「 ぼっち 」 は 「 一人[ひとり]ぼっち 」 から 来[き]た>来る 言葉[ことば] で 、 友[とも]だち が いない>いる 人[ひと] の こと だ 。', en: '"Bocchi" comes from hitoribocchi, "all alone", and means someone with no friends.',
          grammar: ['relative-clause:から来た言葉', 'no-koto:人のこと'] },
        { jp: '一人[ひとり] で 食[た]べる 昼[ひる]ご飯[はん] は 「 ぼっち 飯[めし] 」 と 呼[よ]ばれる>呼ぶ 。', en: 'Lunch eaten alone is called "bocchi-meshi".',
          grammar: ['passive:呼ばれる', 'de-together:一人で'] },
        { jp: 'でも 最近[さいきん] は 、 一人[ひとり] を 楽[たの]しむ 「 ソロ活[かつ] 」 も 人気[にんき] だ 。', en: 'But these days, "solo-katsu" — happily doing things on your own — is popular too.',
          grammar: ['mo-also:「ソロ活」も', 'relative-clause:一人を楽しむ「ソロ活」'] },
      ],
    },
    {
      id: 'meme-s3-kabedon', level: 'n3', size: 'short', kind: 'pop', emoji: '🧱✋',
      title: '壁[かべ]ドン', titleEn: 'Kabe-Don',
      punch: '壁ドン ("wall-bam") is the swoon-worthy manga move of pinning someone against a wall with one hand. It became a buzzword in 2014 — though older Japanese still think of the original meaning: thumping the wall at noisy neighbours. ドン is the sound of the slam.',
      sentences: [
        { jp: '少女[しょうじょ] マンガ で は 、 男[おとこ] の 子[こ] が 女[おんな] の 子[こ] を 壁[かべ] に 追[お]い詰[つ]めて>追い詰める 、 手[て] を 「 ドン ！ 」 と つく 。', en: 'In shōjo manga, a boy corners a girl against a wall and slams his hand on it — "don!"',
          grammar: ['te-sequence:追い詰めて', 'to-quote:」とつく'] },
        { jp: 'これ を 「 壁[かべ] ドン 」 と いう>言う 。', en: 'That\'s called "kabe-don".',
          grammar: ['to-quote:「壁ドン」という'] },
        { jp: 'でも 、 もともと は 、 隣[となり] の 部屋[へや] が うるさい とき に 壁[かべ] を たたく こと だった>だ 。', en: 'But originally, it meant banging on the wall when the neighbours were too loud.',
          grammar: ['toki:うるさいとき', 'koto-nominalizer:たたくこと'] },
      ],
    },
    {
      id: 'meme-s3-sumi', level: 'n3', size: 'short', kind: 'riddle', emoji: '⚫🔴⚪',
      title: '黒[くろ]、赤[あか]、白[しろ]', titleEn: 'Black, Red, White',
      punch: 'Charcoal is black in the bag, glows red in the grill and crumbles into white ash. Riddles built from a chain of changes are a classic なぞなぞ pattern — and a handy drill for い-adjective 〜く なる.',
      sentences: [
        { jp: '「 買[か]う とき は 黒[くろ]く>黒い 、 使[つか]う と 赤[あか]く>赤い なり>なる 、 捨[す]てる とき は 白[しろ]い 。 」', en: '"Black when you buy it, red when you use it, white when you throw it away."',
          grammar: ['toki:買うとき', 'to-conditional:使うと', 'ku-naru:赤くなり'] },
        { jp: '「 これ は 何[なん] だ ？ 」 答[こた]え は 炭[すみ] 。', en: '"What is it?" Answer: charcoal.',
          grammar: ['question-words:何だ', 'wa-topic:答えは'] },
      ],
    },
    {
      id: 'meme-s3-ohayou', level: 'n3', size: 'short', kind: 'trivia', emoji: '🌙☀️',
      title: '夜[よる]でも「おはようございます」', titleEn: '"Good Morning" at Midnight',
      punch: 'In the entertainment world (and in many restaurants and night-shift jobs), おはようございます means "hello — first time seeing you today", whatever the hour. Say it at 10 p.m. in a TV studio and you\'ll sound like an industry insider.',
      sentences: [
        { jp: 'テレビ や 芸能界[げいのうかい] で は 、 夜[よる] に 会[あ]って>会う も 「 おはようございます 」 と あいさつ する 。', en: 'In TV and showbiz, people say "good morning" even when they meet at night.',
          grammar: ['te-mo:会っても', 'to-quote:」とあいさつする'] },
        { jp: 'その 日[ひ] 初[はじ]めて 会[あ]う とき の あいさつ だ から だ そう だ 。', en: 'Apparently, it\'s because it\'s the greeting for the first time you meet that day.',
          grammar: ['sou-hearsay:だからだそうだ', 'toki:会うとき'] },
      ],
    },
  ];

  const LONG = [
    // ── N5 ──────────────────────────────────────────────────────────────────
    {
      id: 'meme-n5-shiritori', level: 'n5', size: 'long', kind: 'story', emoji: '🔤🍜',
      title: 'しりとり', titleEn: 'Shiritori with My Hungry Brother',
      punch: 'しりとり ("taking the tail") is Japan\'s classic word-chain game: each word must start with the last kana of the one before, and since almost no Japanese words start with ん, saying a word that ends in ん loses on the spot. Hungry little brothers lose a lot: パン, ラーメン, みかん, うどん…',
      sentences: [
        { jp: '弟[おとうと] と しりとり を しました>する 。', en: 'I played shiritori with my little brother.',
          grammar: ['to-with:弟と', 'wo-object:しりとりをしました'] },
        { jp: 'しりとり は 、 前[まえ] の 言葉[ことば] の 最後[さいご] の 音[おと] から 、 次[つぎ] の 言葉[ことば] を 言[い]う ゲーム です 。', en: 'In shiritori, each word has to start with the last sound of the word before.',
          grammar: ['kara-from:最後の音から', 'relative-clause:次の言葉を言うゲーム'] },
        { jp: '「 ん>ん(kana) 」 で 終[お]わる 言葉[ことば] を 言[い]ったら>言う 、 負[ま]け です 。', en: 'If you say a word that ends in "n", you lose.',
          grammar: ['tara:言ったら', 'relative-clause:終わる言葉'] },
        { jp: 'わたし>私 は 「 りんご 」 、 弟[おとうと] は 「 ゴリラ 」 と 言[い]いました>言う 。', en: 'I said "ringo" (apple), and my brother said "gorira" (gorilla).',
          grammar: ['wa-contrast:弟は', 'to-quote:「ゴリラ」と言いました'] },
        { jp: 'わたし>私 が 「 ラッパ 」 と 言[い]う と 、 弟[おとうと] は 「 パン 」 と 言[い]いました>言う 。', en: 'When I said "rappa" (trumpet), he said "pan" (bread).',
          grammar: ['to-conditional:言うと', 'to-quote:「パン」と言いました'] },
        { jp: '「 ん>ん(kana) 」 で 終[お]わりました>終わる よ 。 弟[おとうと] の 負[ま]け です 。', en: '"That ends in n! You lose."',
          grammar: ['masu-past:終わりました', 'no-possessive:弟の負け'] },
        { jp: 'もう 一回[いっかい] 。 弟[おとうと] は 「 ラーメン 」 と 言[い]いました>言う 。', en: 'One more round. My brother said "rāmen".',
          grammar: ['to-quote:「ラーメン」と言いました'] },
        { jp: '三回目[さんかいめ] は 「 みかん 」 でした>です 。', en: 'The third time, it was "mikan".',
          grammar: ['deshita:「みかん」でした'] },
        { jp: '弟[おとうと] 「 だって 、 おなか>お腹 が すいた>すく ん だ もん 。 」', en: 'My brother: "But I\'m hungry!"',
          grammar: ['n-desu:すいたんだ'] },
      ],
    },
    {
      id: 'meme-n5-konbini', level: 'n5', size: 'long', kind: 'story', emoji: '🏪🍦',
      title: 'コンビニで「はい」', titleEn: 'Yes to Everything at the Konbini',
      punch: 'Japanese convenience-store clerks fire off a fast, polite checklist — あたためますか (heat it up?), お箸はおつけしますか (chopsticks?), 袋は一緒でいいですか (all in one bag?). Answering はい to everything is how learners end up with microwaved ice cream. Next time: point at the bento and say これだけ (just this one).',
      sentences: [
        { jp: 'トムさん は 日本語[にほんご] を 勉強[べんきょう]して>勉強する います>いる 。', en: 'Tom is studying Japanese.',
          grammar: ['te-iru:勉強しています'] },
        { jp: '今日[きょう] 、 初[はじ]めて 一人[ひとり] で コンビニ に 行[い]きました>行く 。', en: 'Today he went to a convenience store on his own for the first time.',
          grammar: ['de-together:一人で', 'ni-destination:コンビニに行きました'] },
        { jp: 'アイス と お弁当[べんとう] を 買[か]いました>買う 。', en: 'He bought an ice cream and a bento.',
          grammar: ['to-and:アイスとお弁当', 'masu-past:買いました'] },
        { jp: '店員[てんいん]さん は 早口[はやくち] で いろいろ 聞[き]きます>聞く 。', en: 'The clerk asks him all sorts of things, fast.',
          grammar: ['de-means:早口で', 'masu:聞きます'] },
        { jp: '「 あたためます>あたためる か 。 」 「 はい 。 」', en: '"Shall I heat it up?" "Yes."',
          grammar: ['ka-question:あたためますか'] },
        { jp: '「 お箸[はし] は つけます>つける か 。 」 「 はい 。 」', en: '"Do you need chopsticks?" "Yes."',
          grammar: ['ka-question:つけますか', 'wa-topic:お箸は'] },
        { jp: '「 袋[ふくろ] は 一緒[いっしょ] で いい です か 。 」 「 はい 。 」', en: '"Is one bag OK for everything?" "Yes."',
          grammar: ['ka-question:いいですか'] },
        { jp: '家[いえ] で 袋[ふくろ] を 開[あ]けました>開ける 。', en: 'At home, he opened the bag.',
          grammar: ['de-place:家で', 'masu-past:開けました'] },
        { jp: 'お弁当[べんとう] は あたたかい>温かい です 。 アイス も あたたかい>温かい です 。', en: 'The bento was warm. So was the ice cream.',
          grammar: ['mo-also:アイスも', 'i-adj-desu:あたたかいです'] },
        { jp: 'アイス は 、 もう ジュース に なって>なる いました>いる 。', en: 'The ice cream had already turned into juice.',
          grammar: ['ni-naru:ジュースになって', 'te-iru:なっていました'] },
      ],
    },
    {
      id: 'meme-n5-momotaro', level: 'n5', size: 'long', kind: 'story', emoji: '🍑👹',
      title: '桃太郎[ももたろう]ときびだんご', titleEn: 'Momotarō and the Dumpling Deal',
      punch: 'In the folk tale 桃太郎 ("Peach Boy"), a boy born from a giant peach recruits a dog, a monkey and a pheasant with きびだんご (millet dumplings) to fight the ogres of 鬼ヶ島. Every child in Japan knows the song: ももたろうさん、ももたろうさん、おこしにつけたきびだんご、ひとつわたしにくださいな. This version is about what happens when the other side offers better benefits.',
      sentences: [
        { jp: '桃太郎[ももたろう] は 鬼[おに] を たいじ に 行[い]きます>行く 。', en: 'Momotarō sets off to defeat the ogres.',
          grammar: ['ni-iku-purpose:たいじに行きます'] },
        { jp: '犬[いぬ] が 来[き]ました>来る 。 「 きびだんご を 一[ひと]つ ください 。 」', en: 'A dog came along. "One millet dumpling, please."',
          grammar: ['ga-subject:犬が', 'wo-object:きびだんごを'] },
        { jp: '「 はい 、 どうぞ 。 一緒[いっしょ] に 行[い]きましょう>行く 。 」', en: '"Here you go. Let\'s go together."',
          grammar: ['mashou:行きましょう'] },
        { jp: '次[つぎ] に 、 サル が 来[き]ました>来る 。 「 ぼく は 二[ふた]つ ください 。 」', en: 'Next came a monkey. "I\'ll take two, please."',
          grammar: ['counters:二つ', 'wa-contrast:ぼくは'] },
        { jp: 'それから 、 キジ が 来[き]ました>来る 。 「 わたし>私 は 三[みっ]つ と 、 お金[かね] も ください 。 」', en: 'Then came a pheasant. "Three for me — and money, too."',
          grammar: ['to-and:三つと', 'mo-also:お金も'] },
        { jp: '桃太郎[ももたろう] は 困[こま]りました>困る 。 きびだんご は もう ありません>ある 。', en: 'Momotarō was stuck. He had no dumplings left.',
          grammar: ['masu-past:困りました', 'masen:ありません'] },
        { jp: '鬼が島[おにがしま] に 着[つ]く と 、 鬼[おに] が 言[い]いました>言う 。', en: 'When they reached Ogre Island, an ogre said:',
          grammar: ['to-conditional:着くと'] },
        { jp: '「 うち で は 、 きびだんご は 毎日[まいにち] 食[た]べ放題[ほうだい] です よ 。 」', en: '"At our place, it\'s all-you-can-eat dumplings every day!"',
          grammar: ['yo:ですよ', 'de-place:うちでは'] },
        { jp: '犬[いぬ] と サル と キジ は 、 鬼[おに] の 仲間[なかま] に なりました>なる 。', en: 'The dog, the monkey and the pheasant joined the ogres.',
          grammar: ['to-and:犬とサルとキジ', 'ni-naru:仲間になりました'] },
      ],
    },

    // ── N4 ──────────────────────────────────────────────────────────────────
    {
      id: 'meme-n4-kotatsu', level: 'n4', size: 'long', kind: 'aruaru', emoji: '🍊🐈',
      title: 'こたつから出[で]られない', titleEn: 'Trapped in the Kotatsu',
      punch: 'A こたつ is a low table with a heater underneath and a quilt draped over it — the coziest object in Japan and the enemy of productivity. "こたつから出られない" is a winter-long あるある: whoever gets up gets sent on errands (ついでに… "while you\'re at it…"), mandarins (みかん) are the official kotatsu snack, and as the children\'s song says, 猫はこたつで丸くなる — the cat curls up in the kotatsu.',
      sentences: [
        { jp: '冬[ふゆ] に なる と 、 うち の 居間[いま] に は こたつ が 出[で]る 。', en: 'When winter comes, the kotatsu comes out in our living room.',
          grammar: ['to-conditional:なると', 'ni-wa:居間には'] },
        { jp: 'こたつ は 、 下[した] に ヒーター が ある 、 布団[ふとん] を かけた>かける テーブル だ 。', en: 'A kotatsu is a low table with a heater underneath and a quilt over it.',
          grammar: ['relative-clause:布団をかけたテーブル'] },
        { jp: '一度[いちど] 入[はい]る と 、 もう 出[で]られない>出る 。', en: 'Once you\'re in, you can\'t get out.',
          grammar: ['to-conditional:入ると', 'potential:出られない'] },
        { jp: '「 お茶[ちゃ] 、 取[と]って>取る きて>くる 。 」 「 自分[じぶん] で 行[い]って>行く よ 。 」', en: '"Go and get me some tea." "Get it yourself."',
          grammar: ['te-kuru:取ってきて', 'te-request:取ってきて'] },
        { jp: '家族[かぞく] は みんな 、 だれ>誰 が 先[さき] に 出[で]る か 、 じっと 待[ま]って>待つ いる 。', en: 'The whole family sits tight, waiting to see who will get out first.',
          grammar: ['embedded-question:だれが先に出るか', 'te-iru:待っている'] },
        { jp: '結局[けっきょく] 、 トイレ に 行[い]きたく>行く なった>なる 父[ちち] が 負[ま]ける 。', en: 'In the end, Dad needs the toilet and loses.',
          grammar: ['tai:行きたく', 'ku-naru:行きたくなった'] },
        { jp: '「 ついでに 、 みかん も 持[も]って>持つ きて>くる ！ 」 と 、 みんな が 言[い]う 。', en: '"While you\'re up, bring some mandarins!" everyone says.',
          grammar: ['tsuide-ni:ついでに', 'te-kuru:持ってきて'] },
        { jp: '猫[ねこ] だけ は 、 朝[あさ] まで こたつ の 中[なか] で 寝[ね]て>寝る いる 。', en: 'Only the cat stays asleep inside the kotatsu until morning.',
          grammar: ['dake:猫だけ', 'made:朝まで', 'te-iru:寝ている'] },
      ],
    },
    {
      id: 'meme-n4-tsuru', level: 'n4', size: 'long', kind: 'story', emoji: '🕊️📱',
      title: '鶴[つる]の恩返[おんがえ]し（スマホ版[ばん]）', titleEn: 'The Crane\'s Secret (Smartphone Edition)',
      punch: 'In the folk tale 鶴の恩返し ("The Crane Returns a Favour"), a rescued crane becomes a woman and secretly weaves gorgeous cloth from her own feathers; when the old man breaks his promise and peeks, she has to fly away forever. のぞかないでください ("please don\'t peek") is the famous line — here the secret is rather less tragic.',
      sentences: [
        { jp: '昔[むかし] 、 おじいさん が わな に かかった>かかる 鶴[つる] を 助[たす]けました>助ける 。', en: 'Long ago, an old man freed a crane caught in a trap.',
          grammar: ['relative-clause:わなにかかった鶴', 'masu-past:助けました'] },
        { jp: 'その 夜[よる] 、 きれい な 娘[むすめ] が 家[いえ] に 来[き]ました>来る 。', en: 'That night, a beautiful young woman came to his house.',
          grammar: ['na-adj-noun:きれいな娘'] },
        { jp: '「 部屋[へや] で 機[はた] を 織[お]ります>織る 。 でも 、 絶対[ぜったい] に のぞかないで>のぞく ください 。 」', en: '"I\'ll weave cloth in the back room. But you must never peek."',
          grammar: ['naide-kudasai:のぞかないでください', 'de-place:部屋で'] },
        { jp: '毎晩[まいばん] 、 部屋[へや] から 「 カタン 、 カタン 」 と いう>言う 音[おと] が 聞[き]こえました>聞こえる 。', en: 'Every night, a clack-clack sound came from the room.',
          grammar: ['to-iu:」という音', 'kara-from:部屋から'] },
        { jp: 'おじいさん は 、 どうしても 見[み]たく>見る なって>なる 、 そっと のぞいて>のぞく しまいました>しまう 。', en: 'The old man simply had to look, and quietly peeked.',
          grammar: ['ku-naru:見たくなって', 'te-shimau:のぞいてしまいました'] },
        { jp: '中[なか] で は 、 鶴[つる] が スマホ で ゲーム を して>する いました>いる 。', en: 'Inside, the crane was playing a game on her smartphone.',
          grammar: ['de-means:スマホで', 'te-iru:していました'] },
        { jp: '「 カタン 、 カタン 」 は 、 ボタン を 押[お]す 音[おと] だった>だ の>の(explain) だ 。', en: 'The clack-clack was the sound of her jabbing the buttons.',
          grammar: ['relative-clause:ボタンを押す音'] },
        { jp: '鶴[つる] 「 見[み]られた>見る なら 、 しかたない 。 … あと 五分[ごふん] だけ 。 ボス 戦[せん] な の>の(explain) 。 」', en: 'The crane: "Well, since you\'ve seen me… Just five more minutes. It\'s a boss fight."',
          grammar: ['passive:見られた', 'nara:見られたなら', 'dake:五分だけ'] },
      ],
    },
    {
      id: 'meme-n4-kantokansai', level: 'n4', size: 'long', kind: 'aruaru', emoji: '🗼🏯',
      title: '関東[かんとう]と関西[かんさい]', titleEn: 'Tokyo vs Osaka',
      punch: 'Japan\'s friendly East–West rivalry: Kantō (Tokyo) vs Kansai (Osaka, Kyoto). Escalator sides, マック vs マクド, square vs round mochi, and the insult swap — アホ is affectionate in Osaka but harsh in Tokyo, and バカ the other way round. Even the electricity differs: 50 Hz in the east, 60 Hz in the west.',
      sentences: [
        { jp: '日本[にほん] の 東[ひがし] と 西[にし] で は 、 いろいろ>いろいろ(na) な こと が 違[ちが]う 。', en: 'Lots of things are different in eastern and western Japan.',
          grammar: ['na-adj-noun:いろいろなこと', 'to-and:東と西'] },
        { jp: '例[たと]えば 、 エスカレーター で 、 東京[とうきょう] の 人[ひと] は 左[ひだり] に 立[た]つ が 、 大阪[おおさか] の 人[ひと] は 右[みぎ] に 立[た]つ 。', en: 'On escalators, for example, people in Tokyo stand on the left, but people in Osaka stand on the right.',
          grammar: ['ga-but:立つが', 'wa-contrast:大阪の人は'] },
        { jp: 'マクドナルド は 、 東京[とうきょう] で は 「 マック 」 、 大阪[おおさか] で は 「 マクド 」 と 呼[よ]ばれる>呼ぶ 。', en: 'McDonald\'s is "Makku" in Tokyo and "Makudo" in Osaka.',
          grammar: ['passive:呼ばれる', 'wa-contrast:大阪では'] },
        { jp: '大阪[おおさか] で は 「 アホ 」 は 軽[かる]い 冗談[じょうだん] だ が 、 「 バカ 」 と 言[い]われる>言う と 本気[ほんき] で 怒[おこ]る 人[ひと] が 多[おお]い 。', en: 'In Osaka, "aho" (idiot) is a light tease — but lots of people get genuinely angry if you call them "baka".',
          grammar: ['ga-but:冗談だが', 'passive:言われる', 'to-conditional:言われると'] },
        { jp: '東京[とうきょう] で は 、 その 逆[ぎゃく] だ 。', en: 'In Tokyo, it\'s the other way round.',
          grammar: ['de-place:東京では'] },
        { jp: 'お正月[しょうがつ] の お餅[もち] も 、 東[ひがし] は 四角[しかく] 、 西[にし] は 丸[まる] だ 。', en: 'Even the New Year mochi: square in the east, round in the west.',
          grammar: ['mo-also:お餅も', 'wa-contrast:西は'] },
        { jp: 'どっち が 正[ただ]しい か で けんか を する と 、 一日[いちにち] で は 終[お]わらない>終わる 。', en: 'Start an argument about which side is right, and it won\'t be over in a day.',
          grammar: ['embedded-question:どっちが正しいか', 'to-conditional:すると'] },
      ],
    },

    // ── N3 ──────────────────────────────────────────────────────────────────
    {
      id: 'meme-n3-isekai', level: 'n3', size: 'long', kind: 'pop', emoji: '🚚✨',
      title: '異世界[いせかい]転生[てんせい]とトラック', titleEn: 'Isekai and the Truck',
      punch: '異世界転生 ("reincarnated in another world") is the biggest anime and light-novel trend of the last decade-plus. The cliché opening — death by truck — turned トラック into a meme ("Truck-kun", トラックさん), and titles turned into full-sentence summaries: 転生したらスライムだった件 ("That Time I Got Reincarnated as a Slime") is a real hit. 件 (けん) here means "the matter of…" — "the one where…".',
      sentences: [
        { jp: '最近[さいきん] の アニメ や ライトノベル で は 、 「 異世界[いせかい] 転生[てんせい] 」 が 大人気[だいにんき] だ 。', en: 'In recent anime and light novels, "isekai reincarnation" is hugely popular.',
          grammar: ['ya-and:アニメやライトノベル', 'ga-subject:」が大人気'] },
        { jp: '主人公[しゅじんこう] は たいてい 、 普通[ふつう] の 会社員[かいしゃいん] か 高校生[こうこうせい] だ 。', en: 'The hero is usually an ordinary office worker or high-school student.',
          grammar: ['no-possessive:普通の会社員'] },
        { jp: 'ある>ある(certain) 日[ひ] 、 道[みち] で トラック に はねられて>はねる 死[し]んで>死ぬ しまう 。', en: 'One day, he gets hit by a truck and dies.',
          grammar: ['passive:はねられて', 'te-shimau:死んでしまう'] },
        { jp: '目[め] を 覚[さ]ます と 、 そこ は 剣[けん] と 魔法[まほう] の 世界[せかい] だった>だ 。', en: 'When he wakes up, he\'s in a world of swords and magic.',
          grammar: ['to-conditional:覚ますと', 'to-and:剣と魔法'] },
        { jp: 'しかも 、 なぜか 最強[さいきょう] の 力[ちから] を 持[も]って>持つ いる 。', en: 'What\'s more, for some reason, he has the strongest powers in the land.',
          grammar: ['te-iru:持っている'] },
        { jp: 'あまりに たくさん の 主人公[しゅじんこう] を 異世界[いせかい] に 送[おく]った>送る ので 、 ネット で は トラック が 「 トラックさん 」 と 呼[よ]ばれて>呼ぶ いる 。', en: 'Trucks have sent so many heroes to other worlds that online they\'re called "Mr. Truck".',
          grammar: ['node:送ったので', 'passive:呼ばれている'] },
        { jp: 'タイトル も どんどん 長[なが]く>長い なって>なる いる 。', en: 'The titles keep getting longer, too.',
          grammar: ['ku-naru:長くなって', 'te-iru:なっている'] },
        { jp: '例[たと]えば 、 「 トラック に はねられたら>はねる 異世界[いせかい] で スライム に なって>なる いた>いる 件[けん] 」 みたい な 感[かん]じ だ 。', en: 'Something like "That Time I Got Hit by a Truck and Woke Up as a Slime in Another World".',
          grammar: ['tara:はねられたら', 'mitai:みたいな'] },
      ],
    },
    {
      id: 'meme-n3-taishoku', level: 'n3', size: 'long', kind: 'story', emoji: '💼📞',
      title: '退職[たいしょく]代行[だいこう]', titleEn: 'Quitting by Proxy',
      punch: '退職代行 ("resignation by proxy") services boomed in Japan in the late 2010s: for a fee, an agent phones your employer and quits for you, so you never have to face your boss. They say a lot about how hard it can be to say no in a Japanese workplace — and, as the boss discovers, it isn\'t only the juniors who want out.',
      sentences: [
        { jp: '佐藤[さとう]さん は 、 会社[かいしゃ] を 辞[や]めたい>辞める と 思[おも]って>思う いた>いる 。', en: 'Satō had been wanting to quit his job.',
          grammar: ['tai:辞めたい', 'to-omou:辞めたいと思って'] },
        { jp: 'でも 、 怖[こわ]い 部長[ぶちょう] に 言[い]い出[だ]せない>言い出す 。', en: 'But he couldn\'t bring himself to tell his scary boss.',
          grammar: ['potential:言い出せない', 'i-adj-noun:怖い部長'] },
        { jp: 'そこで 、 「 退職[たいしょく] 代行[だいこう] 」 に 電話[でんわ] を した>する 。', en: 'So he called a "resignation agency".',
          grammar: ['plain-form:電話をした'] },
        { jp: 'お金[かね] を 払[はら]う と 、 本人[ほんにん] の 代[か]わり に 会社[かいしゃ] に 「 辞[や]めます>辞める 」 と 伝[つた]えて>伝える くれる サービス だ 。', en: 'It\'s a service that, for a fee, tells your company "they\'re quitting" on your behalf.',
          grammar: ['kawari-ni:本人の代わりに', 'te-kureru:伝えてくれる', 'to-conditional:払うと'] },
        { jp: '次[つぎ] の 朝[あさ] 、 部長[ぶちょう] の 電話[でんわ] が 鳴[な]った>鳴る 。', en: 'The next morning, the boss\'s phone rang.',
          grammar: ['no-possessive:部長の電話'] },
        { jp: '「 佐藤[さとう]さん の 代理[だいり] の 者[もの] です が 、 佐藤[さとう]さん は 本日[ほんじつ] で 退職[たいしょく] されます>する 。 」', en: '"I\'m calling on behalf of Mr. Satō. As of today, Mr. Satō is resigning."',
          grammar: ['ga-but:者ですが', 'sonkeigo:退職されます'] },
        { jp: '部長[ぶちょう] は 黙[だま]って>黙る 電話[でんわ] を 切[き]る と 、 自分[じぶん] の スマホ で 検索[けんさく] を 始[はじ]めた>始める 。', en: 'The boss silently hung up — and started searching on his own phone.',
          grammar: ['te-sequence:黙って', 'to-conditional:切ると'] },
        { jp: '「 退職[たいしょく] 代行[だいこう] 、 部長[ぶちょう] も 使[つか]える>使う か な>な(feeling) … 」', en: '"Resignation agencies… I wonder if bosses can use them too…"',
          grammar: ['potential:使える', 'kana:かな'] },
      ],
    },
    {
      id: 'meme-n3-kotowaza', level: 'n3', size: 'long', kind: 'kotowaza', emoji: '📜🐒',
      title: 'ことわざ、ちょっと変[か]えてみた', titleEn: 'Proverbs, Slightly Updated',
      punch: 'ことわざ are proverbs, very often starring animals: 猿も木から落ちる (even monkeys fall from trees — "nobody\'s perfect"), 猫に小判 (gold coins to a cat — "pearls before swine"), and 花より団子 (dumplings over blossoms — "substance over style"), which is exactly what most お花見 parties turn into. Twisting them into modern jokes is a national hobby.',
      sentences: [
        { jp: 'ことわざ は 、 昔[むかし] から 伝[つた]わる 短[みじか]い 知恵[ちえ] の 言葉[ことば] だ 。', en: 'Kotowaza are short sayings of wisdom passed down from long ago.',
          grammar: ['kara-from:昔から', 'relative-clause:昔から伝わる短い知恵の言葉'] },
        { jp: '「 猿[さる] も 木[き] から 落[お]ちる 」 は 、 名人[めいじん] でも>でも(even) 失敗[しっぱい] する こと が ある と いう>言う 意味[いみ] だ 。', en: '"Even monkeys fall from trees" means even experts make mistakes sometimes.',
          grammar: ['demo-even:名人でも', 'koto-ga-aru-sometimes:失敗することがある', 'to-iu:という意味'] },
        { jp: '現代[げんだい] 版[ばん] なら 、 「 プログラマー も バグ を 出[だ]す 」 だろう か 。', en: 'The modern version: "Even programmers write bugs."',
          grammar: ['nara:版なら', 'deshou:だろうか'] },
        { jp: '「 猫[ねこ] に 小判[こばん] 」 は 、 価値[かち] の わからない>わかる 人[ひと] に いい もの を あげて>あげる も 無駄[むだ] だ と いう>言う 意味[いみ] 。', en: '"Gold coins to a cat" means there\'s no point giving something precious to someone who can\'t appreciate it.',
          grammar: ['te-mo:あげても', 'relative-clause:価値のわからない人'] },
        { jp: 'でも 、 今[いま] の 猫[ねこ] は 、 小判[こばん] より 段[だん]ボール の 箱[はこ] の 方[ほう] が 好[す]き だ 。', en: 'But today\'s cats would rather have the cardboard box than the coins.',
          grammar: ['yori:小判より', 'hou-ga:箱の方が好き'] },
        { jp: '「 花[はな] より 団子[だんご] 」 は 、 きれい な もの より 、 実際[じっさい] に 役[やく] に 立[た]つ もの を 選[えら]ぶ こと 。', en: '"Dumplings over blossoms" means choosing what\'s actually useful over what\'s pretty.',
          grammar: ['yori:きれいなものより', 'koto-nominalizer:選ぶこと'] },
        { jp: 'お花見[はなみ] に 行[い]って>行く も 、 桜[さくら] を 見[み]ないで>見る ずっと 食[た]べて>食べる いる 人[ひと] は 、 まさに これ だ 。', en: 'People who go to a cherry-blossom party and spend the whole time eating without looking at the trees are living proof.',
          grammar: ['te-mo:行っても', 'naide-without:見ないで', 'te-iru:食べている'] },
        { jp: 'ちなみに 、 筆者[ひっしゃ] も 去年[きょねん] の お花見[はなみ] で 、 桜[さくら] の 写真[しゃしん] を 一枚[いちまい] も 撮[と]らなかった>撮る 。', en: 'By the way, at last year\'s hanami, this writer didn\'t take a single photo of the blossoms either.',
          grammar: ['counters:一枚', 'mo-also:筆者も'] },
      ],
    },
  ];

  const memes = global.MEMES_DATA || (global.MEMES_DATA = []);
  memes.push(...SHORT, ...LONG);

  const glossary = global.STORY_GLOSSARY || (global.STORY_GLOSSARY = {});
  Object.keys(global.MEME_GLOSSARY_2).forEach(key => {
    if (!Object.prototype.hasOwnProperty.call(glossary, key)) glossary[key] = global.MEME_GLOSSARY_2[key];
  });
  const grammar = global.STORY_GRAMMAR || (global.STORY_GRAMMAR = {});
  Object.keys(global.MEME_GRAMMAR_2).forEach(id => {
    if (!Object.prototype.hasOwnProperty.call(grammar, id)) grammar[id] = global.MEME_GRAMMAR_2[id];
  });
})(window);
