(function (global) {
  'use strict';

  // Memes, jokes and pop culture for the Memes & Jokes page (memes.html),
  // grouped by JLPT level. Same format as stories-data.js — and read by the
  // same reader — with three extras per item:
  //
  //   kind   — 'dajare' | 'slang' | 'pop' | 'story' | 'riddle' | 'senryu' | 'meme'
  //   emoji  — shown big on the card, like the meme's picture
  //   punch  — "Why it's funny": the pun, the reference or the culture behind it
  //
  // Words and grammar the stories don't already cover live in MEME_GLOSSARY
  // and MEME_GRAMMAR below and are merged into STORY_GLOSSARY / STORY_GRAMMAR,
  // so the reader, the flashcards and the tests treat them like any other.
  // test_memes.js checks every token, grammar id and snippet.

  global.MEME_GRAMMAR = {
    'ni-mieru': { level: 'N4', title: '〜に見える — "looks like"', pattern: 'Noun に見える', note: 'How something appears: 草に見える "looks like grass". With an adjective: おいしく見える "looks tasty".' },
    'to-quote': { level: 'N5', title: 'と — quoting', pattern: '「…」と言う / 書く / 呼ぶ', note: 'Marks the exact words someone says, writes or calls something. Casual speech often uses って instead.' },
    'nau': { level: 'N3', title: '〜なう — "(at) … now" (net slang)', pattern: 'Noun + なう', note: 'English "now" in hiragana, tacked onto a place or activity in a social-media post: 渋谷なう "in Shibuya right now". Playful and a little retro.' },
    'ee-slur': { level: 'N3', title: '〜えー — rough casual い-adjective', pattern: '〜ai / 〜oi / 〜ui → 〜ee', note: 'In rough, drawled speech an い-adjective\'s last two vowels melt into a long え: からい → かれー, すごい → すげー, うまい → うめー, いたい → いてー. Very casual and mostly masculine.' },
    'cha-dame': { level: 'N3', title: '〜ちゃダメ — mustn\'t (casual)', pattern: 'Verb て-form → 〜ちゃ / 〜じゃ + ダメ', note: '〜ちゃ is the spoken contraction of 〜ては (〜じゃ for 〜では): 逃げちゃダメ = 逃げてはダメ "you mustn\'t run away". Same meaning as 〜てはいけない, but casual.' },
    'kansai-de': { level: 'N3', title: 'で — Kansai sentence ending', pattern: 'Sentence + で', note: 'In Kansai dialect a sentence-final で works like standard よ: うまいで "it\'s tasty, I tell you". Other Kansai staples: 知らん (= 知らない), あかん (= だめ), ほんま (= 本当).' },
    'shiran-kedo': { level: 'N3', title: '知らんけど — "not that I know, though"', pattern: 'Statement + 知らんけど', note: 'Kansai tag added after a confident statement to take the responsibility out of it: "don\'t quote me". 知らん is Kansai for 知らない.' },
    'dai-question': { level: 'N3', title: '〜だい — old-fashioned casual question', pattern: 'Question word + だい', note: 'だ + い: a friendly, old-fashioned (often masculine) question ending used with question words: 何時だい？ "what time is it?", どうしたんだい？ "what\'s up?".' },
    'beki-kara-zu': { level: 'N2', title: '〜べからず — must not (classical)', pattern: 'Dictionary form + べからず', note: 'Classical Japanese for "must not ~", still seen on old-style signs: 入るべからず "keep out". The modern spoken equivalent is 〜てはいけない.' },
    'de-wa-naku': { level: 'N3', title: '〜ではなく — not A but B', pattern: 'A ではなく B', note: 'Rejects one thing in favour of another: 端ではなく真ん中 "not the edge, but the middle".' },
  };

  global.MEME_GLOSSARY = {
    // Words, slang and names not already in the stories' glossary.
    'ダジャレ': ['だじゃれ', 'pun, play on words (often a corny one)', 'noun'],
    '吹っ飛ぶ': ['ふっとぶ', 'to be blown away, to go flying', 'う-verb'],
    'ふっとんだ': ['ふっとんだ', '"blew away" — past of 吹っ飛ぶ, written in kana to show the pun', 'う-verb (past)'],
    'イクラ': ['いくら', 'salmon roe (the orange beads on sushi)', 'noun'],
    'いくらでも': ['いくらでも', 'any amount, as much as you like', 'adverb'],
    'カエル': ['かえる', 'frog (蛙)', 'noun'],
    'ジョーク': ['じょーく', 'joke', 'noun'],
    'w': ['だぶりゅー', '"lol" — the w of 笑い (warai, laughing)', 'internet slang'],
    'wwwww': ['だぶりゅーだぶりゅー…', '"lololol" — a field of w\'s, which looks like grass', 'internet slang'],
    '草(slang)': ['くさ', 'grass; (net slang) "lol", because wwwww looks like grass', 'noun'],
    '大草原': ['だいそうげん', 'vast prairie; (net slang) "dying of laughter", a huge field of 草', 'noun'],
    '田中くん': ['たなかくん', 'Tanaka (〜くん: for boys and younger men)', 'name'],
    'え': ['え', 'eh? huh? (surprise)', 'interjection'],
    'ぼく': ['ぼく', 'I, me (used by boys and men; softer than 俺)', 'pronoun'],
    'なう': ['なう', '"now" — net slang from English, added after a place or activity', 'internet slang'],
    'ナウ': ['なう', 'English "now", in katakana', 'loanword'],
    'ツイッター': ['ついったー', 'Twitter (now X)', 'noun'],
    'あまい': ['あまい', 'sweet (taste)', 'い-adjective'],
    'ピカチュウ': ['ぴかちゅう', 'Pikachu (from ピカ "flash" + チュウ "squeak")', 'name'],
    'ポケモン': ['ぽけもん', 'Pokémon (short for ポケットモンスター, "pocket monsters")', 'name'],
    'キャラクター': ['きゃらくたー', 'character (in a story, game or anime)', 'noun'],
    'ピカ': ['ぴか', 'flash! — the sound of something sparkling (ピカピカ, ピカッ)', 'onomatopoeia'],
    'ピカッ': ['ぴかっ', 'with a sudden flash', 'onomatopoeia'],
    'チュウ': ['ちゅう', 'squeak (the sound a mouse makes)', 'onomatopoeia'],
    'ネズミ': ['ねずみ', 'mouse, rat', 'noun'],
    'ドラえもん': ['どらえもん', 'Doraemon, the earless robot cat from the future', 'name'],
    'ネコ型': ['ねこがた', 'cat-type, cat-shaped (〜型: type, model)', 'noun'],
    '大きらい': ['だいきらい', 'hate, really dislike', 'な-adjective'],
    'どら焼き': ['どらやき', 'dorayaki — two small pancakes filled with sweet red bean paste', 'noun'],
    '寝ころぶ': ['ねころぶ', 'to lie down, to flop down (寝転ぶ)', 'う-verb'],
    '十四時間': ['じゅうよじかん', 'fourteen hours', 'noun'],
    'そういう': ['そういう', 'that kind of, such', 'pre-noun'],
    'ソファ': ['そふぁ', 'sofa', 'noun'],

    // N4
    'かたい': ['かたい', 'hard, stiff', 'い-adjective'],
    'ジャパン': ['じゃぱん', 'Japan (in English)', 'noun'],
    '一休さん': ['いっきゅうさん', 'Ikkyū, a witty Zen monk (1394–1481) of folk tales', 'name'],
    'お坊さん': ['おぼうさん', 'Buddhist monk, priest', 'noun'],
    'お殿様': ['おとのさま', 'feudal lord', 'noun'],
    'よぶ': ['よぶ', 'to call, to summon (呼ぶ)', 'う-verb'],
    'わたる': ['わたる', 'to cross (a bridge, a road) (渡る)', 'う-verb'],
    '平気': ['へいき', 'calm, unbothered, fine', 'な-adjective'],
    'こら': ['こら', 'hey! (scolding)', 'interjection'],
    'ではなく': ['ではなく', 'not … (but rather)', 'expression'],
    'リア充': ['りあじゅう', 'someone with a happy real-life (offline) life — リアル + 充実', 'internet slang'],
    'リアル': ['りある', 'real; real life (as opposed to online)', 'noun'],
    '充実する': ['じゅうじつする', 'to be full, fulfilling, rich', 'する-verb'],
    '恋人': ['こいびと', 'boyfriend / girlfriend, partner', 'noun'],
    'クリスマス': ['くりすます', 'Christmas', 'noun'],
    '爆発する': ['ばくはつする', 'to explode', 'する-verb'],
    'うらやましい': ['うらやましい', 'envious, jealous; enviable', 'い-adjective'],
    '冗談': ['じょうだん', 'joke', 'noun'],
    'やばい': ['やばい', 'risky, bad ("uh-oh"); (slang) amazing, awesome', 'い-adjective'],
    'もともと': ['もともと', 'originally, from the start', 'adverb'],
    'あぶない': ['あぶない', 'dangerous', 'い-adjective'],
    'すごく': ['すごく', 'really, terribly (すごい → adverb)', 'adverb'],
    '推し': ['おし', 'your favourite (idol, character, member) — the one you "push"', 'noun'],
    '推す': ['おす', 'to push for, to support, to recommend', 'う-verb'],
    '応援する': ['おうえんする', 'to cheer for, to support', 'する-verb'],
    'アイドル': ['あいどる', 'idol (pop star)', 'noun'],
    'グッズ': ['ぐっず', 'merch, goods', 'noun'],
    'ファン': ['ふぁん', 'fan', 'noun'],
    '尊い': ['とうとい', 'precious, sacred; (fan slang) "too wonderful"', 'い-adjective'],
    '名言': ['めいげん', 'famous saying, great quote', 'noun'],
    'カレー': ['かれー', 'curry', 'noun'],
    'かれー': ['かれー', 'rough, drawled からい: "hot, spicy"', 'い-adjective (casual)'],
    'つまらない': ['つまらない', 'boring, dull, lame', 'い-adjective'],
    'トムさん': ['とむさん', 'Tom', 'name'],
    '飲み会': ['のみかい', 'drinking party, a night out with colleagues', 'noun'],
    'たつ': ['たつ', 'to pass (time) (経つ)', 'う-verb'],
    'ポスト': ['ぽすと', 'mailbox, postbox', 'noun'],
    'あたりたがたとう': ['ありがとう', 'たぬき code: remove every た and it says ありがとう', 'riddle'],
    'たぬき': ['たぬき', 'tanuki, raccoon dog — a trickster in folk tales; sounds like た抜き "ta removed"', 'noun'],
    '描く': ['かく', 'to draw, to paint', 'う-verb'],
    'た(kana)': ['た', 'the kana た', 'kana'],
    '抜く': ['ぬく', 'to pull out, to remove, to leave out', 'う-verb'],
    '北斗の拳': ['ほくとのけん', 'Fist of the North Star, a 1980s martial-arts manga', 'name'],
    '八十年代': ['はちじゅうねんだい', 'the (19)80s', 'noun'],
    'マンガ': ['まんが', 'manga, comics', 'noun'],
    'ケンシロウ': ['けんしろう', 'Kenshiro, hero of 北斗の拳', 'name'],
    '敵': ['てき', 'enemy', 'noun'],
    '突く': ['つく', 'to jab, to poke, to strike', 'う-verb'],
    'なに': ['なに', 'what?!', 'interjection'],
    'セリフ': ['せりふ', 'line (in a play, film or manga), catchphrase', 'noun'],
    '川柳': ['せんりゅう', 'senryū — a funny 5-7-5 poem about everyday life', 'noun'],
    '俳句': ['はいく', 'haiku', 'noun'],
    '五七五': ['ごしちご', 'five-seven-five (the syllable pattern of haiku and senryū)', 'noun'],
    '詩': ['し', 'poem', 'noun'],
    '季語': ['きご', 'season word (a word that places a haiku in a season)', 'noun'],
    '明日(あす)': ['あす', 'tomorrow (formal / poetic reading of 明日)', 'noun'],
    '十年目': ['じゅうねんめ', 'the tenth year', 'noun'],
    'メガネ': ['めがね', 'glasses, spectacles', 'noun'],
    'のる': ['のる', 'to be on top of, to sit on (乗る)', 'う-verb'],
    'ただいま': ['ただいま', '"I\'m home!"', 'expression'],
    '疲れる': ['つかれる', 'to get tired', 'ichidan verb'],

    // N3
    '自信': ['じしん', 'confidence', 'noun'],
    'たっぷり': ['たっぷり', 'plenty, full of', 'adverb'],
    '知らん': ['しらん', 'Kansai / casual for 知らない: don\'t know', 'verb (negative)'],
    '付け加える': ['つけくわえる', 'to add (on), to tack on', 'ichidan verb'],
    '日本一': ['にっぽんいち', 'the best in Japan', 'noun'],
    'うまい': ['うまい', 'tasty, delicious (casual); skilful', 'い-adjective'],
    'で(Kansai)': ['で', '(Kansai) sentence ending = よ: "I tell you"', 'particle'],
    '責任': ['せきにん', 'responsibility', 'noun'],
    '2022年': ['にせんにじゅうにねん', 'the year 2022', 'noun'],
    '流行語大賞': ['りゅうこうごたいしょう', 'the buzzword-of-the-year awards', 'noun'],
    'トップテン': ['とっぷてん', 'top ten', 'noun'],
    'デスノート': ['ですのーと', 'Death Note, a manga about a notebook that kills', 'name'],
    '夜神月': ['やがみらいと', 'Light Yagami, hero of Death Note (月 "moon", read ライト)', 'name'],
    '計画': ['けいかく', 'plan', 'noun'],
    'うまくいく': ['うまくいく', 'to go well, to work out', 'expression'],
    '計画通り': ['けいかくどおり', 'according to plan, just as planned', 'expression'],
    '寝坊する': ['ねぼうする', 'to oversleep', 'する-verb'],
    '遅刻する': ['ちこくする', 'to be late', 'する-verb'],
    '計画する': ['けいかくする', 'to plan', 'する-verb'],
    'バスケットボール': ['ばすけっとぼーる', 'basketball', 'noun'],
    'スラムダンク': ['すらむだんく', 'Slam Dunk, a 1990s basketball manga', 'name'],
    '安西先生': ['あんざいせんせい', 'Coach Anzai of Slam Dunk', 'name'],
    '監督': ['かんとく', 'coach, manager; (film) director', 'noun'],
    '試合': ['しあい', 'match, game', 'noun'],
    'あきらめる': ['あきらめる', 'to give up (諦める)', 'ichidan verb'],
    '終了': ['しゅうりょう', 'end, finish, over', 'noun'],
    'レポート': ['れぽーと', 'report, paper', 'noun'],
    '一杯': ['いっぱい', 'a cup, a glass (of)', 'noun'],
    'エヴァンゲリオン': ['えゔぁんげりおん', 'Neon Genesis Evangelion, a 1995 mecha anime', 'name'],
    'シンジくん': ['しんじくん', 'Shinji Ikari, the reluctant hero of Evangelion', 'name'],
    '巨大': ['きょだい', 'giant, huge', 'な-adjective'],
    '言い聞かせる': ['いいきかせる', 'to tell (yourself / someone) firmly', 'ichidan verb'],
    'ダメ': ['だめ', 'no good, not allowed (だめ)', 'な-adjective'],
    'ちなみに': ['ちなみに', 'by the way, incidentally', 'conjunction'],
    'ちゃ': ['ちゃ', 'spoken contraction of ては', 'particle'],
    'ては': ['ては', 'て-form + は (〜てはいけない: must not)', 'particle'],
    '死亡': ['しぼう', 'death (formal)', 'noun'],
    'フラグ': ['ふらぐ', 'flag; (slang) a line that sets up what happens next', 'noun'],
    '戦い': ['たたかい', 'battle, fight', 'noun'],
    '俺': ['おれ', 'I, me (masculine, casual)', 'pronoun'],
    '任せる': ['まかせる', 'to leave (something) to someone', 'ichidan verb'],
    '倒す': ['たおす', 'to defeat, to knock down', 'う-verb'],
    'だいたい': ['だいたい', 'usually, mostly; roughly', 'adverb'],
    'オタク': ['おたく', 'otaku, geek, superfan', 'noun'],
    '告白する': ['こくはくする', 'to confess (your love)', 'する-verb'],
    '立てる': ['たてる', 'to stand up, to raise (a flag)', 'ichidan verb'],
    '中二病': ['ちゅうにびょう', '"8th-grader syndrome" — acting like you have secret dark powers', 'noun'],
    '言動': ['げんどう', 'words and actions, behaviour', 'noun'],
    '包帯': ['ほうたい', 'bandage', 'noun'],
    '右手': ['みぎて', 'right hand', 'noun'],
    'くっ': ['くっ', 'ngh! (a grunt of pain or frustration)', 'interjection'],
    'うずく': ['うずく', 'to throb, to ache', 'う-verb'],
    '闇': ['やみ', 'darkness', 'noun'],
    '力': ['ちから', 'power, strength', 'noun'],
    '本気': ['ほんき', 'serious, for real', 'noun'],
    '大人': ['おとな', 'adult, grown-up', 'noun'],
    '必殺技': ['ひっさつわざ', 'special move, finishing move', 'noun'],
    '社畜': ['しゃちく', '"company livestock" — a worker totally tamed by their company', 'noun'],
    '家畜': ['かちく', 'livestock, farm animals', 'noun'],
    '満員電車': ['まんいんでんしゃ', 'packed (rush-hour) train', 'noun'],
    '押し込む': ['おしこむ', 'to push in, to cram in', 'う-verb'],
    '十一時': ['じゅういちじ', 'eleven o\'clock', 'noun'],
    'メール': ['めーる', 'email, message', 'noun'],
    'じゃ(neg)': ['じゃ', 'casual では, in じゃない: "is not"', 'particle'],
    '空気': ['くうき', 'air; the mood of a room', 'noun'],
    '場': ['ば', 'place, occasion; (その場) the situation at hand', 'noun'],
    '雰囲気': ['ふんいき', 'atmosphere, mood', 'noun'],
    'KY': ['けーわい', '"can\'t read the air" — 空気 (Kuuki) 読めない (Yomenai)', 'slang'],
    'K': ['けー', 'the letter K', 'letter'],
    'Y': ['わい', 'the letter Y', 'letter'],
    '頭文字': ['かしらもじ', 'initial (letter)', 'noun'],
    '会議': ['かいぎ', 'meeting', 'noun'],
    '質問': ['しつもん', 'question', 'noun'],
    '挙げる': ['あげる', 'to raise (a hand)', 'ichidan verb'],
    'たいてい': ['たいてい', 'usually, in most cases', 'adverb'],
    '逆': ['ぎゃく', 'opposite, reverse (逆に: on the other hand)', 'noun'],
    'すぎ(too)': ['すぎ', 'too much (noun form of すぎる)', 'suffix'],
    '落語': ['らくご', 'rakugo — traditional comic storytelling', 'noun'],
    '話し手': ['はなして', 'speaker, storyteller', 'noun'],
    '扇子': ['せんす', 'folding fan', 'noun'],
    '手ぬぐい': ['てぬぐい', 'thin cotton hand towel', 'noun'],
    '演じる': ['えんじる', 'to perform, to act', 'ichidan verb'],
    '笑い話': ['わらいばなし', 'funny story', 'noun'],
    '四つ': ['よっつ', 'four (things); (Edo time) the 4th hour, about 10 p.m.', 'noun'],
    '五つ': ['いつつ', 'five (things)', 'noun'],
    '六つ': ['むっつ', 'six (things)', 'noun'],
    '七つ': ['ななつ', 'seven (things)', 'noun'],
    '八つ': ['やっつ', 'eight (things)', 'noun'],
    '九つ': ['ここのつ', 'nine (things); (Edo time) the 9th hour, about midnight', 'noun'],
    '十(とお)': ['とお', 'ten (things)', 'noun'],
    '十一': ['じゅういち', 'eleven', 'noun'],
    '何時(なんどき)': ['なんどき', '(old-fashioned) what time', 'noun'],
    'だい': ['だい', '(old-fashioned, casual) question ending = だ + か', 'particle'],
    '店主': ['てんしゅ', 'shop owner', 'noun'],
    '一文': ['いちもん', 'one mon (an Edo-period coin)', 'noun'],
    '得': ['とく', 'profit, gain (得をする: to come out ahead)', 'noun'],
    '別': ['べつ', 'another, different', 'noun'],
    'まね': ['まね', 'imitation (まねをする: to copy)', 'noun'],
    '損': ['そん', 'loss (損をする: to lose out)', 'noun'],
    '若者': ['わかもの', 'young person, young people', 'noun'],
    'ヘビ': ['へび', 'snake', 'noun'],
    'クモ': ['くも', 'spider', 'noun'],
    'しつこい': ['しつこい', 'persistent, pushy', 'い-adjective'],
    'まんじゅう': ['まんじゅう', 'manjū — a steamed bun filled with sweet bean paste', 'noun'],
    'からかう': ['からかう', 'to tease, to make fun of', 'う-verb'],
    '投げ込む': ['なげこむ', 'to throw in(to)', 'う-verb'],
    // Everyday words the stories happen not to use.
    'すし屋': ['すしや', 'sushi bar, sushi restaurant', 'noun'],
    '池': ['いけ', 'pond', 'noun'],
    '子ども': ['こども', 'child, kid (子供)', 'noun'],
    '笑い': ['わらい', 'laugh, laughter', 'noun'],
    'おもしろい': ['おもしろい', 'funny, interesting (面白い)', 'い-adjective'],
    '英語': ['えいご', 'English (language)', 'noun'],
    'ベッド': ['べっど', 'bed', 'noun'],
    '兄': ['あに', '(my) older brother', 'noun'],
    '生活': ['せいかつ', 'life, daily life, lifestyle', 'noun'],
    '気持ち': ['きもち', 'feeling', 'noun'],
    'がんばる': ['がんばる', 'to work hard, to do one\'s best (頑張る)', 'う-verb'],
    '死ぬ': ['しぬ', 'to die', 'う-verb'],
    '心': ['こころ', 'heart, mind', 'noun'],
    '例えば': ['たとえば', 'for example', 'adverb'],
    '優しい': ['やさしい', 'kind, gentle', 'い-adjective'],
    '危ない': ['あぶない', 'dangerous', 'い-adjective'],
    '早い': ['はやい', 'early', 'い-adjective'],
    'すぎる': ['すぎる', 'after a verb stem or adjective: too much, over- (〜すぎる)', 'ichidan verb'],
  };

  global.MEMES_DATA = [
    // ── N5 ──────────────────────────────────────────────────────────────────
    {
      id: 'meme-n5-futon',
      level: 'n5',
      kind: 'dajare',
      emoji: '🛏️💨',
      title: '布団[ふとん]が吹[ふ]っ飛[と]んだ',
      titleEn: 'The Futon Flew Away',
      punch: 'Futon ga futtonda: the word 布団 (futon) is hiding inside 吹っ飛んだ (futtonda, "blew away"). Puns like this are called ダジャレ, and the corny ones that middle-aged men love are おやじギャグ ("old-man gags") — the Japanese dad joke. The groan is the point.',
      sentences: [
        { jp: '「 布団[ふとん] が 吹[ふ]っ飛[と]んだ>吹っ飛ぶ ！ 」', en: '"The futon blew away!"',
          grammar: ['ga-subject:布団が', 'plain-form:吹っ飛んだ'] },
        { jp: 'これ は 日本[にほん] で 一番[いちばん] 有名[ゆうめい] な ダジャレ です 。', en: 'This is the most famous pun in Japan.',
          grammar: ['ichiban:一番有名な', 'na-adj-noun:有名なダジャレ'] },
        { jp: '「 ふとん>布団 」 と 「 ふっとんだ 」 、 音[おと] が 同[おな]じ です ね 。', en: '"Futon" and "futtonda" — they sound the same, right?',
          grammar: ['to-and:ふとん」と「ふっとんだ', 'ne:同じですね'] },
        { jp: 'お父[とう]さん は 毎日[まいにち] この ダジャレ を 言[い]います>言う 。', en: 'My dad says this pun every day.',
          grammar: ['wo-object:ダジャレを言います', 'masu:言います'] },
        { jp: 'でも 、 家族[かぞく] は だれ>誰 も 笑[わら]いません>笑う 。', en: 'But nobody in the family laughs.',
          grammar: ['masen:笑いません'] },
      ],
    },
    {
      id: 'meme-n5-ikura',
      level: 'n5',
      kind: 'dajare',
      emoji: '🍣',
      title: 'イクラはいくら？',
      titleEn: 'How Much Is the Ikura?',
      punch: 'イクラ (ikura) is salmon roe — the shiny orange beads on sushi — and いくら (ikura) means "how much?". So イクラはいくらですか is a perfectly real question that sounds like a tongue twister. The chef tops it with いくらでも ("as much as you like"), a third ikura.',
      sentences: [
        { jp: 'すし屋[や] で 、 男[おとこ] の 人[ひと] が 聞[き]きました>聞く 。', en: 'At a sushi bar, a man asked:',
          grammar: ['de-place:すし屋で', 'masu-past:聞きました'] },
        { jp: '「 すみません 、 イクラ は いくら です か 。 」', en: '"Excuse me, how much is the ikura?"',
          grammar: ['wa-topic:イクラは', 'ka-question:いくらですか'] },
        { jp: '店[みせ] の 人[ひと] は 笑[わら]って>笑う 言[い]いました>言う 。', en: 'The chef laughed and said:',
          grammar: ['no-possessive:店の人', 'te-sequence:笑って言いました'] },
        { jp: '「 イクラ は いくらでも あります>ある よ 。 」', en: '"We\'ve got as much ikura as you like!"',
          grammar: ['wa-topic:イクラは', 'yo:ありますよ'] },
        { jp: '男[おとこ] の 人[ひと] は 何[なに] も 言[い]いませんでした>言う 。', en: 'The man didn\'t say a word.',
          grammar: ['nani-mo-neg:何も言いませんでした', 'masen-deshita:言いませんでした'] },
      ],
    },
    {
      id: 'meme-n5-kaeru',
      level: 'n5',
      kind: 'dajare',
      emoji: '🐸🏠',
      title: 'カエルが帰[かえ]る',
      titleEn: 'The Frog Goes Home',
      punch: 'カエル (kaeru, frog) and 帰る (kaeru, to go home) sound exactly the same. Thanks to the pun, little frog charms are a popular good-luck gift for travellers in Japan: they help you 無事に帰る, "come home safely".',
      sentences: [
        { jp: '夕方[ゆうがた] 、 池[いけ] の カエル が 言[い]いました>言う 。', en: 'In the evening, the frog in the pond said:',
          grammar: ['no-possessive:池のカエル', 'ga-subject:カエルが'] },
        { jp: '「 もう 五時[ごじ] です ね 。 帰[かえ]ります>帰る 。 」', en: '"It\'s already five o\'clock. I\'m going home."',
          grammar: ['ne:五時ですね', 'masu:帰ります'] },
        { jp: '友[とも]だち の カエル も 帰[かえ]りました>帰る 。', en: 'Its frog friend went home too.',
          grammar: ['mo-also:カエルも', 'masu-past:帰りました'] },
        { jp: 'カエル が 帰[かえ]る 。 だから 、 カエル です 。', en: 'The kaeru (frog) kaeru (goes home). That\'s why it\'s called a kaeru.',
          grammar: ['dakara:だから', 'ga-subject:カエルが'] },
        { jp: '日本[にほん] の 子[こ]ども>子ども は この ジョーク が 大好[だいす]き です 。', en: 'Japanese kids love this joke.',
          grammar: ['ga-suki:ジョークが大好きです'] },
      ],
    },
    {
      id: 'meme-n5-kusa',
      level: 'n5',
      kind: 'slang',
      emoji: '🌱😂',
      title: '草[くさ]',
      titleEn: '"Grass" Means LOL',
      punch: 'Japanese netizens type w for 笑 (warai, laughing) — their "lol". A long wwwww looks like a little field of grass, so people started simply writing 草 ("grass") instead, and for something truly hilarious, 大草原 ("a vast prairie").',
      sentences: [
        { jp: '日本[にほん] の ネット で は 、 笑[わら]う とき 「 w 」 を 書[か]きます>書く 。', en: 'On the Japanese internet, people type "w" when they laugh.',
          grammar: ['toki:笑うとき', 'wo-object:「w」を書きます'] },
        { jp: '「 w 」 は 「 笑[わら]い 」 の w です 。', en: '"w" is the w of warai, "laughing".',
          grammar: ['no-possessive:笑い」のw', 'desu:wです'] },
        { jp: 'とても おもしろい とき は 「 wwwww 」 です 。', en: 'When something is really funny, it\'s "wwwww".',
          grammar: ['toki:おもしろいとき'] },
        { jp: '「 wwwww 」 は 草[くさ]>草(slang) に 見[み]えます>見える ね 。', en: '"wwwww" looks like grass, doesn\'t it?',
          grammar: ['ni-mieru:草に見えます', 'ne:見えますね'] },
        { jp: 'だから 、 おもしろい とき 、 「 草[くさ]>草(slang) 」 と 書[か]きます>書く 。', en: 'So when something is funny, people write 草, "grass".',
          grammar: ['dakara:だから', 'to-quote:「草」と書きます'] },
        { jp: 'とても おもしろい とき は 「 大草原[だいそうげん] 」 です 。', en: 'And when it\'s hilarious, it\'s 大草原 — "a vast prairie".',
          grammar: ['toki:おもしろいとき', 'desu:「大草原」です'] },
      ],
    },
    {
      id: 'meme-n5-homework',
      level: 'n5',
      kind: 'story',
      emoji: '🐶📄',
      title: '宿題[しゅくだい]はどこ？',
      titleEn: 'Where\'s the Homework?',
      punch: 'The classic "the dog ate my homework" excuse, with a twist. Watch the last line: Tanaka answers はい to "you don\'t have a cat either, right?". In Japanese, はい agrees with the statement ("yes, that\'s right — I don\'t"), where English would say "no".',
      sentences: [
        { jp: '先生[せんせい] 「 田中[たなか]くん 、 宿題[しゅくだい] は ？ 」', en: 'Teacher: "Tanaka, where\'s your homework?"',
          grammar: ['wa-topic:宿題は'] },
        { jp: '田中[たなか]くん 「 すみません 。 犬[いぬ] が 食[た]べました>食べる 。 」', en: 'Tanaka: "Sorry. The dog ate it."',
          grammar: ['ga-subject:犬が', 'masu-past:食べました'] },
        { jp: '先生[せんせい] 「 え ？ 田中[たなか]くん の 家[いえ] に は 犬[いぬ] が いません>いる よ ね 。 」', en: 'Teacher: "Huh? There\'s no dog at your house, is there?"',
          grammar: ['ni-wa:家には', 'masen:いません'] },
        { jp: '田中[たなか]くん 「 はい 。 だから 、 猫[ねこ] が 食[た]べました>食べる 。 」', en: 'Tanaka: "Right. So the cat ate it."',
          grammar: ['dakara:だから', 'masu-past:食べました'] },
        { jp: '先生[せんせい] 「 猫[ねこ] も いません>いる よ ね 。 」', en: 'Teacher: "You don\'t have a cat either, do you?"',
          grammar: ['mo-also:猫も', 'masen:いません'] },
        { jp: '田中[たなか]くん 「 … はい 。 ぼく が 食[た]べました>食べる 。 」', en: 'Tanaka: "…No. I ate it."',
          grammar: ['ga-subject:ぼくが', 'masu-past:食べました'] },
      ],
    },
    {
      id: 'meme-n5-nau',
      level: 'n5',
      kind: 'slang',
      emoji: '📱🍜',
      title: 'ラーメンなう',
      titleEn: '"Ramen Now"',
      punch: 'Around 2010, Japanese Twitter users ended posts with なう — the English word "now" written in hiragana — to say where they were or what they were doing: 渋谷なう, "in Shibuya right now". These days it feels a bit retro, like saying "YOLO" — which is exactly why dads still use it.',
      sentences: [
        { jp: '「 なう 」 は 英語[えいご] の 「 ナウ 」 です 。', en: '"Nau" is the English word "now".',
          grammar: ['no-possessive:英語の「ナウ」', 'desu:「ナウ」です'] },
        { jp: 'ツイッター で 、 みんな 今[いま] の 場所[ばしょ] に 「 なう 」 を つけました>つける 。', en: 'On Twitter, everyone stuck "nau" after wherever they were.',
          grammar: ['de-place:ツイッターで', 'masu-past:つけました'] },
        { jp: '「 東京[とうきょう] なう 。 」 「 ラーメン なう 。 」', en: '"Tokyo now." "Ramen now."',
          grammar: ['nau:東京なう', 'nau:ラーメンなう'] },
        { jp: '父[ちち] も 毎日[まいにち] 「 会社[かいしゃ] なう 」 と 書[か]きます>書く 。', en: 'My dad writes "office now" every day too.',
          grammar: ['mo-also:父も', 'to-quote:「会社なう」と書きます'] },
        { jp: 'でも 、 父[ちち] は 今[いま] 、 家[いえ] の ベッド に います>いる 。', en: 'But right now he\'s in bed at home.',
          grammar: ['ni-aru:ベッドにいます'] },
        { jp: 'それ は 「 うそ なう 」 です ね 。', en: 'That\'s "lying now," isn\'t it?',
          grammar: ['nau:うそなう', 'ne:ですね'] },
      ],
    },
    {
      id: 'meme-n5-ame',
      level: 'n5',
      kind: 'story',
      emoji: '☔🍬',
      title: 'あめが好[す]き',
      titleEn: 'I Love Ame',
      punch: 'あめ is both 雨 (rain) and 飴 (candy). In Tokyo speech they differ only in pitch — rain is A-me (high-low), candy is a-ME (low-high) — so written in hiragana, the brother can\'t tell which one his sister means. And her reason for loving rain is very relatable.',
      sentences: [
        { jp: '妹[いもうと] 「 わたし>私 、 あめ>雨 が 大好[だいす]き 。 」', en: 'Little sister: "I really love ame."',
          grammar: ['ga-suki:あめが大好き'] },
        { jp: '兄[あに] 「 ぼく も ！ あまくて>あまい 、 おいしい よ ね 。 」', en: 'Big brother: "Me too! It\'s sweet and tasty, right?"',
          grammar: ['kute:あまくて', 'mo-also:ぼくも'] },
        { jp: '妹[いもうと] 「 え ？ あまくない>あまい よ 。 空[そら] から 降[ふ]る あめ>雨 だ よ 。 」', en: 'Sister: "Huh? It\'s not sweet. I mean the ame that falls from the sky."',
          grammar: ['i-adj-neg:あまくない', 'relative-clause:空から降るあめ', 'kara-from:空から'] },
        { jp: '兄[あに] 「 雨[あめ] が 好[す]き ？ どうして ？ 」', en: 'Brother: "You like rain? Why?"',
          grammar: ['ga-suki:雨が好き', 'doushite:どうして'] },
        { jp: '妹[いもうと] 「 雨[あめ] の 日[ひ] は 、 体育[たいいく] が ない から 。 」', en: 'Sister: "Because on rainy days there\'s no P.E."',
          grammar: ['kara-reason:ないから', 'no-possessive:雨の日'] },
      ],
    },
    {
      id: 'meme-n5-pikachu',
      level: 'n5',
      kind: 'pop',
      emoji: '⚡🐭',
      title: 'ピカチュウの名前[なまえ]',
      titleEn: 'Where Pikachu\'s Name Comes From',
      punch: 'Japanese is full of sound words: ピカピカ / ピカッ is the sound of something sparkling or flashing, and チュウ is how a Japanese mouse squeaks. Lots of Pokémon names are built this way — say them out loud and you can often guess what they are.',
      sentences: [
        { jp: 'ピカチュウ は ポケモン の キャラクター です 。', en: 'Pikachu is a Pokémon character.',
          grammar: ['no-possessive:ポケモンのキャラクター', 'desu:キャラクターです'] },
        { jp: '「 ピカ 」 は 日本語[にほんご] で 光[ひか]る 音[おと] です 。', en: 'In Japanese, "pika" is the sound of something flashing.',
          grammar: ['de-means:日本語で', 'relative-clause:光る音'] },
        { jp: '「 チュウ 」 は ネズミ の 声[こえ] です 。', en: '"Chuu" is the sound a mouse makes.',
          grammar: ['no-possessive:ネズミの声'] },
        { jp: 'だから 、 ピカチュウ は 「 ピカッ と 光[ひか]る ネズミ 」 です 。', en: 'So Pikachu is "a mouse that goes flash".',
          grammar: ['dakara:だから', 'relative-clause:ピカッと光るネズミ'] },
        { jp: 'ピカチュウ は 「 ピカ 」 と 「 チュウ 」 しか 言[い]いません>言う 。', en: 'Pikachu only ever says "pika" and "chuu".',
          grammar: ['shika-nai:しか言いません', 'to-and:「ピカ」と「チュウ」'] },
        { jp: 'でも 、 みんな ピカチュウ の 言[い]う こと が わかります>わかる 。', en: 'But everyone understands what Pikachu says.',
          grammar: ['relative-clause:ピカチュウの言うこと', 'masu:わかります'] },
      ],
    },
    {
      id: 'meme-n5-doraemon',
      level: 'n5',
      kind: 'pop',
      emoji: '🤖🐱',
      title: 'ドラえもんの耳[みみ]',
      titleEn: 'Doraemon\'s Missing Ears',
      punch: 'According to his official backstory, Doraemon — a robot cat from the 22nd century — was once yellow with ears, until a robot mouse chewed them off. The shock turned him blue, and ever since, the most famous "cat" in Japan has no ears and is terrified of mice. His favourite food, どら焼き, is a pancake sandwich filled with sweet red bean paste.',
      sentences: [
        { jp: 'ドラえもん は 未来[みらい] から 来[き]た>来る ネコ型[がた] ロボット です 。', en: 'Doraemon is a cat-type robot who came from the future.',
          grammar: ['kara-from:未来から', 'relative-clause:未来から来たネコ型ロボット'] },
        { jp: 'でも 、 ドラえもん に は 耳[みみ] が ありません>ある 。', en: 'But Doraemon has no ears.',
          grammar: ['ni-wa:ドラえもんには', 'masen:ありません'] },
        { jp: 'ネズミ が 耳[みみ] を 食[た]べました>食べる 。', en: 'A mouse ate them.',
          grammar: ['ga-subject:ネズミが', 'wo-object:耳を食べました'] },
        { jp: 'だから 、 ドラえもん は ネズミ が 大[だい]きらい です 。', en: 'So Doraemon really hates mice.',
          grammar: ['dakara:だから', 'ga-suki:ネズミが大きらいです'] },
        { jp: '好[す]き な 食[た]べ物[もの] は どら焼[や]き です 。', en: 'His favourite food is dorayaki.',
          grammar: ['na-adj-noun:好きな食べ物', 'wa-topic:食べ物は'] },
        { jp: 'ネコ型[がた] ロボット です が 、 ネコ に は 見[み]えません>見える ね 。', en: 'He\'s a cat robot, but he doesn\'t look like a cat, does he?',
          grammar: ['ga-but:ですが', 'ni-mieru:ネコには見えません'] },
      ],
    },
    {
      id: 'meme-n5-neko',
      level: 'n5',
      kind: 'dajare',
      emoji: '🐈💤',
      title: '猫[ねこ]が寝[ね]ころんだ',
      titleEn: 'The Cat Lay Down',
      punch: 'Neko ga nekoronda: ねこ (cat) is hiding inside 寝ころんだ (nekoronda, "lay down"). And one popular folk etymology says ねこ itself comes from 寝る子, "the child who sleeps" — not proven, but anyone who owns a cat believes it.',
      sentences: [
        { jp: '「 猫[ねこ] が 寝[ね]ころんだ>寝ころぶ 。 」', en: '"The cat (neko) lay down (nekoronda)."',
          grammar: ['ga-subject:猫が', 'plain-form:寝ころんだ'] },
        { jp: 'これ も 有名[ゆうめい] な ダジャレ です 。', en: 'This is a famous pun too.',
          grammar: ['mo-also:これも', 'na-adj-noun:有名なダジャレ'] },
        { jp: '猫[ねこ] は 一日[いちにち] に 十四時間[じゅうよじかん] ぐらい 寝[ね]ます>寝る 。', en: 'Cats sleep about fourteen hours a day.',
          grammar: ['gurai:十四時間ぐらい', 'masu:寝ます'] },
        { jp: '「 寝[ね]る 子[こ] 」 だから 「 ねこ>猫 」 … ？', en: '"Neru ko" — "the child who sleeps" — so "neko"…?',
          grammar: ['relative-clause:寝る子', 'kara-reason:だから'] },
        { jp: 'そういう 話[はなし] も あります>ある 。', en: 'There\'s a story like that, anyway.',
          grammar: ['mo-also:話も', 'masu:あります'] },
        { jp: 'うち の 猫[ねこ] も 、 今[いま] ソファ で 寝[ね]て>寝る います>いる 。', en: 'Our cat is asleep on the sofa right now, too.',
          grammar: ['te-iru:寝ています', 'de-place:ソファで'] },
      ],
    },

    // ── N4 ──────────────────────────────────────────────────────────────────
    {
      id: 'meme-n4-frypan',
      level: 'n4',
      kind: 'riddle',
      emoji: '🍳🍞',
      title: '食[た]べられないパン',
      titleEn: 'The Pan You Can\'t Eat',
      punch: 'パン means bread (from Portuguese pão), but plenty of other words contain パン — フライパン (frying pan), ジーパン (jeans), パンダ, ジャパン. "〇〇は〇〇でも…" ("it\'s an X, but…") is the standard opening of a Japanese なぞなぞ. Try this one: パンはパンでも、はくパンは？ (A pan you wear? — ジーパン!)',
      sentences: [
        { jp: 'なぞなぞ です 。', en: 'Here\'s a riddle.',
          grammar: ['desu:なぞなぞです'] },
        { jp: '「 パン は パン でも 、 食[た]べられない>食べる パン は 何[なん] だ ？ 」', en: '"It\'s a pan, but you can\'t eat it. What pan is it?"',
          grammar: ['potential:食べられない', 'relative-clause:食べられないパン'] },
        { jp: 'パン屋[や] の パン は 、 もちろん 食[た]べられます>食べる 。', en: 'Bread from a bakery, you can of course eat.',
          grammar: ['potential:食べられます', 'no-possessive:パン屋のパン'] },
        { jp: 'でも 、 台所[だいどころ] に 、 かたくて>かたい 黒[くろ]い パン が あります>ある 。', en: 'But in the kitchen there\'s a hard, black pan.',
          grammar: ['kute:かたくて', 'ni-aru:台所に、かたくて黒いパンがあります'] },
        { jp: '答[こた]え は 「 フライパン 」 です 。', en: 'The answer: a "furaipan" — a frying pan.',
          grammar: ['wa-topic:答えは'] },
        { jp: '「 パンダ 」 も 「 ジャパン 」 も 食[た]べられません>食べる よ 。', en: 'And you can\'t eat a "panda" or "Japan" either!',
          grammar: ['mo-also:「パンダ」も「ジャパン」も', 'potential:食べられません'] },
      ],
    },
    {
      id: 'meme-n4-ikkyu',
      level: 'n4',
      kind: 'story',
      emoji: '🌉🧘',
      title: '一休[いっきゅう]さんと橋[はし]',
      titleEn: 'Ikkyū and the Bridge',
      punch: 'はし can be 橋 (bridge), 端 (edge) or 箸 (chopsticks). Written in hiragana, the sign このはしわたるべからず can mean "don\'t cross this bridge" — or "don\'t walk on this edge". So Ikkyū walks straight down the middle. 一休 was a real 15th-century Zen monk, and these 一休さん tales of quick wit are a childhood classic in Japan.',
      sentences: [
        { jp: '一休[いっきゅう]さん は 、 とても 頭[あたま] の いい お坊[ぼう]さん でした>です 。', en: 'Ikkyū was a very clever monk.',
          grammar: ['relative-clause:頭のいいお坊さん', 'deshita:お坊さんでした'] },
        { jp: 'ある>ある(certain) 日[ひ] 、 お殿様[とのさま] が 一休[いっきゅう]さん を よびました>よぶ 。', en: 'One day, the lord summoned Ikkyū.',
          grammar: ['ga-subject:お殿様が', 'masu-past:よびました'] },
        { jp: '橋[はし] の 前[まえ] に 、 「 この はし わたる べからず 」 と 書[か]いて>書く ありました>ある 。', en: 'In front of the bridge, a sign read: "Do not cross this hashi."',
          grammar: ['te-aru:書いてありました', 'beki-kara-zu:わたるべからず'] },
        { jp: 'でも 、 一休[いっきゅう]さん は 平気[へいき] な 顔[かお] で 橋[はし] を わたりました>わたる 。', en: 'But Ikkyū crossed the bridge without a care.',
          grammar: ['wo-path:橋をわたりました', 'de-means:平気な顔で'] },
        { jp: 'お殿様[とのさま] 「 こら ！ 字[じ] が 読[よ]めない>読む の>の(explain) か ！ 」', en: 'The lord: "Hey! Can\'t you read?!"',
          grammar: ['potential:読めない'] },
        { jp: '一休[いっきゅう]さん 「 読[よ]めました>読む よ 。 だから 、 端[はし] ではなく 、 真[ま]ん中[なか] を 歩[ある]きました>歩く 。 」', en: 'Ikkyū: "I could read it. That\'s why I didn\'t walk on the edge (hashi) — I walked down the middle."',
          grammar: ['potential:読めました', 'de-wa-naku:端ではなく', 'wo-path:真ん中を歩きました'] },
      ],
    },
    {
      id: 'meme-n4-riajuu',
      level: 'n4',
      kind: 'slang',
      emoji: '💑💥',
      title: 'リア充[じゅう]爆発[ばくはつ]しろ',
      titleEn: 'Riajū, Go Explode',
      punch: 'リア充 is short for リアル(の生活)が充実している — "someone whose real, offline life is full". Lonely netizens jokingly curse happy couples with リア充爆発しろ, especially around Christmas Eve, which in Japan is a big date night. The rough command form しろ (from する) is over-the-top on purpose.',
      sentences: [
        { jp: '「 リア充[じゅう] 」 は 「 リアル の 生活[せいかつ] が 充実[じゅうじつ]して>充実する いる>いる 人[ひと] 」 です 。', en: '"Riajū" means "a person whose real life is full".',
          grammar: ['relative-clause:リアルの生活が充実している人', 'te-iru:充実している'] },
        { jp: '恋人[こいびと] が いて>いる 、 友[とも]だち も 多[おお]い 人[ひと] の こと です 。', en: 'It\'s someone with a partner and lots of friends.',
          grammar: ['te-sequence:恋人がいて', 'no-koto:人のこと'] },
        { jp: 'クリスマス に なる と 、 ネット に は この ことば が 出[で]て>出る きます>くる 。', en: 'Every Christmas, this phrase starts popping up online:',
          grammar: ['to-conditional:なると', 'te-kuru:出てきます'] },
        { jp: '「 リア充[じゅう] 爆発[ばくはつ]しろ>爆発する ！ 」', en: '"Riajū — explode!"',
          grammar: ['meirei:爆発しろ'] },
        { jp: 'もちろん 、 本当[ほんとう] に 爆発[ばくはつ]して>爆発する ほしい わけ で は ない>ない 。', en: 'Of course, nobody really wants them to explode.',
          grammar: ['te-hoshii:爆発してほしい', 'wake-ja-nai:わけではない'] },
        { jp: '「 うらやましい ！ 」 と いう>言う 気持[きも]ち の 冗談[じょうだん] です 。', en: 'It\'s a joke that really means "I\'m so jealous!"',
          grammar: ['to-iu:「うらやましい！」という気持ち'] },
      ],
    },
    {
      id: 'meme-n4-yabai',
      level: 'n4',
      kind: 'slang',
      emoji: '😱😋',
      title: 'やばい！',
      titleEn: 'Yabai! (Good or Bad?)',
      punch: 'やばい started out as slang for "risky, dangerous" — "uh-oh, we\'re in trouble". From the 1990s young people flipped it to also mean "incredible", so やばい can be awful, awesome, or both. Tone and face do the work. The grandpa line is the joke: older people only know the old meaning.',
      sentences: [
        { jp: '「 やばい 」 は 、 もともと 「 あぶない 」 と いう>言う 意味[いみ] でした>です 。', en: '"Yabai" originally meant "dangerous".',
          grammar: ['to-iu:「あぶない」という意味', 'deshita:意味でした'] },
        { jp: '「 え 、 テスト は 明日[あした] ？ やばい ！ 」', en: '"Wait, the test is tomorrow? Yabai — I\'m doomed!"',
          grammar: ['wa-topic:テストは'] },
        { jp: 'でも 、 若[わか]い 人[ひと] は おいしい とき も 「 やばい 」 と 言[い]います>言う 。', en: 'But young people also say "yabai" when something tastes great.',
          grammar: ['toki:おいしいとき', 'to-quote:「やばい」と言います'] },
        { jp: '「 この ケーキ 、 やばい ！ 」 は 「 すごく おいしい ！ 」 です 。', en: '"This cake is yabai!" means "This is insanely good!"',
          grammar: ['wa-topic:「このケーキ、やばい！」は'] },
        { jp: 'いい の>の(explain) か 悪[わる]い の>の(explain) か 、 顔[かお] を 見[み]ない>見る と わかりません>わかる 。', en: 'Good or bad? You can\'t tell without seeing their face.',
          grammar: ['to-conditional:見ないと', 'masen:わかりません'] },
        { jp: 'でも 、 おじいちゃん が 「 この お茶[ちゃ] 、 やばい 」 と 言[い]ったら>言う 、 たぶん 本当[ほんとう] に あぶない です 。', en: 'But if Grandpa says "this tea is yabai," it\'s probably actually dangerous.',
          grammar: ['tara:言ったら', 'i-adj-desu:あぶないです'] },
      ],
    },
    {
      id: 'meme-n4-oshi',
      level: 'n4',
      kind: 'pop',
      emoji: '🌟💖',
      title: '推[お]しは尊[とうと]い',
      titleEn: 'My Oshi Is Precious',
      punch: '推し comes from 推す, "to push for, to recommend". It started in idol fandom — "my favourite member is my 推し" — and now covers any favourite: anime characters, actors, even a brand of instant noodles. 推し活 ("oshi activities") means buying merch and going to events, and 尊い ("sacred, precious") is what fans whisper when their oshi is too wonderful to handle.',
      sentences: [
        { jp: '「 推[お]し 」 は 、 一番[いちばん] 応援[おうえん]して>応援する いる アイドル や キャラクター の こと です 。', en: 'Your "oshi" is the idol or character you support the most.',
          grammar: ['te-iru:応援している', 'ya-and:アイドルやキャラクター', 'no-koto:キャラクターのこと'] },
        { jp: '推[お]し の グッズ を 買[か]う ため に 、 アルバイト を がんばる 人[ひと] も います>いる 。', en: 'Some people work extra shifts just to buy their oshi\'s merch.',
          grammar: ['tame-ni:買うために', 'mo-also:人も'] },
        { jp: '推[お]し が 笑[わら]う と 、 ファン は 「 尊[とうと]い … 」 と 言[い]います>言う 。', en: 'When their oshi smiles, fans sigh "so precious…"',
          grammar: ['to-conditional:笑うと', 'to-quote:「尊い…」と言います'] },
        { jp: '推[お]し の 写真[しゃしん] を 見[み]る と 、 元気[げんき] に なれる>なる そう です 。', en: 'Apparently just looking at a photo of your oshi gives you energy.',
          grammar: ['to-conditional:見ると', 'sou-hearsay:なれるそうです', 'potential:なれる'] },
        { jp: '「 推[お]し は 推[お]せる>推す とき に 推[お]せ>推す 」 と いう>言う 名言[めいげん] も あります>ある 。', en: 'There\'s even a famous saying: "Support your oshi while you still can."',
          grammar: ['meirei:推せ', 'potential:推せる', 'to-iu:」という名言'] },
      ],
    },
    {
      id: 'meme-n4-buchou',
      level: 'n4',
      kind: 'story',
      emoji: '🍛❄️',
      title: '部長[ぶちょう]のダジャレ',
      titleEn: 'The Boss\'s Puns',
      punch: 'A joke that falls flat in Japanese is 寒い ("cold") — so bad it lowers the room temperature. The pun: カレー (curry) sounds like かれー, a rough, drawled way of saying 辛い ("spicy"), the same way すごい becomes すげー. Because he\'s the boss, everyone has to laugh anyway — and his comeback is the most famous pun in Japan.',
      sentences: [
        { jp: 'うち の 部長[ぶちょう] は ダジャレ が 大好[だいす]き です 。', en: 'Our department head loves puns.',
          grammar: ['ga-suki:ダジャレが大好きです'] },
        { jp: '昼[ひる]ご飯[はん] に カレー を 食[た]べながら>食べる 、 部長[ぶちょう] は 言[い]いました>言う 。', en: 'Eating curry at lunch, the boss said:',
          grammar: ['nagara:食べながら', 'masu-past:言いました'] },
        { jp: '「 この カレー 、 かれー ！ 」', en: '"This curry (karē) is karē — spicy!"',
          grammar: ['ee-slur:かれー'] },
        { jp: 'みんな は 笑[わら]わなければ>笑う なりません>なる 。', en: 'Everyone has to laugh.',
          grammar: ['nakereba-naranai:笑わなければなりません'] },
        { jp: 'でも 、 その 時[とき] 、 部屋[へや] の 空気[くうき] が 寒[さむ]く>寒い なりました>なる 。', en: 'But at that moment, the air in the room went cold.',
          grammar: ['ku-naru:寒くなりました', 'no-possessive:部屋の空気'] },
        { jp: 'つまらない ダジャレ は 、 日本語[にほんご] で 「 寒[さむ]い 」 と 言[い]います>言う 。', en: 'In Japanese, a lame pun is called "cold".',
          grammar: ['de-means:日本語で', 'to-quote:「寒い」と言います'] },
        { jp: '部長[ぶちょう] 「 寒[さむ]い ね 。 布団[ふとん] が 吹[ふ]っ飛[と]んだ>吹っ飛ぶ ！ 」', en: 'The boss: "Brr, it\'s cold. The futon blew away!"',
          grammar: ['ne:寒いね', 'plain-form:吹っ飛んだ'] },
      ],
    },
    {
      id: 'meme-n4-chotto',
      level: 'n4',
      kind: 'story',
      emoji: '🙅🍻',
      title: '「ちょっと…」',
      titleEn: '"Well, Friday Is a Bit…"',
      punch: 'A flat いいえ to an invitation feels harsh, so Japanese speakers trail off — 金曜日はちょっと… ("Friday is a little…") — and let silence finish the sentence. Everyone understands it as a polite no. Everyone except Tom, who is still waiting for the rest.',
      sentences: [
        { jp: 'アメリカ から 来[き]た>来る トムさん は 、 同僚[どうりょう] の 山田[やまだ]さん を 飲[の]み会[かい] に 誘[さそ]いました>誘う 。', en: 'Tom, who came from America, invited his coworker Yamada out for drinks.',
          grammar: ['relative-clause:アメリカから来たトムさん', 'masu-past:誘いました'] },
        { jp: '「 金曜日[きんようび] 、 一緒[いっしょ] に 飲[の]み>飲む に 行[い]きません>行く か 。 」', en: '"How about going for a drink together on Friday?"',
          grammar: ['masen-ka:行きませんか', 'ni-iku-purpose:飲みに行きません'] },
        { jp: '山田[やまだ]さん は 少[すこ]し 困[こま]った>困る 顔[かお] で 言[い]いました>言う 。', en: 'Yamada answered with a slightly troubled face:',
          grammar: ['relative-clause:困った顔', 'de-means:顔で'] },
        { jp: '「 金曜日[きんようび] は 、 ちょっと … 」', en: '"Friday is a little…"',
          grammar: ['wa-topic:金曜日は'] },
        { jp: 'トムさん は 次[つぎ] の ことば を 待[ま]ちました>待つ 。', en: 'Tom waited for the next words.',
          grammar: ['wo-object:ことばを待ちました', 'masu-past:待ちました'] },
        { jp: '五分[ごふん] たって>たつ も 、 十分[じゅっぷん] たって>たつ も 、 次[つぎ] の ことば は 来[き]ませんでした>来る 。', en: 'Five minutes passed, ten minutes passed — the next words never came.',
          grammar: ['te-mo:五分たっても', 'masen-deshita:来ませんでした'] },
        { jp: '日本[にほん] で は 、 「 ちょっと … 」 は 「 いいえ 」 と いう>言う 意味[いみ] です 。', en: 'In Japan, "chotto…" means "no".',
          grammar: ['to-iu:「いいえ」という意味'] },
      ],
    },
    {
      id: 'meme-n4-tanuki',
      level: 'n4',
      kind: 'riddle',
      emoji: '🦝✉️',
      title: 'たぬきの手紙[てがみ]',
      titleEn: 'A Letter from a Tanuki',
      punch: 'たぬき (tanuki, the raccoon dog) sounds like た抜き — "ta taken out". A たぬき puzzle is a string of kana with a tanuki drawn beside it: strip out every た and the hidden message appears. In folk tales tanuki are shape-shifting tricksters, so a cryptic thank-you note is very on-brand.',
      sentences: [
        { jp: 'ある>ある(certain) 日[ひ] 、 ポスト に 変[へん] な 手紙[てがみ] が 入[はい]って>入る いました>いる 。', en: 'One day, there was a strange letter in my mailbox.',
          grammar: ['te-iru:入っていました', 'na-adj-noun:変な手紙'] },
        { jp: '「 あたりたがたとう 」 と 書[か]いて>書く ありました>ある 。', en: 'It said: "A-ta-ri-ta-ga-ta-to-u."',
          grammar: ['te-aru:書いてありました', 'to-quote:「あたりたがたとう」と書いて'] },
        { jp: '手紙[てがみ] の 下[した] に は 、 たぬき の 絵[え] が 描[か]いて>描く あります>ある 。', en: 'At the bottom of the letter, there\'s a drawing of a tanuki.',
          grammar: ['te-aru:描いてあります', 'ni-wa:下には'] },
        { jp: 'たぬき … 「 た>た(kana) 」 を 抜[ぬ]く ？', en: 'Tanuki… "ta-nuki" — "take out the ta"?',
          grammar: ['wo-object:「た」を抜く'] },
        { jp: '「 た>た(kana) 」 を 全部[ぜんぶ] 取[と]ったら>取る 、 「 ありがとう 」 に なりました>なる 。', en: 'When I took out every た, it turned into "arigatou" — thank you.',
          grammar: ['tara:取ったら', 'ni-naru:「ありがとう」になりました'] },
        { jp: 'きのう>昨日 、 けが を した>する たぬき を 助[たす]けた>助ける から か な>な(feeling) ？', en: 'Maybe because I helped an injured tanuki yesterday?',
          grammar: ['relative-clause:けがをしたたぬき', 'kara-reason:助けたから', 'kana:かな'] },
      ],
    },
    {
      id: 'meme-n4-omaewa',
      level: 'n4',
      kind: 'pop',
      emoji: '👊💀',
      title: 'お前[まえ]はもう死[し]んでいる',
      titleEn: '"You Are Already Dead"',
      punch: 'お前はもう死んでいる is Kenshiro\'s catchphrase in 北斗の拳 (Fist of the North Star, 1983): he strikes secret pressure points, and his opponent only realises a moment later — usually yelling なにっ！？ ("What?!") right before he bursts. It became a worldwide internet meme. Grammar note: 死んでいる isn\'t "is dying" but the resulting state — "is dead".',
      sentences: [
        { jp: '「 北斗[ほくと]の拳[けん] 」 は 八十年代[はちじゅうねんだい] の 有名[ゆうめい] な マンガ です 。', en: '"Fist of the North Star" is a famous manga from the 80s.',
          grammar: ['na-adj-noun:有名なマンガ', 'no-possessive:八十年代の'] },
        { jp: '主人公[しゅじんこう] の ケンシロウ は 、 敵[てき] を 指[ゆび] で 突[つ]いて>突く から 、 こう 言[い]います>言う 。', en: 'The hero, Kenshiro, jabs his enemy with his fingers and then says:',
          grammar: ['te-kara:突いてから', 'de-means:指で'] },
        { jp: '「 お前[まえ] は もう 死[し]んで>死ぬ いる 。 」', en: '"You are already dead."',
          grammar: ['te-iru:死んでいる'] },
        { jp: '敵[てき] は 「 なに ！ ？ 」 と 言[い]って>言う 、 その あと>後(あと) 爆発[ばくはつ]します>爆発する 。', en: 'The enemy says "What?!" — and then explodes.',
          grammar: ['to-quote:「なに！？」と言って', 'te-sequence:言って'] },
        { jp: '今[いま] でも 、 日本[にほん] の 人[ひと] は 冗談[じょうだん] で この セリフ を 使[つか]います>使う 。', en: 'Even now, people in Japan use this line as a joke.',
          grammar: ['demo-even:今でも', 'de-means:冗談で'] },
        { jp: '月曜日[げつようび] の 朝[あさ] 、 疲[つか]れた>疲れる 同僚[どうりょう] に 言[い]って>言う みましょう>みる 。', en: 'Try saying it to an exhausted coworker on Monday morning.',
          grammar: ['te-miru:言ってみましょう', 'relative-clause:疲れた同僚'] },
      ],
    },
    {
      id: 'meme-n4-senryu',
      level: 'n4',
      kind: 'senryu',
      emoji: '📝👓',
      title: 'サラリーマン川柳[せんりゅう]',
      titleEn: 'Comic Poems for Tired Grown-ups',
      punch: 'Senryū (川柳) use the same 5-7-5 rhythm as haiku but are about human foibles instead of nature, and need no season word. A big insurance company has run a famous サラリーマン川柳 contest every year since the late 1980s — poems about diets, smartphones, bosses and being ignored at home. The three here are originals in that style. Count the beats: だ・い・え・っ・と / あ・す・か・ら・や・る・と / じゅ・う・ね・ん・め.',
      sentences: [
        { jp: '川柳[せんりゅう] は 俳句[はいく] と 同[おな]じ 五七五[ごしちご] の 詩[し] です が 、 季語[きご] が いりません>いる(need) 。', en: 'Senryū are 5-7-5 poems, just like haiku, but they don\'t need a season word.',
          grammar: ['ga-but:ですが', 'masen:いりません'] },
        { jp: 'そして 、 おもしろい 川柳[せんりゅう] が 多[おお]い です 。', en: 'And lots of them are funny.',
          grammar: ['i-adj-desu:多いです'] },
        { jp: '「 ダイエット 明日[あす]>明日(あす) から やる と 十年目[じゅうねんめ] 」', en: '"My diet: \'I\'ll start tomorrow\' — now in year ten."',
          grammar: ['kara-from:明日から', 'to-quote:やると'] },
        { jp: '「 メガネ どこ ？ 探[さが]す 頭[あたま] に のって>のる いる 」', en: '"Where are my glasses? On the very head that\'s looking for them."',
          grammar: ['relative-clause:探す頭', 'te-iru:のっている'] },
        { jp: '「 ただいま に 返事[へんじ] する の は 犬[いぬ] だけ 」', en: '"The only one who answers my \'I\'m home!\' is the dog."',
          grammar: ['no-wa:返事するのは', 'dake:犬だけ'] },
        { jp: 'どれ も 、 疲[つか]れた>疲れる お父[とう]さん たち の 気持[きも]ち が よく わかります>わかる ね 。', en: 'Every one of them really captures how worn-out dads feel, doesn\'t it?',
          grammar: ['relative-clause:疲れたお父さんたち', 'ne:わかりますね'] },
      ],
    },

    // ── N3 ──────────────────────────────────────────────────────────────────
    {
      id: 'meme-n3-shirankedo',
      level: 'n3',
      kind: 'meme',
      emoji: '🤷🐙',
      title: '知[し]らんけど',
      titleEn: '"…Not That I Know, Though"',
      punch: 'In Kansai (Osaka and around), 知らんけど — "I don\'t know, though" — is a verbal shrug tacked onto a perfectly confident statement. It isn\'t really admitting ignorance; it\'s a playful "don\'t quote me". 知らん is the Kansai way to say 知らない, and ending a sentence with で (うまいで) is Kansai for よ. In 2022 the phrase made the top ten of Japan\'s buzzword-of-the-year awards.',
      sentences: [
        { jp: '関西[かんさい] の 人[ひと] は 、 自信[じしん] たっぷり に 話[はな]した>話す あと で 、 「 知[し]らん けど 」 と 付[つ]け加[くわ]える>付け加える 。', en: 'People from Kansai say something with total confidence, then tack on "shiran kedo" — "not that I know, though".',
          grammar: ['ato-de:話したあとで', 'to-quote:「知らんけど」と付け加える'] },
        { jp: '「 あの 店[みせ] の たこ焼[や]き 、 日本一[にっぽんいち] うまい で>で(Kansai) 。 知[し]らん けど 。 」', en: '"That shop\'s takoyaki are the best in Japan, I tell ya. Not that I know, though."',
          grammar: ['kansai-de:うまいで', 'shiran-kedo:知らんけど'] },
        { jp: '東京[とうきょう] の 人[ひと] は これ を 聞[き]く と 、 「 じゃあ 、 今[いま] まで の 話[はなし] は 何[なん] だった>だ の>の(explain) ？ 」 と 驚[おどろ]く 。', en: 'When people from Tokyo hear it, they\'re stunned: "Then what was everything you just said?!"',
          grammar: ['to-conditional:聞くと', 'made:今まで'] },
        { jp: 'でも 、 これ は 「 責任[せきにん] は 取[と]らない>取る よ 」 と いう>言う 軽[かる]い 冗談[じょうだん] だ 。', en: 'But it\'s just a light joke meaning "don\'t hold me to it".',
          grammar: ['to-iu:」という軽い冗談', 'i-adj-noun:軽い冗談'] },
        { jp: '2022年[ねん] に は 、 流行語大賞[りゅうこうごたいしょう] の トップテン に も 選[えら]ばれた>選ぶ そう だ 。', en: 'In 2022, it was even picked for the top ten of the buzzword-of-the-year awards.',
          grammar: ['passive:選ばれた', 'sou-hearsay:選ばれたそうだ'] },
        { jp: '日本語[にほんご] は 毎日[まいにち] 勉強[べんきょう]する>勉強する と 、 絶対[ぜったい] 上手[じょうず] に なる 。 知[し]らん けど 。', en: 'Study Japanese every day and you\'ll definitely get good. Not that I know, though.',
          grammar: ['to-conditional:勉強すると', 'ni-naru:上手になる', 'shiran-kedo:知らんけど'] },
      ],
    },
    {
      id: 'meme-n3-keikaku',
      level: 'n3',
      kind: 'pop',
      emoji: '📓😏',
      title: '計画通[けいかくどお]り',
      titleEn: '"All According to Plan"',
      punch: 'In Death Note, genius Light Yagami (夜神月 — his name is written 月, "moon", but read ライト) thinks 計画通り ("exactly as planned") with a famously villainous smirk whenever his schemes succeed. Online it\'s used ironically for pure luck you pretend was intentional. 〜通り after a noun means "in line with": 予定通り "on schedule", 言った通り "just as I said".',
      sentences: [
        { jp: '「 デスノート 」 の 主人公[しゅじんこう] 、 夜神[やがみ]月[らいと] は 、 計画[けいかく] が うまくいく と 、 悪[わる]い 顔[かお] で 笑[わら]う 。', en: 'Light Yagami, the hero of Death Note, flashes an evil grin whenever a plan works out.',
          grammar: ['to-conditional:うまくいくと', 'de-means:悪い顔で'] },
        { jp: 'そして 、 心[こころ] の 中[なか] で 言[い]う 。 「 計画[けいかく]通[どお]り 」', en: 'And in his head, he says: "All according to plan."',
          grammar: ['de-place:心の中で', 'toori-ni:計画通り'] },
        { jp: 'この セリフ は 今[いま] 、 ネット で 全然[ぜんぜん] 違[ちが]う 使[つか]い方[かた] を されて>する いる>いる 。', en: 'Today, this line is used online in a completely different way.',
          grammar: ['passive:されている', 'relative-clause:全然違う使い方'] },
        { jp: '例[たと]えば 、 寝坊[ねぼう]して>寝坊する 遅刻[ちこく]した>遅刻する のに 、 その 日[ひ] は 休[やす]み だった>だ 。', en: 'Say you overslept and were late — and it turns out that day was a holiday.',
          grammar: ['te-reason:寝坊して', 'noni:遅刻したのに'] },
        { jp: 'そんな とき に 、 わざと 悪[わる]い 顔[かお] で 「 計画[けいかく]通[どお]り 」 と 言[い]う の>の(explain) だ 。', en: 'At times like that, you put on an evil face and say "all according to plan."',
          grammar: ['toki:そんなときに', 'to-quote:「計画通り」と言う'] },
        { jp: '本当[ほんとう] は 何[なに] も 計画[けいかく]して>計画する いなかった>いる のに 。', en: 'Even though you hadn\'t planned a thing.',
          grammar: ['nani-mo-neg:何も計画していなかった', 'noni:いなかったのに'] },
      ],
    },
    {
      id: 'meme-n3-akirame',
      level: 'n3',
      kind: 'pop',
      emoji: '🏀🔥',
      title: 'あきらめたらそこで試合終了[しあいしゅうりょう]',
      titleEn: '"If You Give Up, the Game Is Over"',
      punch: 'Coach Anzai (安西先生) of the 1990s basketball manga スラムダンク says this to a desperate player, and it became a national pep talk — quoted to students, salarymen and dieters alike. Grammar: 〜たら sets up the condition ("once you give up"), and そこで ("right there, at that point") makes the consequence immediate.',
      sentences: [
        { jp: 'バスケットボール の マンガ 「 スラムダンク 」 に 、 安西[あんざい]先生[せんせい] と いう>言う 優[やさ]しい 監督[かんとく] が 出[で]て>出る くる 。', en: 'The basketball manga Slam Dunk has a gentle coach called Coach Anzai.',
          grammar: ['to-iu-name:安西先生という', 'te-kuru:出てくる'] },
        { jp: '試合[しあい] に 負[ま]けそう>負ける に なった>なる 選手[せんしゅ] に 、 先生[せんせい] は こう 言[い]う 。', en: 'To a player about to lose a game, he says:',
          grammar: ['sou-ni-naru:負けそうになった', 'relative-clause:負けそうになった選手'] },
        { jp: '「 あきらめたら>あきらめる そこ で 試合[しあい] 終了[しゅうりょう] です よ 。 」', en: '"If you give up, the game is over right there."',
          grammar: ['tara:あきらめたら'] },
        { jp: '今[いま] で は 、 宿題[しゅくだい] や ダイエット や 締[し]め切[き]り の 前[まえ] に 、 みんな が この 言葉[ことば] を 使[つか]う 。', en: 'Now everyone uses the line when facing homework, diets and deadlines.',
          grammar: ['ya-and:宿題やダイエットや締め切り', 'mae-ni:締め切りの前に'] },
        { jp: '夜中[よなか] の 二時[にじ] 。 レポート は まだ 半分[はんぶん] しか 書[か]けて>書く いない>いる 。', en: '2 a.m. The report is still only half written.',
          grammar: ['shika-nai:半分しか書けていない', 'potential:書けて'] },
        { jp: 'でも 、 あきらめたら>あきらめる そこ で 試合[しあい] 終了[しゅうりょう] だ 。 コーヒー を もう 一杯[いっぱい] 飲[の]もう>飲む 。', en: 'But if I give up, the game is over. Time for one more cup of coffee.',
          grammar: ['tara:あきらめたら', 'volitional:飲もう'] },
      ],
    },
    {
      id: 'meme-n3-nigecha',
      level: 'n3',
      kind: 'pop',
      emoji: '🤖😰',
      title: '逃[に]げちゃダメだ',
      titleEn: '"I Mustn\'t Run Away"',
      punch: 'Shinji Ikari repeats 逃げちゃダメだ while forcing himself into the cockpit in 新世紀エヴァンゲリオン (1995), and the line is now quoted by anyone talking themselves into something they dread — Monday mornings especially. 〜ちゃ is the spoken contraction of 〜ては (〜じゃ for 〜では), so 逃げちゃダメだ = 逃げてはダメだ.',
      sentences: [
        { jp: '「 エヴァンゲリオン 」 の 主人公[しゅじんこう] 、 シンジくん は 、 巨大[きょだい] ロボット に 乗[の]る よう に 言[い]われる>言う 。', en: 'Shinji, the hero of Evangelion, is told to pilot a giant robot.',
          grammar: ['you-ni-iu:乗るように言われる', 'passive:言われる'] },
        { jp: '怖[こわ]くて>怖い たまらない が 、 彼[かれ] は 何度[なんど] も 自分[じぶん] に 言[い]い聞[き]かせる>言い聞かせる 。', en: 'He\'s terrified, but tells himself over and over:',
          grammar: ['tamaranai:怖くてたまらない', 'ga-but:たまらないが'] },
        { jp: '「 逃[に]げちゃ>逃げる ダメ だ 、 逃[に]げちゃ>逃げる ダメ だ … 」', en: '"I mustn\'t run away, I mustn\'t run away…"',
          grammar: ['cha-dame:逃げちゃダメだ'] },
        { jp: '日本[にほん] の 会社員[かいしゃいん] は 、 月曜日[げつようび] の 朝[あさ] に この セリフ を つぶやく らしい 。', en: 'Apparently Japanese office workers mutter this line on Monday mornings.',
          grammar: ['rashii:つぶやくらしい', 'ni-time:朝に'] },
        { jp: '「 会社[かいしゃ] から 逃[に]げちゃ>逃げる ダメ だ … 」', en: '"I mustn\'t run away from work…"',
          grammar: ['cha-dame:逃げちゃダメだ', 'kara-from:会社から'] },
        { jp: 'ちなみに 、 「 ちゃ 」 は 「 ては 」 の 短[みじか]い 言[い]い方[かた] だ 。', en: 'By the way, "-cha" is just a short way of saying "-te wa".',
          grammar: ['cha-dame', 'i-adj-noun:短い言い方'] },
      ],
    },
    {
      id: 'meme-n3-flag',
      level: 'n3',
      kind: 'meme',
      emoji: '🚩⚔️',
      title: '死亡[しぼう]フラグ',
      titleEn: 'Death Flags',
      punch: 'フラグ ("flag") comes from video games, where setting a flag triggers a later event. A 死亡フラグ is a line that sets up a character\'s death — talking about the future, like getting married after the war, is the classic. Saying フラグを立てる ("raising a flag") about real life means "careful, you just jinxed it". There are also 恋愛フラグ (romance flags), and フラグを折る — "breaking the flag" — means dodging your fate.',
      sentences: [
        { jp: 'マンガ や 映画[えいが] に は 、 「 この 人[ひと] は もうすぐ 死[し]ぬ な>な(feeling) 」 と わかる セリフ が ある 。', en: 'Manga and films have lines that tell you "this character is about to die".',
          grammar: ['ya-and:マンガや映画', 'relative-clause:」とわかるセリフ'] },
        { jp: 'それ を 「 死亡[しぼう] フラグ 」 と 呼[よ]ぶ 。', en: 'That\'s called a "death flag".',
          grammar: ['to-quote:「死亡フラグ」と呼ぶ'] },
        { jp: '一番[いちばん] 有名[ゆうめい] な の は 、 これ だ 。 「 この 戦[たたか]い が 終[お]わったら>終わる 、 俺[おれ] 、 結婚[けっこん] する ん だ 。 」', en: 'The most famous one is this: "When this battle\'s over, I\'m getting married."',
          grammar: ['no-wa:有名なのは', 'tara:終わったら', 'n-desu:するんだ'] },
        { jp: '「 ここ は 俺[おれ] に 任[まか]せて>任せる 、 先[さき] に 行[い]け>行く ！ 」 も 危[あぶ]ない 。', en: '"Leave this to me — go on ahead!" is dangerous too.',
          grammar: ['meirei:行け', 'mo-also:」も'] },
        { jp: '敵[てき] を 倒[たお]した>倒す と 思[おも]って>思う 「 やった>やる か ！ ？ 」 と 言[い]う と 、 だいたい 倒[たお]せて>倒す いない>いる 。', en: 'And if someone thinks they\'ve beaten the enemy and shouts "Did we get him?!", they usually haven\'t.',
          grammar: ['to-omou:倒したと思って', 'to-conditional:言うと', 'potential:倒せて'] },
        { jp: 'だから 、 友[とも]だち が 「 明日[あした] 、 告白[こくはく]する>告白する ん だ 」 と 言[い]う と 、 オタク は 「 フラグ を 立[た]てる な>な(prohibit) ！ 」 と 心配[しんぱい] する 。', en: 'So when a friend says "I\'m confessing my feelings tomorrow," otaku panic: "Don\'t raise a flag!"',
          grammar: ['to-conditional:言うと', 'na-prohibitive:立てるな'] },
      ],
    },
    {
      id: 'meme-n3-chuuni',
      level: 'n3',
      kind: 'slang',
      emoji: '🦾🌑',
      title: '中二病[ちゅうにびょう]',
      titleEn: '"Eighth-Grader Syndrome"',
      punch: '中二病 ("second-year-of-middle-school disease") was coined by comedian 伊集院光 on his radio show in 1999 for the cringe-worthy phase of believing you\'re secretly special — dark powers, a sealed eye, a cursed right arm. Today it\'s a whole anime genre and a gentle tease among adults: "that\'s so chūni".',
      sentences: [
        { jp: '「 中二病[ちゅうにびょう] 」 は 本当[ほんとう] の 病気[びょうき] で は ない 。', en: '"Chūnibyō" isn\'t a real illness.',
          grammar: ['plain-form:病気ではない'] },
        { jp: '中学[ちゅうがく] 二年生[にねんせい] ぐらい の 子[こ] が よく する 、 ちょっと 恥[は]ずかしい 言動[げんどう] の こと だ 。', en: 'It means the slightly embarrassing things kids around 14 tend to say and do.',
          grammar: ['gurai:二年生ぐらい', 'no-koto:言動のこと'] },
        { jp: '例[たと]えば 、 包帯[ほうたい] を 巻[ま]いた>巻く 右手[みぎて] を 押[お]さえて>押さえる 、 「 くっ … 右手[みぎて] が うずく … 」 と 言[い]う 。', en: 'Like clutching your bandaged right hand and groaning, "Ngh… my right hand… it throbs…"',
          grammar: ['relative-clause:包帯を巻いた右手', 'to-quote:」と言う'] },
        { jp: '「 俺[おれ] の 中[なか] に は 、 闇[やみ] の 力[ちから] が 眠[ねむ]って>眠る いる 」 と 本気[ほんき] で 信[しん]じる 子[こ] も いる 。', en: 'Some kids honestly believe "a power of darkness sleeps within me".',
          grammar: ['te-iru:眠っている', 'ni-wa:中には'] },
        { jp: '大人[おとな] に なって>なる から 昔[むかし] の ノート を 見[み]る と 、 恥[は]ずかしくて>恥ずかしい 死[し]に>死ぬ そう に なる 。', en: 'Grow up, find your old notebooks, and you could die of embarrassment.',
          grammar: ['te-kara:なってから', 'kute:恥ずかしくて', 'sou-ni-naru:死にそうになる'] },
        { jp: '自分[じぶん] で 考[かんが]えた>考える 必殺技[ひっさつわざ] の 名前[なまえ] が 、 たくさん 書[か]いて>書く ある から だ 。', en: 'Because they\'re full of names for special attacks you invented yourself.',
          grammar: ['relative-clause:自分で考えた必殺技', 'te-aru:書いてある'] },
      ],
    },
    {
      id: 'meme-n3-shachiku',
      level: 'n3',
      kind: 'slang',
      emoji: '🐑🏢',
      title: '社畜[しゃちく]の一日[いちにち]',
      titleEn: 'A Day in the Life of "Company Livestock"',
      punch: '社畜 = 会社 (company) + 家畜 (livestock): a worker so thoroughly tamed by the company that they no longer notice. It lives alongside ブラック企業 ("black company", an exploitative employer) in Japanese work slang. The punchline: insisting that you simply love your company is exactly what a shachiku would say.',
      sentences: [
        { jp: '「 社畜[しゃちく] 」 は 「 会社[かいしゃ] 」 と 「 家畜[かちく] 」 を 合[あ]わせた>合わせる 言葉[ことば] だ 。', en: '"Shachiku" combines "company" and "livestock".',
          grammar: ['relative-clause:合わせた言葉', 'to-and:「会社」と「家畜」'] },
        { jp: '会社[かいしゃ] に 飼[か]われて>飼う いる よう に 働[はたら]く 人[ひと] の こと だ 。', en: 'It means people who work as if they were being kept by their company.',
          grammar: ['passive:飼われている', 'no-koto:人のこと'] },
        { jp: '朝[あさ] 六時[ろくじ] 、 満員電車[まんいんでんしゃ] に 押[お]し込[こ]まれる>押し込む 。', en: '6 a.m.: crammed into a packed train.',
          grammar: ['passive:押し込まれる'] },
        { jp: '夜[よる] 十一時[じゅういちじ] 、 部長[ぶちょう] が 帰[かえ]る まで 帰[かえ]れない>帰る 。', en: '11 p.m.: can\'t leave until the boss does.',
          grammar: ['made:帰るまで', 'potential:帰れない'] },
        { jp: '休[やす]み の 日[ひ] に も 、 上司[じょうし] から の メール に すぐ 返事[へんじ] して>する しまう 。', en: 'Even on days off, he ends up answering his boss\'s emails instantly.',
          grammar: ['te-shimau:返事してしまう', 'kara-from:上司からの'] },
        { jp: '友[とも]だち に 「 それ 、 社畜[しゃちく] だ よ 」 と 言[い]われて>言う 、 彼[かれ] は 「 社畜[しゃちく] じゃ>じゃ(neg) ない ！ 会社[かいしゃ] が 好[す]き な だけ だ ！ 」 と 答[こた]えた>答える 。', en: 'When a friend told him "Dude, you\'re shachiku," he replied: "I\'m not livestock! I just like my company!"',
          grammar: ['passive:言われて', 'dake:好きなだけ'] },
        { jp: '… その 返事[へんじ] が 、 一番[いちばん] 社畜[しゃちく] っぽい 。', en: '…which is the most shachiku answer of all.',
          grammar: ['ppoi:社畜っぽい', 'ichiban:一番'] },
      ],
    },
    {
      id: 'meme-n3-kuuki',
      level: 'n3',
      kind: 'slang',
      emoji: '😶🌫️',
      title: '空気[くうき]が読[よ]めない',
      titleEn: 'Can\'t Read the Air',
      punch: '空気を読む ("reading the air") means picking up what nobody says out loud — when to stay quiet, when to leave, what the group wants. Failing at it got you labelled KY (空気 Kūki 読めない Yomenai), a buzzword around 2007. Japanese loves romaji acronyms like this: JK = 女子高生 (high-school girl), MK5 = マジでキレる5秒前 ("five seconds from losing it").',
      sentences: [
        { jp: '日本[にほん] で は 、 その 場[ば] の 雰囲気[ふんいき] を 感[かん]じる こと を 「 空気[くうき] を 読[よ]む 」 と いう>言う 。', en: 'In Japan, sensing the mood of a situation is called "reading the air".',
          grammar: ['koto-nominalizer:感じること', 'to-quote:「空気を読む」という'] },
        { jp: '空気[くうき] を 読[よ]めない>読む 人[ひと] は 、 昔[むかし] 「 KY 」 と 呼[よ]ばれて>呼ぶ いた>いる 。', en: 'People who couldn\'t read the air used to be called "KY".',
          grammar: ['potential:読めない', 'passive:呼ばれていた'] },
        { jp: '「 K 」 は 空気[くうき] 、 「 Y 」 は 読[よ]めない>読む の 頭文字[かしらもじ] だ 。', en: 'K for kūki (air), Y for yomenai (can\'t read).',
          grammar: ['wa-contrast:「Y」は'] },
        { jp: '例[たと]えば 、 会議[かいぎ] が やっと 終[お]わり>終わる そう な とき に 「 質問[しつもん] が 三[みっ]つ あります>ある 」 と 手[て] を 挙[あ]げる 人[ひと] は 、 たいてい KY だ と 思[おも]われる>思う 。', en: 'For example, someone who raises their hand just as a meeting is finally wrapping up and says "I have three questions" will usually be seen as KY.',
          grammar: ['sou-looks:終わりそう', 'passive:思われる'] },
        { jp: '逆[ぎゃく] に 、 空気[くうき] を 読[よ]み>読む すぎて>すぎる 何[なに] も 言[い]えない>言う 人[ひと] も いる 。', en: 'On the other hand, some people read the air so hard they can\'t say anything at all.',
          grammar: ['sugiru:読みすぎて', 'potential:言えない'] },
        { jp: '「 今日[きょう] の 飲[の]み会[かい] 、 みんな 静[しず]か だ ね 。 … 空気[くうき] 、 読[よ]み>読む すぎ>すぎ(too) じゃ>じゃ(neg) ない ？ 」', en: '"Everyone\'s so quiet at tonight\'s drinks… Aren\'t we reading the air a bit too much?"',
          grammar: ['sugiru:読みすぎ'] },
      ],
    },
    {
      id: 'meme-n3-tokisoba',
      level: 'n3',
      kind: 'story',
      emoji: '🍜🪙',
      title: '時[とき]そば',
      titleEn: 'Time Soba (a Rakugo Classic)',
      punch: 'In Edo-period timekeeping the night hours ran 四つ (about 10 p.m.), 九つ (midnight), 八つ… The first man asks the time right after "eight", so the owner\'s "nine" replaces one coin in his count: he pays 15 mon for 16-mon soba while seeming to pay in full. The copycat comes earlier, hears "four", and has to count 5, 6, 7, 8 again — paying four extra. 時そば is one of the best-known rakugo stories.',
      sentences: [
        { jp: '落語[らくご] は 、 一人[ひとり] の 話[はな]し手[て] が 座[すわ]った>座る まま 、 扇子[せんす] と 手[て]ぬぐい だけ で 演[えん]じる 笑[わら]い話[ばなし] だ 。', en: 'Rakugo is comic storytelling performed by a single seated storyteller, using only a fan and a cloth.',
          grammar: ['mama:座ったまま', 'dake:手ぬぐいだけ'] },
        { jp: 'ある>ある(certain) 夜[よる] 、 男[おとこ] が 屋台[やたい] で そば を 食[た]べて>食べる 、 お金[かね] を 払[はら]う 。', en: 'One night, a man eats soba at a street stall and pays.',
          grammar: ['de-place:屋台で', 'te-sequence:食べて'] },
        { jp: '「 一[ひと]つ 、 二[ふた]つ 、 三[みっ]つ … 八[やっ]つ 、 今[いま] 何時[なんどき]>何時(なんどき) だい ？ 」', en: '"One, two, three… eight — say, what time is it?"',
          grammar: ['counters:一つ', 'dai-question:何時だい'] },
        { jp: '店主[てんしゅ] が 「 九[ここの]つ です 」 と 答[こた]える と 、 男[おとこ] は 「 十[とお]>十(とお) 、 十一[じゅういち] … 」 と 続[つづ]けた>続ける 。', en: 'The owner answers "The ninth hour," and the man carries on counting: "Ten, eleven…"',
          grammar: ['to-conditional:答えると', 'to-quote:」と続けた'] },
        { jp: 'こうして 、 一文[いちもん] 得[とく] を した>する の>の(explain) だ 。', en: 'And just like that, he saves one coin.',
          grammar: ['plain-form:得をした'] },
        { jp: 'それ を 見[み]て>見る いた>いる 別[べつ] の 男[おとこ] が 、 次[つぎ] の 日[ひ] 、 まね を しよう>する と した>する 。', en: 'Another man who had watched this tried to copy him the next day.',
          grammar: ['relative-clause:見ていた別の男', 'you-to-suru:しようとした'] },
        { jp: 'でも 、 その 男[おとこ] は 早[はや]い 時間[じかん] に 来[き]て>来る しまった>しまう 。', en: 'But he showed up too early.',
          grammar: ['te-shimau:来てしまった'] },
        { jp: '「 … 八[やっ]つ 、 今[いま] 何時[なんどき]>何時(なんどき) だい ？ 」 「 四[よっ]つ です 」 「 五[いつ]つ 、 六[むっ]つ 、 七[なな]つ 、 八[やっ]つ … 」', en: '"…Eight — what time is it?" "The fourth hour." "Five, six, seven, eight…"',
          grammar: ['dai-question:何時だい', 'counters:四つ'] },
        { jp: '結局[けっきょく] 、 彼[かれ] は 損[そん] を して>する しまった>しまう 。', en: 'In the end, he lost out.',
          grammar: ['te-shimau:してしまった'] },
      ],
    },
    {
      id: 'meme-n3-manjuu',
      level: 'n3',
      kind: 'story',
      emoji: '🍡😨',
      title: 'まんじゅうこわい',
      titleEn: 'I\'m Scared of Manjū',
      punch: 'A classic rakugo tale. The man fakes a fear of まんじゅう (sweet buns filled with red bean paste) — actually his favourite food — so his friends "punish" him with a free feast. The final line is the 落ち (ochi, punchline): after all those sweets, the thing he\'s "terrified" of now is a cup of tea to wash them down.',
      sentences: [
        { jp: '若者[わかもの] たち が 集[あつ]まって>集まる 、 自分[じぶん] の 怖[こわ]い もの を 話[はな]して>話す いた>いる 。', en: 'A group of young men had gathered and were talking about the things they feared.',
          grammar: ['te-iru:話していた', 'te-sequence:集まって'] },
        { jp: '「 俺[おれ] は ヘビ が 怖[こわ]い 」 「 俺[おれ] は クモ だ 」', en: '"I\'m scared of snakes." "For me, it\'s spiders."',
          grammar: ['wa-ga:俺はヘビが怖い'] },
        { jp: '一人[ひとり] だけ 、 「 怖[こわ]い もの なんか ない 」 と 言[い]う 男[おとこ] が いた>いる 。', en: 'Just one man claimed there was nothing he was afraid of.',
          grammar: ['dake:一人だけ', 'relative-clause:」と言う男'] },
        { jp: 'でも 、 しつこく>しつこい 聞[き]かれる>聞く と 、 小[ちい]さい 声[こえ] で 「 実[じつ]は 、 まんじゅう が 怖[こわ]い 」 と 言[い]った>言う 。', en: 'But when they kept pressing him, he said in a small voice, "Actually… I\'m scared of manjū."',
          grammar: ['passive:聞かれる', 'to-conditional:聞かれると', 'ku-adverb:しつこく'] },
        { jp: 'みんな は 彼[かれ] を からかう ため に 、 まんじゅう を たくさん 買[か]って>買う きて>くる 、 部屋[へや] に 投[な]げ込[こ]んだ>投げ込む 。', en: 'To tease him, they bought a pile of manjū and threw them into his room.',
          grammar: ['tame-ni:からかうために', 'te-kuru:買ってきて'] },
        { jp: '「 こわい>怖い ！ こわい>怖い ！ 」 と 叫[さけ]び>叫ぶ ながら 、 男[おとこ] は まんじゅう を 全部[ぜんぶ] 食[た]べて>食べる しまった>しまう 。', en: 'Screaming "So scary! So scary!", the man ate every last one.',
          grammar: ['nagara:叫びながら', 'te-shimau:食べてしまった'] },
        { jp: '「 本当[ほんとう] は 何[なに] が 怖[こわ]い ん だ ！ 」 と 聞[き]く と 、 男[おとこ] は 答[こた]えた>答える 。', en: '"What are you REALLY afraid of?!" they demanded. The man answered:',
          grammar: ['n-desu:怖いんだ', 'to-conditional:聞くと'] },
        { jp: '「 今[いま] は 、 熱[あつ]い お茶[ちゃ] が 一杯[いっぱい] 怖[こわ]い 。 」', en: '"Right now, I\'m terrified of a nice hot cup of tea."',
          grammar: ['wa-contrast:今は', 'ga-subject:お茶が'] },
      ],
    },
  ];

  // Add the meme-only words and grammar to the stories' shared tables, never
  // overwriting an existing entry.
  const glossary = global.STORY_GLOSSARY || (global.STORY_GLOSSARY = {});
  Object.keys(global.MEME_GLOSSARY).forEach(key => {
    if (!Object.prototype.hasOwnProperty.call(glossary, key)) glossary[key] = global.MEME_GLOSSARY[key];
  });
  const grammar = global.STORY_GRAMMAR || (global.STORY_GRAMMAR = {});
  Object.keys(global.MEME_GRAMMAR).forEach(id => {
    if (!Object.prototype.hasOwnProperty.call(grammar, id)) grammar[id] = global.MEME_GRAMMAR[id];
  });
})(window);
