(function (global) {
  'use strict';

  // ことば探偵クロ — "Kuro, Word Detective" (mystery.html): a mystery told
  // in Japanese, where the player moves the story on by answering in Japanese.
  //
  // Every chapter is a list of steps, played in order:
  //   say        a line of dialogue (who: a CAST key, or 'narr' for narration)
  //   place      a change of scene
  //   clue       a piece of evidence goes into the case file
  //   fill       a line with one blank ({_}) to type in
  //   ask        a whole sentence to type, from an English instruction
  //   meaning    a comprehension question answered in English
  //   riddle     a なぞなぞ or kanji puzzle (Layton style)
  //   testimony  find the statement that doesn't hold up (Ace Attorney style)
  //
  // Japanese is written in 漢字[かんじ] furigana markup. Typed answers match
  // with each kanji word written either way, so 時計台[とけいだい]の鍵[かぎ]
  // also accepts とけいだいのかぎ and 時計台のかぎ. Katakana and hiragana
  // count as the same, and spaces and punctuation are ignored.
  //
  // The chapters get harder: the first two are N5 with spaces between words
  // (like a children's game), the last two N4–N3 written normally.

  const CAST = {
    kuro: {
      name: 'クロ', en: 'Kuro', face: '🐈‍⬛', color: '#4b4466',
      role: 'Detective',
      bio: 'A black cat in a deerstalker and the shopping street’s only detective. Speaks nothing but Japanese, adores fish, and says にゃるほど when the pieces click.',
    },
    hana: {
      name: 'ハナ', en: 'Hana', face: '👩‍🍳', color: '#e8643f',
      role: 'Baker',
      bio: 'Runs Fuwafuwa Bakery with boundless energy. Famous for her melon pan; less famous for closing windows.',
    },
    kenta: {
      name: 'ケンタ', en: 'Kenta', face: '👦', color: '#3f9d52',
      role: 'Riddle collector',
      bio: 'Hana’s little brother, nine years old. Trades secrets for riddles — solve his なぞなぞ and he’ll tell you what he saw.',
    },
    gonta: {
      name: 'ゴンタ刑事', en: 'Detective Gonta', face: '👮', color: '#3a57a6',
      role: 'Police detective',
      bio: 'Big, loud and certain. Solves every case in five seconds — wrongly. Ends his sentences with a tough-guy だぜ.',
    },
    tanuki: {
      name: '田貫さん', en: 'Mr. Tanuki', face: '👴', color: '#8a6a3d',
      role: 'Bookseller',
      bio: 'Sleepy owner of the secondhand bookshop. Yawns mid-sentence and calls himself わし, like old men in anime.',
    },
    tokita: {
      name: '時田さん', en: 'Mr. Tokita', face: '👨‍🔧', color: '#6a6878',
      role: 'Clockmaker',
      bio: 'Has wound the street’s clock tower every single morning for forty years.',
    },
    kitsune: {
      name: '狐塚夫人', en: 'Madame Kitsunezuka', face: '🦊', color: '#c9930c',
      role: 'Antique dealer',
      bio: 'Elegant chair of the shopping street association. Speaks flawless 敬語 and cannot resist setting puzzles for Kuro.',
    },
    mame: {
      name: 'マメ', en: 'Mame', face: '🧑', color: '#d9678f',
      role: 'Assistant',
      bio: 'Madame Kitsunezuka’s nervous young assistant. Very careful with antiques. Usually.',
    },
    uozumi: {
      name: '魚住さん', en: 'Mr. Uozumi', face: '🧔', color: '#2a8bb0',
      role: 'Fishmonger',
      bio: 'Shouts every sentence as if he’s selling tuna at five in the morning.',
    },
    ume: {
      name: 'ウメさん', en: 'Granny Ume', face: '👵', color: '#7a5aa6',
      role: 'Fishmonger’s mother',
      bio: 'Sweet, forgetful, and secretly feeds every cat on the street.',
    },
    karasu: {
      name: 'カラス', en: 'The Crow', face: '🐦', color: '#2b2b33',
      role: '???',
      bio: 'Lives on the bookshop roof. Has excellent taste in bread.',
    },
  };

  const say = (who, ja, en) => ({ type: 'say', who, ja, en });
  const narr = (ja, en) => ({ type: 'say', who: 'narr', ja, en });
  const place = (ja, en) => ({ type: 'place', ja, en });
  const clue = (id, name, en, desc) => ({ type: 'clue', id, name, en, desc });

  const CHAPTERS = [
    // ─── Chapter 1 ───────────────────────────────────────────────────────────
    {
      id: 'melonpan',
      num: 1,
      level: 'N5',
      title: '消[き]えた メロンパン',
      en: 'The Vanishing Melon Pan',
      intro: 'Every morning, Hana’s melon pan vanishes from the bakery window. Detective Gonta already has a suspect. Kuro has a brand-new assistant: you.',
      skills: 'Particles · days of the week · あります / います · counters',
      steps: [
        place('クロ探偵[たんてい] 事務所[じむしょ]', 'Kuro’s detective office'),
        say('kuro', 'にゃあ。わたしは クロ。この 商店街[しょうてんがい]の 探偵[たんてい]です。', 'Meow. I’m Kuro, the detective of this shopping street.'),
        say('kuro', 'きみが 新[あたら]しい 助手[じょしゅ]ですね。', 'So you’re my new assistant.'),
        say('kuro', 'わたしは 日本語[にほんご]しか 話[はな]しません。だから、きみも 日本語[にほんご]で 答[こた]えてください。', 'I speak only Japanese. So please answer in Japanese too.'),
        say('kuro', 'ローマ字[じ]で 書[か]いても だいじょうぶ。ひらがなに なりますよ。', 'It’s fine to type in romaji — it turns into hiragana as you go.'),
        {
          type: 'ask', who: 'kuro',
          prompt: 'Greet Kuro properly: “Nice to meet you” (literally, “please treat me well”).',
          answers: [
            'よろしくお願[ねが]いします', 'どうぞよろしくお願[ねが]いします',
            'はじめましてよろしくお願[ねが]いします', 'はじめましてどうぞよろしくお願[ねが]いします',
            'よろしくお願[ねが]いいたします',
          ],
          hint: 'It starts with よろしく… and ends with …します. Type: yoroshiku onegaishimasu',
          note: 'よろしくお願いします is what you say when you start working with someone. Plain よろしく is the casual version — a bit cheeky on your first day.',
        },
        say('kuro', 'よろしく。では、さっそく…', 'Likewise. Now then, let’s get—'),
        narr('バタン！ ドアが 開[あ]きました。', 'Bang! The door flies open.'),
        say('hana', 'クロさん！ たいへんです！', 'Kuro! Something terrible has happened!'),
        say('hana', 'わたしの メロンパンが、また なくなりました！', 'My melon pan has disappeared again!'),
        say('kuro', 'また？', 'Again?'),
        say('hana', 'はい。月曜日[げつようび]も 火曜日[かようび]も なくなりました。そして 今日[きょう]も！', 'Yes. It disappeared on Monday, and on Tuesday. And today too!'),
        {
          type: 'meaning', who: 'kuro',
          prompt: 'Kuro checks that you followed. In English: what keeps disappearing?',
          answers: ['melon pan', 'melonpan', 'melon-pan', 'melon bread', 'melon bun', 'melon', 'bread', 'bun'],
          hint: 'メ・ロ・ン・パ・ン. パン (bread) comes from Portuguese.',
          note: 'メロンパン is a sweet bun with a crisp cookie crust, named for its melon-like look. There’s usually no melon in it at all.',
        },
        {
          type: 'fill', who: 'kuro',
          ja: 'ふむ。今日[きょう]は {_} ですね。',
          en: 'Hmm. So today is ___.',
          prompt: 'Monday, Tuesday… and today. Three mornings in a row. What day is it today?',
          answers: ['水曜日[すいようび]', '水曜[すいよう]'],
          hint: 'Monday is 月曜日, Tuesday 火曜日. The next day is named after water: 水 (すい).',
          note: 'The week: 月 moon, 火 fire, 水 water, 木 wood, 金 gold, 土 earth, 日 sun — each plus 曜日 (ようび).',
        },
        say('kuro', 'では、パン屋[や]へ 行[い]きましょう。', 'Then let’s go to the bakery.'),

        place('パン屋[や]「ふわふわ」', 'Fuwafuwa Bakery'),
        say('hana', '毎朝[まいあさ] 七時[しちじ]に、メロンパンを 窓[まど]の そばに 置[お]きます。さますんです。', 'Every morning at seven, I put the melon pan by the window. To let it cool.'),
        say('hana', 'でも、七時半[しちじはん]に 見[み]ると、ありません。', 'But when I look at half past seven, it’s gone.'),
        {
          type: 'fill', who: 'kuro',
          ja: '窓[まど]{_}そば、ですか。見[み]てみましょう。',
          en: 'By the window, you say? Let’s take a look.',
          prompt: 'Which particle joins the two nouns 窓 (window) and そば (side)?',
          answers: ['の'],
          hint: 'It’s the same particle as in わたしの メロンパン.',
          note: 'の joins two nouns: 窓のそば is “the window’s side”, so “by the window”.',
        },
        narr('窓[まど]の そばに、何[なに]か 落[お]ちて います。', 'Something is lying by the window.'),
        say('kuro', 'おや？ これは…黒[くろ]い 羽[はね]ですね。', 'Oh? This is… a black feather.'),
        say('hana', 'クロさんの 毛[け]じゃ ありませんか？', 'Isn’t that your fur, Kuro?'),
        say('kuro', 'ちがいます。わたしの 毛[け]は もっと きれいです。', 'It is not. My fur is far prettier.'),
        clue('feather', '黒[くろ]い 羽[はね]', 'Black feather', 'Found by the bakery window this morning. Definitely not cat fur.'),
        say('gonta', 'おう、クロ！ 犯人[はんにん]は もう わかったぜ！', 'Hey, Kuro! I’ve already worked out who did it!'),
        say('gonta', 'となりの 本屋[ほんや]の 田貫[たぬき]さんだ！', 'It’s Mr. Tanuki from the bookshop next door!'),
        say('tanuki', 'ふぁあ…わしですか？', '*Yaaawn*… Me?'),
        say('kuro', '…どうして ですか、ゴンタ刑事[けいじ]。', '…And why is that, Detective Gonta?'),
        {
          type: 'testimony', who: 'gonta',
          title: 'ゴンタ刑事[けいじ]の 証言[しょうげん]',
          titleEn: 'Detective Gonta’s testimony',
          prompt: 'One of these statements clashes with the evidence in your case file. Which one?',
          lines: [
            { ja: 'おれは 毎朝[まいあさ]、この 道[みち]を 歩[ある]くぜ。', en: 'I walk down this street every morning.',
              no: ['kuro', 'それは 本当[ほんとう]でしょう。ゴンタ刑事[けいじ]は いつも ここに いますから。', 'That’s probably true. Gonta is always around here.'] },
            { ja: '今朝[けさ] 七時半[しちじはん]、田貫[たぬき]さんが パン屋[や]の 前[まえ]に いた。', en: 'This morning at 7:30, Mr. Tanuki was in front of the bakery.',
              no: ['tanuki', 'ええ、いましたよ。パンを 買[か]いに 来[き]たんです。', 'Yes, I was. I’d come to buy bread.'] },
            { ja: '田貫[たぬき]さんは 白[しろ]い セーターを 着[き]て いた。', en: 'Mr. Tanuki was wearing a white sweater.',
              no: ['kuro', 'たしかに、白[しろ]い セーターですね。', 'It certainly is a white sweater.'] },
            { ja: 'そして、窓[まど]の そばに 白[しろ]い 毛[け]が あったぜ！', en: 'And there was white fluff by the window!' },
          ],
          wrong: 3,
          hint: 'Open your case file. What did you actually find by the window?',
        },
        {
          type: 'fill', who: 'you',
          ja: '窓[まど]の そばに あったのは、白[しろ]い 毛[け]じゃ ありません。{_} 羽[はね]です！',
          en: 'What was by the window wasn’t white fluff. It was a ___ feather!',
          prompt: 'Present the evidence! What colour was the feather? (an い-adjective)',
          answers: ['黒[くろ]い'],
          hint: 'The same 黒 as in Kuro’s own name — クロ means “black”.',
          note: 'Colour words like 黒い, 白い and 赤い are い-adjectives and go straight in front of the noun: 黒い羽.',
        },
        say('gonta', 'ぐぬぬ…！', 'Grrr…!'),
        say('tanuki', 'わしは パンを 買[か]いに 来[き]た だけですよ…ふぁあ。', 'I only came to buy bread… *yawn*.'),
        say('kenta', 'ねえねえ、探偵[たんてい]さん！', 'Hey, hey, Mr. Detective!'),
        say('hana', '弟[おとうと]の ケンタです。なぞなぞが 大好[だいす]きなんです。', 'This is my little brother, Kenta. He loves riddles.'),
        say('kenta', 'ぼくの なぞなぞに 答[こた]えたら、ひみつを 教[おし]えて あげる！', 'If you answer my riddle, I’ll tell you a secret!'),
        {
          type: 'riddle', who: 'kenta',
          title: 'ナゾ その1',
          ja: 'パンは パンでも、食[た]べられない パンは なーんだ？',
          en: 'It’s a パン, but you can’t eat it. Which パン is it?',
          answers: ['フライパン'],
          hint: 'You find it in the kitchen and fry eggs in it. Its name ends in …パン.',
          note: 'フライパン, a frying pan! “Xは Xでも…” (“it’s an X, but…”) is the classic opening of a Japanese なぞなぞ.',
        },
        say('kenta', 'せいかい！ じゃあ、ひみつ。毎朝[まいあさ]、本屋[ほんや]の 屋根[やね]で「カー、カー」って 声[こえ]が するよ。', 'Correct! Here’s the secret: every morning there’s a “caw, caw” up on the bookshop roof.'),
        say('kuro', 'にゃるほど…。助手[じょしゅ]くん、田貫[たぬき]さんに 聞[き]いて ください。', 'Nyaruhodo… Assistant, ask Mr. Tanuki about it.'),
        {
          type: 'ask', who: 'kuro',
          prompt: 'Ask Mr. Tanuki: “What is on the roof?” Whatever is up there is alive, so use います, not あります.',
          answers: [
            '屋根[やね]に何[なに]がいますか', '屋根[やね]の上[うえ]に何[なに]がいますか', '屋根[やね]には何[なに]がいますか',
            '屋根[やね]に何[なに]かいますか', '屋根[やね]の上[うえ]に何[なに]かいますか', '屋根[やね]の上[うえ]には何[なに]がいますか',
          ],
          hint: 'Place + に + 何が + います + か. Roof is 屋根 (やね).',
          note: 'います is for living things (people, animals), あります for objects. 何がいますか asks “what’s there?”; 何かいますか asks “is anything there?” Both work.',
        },
        say('tanuki', '屋根[やね]？ カラスの 巣[す]が ありますよ。毎朝[まいあさ] うるさくて…ふぁあ。', 'The roof? There’s a crow’s nest. It’s noisy every morning… *yawn*.'),

        place('本屋[ほんや]の 屋根[やね]', 'The bookshop roof'),
        narr('はしごで 屋根[やね]に 上[のぼ]りました。', 'You climb a ladder up to the roof.'),
        say('karasu', 'カー！', 'Caw!'),
        {
          type: 'fill', who: 'kuro',
          ja: '見[み]てください！ 巣[す]の 中[なか]に メロンパンが {_} あります！',
          en: 'Look! There are ___ melon pans in the nest!',
          prompt: 'One melon pan a day — Monday, Tuesday, Wednesday. How many are in the nest? Use the native counter 〜つ.',
          answers: ['三[みっ]つ', '3つ', '3'],
          hint: 'ひとつ, ふたつ, …',
          note: 'ひとつ, ふたつ, みっつ, よっつ, いつつ… The つ counter works for almost any object when you don’t know its proper counter.',
        },
        say('kuro', '犯人[はんにん]が わかりました。', 'I know who did it.'),
        {
          type: 'fill', who: 'kuro', accuse: true,
          ja: 'メロンパンを 取[と]ったのは… {_} です！',
          en: 'The one who took the melon pan is… ___!',
          prompt: 'Name the culprit! Black feathers, a nest on the roof, a voice that goes カー…',
          answers: ['カラス'],
          hint: 'In katakana: カ・ラ・ス.',
          note: 'カラス, the crow! Japanese crows are famous for snatching food — especially anything left by an open window.',
        },
        say('karasu', 'カー…。', 'Caw…'),
        say('hana', 'もう！ カラスさん！', 'Honestly! Mr. Crow!'),
        say('tanuki', 'よかった。わしは 犯人[はんにん]じゃ ありませんね。', 'Good. So I’m not the culprit.'),
        say('gonta', 'お、おれも わかってたぜ！ 最初[さいしょ]から！', 'I-I knew it too! From the very start!'),
        say('kuro', '…はいはい。ハナさん、明日[あした]から 窓[まど]を 閉[し]めて くださいね。', '…Sure, sure. Hana, please keep the window shut from tomorrow.'),
        say('hana', 'はい！ お礼[れい]に、メロンパンを どうぞ！', 'Will do! Please have a melon pan as thanks!'),
        say('kuro', 'にゃるほど。事件[じけん]の あとの パンは、おいしいですね。', 'Nyaruhodo. Bread tastes best after a solved case.'),
      ],
    },

    // ─── Chapter 2 ───────────────────────────────────────────────────────────
    {
      id: 'clocktower',
      num: 2,
      level: 'N5',
      title: '止[と]まった 時計台[とけいだい]',
      en: 'The Stopped Clock Tower',
      intro: 'The clock tower over Hidamari Street has stopped, and a strange note built out of kanji is taped to its door. Gonta is calling it a crime notice.',
      skills: 'Telling time · kanji puzzles · て-form · い-adjective past',
      steps: [
        place('商店街[しょうてんがい]の 時計台[とけいだい]', 'The shopping street clock tower'),
        narr('朝[あさ]です。でも、時計台[とけいだい]が 静[しず]かです。', 'It’s morning. But the clock tower is silent.'),
        say('tokita', 'クロさん、見[み]てください。時計[とけい]が 止[と]まって いるんです。', 'Kuro, look. The clock has stopped.'),
        say('kuro', '本当[ほんとう]ですね。針[はり]が 動[うご]いて いません。', 'So it has. The hands aren’t moving.'),
        {
          type: 'fill', who: 'kuro',
          ja: '時計[とけい]は {_} で 止[と]まって いますね。',
          en: 'The clock has stopped at ___.',
          prompt: '🕒 The hands point to 3:15. Say the time in Japanese.',
          answers: ['三時十五分[さんじじゅうごふん]', '3時[じ]15分[ふん]'],
          hint: 'Three o’clock is さんじ. Fifteen minutes is じゅうご + ふん.',
          note: '分 is read ふん after 2, 5, 7 and 9 (ごふん, じゅうごふん) but ぷん after 1, 3, 4, 6, 8 and 10 (さんぷん, じゅっぷん).',
        },
        say('tokita', '四十年[よんじゅうねん]、毎朝[まいあさ] ねじを 巻[ま]いて いますが…こんな ことは はじめてです。', 'I’ve wound it every morning for forty years… this has never happened before.'),
        say('tokita', 'それに、ドアに こんな 手紙[てがみ]が はって ありました。', 'And this letter was stuck to the door.'),
        clue('note', 'ふしぎな 手紙[てがみ]', 'The strange note', '「木[き]」と「木[き]」で 待[ま]って います。「日[ひ]」と「月[つき]」と「日[ひ]」の 三時十五分[さんじじゅうごふん]に。'),
        narr('「木[き]」と「木[き]」で 待[ま]って います。「日[ひ]」と「月[つき]」と「日[ひ]」の 三時十五分[さんじじゅうごふん]に。', '“I will be waiting at ‘tree’ and ‘tree’. At 3:15 on ‘sun’, ‘moon’ and ‘sun’.”'),
        say('gonta', 'これは 犯行予告[はんこうよこく]だぜ！ 大事件[だいじけん]だ！', 'This is a crime notice! It’s a huge case!'),
        say('kuro', '落[お]ち着[つ]いて ください。これは 漢字[かんじ]の なぞなぞです。', 'Calm down. This is a kanji riddle.'),
        {
          type: 'riddle', who: 'kuro',
          title: 'ナゾ その2',
          ja: '「木[き]」と「木[き]」を ならべると、どんな 漢字[かんじ]に なりますか。',
          en: 'Put “tree” (木) next to “tree” (木). Which kanji do you get?',
          answers: ['林[はやし]'],
          hint: 'Two trees are more than one tree but less than a forest (森, もり). It’s read はや…',
          note: '林 (はやし), a grove. Many kanji are built from smaller ones: 木 → 林 → 森. 林 is also a common family name.',
        },
        {
          type: 'riddle', who: 'kuro',
          title: 'ナゾ その3',
          ja: 'では、「日[ひ]」と「月[つき]」を ならべて 一[ひと]つの 漢字[かんじ]に します。その あとに、もう 一[ひと]つ「日[ひ]」。どんな ことばに なりますか。',
          en: 'Now put “sun” (日) beside “moon” (月) to make one kanji, then add another 日 after it. What word do you get?',
          answers: ['明日[あした]', '明日[あす]', '明日[みょうにち]'],
          hint: 'Sun + moon make 明, “bright”. 明 + 日 is a day that hasn’t come yet.',
          note: '明日 — “tomorrow” (あした; more formally あす). 日 + 月 = 明 (bright), and the next bright day is tomorrow.',
        },
        say('kuro', 'にゃるほど。「明日[あした]の 三時十五分[さんじじゅうごふん]に、林[はやし]で 待[ま]って います」。', 'Nyaruhodo. “I’ll be waiting in the grove, tomorrow at 3:15.”'),
        say('tokita', '林[はやし]なら、公園[こうえん]の 北[きた]に ありますよ。', 'There’s a grove just north of the park.'),
        say('gonta', 'わかったぜ！ 犯人[はんにん]は ケンタだ！ なぞなぞが 大好[だいす]きだからな！', 'I’ve got it! The culprit is Kenta! Because he loves riddles!'),
        say('kenta', 'えーっ！？ ぼくじゃ ないよ！', 'Whaaat?! It wasn’t me!'),
        {
          type: 'testimony', who: 'gonta',
          title: 'ゴンタ刑事[けいじ]の 証言[しょうげん]',
          titleEn: 'Detective Gonta’s testimony',
          prompt: 'Gonta’s reasoning has a hole in it. Which statement doesn’t match the evidence?',
          lines: [
            { ja: '昨日[きのう]の 夕方[ゆうがた]、ケンタは 時計台[とけいだい]の 前[まえ]で 遊[あそ]んで いた。', en: 'Yesterday evening, Kenta was playing in front of the clock tower.',
              no: ['kenta', 'うん、遊[あそ]んでたよ。でも、それだけ！', 'Yeah, I was playing. But that’s all!'] },
            { ja: 'ケンタは なぞなぞが 大好[だいす]きだ。', en: 'Kenta loves riddles.',
              no: ['kenta', 'それは ほんとう だけど…。', 'Well, that’s true, but…'] },
            { ja: 'それに、この 手紙[てがみ]は ひらがなだけで 書[か]いて ある。子[こ]どもの 字[じ]だぜ！', en: 'Plus, this letter is written only in hiragana. That’s a kid’s writing!' },
            { ja: 'だから、犯人[はんにん]は ケンタだ！', en: 'So the culprit is Kenta!',
              no: ['kuro', 'それは 結論[けつろん]です。おかしいのは、その 前[まえ]の どこかですよ。', 'That’s his conclusion. What’s wrong is somewhere before it.'] },
          ],
          wrong: 2,
          hint: 'Read the note in your case file again. What is it written in?',
        },
        {
          type: 'fill', who: 'you',
          ja: 'ちがいます！ この 手紙[てがみ]は {_}で 書[か]いて あります！',
          en: 'Wrong! This letter is written in ___!',
          prompt: 'Look at the note in your case file. What kind of characters is it written in?',
          answers: ['漢字[かんじ]'],
          hint: '木, 日, 月, 待… these characters are called かん…',
          note: '書いてある means “is written (and stays that way)”: the て-form + ある describes the result of someone’s action.',
        },
        say('kenta', 'ぼく、まだ「待[ま]つ」の 漢字[かんじ]、書[か]けないよ。', 'I can’t even write the kanji for 待つ yet.'),
        say('gonta', '…むむ。', '…Hmm.'),
        say('kenta', '探偵[たんてい]さん、ぼくの なぞなぞも といてよ！', 'Mr. Detective, solve my riddle too!'),
        {
          type: 'riddle', who: 'kenta',
          title: 'ナゾ その4',
          ja: 'さかさまに 読[よ]むと「かるい」に なる 動物[どうぶつ]は なーんだ？',
          en: 'Which animal becomes かるい (“light”) when you read its name backwards?',
          answers: ['イルカ'],
          hint: 'Read かるい backwards, one kana at a time. It lives in the sea.',
          note: 'いるか (dolphin) ↔ かるい (light). Reading words backwards (さかさことば) is a favourite Japanese word game.',
        },
        say('kenta', 'せいかい！ あ、そうだ。昨日[きのう]の 夜[よる]、きつねの お面[めん]を つけた 人[ひと]が、時計台[とけいだい]に 入[はい]って いったよ。', 'Correct! Oh, right — last night, someone in a fox mask went into the clock tower.'),
        say('kuro', 'きつねの お面[めん]…。', 'A fox mask…'),
        {
          type: 'ask', who: 'kuro',
          prompt: 'Ask Mr. Tokita: “Who has the key to the clock tower?” To have / to hold is 持っている (polite: 持っています).',
          answers: [
            '時計台[とけいだい]の鍵[かぎ]は誰[だれ]が持[も]っていますか', '誰[だれ]が時計台[とけいだい]の鍵[かぎ]を持[も]っていますか',
            '鍵[かぎ]は誰[だれ]が持[も]っていますか', '誰[だれ]が鍵[かぎ]を持[も]っていますか',
            '時計台[とけいだい]の鍵[かぎ]を誰[だれ]が持[も]っていますか',
          ],
          hint: '時計台の かぎは + だれが + 持っていますか.',
          note: '持っている (to have) takes ている because owning something is an ongoing state. だれが asks “who?” as the subject.',
        },
        say('tokita', 'わたしと…あと、骨董屋[こっとうや]の 狐塚[きつねづか]さんです。去年[きょねん]、時計[とけい]を 直[なお]して くれました。', 'Me… and Madame Kitsunezuka from the antique shop. She repaired the clock for me last year.'),
        {
          type: 'fill', who: 'kuro', accuse: true,
          ja: '時計[とけい]を 止[と]めたのは… {_}さんですね。',
          en: 'The one who stopped the clock was… ___-san.',
          prompt: 'A fox mask, a key, and a taste for puzzles. Who stopped the clock?',
          answers: ['狐塚[きつねづか]'],
          hint: 'Her name begins with きつね, “fox”.',
          note: '狐塚: 狐 (きつね, fox) + 塚 (つか, mound). In the compound つ turns into づ — a sound change called rendaku.',
        },

        place('公園[こうえん]の 林[はやし]・次[つぎ]の 日[ひ]、三時十五分[さんじじゅうごふん]', 'The grove in the park · next day, 3:15'),
        narr('林[はやし]の 中[なか]に、だれかが 立[た]って います。', 'Someone is standing among the trees.'),
        say('kitsune', 'ようこそ。お待[ま]ちして おりましたわ、クロ探偵[たんてい]。', 'Welcome. I have been expecting you, Detective Kuro.'),
        say('kuro', 'やはり あなたでしたか、狐塚[きつねづか]さん。', 'So it was you after all, Madame Kitsunezuka.'),
        {
          type: 'ask', who: 'kuro',
          prompt: 'Ask her: “Why did you stop the clock?” Why = どうして or なぜ; to stop something = 止める (とめる).',
          answers: [
            'どうして時計[とけい]を止[と]めたんですか', 'なぜ時計[とけい]を止[と]めたんですか',
            'どうして時計[とけい]を止[と]めたのですか', 'なぜ時計[とけい]を止[と]めたのですか',
            'どうして時計[とけい]を止[と]めましたか', 'なぜ時計[とけい]を止[と]めましたか',
            'どうして止[と]めたんですか', 'なぜ止[と]めたんですか',
          ],
          hint: 'どうして + 時計を + 止めた + んですか.',
          note: '止める (to stop something) is transitive, 止まる (to come to a stop) intransitive: 時計を止めた vs 時計が止まった. Ending a question with 〜んですか asks for the story behind it.',
        },
        say('kitsune', '歯車[はぐるま]が 古[ふる]くて、もうすぐ こわれそう だったのです。', 'One of the gears was old and about to break.'),
        {
          type: 'fill', who: 'kitsune',
          ja: 'ですから、新[あたら]しい 歯車[はぐるま]を {_} きましたわ。',
          en: 'So I made a new gear and brought it along.',
          prompt: 'Fill in the て-form of 作る (つくる, to make). 〜て + きました = “made it and came (with it)”.',
          answers: ['作[つく]って'],
          hint: 'A godan verb ending in る: つくる → つく + って.',
          note: 'Godan verbs ending in う, つ and る take って: 作る → 作って, 待つ → 待って, 買う → 買って.',
        },
        say('kitsune', 'それに、有名[ゆうめい]な 探偵[たんてい]さんを、ちょっと ためして みたかったのです。', 'Besides, I wanted to put the famous detective to a little test.'),
        say('gonta', 'お、おれは ぜんぜん こわくなかったぜ！', 'I-I wasn’t scared at all!'),
        {
          type: 'fill', who: 'kuro',
          ja: 'でも、「大事件[だいじけん]だ！」って 言[い]って いましたよ。ちょっと {_} でしょう？',
          en: 'But you were shouting “It’s a huge case!” You were a bit scared, weren’t you?',
          prompt: 'Put こわい (scary, scared) into the past tense.',
          answers: ['こわかった', '怖[こわ]かった'],
          hint: 'い-adjective past: drop the い, add かった.',
          note: 'こわい → こわかった, たのしい → たのしかった. The one exception is いい → よかった.',
        },
        say('kitsune', 'ふふ。さすがですわ。では、こちらを どうぞ。わたくしの 店[みせ]の パーティーの 招待状[しょうたいじょう]です。', 'Hehe. Impressive. Then please take this: an invitation to a party at my shop.'),
        clue('invite', '招待状[しょうたいじょう]', 'Invitation', 'A gold-edged card for a party at Kitsunezuka Antiques. “Detective Kuro and assistant — your attendance is requested.”'),
        narr('カチ、カチ、カチ…。時計台[とけいだい]が また 動[うご]き出[だ]しました。', 'Tick, tick, tick… The clock tower starts moving again.'),
        say('tokita', 'ああ、よかった！ 動[うご]きました！', 'Oh, thank goodness! It’s moving!'),
        say('kuro', 'にゃるほど…。次[つぎ]は パーティー、ですか。', 'Nyaruhodo… A party next, is it.'),
      ],
    },

    // ─── Chapter 3 ───────────────────────────────────────────────────────────
    {
      id: 'teabowl',
      num: 3,
      level: 'N4',
      title: '月[つき]の茶碗[ちゃわん]',
      en: 'The Moon Tea Bowl',
      intro: 'At Madame Kitsunezuka’s party, a 300-year-old tea bowl vanishes the moment the lights go out. The window is open — but is that what really happened? (From here on, no spaces between words.)',
      skills: 'Keigo · 〜ている vs 〜てある · ある negative · 〜てしまう',
      steps: [
        place('狐塚骨董店[きつねづかこっとうてん]', 'Kitsunezuka Antiques'),
        narr('雨[あめ]の夜[よる]。店[みせ]の中[なか]は、古[ふる]い物[もの]でいっぱいです。', 'A rainy night. The shop is crammed with old things.'),
        say('kitsune', 'ようこそいらっしゃいました、クロ探偵[たんてい]。', 'Welcome, Detective Kuro.'),
        say('kuro', '助手[じょしゅ]くん、狐塚[きつねづか]さんはとても丁寧[ていねい]に話[はな]します。こちらも丁寧[ていねい]にお礼[れい]を言[い]いましょう。', 'Assistant, Madame Kitsunezuka speaks very politely. Let’s thank her just as politely.'),
        {
          type: 'ask', who: 'kuro',
          prompt: 'Thank her politely: “Thank you for inviting me.” Use 招待する (しょうたいする, to invite) + てくださって + ありがとうございます.',
          answers: [
            '招待[しょうたい]してくださってありがとうございます', '招待[しょうたい]してくださってどうもありがとうございます',
            'ご招待[しょうたい]くださってありがとうございます', 'ご招待[しょうたい]ありがとうございます',
            '招待[しょうたい]していただいてありがとうございます', '呼[よ]んでくださってありがとうございます',
          ],
          hint: 'しょうたいして + くださって + ありがとうございます.',
          note: '〜てくださって ありがとうございます thanks someone for doing something for you. くださる is the respectful form of くれる.',
        },
        say('kitsune', 'まあ、ご丁寧[ていねい]に。どうぞ、お入[はい]りください。', 'My, how polite. Please, do come in.'),
        narr('パーティーには、ハナさん、ケンタくん、田貫[たぬき]さん、ゴンタ刑事[けいじ]も来[き]ています。', 'Hana, Kenta, Mr. Tanuki and Detective Gonta are at the party too.'),
        say('mame', 'は、はじめまして。助手[じょしゅ]のマメです。', 'N-nice to meet you. I’m Mame, the assistant.'),
        say('kenta', '探偵[たんてい]さん！新[あたら]しいなぞなぞだよ！', 'Mr. Detective! I’ve got a new riddle!'),
        {
          type: 'riddle', who: 'kenta',
          title: 'ナゾ その5',
          ja: 'トラはトラでも、道[みち]を走[はし]るトラはなーんだ？',
          en: 'It’s a トラ (tiger), but it drives along the road. Which トラ is it?',
          answers: ['トラック'],
          hint: 'A big vehicle that carries things. A loanword from English, starting トラ…',
          note: 'トラック, a truck! English loanwords often get a small っ before a k sound: truck → トラック, bag → バッグ.',
        },
        say('kitsune', 'では、今夜[こんや]の主役[しゅやく]をご覧[らん]ください。', 'And now, please behold the star of the evening.'),
        say('kitsune', '「月[つき]の茶碗[ちゃわん]」でございます。三百年前[さんびゃくねんまえ]に作[つく]られたものですわ。', 'The “Moon Tea Bowl”. It was made three hundred years ago.'),
        {
          type: 'meaning', who: 'kuro',
          prompt: 'How old is the tea bowl? (In English, or as a number.)',
          answers: ['300', 'three hundred', '三百'],
          hint: '三百 = 3 × 100. Careful: ひゃく turns into びゃく after さん.',
          note: 'さんびゃく (300), ろっぴゃく (600) and はっぴゃく (800) change their sound; the other hundreds are a plain ひゃく.',
        },
        clue('bowl', '月[つき]の茶碗[ちゃわん]', 'The Moon Tea Bowl', 'A 300-year-old tea bowl with a moon pattern, shown in a glass case in the middle of the shop.'),
        narr('その時[とき]…パッ！電気[でんき]が消[き]えました。', 'At that moment… click! The lights go out.'),
        say('hana', 'きゃー！何[なに]も見[み]えない！', 'Eek! I can’t see a thing!'),
        narr('十秒後[じゅうびょうご]、電気[でんき]がつきました。ガラスのケースは…からっぽです。', 'Ten seconds later the lights come back on. The glass case is… empty.'),
        say('kitsune', '茶碗[ちゃわん]が…ありませんわ！', 'The tea bowl… it’s gone!'),
        say('mame', 'た、大変[たいへん]です！窓[まど]が開[あ]いています！どろぼうは窓[まど]から逃[に]げたんです！', 'Th-this is terrible! The window is open! The thief got away through the window!'),
        say('gonta', 'よし、外[そと]を探[さが]すぜ！', 'Right, I’ll search outside!'),
        say('kuro', '待[ま]ってください。まず、窓[まど]をよく見[み]ましょう。', 'Wait. First, let’s take a good look at the window.'),
        narr('窓[まど]の外[そと]は雨[あめ]で、地面[じめん]はどろどろです。でも、足[あし]あとは一[ひと]つもありません。', 'Outside, the rain has turned the ground to mud. But there isn’t a single footprint.'),
        clue('mud', '窓[まど]の外[そと]のどろ', 'Mud under the window', 'Soft, wet mud right below the open window. Not one footprint in it.'),
        say('kuro', 'それに、この窓[まど]はとても重[おも]いです。風[かぜ]では開[あ]きません。', 'Besides, this window is very heavy. The wind couldn’t open it.'),
        {
          type: 'fill', who: 'kuro',
          ja: 'この窓[まど]は、ただ開[あ]いているんじゃない。だれかがわざと開[あ]けた…。窓[まど]が{_}あるんです。',
          en: 'This window isn’t simply open. Someone opened it on purpose… The window has been opened (and left that way).',
          prompt: 'Mame said 窓が開いています, “the window is open”. But someone did this deliberately. Use the transitive verb 開ける (あける) in て-form, before ある.',
          answers: ['開[あ]けて'],
          hint: 'あける → あけて.',
          note: '開いている (intransitive 開く + ている) just describes a state: “it’s open”. 開けてある (transitive 開ける + てある) says someone opened it and left it like that — a detective’s favourite verb form.',
        },
        say('kitsune', 'では、どろぼうは外[そと]から来[き]たのではない…ということですの？', 'Then you are saying the thief did not come from outside?'),
        say('mame', 'で、でも…ぼくは見[み]ました！', 'B-but… I saw them!'),
        {
          type: 'testimony', who: 'mame',
          title: 'マメの証言[しょうげん]',
          titleEn: 'Mame’s testimony',
          prompt: 'One of these statements can’t be true, given the evidence. Which?',
          lines: [
            { ja: '電気[でんき]が消[き]えた時[とき]、ぼくは台所[だいどころ]にいました。', en: 'When the lights went out, I was in the kitchen.',
              no: ['kuro', 'ふむ。台所[だいどころ]…覚[おぼ]えておきましょう。', 'Hmm. The kitchen… let’s remember that.'] },
            { ja: '電気[でんき]がついた時[とき]、窓[まど]が開[あ]いていました。', en: 'When the lights came back on, the window was open.',
              no: ['kuro', '窓[まど]が開[あ]いていたのは、本当[ほんとう]ですね。', 'It’s true the window was open.'] },
            { ja: '黒[くろ]い服[ふく]の人[ひと]が、窓[まど]から外[そと]に飛[と]び出[だ]して、走[はし]っていきました。', en: 'Someone dressed in black jumped out of the window and ran off.' },
            { ja: 'きっと、もう遠[とお]くに逃[に]げたと思[おも]います。', en: 'I’m sure they’ve already got far away.',
              no: ['kuro', 'それはマメさんの考[かんが]えですね。証拠[しょうこ]とぶつかってはいません。', 'That’s just Mame’s opinion. It doesn’t clash with any evidence.'] },
          ],
          wrong: 2,
          hint: 'If someone ran out into the mud, what would they leave behind?',
        },
        {
          type: 'fill', who: 'you',
          ja: '外[そと]に走[はし]っていったなら、どろに足[あし]あとがあるはずです。でも、足[あし]あとは一[ひと]つも{_}！',
          en: 'If someone ran outside, there should be footprints in the mud. But there isn’t a single one!',
          prompt: 'Finish the objection with the polite negative of ある.',
          answers: ['ありません', 'ないです', 'ありませんでした', 'なかったです'],
          hint: 'あります → あり…',
          note: 'The negative of ある is irregular: ない (plain), ありません (polite) — never あらない. 〜はずです means “it should (logically) be so”.',
        },
        say('mame', 'う…。', 'Ugh…'),
        say('kitsune', 'では、犯人[はんにん]はまだこの部屋[へや]にいらっしゃる、ということですわね。', 'Then the culprit must still be in this very room.'),
        {
          type: 'fill', who: 'kuro',
          ja: '「いらっしゃる」は、ふつうの言葉[ことば]で言[い]うと「{_}」ですね。',
          en: 'In ordinary words, いらっしゃる means “___”.',
          prompt: 'いらっしゃる is the respectful (尊敬語) form of which plain verb here? The culprit is still in the room.',
          answers: ['いる'],
          hint: 'The culprit “is” in the room. For people, that’s い…',
          note: 'いらっしゃる is the honorific for いる, 行く and 来る. Madame Kitsunezuka is polite even about a thief!',
        },
        say('hana', 'あの…クロさん。これ、台所[だいどころ]のゴミ箱[ばこ]にありました。', 'Um… Kuro. I found this in the kitchen bin.'),
        clue('shards', '茶碗[ちゃわん]のかけら', 'Broken pieces', 'Pieces of a tea bowl with a moon pattern, wrapped in a napkin and hidden at the bottom of the kitchen bin.'),
        say('kuro', '台所[だいどころ]…。電気[でんき]が消[き]えた時[とき]、台所[だいどころ]にいたのはだれでしたか。', 'The kitchen… Who was in the kitchen when the lights went out?'),
        {
          type: 'fill', who: 'kuro', accuse: true,
          ja: '犯人[はんにん]は…{_}さんです！',
          en: 'The culprit is… ___!',
          prompt: 'Who was in the kitchen? Who insisted the thief went out of the window?',
          answers: ['マメ'],
          hint: 'Check the testimony: 「ぼくは台所にいました」.',
          note: 'His own testimony put him in the kitchen — right where the pieces were hidden.',
        },
        say('mame', '…ごめんなさい！', '…I’m so sorry!'),
        say('mame', 'パーティーの前[まえ]に、茶碗[ちゃわん]をケースから出[だ]して、ふいていたんです。そうしたら、手[て]がすべって…。', 'Before the party I took the bowl out of its case to polish it. And then my hand slipped…'),
        say('mame', 'こわくて、言[い]えませんでした。だから電気[でんき]を消[け]して、窓[まど]を開[あ]けて…。', 'I was too scared to say. So I switched off the lights, opened the window…'),
        {
          type: 'fill', who: 'kuro',
          ja: 'つまり、マメさんはうっかり茶碗[ちゃわん]を{_}んですね。',
          en: 'In other words, Mame accidentally broke the tea bowl.',
          prompt: 'Use 割る (わる, to break) + てしまった — “did it by accident, and regrets it”.',
          answers: ['割[わ]ってしまった', '割[わ]っちゃった'],
          hint: 'わる → わって + しまった.',
          note: '〜てしまう adds “by accident” or “and I regret it”. In casual speech it shrinks to 〜ちゃう: 割っちゃった.',
        },
        say('kitsune', '…マメ。顔[かお]を上[あ]げなさい。', '…Mame. Lift your head.'),
        say('kitsune', 'あれはレプリカですわ。本物[ほんもの]は、ずっと金庫[きんこ]の中[なか]です。', 'That was a replica. The real one has been in the safe all along.'),
        {
          type: 'meaning', who: 'kuro',
          prompt: 'Wait — what was the bowl that broke?',
          answers: ['replica', 'copy', 'fake', 'imitation', 'not real', 'not the real', 'reproduction', 'counterfeit'],
          hint: 'レプリカ is a loanword. 本物 (ほんもの) means “the real thing”.',
          note: 'レプリカ = replica. 本物 (the real thing) ↔ 偽物 (にせもの, a fake).',
        },
        say('kitsune', 'クロ探偵[たんてい]が本当[ほんとう]に名探偵[めいたんてい]か、ためしたかったのです。', 'I wanted to test whether Detective Kuro is truly a great detective.'),
        say('kuro', '…また、ですか。', '…Again?'),
        say('gonta', 'お、おれは最初[さいしょ]からわかってたぜ！', 'I-I knew from the start!'),
        narr('その時[とき]、外[そと]から大[おお]きな声[こえ]が聞[き]こえました。', 'Just then, a loud voice comes from outside.'),
        say('uozumi', 'ない！ない！祭[まつ]りの鯛[たい]がないぞー！', 'It’s gone! Gone! The festival sea bream is gone!'),
      ],
    },

    // ─── Chapter 4 ───────────────────────────────────────────────────────────
    {
      id: 'arrested',
      num: 4,
      level: 'N3',
      title: 'クロ、逮捕[たいほ]される！？',
      en: 'Kuro Arrested?!',
      intro: 'The fishmonger’s festival sea bream has vanished, a torn note says 「クロにたべ」, and Gonta has Kuro in handcuffs. This time Kuro can’t solve the case. You have to.',
      skills: 'Hearsay そうだ · passive vs causative · 〜ておく · humble apologies',
      steps: [
        place('魚屋[さかなや]「魚住[うおずみ]」', 'Uozumi Fish Shop'),
        say('uozumi', '明日[あした]の祭[まつ]りのための、一番[いちばん]大[おお]きい鯛[たい]だったんだ！', 'It was the biggest sea bream I had — for tomorrow’s festival!'),
        say('gonta', '店[みせ]の台[だい]の上[うえ]にメモがあったぜ。見[み]ろ！', 'There was a memo on the counter. Look!'),
        clue('memo', 'やぶれたメモ', 'Torn memo', 'Half a memo, torn down the middle, found on the counter. It reads: 「クロにたべ」…'),
        say('gonta', '「クロにたべ」…つまり、「鯛[たい]はクロに食[た]べられた」ってことだ！', '“Kuro… ea—” That means “The sea bream was eaten by Kuro”!'),
        say('gonta', 'クロ、逮捕[たいほ]だ！', 'Kuro, you’re under arrest!'),
        say('kuro', 'にゃ！？', 'Nya?!'),
        narr('カチャッ。クロの前足[まえあし]に、小[ちい]さな手錠[てじょう]がかけられました。', 'Click. A tiny pair of handcuffs closes around Kuro’s front paws.'),
        say('kitsune', 'お待[ま]ちなさい。わたくしは商店街[しょうてんがい]の会長[かいちょう]です。みなさんの前[まえ]で、きちんとお話[はなし]を聞[き]きましょう。', 'Hold on. I am chair of the shopping street association. Let us hear this out properly, in front of everyone.'),

        place('商店街[しょうてんがい]の広場[ひろば]・臨時[りんじ]の裁判[さいばん]', 'The street square · an emergency hearing'),
        say('kuro', '助手[じょしゅ]くん…今日[きょう]は、きみがわたしを助[たす]けてください。', 'Assistant… today, you’re the one who has to save me.'),
        {
          type: 'fill', who: 'you',
          ja: 'クロさんが鯛[たい]を盗[ぬす]んだ{_}ありません！',
          en: 'There’s no way Kuro stole the sea bream!',
          prompt: 'Stand up for Kuro! “There’s no way that…” = verb + はずが + ありません.',
          answers: ['はずが', 'はずは', 'わけが', 'わけは'],
          hint: 'Two kana, then が: は…',
          note: '〜はずがない = “there’s no way that (logically)…”. Compare 〜はずだ, “it should be so”, which you used in the last case.',
        },
        say('gonta', 'ふん。じゃあ、魚住[うおずみ]さんの話[はなし]を聞[き]け！', 'Hmph. Then listen to what Mr. Uozumi has to say!'),
        {
          type: 'testimony', who: 'uozumi',
          title: '魚住[うおずみ]さんの証言[しょうげん]',
          titleEn: 'Mr. Uozumi’s testimony',
          prompt: 'One of these is not something Mr. Uozumi saw with his own eyes. Which statement is only hearsay?',
          lines: [
            { ja: '朝[あさ]六時[ろくじ]に、鯛[たい]を店[みせ]の前[まえ]に並[なら]べた！', en: 'At six this morning, I laid the sea bream out in front of the shop!',
              no: ['kuro', 'それは魚住[うおずみ]さんが自分[じぶん]でしたことですね。', 'That’s something he did himself.'] },
            { ja: '八時[はちじ]ごろ、配達[はいたつ]に出[で]かけた。店[みせ]には母[はは]がいたはずだ！', en: 'Around eight I went out on deliveries. My mother should have been minding the shop!',
              no: ['kuro', '「はずだ」…気[き]になりますね。でも、ここではありません。', '“Should have been”… intriguing. But that’s not the weak spot.'] },
            { ja: '九時[くじ]に帰[かえ]ってきたら、鯛[たい]がなくなっていた！', en: 'When I got back at nine, the sea bream was gone!',
              no: ['kuro', 'それは自分[じぶん]の目[め]で見[み]たことです。', 'He saw that with his own eyes.'] },
            { ja: 'クロが大[おお]きい魚[さかな]をくわえて走[はし]っていたそうだ！', en: 'Kuro was apparently running off with a big fish in his mouth!' },
          ],
          wrong: 3,
          hint: 'Look at how each sentence ends. One ends in a word that reports what someone else said.',
        },
        {
          type: 'meaning', who: 'kuro',
          prompt: 'He said 走っていたそうだ. What does 〜そうだ after a plain verb tell you about where he got this?',
          answers: ['heard', 'hearsay', 'someone said', 'someone told', 'was told', 'apparently', 'reportedly', 'they say', 'people say', 'rumor', 'rumour', 'second hand', 'secondhand', 'second-hand', 'didn’t see', 'didn\'t see', 'did not see', 'not see'],
          hint: 'Plain verb + そうだ is not “looks like” (that’s the ます-stem + そう). It reports something you…',
          note: '走っていたそうだ = “I hear he was running”: reported speech. Compare 走りそうだ = “he looks like he’s about to run”. Same そう, different attachment, very different meaning.',
        },
        say('uozumi', 'う…そう聞[き]いただけだ。言[い]ったのはゴンタ刑事[けいじ]だ！', 'Er… I only heard it. Detective Gonta was the one who said it!'),
        say('gonta', 'お、おれは…メモを読[よ]んで、そう思[おも]っただけだ…。', 'I-I… I just read the memo and figured that’s what happened…'),
        say('kuro', '…それは証拠[しょうこ]ではありません。', '…That is not evidence.'),
        {
          type: 'ask', who: 'kuro',
          prompt: 'Ask Mr. Uozumi to let you look around the shop: “Please let me see the shop.” Use the causative 見させてください — or simply ask him to show you, 見せてください.',
          answers: [
            '店[みせ]を見[み]させてください', 'お店[みせ]を見[み]させてください', '店[みせ]の中[なか]を見[み]させてください', 'お店[みせ]の中[なか]を見[み]させてください',
            '店[みせ]を見[み]せてください', 'お店[みせ]を見[み]せてください', '店[みせ]の中[なか]を見[み]せてください', 'お店[みせ]の中[なか]を見[み]せてください',
          ],
          hint: '(お)店を + 見させて + ください.',
          note: 'Causative て-form + ください asks for permission: 見させてください, “let me look”. 見せる (to show) is a verb of its own: 見せてください, “please show me”.',
        },

        place('魚屋[さかなや]の中[なか]', 'Inside the fish shop'),
        narr('床[ゆか]がぬれています。店[みせ]の前[まえ]から奥[おく]まで、水[みず]のあとが続[つづ]いています。', 'The floor is wet. A trail of water runs from the front of the shop to the back.'),
        narr('奥[おく]には、大[おお]きな冷蔵庫[れいぞうこ]があります。', 'At the back stands a big refrigerator.'),
        clue('trail', '水[みず]のあと', 'Trail of water', 'Drips of water leading from the display at the front of the shop all the way to the big fridge at the back.'),
        narr('ゴミ箱[ばこ]の中[なか]に、紙[かみ]が一枚[いちまい]…。', 'In the bin, a single scrap of paper…'),
        clue('memo2', 'メモの右半分[みぎはんぶん]', 'Other half of the memo', 'Found in the shop’s bin, next to a few small sardine bones. It reads: 「させた。ウメ」'),
        say('kuro', '二[ふた]つを合[あ]わせると…「クロにたべさせた。ウメ」。', 'Put the two halves together… 「クロにたべさせた。ウメ」.'),
        {
          type: 'meaning', who: 'kuro',
          prompt: 'Gonta read it as 食べられた — passive, “was eaten by Kuro”. But 食べさせた is causative. Translate the memo: “I ___ Kuro. —Ume” (one English word)',
          answers: ['fed', 'feed', 'let', 'made', 'gave', 'allowed'],
          hint: 'Causative 〜させる = make or let someone do something. “Made / let Kuro eat” in one word is…',
          note: '食べさせた = “made/let (Kuro) eat”, i.e. “fed”. Granny Ume was leaving a note for her son.',
        },
        {
          type: 'fill', who: 'you',
          ja: '「クロに食[た]べられた」じゃない。「クロに食[た]べ{_}た」です！',
          en: 'Not “eaten by Kuro” — “let Kuro eat”!',
          prompt: 'Fill in the causative ending: 食べる → 食べ＿＿る, here in the past.',
          answers: ['させ'],
          hint: 'Ichidan verbs: drop る, add させる.',
          note: 'Passive 食べられる (be eaten) vs causative 食べさせる (make or let eat). Two kana — さ・せ instead of ら・れ — and the villain changes!',
        },
        say('ume', 'あらあら、何[なん]の騒[さわ]ぎ？', 'Oh my, what’s all this fuss?'),
        say('uozumi', '母[かあ]さん！', 'Mum!'),
        {
          type: 'testimony', who: 'ume',
          title: 'ウメさんの証言[しょうげん]',
          titleEn: 'Granny Ume’s testimony',
          prompt: 'Granny Ume is honest but forgetful. Which statement clashes with the evidence?',
          lines: [
            { ja: '八時[はちじ]すぎに、クロちゃんが遊[あそ]びに来[き]たのよ。', en: 'A little after eight, dear Kuro dropped by.',
              no: ['kuro', 'わたしが行[い]ったのは本当[ほんとう]です。いわし、おいしかった…。', 'It’s true I went. That sardine was delicious…'] },
            { ja: 'おなかがすいていたみたいだから、いわしを一匹[いっぴき]食[た]べさせたの。', en: 'He looked hungry, so I let him eat a sardine.',
              no: ['kuro', 'メモと合[あ]っていますね。', 'That matches the memo.'] },
            { ja: '今日[きょう]は朝[あさ]からとても暑[あつ]かったわねえ。', en: 'It’s been terribly hot since this morning, hasn’t it.',
              no: ['kuro', '暑[あつ]い日[ひ]…大事[だいじ]なことかもしれません。でも、おかしくはありません。', 'A hot day… that might matter. But it isn’t wrong.'] },
            { ja: '鯛[たい]？鯛[たい]なら、ずっと店[みせ]の前[まえ]に置[お]いたままよ。', en: 'The sea bream? Oh, I left it out front the whole time.' },
          ],
          wrong: 3,
          hint: 'Where does the trail of water lead?',
        },
        {
          type: 'ask', who: 'kuro',
          prompt: 'The trail of water leads to the fridge. Ask her gently: “Didn’t you put the sea bream in the fridge?” (fridge = 冷蔵庫 れいぞうこ, to put in = 入れる いれる)',
          answers: [
            '鯛[たい]を冷蔵庫[れいぞうこ]に入[い]れませんでしたか', '鯛[たい]は冷蔵庫[れいぞうこ]に入[い]れませんでしたか',
            '冷蔵庫[れいぞうこ]に鯛[たい]を入[い]れませんでしたか', '冷蔵庫[れいぞうこ]に入[い]れませんでしたか',
            '鯛[たい]を冷蔵庫[れいぞうこ]に入[い]れたんじゃないですか', '鯛[たい]を冷蔵庫[れいぞうこ]に入[い]れたのではありませんか',
            '鯛[たい]を冷蔵庫[れいぞうこ]に入[い]れたんじゃありませんか',
          ],
          hint: '鯛を + 冷蔵庫に + 入れませんでしたか.',
          note: 'A negative question (〜ませんでしたか) is a soft, polite way to suggest something: “Didn’t you…?”',
        },
        say('ume', '…あら！そうだったわ。暑[あつ]かったから、冷蔵庫[れいぞうこ]に入[い]れておいたのよ。', '…Oh my! So I did. It was so hot that I put it in the fridge to keep.'),
        {
          type: 'fill', who: 'kuro',
          ja: '鯛[たい]が悪[わる]くならないように、冷蔵庫[れいぞうこ]に入[い]れて{_}んですね。',
          en: 'So you put the sea bream in the fridge ahead of time, so it wouldn’t go off.',
          prompt: '“Do something in advance / for later” = て-form + おく. Here in the plain past: 入れて＿＿.',
          answers: ['おいた', '置[お]いた'],
          hint: 'おく in the past works like 書く → 書いた.',
          note: '〜ておく = do something in preparation. 〜ないように = “so that … doesn’t happen”. Both are N4–N3 favourites.',
        },
        narr('魚住[うおずみ]さんが冷蔵庫[れいぞうこ]を開[あ]けると…大[おお]きな鯛[たい]が、ぴかぴか光[ひか]っていました。', 'Mr. Uozumi opens the fridge… and there lies the big sea bream, gleaming.'),
        say('uozumi', 'あったー！', 'There it is!'),
        say('kitsune', 'では、判決[はんけつ]を言[い]い渡[わた]します。クロ探偵[たんてい]は…', 'I shall now deliver the verdict. Detective Kuro is…'),
        {
          type: 'fill', who: 'kitsune', accuse: true,
          ja: '{_}ですわ。',
          en: '…not guilty.',
          prompt: 'Deliver the verdict with her: “not guilty” — 無 (without) + 罪 (crime).',
          answers: ['無罪[むざい]'],
          hint: 'む・ざ・い.',
          note: '無罪 (むざい) not guilty ↔ 有罪 (ゆうざい) guilty. 無 means “without”, as in 無料 (むりょう, free of charge).',
        },
        narr('カチャッ。手錠[てじょう]が外[はず]されました。', 'Click. The handcuffs come off.'),
        say('gonta', 'く、クロ…すまん。', 'K-Kuro… sorry.'),
        say('kuro', 'ゴンタ刑事[けいじ]。「すまん」では足[た]りませんね。', 'Detective Gonta. “Sorry” won’t quite cut it.'),
        {
          type: 'ask', who: 'kuro',
          prompt: 'Help Gonta apologise to Kuro in the humblest way: “I am truly sorry” (申し訳, もうしわけ). Past tense, since it’s about what he did.',
          answers: [
            '申[もう]し訳[わけ]ありませんでした', '申[もう]し訳[わけ]ございませんでした',
            '本当[ほんとう]に申[もう]し訳[わけ]ありませんでした', '本当[ほんとう]に申[もう]し訳[わけ]ございませんでした',
            '大変[たいへん]申[もう]し訳[わけ]ありませんでした', '大変[たいへん]申[もう]し訳[わけ]ございませんでした',
            '誠[まこと]に申[もう]し訳[わけ]ございませんでした', '申[もう]し訳[わけ]ありません', '申[もう]し訳[わけ]ございません',
          ],
          hint: 'もうしわけ + ありませんでした.',
          note: 'すまん → すみません → 申し訳ありません → 申し訳ございません: the same apology climbing the politeness ladder.',
        },
        say('gonta', 'も、申[もう]し訳[わけ]ありませんでした…！', 'I-I am truly sorry…!'),
        say('uozumi', 'クロさん、おわびに、これをどうぞ！', 'Kuro, please take this to make up for it!'),
        narr('魚住[うおずみ]さんは、小[ちい]さな鯛[たい]をクロにわたしました。', 'Mr. Uozumi hands Kuro a small sea bream.'),
        say('ume', 'ほら、今度[こんど]は本当[ほんとう]に「クロに食[た]べさせた」わね。', 'There — this time I really did “let Kuro eat”.'),
        say('kuro', 'にゃるほど…。助手[じょしゅ]くん、きみはもう立派[りっぱ]な探偵[たんてい]ですね。', 'Nyaruhodo… Assistant, you’re a fine detective now.'),
        say('kuro', 'でも、明日[あした]の祭[まつ]りでも、きっと何[なに]か起[お]こりますよ。', 'Mind you, I’m sure something will happen at tomorrow’s festival too.'),
      ],
    },
  ];

  global.MYSTERY_CAST = CAST;
  global.MYSTERY_CHAPTERS = CHAPTERS;

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { CAST, CHAPTERS };
  }
})(typeof window !== 'undefined' ? window : globalThis);
