(function (global) {
  'use strict';

  // ことば探偵クロ — "Kuro, Word Detective" (mystery.html): a mystery told
  // in Japanese, where the player moves the story on by answering in Japanese.
  //
  // Every chapter is a list of steps, played in order:
  //   say        a line of dialogue (who: a CAST key, or 'narr' for narration)
  //   place      a change of scene
  //   clue       a piece of evidence goes into the case file
  //   fill       a line with one blank ({_}) to type in
  //   ask        a whole sentence to type, from an English instruction
  //   meaning    a comprehension question answered in English
  //   riddle     a なぞなぞ or kanji puzzle (Layton style)
  //   testimony  find the statement that doesn't hold up (Ace Attorney style)
  //
  // Lines are written like the Stories page (stories-data.js): `ja` is a
  // space-separated list of tokens in 漢字[かんじ] furigana markup, each a
  // STORY_GLOSSARY word (`>key` points a conjugated form at its dictionary
  // form, 落[お]ちて>落ちる), and `g` lists the line's STORY_GRAMMAR points as
  // `id:snippet`. Words the Stories glossary lacks are in mystery-words.js.
  // A fill line marks its blank with a {_} token (or {_} inside a token), and
  // `fill` is what goes there once solved; an ask step's `line` is its model
  // answer as tokens. test_mystery.js checks all of this.
  //
  // Typed answers (`answers`) are plain furigana markup. They match with each
  // kanji word written either way, so 時計台[とけいだい]の鍵[かぎ] also accepts
  // とけいだいのかぎ and 時計台のかぎ. Katakana and hiragana count as the same,
  // and spaces and punctuation are ignored.

  const CAST = {
    kuro: {
      name: 'クロ', en: 'Kuro', face: '🐈‍⬛', color: '#4b4466',
      role: 'Detective',
      bio: 'A black cat in a deerstalker and the shopping street’s only detective. Speaks nothing but Japanese, adores fish, and says にゃるほど when the pieces click.',
    },
    hana: {
      name: 'ハナ', en: 'Hana', face: '👩‍🍳', color: '#e8643f',
      role: 'Baker',
      bio: 'Runs Fuwafuwa Bakery with boundless energy. Famous for her melon pan; less famous for closing windows.',
    },
    kenta: {
      name: 'ケンタ', en: 'Kenta', face: '👦', color: '#3f9d52',
      role: 'Riddle collector',
      bio: 'Hana’s little brother, nine years old. Trades secrets for riddles — solve his なぞなぞ and he’ll tell you what he saw.',
    },
    gonta: {
      name: 'ゴンタ刑事', en: 'Detective Gonta', face: '👮', color: '#3a57a6',
      role: 'Police detective',
      bio: 'Big, loud and certain. Solves every case in five seconds — wrongly. Ends his sentences with a tough-guy だぜ.',
    },
    tanuki: {
      name: '田貫さん', en: 'Mr. Tanuki', face: '👴', color: '#8a6a3d',
      role: 'Bookseller',
      bio: 'Sleepy owner of the secondhand bookshop. Yawns mid-sentence and calls himself わし, like old men in anime.',
    },
    tokita: {
      name: '時田さん', en: 'Mr. Tokita', face: '👨‍🔧', color: '#6a6878',
      role: 'Clockmaker',
      bio: 'Has wound the street’s clock tower every single morning for forty years.',
    },
    kitsune: {
      name: '狐塚夫人', en: 'Madame Kitsunezuka', face: '🦊', color: '#c9930c',
      role: 'Antique dealer',
      bio: 'Elegant chair of the shopping street association. Speaks flawless 敬語 and cannot resist setting puzzles for Kuro.',
    },
    mame: {
      name: 'マメ', en: 'Mame', face: '🧑', color: '#d9678f',
      role: 'Assistant',
      bio: 'Madame Kitsunezuka’s nervous young assistant. Very careful with antiques. Usually.',
    },
    uozumi: {
      name: '魚住さん', en: 'Mr. Uozumi', face: '🧔', color: '#2a8bb0',
      role: 'Fishmonger',
      bio: 'Shouts every sentence as if he’s selling tuna at five in the morning.',
    },
    ume: {
      name: 'ウメさん', en: 'Granny Ume', face: '👵', color: '#7a5aa6',
      role: 'Fishmonger’s mother',
      bio: 'Sweet, forgetful, and secretly feeds every cat on the street.',
    },
    karasu: {
      name: 'カラス', en: 'The Crow', face: '🐦', color: '#2b2b33',
      role: '???',
      bio: 'Lives on the bookshop roof. Has excellent taste in bread.',
    },
  };

  const say = (who, ja, en, g) => ({ type: 'say', who, ja, en, g: g || [] });
  const narr = (ja, en, g) => ({ type: 'say', who: 'narr', ja, en, g: g || [] });
  const place = (ja, en) => ({ type: 'place', ja, en });
  const clue = (id, name, en, desc, ja, g) => ({ type: 'clue', id, name, en, desc, ja, g: g || [] });
  const line = (ja, en, g, no) => ({ ja, en, g: g || [], no });

  const CHAPTERS = [
    // ─── Chapter 1 ───────────────────────────────────────────────────────────
    {
      id: 'melonpan',
      num: 1,
      level: 'N5',
      title: '消[き]えたメロンパン',
      en: 'The Vanishing Melon Pan',
      intro: 'Every morning, Hana’s melon pan vanishes from the bakery window. Detective Gonta already has a suspect. Kuro has a brand-new assistant: you.',
      skills: 'Particles · days of the week · あります / います · counters',
      steps: [
        place('クロ探偵[たんてい]事務所[じむしょ]', 'Kuro’s detective office'),
        say('kuro', 'にゃあ 。 わたし>私 は クロ 。 この 商店街[しょうてんがい] の 探偵[たんてい] です 。', 'Meow. I’m Kuro, the detective of this shopping street.',
          ['wa-topic:わたしはクロ', 'kosoado:この', 'no-possessive:商店街の探偵', 'desu:探偵です']),
        say('kuro', 'きみ>君 が 新[あたら]しい 助手[じょしゅ] です ね 。', 'So you’re my new assistant.',
          ['ga-subject:きみが', 'i-adj-noun:新しい助手', 'ne:ですね']),
        say('kuro', 'わたし>私 は 日本語[にほんご] しか 話[はな]しません>話す 。 だから 、 きみ>君 も 日本語[にほんご] で 答[こた]えて>答える ください 。', 'I speak only Japanese. So please answer in Japanese too.',
          ['shika-nai:日本語しか話しません', 'dakara:だから', 'mo-also:きみも', 'de-means:日本語で', 'te-kudasai:答えてください']),
        say('kuro', 'ローマ字[じ] で 書[か]いて>書く も だいじょうぶ>大丈夫 。 ひらがな に なります>なる よ 。', 'It’s fine to type in romaji — it turns into hiragana as you go.',
          ['te-mo:書いても', 'ni-naru:ひらがなになります', 'yo:なりますよ']),
        {
          type: 'ask', who: 'kuro',
          prompt: 'Greet Kuro properly: “Nice to meet you” (literally, “please treat me well”).',
          answers: [
            'よろしくお願[ねが]いします', 'どうぞよろしくお願[ねが]いします',
            'はじめましてよろしくお願[ねが]いします', 'はじめましてどうぞよろしくお願[ねが]いします',
            'よろしくお願[ねが]いいたします',
          ],
          line: 'よろしく お願[ねが]いします>お願いする 。',
          g: ['kenjougo:お願いします'],
          hint: 'It starts with よろしく… and ends with …します. Type: yoroshiku onegaishimasu',
          note: 'よろしくお願いします is what you say when you start working with someone. Plain よろしく is the casual version — a bit cheeky on your first day.',
        },
        say('kuro', 'よろしく 。 では 、 さっそく …', 'Likewise. Now then, let’s get—'),
        narr('バタン ！ ドア が 開[あ]きました>開く 。', 'Bang! The door flies open.',
          ['ga-subject:ドアが', 'masu-past:開きました']),
        say('hana', 'クロ さん ！ たいへん です ！', 'Kuro! Something terrible has happened!',
          ['desu:たいへんです']),
        say('hana', 'わたし>私 の メロンパン が 、 また なくなりました>なくなる ！', 'My melon pan has disappeared again!',
          ['no-possessive:わたしのメロンパン', 'ga-subject:メロンパンが', 'naku-naru:なくなりました']),
        say('kuro', 'また ？', 'Again?'),
        say('hana', 'はい 。 月曜日[げつようび] も 火曜日[かようび] も なくなりました>なくなる 。 そして 今日[きょう] も ！', 'Yes. It disappeared on Monday, and on Tuesday. And today too!',
          ['mo-also:月曜日も火曜日も', 'masu-past:なくなりました']),
        {
          type: 'meaning', who: 'kuro',
          prompt: 'Kuro checks that you followed. In English: what keeps disappearing?',
          answers: ['melon pan', 'melonpan', 'melon-pan', 'melon bread', 'melon bun', 'melon', 'bread', 'bun'],
          hint: 'メ・ロ・ン・パ・ン. パン (bread) comes from Portuguese.',
          note: 'メロンパン is a sweet bun with a crisp cookie crust, named for its melon-like look. There’s usually no melon in it at all.',
        },
        {
          type: 'fill', who: 'kuro',
          ja: 'ふむ 。 今日[きょう] は {_} です ね 。',
          fill: '水曜日[すいようび]',
          g: ['wa-topic:今日は', 'desu:水曜日です', 'ne:ですね'],
          en: 'Hmm. So today is ___.',
          prompt: 'Monday, Tuesday… and today. Three mornings in a row. What day is it today?',
          answers: ['水曜日[すいようび]', '水曜[すいよう]'],
          hint: 'Monday is 月曜日, Tuesday 火曜日. The next day is named after water: 水 (すい).',
          note: 'The week: 月 moon, 火 fire, 水 water, 木 wood, 金 gold, 土 earth, 日 sun — each plus 曜日 (ようび).',
        },
        say('kuro', 'では 、 パン屋[や] へ 行[い]きましょう>行く 。', 'Then let’s go to the bakery.',
          ['he-direction:パン屋へ', 'mashou:行きましょう']),

        place('パン屋[や]「ふわふわ」', 'Fuwafuwa Bakery'),
        say('hana', '毎朝[まいあさ] 七時[しちじ] に 、 メロンパン を 窓[まど] の そば に 置[お]きます>置く 。 さます>冷ます ん です 。', 'Every morning at seven, I put the melon pan by the window. To let it cool.',
          ['ni-time:七時に', 'wo-object:メロンパンを', 'no-possessive:窓のそば', 'masu:置きます', 'n-desu:さますんです']),
        say('hana', 'でも 、 七時半[しちじはん] に 見[み]る と 、 ありません>ある 。', 'But when I look at half past seven, it’s gone.',
          ['to-conditional:見ると', 'masen:ありません']),
        {
          type: 'fill', who: 'kuro',
          ja: '窓[まど] {_} そば 、 です か 。 見[み]て>見る みましょう>みる 。',
          fill: 'の',
          g: ['no-possessive:窓のそば', 'te-miru:見てみましょう'],
          en: 'By the window, you say? Let’s take a look.',
          prompt: 'Which particle joins the two nouns 窓 (window) and そば (side)?',
          answers: ['の'],
          hint: 'It’s the same particle as in わたしの メロンパン.',
          note: 'の joins two nouns: 窓のそば is “the window’s side”, so “by the window”.',
        },
        narr('窓[まど] の そば に 、 何[なに] か 落[お]ちて>落ちる います>いる 。', 'Something is lying by the window.',
          ['question-words:何か', 'te-iru:落ちています']),
        say('kuro', 'おや ？ これ は … 黒[くろ]い 羽[はね] です ね 。', 'Oh? This is… a black feather.',
          ['kosoado:これ', 'i-adj-noun:黒い羽', 'ne:ですね']),
        say('hana', 'クロ さん の 毛[け] じゃ ありません>ある か ？', 'Isn’t that your fur, Kuro?',
          ['no-possessive:クロさんの毛', 'dewa-arimasen:じゃありません', 'ka-question:ありませんか']),
        say('kuro', 'ちがいます>違う 。 わたし>私 の 毛[け] は もっと きれい です 。', 'It is not. My fur is far prettier.',
          ['wa-topic:わたしの毛は', 'desu:きれいです']),
        clue('feather', '黒[くろ]い羽[はね]', 'Black feather', 'Found by the bakery window this morning. Definitely not cat fur.'),
        say('gonta', 'おう 、 クロ ！ 犯人[はんにん] は もう わかった>わかる ぜ ！', 'Hey, Kuro! I’ve already worked out who did it!',
          ['wa-topic:犯人は', 'plain-form:わかった']),
        say('gonta', 'となり の 本屋[ほんや] の 田貫[たぬき] さん だ ！', 'It’s Mr. Tanuki from the bookshop next door!',
          ['no-possessive:となりの本屋の田貫さん', 'plain-form:田貫さんだ']),
        say('tanuki', 'ふぁあ … わし です か ？', '*Yaaawn*… Me?',
          ['ka-question:わしですか']),
        say('kuro', '… どうして です か 、 ゴンタ 刑事[けいじ] 。', '…And why is that, Detective Gonta?',
          ['question-words:どうして']),
        {
          type: 'testimony', who: 'gonta',
          title: 'ゴンタ刑事[けいじ]の証言[しょうげん]',
          titleEn: 'Detective Gonta’s testimony',
          prompt: 'One of these statements clashes with the evidence in your case file. Which one?',
          lines: [
            line('おれ は 毎朝[まいあさ] 、 この 道[みち] を 歩[ある]く ぜ 。', 'I walk down this street every morning.',
              ['wo-path:道を歩く', 'plain-form:歩く'],
              ['kuro', 'それ は 本当[ほんとう] でしょう 。 ゴンタ 刑事[けいじ] は いつも ここ に います>いる から 。', 'That’s probably true. Gonta is always around here.']),
            line('今朝[けさ] 七時半[しちじはん] 、 田貫[たぬき] さん が パン屋[や] の 前[まえ] に いた>いる 。', 'This morning at 7:30, Mr. Tanuki was in front of the bakery.',
              ['no-possessive:パン屋の前', 'ni-aru:前にいた'],
              ['tanuki', 'ええ 、 いました>いる よ 。 パン を 買[か]い>買う に 来[き]た>来る ん です 。', 'Yes, I was. I’d come to buy bread.']),
            line('田貫[たぬき] さん は 白[しろ]い セーター を 着[き]て>着る いた>いる 。', 'Mr. Tanuki was wearing a white sweater.',
              ['i-adj-noun:白いセーター', 'te-iru:着ていた'],
              ['kuro', 'たしか>確か に 、 白[しろ]い セーター です ね 。', 'It certainly is a white sweater.']),
            line('そして 、 窓[まど] の そば に 白[しろ]い 毛[け] が あった>ある ぜ ！', 'And there was white fluff by the window!',
              ['ni-aru:そばに白い毛があった']),
          ],
          wrong: 3,
          hint: 'Open your case file. What did you actually find by the window?',
        },
        {
          type: 'fill', who: 'you',
          ja: '窓[まど] の そば に あった>ある の は 、 白[しろ]い 毛[け] じゃ ありません>ある 。 {_} 羽[はね] です ！',
          fill: '黒[くろ]い',
          g: ['no-wa:あったのは', 'dewa-arimasen:じゃありません', 'i-adj-noun:黒い羽'],
          en: 'What was by the window wasn’t white fluff. It was a ___ feather!',
          prompt: 'Present the evidence! What colour was the feather? (an い-adjective)',
          answers: ['黒[くろ]い'],
          hint: 'The same 黒 as in Kuro’s own name — クロ means “black”.',
          note: 'Colour words like 黒い, 白い and 赤い are い-adjectives and go straight in front of the noun: 黒い羽.',
        },
        say('gonta', 'ぐぬぬ … ！', 'Grrr…!'),
        say('tanuki', 'わし は パン を 買[か]い>買う に 来[き]た>来る だけ です よ … ふぁあ 。', 'I only came to buy bread… *yawn*.',
          ['ni-iku-purpose:買いに来た', 'dake:来ただけです']),
        say('kenta', 'ねえねえ 、 探偵[たんてい] さん ！', 'Hey, hey, Mr. Detective!'),
        say('hana', '弟[おとうと] の ケンタ です 。 なぞなぞ が 大好[だいす]き な ん です 。', 'This is my little brother, Kenta. He loves riddles.',
          ['ga-suki:なぞなぞが大好き', 'n-desu:大好きなんです']),
        say('kenta', 'ぼく>僕 の なぞなぞ に 答[こた]えたら>答える 、 ひみつ>秘密 を 教[おし]えて>教える あげる ！', 'If you answer my riddle, I’ll tell you a secret!',
          ['tara:答えたら', 'te-ageru:教えてあげる']),
        {
          type: 'riddle', who: 'kenta',
          title: 'ナゾ その1',
          ja: 'パン は パン でも 、 食[た]べられない>食べる パン は なーんだ ？',
          g: ['demo-even:パンでも', 'potential:食べられない'],
          en: 'It’s a パン, but you can’t eat it. Which パン is it?',
          answers: ['フライパン'],
          hint: 'You find it in the kitchen and fry eggs in it. Its name ends in …パン.',
          note: 'フライパン, a frying pan! “Xは Xでも…” (“it’s an X, but…”) is the classic opening of a Japanese なぞなぞ.',
        },
        say('kenta', 'せいかい ！ じゃあ 、 ひみつ>秘密 。 毎朝[まいあさ] 、 本屋[ほんや] の 屋根[やね] で 「 カー 、 カー 」 って 声[こえ] が する よ 。', 'Correct! Here’s the secret: every morning there’s a “caw, caw” up on the bookshop roof.',
          ['de-place:屋根で', 'tte:」って', 'ga-subject:声がする']),
        say('kuro', 'にゃるほど … 。 助手[じょしゅ] くん 、 田貫[たぬき] さん に 聞[き]いて>聞く ください 。', 'Nyaruhodo… Assistant, ask Mr. Tanuki about it.',
          ['te-kudasai:聞いてください']),
        {
          type: 'ask', who: 'kuro',
          prompt: 'Ask Mr. Tanuki: “What is on the roof?” Whatever is up there is alive, so use います, not あります.',
          answers: [
            '屋根[やね]に何[なに]がいますか', '屋根[やね]の上[うえ]に何[なに]がいますか', '屋根[やね]には何[なに]がいますか',
            '屋根[やね]に何[なに]かいますか', '屋根[やね]の上[うえ]に何[なに]かいますか', '屋根[やね]の上[うえ]には何[なに]がいますか',
          ],
          line: '屋根[やね] に 何[なに] が います>いる か ？',
          g: ['ni-aru:屋根に何がいます', 'question-words:何が', 'ka-question:いますか'],
          hint: 'Place + に + 何が + います + か. Roof is 屋根 (やね).',
          note: 'います is for living things (people, animals), あります for objects. 何がいますか asks “what’s there?”; 何かいますか asks “is anything there?” Both work.',
        },
        say('tanuki', '屋根[やね] ？ カラス の 巣[す] が あります>ある よ 。 毎朝[まいあさ] うるさくて>うるさい … ふぁあ 。', 'The roof? There’s a crow’s nest. It’s noisy every morning… *yawn*.',
          ['no-possessive:カラスの巣', 'ga-subject:巣があります', 'kute:うるさくて']),

        place('本屋[ほんや]の屋根[やね]', 'The bookshop roof'),
        narr('はしご で 屋根[やね] に 上[のぼ]りました>上る 。', 'You climb a ladder up to the roof.',
          ['de-means:はしごで', 'ni-destination:屋根に上りました']),
        say('karasu', 'カー ！', 'Caw!'),
        {
          type: 'fill', who: 'kuro',
          ja: '見[み]て>見る ください ！ 巣[す] の 中[なか] に メロンパン が {_} あります>ある ！',
          fill: '三[みっ]つ',
          g: ['te-kudasai:見てください', 'ni-aru:中にメロンパンが三つあります', 'counters:三つ'],
          en: 'Look! There are ___ melon pans in the nest!',
          prompt: 'One melon pan a day — Monday, Tuesday, Wednesday. How many are in the nest? Use the native counter 〜つ.',
          answers: ['三[みっ]つ', '3つ', '3'],
          hint: 'ひとつ, ふたつ, …',
          note: 'ひとつ, ふたつ, みっつ, よっつ, いつつ… The つ counter works for almost any object when you don’t know its proper counter.',
        },
        say('kuro', '犯人[はんにん] が わかりました>わかる 。', 'I know who did it.',
          ['ga-subject:犯人が', 'masu-past:わかりました']),
        {
          type: 'fill', who: 'kuro', accuse: true,
          ja: 'メロンパン を 取[と]った>取る の は … {_} です ！',
          fill: 'カラス',
          g: ['no-wa:取ったのは'],
          en: 'The one who took the melon pan is… ___!',
          prompt: 'Name the culprit! Black feathers, a nest on the roof, a voice that goes カー…',
          answers: ['カラス'],
          hint: 'In katakana: カ・ラ・ス.',
          note: 'カラス, the crow! Japanese crows are famous for snatching food — especially anything left by an open window.',
        },
        say('karasu', 'カー … 。', 'Caw…'),
        say('hana', 'もう ！ カラス さん ！', 'Honestly! Mr. Crow!'),
        say('tanuki', 'よかった>いい 。 わし は 犯人[はんにん] じゃ ありません>ある ね 。', 'Good. So I’m not the culprit.',
          ['i-adj-past:よかった', 'dewa-arimasen:じゃありません']),
        say('gonta', 'おれ も 最初[さいしょ] から わかってた>わかる ぜ ！', 'I knew it too! From the very start!',
          ['mo-also:おれも', 'kara-from:最初から', 'te-iru:わかってた']),
        say('kuro', '… はいはい 。 ハナ さん 、 明日[あした] から 窓[まど] を 閉[し]めて>閉める ください ね 。', '…Sure, sure. Hana, please keep the window shut from tomorrow.',
          ['kara-from:明日から', 'te-kudasai:閉めてください']),
        say('hana', 'はい ！ お礼[れい] に 、 メロンパン を どうぞ ！', 'Will do! Please have a melon pan as thanks!',
          ['wo-object:メロンパンを']),
        say('kuro', 'にゃるほど 。 事件[じけん] の 後[あと] の パン は 、 おいしい です ね 。', 'Nyaruhodo. Bread tastes best after a solved case.',
          ['no-possessive:事件の後のパン', 'i-adj-desu:おいしいです']),
      ],
    },

    // ─── Chapter 2 ───────────────────────────────────────────────────────────
    {
      id: 'clocktower',
      num: 2,
      level: 'N5',
      title: '止[と]まった時計台[とけいだい]',
      en: 'The Stopped Clock Tower',
      intro: 'The clock tower over Hidamari Street has stopped, and a strange note built out of kanji is taped to its door. Gonta is calling it a crime notice.',
      skills: 'Telling time · kanji puzzles · て-form · い-adjective past',
      steps: [
        place('商店街[しょうてんがい]の時計台[とけいだい]', 'The shopping street clock tower'),
        narr('朝[あさ] です 。 でも 、 時計台[とけいだい] が 静[しず]か です 。', 'It’s morning. But the clock tower is silent.',
          ['desu:朝です', 'ga-subject:時計台が']),
        say('tokita', 'クロ さん 、 見[み]て>見る ください 。 時計[とけい] が 止[と]まって>止まる いる ん です 。', 'Kuro, look. The clock has stopped.',
          ['te-kudasai:見てください', 'te-iru:止まっている', 'n-desu:いるんです']),
        say('kuro', '本当[ほんとう] です ね 。 針[はり] が 動[うご]いて>動く いません>いる 。', 'So it has. The hands aren’t moving.',
          ['ne:ですね', 'te-iru:動いていません']),
        {
          type: 'fill', who: 'kuro',
          ja: '時計[とけい] は {_} で 止[と]まって>止まる います>いる ね 。',
          fill: '三時[さんじ] 十五分[じゅうごふん]',
          g: ['te-iru:止まっています'],
          en: 'The clock has stopped at ___.',
          prompt: '🕒 The hands point to 3:15. Say the time in Japanese.',
          answers: ['三時十五分[さんじじゅうごふん]', '3時[じ]15分[ふん]'],
          hint: 'Three o’clock is さんじ. Fifteen minutes is じゅうご + ふん.',
          note: '分 is read ふん after 2, 5, 7 and 9 (ごふん, じゅうごふん) but ぷん after 1, 3, 4, 6, 8 and 10 (さんぷん, じゅっぷん).',
        },
        say('tokita', '四十年[よんじゅうねん] 、 毎朝[まいあさ] ねじ を 巻[ま]いて>巻く います>いる が … こんな こと は はじめて>初めて です 。', 'I’ve wound it every morning for forty years… this has never happened before.',
          ['te-iru:巻いています', 'ga-but:いますが']),
        say('tokita', 'それに 、 ドア に こんな 手紙[てがみ] が はって>貼る ありました>ある 。', 'And this letter was stuck to the door.',
          ['te-aru:はってありました']),
        clue('note', 'ふしぎな手紙[てがみ]', 'The strange note', 'Taped to the clock tower door.',
          '「 木[き] 」 と 「 木[き] 」 で 待[ま]って>待つ います>いる 。 「 日[ひ] 」 と 「 月[つき] 」 と 「 日[ひ] 」 の 三時[さんじ] 十五分[じゅうごふん] に 。',
          ['te-iru:待っています']),
        narr('「 木[き] 」 と 「 木[き] 」 で 待[ま]って>待つ います>いる 。 「 日[ひ] 」 と 「 月[つき] 」 と 「 日[ひ] 」 の 三時[さんじ] 十五分[じゅうごふん] に 。', '“I will be waiting at ‘tree’ and ‘tree’. At 3:15 on ‘sun’, ‘moon’ and ‘sun’.”',
          ['te-iru:待っています', 'ni-time:十五分に']),
        say('gonta', 'これ は 犯行予告[はんこうよこく] だ ぜ ！ 大事件[だいじけん] だ ！', 'This is a crime notice! It’s a huge case!',
          ['plain-form:犯行予告だ']),
        say('kuro', '落[お]ち着[つ]いて>落ち着く ください 。 これ は 漢字[かんじ] の なぞなぞ です 。', 'Calm down. This is a kanji riddle.',
          ['te-kudasai:落ち着いてください', 'no-possessive:漢字のなぞなぞ']),
        {
          type: 'riddle', who: 'kuro',
          title: 'ナゾ その2',
          ja: '「 木[き] 」 と 「 木[き] 」 を ならべる>並べる と 、 どんな 漢字[かんじ] に なります>なる か 。',
          g: ['to-conditional:ならべると', 'ni-naru:漢字になります'],
          en: 'Put “tree” (木) next to “tree” (木). Which kanji do you get?',
          answers: ['林[はやし]'],
          hint: 'Two trees are more than one tree but less than a forest (森, もり). It’s read はや…',
          note: '林 (はやし), a grove. Many kanji are built from smaller ones: 木 → 林 → 森. 林 is also a common family name.',
        },
        {
          type: 'riddle', who: 'kuro',
          title: 'ナゾ その3',
          ja: 'では 、 「 日[ひ] 」 と 「 月[つき] 」 を ならべて>並べる 一[ひと]つ の 漢字[かんじ] に します>する 。 その 後[あと] に 、 もう 一[ひと]つ 「 日[ひ] 」 。 どんな ことば に なります>なる か 。',
          g: ['ni-suru:漢字にします', 'ni-naru:ことばになります'],
          en: 'Now put “sun” (日) beside “moon” (月) to make one kanji, then add another 日 after it. What word do you get?',
          answers: ['明日[あした]', '明日[あす]', '明日[みょうにち]'],
          hint: 'Sun + moon make 明, “bright”. 明 + 日 is a day that hasn’t come yet.',
          note: '明日 — “tomorrow” (あした; more formally あす). 日 + 月 = 明 (bright), and the next bright day is tomorrow.',
        },
        say('kuro', 'にゃるほど 。 「 明日[あした] の 三時[さんじ] 十五分[じゅうごふん] に 、 林[はやし] で 待[ま]って>待つ います>いる 」 。', 'Nyaruhodo. “I’ll be waiting in the grove, tomorrow at 3:15.”',
          ['ni-time:十五分に', 'te-iru:待っています']),
        say('tokita', '林[はやし] なら 、 公園[こうえん] の 北[きた] に あります>ある よ 。', 'There’s a grove just north of the park.',
          ['nara:林なら', 'ni-aru:北にあります']),
        say('gonta', 'わかった>わかる ぜ ！ 犯人[はんにん] は ケンタ だ ！ なぞなぞ が 大好[だいす]き だ から な ！', 'I’ve got it! The culprit is Kenta! Because he loves riddles!',
          ['ga-suki:なぞなぞが大好き', 'kara-reason:だから']),
        say('kenta', 'えーっ ！ ？ ぼく>僕 じゃ ない よ ！', 'Whaaat?! It wasn’t me!',
          ['dewa-arimasen:じゃない']),
        {
          type: 'testimony', who: 'gonta',
          title: 'ゴンタ刑事[けいじ]の証言[しょうげん]',
          titleEn: 'Detective Gonta’s testimony',
          prompt: 'Gonta’s reasoning has a hole in it. Which statement doesn’t match the evidence?',
          lines: [
            line('昨日[きのう] の 夕方[ゆうがた] 、 ケンタ は 時計台[とけいだい] の 前[まえ] で 遊[あそ]んで>遊ぶ いた>いる 。', 'Yesterday evening, Kenta was playing in front of the clock tower.',
              ['de-place:前で', 'te-iru:遊んでいた'],
              ['kenta', 'うん 、 遊[あそ]んでた>遊ぶ よ 。 でも 、 それ だけ ！', 'Yeah, I was playing. But that’s all!']),
            line('ケンタ は なぞなぞ が 大好[だいす]き だ 。', 'Kenta loves riddles.',
              ['wa-ga:ケンタはなぞなぞが大好き'],
              ['kenta', 'それ は 本当[ほんとう] だ けど … 。', 'Well, that’s true, but…']),
            line('それに 、 この 手紙[てがみ] は ひらがな だけ で 書[か]いて>書く ある 。 子[こ]ども>子供 の 字[じ] だ ぜ ！', 'Plus, this letter is written only in hiragana. That’s a kid’s writing!',
              ['dake:ひらがなだけ', 'te-aru:書いてある']),
            line('だから 、 犯人[はんにん] は ケンタ だ ！', 'So the culprit is Kenta!',
              ['dakara:だから'],
              ['kuro', 'それ は 結論[けつろん] です 。 おかしい の は 、 その 前[まえ] の どこ か です よ 。', 'That’s his conclusion. What’s wrong is somewhere before it.']),
          ],
          wrong: 2,
          hint: 'Read the note in your case file again. What is it written in?',
        },
        {
          type: 'fill', who: 'you',
          ja: 'ちがいます>違う ！ この 手紙[てがみ] は {_} で 書[か]いて>書く あります>ある ！',
          fill: '漢字[かんじ]',
          g: ['de-means:漢字で', 'te-aru:書いてあります'],
          en: 'Wrong! This letter is written in ___!',
          prompt: 'Look at the note in your case file. What kind of characters is it written in?',
          answers: ['漢字[かんじ]'],
          hint: '木, 日, 月, 待… these characters are called かん…',
          note: '書いてある means “is written (and stays that way)”: the て-form + ある describes the result of someone’s action.',
        },
        say('kenta', 'ぼく>僕 、 まだ 「 待[ま]つ 」 の 漢字[かんじ] 、 書[か]けない>書く よ 。', 'I can’t even write the kanji for 待つ yet.',
          ['potential:書けない']),
        say('gonta', '… むむ 。', '…Hmm.'),
        say('kenta', '探偵[たんてい] さん 、 ぼく>僕 の なぞなぞ も といて>解く よ ！', 'Mr. Detective, solve my riddle too!',
          ['mo-also:なぞなぞも', 'te-request:といて']),
        {
          type: 'riddle', who: 'kenta',
          title: 'ナゾ その4',
          ja: 'さかさま に 読[よ]む と 「 かるい>軽い 」 に なる 動物[どうぶつ] は なーんだ ？',
          g: ['to-conditional:読むと', 'relative-clause:「かるい」になる動物'],
          en: 'Which animal becomes かるい (“light”) when you read its name backwards?',
          answers: ['イルカ'],
          hint: 'Read かるい backwards, one kana at a time. It lives in the sea.',
          note: 'いるか (dolphin) ↔ かるい (light). Reading words backwards (さかさことば) is a favourite Japanese word game.',
        },
        say('kenta', 'せいかい ！ あ 、 そう だ 。 昨日[きのう] の 夜[よる] 、 きつね>狐 の お面[めん] を つけた>つける 人[ひと] が 、 時計台[とけいだい] に 入[はい]って>入る いった>いく よ 。', 'Correct! Oh, right — last night, someone in a fox mask went into the clock tower.',
          ['relative-clause:お面をつけた人', 'te-iku:入っていった']),
        say('kuro', 'きつね>狐 の お面[めん] … 。', 'A fox mask…'),
        {
          type: 'ask', who: 'kuro',
          prompt: 'Ask Mr. Tokita: “Who has the key to the clock tower?” To have / to hold is 持っている (polite: 持っています).',
          answers: [
            '時計台[とけいだい]の鍵[かぎ]は誰[だれ]が持[も]っていますか', '誰[だれ]が時計台[とけいだい]の鍵[かぎ]を持[も]っていますか',
            '鍵[かぎ]は誰[だれ]が持[も]っていますか', '誰[だれ]が鍵[かぎ]を持[も]っていますか',
            '時計台[とけいだい]の鍵[かぎ]を誰[だれ]が持[も]っていますか',
          ],
          line: '時計台[とけいだい] の 鍵[かぎ] は 誰[だれ] が 持[も]って>持つ います>いる か ？',
          g: ['wa-ga:鍵は誰が', 'question-words:誰が', 'te-iru:持っています'],
          hint: '時計台の かぎは + だれが + 持っていますか.',
          note: '持っている (to have) takes ている because owning something is an ongoing state. だれが asks “who?” as the subject.',
        },
        say('tokita', 'わたし>私 と … あと 、 骨董屋[こっとうや] の 狐塚[きつねづか] さん です 。 去年[きょねん] 、 時計[とけい] を 直[なお]して>直す くれました>くれる 。', 'Me… and Madame Kitsunezuka from the antique shop. She repaired the clock for me last year.',
          ['to-and:わたしと', 'te-kureru:直してくれました']),
        {
          type: 'fill', who: 'kuro', accuse: true,
          ja: '時計[とけい] を 止[と]めた>止める の は … {_} さん です ね 。',
          fill: '狐塚[きつねづか]',
          g: ['no-wa:止めたのは'],
          en: 'The one who stopped the clock was… ___-san.',
          prompt: 'A fox mask, a key, and a taste for puzzles. Who stopped the clock?',
          answers: ['狐塚[きつねづか]'],
          hint: 'Her name begins with きつね, “fox”.',
          note: '狐塚: 狐 (きつね, fox) + 塚 (つか, mound). In the compound つ turns into づ — a sound change called rendaku.',
        },

        place('公園[こうえん]の林[はやし]・次[つぎ]の日[ひ]、三時十五分[さんじじゅうごふん]', 'The grove in the park · next day, 3:15'),
        narr('林[はやし] の 中[なか] に 、 だれか が 立[た]って>立つ います>いる 。', 'Someone is standing among the trees.',
          ['question-words:だれか', 'te-iru:立っています']),
        say('kitsune', 'ようこそ 。 お待[ま]ち>待つ して>する おりました>おる わ 、 クロ 探偵[たんてい] 。', 'Welcome. I have been expecting you, Detective Kuro.',
          ['kenjougo:お待ちしておりました']),
        say('kuro', 'やはり あなた でした>です か 、 狐塚[きつねづか] さん 。', 'So it was you after all, Madame Kitsunezuka.',
          ['deshita:あなたでした']),
        {
          type: 'ask', who: 'kuro',
          prompt: 'Ask her: “Why did you stop the clock?” Why = どうして or なぜ; to stop something = 止める (とめる).',
          answers: [
            'どうして時計[とけい]を止[と]めたんですか', 'なぜ時計[とけい]を止[と]めたんですか',
            'どうして時計[とけい]を止[と]めたのですか', 'なぜ時計[とけい]を止[と]めたのですか',
            'どうして時計[とけい]を止[と]めましたか', 'なぜ時計[とけい]を止[と]めましたか',
            'どうして止[と]めたんですか', 'なぜ止[と]めたんですか',
          ],
          line: 'どうして 時計[とけい] を 止[と]めた>止める ん です か ？',
          g: ['doushite:どうして時計を止めたんですか', 'wo-object:時計を'],
          hint: 'どうして + 時計を + 止めた + んですか.',
          note: '止める (to stop something) is transitive, 止まる (to come to a stop) intransitive: 時計を止めた vs 時計が止まった. Ending a question with 〜んですか asks for the story behind it.',
        },
        say('kitsune', '歯車[はぐるま] が 古[ふる]くて>古い 、 もうすぐ こわれ>壊れる そう だった>だ の>の(explain) です 。', 'One of the gears was old and about to break.',
          ['kute:古くて', 'sou-looks:こわれそうだった']),
        {
          type: 'fill', who: 'kitsune',
          ja: 'です から 、 新[あたら]しい 歯車[はぐるま] を {_} きました>くる わ 。',
          fill: '作[つく]って>作る',
          g: ['i-adj-noun:新しい歯車', 'te-kuru:作ってきました'],
          en: 'So I made a new gear and brought it along.',
          prompt: 'Fill in the て-form of 作る (つくる, to make). 〜て + きました = “made it and came (with it)”.',
          answers: ['作[つく]って'],
          hint: 'A godan verb ending in る: つくる → つく + って.',
          note: 'Godan verbs ending in う, つ and る take って: 作る → 作って, 待つ → 待って, 買う → 買って.',
        },
        say('kitsune', 'それに 、 有名[ゆうめい] な 探偵[たんてい] さん を 、 ちょっと ためして>試す みたかった>みる の>の(explain) です 。', 'Besides, I wanted to put the famous detective to a little test.',
          ['na-adj-noun:有名な探偵', 'te-miru:ためしてみたかった', 'tai:みたかった']),
        say('gonta', 'おれ は ぜんぜん>全然 こわくなかった>怖い ぜ ！', 'I wasn’t scared at all!',
          ['zenzen-neg:ぜんぜんこわくなかった', 'i-adj-neg-past:こわくなかった']),
        {
          type: 'fill', who: 'kuro',
          ja: 'でも 、 「 大事件[だいじけん] だ ！ 」 って 言[い]って>言う いました>いる よ 。 ちょっと {_} でしょう ？',
          fill: 'こわかった>怖い',
          g: ['tte:」って', 'te-iru:言っていました', 'i-adj-past:こわかった', 'deshou:でしょう'],
          en: 'But you were shouting “It’s a huge case!” You were a bit scared, weren’t you?',
          prompt: 'Put こわい (scary, scared) into the past tense.',
          answers: ['こわかった', '怖[こわ]かった'],
          hint: 'い-adjective past: drop the い, add かった.',
          note: 'こわい → こわかった, たのしい → たのしかった. The one exception is いい → よかった.',
        },
        say('kitsune', 'ふふ 。 さすが です わ 。 では 、 こちら を どうぞ 。 わたくし の 店[みせ] の パーティー の 招待状[しょうたいじょう] です 。', 'Hehe. Impressive. Then please take this: an invitation to a party at my shop.',
          ['kosoado:こちら', 'no-possessive:わたくしの店のパーティーの招待状']),
        clue('invite', '招待状[しょうたいじょう]', 'Invitation', 'A gold-edged card for a party at Kitsunezuka Antiques. “Detective Kuro and assistant — your attendance is requested.”'),
        narr('カチ 、 カチ 、 カチ … 。 時計台[とけいだい] が また 動[うご]き出[だ]しました>動き出す 。', 'Tick, tick, tick… The clock tower starts moving again.',
          ['hajimeru:動き出しました']),
        say('tokita', 'ああ 、 よかった>いい ！ 動[うご]きました>動く ！', 'Oh, thank goodness! It’s moving!',
          ['i-adj-past:よかった', 'masu-past:動きました']),
        say('kuro', 'にゃるほど … 。 次[つぎ] は パーティー 、 です か 。', 'Nyaruhodo… A party next, is it.',
          ['wa-topic:次は']),
      ],
    },

    // ─── Chapter 3 ───────────────────────────────────────────────────────────
    {
      id: 'teabowl',
      num: 3,
      level: 'N4',
      title: '月[つき]の茶碗[ちゃわん]',
      en: 'The Moon Tea Bowl',
      intro: 'At Madame Kitsunezuka’s party, a 300-year-old tea bowl vanishes the moment the lights go out. The window is open — but is that what really happened?',
      skills: 'Keigo · 〜ている vs 〜てある · ある negative · 〜てしまう',
      steps: [
        place('狐塚骨董店[きつねづかこっとうてん]', 'Kitsunezuka Antiques'),
        narr('雨[あめ] の 夜[よる] 。 店[みせ] の 中[なか] は 、 古[ふる]い 物[もの] で いっぱい です 。', 'A rainy night. The shop is crammed with old things.',
          ['i-adj-noun:古い物', 'de-full:古い物でいっぱい']),
        say('kitsune', 'ようこそ いらっしゃいました>いらっしゃる 、 クロ 探偵[たんてい] 。', 'Welcome, Detective Kuro.',
          ['sonkeigo:いらっしゃいました']),
        say('kuro', '助手[じょしゅ] くん 、 狐塚[きつねづか] さん は とても 丁寧[ていねい] に 話[はな]します>話す 。 こちら も 丁寧[ていねい] に お礼[れい] を 言[い]いましょう>言う 。', 'Assistant, Madame Kitsunezuka speaks very politely. Let’s thank her just as politely.',
          ['na-adverb:丁寧に', 'mo-also:こちらも', 'mashou:言いましょう']),
        {
          type: 'ask', who: 'kuro',
          prompt: 'Thank her politely: “Thank you for inviting me.” Use 招待する (しょうたいする, to invite) + てくださって + ありがとうございます.',
          answers: [
            '招待[しょうたい]してくださってありがとうございます', '招待[しょうたい]してくださってどうもありがとうございます',
            'ご招待[しょうたい]くださってありがとうございます', 'ご招待[しょうたい]ありがとうございます',
            '招待[しょうたい]していただいてありがとうございます', '呼[よ]んでくださってありがとうございます',
          ],
          line: '招待[しょうたい] して>する くださって>くださる ありがとうございます 。',
          g: ['te-kureru:してくださって', 'sonkeigo:くださって'],
          hint: 'しょうたいして + くださって + ありがとうございます.',
          note: '〜てくださって ありがとうございます thanks someone for doing something for you. くださる is the respectful form of くれる.',
        },
        say('kitsune', 'まあ 、 ご丁寧[ていねい]>丁寧 に 。 どうぞ 、 お入[はい]り>入る ください 。', 'My, how polite. Please, do come in.',
          ['o-honorific:お入りください']),
        narr('パーティー に は 、 ハナ さん 、 ケンタ くん 、 田貫[たぬき] さん 、 ゴンタ 刑事[けいじ] も 来[き]て>来る います>いる 。', 'Hana, Kenta, Mr. Tanuki and Detective Gonta are at the party too.',
          ['ni-wa:パーティーには', 'te-iru:来ています']),
        say('mame', 'あの 、 はじめまして 。 助手[じょしゅ] の マメ です 。', 'Um, nice to meet you. I’m Mame, the assistant.',
          ['desu:マメです']),
        say('kenta', '探偵[たんてい] さん ！ 新[あたら]しい なぞなぞ だ よ ！', 'Mr. Detective! I’ve got a new riddle!',
          ['i-adj-noun:新しいなぞなぞ', 'yo:だよ']),
        {
          type: 'riddle', who: 'kenta',
          title: 'ナゾ その5',
          ja: 'トラ は トラ でも 、 道[みち] を 走[はし]る トラ は なーんだ ？',
          g: ['demo-even:トラでも', 'relative-clause:道を走るトラ', 'wo-path:道を走る'],
          en: 'It’s a トラ (tiger), but it drives along the road. Which トラ is it?',
          answers: ['トラック'],
          hint: 'A big vehicle that carries things. A loanword from English, starting トラ…',
          note: 'トラック, a truck! English loanwords often get a small っ before a k sound: truck → トラック, bag → バッグ.',
        },
        say('kitsune', 'では 、 今夜[こんや] の 主役[しゅやく] を ご覧[らん] ください 。', 'And now, please behold the star of the evening.',
          ['sonkeigo:ご覧ください']),
        say('kitsune', '「 月[つき] の 茶碗[ちゃわん] 」 で ございます>ござる 。 三百年[さんびゃくねん] 前[まえ] に 作[つく]られた>作る もの です わ 。', 'The “Moon Tea Bowl”. It was made three hundred years ago.',
          ['kenjougo:でございます', 'passive:作られた', 'relative-clause:作られたもの']),
        {
          type: 'meaning', who: 'kuro',
          prompt: 'How old is the tea bowl? (In English, or as a number.)',
          answers: ['300', 'three hundred', '三百'],
          hint: '三百 = 3 × 100. Careful: ひゃく turns into びゃく after さん.',
          note: 'さんびゃく (300), ろっぴゃく (600) and はっぴゃく (800) change their sound; the other hundreds are a plain ひゃく.',
        },
        clue('bowl', '月[つき]の茶碗[ちゃわん]', 'The Moon Tea Bowl', 'A 300-year-old tea bowl with a moon pattern, shown in a glass case in the middle of the shop.'),
        narr('その 時[とき] … パッ ！ 電気[でんき] が 消[き]えました>消える 。', 'At that moment… click! The lights go out.',
          ['toki:その時', 'ga-subject:電気が']),
        say('hana', 'きゃー ！ 何[なに] も 見[み]えない>見える ！', 'Eek! I can’t see a thing!',
          ['nani-mo-neg:何も見えない']),
        narr('十秒後[じゅうびょうご] 、 電気[でんき] が つきました>つく 。 ガラス の ケース は … からっぽ です 。', 'Ten seconds later the lights come back on. The glass case is… empty.',
          ['ga-subject:電気が', 'wa-topic:ケースは']),
        say('kitsune', '茶碗[ちゃわん] が … ありません>ある わ ！', 'The tea bowl… it’s gone!',
          ['masen:ありません']),
        say('mame', '大変[たいへん] です ！ 窓[まど] が 開[あ]いて>開く います>いる ！ どろぼう>泥棒 は 窓[まど] から 逃[に]げた>逃げる ん です ！', 'This is terrible! The window is open! The thief got away through the window!',
          ['te-iru:開いています', 'kara-from:窓から', 'n-desu:逃げたんです']),
        say('gonta', 'よし 、 外[そと] を 探[さが]す ぜ ！', 'Right, I’ll search outside!',
          ['wo-object:外を探す']),
        say('kuro', '待[ま]って>待つ ください 。 まず 、 窓[まど] を よく 見[み]ましょう>見る 。', 'Wait. First, let’s take a good look at the window.',
          ['te-kudasai:待ってください', 'mashou:見ましょう']),
        narr('窓[まど] の 外[そと] は 雨[あめ] で 、 地面[じめん] は どろどろ です 。 でも 、 足[あし]あと は 一[ひと]つ も ありません>ある 。', 'Outside, the rain has turned the ground to mud. But there isn’t a single footprint.',
          ['de-and:雨で', 'wa-contrast:地面は', 'nani-mo-neg:一つもありません']),
        clue('mud', '窓[まど]の外[そと]のどろ', 'Mud under the window', 'Soft, wet mud right below the open window. Not one footprint in it.'),
        say('kuro', 'それに 、 この 窓[まど] は とても 重[おも]い です 。 風[かぜ] で は 開[あ]きません>開く 。', 'Besides, this window is very heavy. The wind couldn’t open it.',
          ['i-adj-desu:重いです', 'de-means:風では', 'masen:開きません']),
        {
          type: 'fill', who: 'kuro',
          ja: 'この 窓[まど] は 、 ただ 開[あ]いて>開く いる ん じゃ ない 。 だれか が わざと 開[あ]けた>開ける … 。 窓[まど] が {_} ある ん です 。',
          fill: '開[あ]けて>開ける',
          g: ['te-iru:開いている', 'te-aru:開けてある', 'n-desu:あるんです'],
          en: 'This window isn’t simply open. Someone opened it on purpose… The window has been opened (and left that way).',
          prompt: 'Mame said 窓が開いています, “the window is open”. But someone did this deliberately. Use the transitive verb 開ける (あける) in て-form, before ある.',
          answers: ['開[あ]けて'],
          hint: 'あける → あけて.',
          note: '開いている (intransitive 開く + ている) just describes a state: “it’s open”. 開けてある (transitive 開ける + てある) says someone opened it and left it like that — a detective’s favourite verb form.',
        },
        say('kitsune', 'では 、 どろぼう>泥棒 は 外[そと] から 来[こ]なかった>来る 、 と いう>言う こと です か ？', 'Then you are saying the thief did not come from outside?',
          ['kara-from:外から', 'to-iu:ということ']),
        say('mame', 'でも … ぼく>僕 は 見[み]ました>見る ！', 'B-but… I saw them!',
          ['masu-past:見ました']),
        {
          type: 'testimony', who: 'mame',
          title: 'マメの証言[しょうげん]',
          titleEn: 'Mame’s testimony',
          prompt: 'One of these statements can’t be true, given the evidence. Which?',
          lines: [
            line('電気[でんき] が 消[き]えた>消える 時[とき] 、 ぼく>僕 は 台所[だいどころ] に いました>いる 。', 'When the lights went out, I was in the kitchen.',
              ['toki:消えた時', 'ni-aru:台所にいました'],
              ['kuro', 'ふむ 。 台所[だいどころ] … 覚[おぼ]えて>覚える おきましょう>おく 。', 'Hmm. The kitchen… let’s remember that.']),
            line('電気[でんき] が ついた>つく 時[とき] 、 窓[まど] が 開[あ]いて>開く いました>いる 。', 'When the lights came back on, the window was open.',
              ['toki:ついた時', 'te-iru:開いていました'],
              ['kuro', '窓[まど] が 開[あ]いて>開く いた>いる の は 、 本当[ほんとう] です ね 。', 'It’s true the window was open.']),
            line('黒[くろ]い 服[ふく] の 人[ひと] が 、 窓[まど] から 外[そと] に 飛[と]び出[だ]して>飛び出す 、 走[はし]って>走る いきました>いく 。', 'Someone dressed in black jumped out of the window and ran off.',
              ['te-sequence:飛び出して', 'te-iku:走っていきました']),
            line('きっと 、 もう 遠[とお]く に 逃[に]げた>逃げる と 思[おも]います>思う 。', 'I’m sure they’ve already got far away.',
              ['to-omou:逃げたと思います'],
              ['kuro', 'それ は マメ さん の 考[かんが]え です ね 。 証拠[しょうこ] と ぶつかって>ぶつかる は いません>いる 。', 'That’s just Mame’s opinion. It doesn’t clash with any evidence.']),
          ],
          wrong: 2,
          hint: 'If someone ran out into the mud, what would they leave behind?',
        },
        {
          type: 'fill', who: 'you',
          ja: '外[そと] に 走[はし]って>走る いった>いく なら 、 どろ に 足[あし]あと が ある はず です 。 でも 、 足[あし]あと は 一[ひと]つ も {_} ！',
          fill: 'ありません>ある',
          g: ['nara:いったなら', 'hazu:あるはずです', 'nani-mo-neg:一つもありません'],
          en: 'If someone ran outside, there should be footprints in the mud. But there isn’t a single one!',
          prompt: 'Finish the objection with the polite negative of ある.',
          answers: ['ありません', 'ないです', 'ありませんでした', 'なかったです'],
          hint: 'あります → あり…',
          note: 'The negative of ある is irregular: ない (plain), ありません (polite) — never あらない. 〜はずです means “it should (logically) be so”.',
        },
        say('mame', 'う … 。', 'Ugh…'),
        say('kitsune', 'では 、 犯人[はんにん] は まだ この 部屋[へや] に いらっしゃる 、 と いう>言う こと です わ ね 。', 'Then the culprit must still be in this very room.',
          ['sonkeigo:いらっしゃる', 'to-iu:ということ']),
        {
          type: 'fill', who: 'kuro',
          ja: '「 いらっしゃる 」 は 、 ふつう の 言葉[ことば] で 言[い]う と 「 {_} 」 です ね 。',
          fill: 'いる',
          g: ['to-conditional:言うと', 'sonkeigo:いらっしゃる'],
          en: 'In ordinary words, いらっしゃる means “___”.',
          prompt: 'いらっしゃる is the respectful (尊敬語) form of which plain verb here? The culprit is still in the room.',
          answers: ['いる'],
          hint: 'The culprit “is” in the room. For people, that’s い…',
          note: 'いらっしゃる is the honorific for いる, 行く and 来る. Madame Kitsunezuka is polite even about a thief!',
        },
        say('hana', 'あの … クロ さん 。 これ 、 台所[だいどころ] の ゴミ箱[ばこ] に ありました>ある 。', 'Um… Kuro. I found this in the kitchen bin.',
          ['ni-aru:ゴミ箱にありました']),
        clue('shards', '茶碗[ちゃわん]のかけら', 'Broken pieces', 'Pieces of a tea bowl with a moon pattern, wrapped in a napkin and hidden at the bottom of the kitchen bin.'),
        say('kuro', '台所[だいどころ] … 。 電気[でんき] が 消[き]えた>消える 時[とき] 、 台所[だいどころ] に いた>いる の は だれ>誰 でした>です か 。', 'The kitchen… Who was in the kitchen when the lights went out?',
          ['toki:消えた時', 'no-wa:いたのはだれでしたか']),
        {
          type: 'fill', who: 'kuro', accuse: true,
          ja: '犯人[はんにん] は … {_} さん です ！',
          fill: 'マメ',
          g: ['wa-topic:犯人は'],
          en: 'The culprit is… ___!',
          prompt: 'Who was in the kitchen? Who insisted the thief went out of the window?',
          answers: ['マメ'],
          hint: 'Check the testimony: 「ぼくは台所にいました」.',
          note: 'His own testimony put him in the kitchen — right where the pieces were hidden.',
        },
        say('mame', '… ごめんなさい ！', '…I’m so sorry!'),
        say('mame', 'パーティー の 前[まえ] に 、 茶碗[ちゃわん] を ケース から 出[だ]して>出す 、 ふいて>拭く いた>いる ん です 。 そうしたら 、 手[て] が すべって>滑る … 。', 'Before the party I took the bowl out of its case to polish it. And then my hand slipped…',
          ['mae-ni:パーティーの前に', 'te-iru:ふいていた', 'n-desu:いたんです']),
        say('mame', 'こわくて>怖い 、 言[い]えませんでした>言う 。 だから 電気[でんき] を 消[け]して>消す 、 窓[まど] を 開[あ]けて>開ける … 。', 'I was too scared to say. So I switched off the lights, opened the window…',
          ['te-reason:こわくて', 'potential:言えませんでした', 'te-sequence:消して']),
        {
          type: 'fill', who: 'kuro',
          ja: 'つまり 、 マメ さん は うっかり 茶碗[ちゃわん] を {_} ん です ね 。',
          fill: '割[わ]って>割る しまった>しまう',
          g: ['te-shimau:割ってしまった', 'n-desu:しまったんです'],
          en: 'In other words, Mame accidentally broke the tea bowl.',
          prompt: 'Use 割る (わる, to break) + てしまった — “did it by accident, and regrets it”.',
          answers: ['割[わ]ってしまった', '割[わ]っちゃった'],
          hint: 'わる → わって + しまった.',
          note: '〜てしまう adds “by accident” or “and I regret it”. In casual speech it shrinks to 〜ちゃう: 割っちゃった.',
        },
        say('kitsune', '… マメ 。 顔[かお] を 上[あ]げなさい>上げる 。', '…Mame. Lift your head.',
          ['nasai:上げなさい']),
        say('kitsune', 'あれ は レプリカ です わ 。 本物[ほんもの] は 、 ずっと 金庫[きんこ] の 中[なか] です 。', 'That was a replica. The real one has been in the safe all along.',
          ['kosoado:あれ', 'wa-contrast:本物は']),
        {
          type: 'meaning', who: 'kuro',
          prompt: 'Wait — what was the bowl that broke?',
          answers: ['replica', 'copy', 'fake', 'imitation', 'not real', 'not the real', 'reproduction', 'counterfeit'],
          hint: 'レプリカ is a loanword. 本物 (ほんもの) means “the real thing”.',
          note: 'レプリカ = replica. 本物 (the real thing) ↔ 偽物 (にせもの, a fake).',
        },
        say('kitsune', 'クロ 探偵[たんてい] が 本当[ほんとう] に 名探偵[めいたんてい] か 、 ためしたかった>試す の>の(explain) です 。', 'I wanted to test whether Detective Kuro is truly a great detective.',
          ['embedded-question:名探偵か', 'tai:ためしたかった']),
        say('kuro', '… また 、 です か 。', '…Again?'),
        say('gonta', 'おれ は 最初[さいしょ] から わかってた>わかる ぜ ！', 'I knew from the start!',
          ['kara-from:最初から']),
        narr('その 時[とき] 、 外[そと] から 大[おお]きな 声[こえ] が 聞[き]こえました>聞こえる 。', 'Just then, a loud voice comes from outside.',
          ['kara-from:外から', 'ga-subject:声が']),
        say('uozumi', 'ない ！ ない ！ 祭[まつ]り の 鯛[たい] が ない ぞ ！', 'It’s gone! Gone! The festival sea bream is gone!',
          ['no-possessive:祭りの鯛', 'ga-subject:鯛がない']),
      ],
    },

    // ─── Chapter 4 ───────────────────────────────────────────────────────────
    {
      id: 'arrested',
      num: 4,
      level: 'N3',
      title: 'クロ、逮捕[たいほ]される！？',
      en: 'Kuro Arrested?!',
      intro: 'The fishmonger’s festival sea bream has vanished, a torn note says 「クロにたべ」, and Gonta has Kuro in handcuffs. This time Kuro can’t solve the case. You have to.',
      skills: 'Hearsay そうだ · passive vs causative · 〜ておく · humble apologies',
      steps: [
        place('魚屋[さかなや]「魚住[うおずみ]」', 'Uozumi Fish Shop'),
        say('uozumi', '明日[あした] の 祭[まつ]り の ため の 、 一番[いちばん] 大[おお]きい 鯛[たい] だった>だ ん だ ！', 'It was the biggest sea bream I had — for tomorrow’s festival!',
          ['tame-ni:祭りのための', 'ichiban:一番大きい']),
        say('gonta', '店[みせ] の 台[だい] の 上[うえ] に メモ が あった>ある ぜ 。 見[み]ろ>見る ！', 'There was a memo on the counter. Look!',
          ['ni-aru:上にメモがあった', 'meirei:見ろ']),
        clue('memo', 'やぶれたメモ', 'Torn memo', 'Half a memo, torn down the middle, found on the counter. All that’s left reads 「クロにたべ」…'),
        say('gonta', '「 クロ に たべ>食べる 」 … つまり 、 「 鯛[たい] は クロ に 食[た]べられた>食べる 」 って こと だ ！', '“Kuro… ea—” That means “The sea bream was eaten by Kuro”!',
          ['passive:クロに食べられた', 'tte:」って']),
        say('gonta', 'クロ 、 逮捕[たいほ] だ ！', 'Kuro, you’re under arrest!'),
        say('kuro', 'にゃ ！ ？', 'Nya?!'),
        narr('カチャッ 。 クロ の 前足[まえあし] に 、 小[ちい]さな 手錠[てじょう] が かけられました>かける 。', 'Click. A tiny pair of handcuffs closes around Kuro’s front paws.',
          ['no-possessive:クロの前足', 'passive:かけられました']),
        say('kitsune', 'お待[ま]ち>待つ なさい 。 わたくし は 商店街[しょうてんがい] の 会長[かいちょう] です 。 みなさん の 前[まえ] で 、 きちんと お話[はなし]>話 を 聞[き]きましょう>聞く 。', 'Hold on. I am chair of the shopping street association. Let us hear this out properly, in front of everyone.',
          ['nasai:お待ちなさい', 'de-place:前で', 'mashou:聞きましょう']),

        place('商店街[しょうてんがい]の広場[ひろば]・臨時[りんじ]の裁判[さいばん]', 'The street square · an emergency hearing'),
        say('kuro', '助手[じょしゅ] くん … 今日[きょう] は 、 きみ>君 が わたし>私 を 助[たす]けて>助ける ください 。', 'Assistant… today, you’re the one who has to save me.',
          ['ga-subject:きみが', 'te-kudasai:助けてください']),
        {
          type: 'fill', who: 'you',
          ja: 'クロ さん が 鯛[たい] を 盗[ぬす]んだ>盗む {_} ありません>ある ！',
          fill: 'はず が',
          g: ['hazu-ga-nai:盗んだはずがありません'],
          en: 'There’s no way Kuro stole the sea bream!',
          prompt: 'Stand up for Kuro! “There’s no way that…” = verb + はずが + ありません.',
          answers: ['はずが', 'はずは', 'わけが', 'わけは'],
          hint: 'Two kana, then が: は…',
          note: '〜はずがない = “there’s no way that (logically)…”. Compare 〜はずだ, “it should be so”, which you used in the last case.',
        },
        say('gonta', 'ふん 。 じゃあ 、 魚住[うおずみ] さん の 話[はなし] を 聞[き]け>聞く ！', 'Hmph. Then listen to what Mr. Uozumi has to say!',
          ['meirei:聞け']),
        {
          type: 'testimony', who: 'uozumi',
          title: '魚住[うおずみ]さんの証言[しょうげん]',
          titleEn: 'Mr. Uozumi’s testimony',
          prompt: 'One of these is not something Mr. Uozumi saw with his own eyes. Which statement is only hearsay?',
          lines: [
            line('朝[あさ] 六時[ろくじ] に 、 鯛[たい] を 店[みせ] の 前[まえ] に 並[なら]べた>並べる ！', 'At six this morning, I laid the sea bream out in front of the shop!',
              ['ni-time:六時に', 'wo-object:鯛を'],
              ['kuro', 'それ は 魚住[うおずみ] さん が 自分[じぶん] で した>する こと です ね 。', 'That’s something he did himself.']),
            line('八時[はちじ] ごろ 、 配達[はいたつ] に 出[で]かけた>出かける 。 店[みせ] に は 母[はは] が いた>いる はず だ ！', 'Around eight I went out on deliveries. My mother should have been minding the shop!',
              ['goro:八時ごろ', 'hazu:いたはずだ'],
              ['kuro', '「 はず だ 」 … 気[き] に なります>なる ね 。 でも 、 ここ で は ありません>ある 。', '“Should have been”… intriguing. But that’s not the weak spot.']),
            line('九時[くじ] に 帰[かえ]って>帰る きたら>くる 、 鯛[たい] が なくなって>なくなる いた>いる ！', 'When I got back at nine, the sea bream was gone!',
              ['tara:帰ってきたら', 'te-iru:なくなっていた'],
              ['kuro', 'それ は 自分[じぶん] の 目[め] で 見[み]た>見る こと です 。', 'He saw that with his own eyes.']),
            line('クロ が 大[おお]きい 魚[さかな] を くわえて>くわえる 走[はし]って>走る いた>いる そう だ ！', 'Kuro was apparently running off with a big fish in his mouth!',
              ['sou-hearsay:いたそうだ', 'te-iru:走っていた']),
          ],
          wrong: 3,
          hint: 'Look at how each sentence ends. One ends in a word that reports what someone else said.',
        },
        {
          type: 'meaning', who: 'kuro',
          prompt: 'He said 走っていたそうだ. What does 〜そうだ after a plain verb tell you about where he got this?',
          answers: ['heard', 'hearsay', 'someone said', 'someone told', 'was told', 'apparently', 'reportedly', 'they say', 'people say', 'rumor', 'rumour', 'second hand', 'secondhand', 'second-hand', 'didn’t see', 'didn\'t see', 'did not see', 'not see'],
          hint: 'Plain verb + そうだ is not “looks like” (that’s the ます-stem + そう). It reports something you…',
          note: '走っていたそうだ = “I hear he was running”: reported speech. Compare 走りそうだ = “he looks like he’s about to run”. Same そう, different attachment, very different meaning.',
        },
        say('uozumi', 'う … そう 聞[き]いた>聞く だけ だ 。 言[い]った>言う の は ゴンタ 刑事[けいじ] だ ！', 'Er… I only heard it. Detective Gonta was the one who said it!',
          ['dake:聞いただけ', 'no-wa:言ったのはゴンタ刑事だ']),
        say('gonta', 'おれ は … メモ を 読[よ]んで>読む 、 そう 思[おも]った>思う だけ だ … 。', 'I… I just read the memo and figured that’s what happened…',
          ['te-sequence:読んで', 'dake:思っただけだ']),
        say('kuro', '… それ は 証拠[しょうこ] で は ありません>ある 。', '…That is not evidence.',
          ['dewa-arimasen:ではありません']),
        {
          type: 'ask', who: 'kuro',
          prompt: 'Ask Mr. Uozumi to let you look around the shop: “Please let me see the shop.” Use the causative 見させてください — or simply ask him to show you, 見せてください.',
          answers: [
            '店[みせ]を見[み]させてください', 'お店[みせ]を見[み]させてください', '店[みせ]の中[なか]を見[み]させてください', 'お店[みせ]の中[なか]を見[み]させてください',
            '店[みせ]を見[み]せてください', 'お店[みせ]を見[み]せてください', '店[みせ]の中[なか]を見[み]せてください', 'お店[みせ]の中[なか]を見[み]せてください',
          ],
          line: '店[みせ] を 見[み]させて>見る ください 。',
          g: ['sasete-kudasai:見させてください'],
          hint: '(お)店を + 見させて + ください.',
          note: 'Causative て-form + ください asks for permission: 見させてください, “let me look”. 見せる (to show) is a verb of its own: 見せてください, “please show me”.',
        },

        place('魚屋[さかなや]の中[なか]', 'Inside the fish shop'),
        narr('床[ゆか] が ぬれて>ぬれる います>いる 。 店[みせ] の 前[まえ] から 奥[おく] まで 、 水[みず] の あと が 続[つづ]いて>続く います>いる 。', 'The floor is wet. A trail of water runs from the front of the shop to the back.',
          ['kara-made:前から奥まで', 'te-iru:続いています']),
        narr('奥[おく] に は 、 大[おお]きな 冷蔵庫[れいぞうこ] が あります>ある 。', 'At the back stands a big refrigerator.',
          ['ni-wa:奥には', 'ni-aru:冷蔵庫があります']),
        clue('trail', '水[みず]のあと', 'Trail of water', 'Drips of water leading from the display at the front of the shop all the way to the big fridge at the back.'),
        narr('ゴミ箱[ばこ] の 中[なか] に 、 紙[かみ] が 一枚[いちまい] … 。', 'In the bin, a single scrap of paper…',
          ['counters:一枚']),
        clue('memo2', 'メモの右半分[みぎはんぶん]', 'Other half of the memo', 'Found in the shop’s bin, next to a few small sardine bones. It reads 「させた。ウメ」.'),
        say('kuro', '二[ふた]つ を 合[あ]わせる と … 「 クロ に たべさせた>食べる 。 ウメ 」 。', 'Put the two halves together… 「クロにたべさせた。ウメ」.',
          ['to-conditional:合わせると', 'causative:たべさせた']),
        {
          type: 'meaning', who: 'kuro',
          prompt: 'Gonta read it as 食べられた — passive, “was eaten by Kuro”. But 食べさせた is causative. Translate the memo: “I ___ Kuro. —Ume” (one English word)',
          answers: ['fed', 'feed', 'let', 'made', 'gave', 'allowed'],
          hint: 'Causative 〜させる = make or let someone do something. “Made / let Kuro eat” in one word is…',
          note: '食べさせた = “made/let (Kuro) eat”, i.e. “fed”. Granny Ume was leaving a note for her son.',
        },
        {
          type: 'fill', who: 'you',
          ja: '「 クロ に 食[た]べられた>食べる 」 じゃ ない 。 「 クロ に 食[た]べ{_}た>食べる 」 です ！',
          fill: 'させ',
          g: ['passive:食べられた', 'causative:食べさせた'],
          en: 'Not “eaten by Kuro” — “let Kuro eat”!',
          prompt: 'Fill in the causative ending: 食べる → 食べ＿＿る, here in the past.',
          answers: ['させ'],
          hint: 'Ichidan verbs: drop る, add させる.',
          note: 'Passive 食べられる (be eaten) vs causative 食べさせる (make or let eat). Two kana — さ・せ instead of ら・れ — and the villain changes!',
        },
        say('ume', 'あらあら 、 何[なん] の 騒[さわ]ぎ ？', 'Oh my, what’s all this fuss?',
          ['question-words:何の']),
        say('uozumi', '母[かあ]さん ！', 'Mum!'),
        {
          type: 'testimony', who: 'ume',
          title: 'ウメさんの証言[しょうげん]',
          titleEn: 'Granny Ume’s testimony',
          prompt: 'Granny Ume is honest but forgetful. Which statement clashes with the evidence?',
          lines: [
            line('八時[はちじ] すぎ に 、 クロ ちゃん が 遊[あそ]び>遊ぶ に 来[き]た>来る の>の(explain) よ 。', 'A little after eight, dear Kuro dropped by.',
              ['ni-iku-purpose:遊びに来た'],
              ['kuro', 'わたし>私 が 行[い]った>行く の は 本当[ほんとう] です 。 いわし 、 おいしかった>おいしい … 。', 'It’s true I went. That sardine was delicious…']),
            line('おなか>お腹 が すいて>すく いた>いる みたい だ から 、 いわし を 一匹[いっぴき] 食[た]べさせた>食べる の>の(explain) 。', 'He looked hungry, so I let him eat a sardine.',
              ['mitai:いたみたい', 'kara-reason:だから', 'causative:食べさせた', 'counters:一匹'],
              ['kuro', 'メモ と 合[あ]って>合う います>いる ね 。', 'That matches the memo.']),
            line('今日[きょう] は 朝[あさ] から とても 暑[あつ]かった>暑い わ ねえ 。', 'It’s been terribly hot since this morning, hasn’t it.',
              ['kara-from:朝から', 'i-adj-past:暑かった'],
              ['kuro', '暑[あつ]い 日[ひ] … 大事[だいじ] な こと かもしれません>かもしれない 。 でも 、 おかしく>おかしい は ありません>ある 。', 'A hot day… that might matter. But it isn’t wrong.']),
            line('鯛[たい] ？ 鯛[たい] なら 、 ずっと 店[みせ] の 前[まえ] に 置[お]いた>置く まま よ 。', 'The sea bream? Oh, I left it out front the whole time.',
              ['nara:鯛なら', 'mama:置いたまま']),
          ],
          wrong: 3,
          hint: 'Where does the trail of water lead?',
        },
        {
          type: 'ask', who: 'kuro',
          prompt: 'The trail of water leads to the fridge. Ask her gently: “Didn’t you put the sea bream in the fridge?” (fridge = 冷蔵庫 れいぞうこ, to put in = 入れる いれる)',
          answers: [
            '鯛[たい]を冷蔵庫[れいぞうこ]に入[い]れませんでしたか', '鯛[たい]は冷蔵庫[れいぞうこ]に入[い]れませんでしたか',
            '冷蔵庫[れいぞうこ]に鯛[たい]を入[い]れませんでしたか', '冷蔵庫[れいぞうこ]に入[い]れませんでしたか',
            '鯛[たい]を冷蔵庫[れいぞうこ]に入[い]れたんじゃないですか', '鯛[たい]を冷蔵庫[れいぞうこ]に入[い]れたのではありませんか',
            '鯛[たい]を冷蔵庫[れいぞうこ]に入[い]れたんじゃありませんか',
          ],
          line: '鯛[たい] を 冷蔵庫[れいぞうこ] に 入[い]れませんでした>入れる か ？',
          g: ['ni-destination:冷蔵庫に', 'masen-deshita:入れませんでした', 'ka-question:でしたか'],
          hint: '鯛を + 冷蔵庫に + 入れませんでしたか.',
          note: 'A negative question (〜ませんでしたか) is a soft, polite way to suggest something: “Didn’t you…?”',
        },
        say('ume', '… あら ！ そう だった>だ わ 。 暑[あつ]かった>暑い から 、 冷蔵庫[れいぞうこ] に 入[い]れて>入れる おいた>おく の>の(explain) よ 。', '…Oh my! So I did. It was so hot that I put it in the fridge to keep.',
          ['kara-reason:暑かったから', 'te-oku:入れておいた']),
        {
          type: 'fill', who: 'kuro',
          ja: '鯛[たい] が 悪[わる]く>悪い ならない>なる よう に 、 冷蔵庫[れいぞうこ] に 入[い]れて>入れる {_} ん です ね 。',
          fill: 'おいた>おく',
          g: ['ku-naru:悪くならない', 'you-ni:ならないように', 'te-oku:入れておいた'],
          en: 'So you put the sea bream in the fridge ahead of time, so it wouldn’t go off.',
          prompt: '“Do something in advance / for later” = て-form + おく. Here in the plain past: 入れて＿＿.',
          answers: ['おいた', '置[お]いた'],
          hint: 'おく in the past works like 書く → 書いた.',
          note: '〜ておく = do something in preparation. 〜ないように = “so that … doesn’t happen”. Both are N4–N3 favourites.',
        },
        narr('魚住[うおずみ] さん が 冷蔵庫[れいぞうこ] を 開[あ]ける と … 大[おお]きな 鯛[たい] が 、 ぴかぴか 光[ひか]って>光る いました>いる 。', 'Mr. Uozumi opens the fridge… and there lies the big sea bream, gleaming.',
          ['to-conditional:開けると', 'te-iru:光っていました']),
        say('uozumi', 'あったー>ある ！', 'There it is!'),
        say('kitsune', 'では 、 判決[はんけつ] を 言[い]い渡[わた]します>言い渡す 。 クロ 探偵[たんてい] は …', 'I shall now deliver the verdict. Detective Kuro is…',
          ['wo-object:判決を', 'wa-topic:クロ探偵は']),
        {
          type: 'fill', who: 'kitsune', accuse: true,
          ja: '{_} です わ 。',
          fill: '無罪[むざい]',
          g: ['desu:無罪です'],
          en: '…not guilty.',
          prompt: 'Deliver the verdict with her: “not guilty” — 無 (without) + 罪 (crime).',
          answers: ['無罪[むざい]'],
          hint: 'む・ざ・い.',
          note: '無罪 (むざい) not guilty ↔ 有罪 (ゆうざい) guilty. 無 means “without”, as in 無料 (むりょう, free of charge).',
        },
        narr('カチャッ 。 手錠[てじょう] が 外[はず]されました>外す 。', 'Click. The handcuffs come off.',
          ['passive:外されました']),
        say('gonta', 'クロ … すまん 。', 'K-Kuro… sorry.'),
        say('kuro', 'ゴンタ 刑事[けいじ] 。 「 すまん 」 で は 足[た]りません>足りる ね 。', 'Detective Gonta. “Sorry” won’t quite cut it.',
          ['masen:足りません']),
        {
          type: 'ask', who: 'kuro',
          prompt: 'Help Gonta apologise to Kuro in the humblest way: “I am truly sorry” (申し訳, もうしわけ). Past tense, since it’s about what he did.',
          answers: [
            '申[もう]し訳[わけ]ありませんでした', '申[もう]し訳[わけ]ございませんでした',
            '本当[ほんとう]に申[もう]し訳[わけ]ありませんでした', '本当[ほんとう]に申[もう]し訳[わけ]ございませんでした',
            '大変[たいへん]申[もう]し訳[わけ]ありませんでした', '大変[たいへん]申[もう]し訳[わけ]ございませんでした',
            '誠[まこと]に申[もう]し訳[わけ]ございませんでした', '申[もう]し訳[わけ]ありません', '申[もう]し訳[わけ]ございません',
          ],
          line: '申[もう]し訳[わけ] ありませんでした>ある 。',
          g: ['kenjougo:申し訳ありませんでした'],
          hint: 'もうしわけ + ありませんでした.',
          note: 'すまん → すみません → 申し訳ありません → 申し訳ございません: the same apology climbing the politeness ladder.',
        },
        say('gonta', '申[もう]し訳[わけ] ありませんでした>ある … ！', 'I-I am truly sorry…!',
          ['kenjougo:申し訳ありませんでした']),
        say('uozumi', 'クロ さん 、 おわび に 、 これ を どうぞ ！', 'Kuro, please take this to make up for it!',
          ['wo-object:これを']),
        narr('魚住[うおずみ] さん は 、 小[ちい]さな 鯛[たい] を クロ に わたしました>渡す 。', 'Mr. Uozumi hands Kuro a small sea bream.',
          ['wo-object:鯛を', 'masu-past:わたしました']),
        say('ume', 'ほら 、 今度[こんど] は 本当[ほんとう] に 「 クロ に 食[た]べさせた>食べる 」 わ ね 。', 'There — this time I really did “let Kuro eat”.',
          ['na-adverb:本当に', 'causative:食べさせた']),
        say('kuro', 'にゃるほど … 。 助手[じょしゅ] くん 、 きみ>君 は もう 立派[りっぱ] な 探偵[たんてい] です ね 。', 'Nyaruhodo… Assistant, you’re a fine detective now.',
          ['na-adj-noun:立派な探偵']),
        say('kuro', 'でも 、 明日[あした] の 祭[まつ]り で も 、 きっと 何[なに] か 起[お]こります>起こる よ 。', 'Mind you, I’m sure something will happen at tomorrow’s festival too.',
          ['de-event:祭りでも', 'question-words:何か']),
      ],
    },
  ];

  global.MYSTERY_CAST = CAST;
  global.MYSTERY_CHAPTERS = CHAPTERS;

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { CAST, CHAPTERS };
  }
})(typeof window !== 'undefined' ? window : globalThis);
