// Generated by scripts/generate_news_audio.py: one VOICEVOX recording per news
// story and level, the hash of the script it was recorded from (audioScript()
// in news.js), and when the headline and each sentence start and end (seconds).
(function (g) { g.NEWS_AUDIO = {
  "2026-10-10-beer:N3":{"hash":"652d13ac","src":"audio/news/2026-10-10-beer-N3.mp3","steps":[[5.01,12.55],[13.15,16.27],[16.87,24.76],[25.36,31.26],[31.86,36.6],[37.2,42.57],[43.17,47.41]],"title":[0.3,4.01]},
  "2026-10-10-beer:N4":{"hash":"885c5a54","src":"audio/news/2026-10-10-beer-N4.mp3","steps":[[4.36,9.03],[9.63,13.52],[14.12,18.18],[18.78,23.47],[24.07,28.56],[29.16,32.84],[33.44,37.04]],"title":[0.3,3.36]},
  "2026-10-10-beer:N5":{"hash":"568c409e","src":"audio/news/2026-10-10-beer-N5.mp3","steps":[[3.37,7.05],[7.65,11.55],[12.15,17.49],[18.09,21.83],[22.43,26.1],[26.7,29.64],[30.24,33.47]],"title":[0.3,2.37]},
  "2026-10-10-food-tax:N3":{"hash":"35f1f7de","src":"audio/news/2026-10-10-food-tax-N3.mp3","steps":[[6.09,12.75],[13.35,19.34],[19.94,23.83],[24.43,32.0],[32.6,38.05],[38.65,45.22]],"title":[0.3,5.09]},
  "2026-10-10-food-tax:N4":{"hash":"4d30abb3","src":"audio/news/2026-10-10-food-tax-N4.mp3","steps":[[5.08,7.09],[7.69,12.34],[12.94,18.49],[19.09,21.51],[22.11,30.27],[30.87,34.82]],"title":[0.3,4.08]},
  "2026-10-10-food-tax:N5":{"hash":"af02c4d8","src":"audio/news/2026-10-10-food-tax-N5.mp3","steps":[[3.8,7.34],[7.94,11.38],[11.98,16.09],[16.69,18.68],[19.28,21.96],[22.56,24.67]],"title":[0.3,2.8]},
  "2026-10-10-typhoons:N3":{"hash":"02d6f657","src":"audio/news/2026-10-10-typhoons-N3.mp3","steps":[[5.73,10.26],[10.86,15.8],[16.4,23.79],[24.39,29.03],[29.63,32.87],[33.47,36.84]],"title":[0.3,4.73]},
  "2026-10-10-typhoons:N4":{"hash":"2af39867","src":"audio/news/2026-10-10-typhoons-N4.mp3","steps":[[4.37,8.8],[9.4,13.43],[14.03,18.56],[19.16,22.72],[23.32,28.73],[29.33,34.64],[35.24,38.56]],"title":[0.3,3.37]},
  "2026-10-10-typhoons:N5":{"hash":"c8c2d148","src":"audio/news/2026-10-10-typhoons-N5.mp3","steps":[[3.0,7.34],[7.94,10.59],[11.19,13.81],[14.41,18.01],[18.61,21.69],[22.29,25.0],[25.6,28.86]],"title":[0.3,2.0]}}; })(typeof window !== 'undefined' ? window : globalThis);
