(function (global) {
  'use strict';

  // Per-sentence notes for the particle quiz: why the right particle fits
  // this sentence, and why each of the other choices doesn't. Every entry
  // is [why, ...wrong] where the wrong notes follow the order of that
  // particle's PARTICLE_DISTRACTOR_GROUPS in particles-data.js (the quiz
  // always offers exactly those three).
  const N = {
    // は — not が, も, の
    wa1: ['私 is the topic: “as for me, (I) am a student”. A self-introduction states a fact about someone already known.',
      '私が学生です answers “who is the student?” — “*I* am the student”. Nobody asked who.',
      '私も学生です means “I am a student too” — there’s no “too” in the English.',
      '私の学生です means “(it’s) my student” — 私 would own the student.'],
    wa2: ['これ is the topic you’re commenting on: “as for this, it’s my umbrella”.',
      'これが私の傘です picks this one out from others — “*this* is the one that’s mine”, as if answering “which is yours?”.',
      'これも私の傘です means “this is my umbrella too” — no “too” in the English.',
      'これの私の傘 isn’t a sentence; これ can’t own “my umbrella”.'],
    wa3: ['田中さん is the topic; the sentence tells you what he is.',
      '田中さんが先生です answers “who is the teacher?” — “*Mr. Tanaka* is the teacher”.',
      '田中さんも先生です means “Mr. Tanaka is also a teacher” — no “also” in the English.',
      '田中さんの先生です means “(it’s) Mr. Tanaka’s teacher” — a different person.'],
    wa4: ['今日 is the topic: “as for today, it’s sunny”. Time words like 今日 take は (or nothing), not が.',
      '今日が晴れです means “*today* (of all days) is the sunny one” — contrastive, not a plain weather report.',
      '今日も晴れです means “today is sunny too” — no “too” in the English.',
      '今日の晴れ is “today’s sunny weather” — a noun phrase, not a statement.'],
    wa5: ['日本語 is the topic; 難しい describes it.',
      '日本語が難しいです means “it’s *Japanese* that’s difficult” — singling it out from other things.',
      '日本語も難しいです means “Japanese is difficult too”.',
      '日本語の難しい… is “Japanese’s difficult …” and would need a noun after it.'],
    wa6: ['この本 is the topic; 面白い describes it.',
      'この本が面白いです means “*this* book (not the others) is interesting”.',
      'この本も面白いです means “this book is interesting too”.',
      'この本の面白い… is “this book’s interesting …” and needs a noun after it.'],
    wa7: ['山田さん is the topic; アメリカ人です gives his nationality.',
      '山田さんがアメリカ人です answers “who is American?” — “*Mr. Yamada* is”.',
      '山田さんもアメリカ人です means “Mr. Yamada is American too”.',
      '山田さんのアメリカ人 is “Mr. Yamada’s American” — nonsense.'],
    wa8: ['東京 is the topic; the sentence says what it is.',
      '東京が日本の首都です answers “which city is the capital?” — focus on Tokyo.',
      '東京も日本の首都です means “Tokyo is also the capital” — there’s only one.',
      '東京の日本の首都 is “Tokyo’s capital of Japan” — nonsense.'],
    wa9: ['私の誕生日 is the topic; 九月です gives the month.',
      '私の誕生日が九月です means “it’s *my* birthday that’s in September” — contrastive.',
      '私の誕生日も九月です means “my birthday is in September too”.',
      '私の誕生日の九月 is “the September of my birthday” — a noun phrase, not the statement.'],
    wa10: ['この魚 is the topic; 新鮮 describes it.',
      'この魚が新鮮です means “*this* fish (rather than the others) is the fresh one”.',
      'この魚も新鮮です means “this fish is fresh too”.',
      'この魚の新鮮… is “this fish’s fresh …” and leaves the sentence without a predicate.'],
    wa11: ['兄 is the topic; 医者です states his job.',
      '兄が医者です answers “who is the doctor?” — “my *brother* is”.',
      '兄も医者です means “my brother is a doctor too”.',
      '兄の医者 is “my brother’s doctor” — a different person.'],
    wa12: ['あの猫 is the topic; 白い describes it.',
      'あの猫が白いです means “*that* cat is the white one”.',
      'あの猫も白いです means “that cat is white too”.',
      'あの猫の白い… is “that cat’s white …” and needs a noun after it.'],
    wa13: ['この店 is the topic; the rest says when it closes.',
      'この店が八時に閉まります stresses “*this* shop (not another) closes at eight”.',
      'この店も八時に閉まります means “this shop also closes at eight”.',
      'この店の八時 is “this shop’s eight o’clock” — garbled.'],
    wa14: ['田中さんの犬 is the topic; 大きい describes it.',
      '田中さんの犬が大きいです means “it’s *Mr. Tanaka’s dog* that’s big”.',
      '田中さんの犬も大きいです means “Mr. Tanaka’s dog is big too”.',
      'Another の just keeps chaining nouns (“the dog’s big …”) and leaves no predicate.'],
    wa15: ['明日 is the topic: “as for tomorrow, I’m busy”. Time words take は, not が.',
      '明日が忙しいです means “*tomorrow* is the day I’m busy” — contrastive.',
      '明日も忙しいです means “tomorrow I’m busy too”.',
      '明日の忙しい… is “tomorrow’s busy …” and needs a noun after it.'],
    wa16: ['冬 is the topic of a general statement about winter.',
      '冬が寒いです answers “which season is cold?” — focus on winter.',
      '冬も寒いです means “winter is cold too”.',
      '冬の寒い… is “winter’s cold …” and needs a noun after it.'],
    wa17: ['このレストラン is the topic; 有名 describes it.',
      'このレストランが有名です means “*this* restaurant is the famous one”.',
      'このレストランも有名です means “this restaurant is famous too”.',
      'このレストランの有名… leaves the sentence without a predicate.'],
    wa18: ['山田さんの部屋 is the topic; 綺麗 describes it.',
      '山田さんの部屋が綺麗です means “it’s *his room* that’s clean” — contrastive.',
      '山田さんの部屋も綺麗です means “his room is clean too”.',
      'Another の chains a noun to 綺麗 and leaves no predicate.'],
    wa19: ['私の趣味 is the topic; 読書です says what it is.',
      '私の趣味が読書です answers “whose hobby is reading?” — the wrong focus.',
      '私の趣味も読書です means “my hobby is reading too”.',
      '私の趣味の読書 is “the reading that is my hobby” — a noun phrase, not a statement.'],
    wa20: ['あの映画 is the topic; you comment on it.',
      'あの映画が面白かったです means “*that* movie was the interesting one”.',
      'あの映画も面白かったです means “that movie was interesting too”.',
      'あの映画の面白かった… needs a noun after it.'],

    // が — not は, を, の
    ga1: ['Question words like 誰 take が: they mark the unknown, new information.',
      '誰は is wrong — a question word can’t be the topic, because a topic must already be known.',
      '来る has no object, so を has nothing to mark.',
      '誰の means “whose” and needs a noun after it.'],
    ga2: ['With いる/ある, the thing that exists takes が: “there is a cat”.',
      '猫はいます talks about a cat already known (“the cat, it’s here”) instead of announcing one.',
      'いる has no object, so を can’t be used.',
      '猫のいます isn’t grammatical; の needs a noun after it.'],
    ga3: ['見える (“be visible”) marks what can be seen with が.',
      '星は見えます is contrastive: “stars, at least, are visible”.',
      '見える has no object. 星を見ます would need the verb 見る (“look at”).',
      '星の見えます isn’t a sentence.'],
    ga4: ['わかる marks the thing understood with が.',
      '日本語はわかります is contrastive: “Japanese I understand (other languages, not so much)”.',
      'わかる never takes を — a very common mistake.',
      '日本語のわかります isn’t a sentence.'],
    ga5: ['“X は Y が ある” is how you say X has Y — the thing owned takes が.',
      'A second は makes the car contrastive: “a car he has (but not …)”.',
      'ある has no object; 車をあります is wrong.',
      '車のあります isn’t a sentence.'],
    ga6: ['With 痛い, the body part that hurts takes が.',
      '頭は痛いです is contrastive: “my head, at least, hurts”.',
      '痛い is an adjective; adjectives don’t take objects.',
      '頭の痛い… is a modifier and needs a noun after it.'],
    ga7: ['The people who exist with います take が; the count follows directly.',
      '学生は二十人います comments on students already known, rather than reporting who’s there.',
      'いる has no object.',
      '学生の二十人 is “the twenty of the students” and leaves います without a subject.'],
    ga8: ['The thing that exists with あります takes が.',
      '卵はありますか is contrastive, e.g. right after asking about milk: “and eggs?”.',
      'ある has no object.',
      '卵のありますか isn’t grammatical.'],
    ga9: ['できる marks the skill you can do with が.',
      'A second は makes tennis contrastive: “tennis I can play (other sports maybe not)”.',
      'できる takes が, not を: テニスをします but テニスができます.',
      'テニスのできます isn’t a sentence.'],
    ga10: ['上手 (“good at”) marks the skill with が.',
      'ピアノは上手です is contrastive: “piano, he’s good at (unlike other things)”.',
      '上手 is a na-adjective; adjectives don’t take objects.',
      'ピアノの上手… needs a noun after it.'],
    ga11: ['苦手 (“bad at”) marks the weak spot with が.',
      '数学は苦手です is contrastive: “math, in particular, I’m bad at”.',
      '苦手 is a na-adjective; no を.',
      '数学の苦手… needs a noun after it.'],
    ga12: ['With 痛い, the body part that hurts takes が.',
      '喉は痛いです is contrastive: “my throat, at least, hurts”.',
      '痛い is an adjective; no を.',
      '喉の痛い… needs a noun after it.'],
    ga13: ['The thing you have (or don’t) with ある takes が.',
      'お金はありません is heard too, but it contrasts money with other things; the plain “I have no money” uses が.',
      'ある has no object.',
      'お金のありません isn’t a sentence.'],
    ga14: ['好き marks what you like with が.',
      'この歌は好きです is contrastive: “this song (unlike the others) I like”.',
      '好き is an adjective, so を is wrong — a very common mistake.',
      'この歌の好き… needs a noun after it.'],
    ga15: ['誰 asks for the doer, and question words take が.',
      '誰は is wrong — a question word can’t be the topic.',
      'ドア already has を; 誰 is the one opening, not the thing opened.',
      '誰のドアを開けましたか is grammatical, but means “whose door did you open?”, not “who opened the door?”.'],
    ga16: ['欲しい marks the thing wanted with が, and question words take が anyway.',
      '何は is wrong — a question word can’t be the topic.',
      '欲しい is an adjective; it doesn’t take を.',
      '何の means “what kind of” and needs a noun after it.'],
    ga17: ['The thing that exists with います takes が: “there is a cat”.',
      '猫はいます would talk about a cat already known, not announce one under the tree.',
      'いる has no object.',
      '猫のいます isn’t grammatical.'],
    ga18: ['Reporting weather you see happening (rain falling) uses が — it’s new information.',
      '雨は降っています is contrastive: “rain, at least, is falling”.',
      '降る has no object; the rain is what’s falling.',
      '雨の降って… doesn’t form a sentence here.'],
    ga19: ['In 頭がいい (“smart”, literally “head is good”), the described part takes が.',
      '頭はいいですね implies “your head is good (but something else isn’t)”.',
      'いい is an adjective; no を.',
      '頭のいい… means “a smart …” and needs a noun after it.'],
    ga20: ['Describing a feature of a person — (彼女は)目が大きい — the feature takes が.',
      '目は大きいです is contrastive: “her eyes (unlike other features) are big”.',
      '大きい is an adjective; no を.',
      '目の大きい… means “big-eyed …” and needs a noun after it.'],

    // を — not が, に, で
    wo1: ['パン is the thing eaten — the direct object of 食べる.',
      'パンが食べます would make the bread the one eating.',
      'に marks a target or a place, not what you eat.',
      'パンで食べます means “eat using bread”, not “eat bread”.'],
    wo2: ['手紙 is what you write — the direct object of 書く.',
      '手紙が書きます would make the letter the writer.',
      '手紙に書きます means “write (something) in the letter” — a different meaning.',
      '手紙で means “by letter” — the means, so nothing is being written.'],
    wo3: ['音楽 is what you listen to — the direct object of 聞く.',
      '音楽が聞きます makes the music the listener. (音楽が聞こえます would need a different verb.)',
      '聞く doesn’t mark what you listen to with に.',
      '音楽で means “by means of music”.'],
    wo4: ['テレビ is what you watch — the direct object of 見る.',
      'テレビが見ます would make the TV the watcher.',
      'テレビに means “on the TV” (e.g. appearing on TV), not watching it.',
      'テレビで見ます means “see (it) on TV” — the medium; then what you watched is missing.'],
    wo5: ['新聞 is what you read — the direct object of 読む.',
      '新聞が読みます would make the newspaper the reader.',
      '新聞に means “in the newspaper” (e.g. written in it).',
      '新聞で means “through the newspaper” — the means, not what you read.'],
    wo6: ['With 出る (“leave”), を marks the place you leave.',
      '家が出ます would make the house the one leaving.',
      'に marks where you come out to (外に出る), not the place you leave.',
      'で marks where an action happens, not the place you leave.'],
    wo7: ['コーヒー is what you drink — the direct object of 飲む.',
      'コーヒーが飲みます would make the coffee the drinker.',
      '飲む doesn’t mark what you drink with に.',
      'コーヒーで means “using coffee”.'],
    wo8: ['宿題 is what you do — the object of する.',
      '宿題がします would make the homework the doer.',
      '宿題にします means “I’ll decide on homework / make it homework” — a different construction.',
      '宿題で means “by means of homework”.'],
    wo9: ['花 is what you buy — the direct object of 買う.',
      '花が買います would make the flowers the buyer.',
      '花に means “for the flowers” — a target, not the thing bought.',
      '花で means “with flowers” as a means of payment.'],
    wo10: ['車 is what you wash — the direct object of 洗う.',
      '車が洗います would make the car the washer.',
      'There’s no target here for に to mark.',
      '車で洗います means “wash (something) by car / in the car”.'],
    wo11: ['閉める is transitive: you close the door, so the door takes を.',
      'ドアが would need the intransitive 閉まる (“the door closes”), not 閉めます.',
      'There’s no target here for に to mark.',
      'ドアで means “using the door”.'],
    wo12: ['消す is transitive: you turn the light off, so the light takes を.',
      '電気が would need the intransitive 消える (“the light goes off”), not 消します.',
      'There’s no target here for に to mark.',
      '電気で means “using electricity”.'],
    wo13: ['靴 is what you take off — the direct object of 脱ぐ.',
      '靴が脱ぎます would make the shoes the actor.',
      'に would mark a place, not the item taken off.',
      '靴で means “using shoes”.'],
    wo14: ['部屋 is what you clean — the object of 掃除する.',
      '部屋が掃除します would make the room the cleaner.',
      'There’s no target here for に to mark.',
      '部屋で掃除します means “clean (something) in the room” — where, not what. The English says you clean the room itself.'],
    wo15: ['待つ takes the person waited for as its direct object: 友達を待つ.',
      '友達が待ちます would make your friend the one waiting.',
      'English “wait for” tempts に, but 待つ uses を.',
      '友達で means “by means of my friend”.'],
    wo16: ['With motion verbs like 渡る, を marks the space you move across.',
      '橋が渡ります would make the bridge the one crossing.',
      '橋に渡ります would treat the bridge as a destination, not something you cross.',
      'で marks where an action happens, not the route you cross.'],
    wo17: ['歯 is what you brush — the direct object of 磨く.',
      '歯が磨きます would make the teeth the brusher.',
      'There’s no target here for に to mark.',
      '歯で means “using teeth”.'],
    wo18: ['服 is what you wash — the object of 洗濯する.',
      '服が洗濯します would make the clothes the doer.',
      'There’s no target here for に to mark.',
      '服で means “using clothes”.'],
    wo19: ['傘 is what you forgot — the direct object of 忘れる.',
      '傘が忘れました would make the umbrella the one who forgot.',
      'に marks where you left something (電車に傘を忘れた), not the thing forgotten.',
      '傘で means “using an umbrella”.'],
    wo20: ['手紙 is what you sent — the direct object of 送る.',
      '手紙が送りました would make the letter the sender.',
      'に marks the receiver (友達に送る), not the thing sent.',
      '手紙で送りました means “sent (it) by letter” — the method; then what was sent is missing.'],

    // に — not で, へ, と
    ni1: ['A specific clock time takes に: 七時に.',
      'で doesn’t mark points in time.',
      'へ marks direction of travel — a time isn’t a place you go.',
      '七時と means “with seven o’clock” — nonsense.'],
    ni2: ['The place where something exists (ある/いる) takes に.',
      'で marks where an action happens; existence with ある uses に.',
      'Nothing is moving here, so へ doesn’t fit.',
      '机の上と means “with the top of the desk”.'],
    ni3: ['The person you call is the target of 電話をかける, marked with に.',
      '友達で means “by means of my friend”.',
      'へ marks destinations of travel; for the person you call, use に.',
      '友達と電話をかけます means calling together with your friend, not calling them.'],
    ni4: ['なる marks what something becomes with に: 先生になる.',
      'で doesn’t mark the result of a change.',
      'へ is physical direction, not becoming something.',
      '先生となる exists in formal writing, but everyday Japanese says 先生になる.'],
    ni5: ['八時 is a specific clock time, so it takes に.',
      'で doesn’t mark points in time.',
      'へ marks direction of travel, not time.',
      '八時と means “with eight o’clock”.'],
    ni6: ['に marks the occasion: on/for your birthday.',
      'で doesn’t mark the occasion something happens on.',
      'Nothing is moving toward the birthday, so へ doesn’t fit.',
      '誕生日と means “together with my birthday”.'],
    ni7: ['九時 is a specific clock time, so it takes に.',
      'で doesn’t mark points in time.',
      'へ marks direction of travel, not time.',
      '九時と means “with nine o’clock”.'],
    ni8: ['The place where something exists (ある) takes に.',
      'で marks where an action happens; existence uses に.',
      'Nothing is moving, so へ doesn’t fit.',
      '本棚と means “with the bookshelf”.'],
    ni9: ['The person you ask is the target of 質問する, marked with に.',
      '先生で means “by means of the teacher”.',
      'へ marks destinations of travel, not the person you ask.',
      '先生と質問をします means asking a question together with the teacher.'],
    ni10: ['With あげる, the receiver takes に.',
      '母で means “by means of my mother”.',
      '母へ appears on gift cards (“To Mom”), but with あげる the receiver takes に.',
      '母と花をあげました means you gave flowers together with your mother.'],
    ni11: ['With もらう, に marks the person you received something from.',
      '山田さんで means “by means of Mr. Yamada”.',
      'へ points toward a destination, but Mr. Yamada is the source.',
      '山田さんと means you received the letter together with Mr. Yamada.'],
    ni12: ['The person you teach is the target of 教える, marked with に.',
      '弟で means “by means of my brother”.',
      'Nothing is traveling here, so へ doesn’t fit.',
      '弟と日本語を教えます means you teach Japanese together with your brother.'],
    ni13: ['乗る marks the vehicle you get on with に.',
      'バスで means “by bus”, which works with 行く but not with 乗る.',
      'へ would make the bus a destination you travel to.',
      'バスと means “together with the bus”.'],
    ni14: ['六時 is a specific clock time, so it takes に.',
      'で doesn’t mark points in time.',
      'へ marks direction of travel, not time.',
      '六時と means “with six o’clock”.'],
    ni15: ['週末 is a point on the calendar and takes に. (Relative words like 今日 or 明日 take nothing.)',
      'で doesn’t mark points in time.',
      'へ marks direction of travel, not time.',
      '週末と means “with the weekend”.'],
    ni16: ['The party you call is the target of 電話する, marked with に.',
      '会社で電話をします means “make a call at the office” — where, not who you call.',
      'へ marks destinations of travel; for the party you call, use に.',
      '会社と電話 means calling together with the company.'],
    ni17: ['座る marks the spot you sit down on with に.',
      'で marks where an activity goes on, but 座る is about landing on a spot, which uses に.',
      'へ marks the direction of travel; no one is going anywhere.',
      '椅子と means “together with the chair”.'],
    ni18: ['住む always marks where you live with に.',
      '京都で住んでいます is a classic mistake — living feels like an activity, but 住む takes に.',
      'Nothing is moving, so へ doesn’t fit.',
      '京都と means “together with Kyoto”.'],
    ni19: ['三月 is a specific month, so it takes に.',
      'で doesn’t mark points in time.',
      '日本 already has へ as the destination; a month isn’t a place you go.',
      '三月と means “with March”.'],
    ni20: ['に marks the occasion: for your birthday.',
      'で doesn’t mark the occasion.',
      'Nothing is moving toward the birthday, so へ doesn’t fit.',
      '誕生日と means “together with your birthday”.'],

    // で — not に, へ, と
    de1: ['勉強する is an action, and で marks where an action takes place.',
      'に marks where something exists or ends up; 図書館に勉強します is wrong.',
      'へ would make the library a destination you travel toward.',
      '図書館と means “together with the library”.'],
    de2: ['で marks the means of transport: by bus.',
      '学校に already marks the destination; バスに行きます would mean “go to the bus”.',
      'バスへ行きます would mean “head toward the bus”.',
      'バスと means “together with the bus”, as if it were a companion.'],
    de3: ['で marks the language you use — a means.',
      'Japanese isn’t a target here, so に doesn’t fit.',
      'Nothing is moving, so へ doesn’t fit.',
      '日本語と話します means “talk with Japanese”, as if it were a person.'],
    de4: ['で can mark a cause: absent because of illness.',
      '病気に doesn’t mark a cause here.',
      'Nothing is moving, so へ doesn’t fit.',
      '病気と means “together with illness”.'],
    de5: ['With a number of people, で means “as a group of”: the three of us made it.',
      'に doesn’t mark who did something.',
      'Nothing is moving, so へ doesn’t fit.',
      '三人と means “with three (other) people” — then there were four of you.'],
    de6: ['で marks the tool you use: with a pen.',
      'ペンに名前を書きます means “write my name on the pen”.',
      'Nothing is moving, so へ doesn’t fit.',
      'ペンと means “together with a pen”, as if it were a companion.'],
    de7: ['働く is an action; where you do it takes で.',
      '会社に勤めています uses に, but 働く takes で — a common mix-up.',
      'へ would make the company a destination you travel toward.',
      '会社と働いています means “working together with the company” (as a partner).'],
    de8: ['遊ぶ is an action; where you do it takes で.',
      '公園に is for going there (公園に行く); playing in it takes で.',
      'へ would make the park a destination, not where you play.',
      '公園と means “together with the park”.'],
    de9: ['で marks the means of transport: by bicycle.',
      '自転車に would mean getting on the bike (with 乗る), not traveling by it.',
      '駅まで already says where you go; 自転車へ would make the bike a destination.',
      '自転車と means “together with the bicycle”.'],
    de10: ['で marks the language you use: in English.',
      'English isn’t a target here, so に doesn’t fit.',
      'Nothing is moving, so へ doesn’t fit.',
      '英語と話してください means “please talk with English”, as if it were a person.'],
    de11: ['で can mark a cause: the trains stopped because of the typhoon.',
      '台風に doesn’t mark the cause here.',
      'Nothing is moving toward the typhoon, so へ doesn’t fit.',
      '台風と means “together with the typhoon”.'],
    de12: ['で marks the tool you use: with scissors.',
      'はさみに means “to/on the scissors”.',
      'Nothing is moving, so へ doesn’t fit.',
      'はさみと means “together with scissors”.'],
    de13: ['With a length of time, で means “within / in (the space of)”: done in 30 minutes.',
      '三十分に would be a clock time (“at half past”), not a duration.',
      'A length of time isn’t a direction, so へ doesn’t fit.',
      '三十分と means “with thirty minutes”.'],
    de14: ['食べる is an action; where you do it takes で.',
      '家に is where you are or go to; eating there takes で.',
      'へ would make home a destination you travel toward.',
      '家と means “together with the house”.'],
    de15: ['借りる is an action; where it happens takes で.',
      '図書館に would mark the library as a destination or target, not where you borrowed it.',
      'へ would make the library a destination you travel toward.',
      '図書館と means “together with the library”.'],
    de16: ['で can mark a cause: destroyed in (because of) the earthquake.',
      '地震に doesn’t mark the cause here.',
      'Nothing is moving, so へ doesn’t fit.',
      '地震と means “together with the earthquake”.'],
    de17: ['で marks the scope of a total: “all together it’s ¥3000”.',
      '全部に doesn’t express a total.',
      'Nothing is moving, so へ doesn’t fit.',
      '全部と means “with everything”.'],
    de18: ['With a number of people, で means “as a group of”: the two of us went.',
      'に doesn’t mark who did something.',
      'カラオケに already marks the destination; 二人へ would make the two people one.',
      '二人と means “with two (other) people” — then there were three of you.'],
    de19: ['会議をする is an action; where it happens takes で.',
      '会議室に is where something is or goes, not where an activity takes place.',
      'へ would make the room a destination you travel toward.',
      '会議室と means “together with the meeting room”.'],
    de20: ['で marks the tool you use: with my smartphone.',
      'スマホに would mark where something ends up (e.g. saved to the phone), not the tool.',
      'Nothing is moving, so へ doesn’t fit.',
      'スマホと means “together with my smartphone”.'],

    // へ — not で, と, も
    e1: ['へ marks the direction/destination of 行く: to Tokyo. (に also works.)',
      '東京で marks where an action happens (“at Tokyo”), not where you’re going.',
      '東京と means “together with Tokyo”.',
      '東京も行きます means “I’ll go to Tokyo too” — no “too” in the English.'],
    e2: ['へ marks where 帰る takes him: back to America. (に also works.)',
      'アメリカで marks where an action happens, not the destination.',
      'アメリカと means “together with America”.',
      'アメリカも帰ります means “he’ll return to America too”.'],
    e3: ['へ marks the direction the birds fly: toward the south.',
      '南で飛んで行きます means they fly off while in the south — location, not direction.',
      '南と means “together with the south”.',
      '南も means “the south too”.'],
    e4: ['向かう (“head toward”) is the classic へ verb — it’s all about direction.',
      '駅で向かいました means “headed off at the station” — location, not where you headed.',
      '駅と means “together with the station”.',
      '駅も向かいました means “headed to the station too”.'],
    e5: ['へ marks the direction the train moves: toward Osaka.',
      '大阪で進みます would mean it advances while in Osaka.',
      '大阪と means “together with Osaka”.',
      '大阪も means “Osaka too”.'],
    e6: ['へ marks the destination of the trip: to Kyoto. (に also works.)',
      '京都で旅行に行きます garbles it — で marks an action’s location, not a destination.',
      '京都と means “together with Kyoto”.',
      '京都も means “to Kyoto too”.'],
    e7: ['へ marks the destination of 行く: to the sea.',
      '海で行きます would mean “go, at the sea” — location, not destination.',
      '海と means “together with the sea”.',
      '海も行きます means “I’ll go to the sea too”.'],
    e8: ['へ marks the destination: to Hokkaido. 飛行機で already marks the means.',
      '北海道で would mark Hokkaido as where an action happens, not where you go.',
      '北海道と means “together with Hokkaido”.',
      '北海道も means “to Hokkaido too”.'],
    e9: ['へ marks where he’s moving to: Osaka. (に also works.)',
      '大阪で引っ越します would mean the move happens within Osaka.',
      '大阪と means “together with Osaka”.',
      '大阪も means “to Osaka too”.'],
    e10: ['向かう (“head toward”) takes へ for its direction.',
      '駅で向かっています means it’s heading somewhere while at the station.',
      '駅と means “together with the station”.',
      '駅も means “to the station too”.'],
    e11: ['へ marks where 戻る takes you: back to school. (に also works.)',
      '学校で戻りました means you came back while at school — location, not destination.',
      '学校と means “together with the school”.',
      '学校も means “back to school too”.'],
    e12: ['へ marks where the children ran to: the park.',
      '公園で走って行きました means they ran off from inside the park — location, not destination.',
      '公園と means “together with the park”.',
      '公園も means “to the park too”.'],
    e13: ['へ marks the direction of movement: north.',
      '北で進んでいます means it moves while in the north.',
      '北と means “together with the north”.',
      '北も means “north too”.'],
    e14: ['へ marks the direction the road leads: “to where?”.',
      'どこで続いていますか asks where the road continues, not where it leads.',
      'どこと means “with where” — nonsense.',
      'どこも means “everywhere”, which changes the question completely.'],
    e15: ['へ marks the place you commute to: the company. (に also works.)',
      '会社で通っています would mean commuting while at the company.',
      '会社と means “together with the company”.',
      '会社も means “to the company too”.'],
    e16: ['へ marks the destination of departure: (he left) for London.',
      'ロンドンで出発しました would mean he set off while in London. (To leave London itself: ロンドンを出発.)',
      'ロンドンと means “together with London”.',
      'ロンドンも means “for London too”.'],
    e17: ['へ marks where you climbed to: the top of the mountain. (に also works.)',
      '山の上で登りました would mean you climbed while already on top.',
      '山の上と means “together with the mountaintop”.',
      '山の上も means “to the top too”.'],
    e18: ['へ marks where the package goes: to America.',
      'アメリカで送ります means “send (it) from America” — where the sending happens.',
      'アメリカと means “together with America”.',
      'アメリカも means “to America too”.'],
    e19: ['へ marks where the cat moved to: under the chair. (に also works.)',
      '椅子の下で隠れました puts the cat already under the chair, not moving there.',
      '椅子の下と means “together with the space under the chair”.',
      '椅子の下も means “under the chair too”.'],
    e20: ['向かう (“head toward”) takes へ for its direction.',
      '図書館で向かいます means heading off while at the library.',
      '図書館と means “together with the library”.',
      '図書館も means “to the library too”.'],

    // と — not や, に, も
    to1: ['と marks the person you do something with: with my friend.',
      'や lists things non-exhaustively (“friends and such”) and needs another item after it.',
      '見る has no target, so 友達に doesn’t fit.',
      '友達も映画を見ました means “my friend also watched a movie” — the friend becomes the watcher.'],
    to2: ['と lists a complete set: bread and eggs, exactly those.',
      'パンや卵 means “things like bread and eggs” — grammatical, but the English lists exactly two foods.',
      'パンに卵 means “eggs to go with bread” — a combination, not a plain list.',
      'パンも卵を食べます is broken; も would have to replace を.'],
    to3: ['と marks who she lives with: her older sister.',
      'や lists things non-exhaustively and needs another item after it.',
      'お姉さんに住んでいます would mean living in her sister — に marks where you live.',
      'お姉さんも住んでいます means “her sister lives (there) too” — a different subject.'],
    to4: ['と marks who you played with: your younger brother.',
      'や lists things non-exhaustively and needs another item after it.',
      'テニスをする has no target, so 弟に doesn’t fit.',
      '弟もテニスをしました means “my brother also played tennis”.'],
    to5: ['同じ compares two things: “A と B は同じ” — a complete pair.',
      'これやそれ means “this, that and so on” — 同じ needs an exact pair.',
      'に doesn’t link two nouns as “and”.',
      'これもそれは is broken; “both” would be これもそれも.'],
    to6: ['と marks who you did it with; 一緒に (“together”) is a strong hint for と.',
      'や lists things non-exhaustively and needs another item after it.',
      '母に一緒に doesn’t work — 一緒に goes with と.',
      '母も一緒に料理をしました means “my mother cooked with (us) too” — she becomes an extra cook.'],
    to7: ['と marks who you played with: your younger brother.',
      'や lists things non-exhaustively and needs another item after it.',
      'ゲームをする has no target, so 弟に doesn’t fit.',
      '弟もゲームをしました means “my brother also played a game”.'],
    to8: ['と marks who you went with: your older sister.',
      'や lists things non-exhaustively and needs another item after it.',
      '姉に would make your sister a target; going shopping has none.',
      '姉も買い物に行きました means “my sister went shopping too”.'],
    to9: ['と marks who you talked with: a two-way conversation with the teacher.',
      'や lists things non-exhaustively and needs another item after it.',
      '先生に話しました is grammatical, but means “I told the teacher” — one-way, not talking with them.',
      '先生も話しました means “the teacher talked too”.'],
    to10: ['結婚する takes と for the partner — you marry *with* someone.',
      'や lists things non-exhaustively and needs another item after it.',
      'English “married to” tempts に, but 結婚する uses と.',
      '日本人も結婚しました garbles it into “a Japanese person also married”.'],
    to11: ['と marks the other side of a two-way action: fighting with your brother.',
      'や lists things non-exhaustively and needs another item after it.',
      '兄に喧嘩しました isn’t how it’s said; a fight needs a partner, marked by と.',
      '兄も喧嘩しました means “my brother also had a fight”.'],
    to12: ['と lists a complete set: an apple and a banana, exactly those.',
      'りんごやバナナ means “things like apples and bananas” — the English lists exactly two.',
      'りんごにバナナ means “bananas to go with apples” — a combination, not a plain list.',
      'りんごもバナナを is broken; も would have to replace を.'],
    to13: ['と joins exactly two people: Mr. Tanaka and Mr. Yamada.',
      '田中さんや山田さん implies there are others too — the English names just the two.',
      'に doesn’t link two nouns as “and”.',
      '田中さんも山田さんは is broken; “both” would be 田中さんも山田さんも.'],
    to14: ['と marks who you played with: your child.',
      'や lists things non-exhaustively and needs another item after it.',
      '遊ぶ has no target, so 子供に doesn’t fit.',
      '子供も公園で遊びました means “my child also played at the park”.'],
    to15: ['違う compares two things: “A と B は違う” — a complete pair.',
      'これやあれ means “this, that and so on” — 違う needs an exact pair.',
      'に doesn’t link two nouns as “and”.',
      'これもあれは is broken.'],
    to16: ['と lists a complete set: a dog and a cat, exactly those.',
      '犬や猫 means “animals like dogs and cats” — the English says just a dog and a cat.',
      'に doesn’t link two nouns as “and”.',
      '犬も猫を is broken; も would have to replace を.'],
    to17: ['と marks who you went with: your friend.',
      'や lists things non-exhaustively and needs another item after it.',
      '映画館に already marks the destination; 友達に would make your friend a second one.',
      '友達も映画館に行きました means “my friend went to the theater too”.'],
    to18: ['と marks who you were with: a photo together with your father.',
      'や lists things non-exhaustively and needs another item after it.',
      '父に写真を撮りました isn’t natural; for “he took it for me” you’d say 父に撮ってもらいました.',
      '父も写真を撮りました means “my father took photos too”.'],
    to19: ['と marks who he traveled with: his colleague.',
      'や lists things non-exhaustively and needs another item after it.',
      '出張する has no target, so 同僚に doesn’t fit.',
      '同僚も出張しました means “his colleague also went on a business trip”.'],
    to20: ['と marks who you talked with: a two-way conversation with your friend.',
      'や lists things non-exhaustively and needs another item after it.',
      '友達に話しました means “I told my friend” — one-way, not talking with them.',
      '友達も電話で話しました means “my friend also talked on the phone”.'],

    // も — not は, が, と
    mo1: ['も adds 山田さん to a set: “Mr. Yamada is *also* a student”.',
      '山田さんは学生です is grammatical but drops the “also”.',
      '山田さんが学生です means “*Mr. Yamada* is the student” — focus, not “also”.',
      '山田さんと学生です means “it’s Mr. Yamada and a student”.'],
    mo2: ['も replaces が on the thing liked: “I like apples *too*”.',
      'りんごは好きです is contrastive (“apples I like”) and has no “too”.',
      'りんごが好きです is the plain “I like apples” — no “too”.',
      'りんごと好きです is broken; と would need another noun after it.'],
    mo3: ['も adds これ to a set: “this one is good *too*”.',
      'これはいいですね is grammatical but drops the “too”.',
      'これがいいですね means “*this* one is the good one” — picking it, not adding it.',
      'これと means “with this”, and leaves the sentence without a subject.'],
    mo4: ['も adds 田中さん to the guests: “Mr. Tanaka is *also* coming”.',
      '田中さんはパーティーに来ます drops the “also”.',
      '田中さんが来ます stresses that *he* is the one coming — no “also”.',
      '田中さんとパーティーに来ます means “(someone) comes to the party with Mr. Tanaka”.'],
    mo5: ['も adds 弟 to the learners: “my brother is *also* studying”.',
      '弟は日本語を勉強しています drops the “also”.',
      '弟が勉強しています stresses that *he* is the one studying — no “also”.',
      '弟と日本語を勉強しています means “(I) study Japanese with my brother”.'],
    mo6: ['も adds 今日 to other rainy days: “today is rainy *too*”.',
      '今日は雨です is grammatical but drops the “too”.',
      '今日が雨です means “*today* is the rainy one” — focus, not “too”.',
      '今日と means “with today” — nonsense here.'],
    mo7: ['も adds 私 to the people going: “I’ll go *too*”.',
      '私は行きます drops the “too” (and sounds contrastive).',
      '私が行きます means “*I*’ll be the one to go” — volunteering, not “too”.',
      '私と行きます means “(someone) goes with me”.'],
    mo8: ['も replaces が on the thing liked: “I like this one *too*”.',
      'これは好きです is contrastive (“this one I like”) — no “too”.',
      'これが好きです is the plain “I like this one” — no “too”.',
      'これと好きです is broken; と needs another noun after it.'],
    mo9: ['も adds 妹 to those who are good at Japanese: “my sister *too*”.',
      '妹は日本語が上手です drops the “also”.',
      '妹が上手です means “*my sister* is the one who’s good” — focus, not “also”.',
      '妹と日本語 means “my sister and Japanese” — garbled.'],
    mo10: ['も adds 明日 to other rainy days: “tomorrow will be rainy *too*”.',
      '明日は雨です drops the “too”.',
      '明日が雨です means “*tomorrow* is the rainy day” — focus, not “too”.',
      '明日と means “with tomorrow” — nonsense here.'],
    mo11: ['も adds 田中さん to the people who came: “Mr. Tanaka *also* came”.',
      '田中さんは会議に来ました drops the “also”.',
      '田中さんが来ました means “it was *Mr. Tanaka* who came” — focus, not “also”.',
      '田中さんと会議に来ました means “(I) came to the meeting with Mr. Tanaka”.'],
    mo12: ['も adds このケーキ to other tasty things: “this cake is *also* delicious”.',
      'このケーキは美味しいです drops the “also”.',
      'このケーキが美味しい means “*this* cake is the tasty one” — focus, not “also”.',
      'このケーキと means “with this cake” and leaves no subject.'],
    mo13: ['も replaces が on the skill: “he can *also* play the piano”.',
      'ピアノは弾けます is contrastive (“piano, he can play”) — no “also”.',
      'ピアノが弾けます is the plain “he can play the piano” — no “also”.',
      'ピアノと弾けます means “can play with the piano” — garbled.'],
    mo14: ['も replaces が on the thing liked: “I like fish *too*”.',
      '魚は好きです is contrastive (“fish I like”) — no “too”.',
      '魚が好きです is the plain “I like fish” — no “too”.',
      '魚と好きです is broken; と needs another noun after it.'],
    mo15: ['も adds 弟 to those who did homework: “my brother *also* did it”.',
      '弟は宿題をしました drops the “also”.',
      '弟が宿題をしました means “it was *my brother* who did it” — focus, not “also”.',
      '弟と宿題をしました means “(I) did homework with my brother”.'],
    mo16: ['も adds 今日 to other busy days: “today is busy *too*”.',
      '今日は忙しいです drops the “too”.',
      '今日が忙しい means “*today* is the busy day” — focus, not “too”.',
      '今日と means “with today” — nonsense here.'],
    mo17: ['も adds あの店 to other famous shops: “that shop is famous *too*”.',
      'あの店は有名です drops the “too”.',
      'あの店が有名です means “*that* shop is the famous one” — focus, not “too”.',
      'あの店と means “with that shop” and leaves no subject.'],
    mo18: ['も adds 私 to those living in Kyoto: “I *also* live in Kyoto”.',
      '私は京都に住んでいます drops the “also”.',
      '私が住んでいます means “*I*’m the one who lives there” — focus, not “also”.',
      '私と京都に住んでいます means “(someone) lives in Kyoto with me”.'],
    mo19: ['も adds 山田さん to those traveling: “Mr. Yamada is *also* going”.',
      '山田さんは旅行に行きます drops the “also”.',
      '山田さんが行きます means “*Mr. Yamada* is the one going” — focus, not “also”.',
      '山田さんと旅行に行きます means “(I’m) going on a trip with Mr. Yamada”.'],
    mo20: ['も adds このアパート to other quiet places: “this apartment is quiet *too*”.',
      'このアパートは静かです drops the “too”.',
      'このアパートが静かです means “*this* apartment is the quiet one” — focus, not “too”.',
      'このアパートと means “with this apartment” and leaves no subject.'],

    // の — not が, は, と
    no1: ['の links 私 to 本: “my book”.',
      'これは私が本です has two subjects and means nothing (“I am the book”).',
      'これは私は本です has two topics — garbled.',
      '私と本です means “it’s me and a book”.'],
    no2: ['の links 山田さん to 傘: “Mr. Yamada’s umbrella”.',
      '山田さんが傘はどこ… is garbled — Mr. Yamada can’t be the subject of “where is”.',
      '山田さんは傘はどこですか is loose speech and doesn’t say whose umbrella it is.',
      '山田さんと傘はどこですか means “where are Mr. Yamada and the umbrella?”.'],
    no3: ['の lets 日本語 describe 先生: “the Japanese teacher” — a noun modifying a noun, not ownership.',
      '日本語が先生は… is garbled.',
      '日本語は先生は… has two topics — garbled.',
      '日本語と先生は親切です means “Japanese and the teacher are kind”.'],
    no4: ['の links 友達 to 車: “my friend’s car”.',
      'これは友達が車です is garbled (“the friend is a car”).',
      'これは友達は車です has two topics — garbled.',
      '友達と車です means “it’s my friend and a car”.'],
    no5: ['の links 東京 to 天気: “Tokyo’s weather”.',
      '東京が天気は… is garbled.',
      '東京は天気はいいです stacks two topics; the natural version is 東京は天気がいいです.',
      '東京と天気はいいです means “Tokyo and the weather are nice”.'],
    no6: ['の links 私 to 家族: “my family”.',
      '私が家族は… is garbled.',
      '私は家族は四人です stacks two topics; the natural version is 私の家族は四人です.',
      '私と家族は四人です means “my family and I are four people” — a different count.'],
    no7: ['の links 田中さん to かばん: “Mr. Tanaka’s bag”.',
      'これは田中さんがかばんです is garbled.',
      'これは田中さんはかばんです has two topics — garbled.',
      '田中さんとかばんです means “it’s Mr. Tanaka and a bag”.'],
    no8: ['の lets 学校 describe 建物: “the school building”.',
      'あれは学校が建物です is garbled.',
      'あれは学校は建物です has two topics — garbled.',
      '学校と建物です means “it’s the school and a building”.'],
    no9: ['の links この本 to 作者: “this book’s author”.',
      'この本が作者は… is garbled.',
      'この本は作者は… stacks two topics; the natural version is この本の作者は.',
      'この本と作者は有名です means “this book and the author are famous”.'],
    no10: ['の links 私 to 部屋: “my room”.',
      '私が部屋は… is garbled.',
      '私は部屋は… stacks two topics and doesn’t say whose room.',
      '私と部屋は二階です means “the room and I are on the second floor”.'],
    no11: ['の links 山田さん to 犬: “Mr. Yamada’s dog”.',
      '山田さんが犬は… is garbled.',
      '山田さんは犬は… stacks two topics and doesn’t say whose dog.',
      '山田さんと犬は可愛いです means “Mr. Yamada and the dog are cute”.'],
    no12: ['の links 会社 to 車: “the company’s car”.',
      'これは会社が車です is garbled.',
      'これは会社は車です has two topics — garbled.',
      '会社と車です means “it’s the company and a car”.'],
    no13: ['の links 田中さん to 奥さん: “Mr. Tanaka’s wife”.',
      '田中さんが奥さんは… is garbled.',
      '田中さんは奥さんは… stacks two topics and doesn’t say whose wife.',
      '田中さんと奥さんは医者です means “Mr. Tanaka and his wife are doctors”.'],
    no14: ['の links 私の父 to 趣味: “my father’s hobby”.',
      '私の父が趣味は… is garbled.',
      '私の父は趣味は… stacks two topics and doesn’t say whose hobby.',
      '私の父と趣味は釣りです means “my father and the hobby are fishing” — nonsense.'],
    no15: ['の links 学校 to 図書館: “the school’s library”.',
      '学校が図書館は… is garbled.',
      '学校は図書館は… stacks two topics and doesn’t say whose library.',
      '学校と図書館は大きいです means “the school and the library are big”.'],
    no16: ['の links 友達 to 傘: “my friend’s umbrella”.',
      'これは友達が傘です is garbled.',
      'これは友達は傘です has two topics — garbled.',
      '友達と傘です means “it’s my friend and an umbrella”.'],
    no17: ['の links あの家 to 屋根: “that house’s roof”.',
      'あの家が屋根は… is garbled.',
      'あの家は屋根は… stacks two topics; the natural version is あの家の屋根は.',
      'あの家と屋根は赤いです means “that house and the roof are red”.'],
    no18: ['の links 姉 to 誕生日: “my older sister’s birthday”.',
      '姉が誕生日は… is garbled.',
      '姉は誕生日は… stacks two topics and doesn’t say whose birthday.',
      '姉と誕生日は来月です means “my sister and the birthday are next month” — nonsense.'],
    no19: ['の links 会社 to 電話番号: “the company’s phone number”.',
      '会社が電話番号を教えて… would make the company the one telling.',
      '会社は電話番号を… makes the company the topic and drops whose number it is.',
      '会社と電話番号を教えて means “tell me the company and the phone number”.'],
    no20: ['の links この店 to パン: “this shop’s bread”.',
      'この店がパンは… is garbled.',
      'この店はパンは… stacks two topics; the natural version is この店のパンは.',
      'この店とパンは美味しいです means “this shop and the bread are delicious”.'],

    // や — not と, も, の
    ya1: ['や lists examples without being complete: “things like a book and a pen” — there may be more.',
      '本とペン means exactly a book and a pen — grammatical, but the English says “things like”.',
      '本もペンが is broken; “both” would be 本もペンも.',
      '本のペン means “the book’s pen”.'],
    ya2: ['や lists examples: “animals like dogs and cats”.',
      '犬と猫 means exactly dogs and cats — the English says “animals like”.',
      '犬も猫が is broken; “both” would be 犬も猫も.',
      '犬の猫 means “the dog’s cat”.'],
    ya3: ['や lists examples: “stuff like apples and milk” — there may be more.',
      'りんごと牛乳 means exactly those two — the English says “stuff like”.',
      'りんごも牛乳が is broken; “both” would be りんごも牛乳も.',
      'りんごの牛乳 means “apple milk”.'],
    ya4: ['や lists examples: “things like a TV and a chair”.',
      'テレビと椅子 means exactly those two — the English says “things like”.',
      'テレビも椅子が is broken; “both” would be テレビも椅子も.',
      'テレビの椅子 means “the TV’s chair”.'],
    ya5: ['や lists example activities: “things like shopping and movies”.',
      '買い物と映画 means exactly those two — the English says “things like”.',
      '買い物も映画を is broken.',
      '買い物の映画 means “a shopping movie”.'],
    ya6: ['や lists examples: “students, teachers and others”.',
      '学生と先生 means exactly students and teachers — the English says “and others”.',
      '学生も先生が is broken; “both” would be 学生も先生も.',
      '学生の先生 means “the students’ teacher”.'],
    ya7: ['や lists examples: “things like comics and novels”.',
      '漫画と小説 means exactly those two — the English says “things like”.',
      '漫画も小説が is broken.',
      '漫画の小説 means “a novel of a manga”.'],
    ya8: ['や lists examples: “people like Mr. Yamada and Mr. Tanaka” — others came too.',
      '山田さんと田中さん means exactly those two came.',
      '山田さんも田中さんが is broken.',
      '山田さんの田中さん means “Mr. Yamada’s Mr. Tanaka”.'],
    ya9: ['や lists example chores: “things like cleaning and laundry”.',
      '掃除と洗濯 means exactly those two chores.',
      '掃除も洗濯を is broken.',
      '掃除の洗濯 means “the cleaning’s laundry”.'],
    ya10: ['や lists examples: “children and adults, among others”.',
      '子供と大人 means exactly children and adults.',
      '子供も大人が is broken.',
      '子供の大人 means “the children’s adults”.'],
    ya11: ['や lists examples: “things like fish and meat”.',
      '魚と肉 means exactly fish and meat — the English says “things like”.',
      '魚も肉が is broken.',
      '魚の肉 means “fish meat”.'],
    ya12: ['や lists examples: “things like a passport and money”.',
      'パスポートとお金 means exactly those two — the English says “things like”.',
      'パスポートもお金が is broken.',
      'パスポートのお金 means “the passport’s money”.'],
    ya13: ['や lists examples: “things like books and notebooks”.',
      '本とノート means exactly those two — the English says “things like”.',
      '本もノートが is broken.',
      '本のノート means “notes on the book”.'],
    ya14: ['や lists examples: “things like maps and photos”.',
      '地図と写真 means exactly those two — the English says “things like”.',
      '地図も写真が is broken.',
      '地図の写真 means “a photo of a map”.'],
    ya15: ['や lists examples: “things like boxes and tape”.',
      '箱とテープ means exactly those two — the English says “things like”.',
      '箱もテープが is broken.',
      '箱のテープ means “the box’s tape”.'],
    ya16: ['や lists examples: “things like newspapers and magazines”.',
      '新聞と雑誌 means exactly those two — the English says “things like”.',
      '新聞も雑誌が is broken.',
      '新聞の雑誌 means “the newspaper’s magazine”.'],
    ya17: ['や lists examples: “things like cake and presents”.',
      'ケーキとプレゼント means exactly those two — the English says “things like”.',
      'ケーキもプレゼントを is broken.',
      'ケーキのプレゼント means “a present of cake” — one gift, not two.'],
    ya18: ['や lists examples: “animals like pandas and lions”.',
      'パンダとライオン means exactly those two — the English says “things like”.',
      'パンダもライオンが is broken.',
      'パンダのライオン means “the panda’s lion”.'],
    ya19: ['や lists examples: “things like plates and cups”.',
      'お皿とコップ means exactly those two — the English says “things like”.',
      'お皿もコップが is broken.',
      'お皿のコップ means “the plate’s cup”.'],
    ya20: ['や lists examples: “stuff like juice and beer”.',
      'ジュースとビール means exactly those two — the English says “stuff like”.',
      'ジュースもビールが is broken.',
      'ジュースのビール means “juice beer”.'],
  };

  // { id: { why, not: { particle: note } } }
  const groups = global.PARTICLE_DISTRACTOR_GROUPS || {};
  const items = global.PARTICLE_QUIZ_ITEMS || [];
  global.PARTICLE_NOTES = {};
  items.forEach(item => {
    const n = N[item.id];
    if (!n) return;
    const not = {};
    (groups[item.particle] || []).forEach((p, i) => { not[p] = n[i + 1]; });
    global.PARTICLE_NOTES[item.id] = { why: n[0], not };
  });

})(typeof window !== 'undefined' ? window : globalThis);
