(function (global) {
  'use strict';

  // A short story for each Phrases category page (phrases-<id>.html), using
  // that category's phrases. Each line is [speaker, Japanese, English]: the
  // speaker is '' for narration, and both speaker and Japanese use the same
  // 漢字[かんじ] furigana markup as phrases-data.js. "Read aloud" reads the
  // Japanese lines one after another; the speakers' names aren't read.
  //
  // test_phrases.js checks every category has a story, the markup, and that
  // each story really uses some of its category's phrases.

  global.PHRASE_STORIES = {
    slogans: {
      title: 'コマーシャルの時間[じかん]',
      titleEn: 'Commercial break',
      lines: [
        ['', '日曜日[にちようび]の夜[よる]、ケンとユキはテレビを見[み]ています。', 'Sunday night. Ken and Yuki are watching TV.'],
        ['テレビ', 'やめられない、とまらない…', 'Can\'t quit, can\'t stop…'],
        ['ケン', 'かっぱえびせん！', 'Kappa Ebisen!'],
        ['ユキ', 'ケン、もう一袋[ひとふくろ]食[た]べてるよ。', 'Ken, you\'ve already eaten a whole bag.'],
        ['テレビ', 'そうだ 京都[きょうと]、行[い]こう。', 'I know — let\'s go to Kyoto.'],
        ['ケン', 'そうだ、京都[きょうと]、行[い]こう！', 'I know — let\'s go to Kyoto!'],
        ['ユキ', 'え、今[いま]から？もう夜[よる]の十時[じゅうじ]だよ。', 'What, now? It\'s already ten at night.'],
        ['ケン', '大丈夫[だいじょうぶ]！24時間[じかん]戦[たたか]えますから！', 'No problem! I can fight for 24 hours!'],
        ['ユキ', 'それ、古[ふる]いよ…', 'That one\'s ancient…'],
      ],
    },
    occasions: {
      title: 'メアリーの一年[いちねん]',
      titleEn: 'Mary\'s year',
      lines: [
        ['', '一月[いちがつ]一日[ついたち]、メアリーは友達[ともだち]にメッセージを送[おく]りました。', 'On 1 January, Mary sent her friends a message.'],
        ['メアリー', 'あけましておめでとうございます！今年[ことし]もよろしくお願[ねが]いします。', 'Happy New Year! Please be good to me again this year.'],
        ['', '二月[にがつ]には、会社[かいしゃ]のみんなに義理[ぎり]チョコをあげました。', 'In February she gave obligation chocolate to everyone at work.'],
        ['', '七月[しちがつ]、七夕[たなばた]の短冊[たんざく]にこう書[か]きました。', 'In July she wrote this on her Tanabata wish strip:'],
        ['メアリー', '日本語[にほんご]が上手[じょうず]になりますように。', 'May my Japanese get better.'],
        ['', '十二月[じゅうにがつ]、メアリーの誕生日[たんじょうび]に、友達[ともだち]がケーキを持[も]ってきました。', 'In December, on Mary\'s birthday, her friends brought a cake.'],
        ['みんな', 'お誕生日[たんじょうび]おめでとう！', 'Happy birthday!'],
        ['', '帰[かえ]るとき、メアリーは手[て]を振[ふ]りました。', 'As they went home, Mary waved.'],
        ['メアリー', 'よいお年[とし]を！', 'Have a good New Year!'],
      ],
    },
    everyday: {
      title: 'ケンの一日[いちにち]',
      titleEn: 'Ken\'s day in set phrases',
      lines: [
        ['', '朝[あさ]、ケンは家[いえ]を出[で]ます。', 'In the morning, Ken leaves home.'],
        ['ケン', 'いってきます！', 'I\'m off!'],
        ['お母[かあ]さん', 'いってらっしゃい！気[き]をつけて！', 'See you later! Take care!'],
        ['', '会社[かいしゃ]では、みんなが言[い]います。', 'At the office, everyone says:'],
        ['みんな', 'お疲[つか]れさまです。', 'Thanks for your hard work.'],
        ['', '夜[よる]、ケンは友達[ともだち]の家[いえ]に行[い]きました。', 'In the evening, Ken went to a friend\'s home.'],
        ['ケン', 'お邪魔[じゃま]します。これ、つまらないものですが…', 'Sorry to disturb you. This is just a boring little thing, but…'],
        ['', '二人[ふたり]は手[て]を合[あ]わせました。', 'The two of them put their hands together.'],
        ['二人[ふたり]', 'いただきます！', 'Let\'s eat!'],
        ['', '家[いえ]に帰[かえ]ると、お母[かあ]さんが待[ま]っていました。', 'When he got home, his mother was waiting.'],
        ['ケン', 'ただいま！', 'I\'m home!'],
      ],
    },
    meeting: {
      title: '言語[げんご]交換[こうかん]のイベントで',
      titleEn: 'At the language exchange',
      lines: [
        ['', 'メアリーは初[はじ]めて言語[げんご]交換[こうかん]のイベントに行[い]きました。', 'Mary went to a language exchange event for the first time.'],
        ['メアリー', 'はじめまして。メアリーと申[もう]します。', 'Nice to meet you. My name is Mary.'],
        ['ケン', 'はじめまして、ケンです。どちらから来[き]ましたか？', 'Nice to meet you, I\'m Ken. Where are you from?'],
        ['メアリー', 'オランダから来[き]ました。', 'I\'m from the Netherlands.'],
        ['ケン', '日本[にほん]に来[き]て、どのくらいですか？', 'How long have you been in Japan?'],
        ['メアリー', '半年[はんとし]です。', 'Six months.'],
        ['ケン', '趣味[しゅみ]は何[なん]ですか？', 'What are your hobbies?'],
        ['メアリー', '自転車[じてんしゃ]です。オランダ人[じん]ですから。', 'Cycling. I\'m Dutch, after all.'],
        ['ケン', 'ははは！連絡先[れんらくさき]、交換[こうかん]しませんか？', 'Ha ha! Shall we swap contacts?'],
        ['メアリー', 'はい！これからよろしくお願[ねが]いします。', 'Yes! I look forward to getting to know you.'],
      ],
    },
    firstdate: {
      title: '渋谷[しぶや]で初[はつ]デート',
      titleEn: 'A first date in Shibuya',
      lines: [
        ['', '土曜日[どようび]、ケンはユキと初[はつ]デートです。', 'On Saturday, Ken has his first date with Yuki.'],
        ['', 'ケンは朝[あさ]からずっと緊張[きんちょう]しています。', 'Ken has been nervous since the morning.'],
        ['', 'ユキからLINEが来[き]ました。', 'A LINE message came from Yuki.'],
        ['ユキ', 'ごめん、ちょっと遅[おく]れる！', 'Sorry, I\'ll be a bit late!'],
        ['', '十分[じゅっぷん]後[ご]、ユキが改札[かいさつ]から出[で]てきました。', 'Ten minutes later, Yuki came out of the ticket gates.'],
        ['ケン', 'その服[ふく]、似合[にあ]ってるね。', 'That outfit suits you.'],
        ['ケン', '何[なに]か苦手[にがて]な食[た]べ物[もの]ある？', 'Any food you don\'t like?'],
        ['ユキ', 'ピーマン以外[いがい]なら、大丈夫[だいじょうぶ]！', 'Anything but green peppers!'],
        ['', 'お会計[かいけい]のとき、ケンが財布[さいふ]を出[だ]しました。', 'When the bill came, Ken took out his wallet.'],
        ['ケン', 'ここはぼくが払[はら]うよ。', 'Let me get this.'],
        ['ユキ', 'じゃあ、次[つぎ]は私[わたし]ね。今日[きょう]はすごく楽[たの]しかった！', 'Then next time it\'s me. I had a great time today!'],
        ['ケン', 'ぼくも。家[いえ]に着[つ]いたら連絡[れんらく]してね。', 'Me too. Message me when you get home.'],
      ],
    },
    firstday: {
      title: 'メアリーの初日[しょにち]',
      titleEn: 'Mary\'s first day',
      lines: [
        ['', '四月[しがつ]一日[ついたち]、メアリーの新[あたら]しい仕事[しごと]が始[はじ]まりました。', 'On 1 April, Mary\'s new job began.'],
        ['', '朝[あさ]、メアリーはみんなの前[まえ]に立[た]ちました。', 'In the morning, Mary stood in front of everyone.'],
        ['メアリー', '本日[ほんじつ]からお世話[せわ]になります、メアリーです。', 'I\'ll be in your care from today. I\'m Mary.'],
        ['メアリー', '至[いた]らない点[てん]もあるかと思[おも]いますが、よろしくお願[ねが]いいたします。', 'I may fall short at times, but I ask for your kind support.'],
        ['', '先輩[せんぱい]のサトウさんが、仕事[しごと]を教[おし]えてくれました。', 'Sato, her senior, showed her the job.'],
        ['メアリー', 'メモを取[と]ってもいいですか？', 'May I take notes?'],
        ['', '昼[ひる]、メアリーは勇気[ゆうき]を出[だ]しました。', 'At noon, Mary plucked up her courage.'],
        ['メアリー', 'お昼[ひる]、ご一緒[いっしょ]してもいいですか？', 'May I join you for lunch?'],
        ['サトウさん', 'もちろん！', 'Of course!'],
        ['', '六時[ろくじ]、メアリーはかばんを持[も]ちました。', 'At six, Mary picked up her bag.'],
        ['メアリー', '今日[きょう]はありがとうございました。お先[さき]に失礼[しつれい]します。', 'Thank you for today. Excuse me for leaving first.'],
        ['みんな', 'お疲[つか]れさまでした！', 'Good work today!'],
      ],
    },
    friends: {
      title: 'カラオケに行[い]こう',
      titleEn: 'Let\'s go to karaoke',
      lines: [
        ['', 'ユキとメアリーは、同[おな]じクラスです。', 'Yuki and Mary are in the same class.'],
        ['メアリー', 'ユキさん、週末[しゅうまつ]、ひまですか？', 'Yuki, are you free this weekend?'],
        ['ユキ', 'ひまだよ！あ、タメ口[ぐち]でいいよ。', 'I\'m free! Oh — you can talk casually with me.'],
        ['メアリー', 'じゃあ…カラオケ行[い]かない？', 'Then… want to go to karaoke?'],
        ['ユキ', 'いいね！行[い]こう行[い]こう！', 'Nice! Let\'s go, let\'s go!'],
        ['', 'カラオケで、二人[ふたり]は三時間[さんじかん]も歌[うた]いました。', 'At karaoke the two of them sang for three whole hours.'],
        ['メアリー', '一緒[いっしょ]に写真[しゃしん]撮[と]ろう！', 'Let\'s take a photo together!'],
        ['ユキ', '私[わたし]たち、気[き]が合[あ]うね！', 'We really get along!'],
        ['メアリー', 'それな！', 'Right?!'],
      ],
    },
    texting: {
      title: '既読[きどく]スルー',
      titleEn: 'Left on read',
      lines: [
        ['', '夜[よる]七時[しちじ]、ケンはユキにLINEを送[おく]りました。', 'At seven in the evening, Ken sent Yuki a LINE message.'],
        ['ケン', '今[いま]どこ？', 'Where are you now?'],
        ['', '既読[きどく]はつきました。でも、返事[へんじ]がありません。', 'It was marked as read. But there was no reply.'],
        ['ケン', '既読[きどく]スルーされた…', 'I got left on read…'],
        ['', 'ケンは心配[しんぱい]になって、スタンプを十個[じゅっこ]送[おく]りました。', 'Ken got worried and sent ten stickers.'],
        ['', '三十分[さんじゅっぷん]後[ご]、やっと返事[へんじ]が来[き]ました。', 'Thirty minutes later, a reply finally came.'],
        ['ユキ', 'ごめん、寝落[ねお]ちしてた！スタンプ多[おお]すぎ（笑[わら]）', 'Sorry, I fell asleep! Way too many stickers (lol)'],
        ['ケン', '明日[あした]、駅前[えきまえ]で六時[ろくじ]でいい？', 'Tomorrow, six o\'clock in front of the station?'],
        ['ユキ', 'りょ！おやすみ〜、また明日[あした]ね！', 'K! Night~, see you tomorrow!'],
      ],
    },
    homevisit: {
      title: '先生[せんせい]のお宅[たく]で',
      titleEn: 'At the teacher\'s home',
      lines: [
        ['', '日曜日[にちようび]、メアリーは先生[せんせい]のお宅[たく]に招[まね]かれました。', 'On Sunday, Mary was invited to her teacher\'s home.'],
        ['先生[せんせい]', 'いらっしゃい。どうぞ、上[あ]がってください。', 'Welcome. Please, come on in.'],
        ['', 'メアリーは玄関[げんかん]で靴[くつ]を脱[ぬ]ぎました。', 'Mary took off her shoes in the entrance.'],
        ['先生[せんせい]', 'スリッパをどうぞ。', 'Here, have some slippers.'],
        ['メアリー', '素敵[すてき]なお家[うち]ですね。これ、つまらないものですが…', 'What a lovely home. This is just a little something…'],
        ['', '先生[せんせい]の奥[おく]さんが、料理[りょうり]を出[だ]してくれました。', 'The teacher\'s wife served the food.'],
        ['奥[おく]さん', 'お口[くち]に合[あ]うかどうか…', 'I\'m not sure it\'ll suit your taste…'],
        ['メアリー', 'とてもおいしいです！', 'It\'s delicious!'],
        ['奥[おく]さん', '遠慮[えんりょ]しないで、たくさん食[た]べてね。', 'Don\'t hold back — eat lots!'],
        ['', '夜[よる]九時[くじ]になりました。', 'It got to nine in the evening.'],
        ['メアリー', 'そろそろ失礼[しつれい]します。今日[きょう]はお招[まね]きいただき、ありがとうございました。', 'I should be going. Thank you for having me today.'],
      ],
    },
    sayingno: {
      title: '部長[ぶちょう]とゴルフ',
      titleEn: 'Golf with the boss',
      lines: [
        ['', '金曜日[きんようび]の午後[ごご]、部長[ぶちょう]がケンに聞[き]きました。', 'On Friday afternoon, the boss asked Ken:'],
        ['部長[ぶちょう]', 'ケンくん、明日[あした]、ゴルフに行[い]かない？', 'Ken, want to play golf tomorrow?'],
        ['ケン', 'あ、明日[あした]はちょっと…', 'Ah, tomorrow is a bit…'],
        ['部長[ぶちょう]', 'じゃあ、日曜日[にちようび]は？', 'Then how about Sunday?'],
        ['ケン', 'ちょっと考[かんが]えさせてください。', 'Let me think about it.'],
        ['部長[ぶちょう]', '来週[らいしゅう]の土曜日[どようび]は？', 'Saturday next week?'],
        ['ケン', '今回[こんかい]は遠慮[えんりょ]しておきます。', 'I\'ll pass this time.'],
        ['', '月曜日[げつようび]、ケンは会議[かいぎ]に遅[おく]れました。', 'On Monday, Ken was late for a meeting.'],
        ['ケン', '遅[おく]れてすみません。', 'Sorry I\'m late.'],
        ['部長[ぶちょう]', '気[き]にしないで。…ところで、ゴルフは？', 'Don\'t worry about it. …So, about golf?'],
        ['ケン', '前向[まえむ]きに検討[けんとう]します。', 'I\'ll consider it positively.'],
      ],
    },
    directions: {
      title: '京都[きょうと]で迷子[まいご]',
      titleEn: 'Lost in Kyoto',
      lines: [
        ['', 'メアリーは京都[きょうと]で道[みち]に迷[まよ]ってしまいました。', 'Mary got lost in Kyoto.'],
        ['メアリー', 'すみません、駅[えき]はどこですか？', 'Excuse me, where is the station?'],
        ['おばあさん', '駅[えき]ね。まっすぐ行[い]って、二[ふた]つ目[め]の角[かど]を右[みぎ]です。', 'The station? Go straight, then right at the second corner.'],
        ['メアリー', 'ここから歩[ある]いて行[い]けますか？', 'Can I walk there from here?'],
        ['おばあさん', '五分[ごふん]ぐらいよ。', 'About five minutes.'],
        ['', '三十分[さんじゅっぷん]歩[ある]いても、駅[えき]は見[み]えません。', 'Even after thirty minutes of walking, there\'s no station in sight.'],
        ['', 'メアリーはタクシーに乗[の]りました。', 'Mary got into a taxi.'],
        ['メアリー', '京都駅[きょうとえき]までお願[ねが]いします。', 'To Kyoto Station, please.'],
        ['運転手[うんてんしゅ]さん', 'お客[きゃく]さん、駅[えき]はすぐそこですよ。', 'Miss, the station is right there.'],
        ['', '角[かど]を曲[ま]がると、目[め]の前[まえ]に駅[えき]がありました。', 'Round the corner, the station was right in front of her.'],
      ],
    },
    hotel: {
      title: '箱根[はこね]の旅館[りょかん]',
      titleEn: 'A ryokan in Hakone',
      lines: [
        ['', 'メアリーとユキは、箱根[はこね]の旅館[りょかん]に着[つ]きました。', 'Mary and Yuki arrived at a ryokan in Hakone.'],
        ['メアリー', '予約[よやく]しているスミスです。', 'I have a reservation — Smith.'],
        ['', '部屋[へや]で、ユキが浴衣[ゆかた]の着方[きかた]を教[おし]えてくれました。', 'In the room, Yuki showed her how to wear the yukata.'],
        ['ユキ', '左[ひだり]を上[うえ]にするんだよ。', 'The left side goes on top.'],
        ['', '温泉[おんせん]で、メアリーは先[さき]に体[からだ]を洗[あら]いました。', 'At the hot spring, Mary washed herself first.'],
        ['', '湯船[ゆぶね]に入[はい]ると、となりのおばあさんが言[い]いました。', 'When she got into the bath, the old lady next to her said:'],
        ['おばあさん', 'ああ、極楽[ごくらく]、極楽[ごくらく]…', 'Ahh, paradise, paradise…'],
        ['メアリー', '極楽[ごくらく]、極楽[ごくらく]…', 'Paradise, paradise…'],
        ['', '部屋[へや]に戻[もど]ると、ユキが聞[き]きました。「どうだった？」', 'Back in the room, Yuki asked: "How was it?"'],
        ['メアリー', 'いいお湯[ゆ]でした！', 'That was a lovely bath!'],
      ],
    },
    doctor: {
      title: 'ケン、かぜをひく',
      titleEn: 'Ken catches a cold',
      lines: [
        ['', 'ある朝[あさ]、ケンは体[からだ]がだるくて、起[お]きられませんでした。', 'One morning, Ken felt so sluggish he couldn\'t get up.'],
        ['受付[うけつけ]', '保険証[ほけんしょう]はお持[も]ちですか？', 'Do you have your health insurance card?'],
        ['医者[いしゃ]', 'どうしましたか？', 'What seems to be the problem?'],
        ['ケン', '熱[ねつ]があります。それに、頭[あたま]が痛[いた]いです。', 'I have a fever. And I have a headache.'],
        ['医者[いしゃ]', 'アレルギーはありますか？', 'Do you have any allergies?'],
        ['ケン', 'ありません。', 'No.'],
        ['医者[いしゃ]', 'かぜですね。今日[きょう]はゆっくり休[やす]んでください。お大事[だいじ]に。', 'It\'s a cold. Rest well today. Take care.'],
        ['', '家[いえ]で寝[ね]ていると、急[きゅう]に部屋[へや]がゆれました。', 'As he lay in bed at home, the room suddenly shook.'],
        ['ケン', '地震[じしん]だ！', 'Earthquake!'],
        ['', 'でも、ゆれはすぐに止[と]まりました。ケンはまた寝[ね]ました。', 'But the shaking soon stopped. Ken went back to sleep.'],
      ],
    },
    nomikai: {
      title: '金曜日[きんようび]の飲[の]み会[かい]',
      titleEn: 'Friday drinks',
      lines: [
        ['', '金曜日[きんようび]、会社[かいしゃ]の飲[の]み会[かい]がありました。', 'On Friday there was a work drinking party.'],
        ['メアリー', '今日[きょう]の幹事[かんじ]です。よろしくお願[ねが]いします！', 'I\'m today\'s organiser. Thanks, everyone!'],
        ['部長[ぶちょう]', '今日[きょう]は無礼講[ぶれいこう]で！かんぱーい！', 'No rank tonight! Cheers!'],
        ['', 'メアリーは部長[ぶちょう]のグラスを見[み]ました。', 'Mary looked at the boss\'s glass.'],
        ['メアリー', 'グラスが空[から]ですよ。お注[つ]ぎします。', 'Your glass is empty. Let me pour for you.'],
        ['', 'ケンはビールを五杯[ごはい]も飲[の]みました。', 'Ken drank five whole beers.'],
        ['ケン', '飲[の]みすぎた…', 'I drank too much…'],
        ['部長[ぶちょう]', '二次会[にじかい]行[い]く人[ひと]ー！', 'Who\'s coming to the second round?'],
        ['メアリー', 'やばい、終電[しゅうでん]なくなる！', 'Oh no, I\'ll miss the last train!'],
        ['', '月曜日[げつようび]、ケンは何[なに]も覚[おぼ]えていませんでした。', 'On Monday, Ken didn\'t remember a thing.'],
      ],
    },
    anime: {
      title: 'アニメ部[ぶ]の一日[いちにち]',
      titleEn: 'A day at the anime club',
      lines: [
        ['', 'アニメ部[ぶ]の三人[さんにん]は、毎日[まいにち]セリフで話[はな]します。', 'The three anime club members talk in anime lines every day.'],
        ['ケン', '海賊王[かいぞくおう]に、おれはなる！', 'I\'m gonna be King of the Pirates!'],
        ['ユキ', 'まず、宿題[しゅくだい]をしてね。', 'Do your homework first.'],
        ['', 'テストの前[まえ]、ケンは目[め]を閉[と]じました。', 'Before the test, Ken closed his eyes.'],
        ['ケン', '全集中[ぜんしゅうちゅう]…', 'Total concentration…'],
        ['', 'でも、答[こた]えは一[ひと]つもわかりませんでした。', 'But he didn\'t know a single answer.'],
        ['', '昼[ひる]ごはんのとき、ケンのパンがなくなりました。', 'At lunch, Ken\'s bread disappeared.'],
        ['ケン', 'あれれ〜？おかしいぞ〜？', 'Huh~? That\'s weird~?'],
        ['ユキ', '犯人[はんにん]は…タロウくん！真実[しんじつ]はいつもひとつ！', 'The culprit is… Taro! There is only ever one truth!'],
        ['タロウ', 'お前[まえ]のものはおれのもの、おれのものもおれのもの。', 'What\'s yours is mine, and what\'s mine is mine too.'],
        ['ケン', 'ジャイアンか！', 'Who are you, Gian?!'],
      ],
    },
    ghibli: {
      title: 'ハナの朝[あさ]',
      titleEn: 'Hana\'s morning',
      lines: [
        ['', '朝[あさ]七時[しちじ]。お母[かあ]さんの大[おお]きな声[こえ]がします。', 'Seven in the morning. Mum\'s loud voice rings out.'],
        ['お母[かあ]さん', '40秒[びょう]で支度[したく]しな！', 'Get ready in 40 seconds!'],
        ['ハナ', 'まだ眠[ねむ]い…', 'I\'m still sleepy…'],
        ['', 'ハナは暗[くら]い押[お]し入[い]れを開[あ]けました。', 'Hana opened the dark closet.'],
        ['ハナ', 'まっくろくろすけ、出[で]ておいで！', 'Soot sprites, come out!'],
        ['', '何[なに]もいませんでした。', 'There was nothing there.'],
        ['', '学校[がっこう]で、ハナは友達[ともだち]に話[はな]しました。「森[もり]で大[おお]きいねこを見[み]たよ！」', 'At school, Hana told her friends: "I saw a giant cat in the forest!"'],
        ['友達[ともだち]', 'うそだ！', 'Liar!'],
        ['ハナ', 'トトロ、いたもん！', 'Totoro was there, I tell you!'],
        ['', '帰[かえ]りに、お兄[にい]ちゃんが丘[おか]の上[うえ]から町[まち]を見[み]ました。', 'On the way home, her big brother looked down at the town from a hill.'],
        ['お兄[にい]ちゃん', '見[み]ろ、人[ひと]がゴミのようだ！', 'Look — the people are like garbage!'],
        ['ハナ', 'お兄[にい]ちゃん、それ、悪[わる]い人[ひと]のセリフだよ。', 'That\'s the bad guy\'s line, you know.'],
      ],
    },
    games: {
      title: 'ケンのRPG',
      titleEn: 'Ken\'s real-life RPG',
      lines: [
        ['', 'ケンの毎日[まいにち]は、ロールプレイングゲームです。', 'Ken\'s everyday life is a role-playing game.'],
        ['', '朝[あさ]、駅[えき]の角[かど]を曲[ま]がると…', 'In the morning, as he turns the corner at the station…'],
        ['', 'あ！やせいの 部長[ぶちょう]が とびだしてきた！', 'Oh! A wild boss jumped out!'],
        ['', 'ケンは逃[に]げようとしました。しかし まわりこまれてしまった！', 'Ken tried to run. But he was cut off!'],
        ['部長[ぶちょう]', 'ケンくん、昨日[きのう]の資料[しりょう]は？', 'Ken, where\'s yesterday\'s report?'],
        ['', 'ケンは考[かんが]えました。たたかう？にげる？', 'Ken thought: fight? Run?'],
        ['', '夜[よる]、ケンは友達[ともだち]にメッセージを送[おく]りました。でも、返事[へんじ]がありません。', 'That night, Ken messaged a friend. No reply.'],
        ['', 'へんじがない。ただの しかばね のようだ。', 'No reply. It seems to be just a corpse.'],
        ['', '次[つぎ]の日[ひ]、資料[しりょう]がやっと完成[かんせい]しました。', 'The next day, the report was finally finished.'],
        ['', 'レベルが あがった！', 'You levelled up!'],
      ],
    },
    movies: {
      title: '映画[えいが]の夜[よる]',
      titleEn: 'Movie night',
      lines: [
        ['', '金曜日[きんようび]の夜[よる]は、映画[えいが]の夜[よる]です。', 'Friday night is movie night.'],
        ['ユキ', '今日[きょう]は何[なに]を見[み]る？', 'What shall we watch today?'],
        ['ケン', 'スター・ウォーズ！フォースと共[とも]にあらんことを。', 'Star Wars! May the Force be with you.'],
        ['ユキ', 'また？私[わたし]は昔[むかし]の映画[えいが]がいいな。', 'Again? I want an old film.'],
        ['', '二人[ふたり]は「カサブランカ」を見[み]ました。', 'They watched Casablanca.'],
        ['', '最後[さいご]に、ケンがジュースのグラスを上[あ]げました。', 'At the end, Ken raised his glass of juice.'],
        ['ケン', '君[きみ]の瞳[ひとみ]に乾杯[かんぱい]。', 'Here\'s looking at you.'],
        ['ユキ', '…ちょっと恥[は]ずかしい。', '…That\'s a bit embarrassing.'],
        ['', 'トイレに行[い]くとき、ケンは振[ふ]り向[む]いて言[い]いました。', 'On his way to the toilet, Ken turned round and said:'],
        ['ケン', 'アイル・ビー・バック。', 'I\'ll be back.'],
      ],
    },
    buzzwords: {
      title: 'おじいちゃんと流行語[りゅうこうご]',
      titleEn: 'Grandpa\'s buzzwords',
      lines: [
        ['', 'おじいちゃんは流行語[りゅうこうご]が大好[だいす]きです。でも、ちょっと古[ふる]いです。', 'Grandpa loves buzzwords. But they\'re a little old.'],
        ['ケン', '宿題[しゅくだい]、いつやろうかな。', 'When should I do my homework…'],
        ['おじいちゃん', 'いつやるか？今[いま]でしょ！', 'When will you do it? Now, obviously!'],
        ['ケン', '今日[きょう]、ゲームで三回[さんかい]連続[れんぞく]で勝[か]ったよ！', 'I won three games in a row today!'],
        ['おじいちゃん', '神[かみ]ってるね！', 'You\'re on fire!'],
        ['', 'おばあちゃんがケーキの写真[しゃしん]を撮[と]っています。', 'Grandma is taking a photo of a cake.'],
        ['おじいちゃん', 'インスタ映[ば]えだね。', 'Very Instagrammable.'],
        ['ケン', 'おじいちゃん、すごいね。', 'Grandpa, you\'re amazing.'],
        ['おじいちゃん', 'ワイルドだろぉ？', 'Pretty wild, huh?'],
        ['おばあちゃん', 'そだねー。', 'Yeah, that\'s right~'],
      ],
    },
    shops: {
      title: '夜[よる]のコンビニ',
      titleEn: 'The konbini at night',
      lines: [
        ['', '夜[よる]十時[じゅうじ]、メアリーはコンビニに入[はい]りました。', 'At ten at night, Mary went into a convenience store.'],
        ['店員[てんいん]', 'いらっしゃいませ！', 'Welcome!'],
        ['', 'メアリーはお弁当[べんとう]とお茶[ちゃ]を買[か]いました。', 'Mary bought a bento and some tea.'],
        ['店員[てんいん]', 'お弁当[べんとう]、温[あたた]めますか？', 'Shall I heat up your bento?'],
        ['メアリー', 'はい、お願[ねが]いします。', 'Yes, please.'],
        ['店員[てんいん]', 'ポイントカードはお持[も]ちですか？', 'Do you have a points card?'],
        ['メアリー', '大丈夫[だいじょうぶ]です。', 'No, thanks.'],
        ['店員[てんいん]', '袋[ふくろ]はご利用[りよう]ですか？', 'Will you be using a bag?'],
        ['メアリー', 'いいえ、自分[じぶん]のがあります。', 'No, I have my own.'],
        ['店員[てんいん]', 'ありがとうございました！', 'Thank you!'],
        ['', '家[いえ]に着[つ]いて、メアリーは気[き]がつきました。お箸[はし]がない！', 'At home, Mary noticed: no chopsticks!'],
      ],
    },
    trains: {
      title: '終電[しゅうでん]',
      titleEn: 'The last train',
      lines: [
        ['', '夜[よる]十一時[じゅういちじ]半[はん]、ケンは駅[えき]へ走[はし]っています。', 'Half past eleven at night. Ken is running to the station.'],
        ['アナウンス', 'まもなく、1番線[ばんせん]に電車[でんしゃ]がまいります。', 'A train will shortly arrive at platform 1.'],
        ['ケン', '間[ま]に合[あ]え！', 'Make it!'],
        ['アナウンス', 'ドアが閉[し]まります。ご注意[ちゅうい]ください。', 'The doors are closing. Please be careful.'],
        ['', 'ケンはドアに飛[と]び込[こ]みました。', 'Ken dived through the doors.'],
        ['アナウンス', '駆[か]け込[こ]み乗車[じょうしゃ]は危険[きけん]ですので、おやめください。', 'Rushing onto the train is dangerous, so please don\'t.'],
        ['ケン', 'すみません…', 'Sorry…'],
        ['', '電車[でんしゃ]の中[なか]で、ケンは寝[ね]てしまいました。', 'On the train, Ken fell asleep.'],
        ['アナウンス', '終点[しゅうてん]です。お忘[わす]れ物[もの]のないよう、ご注意[ちゅうい]ください。', 'This is the last stop. Please make sure you haven\'t left anything behind.'],
        ['ケン', '…ここ、どこ？', '…Where am I?'],
      ],
    },
    chants: {
      title: '夏祭[なつまつ]り',
      titleEn: 'The summer festival',
      lines: [
        ['', '八月[はちがつ]、町[まち]でお祭[まつ]りがありました。', 'In August there was a festival in town.'],
        ['', '男[おとこ]の人[ひと]たちが、神輿[みこし]をかついでいます。', 'Men are carrying a portable shrine.'],
        ['みんな', 'わっしょい！わっしょい！', 'Wasshoi! Wasshoi!'],
        ['', 'ユキとケンは、たこ焼[や]きを買[か]いました。最後[さいご]の一[ひと]つをかけて、じゃんけんです。', 'Yuki and Ken bought takoyaki. They played rock-paper-scissors for the last one.'],
        ['二人[ふたり]', 'じゃんけんぽん！あいこでしょ！', 'Rock, paper, scissors! A tie, so again!'],
        ['ケン', '負[ま]けた…', 'I lost…'],
        ['ユキ', 'ドンマイ！', 'Never mind!'],
        ['', '夜[よる]九時[くじ]、空[そら]に大[おお]きな花火[はなび]が上[あ]がりました。', 'At nine, a huge firework burst in the sky.'],
        ['みんな', 'たーまやー！', 'Ta-ma-ya!'],
      ],
    },
    onomatopoeia: {
      title: '音[おと]のある日曜日[にちようび]',
      titleEn: 'A Sunday in sounds',
      lines: [
        ['', '日曜日[にちようび]の朝[あさ]、外[そと]は雨[あめ]がザーザー降[ふ]っています。', 'Sunday morning. Outside, it\'s pouring.'],
        ['', 'ユキはふとんの中[なか]で、ゴロゴロしています。', 'Yuki is lazing around under the covers.'],
        ['', '猫[ねこ]のモモが来[き]ました。もふもふで、あたたかいです。', 'Momo the cat comes over — fluffy and warm.'],
        ['', '昼[ひる]、おなかがペコペコになりました。', 'By noon, she\'s starving.'],
        ['', 'ユキはふわふわのパンケーキを作[つく]って、もぐもぐ食[た]べました。', 'Yuki makes fluffy pancakes and munches them.'],
        ['', '明日[あした]の旅行[りょこう]のことを考[かんが]えると、わくわくします。', 'Thinking about tomorrow\'s trip, she gets excited.'],
        ['', 'でも、急[きゅう]に宿題[しゅくだい]を思[おも]い出[だ]しました。', 'But suddenly she remembers her homework.'],
        ['ユキ', 'ガーン！', '(Shock!)'],
        ['', '部屋[へや]は、シーン…', 'The room goes dead silent…'],
      ],
    },
    fandom: {
      title: 'コンサートの日[ひ]',
      titleEn: 'Concert day',
      lines: [
        ['', 'ユキの推[お]しは、アイドルグループのレンくんです。', 'Yuki\'s fave is Ren from an idol group.'],
        ['', 'コンサートの日[ひ]、ユキは朝[あさ]五時[ごじ]に起[お]きました。', 'On concert day, Yuki got up at five in the morning.'],
        ['ユキ', '今日[きょう]は一日中[いちにちじゅう]、推[お]し活[かつ]！', 'Fan activities all day today!'],
        ['', 'ステージの上[うえ]から、レンくんが手[て]を振[ふ]りました。', 'From the stage, Ren waved.'],
        ['ユキ', '推[お]しが尊[とうと]い…', 'My fave is so precious…'],
        ['友達[ともだち]', 'ユキ、ほかのメンバーも好[す]きでしょ？', 'Yuki, you like the other members too, right?'],
        ['ユキ', 'うん、実[じつ]は箱推[はこお]しです。', 'Yeah — actually I support the whole box.'],
        ['', '帰[かえ]りの電車[でんしゃ]で、友達[ともだち]が新[あたら]しいアニメの話[はなし]を始[はじ]めました。', 'On the train home, her friend started talking about a new anime.'],
        ['ユキ', 'ネタバレ禁止[きんし]！まだ見[み]てない！', 'No spoilers! I haven\'t seen it yet!'],
        ['', '次[つぎ]の週[しゅう]、ユキはそのアニメの沼[ぬま]にハマりました。', 'The next week, Yuki fell into that anime\'s swamp.'],
      ],
    },
    comedians: {
      title: '文化祭[ぶんかさい]の漫才[まんざい]',
      titleEn: 'Comedy at the school festival',
      lines: [
        ['', '文化祭[ぶんかさい]で、ケンとタロウは漫才[まんざい]をしました。', 'At the school festival, Ken and Taro did a comedy double act.'],
        ['タロウ', 'ぼく、朝[あさ]ごはんはいつもパンとコーヒーなんです。', 'I always have bread and coffee for breakfast.'],
        ['ケン', '欧米[おうべい]か！', 'What, are you Western?!'],
        ['タロウ', '今日[きょう]、宿題[しゅくだい]を忘[わす]れました。でも…', 'I forgot my homework today. But…'],
        ['二人[ふたり]', 'そんなの関係[かんけい]ねぇ！', 'That\'s got nothing to do with it!'],
        ['', '誰[だれ]も笑[わら]いません。会場[かいじょう]はシーン…', 'Nobody laughs. Dead silence in the hall…'],
        ['タロウ', 'なんでだろう〜', 'Why is that~'],
        ['ケン', 'ちょっと何[なに]言[い]ってるかわからない。', 'I don\'t quite get what you\'re saying.'],
        ['', '最後[さいご]に、先生[せんせい]だけが親指[おやゆび]を上[あ]げました。', 'At the end, only the teacher gave a thumbs-up.'],
        ['先生[せんせい]', 'グ〜！', 'Goo~!'],
      ],
    },
    songs: {
      title: 'カラオケの夜[よる]',
      titleEn: 'Karaoke night',
      lines: [
        ['', '金曜日[きんようび]の夜[よる]、会社[かいしゃ]の四人[よにん]でカラオケに行[い]きました。', 'On Friday night, four people from work went to karaoke.'],
        ['', '最初[さいしょ]にユキが「夜[よる]に駆[か]ける」を歌[うた]いました。速[はや]くて難[むずか]しい歌[うた]です。', 'First Yuki sang "Racing into the Night" — a fast, hard song.'],
        ['', '次[つぎ]に、ケンが「残酷[ざんこく]な天使[てんし]のテーゼ」を歌[うた]うと、みんなも一緒[いっしょ]に歌[うた]いました。', 'Then Ken sang "A Cruel Angel\'s Thesis", and everyone joined in.'],
        ['', 'メアリーは「上[うえ]を向[む]いて歩[ある]こう」を歌[うた]いました。', 'Mary sang "Ue o Muite Arukō".'],
        ['', 'とてもきれいな声[こえ]で、みんな拍手[はくしゅ]しました。', 'Her voice was beautiful, and everyone clapped.'],
        ['', '最後[さいご]は部長[ぶちょう]の番[ばん]です。部長[ぶちょう]はマイクを持[も]って、立[た]ち上[あ]がりました。', 'Finally it\'s the boss\'s turn. He takes the mic and stands up.'],
        ['部長[ぶちょう]', 'ペンパイナッポーアッポーペン！', 'Pen-Pineapple-Apple-Pen!'],
        ['みんな', '…部長[ぶちょう]、それ、短[みじか]すぎます！', '…Boss, that one\'s way too short!'],
      ],
    },
    kidstv: {
      title: '日曜日[にちようび]の夕方[ゆうがた]',
      titleEn: 'Sunday evening TV',
      lines: [
        ['', '日曜日[にちようび]の夕方[ゆうがた]、ハナは家族[かぞく]とテレビを見[み]ます。', 'On Sunday evening, Hana watches TV with her family.'],
        ['', '弟[おとうと]のソウタは、まだ一歳[いっさい]です。', 'Her little brother Sota is only one.'],
        ['ハナ', 'いないいない、ばあ！', 'Peekaboo!'],
        ['', 'ソウタはキャッキャと笑[わら]いました。', 'Sota squealed with laughter.'],
        ['', 'テレビで、アンパンマンの顔[かお]がぬれてしまいました。', 'On TV, Anpanman\'s face got wet.'],
        ['テレビ', 'アンパンマン、新[あたら]しい顔[かお]よ！', 'Anpanman, here\'s your new face!'],
        ['テレビ', '元気[げんき]100倍[ばい]、アンパンマン！', 'A hundred times the energy — Anpanman!'],
        ['', '次[つぎ]は「サザエさん」です。最後[さいご]にじゃんけんがあります。', 'Next is Sazae-san. It ends with rock-paper-scissors.'],
        ['テレビ', '来週[らいしゅう]もまた見[み]てくださいね！じゃんけんぽん！', 'Watch again next week! Rock, paper, scissors!'],
        ['', 'ハナはグーを出[だ]して…負[ま]けました。', 'Hana threw rock… and lost.'],
        ['ハナ', 'ああ、明日[あした]は月曜日[げつようび]か…', 'Ugh, tomorrow\'s Monday…'],
      ],
    },
    work: {
      title: 'ほうれんそう',
      titleEn: 'Spinach',
      lines: [
        ['', '金曜日[きんようび]の朝[あさ]、ケンはメールを書[か]いています。', 'Friday morning. Ken is writing an email.'],
        ['ケン', 'いつもお世話[せわ]になっております。', 'Thank you as always for your support.'],
        ['部長[ぶちょう]', 'ケンくん、この資料[しりょう]、月曜日[げつようび]までにお願[ねが]い。', 'Ken, I need this report by Monday.'],
        ['ケン', '承知[しょうち]しました。', 'Understood.'],
        ['先輩[せんぱい]', 'ほうれんそうを忘[わす]れずにね。', 'Don\'t forget your spinach.'],
        ['', '昼[ひる]、ケンはほうれんそうのサラダを買[か]ってきました。', 'At lunch, Ken came back with a spinach salad.'],
        ['先輩[せんぱい]', '…そっちのほうれんそうじゃないよ。', '…Not that kind of spinach.'],
        ['', '六時[ろくじ]になりました。', 'Six o\'clock came.'],
        ['ケン', '今日[きょう]は花金[はなきん]だ！定時[ていじ]で帰[かえ]ります！', 'It\'s flower Friday! I\'m leaving on the dot!'],
        ['みんな', 'お疲[つか]れさまでした！', 'Good work today!'],
      ],
    },
    food: {
      title: '居酒屋[いざかや]で',
      titleEn: 'At the izakaya',
      lines: [
        ['', '仕事[しごと]のあと、四人[よにん]で居酒屋[いざかや]に行[い]きました。', 'After work, four of them went to an izakaya.'],
        ['店員[てんいん]', 'ご注文[ちゅうもん]は？', 'What would you like?'],
        ['みんな', 'とりあえずビール！', 'Beer, for starters!'],
        ['', 'メアリーは熱[あつ]いたこ焼[や]きを食[た]べました。', 'Mary ate a hot takoyaki.'],
        ['メアリー', 'あつっ！私[わたし]、猫舌[ねこじた]なんです。', 'Hot! I have a cat\'s tongue.'],
        ['先輩[せんぱい]', 'ケンくん、いい食[た]べっぷりだね！', 'Ken, you really eat with gusto!'],
        ['', '十時[じゅうじ]、みんなおなかがいっぱいです。でも、メアリーはアイスを頼[たの]みました。', 'At ten, everyone is full. But Mary orders ice cream.'],
        ['メアリー', 'デザートは別腹[べつばら]です。', 'Dessert goes in a separate stomach.'],
        ['ケン', 'じゃあ、シメはラーメンで！', 'Then let\'s finish with ramen!'],
        ['みんな', 'まだ食[た]べるの？', 'You\'re still eating?!'],
      ],
    },
    kotowaza: {
      title: 'おばあちゃんのことわざ',
      titleEn: 'Grandma\'s proverbs',
      lines: [
        ['', 'ケンのおばあちゃんは、いつもことわざで話[はな]します。', 'Ken\'s grandma always talks in proverbs.'],
        ['ケン', 'テスト、また悪[わる]かった…', 'I did badly on the test again…'],
        ['おばあちゃん', '七転[ななころ]び八起[やお]きだよ。', 'Fall down seven times, get up eight.'],
        ['ケン', '今日[きょう]、先生[せんせい]が漢字[かんじ]を間違[まちが]えたんだ。', 'The teacher wrote a kanji wrong today.'],
        ['おばあちゃん', '猿[さる]も木[き]から落[お]ちる。', 'Even monkeys fall from trees.'],
        ['', 'ケンは近道[ちかみち]をして、道[みち]に迷[まよ]いました。', 'Ken took a shortcut and got lost.'],
        ['おばあちゃん', '急[いそ]がば回[まわ]れ。', 'If you\'re in a hurry, go the long way round.'],
        ['', 'お花見[はなみ]で、ケンは桜[さくら]を見[み]ないで、お団子[だんご]ばかり食[た]べました。', 'At the cherry-blossom party, Ken ignored the blossoms and just ate dumplings.'],
        ['おばあちゃん', '花[はな]より団子[だんご]だね。', 'Dumplings over flowers.'],
        ['ケン', 'おばあちゃん、ことわざ多[おお]すぎるよ！', 'Grandma, way too many proverbs!'],
        ['おばあちゃん', '笑[わら]う門[かど]には福[ふく]来[きた]る！', 'Luck comes to the gate where people laugh!'],
      ],
    },
    quotes: {
      title: '歴史[れきし]の授業[じゅぎょう]',
      titleEn: 'History class',
      lines: [
        ['先生[せんせい]', 'ホトトギスが鳴[な]かないとき、みんなはどうしますか？', 'If a cuckoo won\'t sing, what would you do?'],
        ['タロウ', '鳴[な]かぬなら鳴[な]くまで待[ま]とうホトトギス。ぼくは待[ま]ちます。', 'If it won\'t sing, wait till it does. I\'d wait.'],
        ['ユキ', '鳴[な]かぬなら鳴[な]かせてみようホトトギス。歌[うた]を教[おし]えます！', 'If it won\'t sing, make it sing. I\'d teach it a song!'],
        ['ケン', 'うーん…スマホで鳴[な]き声[ごえ]を流[なが]します。', 'Hmm… I\'d play a recording on my phone.'],
        ['先生[せんせい]', '…新[あたら]しいですね。', '…That\'s a new one.'],
        ['', '授業[じゅぎょう]の最後[さいご]に、先生[せんせい]は黒板[こくばん]に書[か]きました。', 'At the end of class, the teacher wrote on the blackboard:'],
        ['先生[せんせい]', '少年[しょうねん]よ、大志[たいし]を抱[いだ]け。', 'Boys, be ambitious.'],
        ['ケン', '先生[せんせい]、ぼくの大志[たいし]は、昼[ひる]ごはんです。', 'Sir, my ambition is lunch.'],
      ],
    },
    literature: {
      title: '猫[ねこ]の文学[ぶんがく]',
      titleEn: 'The literary cat',
      lines: [
        ['', 'うちの猫[ねこ]のタマは、毎朝[まいあさ]、窓[まど]の外[そと]を見[み]ています。', 'Our cat Tama looks out of the window every morning.'],
        ['', 'ある日[ひ]、タマのノートを見[み]つけました。一[いち]ページ目[め]にこう書[か]いてありました。', 'One day I found Tama\'s notebook. On the first page it said:'],
        ['タマ', '吾輩[わがはい]は猫[ねこ]である。名前[なまえ]はまだ無[な]い。', 'I am a cat. As yet I have no name.'],
        ['私[わたし]', '名前[なまえ]、あるよ！タマでしょ！', 'You do have a name! It\'s Tama!'],
        ['', '次[つぎ]のページには、俳句[はいく]がありました。', 'On the next page there was a haiku.'],
        ['タマ', '古池[ふるいけ]や　猫[ねこ]飛[と]び込[こ]む　水[みず]の音[おと]', 'An old pond — a cat jumps in — the sound of water.'],
        ['', 'その時[とき]、庭[にわ]から大[おお]きな音[おと]がしました。', 'Just then, there was a loud noise from the garden.'],
        ['', 'タマはびしょびしょになって帰[かえ]ってきました。', 'Tama came back soaking wet.'],
        ['私[わたし]', '…春[はる]はあけぼの、猫[ねこ]はびしょびしょ。', '…In spring, the dawn. In the pond, the cat.'],
      ],
    },
    kansai: {
      title: '大阪[おおさか]のたこ焼[や]き屋[や]',
      titleEn: 'The Osaka takoyaki stand',
      lines: [
        ['', 'メアリーは大阪[おおさか]に旅行[りょこう]に行[い]きました。', 'Mary went on a trip to Osaka.'],
        ['おじさん', 'いらっしゃい！うちのたこ焼[や]き、めっちゃおいしいで！', 'Welcome! My takoyaki are super tasty!'],
        ['メアリー', '一[ひと]つください。…あつい！でも、めっちゃおいしい！', 'One, please. …Hot! But super tasty!'],
        ['おじさん', 'せやろ？', 'Told ya.'],
        ['メアリー', '大阪[おおさか]の人[ひと]は、みんな面白[おもしろ]いんですか？', 'Is everyone in Osaka funny?'],
        ['おじさん', 'ちゃうちゃう。わしは普通[ふつう]や。', 'No, no. I\'m just ordinary.'],
        ['', 'その時[とき]、風[かぜ]でおじさんの帽子[ぼうし]が飛[と]んで、たこ焼[や]きの上[うえ]に落[お]ちました。', 'Just then, the wind blew his hat right onto the takoyaki.'],
        ['お客[きゃく]さん', 'なんでやねん！', 'Why on earth?!'],
        ['メアリー', 'ほんまに面白[おもしろ]い…', 'Really, so funny…'],
        ['おじさん', 'おおきに！また来[き]てな！', 'Thanks! Come again!'],
      ],
    },
    love: {
      title: '月[つき]が綺麗[きれい]ですね',
      titleEn: 'The moon is beautiful',
      lines: [
        ['', 'ケンとユキは、夜[よる]の公園[こうえん]を歩[ある]いています。', 'Ken and Yuki are walking through the park at night.'],
        ['', 'ケンはとても緊張[きんちょう]しています。', 'Ken is very nervous.'],
        ['ケン', 'ユキさん…つ、月[つき]が綺麗[きれい]ですね。', 'Yuki… th-the moon is beautiful, isn\'t it?'],
        ['ユキ', 'え？今日[きょう]、くもりだよ。', 'Huh? It\'s cloudy tonight.'],
        ['', '空[そら]を見[み]ると、月[つき]はどこにもありません。', 'They look up. There\'s no moon anywhere.'],
        ['ケン', '…あの、好[す]きです。付[つ]き合[あ]ってください！', '…Um, I like you. Please go out with me!'],
        ['ユキ', '最初[さいしょ]からそう言[い]ってよ。…うん、いいよ。', 'Should have said that in the first place. …Yes, OK.'],
        ['', 'ケンの顔[かお]は真[ま]っ赤[か]になりました。', 'Ken\'s face went bright red.'],
        ['ユキ', '胸[むね]キュン！', 'Heart-squeeze!'],
      ],
    },
    smalltalk: {
      title: 'となりの田中[たなか]さん',
      titleEn: 'Mrs Tanaka next door',
      lines: [
        ['', 'となりの田中[たなか]さんは、会[あ]うといつも季節[きせつ]の話[はなし]をします。', 'Mrs Tanaka next door always talks about the season when we meet.'],
        ['田中[たなか]さん', '花粉症[かふんしょう]がつらいですねえ。', 'My hay fever is awful.'],
        ['', 'それは三月[さんがつ]でした。六月[ろくがつ]には…', 'That was in March. In June…'],
        ['田中[たなか]さん', '梅雨[つゆ]入[い]りしましたね。', 'The rainy season has started.'],
        ['', '八月[はちがつ]には…', 'In August…'],
        ['田中[たなか]さん', '暑[あつ]いですねえ。夏[なつ]バテしちゃった。', 'Hot, isn\'t it? The heat has worn me out.'],
        ['', '十一月[じゅういちがつ]には…', 'In November…'],
        ['田中[たなか]さん', '紅葉[こうよう]がきれいですね。', 'The autumn leaves are beautiful.'],
        ['', '一月[いちがつ]、田中[たなか]さんは外[そと]に出[で]てきませんでした。こたつから出[で]られないそうです。', 'In January, Mrs Tanaka didn\'t come out. Apparently she can\'t get out of the kotatsu.'],
        ['', '一年後[いちねんご]、気[き]がつくと私[わたし]も同[おな]じ話[はなし]をしています。', 'A year later, I realise I talk exactly the same way.'],
      ],
    },
  };
})(typeof window !== 'undefined' ? window : globalThis);
