(function (global) {
  'use strict';

  // Fun words and sentences for the Phrases page (phrases.html), one group
  // per category: ad slogans, anime and Ghibli lines, game messages, words of
  // the year, what to say on birthdays and at weddings, festival chants…
  //
  //   jp    — the phrase, with furigana as 漢字[かんじ] after every kanji run
  //           (the same markup as the stories). The 🔊 buttons read the
  //           furigana in place of the kanji, so every kanji needs one.
  //   en    — what it means
  //   note  — where it comes from, or when to say it
  //
  // test_phrases.js checks the markup and that every field is filled in.

  global.PHRASES_DATA = [
    {
      id: 'slogans',
      emoji: '📺',
      title: '有名[ゆうめい]なキャッチコピー',
      titleEn: 'Famous ad slogans',
      blurb: 'Jingles and taglines every Japanese person can finish for you.',
      phrases: [
        { jp: 'お、ねだん以上[いじょう]。ニトリ', en: 'Oh — more than the price. Nitori.', note: 'Furniture chain Nitori\'s jingle. The お、 at the start is both "oh!" and the polite prefix of お値段 (price) — a tiny pun.' },
        { jp: 'やめられない、とまらない、かっぱえびせん', en: 'Can\'t quit, can\'t stop — Kappa Ebisen.', note: 'Calbee\'s shrimp crackers, since the 1960s. People quote it about anything addictive.' },
        { jp: 'そうだ 京都[きょうと]、行[い]こう。', en: 'I know — let\'s go to Kyoto.', note: 'JR Central\'s travel campaign since 1993. Swap in any place: そうだ 温泉、行こう。' },
        { jp: 'インテル、入[はい]ってる', en: 'Intel — it\'s inside.', note: 'Japan\'s version of "Intel Inside": インテル and 入ってる (hai-tteru) rhyme.' },
        { jp: '100人[にん]乗[の]っても大丈夫[だいじょうぶ]！', en: 'Even with 100 people on it, it\'s fine!', note: 'Inaba garden sheds: the ad shows a crowd of 100 people standing on the roof.' },
        { jp: 'セブン-イレブン、いい気分[きぶん]', en: 'Seven-Eleven — feeling good.', note: 'The convenience store\'s classic jingle: イレブン and 気分 (kibun) rhyme.' },
        { jp: 'あなたと、コンビに、ファミリーマート', en: 'You and me — at the convenience store — FamilyMart.', note: 'A pun: コンビに means both "as a pair (コンビ)" and "at the コンビニ".' },
        { jp: 'ファイト！一発[いっぱつ]！', en: 'Fight! One shot!', note: 'Lipovitan D energy drink: two men clinging to a cliff shout it as one pulls the other up.' },
        { jp: '24時間[じかん]戦[たたか]えますか', en: 'Can you fight for 24 hours?', note: 'Regain energy drink, 1989 — the bubble-era salaryman anthem. Quoted today with a sigh.' },
        { jp: '元気[げんき]ハツラツ！オロナミンC', en: 'Full of beans! Oronamin C.', note: 'The little brown bottle of fizzy vitamin drink. ハツラツ = lively, bursting with energy.' },
        { jp: 'お口[くち]の恋人[こいびと]、ロッテ', en: 'Your mouth\'s sweetheart — Lotte.', note: 'The gum and chocolate maker\'s slogan for decades.' },
        { jp: 'カラダにピース。カルピス', en: 'Peace for your body. Calpis.', note: 'ピース (peace) rhymes with ピス in カルピス.' },
        { jp: '目[め]のつけどころが、シャープでしょ。', en: 'Our eye for detail is sharp, right?', note: 'Electronics maker Sharp: 目のつけどころがシャープ "a sharp way of looking at things".' },
        { jp: 'おしりだって、洗[あら]ってほしい。', en: 'Bottoms want washing too.', note: 'TOTO\'s 1982 ad that made the Washlet bidet toilet famous.' },
        { jp: 'うまい、やすい、はやい', en: 'Tasty, cheap, fast.', note: 'Yoshinoya\'s promise for its beef bowls (the order of the three has changed over the years). Now used for anything good and quick.' },
        { jp: 'リンゴとハチミツ、とろ〜り溶[と]けてる', en: 'Apples and honey, melting in nice and gooey.', note: 'House Vermont Curry — the mild curry Japanese kids grow up on.' },
        { jp: 'ピッカピカの一年生[いちねんせい]', en: 'Shiny new first-graders.', note: 'Shogakukan\'s magazine ads showing kids about to start school. ピカピカ = sparkling new.' },
        { jp: '亭主[ていしゅ]元気[げんき]で留守[るす]がいい', en: 'Best when the husband\'s healthy — and out.', note: 'A 1986 ad for wardrobe insect repellent that became a buzzword for bored housewives.' },
        { jp: 'スカッとさわやか、コカ・コーラ', en: 'Crisp and refreshing — Coca-Cola.', note: 'Coke\'s Japanese slogan from the 1960s–80s. スカッと = the feeling of a fizzy, clean hit.' },
        { jp: 'わんぱくでもいい、たくましく育[そだ]ってほしい', en: 'Naughty\'s fine — just grow up strong.', note: 'Marudai ham, 1970s: a boy bites into a huge ham on the bone.' },
      ],
    },
    {
      id: 'occasions',
      emoji: '🎉',
      title: '特別[とくべつ]な日[ひ]のことば',
      titleEn: 'Special occasions',
      blurb: 'What to write on the card or say at the party.',
      phrases: [
        { jp: 'あけましておめでとうございます！', en: 'Happy New Year!', note: 'Only from 1 January on. Before midnight you say よいお年を instead. Casual: あけおめ！' },
        { jp: '今年[ことし]もよろしくお願[ねが]いします。', en: 'Please be good to me again this year.', note: 'Always follows the New Year greeting. Casual: ことよろ！' },
        { jp: 'よいお年[とし]を！', en: 'Have a good year (ahead)!', note: 'The last time you see someone before New Year.' },
        { jp: 'お誕生日[たんじょうび]おめでとう！', en: 'Happy birthday!', note: 'Add ございます to be polite. Kids also sing ハッピーバースデー in English.' },
        { jp: 'ご結婚[けっこん]おめでとうございます。', en: 'Congratulations on your marriage.', note: 'At weddings avoid "cutting" words like 切れる or 別れる, and repeated words like 重ね重ね.' },
        { jp: '末永[すえなが]くお幸[しあわ]せに。', en: 'May you be happy for ever and ever.', note: 'The classic line to end a wedding message.' },
        { jp: 'ご卒業[そつぎょう]おめでとうございます。', en: 'Congratulations on graduating.', note: 'School years end in March, so this is a spring phrase — with cherry blossoms.' },
        { jp: '合格[ごうかく]おめでとう！', en: 'Congrats on passing!', note: 'For entrance exams — and the JLPT. Students buy キットカット as a lucky charm: きっと勝つ "you\'ll surely win".' },
        { jp: '成人[せいじん]おめでとう！', en: 'Congrats on coming of age!', note: 'Coming-of-Age Day (成人の日), the second Monday of January: young people in kimono and suits.' },
        { jp: 'メリークリスマス！', en: 'Merry Christmas!', note: 'Christmas Eve is a date night in Japan, and the traditional meal is KFC and strawberry shortcake.' },
        { jp: 'ハッピーハロウィン！トリック・オア・トリート！', en: 'Happy Halloween! Trick or treat!', note: 'Mostly a costume party for grown-ups — Shibuya fills with zombies and Marios.' },
        { jp: 'これ、義理[ぎり]チョコです。', en: 'This is obligation chocolate.', note: 'On Valentine\'s Day women give chocolate: 本命チョコ for the one you love, 義理チョコ for coworkers. Men pay back on White Day, 14 March.' },
        { jp: 'お母[かあ]さん、いつもありがとう。', en: 'Mum, thanks for everything.', note: 'The standard Mother\'s Day card, with a red carnation.' },
        { jp: 'いつまでも長生[ながい]きしてね。', en: 'Please live a long, long life.', note: 'For grandparents on Respect for the Aged Day (敬老の日) in September.' },
        { jp: 'お大事[だいじ]に。', en: 'Take care (of yourself).', note: 'To someone who\'s ill — doctors and pharmacists say it as you leave.' },
        { jp: '暑中[しょちゅう]お見舞[みま]い申[もう]し上[あ]げます。', en: 'Wishing you well in the summer heat.', note: 'The opening of a summer greeting card, sent in July and August.' },
        { jp: 'お年玉[としだま]ちょうだい！', en: 'Give me my New Year money!', note: 'Kids get お年玉 — cash in little envelopes — from relatives at New Year.' },
        { jp: '背[せ]が高[たか]くなりますように。', en: 'I hope I get taller.', note: 'A Tanabata wish (7 July), written on a paper strip and tied to bamboo. 〜ますように = "may…".' },
      ],
    },
    {
      id: 'everyday',
      emoji: '🙇',
      title: '毎日[まいにち]の決[き]まり文句[もんく]',
      titleEn: 'Everyday set phrases',
      blurb: 'Little phrases with no real English translation — Japan runs on them.',
      phrases: [
        { jp: 'いただきます！', en: '(I humbly receive.)', note: 'Before eating, hands together. Thanks to everyone — and everything — that made the meal.' },
        { jp: 'ごちそうさまでした。', en: 'That was a feast.', note: 'After eating. Say it to the cook, or to the staff as you leave a small restaurant.' },
        { jp: 'いってきます！', en: 'I\'m off (and I\'ll be back)!', note: 'Leaving home. The family answers いってらっしゃい！' },
        { jp: 'ただいま！', en: 'I\'m home!', note: 'Coming home. The answer: おかえり（なさい）！' },
        { jp: 'お疲[つか]れさまです。', en: 'You must be tired (thanks for your work).', note: 'The all-purpose work greeting: hello, goodbye and thank you in one.' },
        { jp: 'よろしくお願[ねが]いします。', en: 'Please treat me well.', note: 'After introducing yourself, asking a favour, starting anything together.' },
        { jp: 'お先[さき]に失礼[しつれい]します。', en: 'Excuse me for leaving before you.', note: 'Leaving the office while others are still working.' },
        { jp: 'お邪魔[じゃま]します。', en: 'I\'m going to disturb you.', note: 'Stepping into someone\'s home. When you leave: お邪魔しました。' },
        { jp: 'いえいえ、とんでもないです。', en: 'No, no, not at all.', note: 'The polite way to brush off a compliment. Accepting it straight sounds boastful.' },
        { jp: 'つまらないものですが…', en: 'It\'s just a boring little thing, but…', note: 'Said while handing over a gift. Nowadays many people say ほんの気持ちですが "just a token" instead.' },
        { jp: 'しょうがない。', en: 'It can\'t be helped.', note: 'Rain on the picnic, a missed train, life. Also しかたない.' },
        { jp: '気[き]をつけて！', en: 'Take care! / Watch out!', note: 'When someone leaves, or is about to trip over something.' },
      ],
    },
    {
      id: 'anime',
      emoji: '⚡',
      title: 'アニメ・漫画[まんが]の名[めい]セリフ',
      titleEn: 'Anime & manga lines',
      blurb: 'Catchphrases fans shout at each other.',
      phrases: [
        { jp: '海賊王[かいぞくおう]に、おれはなる！', en: 'I\'m gonna be King of the Pirates!', note: 'Luffy, One Piece — the series\' first big promise.' },
        { jp: '真実[しんじつ]はいつもひとつ！', en: 'There is only ever one truth!', note: 'Detective Conan, pointing at the culprit.' },
        { jp: 'あれれ〜？おかしいぞ〜？', en: 'Huh~? That\'s weird~?', note: 'Conan playing the innocent kid while dropping a clue for the adults.' },
        { jp: 'じっちゃんの名[な]にかけて！', en: 'On my grandpa\'s name!', note: 'Kindaichi Case Files: his grandfather was the famous detective Kosuke Kindaichi.' },
        { jp: '月[つき]に代[か]わって、おしおきよ！', en: 'In the name of the moon, I\'ll punish you!', note: 'Sailor Moon. Literally "standing in for the moon".' },
        { jp: 'かめはめ波[は]ー！', en: 'Kamehameha wave!', note: 'Goku\'s signature attack, Dragon Ball — named after the Hawaiian king.' },
        { jp: 'クリリンのことかーっ！', en: 'You mean Krillin?!', note: 'Goku turning Super Saiyan for the first time. Used when something makes you snap.' },
        { jp: 'お前[まえ]のものはおれのもの、おれのものもおれのもの。', en: 'What\'s yours is mine, and what\'s mine is mine too.', note: 'Gian, the bully in Doraemon. Japan\'s name for this attitude: ジャイアニズム.' },
        { jp: 'のび太[た]のくせに、生意気[なまいき]だぞ！', en: 'You\'re just Nobita — don\'t get cocky!', note: 'Gian again. 〜のくせに = "for someone who\'s only…".' },
        { jp: '親父[おやじ]にもぶたれたことないのに！', en: 'Not even my father ever hit me!', note: 'Amuro, Mobile Suit Gundam (1979), after being slapped.' },
        { jp: '立[た]て、立[た]つんだジョー！', en: 'Get up — get up, Joe!', note: 'The coach in the boxing manga Ashita no Joe. Quoted to anyone on the floor.' },
        { jp: '心[こころ]を燃[も]やせ。', en: 'Set your heart ablaze.', note: 'Rengoku, Demon Slayer (鬼滅の刃).' },
        { jp: '全集中[ぜんしゅうちゅう]！', en: 'Total concentration!', note: 'The breathing technique in Demon Slayer. Kids say it before a test.' },
        { jp: '領域[りょういき]展開[てんかい]。', en: 'Domain expansion.', note: 'Jujutsu Kaisen\'s ultimate technique — and a meme for taking over a room.' },
        { jp: '私[わたし]が来[き]た！', en: 'I am here!', note: 'All Might, My Hero Academia, arriving to save the day.' },
        { jp: 'わくわく！', en: 'So exciting!', note: 'Anya in Spy×Family, eyes sparkling.' },
        { jp: '心臓[しんぞう]を捧[ささ]げよ！', en: 'Dedicate your hearts!', note: 'The Survey Corps salute in Attack on Titan, fist on chest.' },
        { jp: 'ピカチュウ、きみにきめた！', en: 'Pikachu, I choose you!', note: 'Satoshi (Ash), Pokémon. In Japanese, literally "I\'ve decided on you".' },
      ],
    },
    {
      id: 'ghibli',
      emoji: '🌳',
      title: 'ジブリの名[めい]セリフ',
      titleEn: 'Studio Ghibli lines',
      blurb: 'From the films every family in Japan has watched a dozen times.',
      phrases: [
        { jp: '見[み]ろ、人[ひと]がゴミのようだ！', en: 'Look — the people are like garbage!', note: 'Muska, Castle in the Sky. Said jokingly from any high viewpoint.' },
        { jp: '40秒[びょう]で支度[したく]しな！', en: 'Get ready in 40 seconds!', note: 'Dola the sky-pirate mum, Castle in the Sky. Every parent on a school morning.' },
        { jp: '飛[と]ばねえ豚[ぶた]は、ただの豚[ぶた]だ。', en: 'A pig that doesn\'t fly is just a pig.', note: 'Porco Rosso — about giving up on your dreams.' },
        { jp: '黙[だま]れ小僧[こぞう]！', en: 'Silence, boy!', note: 'Moro the wolf goddess, Princess Mononoke.' },
        { jp: '生[い]きろ。', en: 'Live.', note: 'The one-word poster tagline of Princess Mononoke (1997).' },
        { jp: 'トトロ、いたもん！', en: 'Totoro was there, I tell you!', note: 'Mei in My Neighbor Totoro, when no one believes her. 〜もん = a child\'s "because!".' },
        { jp: 'まっくろくろすけ、出[で]ておいで！', en: 'Soot sprites, come out!', note: 'My Neighbor Totoro. Children say it into dark corners.' },
        { jp: '贅沢[ぜいたく]な名前[なまえ]だね。', en: 'What an extravagant name.', note: 'Yubaba in Spirited Away, just before she takes Chihiro\'s name away.' },
        { jp: 'おちこんだりもしたけれど、私[わたし]はげんきです。', en: 'I\'ve had my down days, but I\'m doing fine.', note: 'The poster line of Kiki\'s Delivery Service.' },
        { jp: 'バ〜ルス！', en: 'Balse! (the spell of destruction)', note: 'Castle in the Sky. Every TV rerun, all of Japan tweets it at the same second.' },
      ],
    },
    {
      id: 'games',
      emoji: '🎮',
      title: 'ゲームの名[めい]セリフ',
      titleEn: 'Video game messages',
      blurb: 'Text boxes from Dragon Quest, Pokémon and friends that became everyday jokes.',
      phrases: [
        { jp: 'へんじがない。ただの しかばね のようだ。', en: 'No reply. It seems to be just a corpse.', note: 'Dragon Quest, talking to a skeleton. Said about a friend who won\'t answer messages.' },
        { jp: 'ゆうべは おたのしみでしたね。', en: 'You had fun last night, didn\'t you?', note: 'The innkeeper in Dragon Quest I, after you stay the night with the princess.' },
        { jp: 'ぼうけんのしょは きえてしまいました。', en: 'Your adventure log has been erased.', note: 'Dragon Quest\'s dreaded lost-save message — with a creepy jingle. A generation\'s trauma.' },
        { jp: 'しかし まわりこまれてしまった！', en: 'But you were cut off!', note: 'Dragon Quest: you tried to run, and the monster blocked you. For any escape that fails.' },
        { jp: 'いのちだいじに', en: 'Value your life.', note: 'Dragon Quest\'s party tactic for "play it safe". The opposite: ガンガンいこうぜ "go all out!".' },
        { jp: 'あ！ やせいの ピカチュウが とびだしてきた！', en: 'Oh! A wild Pikachu jumped out!', note: 'Pokémon\'s battle message. Swap in anything that suddenly appears: やせいの 部長が…' },
        { jp: 'レベルが あがった！', en: 'You levelled up!', note: 'After any small win in real life.' },
        { jp: '波動拳[はどうけん]！', en: 'Hadouken! (Surge fist)', note: 'Ryu, Street Fighter. Yes, it\'s Japanese.' },
        { jp: 'たたかう　にげる', en: 'Fight / Run', note: 'The classic RPG battle menu. Meme: a picture of a hard choice with these two options.' },
        { jp: 'コンティニュー？', en: 'Continue?', note: 'The arcade countdown — 10, 9, 8… Put in another coin!' },
      ],
    },
    {
      id: 'movies',
      emoji: '🎬',
      title: '映画[えいが]の日本語[にほんご]セリフ',
      titleEn: 'Movie lines, the Japanese way',
      blurb: 'Hollywood classics as Japan knows them from subtitles and dubs.',
      phrases: [
        { jp: '君[きみ]の瞳[ひとみ]に乾杯[かんぱい]。', en: 'A toast to your eyes.', note: 'Casablanca\'s "Here\'s looking at you, kid" — the subtitle is more famous in Japan than the original.' },
        { jp: 'フォースと共[とも]にあらんことを。', en: 'May the Force be with you.', note: 'Star Wars, in old-fashioned grand Japanese.' },
        { jp: 'アイル・ビー・バック', en: 'I\'ll be back.', note: 'The Terminator — Japanese fans just say it in English, katakana-style.' },
        { jp: 'ありのままの姿[すがた]見[み]せるのよ', en: 'Show yourself just as you are.', note: 'Frozen\'s "Let It Go", known in Japan as 「ありのままで」— a 2014 buzzword.' },
        { jp: '明日[あした]は明日[あした]の風[かぜ]が吹[ふ]く。', en: 'Tomorrow tomorrow\'s wind will blow.', note: 'The Japanese rendering of "Tomorrow is another day" (Gone with the Wind). Now a proverb: don\'t worry.' },
        { jp: '男[おとこ]はつらいよ', en: 'It\'s tough being a man.', note: 'Tora-san, Japan\'s 48-film comedy series (1969–1995) about a lovable wanderer.' },
        { jp: 'ゴジラだ！', en: 'It\'s Godzilla!', note: 'ゴジラ = ゴリラ (gorilla) + クジラ (whale). Toho, 1954.' },
      ],
    },
    {
      id: 'buzzwords',
      emoji: '🏆',
      title: '流行語[りゅうこうご]大賞[たいしょう]',
      titleEn: 'Buzzwords of the year',
      blurb: 'Winners of the yearly 新語・流行語大賞 — a snapshot of Japan, year by year.',
      phrases: [
        { jp: 'いつやるか？今[いま]でしょ！', en: 'When will you do it? Now, obviously!', note: '2013: cram-school teacher Osamu Hayashi\'s TV ad line.' },
        { jp: 'お・も・て・な・し', en: 'O-mo-te-na-shi (hospitality)', note: '2013: Christel Takigawa\'s Tokyo 2020 Olympic bid speech, spelled out with a gesture.' },
        { jp: 'じぇじぇじぇ！', en: 'Jeh-jeh-jeh! (Whaaat?!)', note: '2013: the surprised cry from Iwate dialect in the morning drama あまちゃん.' },
        { jp: '倍返[ばいがえ]しだ！', en: 'I\'ll pay you back double!', note: '2013: banker Hanzawa Naoki\'s revenge line in the hit drama 半沢直樹.' },
        { jp: '神[かみ]ってる', en: 'Godlike (on a roll)', note: '2016: the Hiroshima Carp manager about a player hitting walk-off homers.' },
        { jp: 'インスタ映[ば]え', en: 'Looking good on Instagram', note: '2017: food, cafés and places made for the photo.' },
        { jp: 'そだねー', en: 'Yeah, that\'s right~', note: '2018: the women\'s curling team\'s Hokkaido-accent chatter during their bronze-medal Olympics.' },
        { jp: 'ONE TEAM', en: 'One team', note: '2019: the motto of Japan\'s Rugby World Cup team, which reached the quarter-finals at home.' },
        { jp: '3密[みつ]', en: 'The Three Cs', note: '2020: avoid closed spaces, crowds and close contact (密閉・密集・密接).' },
        { jp: 'リアル二刀流[にとうりゅう]', en: 'Real two-sword style', note: '2021: Shohei Ohtani pitching and hitting in the majors — like a samurai with two swords.' },
        { jp: '村神様[むらかみさま]', en: 'Lord Murakami', note: '2022: Yakult Swallows slugger Munetaka Murakami, who hit 56 home runs.' },
        { jp: 'アレ', en: '"That" (A.R.E.)', note: '2023: Hanshin Tigers manager Okada never said 優勝 (championship) — just "that". They won it.' },
        { jp: 'ふてほど', en: 'Inappropriate (Futeho-do)', note: '2024: short for the time-travel drama 不適切にもほどがある！"Way too inappropriate!".' },
        { jp: 'ワイルドだろぉ？', en: 'Pretty wild, huh?', note: '2012: comedian Sugi-chan\'s catchphrase.' },
        { jp: 'なでしこジャパン', en: 'Nadeshiko Japan', note: '2011: the women\'s football team won the World Cup. なでしこ (a pink flower) = the ideal Japanese woman.' },
      ],
    },
    {
      id: 'shops',
      emoji: '🏪',
      title: 'お店[みせ]で聞[き]くことば',
      titleEn: 'What you hear in shops',
      blurb: 'The lines every konbini clerk and waiter says a hundred times a day.',
      phrases: [
        { jp: 'いらっしゃいませ！', en: 'Welcome!', note: 'Shouted as you walk in. You don\'t answer — a small nod is fine.' },
        { jp: '何名様[なんめいさま]ですか？', en: 'How many people?', note: 'At a restaurant door. Answer with fingers, or 二人です.' },
        { jp: '少々[しょうしょう]お待[ま]ちください。', en: 'Please wait a moment.', note: 'The politest "just a sec".' },
        { jp: 'お弁当[べんとう]、温[あたた]めますか？', en: 'Shall I heat up your bento?', note: 'Every convenience store, every time. はい、お願いします or 大丈夫です (no thanks).' },
        { jp: 'ポイントカードはお持[も]ちですか？', en: 'Do you have a points card?', note: 'Asked at almost every checkout. 大丈夫です means "no, thanks".' },
        { jp: '袋[ふくろ]はご利用[りよう]ですか？', en: 'Will you be using a bag?', note: 'Plastic bags have cost a few yen since 2020.' },
        { jp: 'すみませーん！', en: 'Excuse me~!', note: 'Called out to get a waiter\'s attention — totally normal in Japan.' },
        { jp: 'お会計[かいけい]お願[ねが]いします。', en: 'The bill, please.', note: 'Or make a little X with your index fingers.' },
        { jp: '店内[てんない]でお召[め]し上[あ]がりですか？', en: 'Will you be eating in?', note: 'At fast food places. The answer: 持ち帰りで (takeaway) or 店内で.' },
        { jp: 'ありがとうございました！またお越[こ]しくださいませ！', en: 'Thank you! Please come again!', note: 'Shouted as you leave — sometimes by the whole kitchen at once.' },
      ],
    },
    {
      id: 'trains',
      emoji: '🚃',
      title: '駅[えき]と電車[でんしゃ]のアナウンス',
      titleEn: 'Station & train announcements',
      blurb: 'The soundtrack of every commute in Tokyo.',
      phrases: [
        { jp: 'まもなく、1番線[ばんせん]に電車[でんしゃ]がまいります。', en: 'A train will shortly arrive at platform 1.', note: 'まいります is humble-polite for 来ます.' },
        { jp: '黄色[きいろ]い線[せん]の内側[うちがわ]までお下[さ]がりください。', en: 'Please stand back behind the yellow line.', note: 'Heard on every platform, many times an hour.' },
        { jp: '駆[か]け込[こ]み乗車[じょうしゃ]は危険[きけん]ですので、おやめください。', en: 'Rushing onto the train is dangerous, so please don\'t.', note: 'Said the moment someone sprints for the closing doors.' },
        { jp: 'ドアが閉[し]まります。ご注意[ちゅうい]ください。', en: 'The doors are closing. Please be careful.', note: 'Each station plays its own little melody (発車メロディ) before this.' },
        { jp: '次[つぎ]は、渋谷[しぶや]です。', en: 'The next stop is Shibuya.', note: 'The basic in-train announcement, then repeated in English.' },
        { jp: 'お忘[わす]れ物[もの]のないよう、ご注意[ちゅうい]ください。', en: 'Please make sure you haven\'t left anything behind.', note: 'At the last stop. Lost things in Japan usually get handed in.' },
        { jp: '車内[しゃない]では、携帯電話[けいたいでんわ]での通話[つうわ]はご遠慮[えんりょ]ください。', en: 'Please refrain from phone calls on the train.', note: 'Trains are quiet — calls are a big no.' },
        { jp: 'ただいま、電車[でんしゃ]が遅[おく]れております。', en: 'The train is currently delayed.', note: 'Even a delay of a few minutes gets an apology — and you can ask for a 遅延証明書 (delay certificate) for work.' },
      ],
    },
    {
      id: 'chants',
      emoji: '🏮',
      title: '祭[まつ]りと掛[か]け声[ごえ]',
      titleEn: 'Festival & party chants',
      blurb: 'What people shout together — at festivals, fireworks, games and parties.',
      phrases: [
        { jp: 'わっしょい！わっしょい！', en: 'Wasshoi! Wasshoi!', note: 'Carrying a portable shrine (神輿) through the streets at a festival.' },
        { jp: 'たーまやー！', en: 'Ta-ma-ya!', note: 'Shouted at fireworks — Tamaya was a famous Edo-period fireworks maker.' },
        { jp: '鬼[おに]は外[そと]！福[ふく]は内[うち]！', en: 'Demons out! Luck in!', note: 'Setsubun (3 February): throw roasted beans at someone in a demon mask.' },
        { jp: 'かんぱーい！', en: 'Cheers!', note: '乾杯 — literally "dry the cup". Wait for everyone before the first sip.' },
        { jp: 'じゃんけんぽん！あいこでしょ！', en: 'Rock, paper, scissors! A tie, so again!', note: 'Japan\'s way to settle anything. あいこ = a draw.' },
        { jp: 'せーの！', en: 'Ready… go!', note: 'To lift, jump or say something all together.' },
        { jp: 'ばんざーい！', en: 'Banzai! (Ten thousand years!)', note: 'Hands up three times — for an election win, a wedding, a big success.' },
        { jp: 'よっ、日本一[にっぽんいち]！', en: 'Hey — best in Japan!', note: 'A kabuki-audience cheer, now used to hype a friend.' },
        { jp: 'はっけよい、のこった！', en: 'Hakkeyoi — still in!', note: 'The sumo referee: のこった means the wrestlers are still in the ring.' },
        { jp: 'ニッポン、チャチャチャ！', en: 'Nippon, cha-cha-cha!', note: 'The clap-along chant at Japan\'s national-team games.' },
        { jp: 'ドンマイ！', en: 'Don\'t mind!', note: 'Japanese-English for "never mind, it\'s OK" after a mistake in sports.' },
        { jp: 'ファイト、オー！', en: 'Fight — oh!', note: 'A team\'s hands-in cheer before a match or school event.' },
      ],
    },
    {
      id: 'onomatopoeia',
      emoji: '💥',
      title: 'オノマトペ',
      titleEn: 'Sound & feeling words',
      blurb: 'Japanese has thousands of these — for sounds, and for feelings that make no sound at all.',
      phrases: [
        { jp: 'わくわくする！', en: 'I\'m so excited!', note: 'The tingle of looking forward to something.' },
        { jp: 'ドキドキした。', en: 'My heart was pounding.', note: 'Nerves, or a crush.' },
        { jp: 'おなかがペコペコ。', en: 'I\'m starving.', note: 'ペコペコ = an empty, caved-in tummy. Also bowing again and again.' },
        { jp: 'キラキラ光[ひか]る星[ほし]', en: 'Twinkling, sparkling stars', note: '"Twinkle Twinkle Little Star" in Japanese is きらきら星.' },
        { jp: '雨[あめ]がザーザー降[ふ]っている。', en: 'It\'s pouring down.', note: 'Heavy rain. Light rain is しとしと, sudden showers ポツポツ.' },
        { jp: 'ニコニコ笑[わら]う', en: 'Smile happily', note: 'Gentle smiling. Grinning is ニヤニヤ — a bit sly.' },
        { jp: 'イライラする！', en: 'I\'m so irritated!', note: 'Like something prickly under your skin.' },
        { jp: 'この猫[ねこ]、もふもふ！', en: 'This cat is so fluffy!', note: 'The softness of fur you want to bury your face in. Internet favourite.' },
        { jp: 'シーン…', en: '(Dead silence)', note: 'The "sound" of silence in manga, after a joke that didn\'t land.' },
        { jp: 'ガーン！', en: '(Shock!)', note: 'The manga sound of terrible news hitting you.' },
        { jp: 'ゴロゴロしたい。', en: 'I want to laze around.', note: 'Rolling about on the floor. Also thunder rumbling and a cat purring.' },
        { jp: 'ぐっすり寝[ね]た。', en: 'I slept like a log.', note: 'Deep, sound sleep.' },
        { jp: 'もぐもぐ', en: '(Munch munch)', note: 'Chewing with your mouth full — cute in manga and on cooking shows.' },
        { jp: 'ふわふわのパンケーキ', en: 'Fluffy pancakes', note: 'Soft and airy — Japanese soufflé pancakes are the ふわふわ champions.' },
      ],
    },
    {
      id: 'fandom',
      emoji: '💖',
      title: 'オタク・推[お]し活[かつ]用語[ようご]',
      titleEn: 'Fandom & otaku words',
      blurb: 'How fans talk about the idols, characters and shows they love.',
      phrases: [
        { jp: '推[お]しが尊[とうと]い。', en: 'My fave is precious.', note: '推し = the member or character you support. 尊い = so wonderful it\'s almost holy.' },
        { jp: '推[お]し活[かつ]してる。', en: 'I\'m doing fan activities.', note: 'Concerts, merch, birthday cakes for a character — anything for your 推し.' },
        { jp: '沼[ぬま]にハマった。', en: 'I fell into the swamp.', note: 'Got hooked on a new series or hobby, with no way out.' },
        { jp: '今日[きょう]は神回[かみかい]だった！', en: 'Today was a god-tier episode!', note: '神 = amazing. 神回 = the best episode, 神対応 = amazing service.' },
        { jp: '聖地[せいち]巡礼[じゅんれい]に行[い]きたい。', en: 'I want to make a pilgrimage to the holy land.', note: 'Visiting the real places an anime is set in.' },
        { jp: '箱推[はこお]しです。', en: 'I support the whole box.', note: 'A fan of the whole group, not just one member.' },
        { jp: '解釈[かいしゃく]違[ちが]い！', en: 'That\'s not my interpretation!', note: 'When fan art or a sequel gets your favourite character "wrong".' },
        { jp: 'コスプレしてみた。', en: 'I tried cosplay.', note: 'コスプレ is Japanese-made: コスチューム + プレイ. 〜してみた is the classic video-title format.' },
        { jp: 'ネタバレ禁止[きんし]！', en: 'No spoilers!', note: 'ネタ (the material) + バレ (revealed).' },
        { jp: '萌[も]え〜', en: 'So moe~', note: 'The warm, protective feeling a cute character gives you. Literally "budding".' },
      ],
    },
    {
      id: 'work',
      emoji: '💼',
      title: '会社[かいしゃ]のことば',
      titleEn: 'Office life',
      blurb: 'From polite email openers to the joy of Friday night.',
      phrases: [
        { jp: 'いつもお世話[せわ]になっております。', en: 'Thank you as always for your support.', note: 'How almost every business email and phone call begins — even with strangers.' },
        { jp: '承知[しょうち]しました。', en: 'Understood.', note: 'The polite "got it" to a boss or customer. りょうかいです is a bit casual for that.' },
        { jp: '恐[おそ]れ入[い]りますが…', en: 'I\'m terribly sorry, but…', note: 'The soft lead-in before asking someone for something.' },
        { jp: 'ほうれんそうを忘[わす]れずに！', en: 'Don\'t forget your spinach!', note: 'ほうれんそう (spinach) = 報告・連絡・相談: report, inform, consult. Taught to every new employee.' },
        { jp: '今日[きょう]は花金[はなきん]だ！', en: 'It\'s flower Friday!', note: '花の金曜日 — Friday night out after work.' },
        { jp: '飲[の]みニケーションしよう。', en: 'Let\'s drink-municate.', note: '飲み (drinking) + コミュニケーション: bonding with coworkers over drinks.' },
        { jp: '定時[ていじ]で帰[かえ]ります！', en: 'I\'m leaving on the dot!', note: 'Going home right at closing time — a small act of rebellion. A 2019 drama was called わたし、定時で帰ります。' },
        { jp: '根回[ねまわ]しが大事[だいじ]です。', en: 'Groundwork is important.', note: 'Quietly getting everyone to agree before the meeting. Literally "digging around the roots".' },
        { jp: '有給[ゆうきゅう]を取[と]ります。', en: 'I\'m taking paid leave.', note: 'Many workers leave lots of 有給 unused, so there\'s now a legal minimum of five days a year.' },
      ],
    },
    {
      id: 'food',
      emoji: '🍜',
      title: '食[た]べ物[もの]と飲[の]み会[かい]',
      titleEn: 'Food & drinking',
      blurb: 'For the izakaya, the ramen shop and the dessert counter.',
      phrases: [
        { jp: 'とりあえずビール！', en: 'Beer, for starters!', note: 'The first order at every izakaya, before anyone has read the menu.' },
        { jp: 'デザートは別腹[べつばら]。', en: 'Dessert goes in a separate stomach.', note: 'Full of dinner, but there\'s always room for cake.' },
        { jp: 'シメはラーメンで。', en: 'Let\'s finish with ramen.', note: 'シメ (〆) = the closing dish of the night: ramen after drinks, rice in the hotpot.' },
        { jp: 'おかわり！', en: 'Seconds, please!', note: 'Some ramen shops let you order a 替え玉 — an extra ball of noodles for your soup.' },
        { jp: '私[わたし]、猫舌[ねこじた]なんです。', en: 'I have a cat\'s tongue.', note: 'You can\'t handle hot food or drinks, like a cat.' },
        { jp: '食[た]べ放題[ほうだい]、飲[の]み放題[ほうだい]！', en: 'All you can eat, all you can drink!', note: '〜放題 = as much as you like, usually for a set time.' },
        { jp: '一口[ひとくち]ちょうだい！', en: 'Give me a bite!', note: 'Sharing food is common among friends.' },
        { jp: 'いい食[た]べっぷりだね！', en: 'You really eat with gusto!', note: 'A compliment — Japanese hosts love a big eater.' },
        { jp: '花[はな]より団子[だんご]', en: 'Dumplings over flowers.', note: 'At cherry-blossom parties, the food is the real star. A proverb for practical people.' },
      ],
    },
    {
      id: 'kotowaza',
      emoji: '🦉',
      title: 'ことわざ・四字熟語[よじじゅくご]',
      titleEn: 'Proverbs & four-kanji idioms',
      blurb: 'Old wisdom you will hear in dramas, speeches and school.',
      phrases: [
        { jp: '猿[さる]も木[き]から落[お]ちる。', en: 'Even monkeys fall from trees.', note: 'Even experts make mistakes.' },
        { jp: '七転[ななころ]び八起[やお]き', en: 'Fall down seven times, get up eight.', note: 'Never give up. The Daruma doll, which always rolls back upright, is its symbol.' },
        { jp: '石[いし]の上[うえ]にも三年[さんねん]', en: 'Three years even on a stone.', note: 'Sit on a cold stone long enough and it warms up: patience pays.' },
        { jp: '猫[ねこ]に小判[こばん]', en: 'Gold coins to a cat.', note: 'Wasted on someone who can\'t appreciate it. Like "pearls before swine".' },
        { jp: '急[いそ]がば回[まわ]れ。', en: 'If you\'re in a hurry, go the long way round.', note: 'More haste, less speed.' },
        { jp: '笑[わら]う門[かど]には福[ふく]来[きた]る。', en: 'Luck comes to the gate where people laugh.', note: 'Keep smiling and good things follow. A New Year favourite.' },
        { jp: '犬[いぬ]も歩[ある]けば棒[ぼう]に当[あ]たる。', en: 'Even a dog that walks around bumps into a stick.', note: 'Go out and something happens — good or bad.' },
        { jp: '弘法[こうぼう]も筆[ふで]の誤[あやま]り', en: 'Even Kobo Daishi slipped with his brush.', note: 'Even the great calligrapher-monk made mistakes.' },
        { jp: '一期一会[いちごいちえ]', en: 'One time, one meeting', note: 'From the tea ceremony: treasure this moment — it will never come again.' },
        { jp: '十人十色[じゅうにんといろ]', en: 'Ten people, ten colours', note: 'Everyone is different.' },
        { jp: '一石二鳥[いっせきにちょう]', en: 'One stone, two birds', note: 'The same idea as English, in four kanji.' },
        { jp: '自業自得[じごうじとく]', en: 'You reap what you sow.', note: 'Your own actions brought it on — said with no sympathy at all.' },
      ],
    },
    {
      id: 'quotes',
      emoji: '📜',
      title: '歴史[れきし]の名言[めいげん]',
      titleEn: 'Famous quotes from history',
      blurb: 'Lines from warlords, thinkers and teachers that are still quoted today.',
      phrases: [
        { jp: '鳴[な]かぬなら殺[ころ]してしまえホトトギス', en: 'If the cuckoo won\'t sing, kill it.', note: 'Oda Nobunaga\'s character in a famous trio of verses — ruthless.' },
        { jp: '鳴[な]かぬなら鳴[な]かせてみようホトトギス', en: 'If the cuckoo won\'t sing, make it sing.', note: 'Toyotomi Hideyoshi — clever and resourceful.' },
        { jp: '鳴[な]かぬなら鳴[な]くまで待[ま]とうホトトギス', en: 'If the cuckoo won\'t sing, wait till it does.', note: 'Tokugawa Ieyasu — patient. And it was Ieyasu who ended up ruling Japan.' },
        { jp: '少年[しょうねん]よ、大志[たいし]を抱[いだ]け。', en: 'Boys, be ambitious.', note: 'William S. Clark, leaving his school in Sapporo in 1877. There\'s a statue of him pointing.' },
        { jp: '天[てん]は人[ひと]の上[うえ]に人[ひと]を造[つく]らず、人[ひと]の下[した]に人[ひと]を造[つく]らず。', en: 'Heaven creates no one above or below anyone else.', note: 'Fukuzawa Yukichi, 1872 — the man on the old 10,000-yen note.' },
        { jp: '和[わ]を以[もっ]て貴[とうと]しとなす。', en: 'Harmony is to be valued.', note: 'The first article of Prince Shotoku\'s Constitution, 604 — the root of Japan\'s love of 和.' },
        { jp: '為[な]せば成[な]る、為[な]さねば成[な]らぬ何事[なにごと]も。', en: 'Try and it can be done; don\'t, and nothing will be.', note: 'Uesugi Yozan, 18th-century lord. A school-motto classic.' },
        { jp: '芸術[げいじゅつ]は爆発[ばくはつ]だ！', en: 'Art is an explosion!', note: 'Artist Taro Okamoto in a 1981 TV ad. He made the Tower of the Sun in Osaka.' },
      ],
    },
    {
      id: 'literature',
      emoji: '📚',
      title: '文学[ぶんがく]の名文[めいぶん]と俳句[はいく]',
      titleEn: 'Famous openings & haiku',
      blurb: 'First lines and poems every student learns by heart.',
      phrases: [
        { jp: '吾輩[わがはい]は猫[ねこ]である。名前[なまえ]はまだ無[な]い。', en: 'I am a cat. As yet I have no name.', note: 'Natsume Soseki, 1905 — told by a snooty cat. 吾輩 is a pompous "I".' },
        { jp: '国境[こっきょう]の長[なが]いトンネルを抜[ぬ]けると雪国[ゆきぐに]であった。', en: 'The train came out of the long border tunnel into the snow country.', note: 'Kawabata Yasunari\'s Snow Country. He won the Nobel Prize in 1968.' },
        { jp: 'メロスは激怒[げきど]した。', en: 'Melos was enraged.', note: 'Dazai Osamu\'s Run, Melos! — in every middle-school textbook.' },
        { jp: '恥[はじ]の多[おお]い生涯[しょうがい]を送[おく]って来[き]ました。', en: 'I have lived a life full of shame.', note: 'Dazai\'s No Longer Human, one of Japan\'s best-selling novels.' },
        { jp: '春[はる]はあけぼの。', en: 'In spring, the dawn.', note: 'Sei Shonagon\'s Pillow Book, around the year 1000: the best moment of each season.' },
        { jp: '祇園精舎[ぎおんしょうじゃ]の鐘[かね]の声[こえ]、諸行無常[しょぎょうむじょう]の響[ひび]きあり。', en: 'The bell of Gion Temple rings that nothing lasts.', note: 'The Tale of the Heike — about the fall of a great samurai clan.' },
        { jp: '古池[ふるいけ]や　蛙[かわず]飛[と]び込[こ]む　水[みず]の音[おと]', en: 'An old pond — a frog jumps in — the sound of water.', note: 'Basho, 1686: the most famous haiku of all. 5-7-5 sounds.' },
        { jp: '柿[かき]食[く]えば　鐘[かね]が鳴[な]るなり　法隆寺[ほうりゅうじ]', en: 'I eat a persimmon, and the bell rings — Horyuji.', note: 'Masaoka Shiki, 1895. Persimmons + temple bells = autumn in Nara.' },
        { jp: '雨[あめ]ニモマケズ　風[かぜ]ニモマケズ', en: 'Not losing to the rain, not losing to the wind', note: 'Miyazawa Kenji\'s poem about the kind of person he wanted to be — written in katakana.' },
      ],
    },
    {
      id: 'love',
      emoji: '💌',
      title: '恋[こい]とほめことば',
      titleEn: 'Love & compliments',
      blurb: 'Confessions, compliments and the trope-words of romance manga.',
      phrases: [
        { jp: '月[つき]が綺麗[きれい]ですね。', en: 'The moon is beautiful, isn\'t it?', note: 'Legend says Natsume Soseki taught that a Japanese person would say "I love you" this way.' },
        { jp: '好[す]きです。付[つ]き合[あ]ってください！', en: 'I like you. Please go out with me!', note: 'The 告白 (confession): couples officially start with this.' },
        { jp: '一目惚[ひとめぼ]れしました。', en: 'It was love at first sight.', note: 'Literally "fell for you in one look".' },
        { jp: '胸[むね]キュン！', en: 'Heart-squeeze!', note: 'That tight little feeling in your chest in a romantic scene.' },
        { jp: '壁[かべ]ドン', en: 'Wall-slam', note: 'The manga move: hand on the wall, trapping your crush. ドン is the slam.' },
        { jp: '結婚[けっこん]してください。', en: 'Please marry me.', note: 'The proposal line — simple and direct.' },
        { jp: 'センスいいね！', en: 'You\'ve got good taste!', note: 'センス = a sense of style.' },
        { jp: 'かっこいい！', en: 'So cool!', note: 'For a stylish person, a nice car, a great move.' },
        { jp: '日本語[にほんご]、上手[じょうず]ですね！', en: 'Your Japanese is so good!', note: 'You\'ll hear it after saying ありがとう. Reply いえいえ、まだまだです (no, I\'ve got a long way to go).' },
      ],
    },
    {
      id: 'smalltalk',
      emoji: '🌸',
      title: '季節[きせつ]のあいさつ',
      titleEn: 'Seasonal small talk',
      blurb: 'Japan talks about the weather — and the seasons — a lot.',
      phrases: [
        { jp: '暑[あつ]いですねえ。', en: 'Hot, isn\'t it?', note: 'Summer\'s number-one conversation starter. Winter: 寒いですねえ。' },
        { jp: 'お花見[はなみ]しよう！', en: 'Let\'s go cherry-blossom viewing!', note: 'Late March to early April: picnics under the trees, often all day.' },
        { jp: '花粉症[かふんしょう]がつらい。', en: 'My hay fever is awful.', note: 'Cedar pollen hits roughly a third of Japan every spring. Masks everywhere.' },
        { jp: '梅雨[つゆ]入[い]りしましたね。', en: 'The rainy season has started.', note: 'June to mid-July. 梅雨 = "plum rain", the season the plums ripen.' },
        { jp: '夏[なつ]バテしちゃった。', en: 'The summer heat has worn me out.', note: 'The cure: eel (うなぎ) on the Day of the Ox in late July.' },
        { jp: '紅葉[こうよう]がきれいですね。', en: 'The autumn leaves are beautiful.', note: 'Going out to see them is 紅葉狩り — "autumn-leaf hunting".' },
        { jp: 'こたつから出[で]られない…', en: 'I can\'t get out of the kotatsu…', note: 'The heated table with a blanket — the most dangerous furniture in winter.' },
        { jp: '年越[としこ]しそば、食[た]べた？', en: 'Did you have your year-crossing soba?', note: 'Long noodles on New Year\'s Eve for a long life.' },
      ],
    },
  ];
})(typeof window !== 'undefined' ? window : globalThis);
