(function (global) {
  'use strict';

  // Graded reading stories for the Stories page (stories.html), grouped by
  // JLPT level.
  //
  // Each sentence's `jp` is a space-separated list of tokens. A token uses the
  // same inline `kanji[reading]` furigana markup as particles-data.js, and may
  // end in `>key` to point at a STORY_GLOSSARY entry other than its own plain
  // spelling — conjugated words point at their dictionary form this way
  // (`起[お]きます>起きる`). Punctuation tokens (。、「」？) aren't clickable.
  //
  // `grammar` lists `id:snippet` pairs: the id is a STORY_GRAMMAR key, and the
  // optional snippet is the exact stretch of the (furigana-stripped) sentence
  // that uses it, so the reader can highlight it. test_stories.js checks that
  // every token has a glossary entry and every snippet occurs in its sentence.

  global.STORY_GRAMMAR = {
    // ── N5 ──
    'wa-topic': { level: 'N5', title: 'は — topic marker', pattern: 'X は Y', note: 'Marks what the sentence is about ("as for X…"). Written は but read わ.' },
    'desu': { level: 'N5', title: 'です — polite "is"', pattern: 'Noun / な-adj + です', note: 'The polite copula: "X is Y". Its plain form is だ.' },
    'deshita': { level: 'N5', title: 'でした — polite "was"', pattern: 'Noun / な-adj + でした', note: 'Past tense of です.' },
    'masu': { level: 'N5', title: '〜ます — polite present', pattern: 'Verb stem + ます', note: 'Polite non-past form of a verb: covers habits ("every day I…") and the future ("I will…").' },
    'masu-past': { level: 'N5', title: '〜ました — polite past', pattern: 'Verb stem + ました', note: 'Polite past form: "did ~".' },
    'masen-deshita': { level: 'N5', title: '〜ませんでした — polite past negative', pattern: 'Verb stem + ませんでした', note: 'Polite "did not ~".' },
    'masen': { level: 'N5', title: '〜ません — polite negative', pattern: 'Verb stem + ません', note: 'Polite "does not / will not ~".' },
    'mashou': { level: 'N5', title: '〜ましょう — "let\'s"', pattern: 'Verb stem + ましょう', note: 'Suggests doing something together: "let\'s ~".' },
    'wo-object': { level: 'N5', title: 'を — direct object', pattern: 'Noun を Verb', note: 'Marks the thing the action is done to.' },
    'ga-subject': { level: 'N5', title: 'が — subject marker', pattern: 'Noun が Verb', note: 'Marks the subject, often new information or the thing that exists / happens.' },
    'ni-time': { level: 'N5', title: 'に — point in time', pattern: 'Time に Verb', note: 'Marks a specific time: 六時に "at six". Not used with relative times like 毎朝 or 昨日.' },
    'ni-destination': { level: 'N5', title: 'に — destination', pattern: 'Place に 行く / 来る / 帰る', note: 'Marks where you go to. Interchangeable with へ for movement.' },
    'he-direction': { level: 'N5', title: 'へ — direction', pattern: 'Place へ 行く', note: 'Marks the direction of movement ("towards"). Written へ but read え.' },
    'de-place': { level: 'N5', title: 'で — place of action', pattern: 'Place で Verb', note: 'Marks where an action happens.' },
    'de-means': { level: 'N5', title: 'で — means / material', pattern: 'Tool / transport / material で', note: 'Marks how something is done: by train, with tomatoes, in Japanese.' },
    'de-together': { level: 'N5', title: 'で — "as a group of"', pattern: 'Number of people で', note: '二人で = "the two of us (together)", 一人で = "alone".' },
    'to-and': { level: 'N5', title: 'と — "and" (complete list)', pattern: 'A と B', note: 'Joins nouns into a complete list: "A and B".' },
    'to-with': { level: 'N5', title: 'と — "with"', pattern: 'Person と Verb', note: 'Marks who you do something together with.' },
    'ya-and': { level: 'N5', title: 'や — "and" (examples)', pattern: 'A や B', note: 'Lists examples, implying there are others: "A, B, and so on".' },
    'no-possessive': { level: 'N5', title: 'の — linking nouns', pattern: 'Noun の Noun', note: 'Links two nouns: possession ("my house"), description ("clothes shop") or position ("inside the train").' },
    'wa-ga': { level: 'N5', title: 'X は Y が Adj', pattern: 'Topic は Subject が Adjective', note: 'Describes one aspect of the topic: 電車は人が多い "as for the train, people are many" → "the train is crowded".' },
    'ni-aru': { level: 'N5', title: 'に…ある / いる — existence', pattern: 'Place に Thing が ある / Person・animal が いる', note: 'Says something exists somewhere. ある for things, いる for people and animals.' },
    'ni-wa': { level: 'N5', title: 'には — "at / in" + topic', pattern: 'Place に は', note: 'に (location) combined with は to make the place the topic: "at my house, (there is)…".' },
    'i-adj-desu': { level: 'N5', title: 'い-adjective + です', pattern: 'い-adj + です', note: 'An い-adjective ends a polite sentence with です added only for politeness.' },
    'i-adj-past': { level: 'N5', title: 'い-adjective past', pattern: 'い-adj (〜い → 〜かった)', note: 'Past tense of い-adjectives: 高い → 高かった, うれしい → うれしかった.' },
    'i-adj-noun': { level: 'N5', title: 'い-adjective before a noun', pattern: 'い-adj + Noun', note: 'い-adjectives go directly in front of the noun they describe.' },
    'na-adj-noun': { level: 'N5', title: 'な-adjective before a noun', pattern: 'な-adj + な + Noun', note: 'な-adjectives need な between them and the noun.' },
    'kute': { level: 'N5', title: '〜くて — joining adjectives', pattern: 'い-adj (〜い → 〜くて), …', note: 'The て-form of an い-adjective, used to chain descriptions ("white and small") or give a reason ("it was hot, so…").' },
    'te-sequence': { level: 'N5', title: '〜て — "and then"', pattern: 'Verb て-form, Verb', note: 'Links actions in order: "do A, and then B".' },
    'te-iru': { level: 'N5', title: '〜ている — ongoing action / state', pattern: 'Verb て-form + いる', note: 'An action in progress ("is sleeping"), a habit ("grows vegetables every day"), or a resulting state ("lives in", "is inside").' },
    'ga-suki': { level: 'N5', title: '〜が好き — liking', pattern: 'Noun が 好き / 大好き', note: 'The thing liked is marked with が, not を.' },
    'hoshii': { level: 'N5', title: '〜が欲しい — wanting a thing', pattern: 'Noun が 欲しい', note: '"I want (a thing)". 欲しい is an い-adjective, so its past is 欲しかった.' },
    'kosoado': { level: 'N5', title: 'この / その / あの', pattern: 'この・その・あの + Noun', note: '"this (near me)", "that (near you / just mentioned)", "that (over there)".' },
    'ka-question': { level: 'N5', title: 'か — question marker', pattern: 'Sentence + か', note: 'Added to the end of a polite sentence to make it a question.' },
    'ga-but': { level: 'N5', title: 'が — "but"', pattern: 'Clause が、Clause', note: 'Joins two clauses with a contrast: "…, but …".' },
    'dakara': { level: 'N5', title: 'だから — "so / therefore"', pattern: 'Sentence。だから、Sentence', note: 'Starts a sentence that follows from the previous one.' },
    'to-iu': { level: 'N5', title: '〜と言う — quoting', pattern: '「Quote」と 言う', note: 'と marks what was said.' },
    'tari': { level: 'N5', title: '〜たり〜たりする — doing things like', pattern: 'Verb た-form + り, Verb た-form + り する', note: 'Lists example actions without claiming the list is complete.' },
    'yo': { level: 'N5', title: 'よ — assertion', pattern: 'Sentence + よ', note: 'Sentence-ending particle for telling the listener something you think they need to hear.' },
    'ne': { level: 'N5', title: 'ね — seeking agreement', pattern: 'Sentence + ね', note: 'Sentence-ending particle: "…, right?" / "…, isn\'t it?". Common in friendly replies.' },
    'nani-mo-neg': { level: 'N5', title: '何も + negative — "nothing"', pattern: '何も + negative verb', note: '何も with a negative verb means "nothing (at all)".' },
    'ichiban': { level: 'N5', title: '一番 — "the most / number one"', pattern: '一番 + adjective / 一番の + Noun', note: 'Makes a superlative: 一番の友だち "best friend".' },

    // ── N4 ──
    'plain-form': { level: 'N4', title: 'Plain (dictionary) form', pattern: 'Verb dictionary form / だ', note: 'Casual / written style without です・ます. Common in novels, diaries and between friends.' },
    'ta-koto-ga-aru': { level: 'N4', title: '〜たことがある — experience', pattern: 'Verb た-form + ことがある', note: '"Have (ever) done ~". With ない / なかった: "have never done ~".' },
    'node': { level: 'N4', title: '〜ので — "because / so"', pattern: 'Plain form + ので', note: 'Gives a reason, sounding softer and more objective than から.' },
    'kara-reason': { level: 'N4', title: '〜から — "because"', pattern: 'Clause + から', note: 'Gives a reason. After a noun in casual speech: 雨だから "because it\'s raining".' },
    'kara-from': { level: 'N4', title: 'から — "from"', pattern: 'Person / place / time から', note: 'Marks a starting point or source.' },
    'made': { level: 'N4', title: 'まで — "up to / until"', pattern: 'Place / time まで', note: 'Marks an end point: 駅まで "as far as the station".' },
    'made-ni': { level: 'N4', title: 'までに — "by (a deadline)"', pattern: 'Time までに', note: 'Something happens before that point in time, not continuing until it.' },
    'ni-iku-purpose': { level: 'N4', title: '〜に行く — going to do', pattern: 'Verb stem + に 行く / 来る', note: 'Says the purpose of going somewhere: 見に行く "go to see".' },
    'sugiru': { level: 'N4', title: '〜すぎる — too much', pattern: 'Verb stem / adj stem + すぎる', note: '"Too ~": 多すぎる "too many". Conjugates like an ichidan verb.' },
    'potential': { level: 'N4', title: 'Potential form — "can"', pattern: 'う-verb: 〜える / る-verb: 〜られる / する → できる', note: 'Says something can (or can\'t) be done: 進める "can move forward", 言える "can say".' },
    'nakanaka-neg': { level: 'N4', title: 'なかなか + negative', pattern: 'なかなか + negative verb', note: '"Not easily / not readily": it was hard to make progress.' },
    'naku-naru': { level: 'N4', title: '〜なくなる — no longer', pattern: 'Verb ない-form (〜ない → 〜なく) + なる', note: '"Come to not ~": わからなくなる "lose track / stop knowing".' },
    'relative-clause': { level: 'N4', title: 'Relative clause', pattern: 'Plain-form clause + Noun', note: 'A whole clause can describe a noun, placed right before it: 祖母が作ったトマト "the tomatoes (that) grandma grew".' },
    'te-kureru': { level: 'N4', title: '〜てくれる — doing a favour for me', pattern: 'Verb て-form + くれる', note: 'Someone does something for the speaker (or their group). Shows gratitude.' },
    'te-ageru': { level: 'N4', title: '〜てあげる — doing a favour for someone', pattern: 'Verb て-form + あげる', note: 'The speaker (or subject) does something for someone else.' },
    'te-request': { level: 'N4', title: '〜て — casual request', pattern: 'Verb て-form (end of sentence)', note: 'A て-form on its own is a casual way to ask someone to do something (short for 〜てください).' },
    'na-adverb': { level: 'N4', title: 'な-adjective + に — adverb', pattern: 'な-adj + に + Verb', note: 'Turns a な-adjective into an adverb: 親切に "kindly".' },
    'te-reason': { level: 'N4', title: '〜て — reason / cause', pattern: 'Clause て-form, feeling / result', note: 'The て-form can give the cause of a feeling or result: "I could say it, (and so) I was happy".' },
    'te-shimau': { level: 'N4', title: '〜てしまう — regret / completion', pattern: 'Verb て-form + しまう', note: 'Something happened that you didn\'t want (or was done completely): "ended up ~", "accidentally ~".' },
    'no-naka-de-ichiban': { level: 'N4', title: '〜の中で一番 — the most among', pattern: 'Group の中で 一番 + adjective', note: '"Of all ~, the most …".' },
    'you-ni': { level: 'N4', title: '〜ように — "so that"', pattern: 'Potential / ない-form + ように', note: 'Says the goal of an action: 行けるように "so that I can go".' },
    'tara': { level: 'N4', title: '〜たら — "when / if"', pattern: 'Verb た-form + ら', note: '"When (once) A happened…" or "if A happens…". Often for a surprise discovery: 起きたら雨だった.' },
    'to-omou': { level: 'N4', title: '〜と思う — "I think"', pattern: 'Plain form + と 思う', note: 'Reports a thought or opinion.' },
    'volitional-to-omou': { level: 'N4', title: '〜ようと思う — intending to', pattern: 'Volitional form + と 思う', note: '"Think I\'ll ~ / be about to ~": かけようと思った "was going to call".' },
    'toki': { level: 'N4', title: '〜とき — "when"', pattern: 'Plain form + とき', note: '"At the time when ~". A past verb before とき means the action had already happened.' },
    'nai-invitation': { level: 'N4', title: '〜ない？ — casual invitation', pattern: 'Verb ない-form + ？', note: 'Asking "won\'t you ~?" with rising intonation is a friendly way to suggest something.' },
    'mae-ni': { level: 'N4', title: '〜前に — "before"', pattern: 'Verb dictionary form + 前に', note: '"Before doing ~". The verb is always in dictionary form, even in a past story.' },
    'nakereba-naranai': { level: 'N4', title: '〜なければならない — must', pattern: 'Verb ない-form (〜ない → 〜なければ) + ならない', note: '"Have to ~". Polite past: 〜なければなりませんでした "had to ~".' },
    'to-conditional': { level: 'N4', title: '〜と — "when (and then)"', pattern: 'Verb dictionary form + と', note: '"When A happens, B (naturally / as found)". 着くと "when I arrived, (I found)…".' },
    'ba-conditional': { level: 'N4', title: '〜ば — "if"', pattern: 'Verb (〜う → 〜えば)', note: 'A general condition: いれば "if (they) are there".' },
    'demo-even': { level: 'N4', title: '〜でも — "even"', pattern: 'Noun + でも', note: '"Even on ~ / even with ~".' },
    'te-aru': { level: 'N4', title: '〜てある — something has been done', pattern: 'Transitive verb て-form + ある', note: 'Describes a state left by someone\'s action: 書いてある "is written (there)".' },
    'sou-looks': { level: 'N4', title: '〜そう — "looks ~"', pattern: 'Adj stem (drop い / な) + そう', note: 'Judging by appearance: おいしそう "looks delicious".' },
    'nagara': { level: 'N4', title: '〜ながら — "while"', pattern: 'Verb stem + ながら', note: 'Doing two things at once; the main action is the second one.' },
    'to-ii': { level: 'N4', title: '〜といいな — hoping', pattern: 'Plain form + と いい（な）', note: '"It would be nice if ~" / "I hope ~".' },
    'tai': { level: 'N4', title: '〜たい — want to', pattern: 'Verb stem + たい', note: '"Want to ~". にしたい = "want to make it into…".' },
    'ni-naru': { level: 'N4', title: '〜になる — become', pattern: 'Noun / な-adj + に なる', note: '"Become ~": 好きになる "come to like".' },
    'ni-suru': { level: 'N4', title: '〜にする — make into', pattern: 'Noun + に する', note: '"Make (something) into ~".' },
    'te-kara': { level: 'N4', title: '〜てから — "after"', pattern: 'Verb て-form + から', note: '"After doing ~, …". Stresses the order of events.' },
    'koto-nominalizer': { level: 'N4', title: '〜こと — turning a verb into a noun', pattern: 'Plain form + こと', note: 'Makes a clause into a noun ("the fact that ~"), so it can take を / が.' },

    // ── N3 ──
    'hazu': { level: 'N3', title: '〜はずだ — "should be"', pattern: 'Plain form + はずだ', note: 'Strong expectation based on reasoning: "it must have been / should be".' },
    'sorehodo-neg': { level: 'N3', title: 'それほど + negative', pattern: 'それほど + negative', note: '"Not that much / not so ~".' },
    'keredo': { level: 'N3', title: '〜けれど — "but / although"', pattern: 'Clause + けれど', note: 'Contrast, a little softer than が. Also けど, けれども.' },
    'koto-ni-suru': { level: 'N3', title: '〜ことにする — deciding to', pattern: 'Verb dictionary form + ことにする', note: '"Decide to ~". Past ことにした: "decided to ~".' },
    'te-kuru': { level: 'N3', title: '〜てくる — towards the speaker', pattern: 'Verb て-form + くる', note: 'An action directed at the speaker: 電話がかかってきた "a call came (to me)".' },
    'ni-yoru-to': { level: 'N3', title: '〜によると — "according to"', pattern: 'Source + によると', note: 'Names where information comes from. Usually ends in そうだ / らしい.' },
    'sou-hearsay': { level: 'N3', title: '〜そうだ — "I heard that"', pattern: 'Plain form + そうだ', note: 'Reports something heard from someone else. Different from adjective-stem + そう ("looks ~").' },
    'passive': { level: 'N3', title: 'Passive — "is done (by)"', pattern: 'う-verb: 〜われる・〜られる / る-verb: 〜られる', note: 'The subject receives the action: 拾われる "be picked up", 愛される "be loved". The doer is marked with に.' },
    'rashii': { level: 'N3', title: '〜らしい — "apparently"', pattern: 'Plain form + らしい', note: 'A conclusion based on what you heard or saw: "it seems".' },
    'bakari-dewanai': { level: 'N3', title: '〜ばかりではない — "not only / not all"', pattern: 'Noun + ばかり では ない', note: '"It isn\'t all ~": 悪い人ばかりではない "not everyone is bad".' },
    'you-ni-suru': { level: 'N3', title: '〜ようにしている — making a point of', pattern: 'Verb dictionary form + ようにしている', note: '"Make a habit of ~ / always make sure to ~".' },
    'tame-ni': { level: 'N3', title: '〜ために — "in order to"', pattern: 'Verb dictionary form + ために', note: 'States a purpose (with the same subject in both clauses).' },
    'kata': { level: 'N3', title: '〜方 — "way of doing"', pattern: 'Verb stem + 方', note: '作り方 "how to make", 読み方 "how to read".' },
    'you-ni-naru': { level: 'N3', title: '〜ようになる — come to be able', pattern: 'Verb (often potential) + ようになる', note: 'A gradual change: 話せるようになった "became able to speak".' },
    'zenzen-neg': { level: 'N3', title: '全然 + negative', pattern: '全然 + negative', note: '"Not at all".' },
    'ba-hodo': { level: 'N3', title: '〜ば〜ほど — "the more…the more"', pattern: 'Verb ば-form + same verb + ほど', note: '"The more you ~, the more …".' },
    'causative': { level: 'N3', title: 'Causative — make / let do', pattern: 'う-verb: 〜わせる・〜せる / る-verb: 〜させる', note: '"Have / let someone do": 手伝わせる "have (someone) help". The person made to act is marked with に.' },
    'te-bakari': { level: 'N3', title: '〜てばかりいる — doing nothing but', pattern: 'Verb て-form + ばかり いる', note: '"Keep on ~ / do nothing but ~", usually a complaint.' },
  };

  // Word glossary keyed by dictionary form: [reading, meaning, part of speech].
  // A key may carry a (disambiguation) suffix for words that share a
  // spelling but not a meaning; the reader shows the key without it.
  global.STORY_GLOSSARY = {
    // Particles & copula
    'は': ['わ', 'topic marker ("as for…")', 'particle'],
    'が': ['が', 'subject marker; "but" (between clauses)', 'particle'],
    'を': ['お', 'direct object marker', 'particle'],
    'に': ['に', 'at (time), to (destination), in (location of existence); by (passive / causative)', 'particle'],
    'へ': ['え', 'towards (direction)', 'particle'],
    'で': ['で', 'at / in (place of action); by / with (means); linking form of だ (では)', 'particle'],
    'と': ['と', 'and; with; quotation marker; "when" (after a verb)', 'particle'],
    'の': ['の', 'possessive / linking particle ("\'s", "of")', 'particle'],
    'も': ['も', 'also, too; (with negative) not even', 'particle'],
    'や': ['や', 'and (non-exhaustive list)', 'particle'],
    'か': ['か', 'question marker', 'particle'],
    'よ': ['よ', 'sentence ending: "I tell you"', 'particle'],
    'ね': ['ね', 'sentence ending: "right?", "isn\'t it?"', 'particle'],
    'な': ['な', 'links a な-adjective to a noun', 'particle'],
    'な(feeling)': ['な', 'sentence ending expressing a feeling or wish (casual)', 'particle'],
    'から': ['から', 'from; because', 'particle'],
    'まで': ['まで', 'until; as far as', 'particle'],
    'ので': ['ので', 'because, so', 'conjunction'],
    'けれど': ['けれど', 'but, although', 'conjunction'],
    'ながら': ['ながら', 'while (doing)', 'particle'],
    'ばかり': ['ばかり', 'only, nothing but', 'particle'],
    'たい': ['たい', 'want to (after a verb stem)', 'auxiliary'],
    'ほど': ['ほど', 'extent; (〜ば〜ほど) the more…', 'particle'],
    'でも(even)': ['でも', 'even (〜でも)', 'particle'],
    'です': ['です', 'is, am, are (polite copula)', 'copula'],
    'だ': ['だ', 'is (plain copula)', 'copula'],
    'じゃ': ['じゃ', 'casual では: "with (this)", "in that case"', 'particle'],
    'ない': ['ない', 'not; there isn\'t (negative of ある)', 'auxiliary'],
    'はず': ['はず', 'should be, expected to be', 'noun'],
    'らしい': ['らしい', 'apparently, it seems', 'auxiliary'],
    'そう': ['そう', 'looks (like); I hear that', 'auxiliary'],
    'よう': ['よう', 'way, manner; (〜ように) so that', 'noun'],
    'こと': ['こと', 'thing, matter; (〜こと) turns a verb into a noun', 'noun'],
    'とき': ['とき', 'time; when', 'noun'],
    'ため': ['ため', 'sake; (〜ために) in order to', 'noun'],
    'ころ': ['ころ', 'time, days (when…)', 'noun'],
    'さん': ['さん', 'Mr. / Ms. (polite suffix)', 'suffix'],

    // Conjunctions & adverbs
    'それから': ['それから', 'after that, and then', 'conjunction'],
    'でも': ['でも', 'but, however', 'conjunction'],
    'だから': ['だから', 'so, therefore', 'conjunction'],
    'いつも': ['いつも', 'always', 'adverb'],
    'とても': ['とても', 'very', 'adverb'],
    'ちょっと': ['ちょっと', 'a little, a bit', 'adverb'],
    'たくさん': ['たくさん', 'a lot, many', 'adverb'],
    'また': ['また', 'again', 'adverb'],
    'まず': ['まず', 'first (of all)', 'adverb'],
    'なかなか': ['なかなか', '(with negative) not easily', 'adverb'],
    'すぐ': ['すぐ', 'immediately, right away', 'adverb'],
    'たぶん': ['たぶん', 'probably', 'adverb'],
    'もう': ['もう', 'already; (with age) now', 'adverb'],
    'まだ': ['まだ', 'still, (not) yet', 'adverb'],
    'ずっと': ['ずっと', 'for a long time, forever', 'adverb'],
    'だんだん': ['だんだん', 'gradually', 'adverb'],
    'それほど': ['それほど', '(with negative) not that much', 'adverb'],
    '少し': ['すこし', 'a little', 'adverb'],
    '初めて': ['はじめて', 'for the first time', 'adverb'],
    '確かに': ['たしかに', 'certainly, surely', 'adverb'],
    '本当に': ['ほんとうに', 'really, truly', 'adverb'],
    '全然': ['ぜんぜん', '(with negative) not at all', 'adverb'],
    '特に': ['とくに', 'especially', 'adverb'],
    '必ず': ['かならず', 'always, without fail', 'adverb'],
    '改めて': ['あらためて', 'once again, anew', 'adverb'],
    '一生懸命': ['いっしょうけんめい', 'with all one\'s might, very hard', 'adverb'],
    '最後に': ['さいごに', 'finally, at the end', 'adverb'],
    '長く': ['ながく', 'for a long time', 'adverb'],

    // Pronouns & demonstratives
    '私': ['わたし', 'I, me', 'pronoun'],
    'これ': ['これ', 'this (one)', 'pronoun'],
    'それ': ['それ', 'that (one)', 'pronoun'],
    'この': ['この', 'this (+ noun)', 'pre-noun'],
    'その': ['その', 'that (+ noun)', 'pre-noun'],
    '何': ['なに', 'what', 'pronoun'],
    'いくら': ['いくら', 'how much (price)', 'question word'],
    '小さな': ['ちいさな', 'small, little (+ noun)', 'pre-noun'],

    // People & names
    '田中さん': ['たなかさん', 'Tanaka-san (a family name)', 'name'],
    '木村さん': ['きむらさん', 'Kimura-san (a family name)', 'name'],
    'タマ': ['タマ', 'Tama (a common cat name)', 'name'],
    'ケン': ['ケン', 'Ken (a given name)', 'name'],
    '会社員': ['かいしゃいん', 'office worker, company employee', 'noun'],
    '人': ['ひと', 'person, people', 'noun'],
    '友だち': ['ともだち', 'friend', 'noun'],
    '二人': ['ふたり', 'two people', 'noun'],
    'おじいさん': ['おじいさん', 'old man; grandfather', 'noun'],
    '祖母': ['そぼ', '(my) grandmother', 'noun'],
    'おばあちゃん': ['おばあちゃん', 'grandma (affectionate)', 'noun'],
    '母': ['はは', '(my) mother', 'noun'],
    '息子': ['むすこ', 'son', 'noun'],
    '息子さん': ['むすこさん', '(someone else\'s) son', 'noun'],
    '店長': ['てんちょう', 'shop manager, owner', 'noun'],
    '駅員': ['えきいん', 'station staff', 'noun'],
    '警察': ['けいさつ', 'police', 'noun'],

    // Time
    '毎朝': ['まいあさ', 'every morning', 'noun'],
    '毎日': ['まいにち', 'every day', 'noun'],
    '朝': ['あさ', 'morning', 'noun'],
    '夜': ['よる', 'night, evening', 'noun'],
    '昼': ['ひる', 'noon, midday', 'noun'],
    '昨日': ['きのう', 'yesterday', 'noun'],
    '土曜日': ['どようび', 'Saturday', 'noun'],
    '日曜日': ['にちようび', 'Sunday', 'noun'],
    '来週': ['らいしゅう', 'next week', 'noun'],
    '先週': ['せんしゅう', 'last week', 'noun'],
    '先月': ['せんげつ', 'last month', 'noun'],
    '去年': ['きょねん', 'last year', 'noun'],
    '春': ['はる', 'spring', 'noun'],
    '夏休み': ['なつやすみ', 'summer holidays', 'noun'],
    '一日': ['いちにち', 'one day; a (whole) day', 'noun'],
    '日': ['ひ', 'day', 'noun'],
    '今': ['いま', 'now', 'noun'],
    '最近': ['さいきん', 'recently, lately', 'noun'],
    '最初': ['さいしょ', 'the beginning, at first', 'noun'],
    '次': ['つぎ', 'next', 'noun'],
    '以来': ['いらい', 'since (then)', 'noun'],
    '六時': ['ろくじ', 'six o\'clock', 'noun'],
    '四時': ['よじ', 'four o\'clock', 'noun'],
    '八十歳': ['はちじゅっさい', 'eighty years old', 'noun'],

    // Places & things
    '会社': ['かいしゃ', 'company, office', 'noun'],
    '電車': ['でんしゃ', 'train', 'noun'],
    '駅': ['えき', 'station', 'noun'],
    '駅前': ['えきまえ', 'in front of the station', 'noun'],
    '中': ['なか', 'inside, middle; (〜の中で) among', 'noun'],
    '上': ['うえ', 'on top, above', 'noun'],
    '前': ['まえ', 'front; before', 'noun'],
    '近く': ['ちかく', 'near, nearby', 'noun'],
    '本': ['ほん', 'book', 'noun'],
    '雨': ['あめ', 'rain', 'noun'],
    '傘': ['かさ', 'umbrella', 'noun'],
    '二本': ['にほん', 'two (long, thin objects)', 'counter'],
    '朝ご飯': ['あさごはん', 'breakfast', 'noun'],
    'パン': ['パン', 'bread', 'noun'],
    'コーヒー': ['コーヒー', 'coffee', 'noun'],
    'デパート': ['デパート', 'department store', 'noun'],
    'セーター': ['セーター', 'sweater', 'noun'],
    '三階': ['さんがい', 'third floor', 'noun'],
    '服': ['ふく', 'clothes', 'noun'],
    '店': ['みせ', 'shop, store', 'noun'],
    '五千円': ['ごせんえん', '5,000 yen', 'noun'],
    '喫茶店': ['きっさてん', 'café, coffee shop', 'noun'],
    'ケーキ': ['ケーキ', 'cake', 'noun'],
    '家': ['いえ', 'house, home', 'noun'],
    '猫': ['ねこ', 'cat', 'noun'],
    '名前': ['なまえ', 'name', 'noun'],
    '魚': ['さかな', 'fish', 'noun'],
    '窓': ['まど', 'window', 'noun'],
    '部屋': ['へや', 'room', 'noun'],
    '足': ['あし', 'foot, leg', 'noun'],
    '机': ['つくえ', 'desk', 'noun'],
    'ペン': ['ペン', 'pen', 'noun'],
    '一番': ['いちばん', 'number one, the most, best', 'noun'],
    '日本': ['にほん', 'Japan', 'noun'],
    '東京': ['とうきょう', 'Tokyo', 'noun'],
    '浅草': ['あさくさ', 'Asakusa (an old district of Tokyo)', 'noun'],
    'お寺': ['おてら', 'Buddhist temple', 'noun'],
    '道': ['みち', 'road, way', 'noun'],
    '日本語': ['にほんご', 'Japanese (language)', 'noun'],
    'ありがとうございます': ['ありがとうございます', 'thank you (polite)', 'expression'],
    'ホテル': ['ホテル', 'hotel', 'noun'],
    'ラーメン': ['ラーメン', 'ramen (noodle soup)', 'noun'],
    '舌': ['した', 'tongue', 'noun'],
    'やけど': ['やけど', 'a burn; (やけどする) to burn oneself', 'noun'],
    '公園': ['こうえん', 'park', 'noun'],
    'テニス': ['テニス', 'tennis', 'noun'],
    '約束': ['やくそく', 'promise, plans (to meet)', 'noun'],
    '電話': ['でんわ', 'telephone, phone call', 'noun'],
    'メッセージ': ['メッセージ', 'message', 'noun'],
    '映画': ['えいが', 'movie', 'noun'],
    '映画館': ['えいがかん', 'movie theater', 'noun'],
    '返事': ['へんじ', 'reply, answer', 'noun'],
    '洗濯物': ['せんたくもの', 'laundry', 'noun'],
    '田舎': ['いなか', 'the countryside; hometown', 'noun'],
    '手紙': ['てがみ', 'letter', 'noun'],
    '畑': ['はたけ', 'field (for vegetables)', 'noun'],
    '野菜': ['やさい', 'vegetables', 'noun'],
    '箱': ['はこ', 'box', 'noun'],
    'トマト': ['トマト', 'tomato', 'noun'],
    '音楽': ['おんがく', 'music', 'noun'],
    'サラダ': ['サラダ', 'salad', 'noun'],
    'お礼': ['おれい', 'thanks, gratitude', 'noun'],
    '学校': ['がっこう', 'school', 'noun'],
    '仕事': ['しごと', 'work, job', 'noun'],
    '帰り': ['かえり', 'the way home, return', 'noun'],
    '財布': ['さいふ', 'wallet', 'noun'],
    'かばん': ['かばん', 'bag', 'noun'],
    'お金': ['おかね', 'money', 'noun'],
    'カード': ['カード', 'card (credit / bank card)', 'noun'],
    '免許証': ['めんきょしょう', 'driver\'s license', 'noun'],
    '全部': ['ぜんぶ', 'all, everything', 'noun'],
    '届け': ['とどけ', 'report, notification (to the authorities)', 'noun'],
    '番号': ['ばんごう', 'number', 'noun'],
    'ベンチ': ['ベンチ', 'bench', 'noun'],
    '中身': ['なかみ', 'contents', 'noun'],
    '世の中': ['よのなか', 'the world, society', 'noun'],
    '落とし物': ['おとしもの', 'lost item, something dropped', 'noun'],
    'パン屋': ['パンや', 'bakery', 'noun'],
    'フランス': ['フランス', 'France', 'noun'],
    'フランス語': ['フランスご', 'French (language)', 'noun'],
    '作り方': ['つくりかた', 'how to make, recipe', 'noun'],
    '町': ['まち', 'town', 'noun'],
    '自分': ['じぶん', 'oneself, one\'s own', 'noun'],
    '味': ['あじ', 'taste, flavour', 'noun'],
    'メロンパン': ['メロンパン', 'melon bread (a sweet bun)', 'noun'],
    '人気': ['にんき', 'popularity', 'noun'],
    '失敗': ['しっぱい', 'mistake, failure', 'noun'],
    '練習': ['れんしゅう', 'practice', 'noun'],
    '勉強': ['べんきょう', 'study', 'noun'],
    '元気': ['げんき', 'healthy, lively, energetic', 'な-adjective'],

    // Adjectives
    '多い': ['おおい', 'many, a lot', 'い-adjective'],
    '多すぎる': ['おおすぎる', 'too many', 'ichidan verb'],
    '新しい': ['あたらしい', 'new', 'い-adjective'],
    '青い': ['あおい', 'blue', 'い-adjective'],
    '赤い': ['あかい', 'red', 'い-adjective'],
    '白い': ['しろい', 'white', 'い-adjective'],
    '小さい': ['ちいさい', 'small', 'い-adjective'],
    '高い': ['たかい', 'expensive; high, tall', 'い-adjective'],
    'かわいい': ['かわいい', 'cute', 'い-adjective'],
    '楽しい': ['たのしい', 'fun, enjoyable', 'い-adjective'],
    '欲しい': ['ほしい', 'wanted, desired ("I want")', 'い-adjective'],
    '熱い': ['あつい', 'hot (to the touch)', 'い-adjective'],
    'おいしい': ['おいしい', 'delicious', 'い-adjective'],
    'うれしい': ['うれしい', 'happy, glad', 'い-adjective'],
    'いい': ['いい', 'good', 'い-adjective'],
    '長い': ['ながい', 'long', 'い-adjective'],
    '悪い': ['わるい', 'bad', 'い-adjective'],
    '若い': ['わかい', 'young', 'い-adjective'],
    'きれい': ['きれい', 'pretty; clean', 'な-adjective'],
    '好き': ['すき', 'liked, favourite', 'な-adjective'],
    '大好き': ['だいすき', 'loved, really liked', 'な-adjective'],
    '親切': ['しんせつ', 'kind', 'な-adjective'],
    '楽しみ': ['たのしみ', 'something to look forward to', 'noun / な-adjective'],
    'だめ': ['だめ', 'no good, not allowed', 'な-adjective'],

    // Verbs
    'ある': ['ある', 'to be, to exist (things); to have', 'う-verb'],
    'いる': ['いる', 'to be, to exist (people, animals); after て-form: be ~ing', 'ichidan verb'],
    'する': ['する', 'to do', 'irregular verb'],
    'くる': ['くる', 'after て-form: towards the speaker', 'irregular verb'],
    '来る': ['くる', 'to come', 'irregular verb'],
    '行く': ['いく', 'to go', 'う-verb'],
    'なる': ['なる', 'to become', 'う-verb'],
    'できる': ['できる', 'to be able to do, can', 'ichidan verb'],
    '起きる': ['おきる', 'to get up, to wake up', 'ichidan verb'],
    '乗る': ['のる', 'to get on, to ride (a train, bus…)', 'う-verb'],
    '読む': ['よむ', 'to read', 'う-verb'],
    '買う': ['かう', 'to buy', 'う-verb'],
    '入る': ['はいる', 'to enter, to go in; to be contained', 'う-verb'],
    '食べる': ['たべる', 'to eat', 'ichidan verb'],
    '言う': ['いう', 'to say', 'う-verb'],
    '寝る': ['ねる', 'to sleep', 'ichidan verb'],
    '走る': ['はしる', 'to run', 'う-verb'],
    '遊ぶ': ['あそぶ', 'to play', 'う-verb'],
    '落とす': ['おとす', 'to drop, to knock down', 'う-verb'],
    '着く': ['つく', 'to arrive', 'う-verb'],
    '見る': ['みる', 'to see, to look at, to watch', 'ichidan verb'],
    '進む': ['すすむ', 'to move forward, to advance', 'う-verb'],
    'わかる': ['わかる', 'to understand, to know', 'う-verb'],
    '聞く': ['きく', 'to ask; to listen, to hear', 'う-verb'],
    '連れる': ['つれる', 'to take (someone) along', 'ichidan verb'],
    'くれる': ['くれる', 'to give (to me); after て-form: do for me', 'ichidan verb'],
    'あげる': ['あげる', 'to give; after て-form: do for someone', 'ichidan verb'],
    'しまう': ['しまう', 'after て-form: to end up ~, to do completely', 'う-verb'],
    '勉強する': ['べんきょうする', 'to study', 'する-verb'],
    '降る': ['ふる', 'to fall (rain, snow)', 'う-verb'],
    '思う': ['おもう', 'to think', 'う-verb'],
    'かける': ['かける', 'to make (a phone call)', 'ichidan verb'],
    'やめる': ['やめる', 'to stop, to give up, to call off', 'ichidan verb'],
    '入れる': ['いれる', 'to put in, to bring in', 'ichidan verb'],
    '急ぐ': ['いそぐ', 'to hurry', 'う-verb'],
    '出る': ['でる', 'to leave, to go out', 'ichidan verb'],
    '忘れる': ['わすれる', 'to forget; to leave behind', 'ichidan verb'],
    '持つ': ['もつ', 'to hold, to carry, to have', 'う-verb'],
    '待つ': ['まつ', 'to wait', 'う-verb'],
    '笑う': ['わらう', 'to laugh, to smile', 'う-verb'],
    '住む': ['すむ', 'to live (somewhere)', 'う-verb'],
    '届く': ['とどく', 'to arrive, to be delivered', 'う-verb'],
    '育てる': ['そだてる', 'to grow, to raise', 'ichidan verb'],
    '書く': ['かく', 'to write', 'う-verb'],
    '作る': ['つくる', 'to make', 'う-verb'],
    '会う': ['あう', 'to meet', 'う-verb'],
    '喜ぶ': ['よろこぶ', 'to be pleased, to be glad', 'う-verb'],
    'なくす': ['なくす', 'to lose', 'う-verb'],
    '帰る': ['かえる', 'to go home, to return', 'う-verb'],
    '気が付く': ['きがつく', 'to notice, to realise', 'expression'],
    '焦る': ['あせる', 'to panic, to be flustered', 'う-verb'],
    '出す': ['だす', 'to hand in, to submit; to take out', 'う-verb'],
    '知る': ['しる', 'to know (知らない: unknown)', 'う-verb'],
    'かかる': ['かかる', '(a phone call) to come in', 'う-verb'],
    'よる': ['よる', '(〜によると) according to', 'う-verb'],
    '見つかる': ['みつかる', 'to be found', 'う-verb'],
    '拾う': ['ひろう', 'to pick up (from the ground)', 'う-verb'],
    '届ける': ['とどける', 'to deliver; to hand in (to the police)', 'ichidan verb'],
    '受け取る': ['うけとる', 'to receive', 'う-verb'],
    'なくなる': ['なくなる', 'to go missing, to be gone', 'う-verb'],
    '感じる': ['かんじる', 'to feel', 'ichidan verb'],
    '見つける': ['みつける', 'to find', 'ichidan verb'],
    '焼く': ['やく', 'to bake, to grill', 'う-verb'],
    '学ぶ': ['まなぶ', 'to learn', 'う-verb'],
    '話す': ['はなす', 'to speak, to talk', 'う-verb'],
    '戻る': ['もどる', 'to return, to come back', 'う-verb'],
    '開く': ['ひらく', 'to open (a shop)', 'う-verb'],
    '売り切れる': ['うりきれる', 'to sell out', 'ichidan verb'],
    '手伝う': ['てつだう', 'to help', 'う-verb'],
    '愛する': ['あいする', 'to love', 'する-verb'],
    '続く': ['つづく', 'to continue, to last', 'う-verb'],
    '願う': ['ねがう', 'to hope, to wish', 'う-verb'],
  };

  global.STORIES_DATA = [
    // ── N5 ──────────────────────────────────────────────────────────────────
    {
      id: 'n5-tanaka-morning',
      level: 'n5',
      title: '田中[たなか]さんの朝[あさ]',
      titleEn: 'Tanaka-san\'s Morning',
      sentences: [
        { jp: '田中[たなか]さん は 会社員[かいしゃいん] です 。', en: 'Tanaka-san is an office worker.',
          grammar: ['wa-topic:田中さんは', 'desu:会社員です'] },
        { jp: '毎朝[まいあさ] 六時[ろくじ] に 起[お]きます>起きる 。', en: 'She gets up at six every morning.',
          grammar: ['ni-time:六時に', 'masu:起きます'] },
        { jp: '朝[あさ]ご飯[はん] は パン と コーヒー です 。', en: 'Breakfast is bread and coffee.',
          grammar: ['wa-topic:朝ご飯は', 'to-and:パンとコーヒー'] },
        { jp: 'それから 、 電車[でんしゃ] で 会社[かいしゃ] に 行[い]きます>行く 。', en: 'Then she goes to the office by train.',
          grammar: ['de-means:電車で', 'ni-destination:会社に行きます'] },
        { jp: '電車[でんしゃ] は いつも 人[ひと] が 多[おお]い です 。', en: 'The train is always crowded.',
          grammar: ['wa-ga:電車はいつも人が多い', 'i-adj-desu:多いです'] },
        { jp: '田中[たなか]さん は 電車[でんしゃ] の 中[なか] で 本[ほん] を 読[よ]みます>読む 。', en: 'Tanaka-san reads a book on the train.',
          grammar: ['no-possessive:電車の中', 'de-place:中で', 'wo-object:本を読みます'] },
        { jp: '昨日[きのう] は 雨[あめ] でした>です 。', en: 'Yesterday it rained.',
          grammar: ['deshita:雨でした'] },
        { jp: 'でも 、 傘[かさ] が ありませんでした>ある 。', en: 'But she didn\'t have an umbrella.',
          grammar: ['ga-subject:傘が', 'masen-deshita:ありませんでした'] },
        { jp: '駅[えき] で 新[あたら]しい 傘[かさ] を 買[か]いました>買う 。', en: 'She bought a new umbrella at the station.',
          grammar: ['de-place:駅で', 'i-adj-noun:新しい傘', 'masu-past:買いました'] },
        { jp: '青[あお]くて>青い きれい な 傘[かさ] です 。', en: 'It is a pretty blue umbrella.',
          grammar: ['kute:青くて', 'na-adj-noun:きれいな傘'] },
        { jp: '田中[たなか]さん は その 傘[かさ] が とても 好[す]き です 。', en: 'Tanaka-san likes that umbrella very much.',
          grammar: ['kosoado:その傘', 'ga-suki:傘がとても好き'] },
      ],
    },
    {
      id: 'n5-weekend-shopping',
      level: 'n5',
      title: '週末[しゅうまつ]の買[か]い物[もの]',
      titleEn: 'Weekend Shopping',
      sentences: [
        { jp: '土曜日[どようび] 、 友[とも]だち と デパート へ 行[い]きました>行く 。', en: 'On Saturday, I went to a department store with a friend.',
          grammar: ['to-with:友だちと', 'he-direction:デパートへ', 'masu-past:行きました'] },
        { jp: '私[わたし] は 新[あたら]しい セーター が 欲[ほ]しかった>欲しい です 。', en: 'I wanted a new sweater.',
          grammar: ['hoshii:セーターが欲しかった', 'i-adj-past:欲しかったです'] },
        { jp: '三階[さんがい] に 服[ふく] の 店[みせ] が たくさん あります>ある 。', en: 'On the third floor there are lots of clothes shops.',
          grammar: ['ni-aru:三階に服の店がたくさんあります', 'no-possessive:服の店'] },
        { jp: '赤[あか]い セーター と 白[しろ]い セーター が ありました>ある 。', en: 'There was a red sweater and a white sweater.',
          grammar: ['i-adj-noun:赤いセーター', 'to-and:赤いセーターと白いセーター', 'masu-past:ありました'] },
        { jp: '「 この 赤[あか]い セーター は いくら です か 。 」', en: '"How much is this red sweater?"',
          grammar: ['kosoado:この', 'ka-question:いくらですか'] },
        { jp: '「 五千円[ごせんえん] です 。 」', en: '"It\'s 5,000 yen."',
          grammar: ['desu:五千円です'] },
        { jp: 'ちょっと 高[たか]かった>高い です が 、 とても かわいかった>かわいい です 。', en: 'It was a little expensive, but it was very cute.',
          grammar: ['i-adj-past:高かったです', 'ga-but:高かったですが'] },
        { jp: 'だから 、 その セーター を 買[か]いました>買う 。', en: 'So I bought that sweater.',
          grammar: ['dakara:だから', 'wo-object:セーターを買いました'] },
        { jp: 'それから 、 二人[ふたり] で 喫茶店[きっさてん] に 入[はい]って>入る 、 ケーキ を 食[た]べました>食べる 。', en: 'After that, the two of us went into a café and ate cake.',
          grammar: ['de-together:二人で', 'te-sequence:入って、ケーキを食べました'] },
        { jp: '友[とも]だち は 「 また 来週[らいしゅう] 来[き]ましょう>来る 。 」 と 言[い]いました>言う 。', en: 'My friend said, "Let\'s come again next week."',
          grammar: ['mashou:来ましょう', 'to-iu:と言いました'] },
        { jp: '楽[たの]しい 一日[いちにち] でした>です 。', en: 'It was a fun day.',
          grammar: ['i-adj-noun:楽しい一日', 'deshita:一日でした'] },
      ],
    },
    {
      id: 'n5-tama-the-cat',
      level: 'n5',
      title: '猫[ねこ]のタマ',
      titleEn: 'Tama the Cat',
      sentences: [
        { jp: '私[わたし] の 家[いえ] に は 猫[ねこ] が います>いる 。', en: 'There is a cat at my house.',
          grammar: ['ni-wa:家には', 'ni-aru:猫がいます'] },
        { jp: '名前[なまえ] は タマ です 。', en: 'Her name is Tama.',
          grammar: ['wa-topic:名前は', 'desu:タマです'] },
        { jp: 'タマ は 白[しろ]くて>白い 小[ちい]さい 猫[ねこ] です 。', en: 'Tama is a small white cat.',
          grammar: ['kute:白くて', 'i-adj-noun:小さい猫'] },
        { jp: 'タマ は 魚[さかな] が 大好[だいす]き です 。', en: 'Tama loves fish.',
          grammar: ['ga-suki:魚が大好き'] },
        { jp: '毎日[まいにち] 、 窓[まど] の 近[ちか]く で 寝[ね]て>寝る います>いる 。', en: 'Every day, she sleeps near the window.',
          grammar: ['no-possessive:窓の近く', 'te-iru:寝ています'] },
        { jp: 'でも 、 夜[よる] は とても 元気[げんき] です 。', en: 'But at night she is very lively.',
          grammar: ['wa-topic:夜は', 'desu:元気です'] },
        { jp: '部屋[へや] の 中[なか] を 走[はし]ったり>走る 、 私[わたし] の 足[あし] で 遊[あそ]んだり>遊ぶ します>する 。', en: 'She does things like running around the room and playing with my feet.',
          grammar: ['tari:走ったり、私の足で遊んだりします', 'de-means:足で'] },
        { jp: '昨日[きのう] 、 タマ は 机[つくえ] の 上[うえ] の ペン を 落[お]としました>落とす 。', en: 'Yesterday, Tama knocked the pen on the desk onto the floor.',
          grammar: ['no-possessive:机の上のペン', 'masu-past:落としました'] },
        { jp: '「 タマ 、 だめ です よ 。 」', en: '"Tama, you mustn\'t do that!"',
          grammar: ['yo:だめですよ'] },
        { jp: 'でも 、 タマ は 何[なに] も 言[い]いません>言う 。', en: 'But Tama doesn\'t say anything.',
          grammar: ['nani-mo-neg:何も言いません', 'masen:言いません'] },
        { jp: 'タマ は 私[わたし] の 一番[いちばん] の 友[とも]だち です 。', en: 'Tama is my best friend.',
          grammar: ['ichiban:一番の友だち'] },
      ],
    },

    // ── N4 ──────────────────────────────────────────────────────────────────
    {
      id: 'n4-first-trip',
      level: 'n4',
      title: '初[はじ]めての日本[にほん]旅行[りょこう]',
      titleEn: 'My First Trip to Japan',
      sentences: [
        { jp: '去年[きょねん] の 春[はる] 、 私[わたし] は 初[はじ]めて 日本[にほん] へ 行[い]きました>行く 。', en: 'Last spring, I went to Japan for the first time.',
          grammar: ['no-possessive:去年の春', 'he-direction:日本へ行きました'] },
        { jp: '日本[にほん] へ 行[い]った>行く こと が なかった>ない ので 、 とても 楽[たの]しみ でした>です 。', en: 'I had never been to Japan, so I was really looking forward to it.',
          grammar: ['ta-koto-ga-aru:行ったことがなかった', 'node:なかったので'] },
        { jp: '東京[とうきょう] に 着[つ]いて>着く 、 まず 浅草[あさくさ] の お寺[てら] を 見[み]>見る に 行[い]きました>行く 。', en: 'When I arrived in Tokyo, I first went to see the temple in Asakusa.',
          grammar: ['te-sequence:着いて、', 'ni-iku-purpose:見に行きました'] },
        { jp: '人[ひと] が 多[おお]すぎて>多すぎる 、 なかなか 前[まえ] に 進[すす]めませんでした>進む 。', en: 'There were too many people, and I could hardly move forward.',
          grammar: ['sugiru:多すぎて', 'nakanaka-neg:なかなか前に進めませんでした', 'potential:進めませんでした'] },
        { jp: '道[みち] が わからなくなって>わかる 、 近[ちか]く に いた>いる おじいさん に 聞[き]きました>聞く 。', en: 'I lost my way, so I asked an old man who was nearby.',
          grammar: ['naku-naru:わからなくなって', 'relative-clause:近くにいたおじいさん'] },
        { jp: 'おじいさん は 親切[しんせつ] に 駅[えき] まで 連[つ]れて>連れる 行[い]って>行く くれました>くれる 。', en: 'The old man kindly took me all the way to the station.',
          grammar: ['na-adverb:親切に', 'made:駅まで', 'te-kureru:連れて行ってくれました'] },
        { jp: '日本語[にほんご] で 「 ありがとうございます 」 と 言[い]えて>言う 、 うれしかった>うれしい です 。', en: 'I was happy that I could say "thank you" in Japanese.',
          grammar: ['de-means:日本語で', 'potential:言えて', 'te-reason:言えて、うれしかった'] },
        { jp: '夜[よる] は ホテル の 近[ちか]く で ラーメン を 食[た]べました>食べる 。', en: 'In the evening, I ate ramen near the hotel.',
          grammar: ['de-place:近くで', 'masu-past:食べました'] },
        { jp: '熱[あつ]くて>熱い 、 少[すこ]し 舌[した] を やけど して>する しまいました>しまう 。', en: 'It was so hot that I burned my tongue a little.',
          grammar: ['kute:熱くて', 'te-shimau:やけどしてしまいました'] },
        { jp: 'でも 、 今[いま] まで 食[た]べた>食べる ラーメン の 中[なか] で 一番[いちばん] おいしかった>おいしい です 。', en: 'But it was the most delicious ramen I have ever eaten.',
          grammar: ['relative-clause:今まで食べたラーメン', 'no-naka-de-ichiban:ラーメンの中で一番おいしかった'] },
        { jp: 'また 日本[にほん] に 行[い]ける>行く よう に 、 今[いま] 毎日[まいにち] 日本語[にほんご] を 勉強[べんきょう] して>する います>いる 。', en: 'So that I can go to Japan again, I am now studying Japanese every day.',
          grammar: ['potential:行ける', 'you-ni:行けるように', 'te-iru:勉強しています'] },
      ],
    },
    {
      id: 'n4-rainy-promise',
      level: 'n4',
      title: '雨[あめ]の日[ひ]の約束[やくそく]',
      titleEn: 'A Rainy-Day Promise',
      sentences: [
        { jp: '日曜日[にちようび] に 、 友[とも]だち の ケン と 公園[こうえん] で テニス を する 約束[やくそく] を しました>する 。', en: 'I made plans to play tennis in the park with my friend Ken on Sunday.',
          grammar: ['no-possessive:友だちのケン', 'relative-clause:テニスをする約束'] },
        { jp: 'でも 、 朝[あさ] 起[お]きたら>起きる 、 雨[あめ] が 降[ふ]って>降る いました>いる 。', en: 'But when I got up in the morning, it was raining.',
          grammar: ['tara:起きたら', 'te-iru:降っていました'] },
        { jp: '「 これ じゃ 、 テニス は できない>できる 。 」 と 思[おも]いました>思う 。', en: 'I thought, "We can\'t play tennis like this."',
          grammar: ['potential:できない', 'to-omou:と思いました'] },
        { jp: 'ケン に 電話[でんわ] を かけよう>かける と 思[おも]った>思う とき 、 ケン から メッセージ が 来[き]ました>来る 。', en: 'Just as I was about to call Ken, a message came from him.',
          grammar: ['volitional-to-omou:かけようと思った', 'toki:思ったとき', 'kara-from:ケンから'] },
        { jp: '「 雨[あめ] だ から 、 テニス は やめて>やめる 、 映画[えいが] を 見[み]>見る に 行[い]かない>行く ？ 」', en: '"It\'s raining, so how about we skip tennis and go see a movie?"',
          grammar: ['kara-reason:雨だから', 'ni-iku-purpose:見に行かない', 'nai-invitation:行かない？'] },
        { jp: '私[わたし] は すぐ 「 いい ね 。 」 と 返事[へんじ] を しました>する 。', en: 'I replied right away, "Sounds good."',
          grammar: ['ne:いいね'] },
        { jp: '映画館[えいがかん] へ 行[い]く 前[まえ] に 、 洗濯物[せんたくもの] を 中[なか] に 入[い]れなければ>入れる なりませんでした>なる 。', en: 'Before going to the cinema, I had to bring the laundry inside.',
          grammar: ['mae-ni:行く前に', 'nakereba-naranai:入れなければなりませんでした'] },
        { jp: '急[いそ]いで>急ぐ 家[いえ] を 出[で]た>出る ので 、 傘[かさ] を 忘[わす]れて>忘れる しまいました>しまう 。', en: 'I left the house in a hurry, so I forgot my umbrella.',
          grammar: ['node:出たので', 'te-shimau:忘れてしまいました'] },
        { jp: '駅[えき] に 着[つ]く と 、 ケン が 傘[かさ] を 二本[にほん] 持[も]って>持つ 待[ま]って>待つ いました>いる 。', en: 'When I got to the station, Ken was waiting, holding two umbrellas.',
          grammar: ['to-conditional:着くと', 'te-iru:待っていました'] },
        { jp: '「 たぶん 忘[わす]れる と 思[おも]った>思う よ 。 」 と ケン は 笑[わら]いました>笑う 。', en: '"I figured you\'d probably forget," Ken laughed.',
          grammar: ['to-omou:忘れると思った', 'yo:思ったよ'] },
        { jp: '雨[あめ] の 日[ひ] でも>でも(even) 、 いい 友[とも]だち が いれば>いる 楽[たの]しい です 。', en: 'Even on a rainy day, it\'s fun if you have a good friend.',
          grammar: ['demo-even:日でも', 'ba-conditional:いれば'] },
      ],
    },
    {
      id: 'n4-grandmas-letter',
      level: 'n4',
      title: 'おばあちゃんの手紙[てがみ]',
      titleEn: 'Grandma\'s Letter',
      sentences: [
        { jp: '先週[せんしゅう] 、 田舎[いなか] に 住[す]んで>住む いる 祖母[そぼ] から 手紙[てがみ] が 届[とど]きました>届く 。', en: 'Last week, a letter arrived from my grandmother, who lives in the countryside.',
          grammar: ['te-iru:住んでいる', 'relative-clause:田舎に住んでいる祖母', 'kara-from:祖母から'] },
        { jp: '祖母[そぼ] は もう 八十歳[はちじゅっさい] です が 、 毎日[まいにち] 畑[はたけ] で 野菜[やさい] を 育[そだ]てて>育てる います>いる 。', en: 'My grandmother is already eighty, but she grows vegetables in her field every day.',
          grammar: ['ga-but:八十歳ですが', 'te-iru:育てています'] },
        { jp: '手紙[てがみ] に は 「 元気[げんき] に して>する います>いる か 。 」 と 書[か]いて>書く ありました>ある 。', en: 'The letter said, "Are you keeping well?"',
          grammar: ['ni-wa:手紙には', 'te-aru:書いてありました'] },
        { jp: '箱[はこ] の 中[なか] に は 、 祖母[そぼ] が 作[つく]った>作る トマト が 入[はい]って>入る いました>いる 。', en: 'Inside the box were tomatoes that my grandmother had grown.',
          grammar: ['relative-clause:祖母が作ったトマト', 'te-iru:入っていました'] },
        { jp: 'とても 赤[あか]くて>赤い 、 おいし>おいしい そう でした>です 。', en: 'They were very red and looked delicious.',
          grammar: ['kute:赤くて', 'sou-looks:おいしそうでした'] },
        { jp: '私[わたし] は 音楽[おんがく] を 聞[き]き>聞く ながら 、 トマト で サラダ を 作[つく]りました>作る 。', en: 'I made a salad with the tomatoes while listening to music.',
          grammar: ['nagara:聞きながら', 'de-means:トマトで'] },
        { jp: '母[はは] は 「 おばあちゃん に お礼[れい] の 手紙[てがみ] を 書[か]いて>書く あげて>あげる 。 」 と 言[い]いました>言う 。', en: 'My mother said, "Write grandma a thank-you letter."',
          grammar: ['te-ageru:書いてあげて', 'te-request:あげて。'] },
        { jp: '夜[よる] 、 祖母[そぼ] に 長[なが]い 手紙[てがみ] を 書[か]きました>書く 。', en: 'That night, I wrote my grandmother a long letter.',
          grammar: ['i-adj-noun:長い手紙', 'masu-past:書きました'] },
        { jp: '学校[がっこう] の こと や 友[とも]だち の こと を たくさん 書[か]きました>書く 。', en: 'I wrote a lot about school, my friends and so on.',
          grammar: ['ya-and:学校のことや友だちのこと'] },
        { jp: '最後[さいご]に 「 夏休[なつやす]み に 会[あ]い>会う に 行[い]きます>行く 。 」 と 書[か]きました>書く 。', en: 'At the end, I wrote, "I\'ll come to see you in the summer holidays."',
          grammar: ['ni-iku-purpose:会いに行きます', 'to-iu:と書きました'] },
        { jp: '祖母[そぼ] が 喜[よろこ]んで>喜ぶ くれる と いい な>な(feeling) と 思[おも]います>思う 。', en: 'I hope she\'ll be pleased.',
          grammar: ['te-kureru:喜んでくれる', 'to-ii:くれるといいな', 'to-omou:と思います'] },
      ],
    },

    // ── N3 ──────────────────────────────────────────────────────────────────
    {
      id: 'n3-lost-wallet',
      level: 'n3',
      title: 'なくした財布[さいふ]',
      titleEn: 'The Lost Wallet',
      sentences: [
        { jp: '先月[せんげつ] 、 仕事[しごと] の 帰[かえ]り に 財布[さいふ] を なくして>なくす しまった>しまう 。', en: 'Last month, I lost my wallet on the way home from work.',
          grammar: ['plain-form:しまった', 'te-shimau:なくしてしまった'] },
        { jp: '電車[でんしゃ] に 乗[の]る>乗る 前[まえ] は 、 確[たし]かに かばん の 中[なか] に あった>ある はず だ 。', en: 'Before I got on the train, it should definitely have been in my bag.',
          grammar: ['mae-ni:乗る前', 'hazu:あったはずだ'] },
        { jp: '家[いえ] に 帰[かえ]って>帰る から 気[き]が付[つ]いた>気が付く ので 、 本当[ほんとう]に 焦[あせ]った>焦る 。', en: 'I only noticed after I got home, so I really panicked.',
          grammar: ['te-kara:帰ってから', 'node:気が付いたので'] },
        { jp: 'お金[かね] は それほど 入[はい]って>入る いなかった>いる けれど 、 カード や 免許証[めんきょしょう] が 全部[ぜんぶ] 入[はい]って>入る いた>いる 。', en: 'There wasn\'t much money in it, but my cards, my driver\'s license — everything was in it.',
          grammar: ['sorehodo-neg:それほど入っていなかった', 'keredo:いなかったけれど', 'ya-and:カードや免許証'] },
        { jp: 'すぐ に 警察[けいさつ] に 届[とど]け を 出[だ]す>出す こと に した>する 。', en: 'I decided to file a report with the police right away.',
          grammar: ['koto-ni-suru:出すことにした'] },
        { jp: '次[つぎ] の 日[ひ] 、 知[し]らない>知る 番号[ばんごう] から 電話[でんわ] が かかって>かかる きた>くる 。', en: 'The next day, I got a call from a number I didn\'t know.',
          grammar: ['relative-clause:知らない番号', 'te-kuru:かかってきた'] },
        { jp: '駅員[えきいん] に よる と 、 私[わたし] の 財布[さいふ] が 駅[えき] の ベンチ で 見[み]つかった>見つかる そう だ 。', en: 'According to the station staff, my wallet had been found on a bench at the station.',
          grammar: ['ni-yoru-to:駅員によると', 'sou-hearsay:見つかったそうだ'] },
        { jp: '親切[しんせつ] な 人[ひと] に 拾[ひろ]われて>拾う 、 駅[えき] に 届[とど]けられた>届ける らしい 。', en: 'Apparently a kind person picked it up and handed it in at the station.',
          grammar: ['passive:人に拾われて', 'passive:届けられた', 'rashii:届けられたらしい'] },
        { jp: '財布[さいふ] を 受[う]け取[と]った>受け取る とき 、 中身[なかみ] は 何[なに] も なくなって>なくなる いなかった>いる 。', en: 'When I got the wallet back, nothing inside was missing.',
          grammar: ['toki:受け取ったとき', 'nani-mo-neg:何もなくなっていなかった'] },
        { jp: '世[よ]の中[なか] は 悪[わる]い 人[ひと] ばかり で は ない と 、 改[あらた]めて 感[かん]じた>感じる 。', en: 'It made me feel once again that the world isn\'t full of bad people.',
          grammar: ['bakari-dewanai:悪い人ばかりではない', 'to-omou:ないと、改めて感じた'] },
        { jp: 'それ 以来[いらい] 、 落[お]とし物[もの] を 見[み]つけたら>見つける 、 必[かなら]ず 届[とど]ける よう に して>する いる 。', en: 'Since then, whenever I find a lost item, I make sure to hand it in.',
          grammar: ['tara:見つけたら', 'you-ni-suru:届けるようにしている'] },
      ],
    },
    {
      id: 'n3-town-bakery',
      level: 'n3',
      title: '町[まち]の小[ちい]さなパン屋[や]',
      titleEn: 'The Little Bakery in Town',
      sentences: [
        { jp: '駅前[えきまえ] に 小[ちい]さな パン屋[や] が ある 。', en: 'There is a small bakery in front of the station.',
          grammar: ['plain-form:ある', 'ni-aru:駅前に小さなパン屋がある'] },
        { jp: '店長[てんちょう] の 木村[きむら]さん は 、 毎朝[まいあさ] 四時[よじ] に 起[お]きて>起きる パン を 焼[や]く>焼く そう だ 。', en: 'I hear the owner, Kimura-san, gets up at four every morning to bake bread.',
          grammar: ['te-sequence:起きてパンを焼く', 'sou-hearsay:焼くそうだ'] },
        { jp: '若[わか]い ころ 、 木村[きむら]さん は パン の 作[つく]り方[かた] を 学[まな]ぶ ため に フランス へ 行[い]った>行く 。', en: 'When Kimura-san was young, they went to France to learn how to make bread.',
          grammar: ['kata:作り方', 'tame-ni:学ぶために'] },
        { jp: '最初[さいしょ] は フランス語[ご] が 全然[ぜんぜん] わからなかった>わかる が 、 だんだん 話[はな]せる>話す よう に なった>なる 。', en: 'At first they didn\'t understand any French, but they gradually became able to speak it.',
          grammar: ['zenzen-neg:全然わからなかった', 'potential:話せる', 'you-ni-naru:話せるようになった'] },
        { jp: '日本[にほん] に 戻[もど]って>戻る から 、 この 町[まち] に 自分[じぶん] の 店[みせ] を 開[ひら]いた>開く 。', en: 'After coming back to Japan, they opened their own shop in this town.',
          grammar: ['te-kara:戻ってから'] },
        { jp: '木村[きむら]さん の パン は 食[た]べれば>食べる 食[た]べる ほど 好[す]き に なる 味[あじ] だ 。', en: 'Kimura-san\'s bread has the kind of taste you like more the more you eat it.',
          grammar: ['ba-hodo:食べれば食べるほど', 'ni-naru:好きになる', 'relative-clause:好きになる味'] },
        { jp: '特[とく]に メロンパン は 人気[にんき] が あって>ある 、 昼[ひる] まで に 売[う]り切[き]れて>売り切れる しまう 。', en: 'The melon bread in particular is popular and sells out before noon.',
          grammar: ['made-ni:昼までに', 'te-shimau:売り切れてしまう'] },
        { jp: '最近[さいきん] 、 木村[きむら]さん は 息子[むすこ] に 店[みせ] を 手伝[てつだ]わせて>手伝う いる 。', en: 'Recently, Kimura-san has been having their son help out at the shop.',
          grammar: ['causative:息子に店を手伝わせて', 'te-iru:手伝わせている'] },
        { jp: '息子[むすこ]さん は まだ 失敗[しっぱい] して>する ばかり いる が 、 毎日[まいにち] 一生懸命[いっしょうけんめい] 練習[れんしゅう] して>する いる 。', en: 'The son still keeps making mistakes, but practises as hard as he can every day.',
          grammar: ['te-bakari:失敗してばかりいる', 'ga-but:いるが'] },
        { jp: '「 この 店[みせ] を 町[まち] の 人[ひと] に 長[なが]く 愛[あい]される>愛する 店[みせ] に し>する たい 」 と 木村[きむら]さん は 言[い]う>言う 。', en: '"I want to make this a shop that the people of this town will love for a long time," says Kimura-san.',
          grammar: ['passive:人に長く愛される', 'ni-suru:店にしたい', 'tai:したい'] },
        { jp: '私[わたし] も 、 この 店[みせ] が ずっと 続[つづ]く>続く こと を 願[ねが]って>願う いる 。', en: 'I also hope this shop will carry on for a long, long time.',
          grammar: ['koto-nominalizer:続くことを', 'te-iru:願っている'] },
      ],
    },
  ];
})(window);
