(function (global) {
  'use strict';

  // Graded reading stories for the Stories page (stories.html), grouped by
  // JLPT level.
  //
  // Each sentence's `jp` is a space-separated list of tokens. A token uses the
  // same inline `kanji[reading]` furigana markup as particles-data.js, and may
  // end in `>key` to point at a STORY_GLOSSARY entry other than its own plain
  // spelling — conjugated words point at their dictionary form this way
  // (`起[お]きます>起きる`). Punctuation tokens (。、「」？) aren't clickable.
  //
  // `grammar` lists `id:snippet` pairs: the id is a STORY_GRAMMAR key, and the
  // optional snippet is the exact stretch of the (furigana-stripped) sentence
  // that uses it, so the reader can highlight it. test_stories.js checks that
  // every token has a glossary entry and every snippet occurs in its sentence.

  global.STORY_GRAMMAR = {
    // ── N5 ──
    'wa-topic': { level: 'N5', title: 'は — topic marker', pattern: 'X は Y', note: 'Marks what the sentence is about ("as for X…"). Written は but read わ.' },
    'desu': { level: 'N5', title: 'です — polite "is"', pattern: 'Noun / な-adj + です', note: 'The polite copula: "X is Y". Its plain form is だ.' },
    'deshita': { level: 'N5', title: 'でした — polite "was"', pattern: 'Noun / な-adj + でした', note: 'Past tense of です.' },
    'masu': { level: 'N5', title: '〜ます — polite present', pattern: 'Verb stem + ます', note: 'Polite non-past form of a verb: covers habits ("every day I…") and the future ("I will…").' },
    'masu-past': { level: 'N5', title: '〜ました — polite past', pattern: 'Verb stem + ました', note: 'Polite past form: "did ~".' },
    'masen-deshita': { level: 'N5', title: '〜ませんでした — polite past negative', pattern: 'Verb stem + ませんでした', note: 'Polite "did not ~".' },
    'masen': { level: 'N5', title: '〜ません — polite negative', pattern: 'Verb stem + ません', note: 'Polite "does not / will not ~".' },
    'mashou': { level: 'N5', title: '〜ましょう — "let\'s"', pattern: 'Verb stem + ましょう', note: 'Suggests doing something together: "let\'s ~".' },
    'wo-object': { level: 'N5', title: 'を — direct object', pattern: 'Noun を Verb', note: 'Marks the thing the action is done to.' },
    'ga-subject': { level: 'N5', title: 'が — subject marker', pattern: 'Noun が Verb', note: 'Marks the subject, often new information or the thing that exists / happens.' },
    'ni-time': { level: 'N5', title: 'に — point in time', pattern: 'Time に Verb', note: 'Marks a specific time: 六時に "at six". Not used with relative times like 毎朝 or 昨日.' },
    'ni-destination': { level: 'N5', title: 'に — destination', pattern: 'Place に 行く / 来る / 帰る', note: 'Marks where you go to. Interchangeable with へ for movement.' },
    'he-direction': { level: 'N5', title: 'へ — direction', pattern: 'Place へ 行く', note: 'Marks the direction of movement ("towards"). Written へ but read え.' },
    'de-place': { level: 'N5', title: 'で — place of action', pattern: 'Place で Verb', note: 'Marks where an action happens.' },
    'de-means': { level: 'N5', title: 'で — means / material', pattern: 'Tool / transport / material で', note: 'Marks how something is done: by train, with tomatoes, in Japanese.' },
    'de-together': { level: 'N5', title: 'で — "as a group of"', pattern: 'Number of people で', note: '二人で = "the two of us (together)", 一人で = "alone".' },
    'to-and': { level: 'N5', title: 'と — "and" (complete list)', pattern: 'A と B', note: 'Joins nouns into a complete list: "A and B".' },
    'to-with': { level: 'N5', title: 'と — "with"', pattern: 'Person と Verb', note: 'Marks who you do something together with.' },
    'ya-and': { level: 'N5', title: 'や — "and" (examples)', pattern: 'A や B', note: 'Lists examples, implying there are others: "A, B, and so on".' },
    'no-possessive': { level: 'N5', title: 'の — linking nouns', pattern: 'Noun の Noun', note: 'Links two nouns: possession ("my house"), description ("clothes shop") or position ("inside the train").' },
    'wa-ga': { level: 'N5', title: 'X は Y が Adj', pattern: 'Topic は Subject が Adjective', note: 'Describes one aspect of the topic: 電車は人が多い "as for the train, people are many" → "the train is crowded".' },
    'ni-aru': { level: 'N5', title: 'に…ある / いる — existence', pattern: 'Place に Thing が ある / Person・animal が いる', note: 'Says something exists somewhere. ある for things, いる for people and animals.' },
    'ni-wa': { level: 'N5', title: 'には — "at / in" + topic', pattern: 'Place に は', note: 'に (location) combined with は to make the place the topic: "at my house, (there is)…".' },
    'i-adj-desu': { level: 'N5', title: 'い-adjective + です', pattern: 'い-adj + です', note: 'An い-adjective ends a polite sentence with です added only for politeness.' },
    'i-adj-past': { level: 'N5', title: 'い-adjective past', pattern: 'い-adj (〜い → 〜かった)', note: 'Past tense of い-adjectives: 高い → 高かった, うれしい → うれしかった.' },
    'i-adj-noun': { level: 'N5', title: 'い-adjective before a noun', pattern: 'い-adj + Noun', note: 'い-adjectives go directly in front of the noun they describe.' },
    'na-adj-noun': { level: 'N5', title: 'な-adjective before a noun', pattern: 'な-adj + な + Noun', note: 'な-adjectives need な between them and the noun.' },
    'kute': { level: 'N5', title: '〜くて — joining adjectives', pattern: 'い-adj (〜い → 〜くて), …', note: 'The て-form of an い-adjective, used to chain descriptions ("white and small") or give a reason ("it was hot, so…").' },
    'te-sequence': { level: 'N5', title: '〜て — "and then"', pattern: 'Verb て-form, Verb', note: 'Links actions in order: "do A, and then B".' },
    'te-iru': { level: 'N5', title: '〜ている — ongoing action / state', pattern: 'Verb て-form + いる', note: 'An action in progress ("is sleeping"), a habit ("grows vegetables every day"), or a resulting state ("lives in", "is inside").' },
    'ga-suki': { level: 'N5', title: '〜が好き — liking', pattern: 'Noun が 好き / 大好き', note: 'The thing liked is marked with が, not を.' },
    'hoshii': { level: 'N5', title: '〜が欲しい — wanting a thing', pattern: 'Noun が 欲しい', note: '"I want (a thing)". 欲しい is an い-adjective, so its past is 欲しかった.' },
    'kosoado': { level: 'N5', title: 'この / その / あの', pattern: 'この・その・あの + Noun', note: '"this (near me)", "that (near you / just mentioned)", "that (over there)".' },
    'ka-question': { level: 'N5', title: 'か — question marker', pattern: 'Sentence + か', note: 'Added to the end of a polite sentence to make it a question.' },
    'ga-but': { level: 'N5', title: 'が — "but"', pattern: 'Clause が、Clause', note: 'Joins two clauses with a contrast: "…, but …".' },
    'dakara': { level: 'N5', title: 'だから — "so / therefore"', pattern: 'Sentence。だから、Sentence', note: 'Starts a sentence that follows from the previous one.' },
    'to-iu': { level: 'N5', title: '〜と言う — quoting', pattern: '「Quote」と 言う', note: 'と marks what was said.' },
    'tari': { level: 'N5', title: '〜たり〜たりする — doing things like', pattern: 'Verb た-form + り, Verb た-form + り する', note: 'Lists example actions without claiming the list is complete.' },
    'yo': { level: 'N5', title: 'よ — assertion', pattern: 'Sentence + よ', note: 'Sentence-ending particle for telling the listener something you think they need to hear.' },
    'ne': { level: 'N5', title: 'ね — seeking agreement', pattern: 'Sentence + ね', note: 'Sentence-ending particle: "…, right?" / "…, isn\'t it?". Common in friendly replies.' },
    'nani-mo-neg': { level: 'N5', title: '何も + negative — "nothing"', pattern: '何も + negative verb', note: '何も with a negative verb means "nothing (at all)".' },
    'ichiban': { level: 'N5', title: '一番 — "the most / number one"', pattern: '一番 + adjective / 一番の + Noun', note: 'Makes a superlative: 一番の友だち "best friend".' },

    // ── N4 ──
    'plain-form': { level: 'N4', title: 'Plain (dictionary) form', pattern: 'Verb dictionary form / だ', note: 'Casual / written style without です・ます. Common in novels, diaries and between friends.' },
    'ta-koto-ga-aru': { level: 'N4', title: '〜たことがある — experience', pattern: 'Verb た-form + ことがある', note: '"Have (ever) done ~". With ない / なかった: "have never done ~".' },
    'node': { level: 'N4', title: '〜ので — "because / so"', pattern: 'Plain form + ので', note: 'Gives a reason, sounding softer and more objective than から.' },
    'kara-reason': { level: 'N4', title: '〜から — "because"', pattern: 'Clause + から', note: 'Gives a reason. After a noun in casual speech: 雨だから "because it\'s raining".' },
    'kara-from': { level: 'N4', title: 'から — "from"', pattern: 'Person / place / time から', note: 'Marks a starting point or source.' },
    'made': { level: 'N4', title: 'まで — "up to / until"', pattern: 'Place / time まで', note: 'Marks an end point: 駅まで "as far as the station".' },
    'made-ni': { level: 'N4', title: 'までに — "by (a deadline)"', pattern: 'Time までに', note: 'Something happens before that point in time, not continuing until it.' },
    'ni-iku-purpose': { level: 'N4', title: '〜に行く — going to do', pattern: 'Verb stem + に 行く / 来る', note: 'Says the purpose of going somewhere: 見に行く "go to see".' },
    'sugiru': { level: 'N4', title: '〜すぎる — too much', pattern: 'Verb stem / adj stem + すぎる', note: '"Too ~": 多すぎる "too many". Conjugates like an ichidan verb.' },
    'potential': { level: 'N4', title: 'Potential form — "can"', pattern: 'う-verb: 〜える / る-verb: 〜られる / する → できる', note: 'Says something can (or can\'t) be done: 進める "can move forward", 言える "can say".' },
    'nakanaka-neg': { level: 'N4', title: 'なかなか + negative', pattern: 'なかなか + negative verb', note: '"Not easily / not readily": it was hard to make progress.' },
    'naku-naru': { level: 'N4', title: '〜なくなる — no longer', pattern: 'Verb ない-form (〜ない → 〜なく) + なる', note: '"Come to not ~": わからなくなる "lose track / stop knowing".' },
    'relative-clause': { level: 'N4', title: 'Relative clause', pattern: 'Plain-form clause + Noun', note: 'A whole clause can describe a noun, placed right before it: 祖母が作ったトマト "the tomatoes (that) grandma grew".' },
    'te-kureru': { level: 'N4', title: '〜てくれる — doing a favour for me', pattern: 'Verb て-form + くれる', note: 'Someone does something for the speaker (or their group). Shows gratitude.' },
    'te-ageru': { level: 'N4', title: '〜てあげる — doing a favour for someone', pattern: 'Verb て-form + あげる', note: 'The speaker (or subject) does something for someone else.' },
    'te-request': { level: 'N4', title: '〜て — casual request', pattern: 'Verb て-form (end of sentence)', note: 'A て-form on its own is a casual way to ask someone to do something (short for 〜てください).' },
    'na-adverb': { level: 'N4', title: 'な-adjective + に — adverb', pattern: 'な-adj + に + Verb', note: 'Turns a な-adjective into an adverb: 親切に "kindly".' },
    'te-reason': { level: 'N4', title: '〜て — reason / cause', pattern: 'Clause て-form, feeling / result', note: 'The て-form can give the cause of a feeling or result: "I could say it, (and so) I was happy".' },
    'te-shimau': { level: 'N4', title: '〜てしまう — regret / completion', pattern: 'Verb て-form + しまう', note: 'Something happened that you didn\'t want (or was done completely): "ended up ~", "accidentally ~".' },
    'no-naka-de-ichiban': { level: 'N4', title: '〜の中で一番 — the most among', pattern: 'Group の中で 一番 + adjective', note: '"Of all ~, the most …".' },
    'you-ni': { level: 'N4', title: '〜ように — "so that"', pattern: 'Potential / ない-form + ように', note: 'Says the goal of an action: 行けるように "so that I can go".' },
    'tara': { level: 'N4', title: '〜たら — "when / if"', pattern: 'Verb た-form + ら', note: '"When (once) A happened…" or "if A happens…". Often for a surprise discovery: 起きたら雨だった.' },
    'to-omou': { level: 'N4', title: '〜と思う — "I think"', pattern: 'Plain form + と 思う', note: 'Reports a thought or opinion.' },
    'volitional-to-omou': { level: 'N4', title: '〜ようと思う — intending to', pattern: 'Volitional form + と 思う', note: '"Think I\'ll ~ / be about to ~": かけようと思った "was going to call".' },
    'toki': { level: 'N4', title: '〜とき — "when"', pattern: 'Plain form + とき', note: '"At the time when ~". A past verb before とき means the action had already happened.' },
    'nai-invitation': { level: 'N4', title: '〜ない？ — casual invitation', pattern: 'Verb ない-form + ？', note: 'Asking "won\'t you ~?" with rising intonation is a friendly way to suggest something.' },
    'mae-ni': { level: 'N4', title: '〜前に — "before"', pattern: 'Verb dictionary form + 前に', note: '"Before doing ~". The verb is always in dictionary form, even in a past story.' },
    'nakereba-naranai': { level: 'N4', title: '〜なければならない — must', pattern: 'Verb ない-form (〜ない → 〜なければ) + ならない', note: '"Have to ~". Polite past: 〜なければなりませんでした "had to ~".' },
    'to-conditional': { level: 'N4', title: '〜と — "when (and then)"', pattern: 'Verb dictionary form + と', note: '"When A happens, B (naturally / as found)". 着くと "when I arrived, (I found)…".' },
    'ba-conditional': { level: 'N4', title: '〜ば — "if"', pattern: 'Verb (〜う → 〜えば)', note: 'A general condition: いれば "if (they) are there".' },
    'demo-even': { level: 'N4', title: '〜でも — "even"', pattern: 'Noun + でも', note: '"Even on ~ / even with ~".' },
    'te-aru': { level: 'N4', title: '〜てある — something has been done', pattern: 'Transitive verb て-form + ある', note: 'Describes a state left by someone\'s action: 書いてある "is written (there)".' },
    'sou-looks': { level: 'N4', title: '〜そう — "looks ~"', pattern: 'Adj stem (drop い / な) + そう', note: 'Judging by appearance: おいしそう "looks delicious".' },
    'nagara': { level: 'N4', title: '〜ながら — "while"', pattern: 'Verb stem + ながら', note: 'Doing two things at once; the main action is the second one.' },
    'to-ii': { level: 'N4', title: '〜といいな — hoping', pattern: 'Plain form + と いい（な）', note: '"It would be nice if ~" / "I hope ~".' },
    'tai': { level: 'N4', title: '〜たい — want to', pattern: 'Verb stem + たい', note: '"Want to ~". にしたい = "want to make it into…".' },
    'ni-naru': { level: 'N4', title: '〜になる — become', pattern: 'Noun / な-adj + に なる', note: '"Become ~": 好きになる "come to like".' },
    'ni-suru': { level: 'N4', title: '〜にする — make into', pattern: 'Noun + に する', note: '"Make (something) into ~".' },
    'te-kara': { level: 'N4', title: '〜てから — "after"', pattern: 'Verb て-form + から', note: '"After doing ~, …". Stresses the order of events.' },
    'koto-nominalizer': { level: 'N4', title: '〜こと — turning a verb into a noun', pattern: 'Plain form + こと', note: 'Makes a clause into a noun ("the fact that ~"), so it can take を / が.' },

    // ── N3 ──
    'hazu': { level: 'N3', title: '〜はずだ — "should be"', pattern: 'Plain form + はずだ', note: 'Strong expectation based on reasoning: "it must have been / should be".' },
    'sorehodo-neg': { level: 'N3', title: 'それほど + negative', pattern: 'それほど + negative', note: '"Not that much / not so ~".' },
    'keredo': { level: 'N3', title: '〜けれど — "but / although"', pattern: 'Clause + けれど', note: 'Contrast, a little softer than が. Also けど, けれども.' },
    'koto-ni-suru': { level: 'N3', title: '〜ことにする — deciding to', pattern: 'Verb dictionary form + ことにする', note: '"Decide to ~". Past ことにした: "decided to ~".' },
    'te-kuru': { level: 'N3', title: '〜てくる — towards the speaker', pattern: 'Verb て-form + くる', note: 'An action directed at the speaker: 電話がかかってきた "a call came (to me)".' },
    'ni-yoru-to': { level: 'N3', title: '〜によると — "according to"', pattern: 'Source + によると', note: 'Names where information comes from. Usually ends in そうだ / らしい.' },
    'sou-hearsay': { level: 'N3', title: '〜そうだ — "I heard that"', pattern: 'Plain form + そうだ', note: 'Reports something heard from someone else. Different from adjective-stem + そう ("looks ~").' },
    'passive': { level: 'N3', title: 'Passive — "is done (by)"', pattern: 'う-verb: 〜われる・〜られる / る-verb: 〜られる', note: 'The subject receives the action: 拾われる "be picked up", 愛される "be loved". The doer is marked with に.' },
    'rashii': { level: 'N3', title: '〜らしい — "apparently"', pattern: 'Plain form + らしい', note: 'A conclusion based on what you heard or saw: "it seems".' },
    'bakari-dewanai': { level: 'N3', title: '〜ばかりではない — "not only / not all"', pattern: 'Noun + ばかり では ない', note: '"It isn\'t all ~": 悪い人ばかりではない "not everyone is bad".' },
    'you-ni-suru': { level: 'N3', title: '〜ようにしている — making a point of', pattern: 'Verb dictionary form + ようにしている', note: '"Make a habit of ~ / always make sure to ~".' },
    'tame-ni': { level: 'N3', title: '〜ために — "in order to"', pattern: 'Verb dictionary form + ために', note: 'States a purpose (with the same subject in both clauses).' },
    'kata': { level: 'N3', title: '〜方 — "way of doing"', pattern: 'Verb stem + 方', note: '作り方 "how to make", 読み方 "how to read".' },
    'you-ni-naru': { level: 'N3', title: '〜ようになる — come to be able', pattern: 'Verb (often potential) + ようになる', note: 'A gradual change: 話せるようになった "became able to speak".' },
    'zenzen-neg': { level: 'N3', title: '全然 + negative', pattern: '全然 + negative', note: '"Not at all".' },
    'ba-hodo': { level: 'N3', title: '〜ば〜ほど — "the more…the more"', pattern: 'Verb ば-form + same verb + ほど', note: '"The more you ~, the more …".' },
    'causative': { level: 'N3', title: 'Causative — make / let do', pattern: 'う-verb: 〜わせる・〜せる / る-verb: 〜させる', note: '"Have / let someone do": 手伝わせる "have (someone) help". The person made to act is marked with に.' },
    'te-bakari': { level: 'N3', title: '〜てばかりいる — doing nothing but', pattern: 'Verb て-form + ばかり いる', note: '"Keep on ~ / do nothing but ~", usually a complaint.' },
    'wo-path': { level: 'N5', title: 'を — route / place passed', pattern: 'Place を 通る / 歩く / 渡る', note: 'With verbs of movement, を marks the space you move through or past.' },
    'wa-contrast': { level: 'N5', title: 'は — contrast', pattern: 'A は …、B は …', note: 'Two は phrases side by side contrast the two topics: "red plates are…, (whereas) black plates are…".' },
    'ku-naru': { level: 'N5', title: '〜くなる — become (い-adj)', pattern: 'い-adj (〜い → 〜く) + なる', note: 'A change of state: 赤くなる "turn red", 暖かくなる "get warm".' },
    'de-and': { level: 'N5', title: 'で — "and" between noun sentences', pattern: 'Noun で、…', note: 'The て-form of です, used to join two descriptions: 目は石で、鼻はにんじんです.' },
    'mo-also': { level: 'N5', title: 'も — "also / too"', pattern: 'Noun も', note: 'Replaces は / が / を to mean "also". Repeated (A も B も) with a negative: "neither A nor B".' },
    'shika-nai': { level: 'N5', title: '〜しか〜ない — "only"', pattern: 'Noun しか + negative verb', note: '"Nothing but ~". Always paired with a negative, and stresses that it is less than hoped.' },
    'dewa-arimasen': { level: 'N5', title: 'ではありません — polite "is not"', pattern: 'Noun + ではありません', note: 'Negative of です. Casual: じゃない.' },
    'dake': { level: 'N5', title: 'だけ — "only, just"', pattern: 'Noun / plain form + だけ', note: 'Limits something to exactly that: 一曲だけ "just one piece". Unlike しか, it takes a positive verb.' },
    'yori': { level: 'N4', title: 'より — "than"', pattern: 'A は B より + adjective', note: 'Compares: いつもより "than usual".' },
    'to-iu-name': { level: 'N4', title: '〜という — "called"', pattern: '「Name」という + Noun', note: 'Names or labels something: ユキオという名前 "the name Yukio".' },
    'volitional': { level: 'N4', title: 'Volitional — "let\'s" (casual)', pattern: 'う-verb: 〜おう / る-verb: 〜よう', note: 'Casual version of 〜ましょう: 開けよう "let\'s open it".' },
    'te-mo': { level: 'N4', title: '〜ても — "even if"', pattern: 'Verb / adj て-form + も', note: 'The result holds regardless: なっていなくても "even if you haven\'t become".' },
    'ki-ga-suru': { level: 'N4', title: '〜気がする — "have a feeling that"', pattern: 'Plain form + 気がする', note: 'A vague feeling or impression: 褒められた気がした "felt as if I\'d been praised".' },
    'no-koto': { level: 'N4', title: '〜のこと — "about"', pattern: 'Noun + のこと', note: 'Turns a noun into "matters concerning it": 犬のこと "about the dog".' },
    'te-iku': { level: 'N4', title: '〜ていく — going away', pattern: 'Verb て-form + いく', note: 'The action moves away from the speaker: 帰っていく "heads off home".' },
    'te-miru': { level: 'N4', title: '〜てみる — "try doing"', pattern: 'Verb て-form + みる', note: 'Do something to see what happens: 聞いてみた "tried asking".' },
    'te-morau': { level: 'N4', title: '〜てもらう — have someone do', pattern: 'Verb て-form + もらう', note: 'Receiving a favour: 聞いてもらえる "to have people listen (to me)".' },
    'hajimeru': { level: 'N4', title: '〜始める — start doing', pattern: 'Verb stem + 始める', note: '弾き始める "start playing". Conjugates like an ichidan verb.' },
    'n-desu': { level: 'N4', title: '〜んです — explaining', pattern: 'Plain form + んです (Noun / な-adj + なんです)', note: 'Gives background or an explanation, often in answer to "why?".' },
    'embedded-question': { level: 'N4', title: '〜か — embedded question', pattern: 'Question word … plain form + (の)か + Verb', note: 'Puts a question inside a sentence: なぜ弾くのか聞いた "asked why he played".' },
    'dare-demo': { level: 'N4', title: '誰でも — "anyone"', pattern: 'Question word + でも', note: '誰でも "anyone", 何でも "anything", いつでも "any time".' },
    'tokoro': { level: 'N3', title: '〜たところ — "when I did ~, (it turned out)"', pattern: 'Verb た-form + ところ、result', note: 'Something was done and an (often unexpected) result followed.' },
    'made-even': { level: 'N3', title: 'まで — "even"', pattern: 'Noun + まで', note: 'Something goes surprisingly far: 遠くから来る人まで "even people coming from far away".' },
    'masaka': { level: 'N3', title: 'まさか〜とは思わない — never imagined', pattern: 'まさか + plain form + とは 思わなかった', note: '"I never dreamed that ~". Expresses surprise.' },
    'koto-ni-shite-iru': { level: 'N3', title: '〜ことにしている — make it a rule to', pattern: 'Verb dictionary form + ことにしている', note: 'A personal habit you decided on: 食べることにしている "I make a point of eating it".' },
    'koto-ni-naru': { level: 'N3', title: '〜ことになる — it turns out / it\'s been decided', pattern: 'Verb dictionary form + ことになる', note: 'An outcome decided by circumstances or others: 分けることになった "ended up sharing". ことになっている: "is scheduled to".' },
    'shunkan': { level: 'N3', title: '〜た瞬間 — "the moment"', pattern: 'Verb た-form + 瞬間', note: 'Something happens at the exact instant of another action.' },
    'you-ka-to': { level: 'N3', title: '〜ようか(と) — wondering whether to', pattern: 'Volitional + か と 迷う / 思う', note: '"Debating whether to ~": 譲ろうかと迷う.' },
    'ta-bakari': { level: 'N3', title: '〜たばかり — "just did"', pattern: 'Verb た-form + ばかり', note: 'Something happened only a short time ago. Different from 〜てばかり ("nothing but").' },
    'noni': { level: 'N3', title: '〜のに — "even though"', pattern: 'Plain form (Noun / な-adj + な) + のに', note: 'Contrary to expectation, often with surprise or frustration.' },
  };

  // Word glossary keyed by dictionary form: [reading, meaning, part of speech].
  // A key may carry a (disambiguation) suffix for words that share a
  // spelling but not a meaning; the reader shows the key without it.
  global.STORY_GLOSSARY = {
    // Particles & copula
    'は': ['わ', 'topic marker ("as for…")', 'particle'],
    'が': ['が', 'subject marker; "but" (between clauses)', 'particle'],
    'を': ['お', 'direct object marker', 'particle'],
    'に': ['に', 'at (time), to (destination), in (location of existence); by (passive / causative)', 'particle'],
    'へ': ['え', 'towards (direction)', 'particle'],
    'で': ['で', 'at / in (place of action); by / with (means); linking form of だ (では)', 'particle'],
    'と': ['と', 'and; with; quotation marker; "when" (after a verb)', 'particle'],
    'の': ['の', 'possessive / linking particle ("\'s", "of")', 'particle'],
    'も': ['も', 'also, too; (with negative) not even', 'particle'],
    'や': ['や', 'and (non-exhaustive list)', 'particle'],
    'か': ['か', 'question marker', 'particle'],
    'よ': ['よ', 'sentence ending: "I tell you"', 'particle'],
    'ね': ['ね', 'sentence ending: "right?", "isn\'t it?"', 'particle'],
    'な': ['な', 'links a な-adjective to a noun', 'particle'],
    'な(feeling)': ['な', 'sentence ending expressing a feeling or wish (casual)', 'particle'],
    'から': ['から', 'from; because', 'particle'],
    'まで': ['まで', 'until; as far as', 'particle'],
    'ので': ['ので', 'because, so', 'conjunction'],
    'けれど': ['けれど', 'but, although', 'conjunction'],
    'ながら': ['ながら', 'while (doing)', 'particle'],
    'ばかり': ['ばかり', 'only, nothing but', 'particle'],
    'たい': ['たい', 'want to (after a verb stem)', 'auxiliary'],
    'ほど': ['ほど', 'extent; (〜ば〜ほど) the more…', 'particle'],
    'でも(even)': ['でも', 'even (〜でも)', 'particle'],
    'です': ['です', 'is, am, are (polite copula)', 'copula'],
    'だ': ['だ', 'is (plain copula)', 'copula'],
    'じゃ': ['じゃ', 'casual では: "with (this)", "in that case"', 'particle'],
    'ない': ['ない', 'not; there isn\'t (negative of ある)', 'auxiliary'],
    'はず': ['はず', 'should be, expected to be', 'noun'],
    'らしい': ['らしい', 'apparently, it seems', 'auxiliary'],
    'そう': ['そう', 'looks (like); I hear that', 'auxiliary'],
    'よう': ['よう', 'way, manner; (〜ように) so that', 'noun'],
    'こと': ['こと', 'thing, matter; (〜こと) turns a verb into a noun', 'noun'],
    'とき': ['とき', 'time; when', 'noun'],
    'ため': ['ため', 'sake; (〜ために) in order to', 'noun'],
    'ころ': ['ころ', 'time, days (when…)', 'noun'],
    'さん': ['さん', 'Mr. / Ms. (polite suffix)', 'suffix'],

    // Conjunctions & adverbs
    'それから': ['それから', 'after that, and then', 'conjunction'],
    'でも': ['でも', 'but, however', 'conjunction'],
    'だから': ['だから', 'so, therefore', 'conjunction'],
    'いつも': ['いつも', 'always', 'adverb'],
    'とても': ['とても', 'very', 'adverb'],
    'ちょっと': ['ちょっと', 'a little, a bit', 'adverb'],
    'たくさん': ['たくさん', 'a lot, many', 'adverb'],
    'また': ['また', 'again', 'adverb'],
    'まず': ['まず', 'first (of all)', 'adverb'],
    'なかなか': ['なかなか', '(with negative) not easily', 'adverb'],
    'すぐ': ['すぐ', 'immediately, right away', 'adverb'],
    'たぶん': ['たぶん', 'probably', 'adverb'],
    'もう': ['もう', 'already; (with age) now', 'adverb'],
    'まだ': ['まだ', 'still, (not) yet', 'adverb'],
    'ずっと': ['ずっと', 'for a long time, forever', 'adverb'],
    'だんだん': ['だんだん', 'gradually', 'adverb'],
    'それほど': ['それほど', '(with negative) not that much', 'adverb'],
    '少し': ['すこし', 'a little', 'adverb'],
    '初めて': ['はじめて', 'for the first time', 'adverb'],
    '確かに': ['たしかに', 'certainly, surely', 'adverb'],
    '本当に': ['ほんとうに', 'really, truly', 'adverb'],
    '全然': ['ぜんぜん', '(with negative) not at all', 'adverb'],
    '特に': ['とくに', 'especially', 'adverb'],
    '必ず': ['かならず', 'always, without fail', 'adverb'],
    '改めて': ['あらためて', 'once again, anew', 'adverb'],
    '一生懸命': ['いっしょうけんめい', 'with all one\'s might, very hard', 'adverb'],
    '最後に': ['さいごに', 'finally, at the end', 'adverb'],
    '長く': ['ながく', 'for a long time', 'adverb'],

    // Pronouns & demonstratives
    '私': ['わたし', 'I, me', 'pronoun'],
    'これ': ['これ', 'this (one)', 'pronoun'],
    'それ': ['それ', 'that (one)', 'pronoun'],
    'この': ['この', 'this (+ noun)', 'pre-noun'],
    'その': ['その', 'that (+ noun)', 'pre-noun'],
    '何': ['なに', 'what', 'pronoun'],
    'いくら': ['いくら', 'how much (price)', 'question word'],
    '小さな': ['ちいさな', 'small, little (+ noun)', 'pre-noun'],

    // People & names
    '田中さん': ['たなかさん', 'Tanaka-san (a family name)', 'name'],
    '木村さん': ['きむらさん', 'Kimura-san (a family name)', 'name'],
    'タマ': ['タマ', 'Tama (a common cat name)', 'name'],
    'ケン': ['ケン', 'Ken (a given name)', 'name'],
    '会社員': ['かいしゃいん', 'office worker, company employee', 'noun'],
    '人': ['ひと', 'person, people', 'noun'],
    '友だち': ['ともだち', 'friend', 'noun'],
    '二人': ['ふたり', 'two people', 'noun'],
    'おじいさん': ['おじいさん', 'old man; grandfather', 'noun'],
    '祖母': ['そぼ', '(my) grandmother', 'noun'],
    'おばあちゃん': ['おばあちゃん', 'grandma (affectionate)', 'noun'],
    '母': ['はは', '(my) mother', 'noun'],
    '息子': ['むすこ', 'son', 'noun'],
    '息子さん': ['むすこさん', '(someone else\'s) son', 'noun'],
    '店長': ['てんちょう', 'shop manager, owner', 'noun'],
    '駅員': ['えきいん', 'station staff', 'noun'],
    '警察': ['けいさつ', 'police', 'noun'],

    // Time
    '毎朝': ['まいあさ', 'every morning', 'noun'],
    '毎日': ['まいにち', 'every day', 'noun'],
    '朝': ['あさ', 'morning', 'noun'],
    '夜': ['よる', 'night, evening', 'noun'],
    '昼': ['ひる', 'noon, midday', 'noun'],
    '昨日': ['きのう', 'yesterday', 'noun'],
    '土曜日': ['どようび', 'Saturday', 'noun'],
    '日曜日': ['にちようび', 'Sunday', 'noun'],
    '来週': ['らいしゅう', 'next week', 'noun'],
    '先週': ['せんしゅう', 'last week', 'noun'],
    '先月': ['せんげつ', 'last month', 'noun'],
    '去年': ['きょねん', 'last year', 'noun'],
    '春': ['はる', 'spring', 'noun'],
    '夏休み': ['なつやすみ', 'summer holidays', 'noun'],
    '一日': ['いちにち', 'one day; a (whole) day', 'noun'],
    '日': ['ひ', 'day', 'noun'],
    '今': ['いま', 'now', 'noun'],
    '最近': ['さいきん', 'recently, lately', 'noun'],
    '最初': ['さいしょ', 'the beginning, at first', 'noun'],
    '次': ['つぎ', 'next', 'noun'],
    '以来': ['いらい', 'since (then)', 'noun'],
    '六時': ['ろくじ', 'six o\'clock', 'noun'],
    '四時': ['よじ', 'four o\'clock', 'noun'],
    '八十歳': ['はちじゅっさい', 'eighty years old', 'noun'],

    // Places & things
    '会社': ['かいしゃ', 'company, office', 'noun'],
    '電車': ['でんしゃ', 'train', 'noun'],
    '駅': ['えき', 'station', 'noun'],
    '駅前': ['えきまえ', 'in front of the station', 'noun'],
    '中': ['なか', 'inside, middle; (〜の中で) among', 'noun'],
    '上': ['うえ', 'on top, above', 'noun'],
    '前': ['まえ', 'front; before', 'noun'],
    '近く': ['ちかく', 'near, nearby', 'noun'],
    '本': ['ほん', 'book', 'noun'],
    '雨': ['あめ', 'rain', 'noun'],
    '傘': ['かさ', 'umbrella', 'noun'],
    '二本': ['にほん', 'two (long, thin objects)', 'counter'],
    '朝ご飯': ['あさごはん', 'breakfast', 'noun'],
    'パン': ['パン', 'bread', 'noun'],
    'コーヒー': ['コーヒー', 'coffee', 'noun'],
    'デパート': ['デパート', 'department store', 'noun'],
    'セーター': ['セーター', 'sweater', 'noun'],
    '三階': ['さんがい', 'third floor', 'noun'],
    '服': ['ふく', 'clothes', 'noun'],
    '店': ['みせ', 'shop, store', 'noun'],
    '五千円': ['ごせんえん', '5,000 yen', 'noun'],
    '喫茶店': ['きっさてん', 'café, coffee shop', 'noun'],
    'ケーキ': ['ケーキ', 'cake', 'noun'],
    '家': ['いえ', 'house, home', 'noun'],
    '猫': ['ねこ', 'cat', 'noun'],
    '名前': ['なまえ', 'name', 'noun'],
    '魚': ['さかな', 'fish', 'noun'],
    '窓': ['まど', 'window', 'noun'],
    '部屋': ['へや', 'room', 'noun'],
    '足': ['あし', 'foot, leg', 'noun'],
    '机': ['つくえ', 'desk', 'noun'],
    'ペン': ['ペン', 'pen', 'noun'],
    '一番': ['いちばん', 'number one, the most, best', 'noun'],
    '日本': ['にほん', 'Japan', 'noun'],
    '東京': ['とうきょう', 'Tokyo', 'noun'],
    '浅草': ['あさくさ', 'Asakusa (an old district of Tokyo)', 'noun'],
    'お寺': ['おてら', 'Buddhist temple', 'noun'],
    '道': ['みち', 'road, way', 'noun'],
    '日本語': ['にほんご', 'Japanese (language)', 'noun'],
    'ありがとうございます': ['ありがとうございます', 'thank you (polite)', 'expression'],
    'ホテル': ['ホテル', 'hotel', 'noun'],
    'ラーメン': ['ラーメン', 'ramen (noodle soup)', 'noun'],
    '舌': ['した', 'tongue', 'noun'],
    'やけど': ['やけど', 'a burn; (やけどする) to burn oneself', 'noun'],
    '公園': ['こうえん', 'park', 'noun'],
    'テニス': ['テニス', 'tennis', 'noun'],
    '約束': ['やくそく', 'promise, plans (to meet)', 'noun'],
    '電話': ['でんわ', 'telephone, phone call', 'noun'],
    'メッセージ': ['メッセージ', 'message', 'noun'],
    '映画': ['えいが', 'movie', 'noun'],
    '映画館': ['えいがかん', 'movie theater', 'noun'],
    '返事': ['へんじ', 'reply, answer', 'noun'],
    '洗濯物': ['せんたくもの', 'laundry', 'noun'],
    '田舎': ['いなか', 'the countryside; hometown', 'noun'],
    '手紙': ['てがみ', 'letter', 'noun'],
    '畑': ['はたけ', 'field (for vegetables)', 'noun'],
    '野菜': ['やさい', 'vegetables', 'noun'],
    '箱': ['はこ', 'box', 'noun'],
    'トマト': ['トマト', 'tomato', 'noun'],
    '音楽': ['おんがく', 'music', 'noun'],
    'サラダ': ['サラダ', 'salad', 'noun'],
    'お礼': ['おれい', 'thanks, gratitude', 'noun'],
    '学校': ['がっこう', 'school', 'noun'],
    '仕事': ['しごと', 'work, job', 'noun'],
    '帰り': ['かえり', 'the way home, return', 'noun'],
    '財布': ['さいふ', 'wallet', 'noun'],
    'かばん': ['かばん', 'bag', 'noun'],
    'お金': ['おかね', 'money', 'noun'],
    'カード': ['カード', 'card (credit / bank card)', 'noun'],
    '免許証': ['めんきょしょう', 'driver\'s license', 'noun'],
    '全部': ['ぜんぶ', 'all, everything', 'noun'],
    '届け': ['とどけ', 'report, notification (to the authorities)', 'noun'],
    '番号': ['ばんごう', 'number', 'noun'],
    'ベンチ': ['ベンチ', 'bench', 'noun'],
    '中身': ['なかみ', 'contents', 'noun'],
    '世の中': ['よのなか', 'the world, society', 'noun'],
    '落とし物': ['おとしもの', 'lost item, something dropped', 'noun'],
    'パン屋': ['パンや', 'bakery', 'noun'],
    'フランス': ['フランス', 'France', 'noun'],
    'フランス語': ['フランスご', 'French (language)', 'noun'],
    '作り方': ['つくりかた', 'how to make, recipe', 'noun'],
    '町': ['まち', 'town', 'noun'],
    '自分': ['じぶん', 'oneself, one\'s own', 'noun'],
    '味': ['あじ', 'taste, flavour', 'noun'],
    'メロンパン': ['メロンパン', 'melon bread (a sweet bun)', 'noun'],
    '人気': ['にんき', 'popularity', 'noun'],
    '失敗': ['しっぱい', 'mistake, failure', 'noun'],
    '練習': ['れんしゅう', 'practice', 'noun'],
    '勉強': ['べんきょう', 'study', 'noun'],
    '元気': ['げんき', 'healthy, lively, energetic', 'な-adjective'],

    // Adjectives
    '多い': ['おおい', 'many, a lot', 'い-adjective'],
    '多すぎる': ['おおすぎる', 'too many', 'ichidan verb'],
    '新しい': ['あたらしい', 'new', 'い-adjective'],
    '青い': ['あおい', 'blue', 'い-adjective'],
    '赤い': ['あかい', 'red', 'い-adjective'],
    '白い': ['しろい', 'white', 'い-adjective'],
    '小さい': ['ちいさい', 'small', 'い-adjective'],
    '高い': ['たかい', 'expensive; high, tall', 'い-adjective'],
    'かわいい': ['かわいい', 'cute', 'い-adjective'],
    '楽しい': ['たのしい', 'fun, enjoyable', 'い-adjective'],
    '欲しい': ['ほしい', 'wanted, desired ("I want")', 'い-adjective'],
    '熱い': ['あつい', 'hot (to the touch)', 'い-adjective'],
    'おいしい': ['おいしい', 'delicious', 'い-adjective'],
    'うれしい': ['うれしい', 'happy, glad', 'い-adjective'],
    'いい': ['いい', 'good', 'い-adjective'],
    '長い': ['ながい', 'long', 'い-adjective'],
    '悪い': ['わるい', 'bad', 'い-adjective'],
    '若い': ['わかい', 'young', 'い-adjective'],
    'きれい': ['きれい', 'pretty; clean', 'な-adjective'],
    '好き': ['すき', 'liked, favourite', 'な-adjective'],
    '大好き': ['だいすき', 'loved, really liked', 'な-adjective'],
    '親切': ['しんせつ', 'kind', 'な-adjective'],
    '楽しみ': ['たのしみ', 'something to look forward to', 'noun / な-adjective'],
    'だめ': ['だめ', 'no good, not allowed', 'な-adjective'],

    // Verbs
    'ある': ['ある', 'to be, to exist (things); to have', 'う-verb'],
    'いる': ['いる', 'to be, to exist (people, animals); after て-form: be ~ing', 'ichidan verb'],
    'する': ['する', 'to do', 'irregular verb'],
    'くる': ['くる', 'after て-form: towards the speaker', 'irregular verb'],
    '来る': ['くる', 'to come', 'irregular verb'],
    '行く': ['いく', 'to go', 'う-verb'],
    'なる': ['なる', 'to become', 'う-verb'],
    'できる': ['できる', 'to be able to do, can', 'ichidan verb'],
    '起きる': ['おきる', 'to get up, to wake up', 'ichidan verb'],
    '乗る': ['のる', 'to get on, to ride (a train, bus…)', 'う-verb'],
    '読む': ['よむ', 'to read', 'う-verb'],
    '買う': ['かう', 'to buy', 'う-verb'],
    '入る': ['はいる', 'to enter, to go in; to be contained', 'う-verb'],
    '食べる': ['たべる', 'to eat', 'ichidan verb'],
    '言う': ['いう', 'to say', 'う-verb'],
    '寝る': ['ねる', 'to sleep', 'ichidan verb'],
    '走る': ['はしる', 'to run', 'う-verb'],
    '遊ぶ': ['あそぶ', 'to play', 'う-verb'],
    '落とす': ['おとす', 'to drop, to knock down', 'う-verb'],
    '着く': ['つく', 'to arrive', 'う-verb'],
    '見る': ['みる', 'to see, to look at, to watch', 'ichidan verb'],
    '進む': ['すすむ', 'to move forward, to advance', 'う-verb'],
    'わかる': ['わかる', 'to understand, to know', 'う-verb'],
    '聞く': ['きく', 'to ask; to listen, to hear', 'う-verb'],
    '連れる': ['つれる', 'to take (someone) along', 'ichidan verb'],
    'くれる': ['くれる', 'to give (to me); after て-form: do for me', 'ichidan verb'],
    'あげる': ['あげる', 'to give; after て-form: do for someone', 'ichidan verb'],
    'しまう': ['しまう', 'after て-form: to end up ~, to do completely', 'う-verb'],
    '勉強する': ['べんきょうする', 'to study', 'する-verb'],
    '降る': ['ふる', 'to fall (rain, snow)', 'う-verb'],
    '思う': ['おもう', 'to think', 'う-verb'],
    'かける': ['かける', 'to make (a phone call)', 'ichidan verb'],
    'やめる': ['やめる', 'to stop, to give up, to call off', 'ichidan verb'],
    '入れる': ['いれる', 'to put in, to bring in', 'ichidan verb'],
    '急ぐ': ['いそぐ', 'to hurry', 'う-verb'],
    '出る': ['でる', 'to leave, to go out', 'ichidan verb'],
    '忘れる': ['わすれる', 'to forget; to leave behind', 'ichidan verb'],
    '持つ': ['もつ', 'to hold, to carry, to have', 'う-verb'],
    '待つ': ['まつ', 'to wait', 'う-verb'],
    '笑う': ['わらう', 'to laugh, to smile', 'う-verb'],
    '住む': ['すむ', 'to live (somewhere)', 'う-verb'],
    '届く': ['とどく', 'to arrive, to be delivered', 'う-verb'],
    '育てる': ['そだてる', 'to grow, to raise', 'ichidan verb'],
    '書く': ['かく', 'to write', 'う-verb'],
    '作る': ['つくる', 'to make', 'う-verb'],
    '会う': ['あう', 'to meet', 'う-verb'],
    '喜ぶ': ['よろこぶ', 'to be pleased, to be glad', 'う-verb'],
    'なくす': ['なくす', 'to lose', 'う-verb'],
    '帰る': ['かえる', 'to go home, to return', 'う-verb'],
    '気が付く': ['きがつく', 'to notice, to realise', 'expression'],
    '焦る': ['あせる', 'to panic, to be flustered', 'う-verb'],
    '出す': ['だす', 'to hand in, to submit; to take out', 'う-verb'],
    '知る': ['しる', 'to know (知らない: unknown)', 'う-verb'],
    'かかる': ['かかる', '(a phone call) to come in', 'う-verb'],
    'よる': ['よる', '(〜によると) according to', 'う-verb'],
    '見つかる': ['みつかる', 'to be found', 'う-verb'],
    '拾う': ['ひろう', 'to pick up (from the ground)', 'う-verb'],
    '届ける': ['とどける', 'to deliver; to hand in (to the police)', 'ichidan verb'],
    '受け取る': ['うけとる', 'to receive', 'う-verb'],
    'なくなる': ['なくなる', 'to go missing, to be gone', 'う-verb'],
    '感じる': ['かんじる', 'to feel', 'ichidan verb'],
    '見つける': ['みつける', 'to find', 'ichidan verb'],
    '焼く': ['やく', 'to bake, to grill', 'う-verb'],
    '学ぶ': ['まなぶ', 'to learn', 'う-verb'],
    '話す': ['はなす', 'to speak, to talk', 'う-verb'],
    '戻る': ['もどる', 'to return, to come back', 'う-verb'],
    '開く': ['ひらく', 'to open (a shop)', 'う-verb'],
    '売り切れる': ['うりきれる', 'to sell out', 'ichidan verb'],
    '手伝う': ['てつだう', 'to help', 'う-verb'],
    '愛する': ['あいする', 'to love', 'する-verb'],
    '続く': ['つづく', 'to continue, to last', 'う-verb'],
    '願う': ['ねがう', 'to hope, to wish', 'う-verb'],
    // Added with the second batch of stories
    'あ': ['あ', 'ah!, oh!', 'interjection'],
    'あっという間に': ['あっというまに', 'in an instant, in no time', 'expression'],
    'あと': ['あと', '(with a number) … more, … left', 'adverb'],
    'あなた': ['あなた', 'you', 'pronoun'],
    'ある(certain)': ['ある', 'a certain, one (day / evening)', 'pre-noun'],
    'いく': ['いく', 'after て-form: away from the speaker, off into the distance', 'う-verb'],
    'うち': ['うち', 'our, my (home / local)', 'noun'],
    'おばあさん': ['おばあさん', 'old woman; grandmother', 'noun'],
    'お皿': ['おさら', 'plate', 'noun'],
    'かぶせる': ['かぶせる', 'to put (a hat) on someone', 'ichidan verb'],
    'ください': ['ください', 'please give me', 'expression'],
    'けが': ['けが', 'injury; (けがする) to get hurt', 'noun'],
    'こう': ['こう', 'like this, this way', 'adverb'],
    'こうして': ['こうして', 'and so, in this way', 'conjunction'],
    'こんな': ['こんな', 'such, like this; (こんなに) this much', 'pre-noun'],
    'ご飯': ['ごはん', 'meal; cooked rice', 'noun'],
    'しか': ['しか', '(with negative) only, nothing but', 'particle'],
    'すごい': ['すごい', 'amazing, great', 'い-adjective'],
    'たたく': ['たたく', 'to hit, to bang', 'う-verb'],
    'たち': ['たち', 'plural suffix (私たち: we)', 'suffix'],
    'だけ': ['だけ', 'only, just', 'particle'],
    'ちゃんと': ['ちゃんと', 'properly', 'adverb'],
    'つける': ['つける', 'to give (a name)', 'ichidan verb'],
    'ところ': ['ところ', 'place; (〜たところ) when I did ~, (it turned out)', 'noun'],
    'ところが': ['ところが', 'however, but then', 'conjunction'],
    'な(copula)': ['な', 'form of だ before の / ん (〜なんです, 〜なのに)', 'copula'],
    'なぜ': ['なぜ', 'why', 'question word'],
    'にんじん': ['にんじん', 'carrot', 'noun'],
    'のに': ['のに', 'even though, despite', 'conjunction'],
    'まさか': ['まさか', 'surely not, never (expected)', 'adverb'],
    'まったく': ['まったく', 'completely, exactly', 'adverb'],
    'みる': ['みる', 'after て-form: try doing', 'ichidan verb'],
    'みんな': ['みんな', 'everyone', 'noun'],
    'もし': ['もし', 'if, supposing', 'adverb'],
    'もしもし': ['もしもし', 'hello (on the phone)', 'expression'],
    'もらう': ['もらう', 'to receive; after て-form: have someone do', 'う-verb'],
    'やっと': ['やっと', 'finally, at last', 'adverb'],
    'ゆっくり': ['ゆっくり', 'slowly', 'adverb'],
    'より': ['より', 'than', 'particle'],
    'わさび': ['わさび', 'wasabi (Japanese horseradish)', 'noun'],
    'ん': ['ん', '(〜んです) explaining / giving background', 'particle'],
    'アボカド': ['アボカド', 'avocado', 'noun'],
    'アメリカ': ['アメリカ', 'America', 'noun'],
    'クラス': ['クラス', 'class', 'noun'],
    'ケース': ['ケース', '(display) case', 'noun'],
    'サッカー': ['サッカー', 'soccer, football', 'noun'],
    'スーツ': ['スーツ', 'suit', 'noun'],
    'タイムカプセル': ['タイムカプセル', 'time capsule', 'noun'],
    'タカシ': ['タカシ', 'Takashi (a given name)', 'name'],
    'チーズケーキ': ['チーズケーキ', 'cheesecake', 'noun'],
    'ネット': ['ネット', 'the internet', 'noun'],
    'パーティー': ['パーティー', 'party', 'noun'],
    'ピアニスト': ['ピアニスト', 'pianist', 'noun'],
    'ピアノ': ['ピアノ', 'piano', 'noun'],
    'マイク': ['マイク', 'Mike (a given name)', 'name'],
    'ミス': ['ミス', 'mistake', 'noun'],
    'ユキオ': ['ユキオ', 'Yukio (a given name; 雪 "snow" + 男 "man")', 'name'],
    'リハビリ': ['リハビリ', 'rehabilitation, physical therapy', 'noun'],
    'レストラン': ['レストラン', 'restaurant', 'noun'],
    '一つ': ['ひとつ', 'one (thing)', 'noun'],
    '一曲': ['いっきょく', 'one piece (of music)', 'noun'],
    '一緒': ['いっしょ', 'together (一緒に)', 'noun'],
    '一週間': ['いっしゅうかん', 'one week', 'noun'],
    '七時': ['しちじ', 'seven o\'clock', 'noun'],
    '三杯': ['さんばい', 'three glasses / cups', 'counter'],
    '上司': ['じょうし', 'boss, superior', 'noun'],
    '下手': ['へた', 'unskilful, bad at', 'な-adjective'],
    '久しぶり': ['ひさしぶり', 'for the first time in a long while', 'noun'],
    '二十歳': ['はたち', 'twenty years old', 'noun'],
    '百円': ['ひゃくえん', '100 yen', 'noun'],
    '五百円': ['ごひゃくえん', '500 yen', 'noun'],
    '今日': ['きょう', 'today', 'noun'],
    '何(なん)': ['なん', 'what (before です, で, の)', 'pronoun'],
    '入院': ['にゅういん', 'being in hospital; (入院する) to be hospitalised', 'noun'],
    '写真': ['しゃしん', 'photo', 'noun'],
    '冬': ['ふゆ', 'winter', 'noun'],
    '分ける': ['わける', 'to share, to split', 'ichidan verb'],
    '勇気': ['ゆうき', 'courage (勇気を出す: work up courage)', 'noun'],
    '十個': ['じゅっこ', 'ten (small things)', 'counter'],
    '十歳': ['じゅっさい', 'ten years old', 'noun'],
    '半分': ['はんぶん', 'half', 'noun'],
    '卒業': ['そつぎょう', 'graduation; (卒業する) to graduate', 'noun'],
    '古い': ['ふるい', 'old (things)', 'い-adjective'],
    '叱る': ['しかる', 'to scold, to tell off', 'う-verb'],
    '同じ': ['おなじ', 'the same', 'pre-noun'],
    '回転寿司': ['かいてんずし', 'conveyor-belt sushi', 'noun'],
    '埋める': ['うめる', 'to bury', 'ichidan verb'],
    '声': ['こえ', 'voice', 'noun'],
    '外': ['そと', 'outside', 'noun'],
    '大きい': ['おおきい', 'big', 'い-adjective'],
    '女性': ['じょせい', 'woman', 'noun'],
    '男性': ['だんせい', 'man', 'noun'],
    '男': ['おとこ', 'man, male', 'noun'],
    '妻': ['つま', '(my) wife', 'noun'],
    '姿': ['すがた', 'figure, appearance (スーツ姿: dressed in a suit)', 'noun'],
    '子供': ['こども', 'child', 'noun'],
    '字': ['じ', 'handwriting; written character', 'noun'],
    '小学校': ['しょうがっこう', 'elementary school', 'noun'],
    '山': ['やま', 'mountain; heap', 'noun'],
    '帽子': ['ぼうし', 'hat', 'noun'],
    '店員さん': ['てんいんさん', 'shop / café staff', 'noun'],
    '庭': ['にわ', 'garden, yard', 'noun'],
    '弟': ['おとうと', '(my) younger brother', 'noun'],
    '強い': ['つよい', 'strong', 'い-adjective'],
    '弾く': ['ひく', 'to play (piano, guitar)', 'う-verb'],
    '弾き始める': ['ひきはじめる', 'to start playing', 'ichidan verb'],
    '彼': ['かれ', 'he, him', 'pronoun'],
    '彼女': ['かのじょ', 'she, her', 'pronoun'],
    '後': ['ご', 'after, later (一週間後: a week later)', 'suffix'],
    '思わず': ['おもわず', 'without meaning to, couldn\'t help (but)', 'adverb'],
    '懐かしい': ['なつかしい', 'dear, nostalgic, long-missed', 'い-adjective'],
    '手': ['て', 'hand', 'noun'],
    '撮る': ['とる', 'to take (a photo), to film', 'う-verb'],
    '料理': ['りょうり', 'cooking, dish', 'noun'],
    '昔': ['むかし', 'long ago, the old days', 'noun'],
    '時': ['とき', 'time; when', 'noun'],
    '晩': ['ばん', 'evening', 'noun'],
    '暖かい': ['あたたかい', 'warm', 'い-adjective'],
    '曲': ['きょく', 'piece of music, song', 'noun'],
    '最後': ['さいご', 'the end, the last', 'noun'],
    '本物': ['ほんもの', 'the real thing, genuine', 'noun'],
    '来月': ['らいげつ', 'next month', 'noun'],
    '横': ['よこ', 'side, beside', 'noun'],
    '残る': ['のこる', 'to remain, to be left', 'う-verb'],
    '毎年': ['まいとし', 'every year', 'noun'],
    '毎晩': ['まいばん', 'every evening', 'noun'],
    '毎週': ['まいしゅう', 'every week', 'noun'],
    '気': ['き', 'feeling, mind (気がする: have a feeling)', 'noun'],
    '気まずい': ['きまずい', 'awkward, embarrassing', 'い-adjective'],
    '水': ['みず', 'water', 'noun'],
    '泣く': ['なく', 'to cry', 'う-verb'],
    '演奏': ['えんそう', 'musical performance', 'noun'],
    '照れる': ['てれる', 'to be shy, to be embarrassed', 'ichidan verb'],
    '父': ['ちち', '(my) father', 'noun'],
    '犬': ['いぬ', 'dog', 'noun'],
    '現れる': ['あらわれる', 'to appear, to show up', 'ichidan verb'],
    '目': ['め', 'eye', 'noun'],
    '目指す': ['めざす', 'to aim for', 'う-verb'],
    '真っ白': ['まっしろ', 'pure white', 'な-adjective'],
    '着る': ['きる', 'to wear (clothes on the body)', 'ichidan verb'],
    '瞬間': ['しゅんかん', 'moment, instant', 'noun'],
    '石': ['いし', 'stone', 'noun'],
    '答える': ['こたえる', 'to answer', 'ichidan verb'],
    '結婚': ['けっこん', 'marriage, wedding', 'noun'],
    '緑': ['みどり', 'green', 'noun'],
    '黒い': ['くろい', 'black', 'い-adjective'],
    '置く': ['おく', 'to put, to place', 'う-verb'],
    '聞こえる': ['きこえる', 'to be heard, can hear', 'ichidan verb'],
    '花': ['はな', 'flower', 'noun'],
    '花束': ['はなたば', 'bouquet', 'noun'],
    '落ち込む': ['おちこむ', 'to feel down, to be depressed', 'う-verb'],
    '褒める': ['ほめる', 'to praise', 'ichidan verb'],
    '言葉': ['ことば', 'word(s)', 'noun'],
    '話題': ['わだい', 'topic; (話題になる) to become the talk of the town', 'noun'],
    '誰': ['だれ', 'who; (誰か) someone; (誰でも) anyone', 'pronoun'],
    '諦める': ['あきらめる', 'to give up', 'ichidan verb'],
    '譲る': ['ゆずる', 'to give up (something) for someone, to let someone have', 'う-verb'],
    '載せる': ['のせる', 'to post, to put up (online)', 'ichidan verb'],
    '近所': ['きんじょ', 'neighbourhood', 'noun'],
    '迷う': ['まよう', 'to hesitate, to be unable to decide', 'う-verb'],
    '通る': ['とおる', 'to pass by, to go through', 'う-verb'],
    '遠く': ['とおく', 'far away', 'noun'],
    '適当': ['てきとう', 'random, careless (also: suitable)', 'な-adjective'],
    '選手': ['せんしゅ', 'player, athlete', 'noun'],
    '金曜日': ['きんようび', 'Friday', 'noun'],
    '鍵盤': ['けんばん', 'keyboard, keys (of a piano)', 'noun'],
    '開ける': ['あける', 'to open (something)', 'ichidan verb'],
    '間違える': ['まちがえる', 'to get wrong, to make a mistake', 'ichidan verb'],
    '隣': ['となり', 'next to, beside', 'noun'],
    '雪': ['ゆき', 'snow', 'noun'],
    '雪だるま': ['ゆきだるま', 'snowman', 'noun'],
    '顔': ['かお', 'face', 'noun'],
    '飲む': ['のむ', 'to drink', 'う-verb'],
    '黙る': ['だまる', 'to be silent (黙って: without a word)', 'う-verb'],
    '鼻': ['はな', 'nose', 'noun'],
  };

  global.STORIES_DATA = [
    // ── N5 ──────────────────────────────────────────────────────────────────
    {
      id: 'n5-tanaka-morning',
      level: 'n5',
      title: '田中[たなか]さんの朝[あさ]',
      titleEn: 'Tanaka-san\'s Morning',
      sentences: [
        { jp: '田中[たなか]さん は 会社員[かいしゃいん] です 。', en: 'Tanaka-san is an office worker.',
          grammar: ['wa-topic:田中さんは', 'desu:会社員です'] },
        { jp: '毎朝[まいあさ] 六時[ろくじ] に 起[お]きます>起きる 。', en: 'She gets up at six every morning.',
          grammar: ['ni-time:六時に', 'masu:起きます'] },
        { jp: '朝[あさ]ご飯[はん] は パン と コーヒー です 。', en: 'Breakfast is bread and coffee.',
          grammar: ['wa-topic:朝ご飯は', 'to-and:パンとコーヒー'] },
        { jp: 'それから 、 電車[でんしゃ] で 会社[かいしゃ] に 行[い]きます>行く 。', en: 'Then she goes to the office by train.',
          grammar: ['de-means:電車で', 'ni-destination:会社に行きます'] },
        { jp: '電車[でんしゃ] は いつも 人[ひと] が 多[おお]い です 。', en: 'The train is always crowded.',
          grammar: ['wa-ga:電車はいつも人が多い', 'i-adj-desu:多いです'] },
        { jp: '田中[たなか]さん は 電車[でんしゃ] の 中[なか] で 本[ほん] を 読[よ]みます>読む 。', en: 'Tanaka-san reads a book on the train.',
          grammar: ['no-possessive:電車の中', 'de-place:中で', 'wo-object:本を読みます'] },
        { jp: '昨日[きのう] は 雨[あめ] でした>です 。', en: 'Yesterday it rained.',
          grammar: ['deshita:雨でした'] },
        { jp: 'でも 、 傘[かさ] が ありませんでした>ある 。', en: 'But she didn\'t have an umbrella.',
          grammar: ['ga-subject:傘が', 'masen-deshita:ありませんでした'] },
        { jp: '駅[えき] で 新[あたら]しい 傘[かさ] を 買[か]いました>買う 。', en: 'She bought a new umbrella at the station.',
          grammar: ['de-place:駅で', 'i-adj-noun:新しい傘', 'masu-past:買いました'] },
        { jp: '青[あお]くて>青い きれい な 傘[かさ] です 。', en: 'It is a pretty blue umbrella.',
          grammar: ['kute:青くて', 'na-adj-noun:きれいな傘'] },
        { jp: '田中[たなか]さん は その 傘[かさ] が とても 好[す]き です 。', en: 'Tanaka-san likes that umbrella very much.',
          grammar: ['kosoado:その傘', 'ga-suki:傘がとても好き'] },
      ],
    },
    {
      id: 'n5-weekend-shopping',
      level: 'n5',
      title: '週末[しゅうまつ]の買[か]い物[もの]',
      titleEn: 'Weekend Shopping',
      sentences: [
        { jp: '土曜日[どようび] 、 友[とも]だち と デパート へ 行[い]きました>行く 。', en: 'On Saturday, I went to a department store with a friend.',
          grammar: ['to-with:友だちと', 'he-direction:デパートへ', 'masu-past:行きました'] },
        { jp: '私[わたし] は 新[あたら]しい セーター が 欲[ほ]しかった>欲しい です 。', en: 'I wanted a new sweater.',
          grammar: ['hoshii:セーターが欲しかった', 'i-adj-past:欲しかったです'] },
        { jp: '三階[さんがい] に 服[ふく] の 店[みせ] が たくさん あります>ある 。', en: 'On the third floor there are lots of clothes shops.',
          grammar: ['ni-aru:三階に服の店がたくさんあります', 'no-possessive:服の店'] },
        { jp: '赤[あか]い セーター と 白[しろ]い セーター が ありました>ある 。', en: 'There was a red sweater and a white sweater.',
          grammar: ['i-adj-noun:赤いセーター', 'to-and:赤いセーターと白いセーター', 'masu-past:ありました'] },
        { jp: '「 この 赤[あか]い セーター は いくら です か 。 」', en: '"How much is this red sweater?"',
          grammar: ['kosoado:この', 'ka-question:いくらですか'] },
        { jp: '「 五千円[ごせんえん] です 。 」', en: '"It\'s 5,000 yen."',
          grammar: ['desu:五千円です'] },
        { jp: 'ちょっと 高[たか]かった>高い です が 、 とても かわいかった>かわいい です 。', en: 'It was a little expensive, but it was very cute.',
          grammar: ['i-adj-past:高かったです', 'ga-but:高かったですが'] },
        { jp: 'だから 、 その セーター を 買[か]いました>買う 。', en: 'So I bought that sweater.',
          grammar: ['dakara:だから', 'wo-object:セーターを買いました'] },
        { jp: 'それから 、 二人[ふたり] で 喫茶店[きっさてん] に 入[はい]って>入る 、 ケーキ を 食[た]べました>食べる 。', en: 'After that, the two of us went into a café and ate cake.',
          grammar: ['de-together:二人で', 'te-sequence:入って、ケーキを食べました'] },
        { jp: '友[とも]だち は 「 また 来週[らいしゅう] 来[き]ましょう>来る 。 」 と 言[い]いました>言う 。', en: 'My friend said, "Let\'s come again next week."',
          grammar: ['mashou:来ましょう', 'to-iu:と言いました'] },
        { jp: '楽[たの]しい 一日[いちにち] でした>です 。', en: 'It was a fun day.',
          grammar: ['i-adj-noun:楽しい一日', 'deshita:一日でした'] },
      ],
    },
    {
      id: 'n5-tama-the-cat',
      level: 'n5',
      title: '猫[ねこ]のタマ',
      titleEn: 'Tama the Cat',
      sentences: [
        { jp: '私[わたし] の 家[いえ] に は 猫[ねこ] が います>いる 。', en: 'There is a cat at my house.',
          grammar: ['ni-wa:家には', 'ni-aru:猫がいます'] },
        { jp: '名前[なまえ] は タマ です 。', en: 'Her name is Tama.',
          grammar: ['wa-topic:名前は', 'desu:タマです'] },
        { jp: 'タマ は 白[しろ]くて>白い 小[ちい]さい 猫[ねこ] です 。', en: 'Tama is a small white cat.',
          grammar: ['kute:白くて', 'i-adj-noun:小さい猫'] },
        { jp: 'タマ は 魚[さかな] が 大好[だいす]き です 。', en: 'Tama loves fish.',
          grammar: ['ga-suki:魚が大好き'] },
        { jp: '毎日[まいにち] 、 窓[まど] の 近[ちか]く で 寝[ね]て>寝る います>いる 。', en: 'Every day, she sleeps near the window.',
          grammar: ['no-possessive:窓の近く', 'te-iru:寝ています'] },
        { jp: 'でも 、 夜[よる] は とても 元気[げんき] です 。', en: 'But at night she is very lively.',
          grammar: ['wa-topic:夜は', 'desu:元気です'] },
        { jp: '部屋[へや] の 中[なか] を 走[はし]ったり>走る 、 私[わたし] の 足[あし] で 遊[あそ]んだり>遊ぶ します>する 。', en: 'She does things like running around the room and playing with my feet.',
          grammar: ['tari:走ったり、私の足で遊んだりします', 'de-means:足で'] },
        { jp: '昨日[きのう] 、 タマ は 机[つくえ] の 上[うえ] の ペン を 落[お]としました>落とす 。', en: 'Yesterday, Tama knocked the pen on the desk onto the floor.',
          grammar: ['no-possessive:机の上のペン', 'masu-past:落としました'] },
        { jp: '「 タマ 、 だめ です よ 。 」', en: '"Tama, you mustn\'t do that!"',
          grammar: ['yo:だめですよ'] },
        { jp: 'でも 、 タマ は 何[なに] も 言[い]いません>言う 。', en: 'But Tama doesn\'t say anything.',
          grammar: ['nani-mo-neg:何も言いません', 'masen:言いません'] },
        { jp: 'タマ は 私[わたし] の 一番[いちばん] の 友[とも]だち です 。', en: 'Tama is my best friend.',
          grammar: ['ichiban:一番の友だち'] },
      ],
    },

    {
      id: 'n5-first-sushi',
      level: 'n5',
      title: 'はじめての回転寿司[かいてんずし]',
      titleEn: 'Mike\'s First Conveyor-Belt Sushi',
      sentences: [
        { jp: '先週[せんしゅう] 、 アメリカ から 友[とも]だち の マイク が 来[き]ました>来る 。', en: 'Last week, my friend Mike came from America.',
          grammar: ['kara-from:アメリカから', 'no-possessive:友だちのマイク', 'masu-past:来ました'] },
        { jp: '私[わたし] たち は 駅[えき] の 近[ちか]く の 回転寿司[かいてんずし] に 行[い]きました>行く 。', en: 'We went to a conveyor-belt sushi restaurant near the station.',
          grammar: ['no-possessive:駅の近くの回転寿司', 'ni-destination:回転寿司に行きました'] },
        { jp: 'お皿[さら] が ゆっくり 前[まえ] を 通[とお]ります>通る 。', en: 'Plates slowly pass by in front of you.',
          grammar: ['wo-path:前を通ります'] },
        { jp: 'マイク は 「 すごい ！ 」 と 言[い]って>言う 、 たくさん 写真[しゃしん] を 撮[と]りました>撮る 。', en: 'Mike said "Amazing!" and took lots of photos.',
          grammar: ['to-iu:と言って', 'te-sequence:言って、たくさん写真を撮りました'] },
        { jp: '赤[あか]い お皿[さら] は 百円[ひゃくえん] 、 黒[くろ]い お皿[さら] は 五百円[ごひゃくえん] です 。', en: 'Red plates are 100 yen, and black plates are 500 yen.',
          grammar: ['wa-contrast:赤いお皿は百円、黒いお皿は五百円', 'i-adj-noun:赤いお皿'] },
        { jp: 'ある お皿[さら] の 上[うえ] に 、 小[ちい]さい 緑[みどり] の 山[やま] が ありました>ある 。', en: 'On one plate, there was a little green mountain.',
          grammar: ['ni-aru:お皿の上に、小さい緑の山がありました'] },
        { jp: '「 これ は 何[なん]>何(なん) です か 。 アボカド です か 。 」', en: '"What\'s this? Is it avocado?"',
          grammar: ['ka-question:何ですか', 'ka-question:アボカドですか'] },
        { jp: '私[わたし] が 「 あ 、 それ は … 」 と 言[い]う 前[まえ] に 、 マイク は 全部[ぜんぶ] 食[た]べました>食べる 。', en: 'Before I could say "Oh, that\'s…", Mike ate the whole thing.',
          grammar: ['mae-ni:言う前に', 'masu-past:食べました'] },
        { jp: 'マイク の 顔[かお] が 赤[あか]く>赤い なりました>なる 。', en: 'Mike\'s face turned red.',
          grammar: ['ku-naru:赤くなりました'] },
        { jp: 'それ は わさび でした>です 。', en: 'It was wasabi.',
          grammar: ['deshita:わさびでした'] },
        { jp: 'マイク は 水[みず] を 三杯[さんばい] 飲[の]んで>飲む 、 「 日本[にほん] の アボカド は 強[つよ]い です ね 。 」 と 言[い]いました>言う 。', en: 'Mike drank three glasses of water and said, "Japanese avocado sure is strong, huh."',
          grammar: ['te-sequence:飲んで、', 'ne:強いですね'] },
      ],
    },
    {
      id: 'n5-snowman',
      level: 'n5',
      title: '雪[ゆき]だるまのユキオ',
      titleEn: 'Yukio the Snowman',
      sentences: [
        { jp: '朝[あさ] 、 窓[まど] を 開[あ]けました>開ける 。', en: 'In the morning, I opened the window.',
          grammar: ['wo-object:窓を開けました'] },
        { jp: '外[そと] は 真[ま]っ白[しろ] でした>です 。 雪[ゆき] です ！', en: 'Outside, everything was white. Snow!',
          grammar: ['deshita:真っ白でした'] },
        { jp: '私[わたし] は 弟[おとうと] と 庭[にわ] で 大[おお]きい 雪[ゆき]だるま を 作[つく]りました>作る 。', en: 'My little brother and I made a big snowman in the garden.',
          grammar: ['to-with:弟と', 'de-place:庭で', 'i-adj-noun:大きい雪だるま'] },
        { jp: '目[め] は 石[いし] で 、 鼻[はな] は にんじん です 。', en: 'Its eyes are stones, and its nose is a carrot.',
          grammar: ['de-and:石で、', 'wa-contrast:目は石で、鼻はにんじん'] },
        { jp: '父[ちち] の 古[ふる]い 帽子[ぼうし] も かぶせました>かぶせる 。', en: 'We put Dad\'s old hat on it, too.',
          grammar: ['mo-also:帽子もかぶせました'] },
        { jp: '弟[おとうと] は 雪[ゆき]だるま に 「 ユキオ 」 と いう>言う 名前[なまえ] を つけました>つける 。', en: 'My brother gave the snowman the name "Yukio".',
          grammar: ['to-iu-name:「ユキオ」という名前'] },
        { jp: '次[つぎ] の 日[ひ] は とても 暖[あたた]かかった>暖かい です 。', en: 'The next day was very warm.',
          grammar: ['i-adj-past:暖かかったです'] },
        { jp: '庭[にわ] に は 帽子[ぼうし] と にんじん と 石[いし] しか ありませんでした>ある 。', en: 'In the garden, there was nothing but the hat, the carrot and the stones.',
          grammar: ['ni-wa:庭には', 'shika-nai:石しかありませんでした'] },
        { jp: '弟[おとうと] は 泣[な]きました>泣く 。', en: 'My brother cried.',
          grammar: ['masu-past:泣きました'] },
        { jp: '父[ちち] は 「 ユキオ は 山[やま] の 家[いえ] に 帰[かえ]った>帰る よ 。 また 冬[ふゆ] に 来[く]る よ 。 」 と 言[い]いました>言う 。', en: 'Dad said, "Yukio went back to his house in the mountains. He\'ll come again in winter."',
          grammar: ['plain-form:帰ったよ', 'yo:来るよ'] },
        { jp: '弟[おとうと] は 今[いま] も 毎年[まいとし] 冬[ふゆ] を 待[ま]って>待つ います>いる 。', en: 'Even now, my brother waits for winter every year.',
          grammar: ['te-iru:待っています'] },
      ],
    },
    // ── N4 ──────────────────────────────────────────────────────────────────
    {
      id: 'n4-first-trip',
      level: 'n4',
      title: '初[はじ]めての日本[にほん]旅行[りょこう]',
      titleEn: 'My First Trip to Japan',
      sentences: [
        { jp: '去年[きょねん] の 春[はる] 、 私[わたし] は 初[はじ]めて 日本[にほん] へ 行[い]きました>行く 。', en: 'Last spring, I went to Japan for the first time.',
          grammar: ['no-possessive:去年の春', 'he-direction:日本へ行きました'] },
        { jp: '日本[にほん] へ 行[い]った>行く こと が なかった>ない ので 、 とても 楽[たの]しみ でした>です 。', en: 'I had never been to Japan, so I was really looking forward to it.',
          grammar: ['ta-koto-ga-aru:行ったことがなかった', 'node:なかったので'] },
        { jp: '東京[とうきょう] に 着[つ]いて>着く 、 まず 浅草[あさくさ] の お寺[てら] を 見[み]>見る に 行[い]きました>行く 。', en: 'When I arrived in Tokyo, I first went to see the temple in Asakusa.',
          grammar: ['te-sequence:着いて、', 'ni-iku-purpose:見に行きました'] },
        { jp: '人[ひと] が 多[おお]すぎて>多すぎる 、 なかなか 前[まえ] に 進[すす]めませんでした>進む 。', en: 'There were too many people, and I could hardly move forward.',
          grammar: ['sugiru:多すぎて', 'nakanaka-neg:なかなか前に進めませんでした', 'potential:進めませんでした'] },
        { jp: '道[みち] が わからなくなって>わかる 、 近[ちか]く に いた>いる おじいさん に 聞[き]きました>聞く 。', en: 'I lost my way, so I asked an old man who was nearby.',
          grammar: ['naku-naru:わからなくなって', 'relative-clause:近くにいたおじいさん'] },
        { jp: 'おじいさん は 親切[しんせつ] に 駅[えき] まで 連[つ]れて>連れる 行[い]って>行く くれました>くれる 。', en: 'The old man kindly took me all the way to the station.',
          grammar: ['na-adverb:親切に', 'made:駅まで', 'te-kureru:連れて行ってくれました'] },
        { jp: '日本語[にほんご] で 「 ありがとうございます 」 と 言[い]えて>言う 、 うれしかった>うれしい です 。', en: 'I was happy that I could say "thank you" in Japanese.',
          grammar: ['de-means:日本語で', 'potential:言えて', 'te-reason:言えて、うれしかった'] },
        { jp: '夜[よる] は ホテル の 近[ちか]く で ラーメン を 食[た]べました>食べる 。', en: 'In the evening, I ate ramen near the hotel.',
          grammar: ['de-place:近くで', 'masu-past:食べました'] },
        { jp: '熱[あつ]くて>熱い 、 少[すこ]し 舌[した] を やけど して>する しまいました>しまう 。', en: 'It was so hot that I burned my tongue a little.',
          grammar: ['kute:熱くて', 'te-shimau:やけどしてしまいました'] },
        { jp: 'でも 、 今[いま] まで 食[た]べた>食べる ラーメン の 中[なか] で 一番[いちばん] おいしかった>おいしい です 。', en: 'But it was the most delicious ramen I have ever eaten.',
          grammar: ['relative-clause:今まで食べたラーメン', 'no-naka-de-ichiban:ラーメンの中で一番おいしかった'] },
        { jp: 'また 日本[にほん] に 行[い]ける>行く よう に 、 今[いま] 毎日[まいにち] 日本語[にほんご] を 勉強[べんきょう] して>する います>いる 。', en: 'So that I can go to Japan again, I am now studying Japanese every day.',
          grammar: ['potential:行ける', 'you-ni:行けるように', 'te-iru:勉強しています'] },
      ],
    },
    {
      id: 'n4-rainy-promise',
      level: 'n4',
      title: '雨[あめ]の日[ひ]の約束[やくそく]',
      titleEn: 'A Rainy-Day Promise',
      sentences: [
        { jp: '日曜日[にちようび] に 、 友[とも]だち の ケン と 公園[こうえん] で テニス を する 約束[やくそく] を しました>する 。', en: 'I made plans to play tennis in the park with my friend Ken on Sunday.',
          grammar: ['no-possessive:友だちのケン', 'relative-clause:テニスをする約束'] },
        { jp: 'でも 、 朝[あさ] 起[お]きたら>起きる 、 雨[あめ] が 降[ふ]って>降る いました>いる 。', en: 'But when I got up in the morning, it was raining.',
          grammar: ['tara:起きたら', 'te-iru:降っていました'] },
        { jp: '「 これ じゃ 、 テニス は できない>できる 。 」 と 思[おも]いました>思う 。', en: 'I thought, "We can\'t play tennis like this."',
          grammar: ['potential:できない', 'to-omou:と思いました'] },
        { jp: 'ケン に 電話[でんわ] を かけよう>かける と 思[おも]った>思う とき 、 ケン から メッセージ が 来[き]ました>来る 。', en: 'Just as I was about to call Ken, a message came from him.',
          grammar: ['volitional-to-omou:かけようと思った', 'toki:思ったとき', 'kara-from:ケンから'] },
        { jp: '「 雨[あめ] だ から 、 テニス は やめて>やめる 、 映画[えいが] を 見[み]>見る に 行[い]かない>行く ？ 」', en: '"It\'s raining, so how about we skip tennis and go see a movie?"',
          grammar: ['kara-reason:雨だから', 'ni-iku-purpose:見に行かない', 'nai-invitation:行かない？'] },
        { jp: '私[わたし] は すぐ 「 いい ね 。 」 と 返事[へんじ] を しました>する 。', en: 'I replied right away, "Sounds good."',
          grammar: ['ne:いいね'] },
        { jp: '映画館[えいがかん] へ 行[い]く 前[まえ] に 、 洗濯物[せんたくもの] を 中[なか] に 入[い]れなければ>入れる なりませんでした>なる 。', en: 'Before going to the cinema, I had to bring the laundry inside.',
          grammar: ['mae-ni:行く前に', 'nakereba-naranai:入れなければなりませんでした'] },
        { jp: '急[いそ]いで>急ぐ 家[いえ] を 出[で]た>出る ので 、 傘[かさ] を 忘[わす]れて>忘れる しまいました>しまう 。', en: 'I left the house in a hurry, so I forgot my umbrella.',
          grammar: ['node:出たので', 'te-shimau:忘れてしまいました'] },
        { jp: '駅[えき] に 着[つ]く と 、 ケン が 傘[かさ] を 二本[にほん] 持[も]って>持つ 待[ま]って>待つ いました>いる 。', en: 'When I got to the station, Ken was waiting, holding two umbrellas.',
          grammar: ['to-conditional:着くと', 'te-iru:待っていました'] },
        { jp: '「 たぶん 忘[わす]れる と 思[おも]った>思う よ 。 」 と ケン は 笑[わら]いました>笑う 。', en: '"I figured you\'d probably forget," Ken laughed.',
          grammar: ['to-omou:忘れると思った', 'yo:思ったよ'] },
        { jp: '雨[あめ] の 日[ひ] でも>でも(even) 、 いい 友[とも]だち が いれば>いる 楽[たの]しい です 。', en: 'Even on a rainy day, it\'s fun if you have a good friend.',
          grammar: ['demo-even:日でも', 'ba-conditional:いれば'] },
      ],
    },
    {
      id: 'n4-grandmas-letter',
      level: 'n4',
      title: 'おばあちゃんの手紙[てがみ]',
      titleEn: 'Grandma\'s Letter',
      sentences: [
        { jp: '先週[せんしゅう] 、 田舎[いなか] に 住[す]んで>住む いる 祖母[そぼ] から 手紙[てがみ] が 届[とど]きました>届く 。', en: 'Last week, a letter arrived from my grandmother, who lives in the countryside.',
          grammar: ['te-iru:住んでいる', 'relative-clause:田舎に住んでいる祖母', 'kara-from:祖母から'] },
        { jp: '祖母[そぼ] は もう 八十歳[はちじゅっさい] です が 、 毎日[まいにち] 畑[はたけ] で 野菜[やさい] を 育[そだ]てて>育てる います>いる 。', en: 'My grandmother is already eighty, but she grows vegetables in her field every day.',
          grammar: ['ga-but:八十歳ですが', 'te-iru:育てています'] },
        { jp: '手紙[てがみ] に は 「 元気[げんき] に して>する います>いる か 。 」 と 書[か]いて>書く ありました>ある 。', en: 'The letter said, "Are you keeping well?"',
          grammar: ['ni-wa:手紙には', 'te-aru:書いてありました'] },
        { jp: '箱[はこ] の 中[なか] に は 、 祖母[そぼ] が 作[つく]った>作る トマト が 入[はい]って>入る いました>いる 。', en: 'Inside the box were tomatoes that my grandmother had grown.',
          grammar: ['relative-clause:祖母が作ったトマト', 'te-iru:入っていました'] },
        { jp: 'とても 赤[あか]くて>赤い 、 おいし>おいしい そう でした>です 。', en: 'They were very red and looked delicious.',
          grammar: ['kute:赤くて', 'sou-looks:おいしそうでした'] },
        { jp: '私[わたし] は 音楽[おんがく] を 聞[き]き>聞く ながら 、 トマト で サラダ を 作[つく]りました>作る 。', en: 'I made a salad with the tomatoes while listening to music.',
          grammar: ['nagara:聞きながら', 'de-means:トマトで'] },
        { jp: '母[はは] は 「 おばあちゃん に お礼[れい] の 手紙[てがみ] を 書[か]いて>書く あげて>あげる 。 」 と 言[い]いました>言う 。', en: 'My mother said, "Write grandma a thank-you letter."',
          grammar: ['te-ageru:書いてあげて', 'te-request:あげて。'] },
        { jp: '夜[よる] 、 祖母[そぼ] に 長[なが]い 手紙[てがみ] を 書[か]きました>書く 。', en: 'That night, I wrote my grandmother a long letter.',
          grammar: ['i-adj-noun:長い手紙', 'masu-past:書きました'] },
        { jp: '学校[がっこう] の こと や 友[とも]だち の こと を たくさん 書[か]きました>書く 。', en: 'I wrote a lot about school, my friends and so on.',
          grammar: ['ya-and:学校のことや友だちのこと'] },
        { jp: '最後[さいご]に 「 夏休[なつやす]み に 会[あ]い>会う に 行[い]きます>行く 。 」 と 書[か]きました>書く 。', en: 'At the end, I wrote, "I\'ll come to see you in the summer holidays."',
          grammar: ['ni-iku-purpose:会いに行きます', 'to-iu:と書きました'] },
        { jp: '祖母[そぼ] が 喜[よろこ]んで>喜ぶ くれる と いい な>な(feeling) と 思[おも]います>思う 。', en: 'I hope she\'ll be pleased.',
          grammar: ['te-kureru:喜んでくれる', 'to-ii:くれるといいな', 'to-omou:と思います'] },
      ],
    },

    {
      id: 'n4-time-capsule',
      level: 'n4',
      title: 'タイムカプセル',
      titleEn: 'The Time Capsule',
      sentences: [
        { jp: '小学校[しょうがっこう] を 卒業[そつぎょう] する 時[とき] 、 クラス の みんな で タイムカプセル を 埋[う]めました>埋める 。', en: 'When we graduated from elementary school, the whole class buried a time capsule.',
          grammar: ['toki:卒業する時', 'de-together:みんなで'] },
        { jp: '「 二十歳[はたち] に なったら>なる 、 一緒[いっしょ] に 開[あ]けよう>開ける 」 と 約束[やくそく] しました>する 。', en: 'We promised: "When we turn twenty, let\'s open it together."',
          grammar: ['tara:なったら', 'volitional:開けよう'] },
        { jp: '先月[せんげつ] 、 その 日[ひ] が やっと 来[き]ました>来る 。', en: 'Last month, that day finally came.',
          grammar: ['kosoado:その日'] },
        { jp: '久[ひさ]しぶり に 学校[がっこう] へ 行[い]く と 、 懐[なつ]かしい 顔[かお] が たくさん ありました>ある 。', en: 'When I went to the school for the first time in years, there were lots of familiar faces.',
          grammar: ['to-conditional:行くと'] },
        { jp: '箱[はこ] の 中[なか] から 、 私[わたし] が 書[か]いた>書く 手紙[てがみ] が 出[で]て>出る きました>くる 。', en: 'Out of the box came the letter I had written.',
          grammar: ['relative-clause:私が書いた手紙', 'te-kuru:出てきました'] },
        { jp: '手紙[てがみ] に は 下手[へた] な 字[じ] で 、 こう 書[か]いて>書く ありました>ある 。', en: 'In clumsy handwriting, it said:',
          grammar: ['na-adj-noun:下手な字', 'te-aru:書いてありました'] },
        { jp: '「 二十歳[はたち] の 私[わたし] へ 。 サッカー 選手[せんしゅ] に なりました>なる か 。 」', en: '"To me at twenty: Did you become a soccer player?"',
          grammar: ['ni-naru:選手になりました', 'ka-question:なりましたか'] },
        { jp: '私[わたし] は 思[おも]わず 笑[わら]って>笑う しまいました>しまう 。', en: 'I couldn\'t help laughing.',
          grammar: ['te-shimau:笑ってしまいました'] },
        { jp: '今[いま] は レストラン で 料理[りょうり] を 作[つく]る 仕事[しごと] を して>する います>いる 。', en: 'These days I work as a cook in a restaurant.',
          grammar: ['relative-clause:料理を作る仕事', 'te-iru:しています'] },
        { jp: 'でも 、 手紙[てがみ] の 最後[さいご] に は 、 もう 一[ひと]つ 書[か]いて>書く ありました>ある 。', en: 'But at the end of the letter, there was one more thing.',
          grammar: ['ni-wa:最後には', 'te-aru:書いてありました'] },
        { jp: '「 もし 選手[せんしゅ] に なって>なる いなくて>いる も 、 好[す]き な こと を して>する いれば>いる 、 それ で いい よ 。 」', en: '"Even if you didn\'t become a player, as long as you\'re doing something you love, that\'s fine."',
          grammar: ['te-mo:なっていなくても', 'ba-conditional:していれば', 'na-adj-noun:好きなこと'] },
        { jp: '十歳[じゅっさい] の 自分[じぶん] に 、 少[すこ]し 褒[ほ]められた>褒める 気[き] が しました>する 。', en: 'I felt as if my ten-year-old self had praised me a little.',
          grammar: ['passive:自分に、少し褒められた', 'ki-ga-suru:気がしました'] },
      ],
    },
    {
      id: 'n4-wrong-number',
      level: 'n4',
      title: 'まちがい電話[でんわ]',
      titleEn: 'The Wrong Number',
      sentences: [
        { jp: '毎晩[まいばん] 七時[しちじ] に 、 知[し]らない>知る おばあさん から 電話[でんわ] が かかって>かかる きます>くる 。', en: 'Every evening at seven, I get a call from an old woman I don\'t know.',
          grammar: ['relative-clause:知らないおばあさん', 'te-kuru:かかってきます'] },
        { jp: '「 もしもし 、 タカシ ？ ご飯[はん] は ちゃんと 食[た]べて>食べる いる ？ 」', en: '"Hello, Takashi? Are you eating properly?"',
          grammar: ['plain-form:食べている？', 'te-iru:食べている'] },
        { jp: '私[わたし] の 名前[なまえ] は タカシ で は ありません>ある 。', en: 'My name isn\'t Takashi.',
          grammar: ['dewa-arimasen:タカシではありません'] },
        { jp: '最初[さいしょ] の 日[ひ] 、 「 番号[ばんごう] を 間違[まちが]えて>間違える います>いる よ 」 と 言[い]おう>言う と 思[おも]いました>思う 。', en: 'On the first day, I was going to tell her, "You\'ve got the wrong number."',
          grammar: ['te-iru:間違えています', 'volitional-to-omou:言おうと思いました'] },
        { jp: 'でも 、 おばあさん の 声[こえ] が とても うれし>うれしい そう だった>だ ので 、 言[い]えません>言う でした>です 。', en: 'But her voice sounded so happy that I couldn\'t say it.',
          grammar: ['sou-looks:うれしそう', 'node:だったので', 'potential:言えませんでした'] },
        { jp: 'それから 、 私[わたし] は 毎晩[まいばん] タカシ に なって>なる 、 おばあさん と 話[はな]す よう に なりました>なる 。', en: 'From then on, I became Takashi every evening and started chatting with her.',
          grammar: ['ni-naru:タカシになって', 'you-ni-naru:話すようになりました'] },
        { jp: '庭[にわ] の 花[はな] の こと 、 近所[きんじょ] の 犬[いぬ] の こと 、 昔[むかし] の こと 。', en: 'About the flowers in her garden, the neighbour\'s dog, the old days.',
          grammar: ['no-koto:花のこと'] },
        { jp: 'ある>ある(certain) 日[ひ] 、 電話[でんわ] が かかって>かかる きません>くる でした>です 。', en: 'Then one day, the call didn\'t come.',
          grammar: ['masen-deshita:きませんでした'] },
        { jp: '次[つぎ] の 日[ひ] も 、 その 次[つぎ] の 日[ひ] も 来[き]ません>来る でした>です 。', en: 'Not the next day, nor the day after that.',
          grammar: ['mo-also:次の日も、その次の日も'] },
        { jp: '一週間[いっしゅうかん] 後[ご] 、 若[わか]い 男[おとこ] の 人[ひと] から 電話[でんわ] が ありました>ある 。', en: 'A week later, I got a call from a young man.',
          grammar: ['kara-from:人から'] },
        { jp: '「 本物[ほんもの] の タカシ です 。 祖母[そぼ] が 入院[にゅういん] して>する いて>いる 、 あなた に お礼[れい] を 言[い]いたい>言う と 言[い]って>言う います>いる 。 」', en: '"This is the real Takashi. My grandmother is in hospital, and she says she wants to thank you."',
          grammar: ['te-iru:入院していて', 'tai:言いたい', 'to-iu:と言っています'] },
        { jp: '「 祖母[そぼ] は 最初[さいしょ] から 知[し]って>知る いた>いる そう です 。 」', en: '"Apparently, she knew from the very beginning."',
          grammar: ['te-iru:知っていた', 'sou-hearsay:いたそうです'] },
      ],
    },
    // ── N3 ──────────────────────────────────────────────────────────────────
    {
      id: 'n3-lost-wallet',
      level: 'n3',
      title: 'なくした財布[さいふ]',
      titleEn: 'The Lost Wallet',
      sentences: [
        { jp: '先月[せんげつ] 、 仕事[しごと] の 帰[かえ]り に 財布[さいふ] を なくして>なくす しまった>しまう 。', en: 'Last month, I lost my wallet on the way home from work.',
          grammar: ['plain-form:しまった', 'te-shimau:なくしてしまった'] },
        { jp: '電車[でんしゃ] に 乗[の]る>乗る 前[まえ] は 、 確[たし]かに かばん の 中[なか] に あった>ある はず だ 。', en: 'Before I got on the train, it should definitely have been in my bag.',
          grammar: ['mae-ni:乗る前', 'hazu:あったはずだ'] },
        { jp: '家[いえ] に 帰[かえ]って>帰る から 気[き]が付[つ]いた>気が付く ので 、 本当[ほんとう]に 焦[あせ]った>焦る 。', en: 'I only noticed after I got home, so I really panicked.',
          grammar: ['te-kara:帰ってから', 'node:気が付いたので'] },
        { jp: 'お金[かね] は それほど 入[はい]って>入る いなかった>いる けれど 、 カード や 免許証[めんきょしょう] が 全部[ぜんぶ] 入[はい]って>入る いた>いる 。', en: 'There wasn\'t much money in it, but my cards, my driver\'s license — everything was in it.',
          grammar: ['sorehodo-neg:それほど入っていなかった', 'keredo:いなかったけれど', 'ya-and:カードや免許証'] },
        { jp: 'すぐ に 警察[けいさつ] に 届[とど]け を 出[だ]す>出す こと に した>する 。', en: 'I decided to file a report with the police right away.',
          grammar: ['koto-ni-suru:出すことにした'] },
        { jp: '次[つぎ] の 日[ひ] 、 知[し]らない>知る 番号[ばんごう] から 電話[でんわ] が かかって>かかる きた>くる 。', en: 'The next day, I got a call from a number I didn\'t know.',
          grammar: ['relative-clause:知らない番号', 'te-kuru:かかってきた'] },
        { jp: '駅員[えきいん] に よる と 、 私[わたし] の 財布[さいふ] が 駅[えき] の ベンチ で 見[み]つかった>見つかる そう だ 。', en: 'According to the station staff, my wallet had been found on a bench at the station.',
          grammar: ['ni-yoru-to:駅員によると', 'sou-hearsay:見つかったそうだ'] },
        { jp: '親切[しんせつ] な 人[ひと] に 拾[ひろ]われて>拾う 、 駅[えき] に 届[とど]けられた>届ける らしい 。', en: 'Apparently a kind person picked it up and handed it in at the station.',
          grammar: ['passive:人に拾われて', 'passive:届けられた', 'rashii:届けられたらしい'] },
        { jp: '財布[さいふ] を 受[う]け取[と]った>受け取る とき 、 中身[なかみ] は 何[なに] も なくなって>なくなる いなかった>いる 。', en: 'When I got the wallet back, nothing inside was missing.',
          grammar: ['toki:受け取ったとき', 'nani-mo-neg:何もなくなっていなかった'] },
        { jp: '世[よ]の中[なか] は 悪[わる]い 人[ひと] ばかり で は ない と 、 改[あらた]めて 感[かん]じた>感じる 。', en: 'It made me feel once again that the world isn\'t full of bad people.',
          grammar: ['bakari-dewanai:悪い人ばかりではない', 'to-omou:ないと、改めて感じた'] },
        { jp: 'それ 以来[いらい] 、 落[お]とし物[もの] を 見[み]つけたら>見つける 、 必[かなら]ず 届[とど]ける よう に して>する いる 。', en: 'Since then, whenever I find a lost item, I make sure to hand it in.',
          grammar: ['tara:見つけたら', 'you-ni-suru:届けるようにしている'] },
      ],
    },
    {
      id: 'n3-town-bakery',
      level: 'n3',
      title: '町[まち]の小[ちい]さなパン屋[や]',
      titleEn: 'The Little Bakery in Town',
      sentences: [
        { jp: '駅前[えきまえ] に 小[ちい]さな パン屋[や] が ある 。', en: 'There is a small bakery in front of the station.',
          grammar: ['plain-form:ある', 'ni-aru:駅前に小さなパン屋がある'] },
        { jp: '店長[てんちょう] の 木村[きむら]さん は 、 毎朝[まいあさ] 四時[よじ] に 起[お]きて>起きる パン を 焼[や]く>焼く そう だ 。', en: 'I hear the owner, Kimura-san, gets up at four every morning to bake bread.',
          grammar: ['te-sequence:起きてパンを焼く', 'sou-hearsay:焼くそうだ'] },
        { jp: '若[わか]い ころ 、 木村[きむら]さん は パン の 作[つく]り方[かた] を 学[まな]ぶ ため に フランス へ 行[い]った>行く 。', en: 'When Kimura-san was young, they went to France to learn how to make bread.',
          grammar: ['kata:作り方', 'tame-ni:学ぶために'] },
        { jp: '最初[さいしょ] は フランス語[ご] が 全然[ぜんぜん] わからなかった>わかる が 、 だんだん 話[はな]せる>話す よう に なった>なる 。', en: 'At first they didn\'t understand any French, but they gradually became able to speak it.',
          grammar: ['zenzen-neg:全然わからなかった', 'potential:話せる', 'you-ni-naru:話せるようになった'] },
        { jp: '日本[にほん] に 戻[もど]って>戻る から 、 この 町[まち] に 自分[じぶん] の 店[みせ] を 開[ひら]いた>開く 。', en: 'After coming back to Japan, they opened their own shop in this town.',
          grammar: ['te-kara:戻ってから'] },
        { jp: '木村[きむら]さん の パン は 食[た]べれば>食べる 食[た]べる ほど 好[す]き に なる 味[あじ] だ 。', en: 'Kimura-san\'s bread has the kind of taste you like more the more you eat it.',
          grammar: ['ba-hodo:食べれば食べるほど', 'ni-naru:好きになる', 'relative-clause:好きになる味'] },
        { jp: '特[とく]に メロンパン は 人気[にんき] が あって>ある 、 昼[ひる] まで に 売[う]り切[き]れて>売り切れる しまう 。', en: 'The melon bread in particular is popular and sells out before noon.',
          grammar: ['made-ni:昼までに', 'te-shimau:売り切れてしまう'] },
        { jp: '最近[さいきん] 、 木村[きむら]さん は 息子[むすこ] に 店[みせ] を 手伝[てつだ]わせて>手伝う いる 。', en: 'Recently, Kimura-san has been having their son help out at the shop.',
          grammar: ['causative:息子に店を手伝わせて', 'te-iru:手伝わせている'] },
        { jp: '息子[むすこ]さん は まだ 失敗[しっぱい] して>する ばかり いる が 、 毎日[まいにち] 一生懸命[いっしょうけんめい] 練習[れんしゅう] して>する いる 。', en: 'The son still keeps making mistakes, but practises as hard as he can every day.',
          grammar: ['te-bakari:失敗してばかりいる', 'ga-but:いるが'] },
        { jp: '「 この 店[みせ] を 町[まち] の 人[ひと] に 長[なが]く 愛[あい]される>愛する 店[みせ] に し>する たい 」 と 木村[きむら]さん は 言[い]う>言う 。', en: '"I want to make this a shop that the people of this town will love for a long time," says Kimura-san.',
          grammar: ['passive:人に長く愛される', 'ni-suru:店にしたい', 'tai:したい'] },
        { jp: '私[わたし] も 、 この 店[みせ] が ずっと 続[つづ]く>続く こと を 願[ねが]って>願う いる 。', en: 'I also hope this shop will carry on for a long, long time.',
          grammar: ['koto-nominalizer:続くことを', 'te-iru:願っている'] },
      ],
    },
    {
      id: 'n3-station-piano',
      level: 'n3',
      title: '駅[えき]のピアノ',
      titleEn: 'The Station Piano',
      sentences: [
        { jp: '去年[きょねん] 、 うち の 駅[えき] に 、 誰[だれ] でも>でも(even) 弾[ひ]ける>弾く ピアノ が 置[お]かれた>置く 。', en: 'Last year, a piano that anyone can play was put in our station.',
          grammar: ['dare-demo:誰でも', 'potential:弾ける', 'passive:置かれた'] },
        { jp: '最初[さいしょ] は 、 子供[こども] が 適当[てきとう] に 鍵盤[けんばん] を たたく だけ だった>だ 。', en: 'At first, it was just kids randomly banging on the keys.',
          grammar: ['na-adverb:適当に', 'dake:たたくだけだった'] },
        { jp: 'ところが 、 ある>ある(certain) 晩[ばん] から 、 スーツ を 着[き]た>着る 男性[だんせい] が 毎日[まいにち] 弾[ひ]く>弾く よう に なった>なる 。', en: 'But from one evening on, a man in a suit started playing it every day.',
          grammar: ['relative-clause:スーツを着た男性', 'you-ni-naru:弾くようになった'] },
        { jp: '彼[かれ] は いつも 同[おな]じ 曲[きょく] を 一曲[いっきょく] だけ 弾[ひ]いて>弾く 、 電車[でんしゃ] が 来[く]る と 黙[だま]って>黙る 帰[かえ]って>帰る いく 。', en: 'He always plays just one piece, the same one, and when his train comes he leaves without a word.',
          grammar: ['dake:一曲だけ', 'to-conditional:来ると', 'te-iku:帰っていく'] },
        { jp: 'その 演奏[えんそう] を 誰[だれ] か が 撮[と]って>撮る ネット に 載[の]せた>載せる ところ 、 あっという間[ま]に 話題[わだい] に なった>なる 。', en: 'Someone filmed his playing and posted it online, and it became a hit in no time.',
          grammar: ['tokoro:載せたところ', 'ni-naru:話題になった'] },
        { jp: '彼[かれ] の 演奏[えんそう] を 聞[き]く ため に 、 遠[とお]く から 来[く]る 人[ひと] まで 現[あらわ]れた>現れる 。', en: 'People even started coming from far away just to hear him play.',
          grammar: ['tame-ni:聞くために', 'made-even:来る人まで'] },
        { jp: 'ある>ある(certain) 日[ひ] 、 私[わたし] は 勇気[ゆうき] を 出[だ]して>出す 、 なぜ 毎日[まいにち] 同[おな]じ 曲[きょく] を 弾[ひ]く>弾く の か 聞[き]いて>聞く みた>みる 。', en: 'One day, I worked up the courage to ask him why he played the same piece every day.',
          grammar: ['embedded-question:なぜ毎日同じ曲を弾くのか', 'te-miru:聞いてみた'] },
        { jp: '彼[かれ] は 少[すこ]し 照[て]れ>照れる ながら 、 こう 答[こた]えた>答える 。', en: 'Looking a little embarrassed, he answered:',
          grammar: ['nagara:照れながら'] },
        { jp: '「 昔[むかし] 、 ピアニスト を 目指[めざ]して>目指す いた>いる ん です が 、 手[て] を けが して>する 諦[あきら]めた>諦める ん です 。 」', en: '"I used to want to be a pianist, but I injured my hand and gave up."',
          grammar: ['n-desu:目指していたんです', 'te-reason:けがして諦めた'] },
        { jp: '「 この 曲[きょく] は 、 妻[つま] が 初[はじ]めて 褒[ほ]めて>褒める くれた>くれる 曲[きょく] な>な(copula) ん です 。 」', en: '"This is the first piece my wife ever praised."',
          grammar: ['te-kureru:褒めてくれた', 'relative-clause:妻が初めて褒めてくれた曲', 'n-desu:曲なんです'] },
        { jp: '「 リハビリ の ため に 弾[ひ]き始[はじ]めた>弾き始める ん です が 、 まさか こんな に 聞[き]いて>聞く もらえる>もらう と は 思[おも]いません>思う でした>です 。 」', en: '"I started playing it as rehab. I never dreamed so many people would listen."',
          grammar: ['tame-ni:リハビリのために', 'hajimeru:弾き始めた', 'te-morau:聞いてもらえる', 'masaka:まさかこんなに聞いてもらえるとは思いませんでした'] },
        { jp: '次[つぎ] の 日[ひ] 、 ピアノ の 上[うえ] に は 、 誰[だれ] か が 置[お]いた>置く 小[ちい]さな 花束[はなたば] が あった>ある 。', en: 'The next day, on top of the piano, there was a small bouquet that someone had left.',
          grammar: ['ni-wa:上には', 'relative-clause:誰かが置いた小さな花束'] },
      ],
    },
    {
      id: 'n3-last-slice',
      level: 'n3',
      title: '最後[さいご]のひとつ',
      titleEn: 'The Last Slice',
      sentences: [
        { jp: '会社[かいしゃ] の 近[ちか]く の 喫茶店[きっさてん] に は 、 一日[いちにち] 十個[じゅっこ] しか 作[つく]られない>作る チーズケーキ が ある 。', en: 'The café near my office has a cheesecake they only make ten of a day.',
          grammar: ['shika-nai:十個しか作られない', 'passive:作られない'] },
        { jp: '仕事[しごと] で 失敗[しっぱい] した>する 日[ひ] は 、 それ を 食[た]べる こと に して>する いる 。', en: 'On days when I mess up at work, I make a point of eating it.',
          grammar: ['relative-clause:仕事で失敗した日', 'koto-ni-shite-iru:食べることにしている'] },
        { jp: 'その 日[ひ] も 上司[じょうし] に 叱[しか]られて>叱る 、 落[お]ち込[こ]んで>落ち込む いた>いる 。', en: 'That day, too, I\'d been told off by my boss and was feeling down.',
          grammar: ['passive:上司に叱られて', 'te-iru:落ち込んでいた'] },
        { jp: '店[みせ] に 着[つ]いた>着く とき 、 ケース の 中[なか] に は ケーキ が あと 一[ひと]つ だけ 残[のこ]って>残る いた>いる 。', en: 'When I got to the café, there was just one cake left in the case.',
          grammar: ['toki:着いたとき', 'dake:一つだけ', 'te-iru:残っていた'] },
        { jp: '「 これ を ください 」 と 言[い]った>言う 瞬間[しゅんかん] 、 隣[となり] から まったく 同[おな]じ 言葉[ことば] が 聞[き]こえた>聞こえる 。', en: 'The moment I said "This one, please," I heard exactly the same words from right beside me.',
          grammar: ['shunkan:言った瞬間'] },
        { jp: '横[よこ] を 見[み]る と 、 スーツ 姿[すがた] の 女性[じょせい] が 気[き]まず>気まずい そう に 笑[わら]って>笑う いた>いる 。', en: 'I looked over, and a woman in a suit was smiling awkwardly.',
          grammar: ['to-conditional:見ると', 'sou-looks:気まずそうに', 'te-iru:笑っていた'] },
        { jp: '譲[ゆず]ろう>譲る か と 迷[まよ]って>迷う いる と 、 店員[てんいん]さん が 「 半分[はんぶん] に しましょう>する か 」 と 言[い]って>言う くれた>くれる 。', en: 'While I was wondering whether to let her have it, the waiter said, "Shall I cut it in half?"',
          grammar: ['you-ka-to:譲ろうかと迷っている', 'mashou:しましょうか', 'te-kureru:言ってくれた'] },
        { jp: 'こうして 、 知[し]らない>知る 人[ひと] と 一[ひと]つ の ケーキ を 分[わ]ける>分ける こと に なった>なる 。', en: 'And so I ended up sharing one cake with a complete stranger.',
          grammar: ['relative-clause:知らない人', 'koto-ni-naru:分けることになった'] },
        { jp: '話[はな]して>話す みる と 、 彼女[かのじょ] も 今日[きょう] 仕事[しごと] で ミス を した>する ばかり だ と いう>言う 。', en: 'When we got talking, it turned out she had also just made a mistake at work that day.',
          grammar: ['te-miru:話してみる', 'ta-bakari:したばかりだ', 'to-iu:だという'] },
        { jp: '半分[はんぶん] の ケーキ は いつも より 小[ちい]さい はず な>な(copula) のに 、 なぜ か いつも より おいしく>おいしい 感[かん]じた>感じる 。', en: 'Half a cake should have been smaller than usual, yet somehow it tasted better than ever.',
          grammar: ['yori:いつもより', 'hazu:小さいはず', 'noni:はずなのに'] },
        { jp: 'それ から 毎週[まいしゅう] 金曜日[きんようび] 、 私[わたし] たち は その 店[みせ] で 会[あ]う よう に なった>なる 。', en: 'After that, we started meeting at that café every Friday.',
          grammar: ['you-ni-naru:会うようになった'] },
        { jp: '来月[らいげつ] 、 その 喫茶店[きっさてん] で 、 私[わたし] たち の 小[ちい]さな 結婚[けっこん] パーティー を 開[ひら]く こと に なって>なる いる 。', en: 'Next month, we\'re holding our small wedding party at that very café.',
          grammar: ['koto-ni-naru:開くことになっている'] },
      ],
    },
  ];
})(window);
