(function (global) {
  'use strict';

  // JLPT vocabulary lists (N5-N3) for the Vocabulary hover reference page.
  //
  // Words use the same inline `kanji[reading]` markup as particles-data.js's
  // sentences — one bracket per contiguous kanji run, covering okurigana too
  // (e.g. "食[た]べる"). Unlike particles-data.js, the run also allows 々 so
  // repeated-kanji words like 時々[ときどき] parse correctly. Each word is
  // written once and expanded into three display forms: kanji-only text
  // (e.g. "食べる"), kana-only text (e.g. "たべる"), and furigana ruby HTML.
  function parseVocabWord(word) {
    const kanji = word.replace(/([一-鿿々]+)\[([^\]]+)\]/g, '$1');
    const kana = word.replace(/([一-鿿々]+)\[([^\]]+)\]/g, '$2');
    const html = word.replace(/([一-鿿々]+)\[([^\]]+)\]/g, '<ruby>$1<rp>(</rp><rt>$2</rt><rp>)</rp></ruby>');
    return { kanji, kana, html };
  }

  const RAW_VOCAB = {
    n5: [
      { word: '私[わたし]', meaning: 'I, me' },
      { word: 'あなた', meaning: 'You' },
      { word: '彼[かれ]', meaning: 'He' },
      { word: '彼女[かのじょ]', meaning: 'She' },
      { word: '友達[ともだち]', meaning: 'Friend' },
      { word: '先生[せんせい]', meaning: 'Teacher' },
      { word: '学生[がくせい]', meaning: 'Student' },
      { word: '会社員[かいしゃいん]', meaning: 'Company employee' },
      { word: '医者[いしゃ]', meaning: 'Doctor' },
      { word: '学校[がっこう]', meaning: 'School' },
      { word: '図書館[としょかん]', meaning: 'Library' },
      { word: '病院[びょういん]', meaning: 'Hospital' },
      { word: '郵便局[ゆうびんきょく]', meaning: 'Post office' },
      { word: '銀行[ぎんこう]', meaning: 'Bank' },
      { word: '駅[えき]', meaning: 'Station' },
      { word: '家[いえ]', meaning: 'House, home' },
      { word: '部屋[へや]', meaning: 'Room' },
      { word: '教室[きょうしつ]', meaning: 'Classroom' },
      { word: '会社[かいしゃ]', meaning: 'Company' },
      { word: '店[みせ]', meaning: 'Shop, store' },
      { word: '今日[きょう]', meaning: 'Today' },
      { word: '明日[あした]', meaning: 'Tomorrow' },
      { word: '昨日[きのう]', meaning: 'Yesterday' },
      { word: '今[いま]', meaning: 'Now' },
      { word: '毎日[まいにち]', meaning: 'Every day' },
      { word: '朝[あさ]', meaning: 'Morning' },
      { word: '昼[ひる]', meaning: 'Noon, daytime' },
      { word: '晩[ばん]', meaning: 'Evening' },
      { word: '夜[よる]', meaning: 'Night' },
      { word: '時間[じかん]', meaning: 'Time' },
      { word: '週末[しゅうまつ]', meaning: 'Weekend' },
      { word: '食[た]べ物[もの]', meaning: 'Food' },
      { word: '飲[の]み物[もの]', meaning: 'Drink' },
      { word: 'ご飯[はん]', meaning: 'Rice, meal' },
      { word: '水[みず]', meaning: 'Water' },
      { word: 'お茶[ちゃ]', meaning: 'Tea' },
      { word: '魚[さかな]', meaning: 'Fish' },
      { word: '肉[にく]', meaning: 'Meat' },
      { word: 'パン', meaning: 'Bread' },
      { word: 'りんご', meaning: 'Apple' },
      { word: '車[くるま]', meaning: 'Car' },
      { word: '自転車[じてんしゃ]', meaning: 'Bicycle' },
      { word: '電車[でんしゃ]', meaning: 'Train' },
      { word: '飛行機[ひこうき]', meaning: 'Airplane' },
      { word: 'バス', meaning: 'Bus' },
      { word: '道[みち]', meaning: 'Road, street' },
      { word: '天気[てんき]', meaning: 'Weather' },
      { word: '雨[あめ]', meaning: 'Rain' },
      { word: '雪[ゆき]', meaning: 'Snow' },
      { word: '音楽[おんがく]', meaning: 'Music' },
      { word: '映画[えいが]', meaning: 'Movie' },
      { word: '新聞[しんぶん]', meaning: 'Newspaper' },
      { word: '辞書[じしょ]', meaning: 'Dictionary' },
      { word: 'かばん', meaning: 'Bag' },
      { word: '傘[かさ]', meaning: 'Umbrella' },
      { word: '時計[とけい]', meaning: 'Clock, watch' },
      { word: '財布[さいふ]', meaning: 'Wallet' },
      { word: '写真[しゃしん]', meaning: 'Photo' },
      { word: '電話[でんわ]', meaning: 'Telephone' },
      { word: 'テレビ', meaning: 'Television' },
      { word: '仕事[しごと]', meaning: 'Work, job' },
      { word: '名前[なまえ]', meaning: 'Name' },
      { word: '誕生日[たんじょうび]', meaning: 'Birthday' },
      { word: 'お金[かね]', meaning: 'Money' },
      { word: '猫[ねこ]', meaning: 'Cat' },
      { word: '犬[いぬ]', meaning: 'Dog' },
      { word: '花[はな]', meaning: 'Flower' },
      { word: '木[き]', meaning: 'Tree' },
      { word: '山[やま]', meaning: 'Mountain' },
      { word: '川[かわ]', meaning: 'River' },
      { word: '海[うみ]', meaning: 'Sea' },
      { word: '空[そら]', meaning: 'Sky' },
      { word: '人[ひと]', meaning: 'Person' },
      { word: '子供[こども]', meaning: 'Child' },
      { word: '男[おとこ]', meaning: 'Man' },
      { word: '女[おんな]', meaning: 'Woman' },
      { word: '父[ちち]', meaning: 'Father' },
      { word: '母[はは]', meaning: 'Mother' },
      { word: '兄[あに]', meaning: 'Older brother' },
      { word: '姉[あね]', meaning: 'Older sister' },
      { word: '弟[おとうと]', meaning: 'Younger brother' },
      { word: '妹[いもうと]', meaning: 'Younger sister' },
      { word: '家族[かぞく]', meaning: 'Family' },
      { word: '食[た]べる', meaning: 'To eat' },
      { word: '飲[の]む', meaning: 'To drink' },
      { word: '見[み]る', meaning: 'To see, watch' },
      { word: '聞[き]く', meaning: 'To listen, ask' },
      { word: '話[はな]す', meaning: 'To speak' },
      { word: '読[よ]む', meaning: 'To read' },
      { word: '書[か]く', meaning: 'To write' },
      { word: '行[い]く', meaning: 'To go' },
      { word: '来[く]る', meaning: 'To come' },
      { word: '帰[かえ]る', meaning: 'To return, go home' },
      { word: 'する', meaning: 'To do' },
      { word: 'ある', meaning: 'To exist (things)' },
      { word: 'いる', meaning: 'To exist (people, animals)' },
      { word: '分[わ]かる', meaning: 'To understand' },
      { word: 'できる', meaning: 'To be able to, can do' },
      { word: '買[か]う', meaning: 'To buy' },
      { word: '会[あ]う', meaning: 'To meet' },
      { word: '起[お]きる', meaning: 'To wake up' },
      { word: '寝[ね]る', meaning: 'To sleep' },
      { word: '休[やす]む', meaning: 'To rest' },
      { word: '働[はたら]く', meaning: 'To work' },
      { word: '勉強[べんきょう]する', meaning: 'To study' },
      { word: '待[ま]つ', meaning: 'To wait' },
      { word: '入[はい]る', meaning: 'To enter' },
      { word: '出[で]る', meaning: 'To exit, leave' },
      { word: '座[すわ]る', meaning: 'To sit' },
      { word: '立[た]つ', meaning: 'To stand' },
      { word: '歩[ある]く', meaning: 'To walk' },
      { word: '走[はし]る', meaning: 'To run' },
      { word: '使[つか]う', meaning: 'To use' },
      { word: '作[つく]る', meaning: 'To make' },
      { word: '持[も]つ', meaning: 'To hold, carry' },
      { word: '大[おお]きい', meaning: 'Big' },
      { word: '小[ちい]さい', meaning: 'Small' },
      { word: '新[あたら]しい', meaning: 'New' },
      { word: '古[ふる]い', meaning: 'Old' },
      { word: '高[たか]い', meaning: 'Expensive, tall' },
      { word: '安[やす]い', meaning: 'Cheap' },
      { word: 'いい', meaning: 'Good' },
      { word: '悪[わる]い', meaning: 'Bad' },
      { word: '暑[あつ]い', meaning: 'Hot (weather)' },
      { word: '寒[さむ]い', meaning: 'Cold (weather)' },
      { word: 'おいしい', meaning: 'Delicious' },
      { word: '面白[おもしろ]い', meaning: 'Interesting' },
      { word: '忙[いそが]しい', meaning: 'Busy' },
      { word: '難[むずか]しい', meaning: 'Difficult' },
      { word: '簡単[かんたん]', meaning: 'Easy, simple' },
      { word: '好[す]き', meaning: 'Likeable, favorite' },
      { word: 'きれい', meaning: 'Pretty, clean' },
      { word: '元気[げんき]', meaning: 'Healthy, energetic' },
    ],
    n4: [
      { word: '経験[けいけん]', meaning: 'Experience' },
      { word: '説明[せつめい]', meaning: 'Explanation' },
      { word: '質問[しつもん]', meaning: 'Question' },
      { word: '答[こた]え', meaning: 'Answer' },
      { word: '問題[もんだい]', meaning: 'Problem' },
      { word: '意味[いみ]', meaning: 'Meaning' },
      { word: '理由[りゆう]', meaning: 'Reason' },
      { word: '方法[ほうほう]', meaning: 'Method' },
      { word: '予定[よてい]', meaning: 'Plan, schedule' },
      { word: '用事[ようじ]', meaning: 'Errand, business' },
      { word: '準備[じゅんび]', meaning: 'Preparation' },
      { word: '生活[せいかつ]', meaning: 'Life, living' },
      { word: '最近[さいきん]', meaning: 'Recently' },
      { word: '最初[さいしょ]', meaning: 'First, beginning' },
      { word: '最後[さいご]', meaning: 'Last, end' },
      { word: '一度[いちど]', meaning: 'Once' },
      { word: '時々[ときどき]', meaning: 'Sometimes' },
      { word: '全部[ぜんぶ]', meaning: 'All, everything' },
      { word: '少[すこ]し', meaning: 'A little' },
      { word: 'たくさん', meaning: 'A lot, many' },
      { word: 'もちろん', meaning: 'Of course' },
      { word: 'たぶん', meaning: 'Probably' },
      { word: 'きっと', meaning: 'Surely' },
      { word: 'だんだん', meaning: 'Gradually' },
      { word: '初[はじ]めて', meaning: 'For the first time' },
      { word: '返事[へんじ]', meaning: 'Reply' },
      { word: '約束[やくそく]', meaning: 'Promise' },
      { word: '相談[そうだん]', meaning: 'Consultation, discussion' },
      { word: '連絡[れんらく]', meaning: 'Contact' },
      { word: '紹介[しょうかい]', meaning: 'Introduction' },
      { word: '案内[あんない]', meaning: 'Guide, information' },
      { word: '招待[しょうたい]', meaning: 'Invitation' },
      { word: '利用[りよう]', meaning: 'Use, utilization' },
      { word: '用意[ようい]', meaning: 'Preparation' },
      { word: '参加[さんか]', meaning: 'Participation' },
      { word: '出席[しゅっせき]', meaning: 'Attendance' },
      { word: '欠席[けっせき]', meaning: 'Absence' },
      { word: '到着[とうちゃく]', meaning: 'Arrival' },
      { word: '出発[しゅっぱつ]', meaning: 'Departure' },
      { word: '出張[しゅっちょう]', meaning: 'Business trip' },
      { word: '旅行[りょこう]', meaning: 'Travel' },
      { word: '運転[うんてん]', meaning: 'Driving' },
      { word: '運動[うんどう]', meaning: 'Exercise' },
      { word: '散歩[さんぽ]', meaning: 'Walk, stroll' },
      { word: '料理[りょうり]', meaning: 'Cooking' },
      { word: '掃除[そうじ]', meaning: 'Cleaning' },
      { word: '洗濯[せんたく]', meaning: 'Laundry' },
      { word: '買[か]い物[もの]', meaning: 'Shopping' },
      { word: '引[ひ]っ越[こ]し', meaning: 'Moving house' },
      { word: '結婚[けっこん]', meaning: 'Marriage' },
      { word: '夫婦[ふうふ]', meaning: 'Married couple' },
      { word: '夫[おっと]', meaning: 'Husband' },
      { word: '妻[つま]', meaning: 'Wife' },
      { word: '赤[あか]ちゃん', meaning: 'Baby' },
      { word: '子育[こそだ]て', meaning: 'Child-rearing' },
      { word: '性格[せいかく]', meaning: 'Personality' },
      { word: '気分[きぶん]', meaning: 'Mood, feeling' },
      { word: '気持[きも]ち', meaning: 'Feeling' },
      { word: '心配[しんぱい]', meaning: 'Worry' },
      { word: '安心[あんしん]', meaning: 'Relief, peace of mind' },
      { word: '残念[ざんねん]', meaning: 'Regrettable, unfortunate' },
      { word: '必要[ひつよう]', meaning: 'Necessary' },
      { word: '大切[たいせつ]', meaning: 'Important' },
      { word: '大変[たいへん]', meaning: 'Tough, terrible' },
      { word: '親切[しんせつ]', meaning: 'Kind' },
      { word: '便利[べんり]', meaning: 'Convenient' },
      { word: '不便[ふべん]', meaning: 'Inconvenient' },
      { word: '危険[きけん]', meaning: 'Dangerous' },
      { word: '安全[あんぜん]', meaning: 'Safe' },
      { word: '特別[とくべつ]', meaning: 'Special' },
      { word: '普通[ふつう]', meaning: 'Normal, usual' },
      { word: '教育[きょういく]', meaning: 'Education' },
      { word: '試験[しけん]', meaning: 'Exam' },
      { word: '宿題[しゅくだい]', meaning: 'Homework' },
      { word: '成績[せいせき]', meaning: 'Grades' },
      { word: '入学[にゅうがく]', meaning: 'School entrance, admission' },
      { word: '卒業[そつぎょう]', meaning: 'Graduation' },
      { word: '就職[しゅうしょく]', meaning: 'Getting a job' },
      { word: '給料[きゅうりょう]', meaning: 'Salary' },
      { word: '値段[ねだん]', meaning: 'Price' },
      { word: '無料[むりょう]', meaning: 'Free of charge' },
      { word: '払[はら]う', meaning: 'To pay' },
      { word: '借[か]りる', meaning: 'To borrow' },
      { word: '貸[か]す', meaning: 'To lend' },
      { word: '返[かえ]す', meaning: 'To return (something)' },
      { word: '決[き]める', meaning: 'To decide' },
      { word: '決[き]まる', meaning: 'To be decided' },
      { word: '続[つづ]ける', meaning: 'To continue (something)' },
      { word: '続[つづ]く', meaning: 'To continue' },
      { word: '始[はじ]める', meaning: 'To begin (something)' },
      { word: '始[はじ]まる', meaning: 'To begin' },
      { word: '終[お]わる', meaning: 'To end' },
      { word: '変[か]える', meaning: 'To change (something)' },
      { word: '変[か]わる', meaning: 'To change' },
      { word: '気[き]づく', meaning: 'To notice' },
      { word: '慣[な]れる', meaning: 'To get used to' },
      { word: '比[くら]べる', meaning: 'To compare' },
      { word: '選[えら]ぶ', meaning: 'To choose' },
      { word: '探[さが]す', meaning: 'To search for' },
      { word: '見[み]つける', meaning: 'To find' },
    ],
    n3: [
      { word: '影響[えいきょう]', meaning: 'Influence' },
      { word: '原因[げんいん]', meaning: 'Cause' },
      { word: '結果[けっか]', meaning: 'Result' },
      { word: '効果[こうか]', meaning: 'Effect' },
      { word: '状態[じょうたい]', meaning: 'Condition, state' },
      { word: '状況[じょうきょう]', meaning: 'Situation' },
      { word: '場合[ばあい]', meaning: 'Case, situation' },
      { word: '可能性[かのうせい]', meaning: 'Possibility' },
      { word: '機会[きかい]', meaning: 'Opportunity' },
      { word: '機能[きのう]', meaning: 'Function' },
      { word: '制度[せいど]', meaning: 'System, institution' },
      { word: '制限[せいげん]', meaning: 'Restriction' },
      { word: '条件[じょうけん]', meaning: 'Condition, term' },
      { word: '対象[たいしょう]', meaning: 'Target, subject' },
      { word: '対応[たいおう]', meaning: 'Response, correspondence' },
      { word: '対策[たいさく]', meaning: 'Countermeasure' },
      { word: '政府[せいふ]', meaning: 'Government' },
      { word: '企業[きぎょう]', meaning: 'Corporation' },
      { word: '産業[さんぎょう]', meaning: 'Industry' },
      { word: '技術[ぎじゅつ]', meaning: 'Technology' },
      { word: '資源[しげん]', meaning: 'Resource' },
      { word: '資料[しりょう]', meaning: 'Materials, data' },
      { word: '情報[じょうほう]', meaning: 'Information' },
      { word: '知識[ちしき]', meaning: 'Knowledge' },
      { word: '能力[のうりょく]', meaning: 'Ability' },
      { word: '性質[せいしつ]', meaning: 'Nature, property' },
      { word: '特徴[とくちょう]', meaning: 'Characteristic' },
      { word: '印象[いんしょう]', meaning: 'Impression' },
      { word: '態度[たいど]', meaning: 'Attitude' },
      { word: '表現[ひょうげん]', meaning: 'Expression' },
      { word: '表情[ひょうじょう]', meaning: 'Facial expression' },
      { word: '感情[かんじょう]', meaning: 'Emotion' },
      { word: '感覚[かんかく]', meaning: 'Sense, feeling' },
      { word: '判断[はんだん]', meaning: 'Judgment' },
      { word: '評価[ひょうか]', meaning: 'Evaluation' },
      { word: '比較[ひかく]', meaning: 'Comparison' },
      { word: '分析[ぶんせき]', meaning: 'Analysis' },
      { word: '調査[ちょうさ]', meaning: 'Investigation, survey' },
      { word: '研究[けんきゅう]', meaning: 'Research' },
      { word: '発展[はってん]', meaning: 'Development' },
      { word: '発達[はったつ]', meaning: 'Development, growth' },
      { word: '成長[せいちょう]', meaning: 'Growth' },
      { word: '向上[こうじょう]', meaning: 'Improvement' },
      { word: '改善[かいぜん]', meaning: 'Improvement' },
      { word: '解決[かいけつ]', meaning: 'Solution, resolution' },
      { word: '解釈[かいしゃく]', meaning: 'Interpretation' },
      { word: '議論[ぎろん]', meaning: 'Discussion, argument' },
      { word: '主張[しゅちょう]', meaning: 'Assertion, claim' },
      { word: '意見[いけん]', meaning: 'Opinion' },
      { word: '考[かんが]える', meaning: 'To think, consider' },
      { word: '感[かん]じる', meaning: 'To feel' },
      { word: '悩[なや]む', meaning: 'To worry, be troubled' },
      { word: '努力[どりょく]する', meaning: 'To make an effort' },
      { word: '挑戦[ちょうせん]する', meaning: 'To challenge, attempt' },
      { word: '達成[たっせい]する', meaning: 'To achieve' },
      { word: '実現[じつげん]する', meaning: 'To realize, make happen' },
      { word: '成功[せいこう]する', meaning: 'To succeed' },
      { word: '失敗[しっぱい]する', meaning: 'To fail' },
      { word: '反対[はんたい]する', meaning: 'To oppose' },
      { word: '賛成[さんせい]する', meaning: 'To agree, approve' },
      { word: '含[ふく]む', meaning: 'To include' },
      { word: '避[さ]ける', meaning: 'To avoid' },
      { word: '防[ふせ]ぐ', meaning: 'To prevent' },
      { word: '支[ささ]える', meaning: 'To support' },
      { word: '保[たも]つ', meaning: 'To keep, maintain' },
      { word: '守[まも]る', meaning: 'To protect, keep (a promise)' },
      { word: '従[したが]う', meaning: 'To follow, obey' },
      { word: '争[あらそ]う', meaning: 'To fight, compete' },
      { word: '競争[きょうそう]する', meaning: 'To compete' },
      { word: '協力[きょうりょく]する', meaning: 'To cooperate' },
      { word: '提案[ていあん]する', meaning: 'To propose' },
      { word: '要求[ようきゅう]する', meaning: 'To demand, request' },
      { word: '求[もと]める', meaning: 'To seek, request' },
      { word: '満足[まんぞく]する', meaning: 'To be satisfied' },
      { word: '不満[ふまん]', meaning: 'Dissatisfaction' },
      { word: '信[しん]じる', meaning: 'To believe' },
      { word: '疑[うたが]う', meaning: 'To doubt' },
      { word: '確[たし]かめる', meaning: 'To make sure, verify' },
      { word: '訪[おとず]れる', meaning: 'To visit' },
      { word: '訪問[ほうもん]する', meaning: 'To visit (formal)' },
      { word: '移動[いどう]する', meaning: 'To move, relocate' },
      { word: '移[うつ]る', meaning: 'To move, shift' },
      { word: '移[うつ]す', meaning: 'To move (something)' },
      { word: '広[ひろ]がる', meaning: 'To spread, expand' },
      { word: '広[ひろ]げる', meaning: 'To spread (something)' },
      { word: '増[ふ]える', meaning: 'To increase' },
      { word: '増[ふ]やす', meaning: 'To increase (something)' },
      { word: '減[へ]る', meaning: 'To decrease' },
      { word: '減[へ]らす', meaning: 'To decrease (something)' },
      { word: '単純[たんじゅん]', meaning: 'Simple' },
      { word: '豊[ゆた]か', meaning: 'Abundant, rich' },
      { word: '確[たし]か', meaning: 'Certain, sure' },
      { word: '明[あき]らか', meaning: 'Clear, obvious' },
      { word: '様々[さまざま]', meaning: 'Various' },
      { word: '主[おも]な', meaning: 'Main, primary' },
      { word: '重要[じゅうよう]', meaning: 'Important' },
      { word: '一般的[いっぱんてき]', meaning: 'General' },
      { word: '具体的[ぐたいてき]', meaning: 'Concrete, specific' },
      { word: '積極的[せっきょくてき]', meaning: 'Proactive, positive' },
      { word: '効果的[こうかてき]', meaning: 'Effective' },
    ],
  };

  global.VOCAB_DATA = {};
  Object.keys(RAW_VOCAB).forEach(level => {
    global.VOCAB_DATA[level] = RAW_VOCAB[level].map(({ word, meaning }) => {
      const { kanji, kana, html } = parseVocabWord(word);
      return { kanji, kana, html, meaning };
    });
  });
})(window);
