#!/usr/bin/env node
// Build phrases-words.js from phrases-data.js and phrases-stories.js: every
// phrase and story line split into words (each linked to a dictionary entry)
// plus the grammar it uses, so tapping a sentence on a Phrases page can
// explain it word by word.
//
// Words come from jp_words.mjs (kuromoji + the site's glossaries), with
// phrase_extra_words.json for slogans, slang, names and the like, and
// phrase_whole_words.json for set phrases kuromoji would split apart.
// Grammar is found by the rules in jp_grammar.mjs and points at the Stories
// grammar notes (STORY_GRAMMAR) or at the few in GRAMMAR_EXTRA.
//
// Usage (kuromoji isn't a site dependency, so install it just for this):
//   npm install --no-save kuromoji
//   node scripts/tokenize_phrases.mjs [--misses]
// test_phrases.js fails when the phrases and this file drift apart.
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { ROOT, createWordFinder, loadSiteData } from './jp_words.mjs';
import { GRAMMAR_EXTRA, detectGrammar } from './jp_grammar.mjs';

const site = loadSiteData(['phrases-data.js', 'phrases-stories.js', 'stories-data.js', 'mystery-words.js', 'memes-data.js', 'memes-data-2.js']);
const { PHRASES_DATA, PHRASE_STORIES, STORY_GRAMMAR } = site;

const readJson = f => JSON.parse(readFileSync(path.join(ROOT, 'scripts', f), 'utf8'));
const { segment } = await createWordFinder({ extra: readJson('phrase_extra_words.json'), whole: readJson('phrase_whole_words.json') });

const GRAMMAR = { ...STORY_GRAMMAR, ...GRAMMAR_EXTRA };

// ─── Build ───────────────────────────────────────────────────────────────────

const gloss = {};
const grammarUsed = new Set();
const lines = {};
const misses = new Map();

function analyse(id, markup) {
  const { pieces, morphs, plain } = segment(markup);
  const words = [];
  pieces.forEach(({ src, key }) => {
    // Unknown single characters (a stray ー, a stutter) stay plain text.
    if (key && key.miss) {
      if (key.miss.length > 1) misses.set(key.miss, (misses.get(key.miss) || []).concat(id));
      words.push(src);
    } else if (key) {
      gloss[key[0]] = key[1];
      words.push([src, key[0]]);
    } else words.push(src);
  });
  // Join runs of plain (unlinked) text.
  const w = words.reduce((acc, t) => {
    if (typeof t === 'string' && typeof acc[acc.length - 1] === 'string') acc[acc.length - 1] += t;
    else acc.push(t);
    return acc;
  }, []);
  const g = detectGrammar(morphs, plain, GRAMMAR);
  g.forEach(([gid]) => grammarUsed.add(gid));
  lines[id] = { w, g };
}

for (const cat of PHRASES_DATA) {
  cat.phrases.forEach((p, i) => analyse(`${cat.id}:p${i}`, p.jp));
  const story = PHRASE_STORIES[cat.id];
  if (story) story.lines.forEach((l, i) => analyse(`${cat.id}:s${i}`, l[1]));
}

const sorted = o => Object.fromEntries(Object.keys(o).sort().map(k => [k, o[k]]));
const grammar = sorted(Object.fromEntries([...grammarUsed].map(id => [id, GRAMMAR[id]])));
const js = `// Generated by scripts/tokenize_phrases.mjs from phrases-data.js and
// phrases-stories.js — do not edit.
// PHRASE_WORDS.lines['<category>:p<n>'] (phrase n) or ['<category>:s<n>']
// (story line n) is { w, g }: w lists the sentence's pieces — a string is
// plain text, [markup, key] a word whose [reading, meaning, part of speech]
// is gloss[key] — and g lists its grammar as [id, snippet], explained in
// grammar[id].
(function (global) {
  'use strict';
  global.PHRASE_WORDS = ${JSON.stringify({ gloss: sorted(gloss), grammar, lines })};
})(typeof window !== 'undefined' ? window : globalThis);
`;
writeFileSync(path.join(ROOT, 'phrases-words.js'), js);
console.log(`${Object.keys(lines).length} sentences, ${Object.keys(gloss).length} words, ${grammarUsed.size} grammar points; ${misses.size} words not found`);
if (process.argv.includes('--misses')) [...misses].forEach(([k, ids]) => console.log(k, ids.length, ids[0]));
