#!/usr/bin/env node
// Build story-fill-words.js from story-fill-data.js: every passage split into
// words, each linked to a dictionary entry, so a tapped word on the Story
// Fill-in page can show its reading and meaning (as on the Stories page).
// The splitting and lookup live in jp_words.mjs, shared with the Phrases
// pages.
//
// Usage (kuromoji isn't a site dependency, so install it just for this):
//   npm install --no-save kuromoji
//   node scripts/tokenize_story_fill.mjs
// test_story_fill.js fails when the passages and this file drift apart.
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { ROOT, createWordFinder, loadSiteData } from './jp_words.mjs';

const { STORY_FILL_PASSAGES: PASSAGES } = loadSiteData(['story-fill-data.js']);

// Words neither list has (or has with a different sense): [reading, meaning, part of speech].
const EXTRA = JSON.parse(readFileSync(path.join(ROOT, 'scripts', 'story_fill_extra_words.json'), 'utf8'));

// Kuromoji splits these oddly in kana-heavy text; keep them whole.
const WHOLE = ['しゅみ', 'すきやき', 'てんぷら', 'ざんねん', 'スマートフォン', '自動販売機'];
const { segment } = await createWordFinder({ extra: EXTRA, whole: WHOLE });

const gloss = {};
const passages = {};
const misses = new Map();
for (const p of PASSAGES) {
  passages[p.id] = p.paragraphs.map(par => {
    const out = [];
    par.split(/(\{\d+\})/).forEach(seg => {
      if (!seg) return;
      if (/^\{\d+\}$/.test(seg)) { out.push(seg); return; }
      const { pieces } = segment(seg);
      pieces.forEach(({ src, key }) => {
        if (key && key.miss) {
          misses.set(key.miss, (misses.get(key.miss) || []).concat(p.id));
          out.push(src);
        } else if (key) {
          gloss[key[0]] = key[1];
          out.push([src, key[0]]);
        } else out.push(src);
      });
    });
    // Join runs of plain (unlinked) text.
    return out.reduce((acc, t) => {
      if (typeof t === 'string' && !/^\{\d+\}$/.test(t) && typeof acc[acc.length - 1] === 'string' && !/^\{\d+\}$/.test(acc[acc.length - 1])) acc[acc.length - 1] += t;
      else acc.push(t);
      return acc;
    }, []);
  });
}

const sortedGloss = Object.fromEntries(Object.keys(gloss).sort().map(k => [k, gloss[k]]));
const js = `// Generated by scripts/tokenize_story_fill.mjs from story-fill-data.js — do not edit.
// STORY_FILL_WORDS.passages[id] has each paragraph as a list of pieces: a
// string is plain text or a blank ({1}), [markup, key] is a word that can be
// tapped, and gloss[key] is its [reading, meaning, part of speech].
(function (global) {
  'use strict';
  global.STORY_FILL_WORDS = ${JSON.stringify({ gloss: sortedGloss, passages })};
})(typeof window !== 'undefined' ? window : globalThis);
`;
writeFileSync(path.join(ROOT, 'story-fill-words.js'), js);
const missList = [...misses].sort((a, b) => b[1].length - a[1].length);
console.log(`${Object.keys(sortedGloss).length} words; ${missList.length} not found`);
if (process.argv.includes('--misses')) missList.forEach(([k, ids]) => console.log(k, ids.length, ids[0]));
